ArNetworking: changeMapOnServer.cpp File Reference
changeMapOnServer.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
Functions
void gotConfig (void)
int main (int argc, char **argv)
Variables
ArClientBase * client
ArClientHandlerConfig * configHandler
bool done = false
std::string newmapname
Function Documentation
void gotConfig (void)
References done, ArConfig::findSection(), ArClientHandlerConfig::getConfig(), ArClientHandlerConfig::lock(), newmapname, ArClientHandlerConfig::saveConfigToServer(), ArConfigArg::setString(), ArUtil::sleep(), and ArClientHandlerConfig::unlock().
Referenced by main().
int main (int argc, char ** argv)
References ArClientHandlerConfig::addGotConfigCB(), ArArgumentParser::checkHelpAndWarnUnparsed(), ArArgumentParser::checkParameterArgument(), ArClientSimpleConnector::connectClient(), done, Aria::exit(), ArClientBase::getHost(), gotConfig(), Aria::init(), ArArgumentParser::loadDefaultArguments(), Aria::logOptions(), newmapname, Aria::parseArgs(), ArClientHandlerConfig::requestConfigFromServer(), ArClientBase::runAsync(), ArClientBase::setRobotName(), and ArUtil::sleep().
Variable Documentation
ArClientBase* client
Examples:
drawingsExample.cpp, drawingsExampleWithRobot.cpp, getVideoExample.cpp, ptzCameraClientExample.cpp, and robotUpdateExample.cpp.
Referenced by ArClientDeleteFileOnServer::ArClientDeleteFileOnServer(), ArClientFileLister::ArClientFileLister(), ArHybridForwarderVideo::ArHybridForwarderVideo(), ArServerBase::close(), ArServerBase::closeConnectionID(), ArServerBase::finishAcceptingSocket(), ArClientSwitchManager::getConfigDisplayHint(), ArServerModeJogPosition::getDriveAction(), ArServerBase::getRequestTransactionCount(), ArServerFileFromClient::internalPutFile(), ArServerBase::logConnections(), ArServerBase::loopOnce(), main(), ArServerBase::processPacket(), ArCentralManager::remCycleCallback(), ArServerModeRatioDrive::remDrivingBackwardsCallback(), ArServerBase::remTooManyClientsCB(), ArClientHandlerRobotUpdate::RobotData::RobotData(), ArServerHandlerMap::sendMapWithMaxCategory(), ArServerHandlerMap::serverGetMap(), ArServerHandlerMap::serverGetMapBinary(), ArServerMode::setStatus(), ArServerHandlerCommands::setTextServer(), ArServerBase::slowIdleCallback(), and Circle::~Circle().
ArClientHandlerConfig* configHandler
Referenced by main().
bool done = false
Referenced by gotConfig(), main(), and ArClientFileFromClient::netPutFile().
std::string newmapname
Referenced by gotConfig(), and main().