ArNetworking: ArClientHandlerConfig Class Reference
ArClientHandlerConfig Class Reference
Client handler for receiving and updating ArConfig data via ArNetworking.
#include <ArClientHandlerConfig.h>
Public Member Functions
void addGotConfigCB (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a gotConfig callback.
void addGotConfigDefaultsCB (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a got config defaults callback.
void addGotLastEditablePriorityCB (ArFunctor *functor, int position=50)
Adds callback invoked when the last editable priority packet is received.
void addSaveConfigFailedCB (ArFunctor1< const char * > *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a save config to server failed callback.
void addSaveConfigSucceededCB (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a save config to server succeeded callback.
ArClientHandlerConfig (ArClientBase *client, bool ignoreBounds=false, const char *robotName=NULL, const char *logPrefix=NULL)
Constructor.
bool canRequestDefaults (void)
Sees if we can request defaults (both types)
ArConfig * getConfig (void)
Unthreadsafe way to get the config to play with (see long docs)
ArConfig getConfigCopy (void)
Threadsafe way to get the config to play with.
ArConfig * getDefaultConfig ()
Returns a pointer to the robot server's default configuration, if canRequestDefaults() is true.
ArPriority::Priority getLastEditablePriority ()
Returns the last editable priority of the config.
void handleGetConfig (ArNetPacket *packet)
Handles the packet from the getConfig.
void handleGetConfigBySections (ArNetPacket *packet)
Handles the packet from the GetConfigBySections.
void handleGetConfigBySectionsV2 (ArNetPacket *packet)
Handles the packet from the GetConfigBySectionsV2.
void handleGetConfigBySectionsV3 (ArNetPacket *packet)
Handles the packet from the GetConfigBySectionsV3.
void handleGetConfigBySectionsV4 (ArNetPacket *packet)
Handles the packet from the GetConfigBySectionsV4.
void handleGetConfigDefaults (ArNetPacket *packet)
Handles the return packet from getConfigDefaults.
void handleGetConfigSectionFlags (ArNetPacket *packet)
Handles the packet from the GetConfigSectionFlags.
void handleGetLastEditablePriority (ArNetPacket *packet)
Handles the return packet from getLastEditablePriority.
void handleSetConfig (ArNetPacket *packet)
Handles the return packet from the setConfig (saveConfigToServer)
void handleSetConfigBySections (ArNetPacket *packet)
Handles the return packet from the setConfigBySections (saveConfigToServer)
void handleSetConfigBySectionsV2 (ArNetPacket *packet)
Handles the return packet from the setConfigBySectionsV2 (saveConfigToServer)
bool haveGottenConfig (void)
Returns true if config gotten.
bool haveGottenDefaults (void)
Returns if we've gotten our requested defaults.
bool haveGottenLastEditablePriority ()
Returns whether the last editable priority has been received from the server.
bool haveRequestedDefaults (void)
Returns if we've requested some defaults.
bool isLastEditablePriorityAvailable ()
Returns whether the server supports the last editable priority request.
int lock (void)
Locks the config for if you're using the unthreadsafe getConfig.
void reloadConfigOnServer (void)
Tells the server to reload the configuration.
void remGotConfigCB (ArFunctor *functor)
Removes a gotConfig callback.
void remGotConfigDefaultsCB (ArFunctor *functor)
Removes a got config defaults callback.
void remGotLastEditablePriorityCB (ArFunctor *functor)
Removes the specified callback from the list of last editable priority callbacks.
void remSaveConfigFailedCB (ArFunctor1< const char * > *functor)
Removes a save config to server failed callback.
void remSaveConfigSucceededCB (ArFunctor *functor)
Removes a save config to server succeeded callback.
bool requestConfigDefaults (void)
Requests defaults for all sections from the server; modifies the config.
void requestConfigFromServer (void)
Requests the config from the server.
bool requestDefaultConfigFromServer (void)
bool requestLastEditablePriorityFromServer ()
Requests the last editable priority from the server.
bool requestSectionDefaults (const char *section)
Requests defaults for one section from the server; modifies the config.
void saveConfigToServer (void)
Sends the config back to the server.
void saveConfigToServer (ArConfig *config, const std::set< std::string, ArStrCaseCmpOp > *ignoreTheseSections=NULL)
Sends the config back to the server.
void setQuiet (bool isQuiet)
Turn on this flag to reduce the number of verbose log messages.
int tryLock (void)
Try to lock for the config for if you're using the unthreadsafe getConfig.
int unlock (void)
Unlocks the config for if you're using the unthreadsafe getConfig.
virtual ~ArClientHandlerConfig (void)
Destructor.
Protected Member Functions
void handleGetConfigData (ArNetPacket *packet, bool isMultiplePackets, int version)
Protected Attributes
ArMutex myCallbackMutex
ArClientBase * myClient
ArConfig myConfig
ArMutex myDataMutex
ArConfig * myDefaultConfig
std::list< ArFunctor * > myGotConfigCBList
std::list< ArFunctor * > myGotConfigDefaultsCBList
ArCallbackList myGotLastEditablePriorityCBList
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetConfigBySectionsCB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetConfigBySectionsV2CB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetConfigBySectionsV3CB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetConfigBySectionsV4CB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetConfigCB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetConfigDefaultsCB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetConfigSectionFlagsCB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetDefaultConfigCB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetLastEditablePriorityCB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleSetConfigBySectionsCB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleSetConfigBySectionsV2CB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleSetConfigCB
bool myHaveGottenConfig
bool myHaveGottenDefaults
bool myHaveGottenLastEditablePriority
bool myHaveRequestedConfig
bool myHaveRequestedDefaultCopy
bool myHaveRequestedDefaults
bool myHaveRequestedLastEditablePriority
bool myIsQuiet
ArPriority::Priority myLastEditablePriority
std::string myLogPrefix
std::string myRobotName
std::list< ArFunctor1< const
char * > * > mySaveConfigFailedCBList
std::list< ArFunctor * > mySaveConfigSucceededCBList
Detailed Description
Client handler for receiving and updating ArConfig data via ArNetworking.
ArClientHandlerConfig processes the network packets that describe a robot's ArConfig. It also provides a means to save the modified configuration data to the robot server. This class is designed to work in conjunction with the ArServerHandlerConfig. See the server handler documentation for a complete description of the networking interface.
This class should be thread safe, with the exception of unThreadSafeGetConfig. (If you want to use this method, surround it with calls to lock() and unlock().)
Note that you can't add callbacks or remove callbacks from within a callback function.
Constructor & Destructor Documentation
ArClientHandlerConfig::ArClientHandlerConfig (ArClientBase * client, bool ignoreBounds = false, const char * robotName = NULL, const char * logPrefix = NULL)
Constructor.
Parameters:
client the client base to attach to
ignoreBounds whether the ArConfig we have should ignore bounds or not, this should only be used for debugging
robotName a name or identifier for the robot the server is controlling, used for logging etc.
References myCallbackMutex, myConfig, myDataMutex, myLogPrefix, myRobotName, ArConfig::setConfigName(), and ArMutex::setLogName().
ArClientHandlerConfig::~ArClientHandlerConfig (void) [virtual]
Destructor.
References myDefaultConfig.
Member Function Documentation
void ArClientHandlerConfig::addGotConfigCB (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a gotConfig callback.
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, myGotConfigCBList, ArLog::Terse, and ArMutex::unlock().
Referenced by main().
void ArClientHandlerConfig::addGotConfigDefaultsCB (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a got config defaults callback.
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, myGotConfigDefaultsCBList, ArLog::Terse, and ArMutex::unlock().
void ArClientHandlerConfig::addGotLastEditablePriorityCB (ArFunctor * functor, int position = 50)
Adds callback invoked when the last editable priority packet is received.
void ArClientHandlerConfig::addSaveConfigFailedCB (ArFunctor1< const char * > * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a save config to server failed callback.
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, mySaveConfigFailedCBList, ArLog::Terse, and ArMutex::unlock().
Referenced by main().
void ArClientHandlerConfig::addSaveConfigSucceededCB (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a save config to server succeeded callback.
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, mySaveConfigSucceededCBList, ArLog::Terse, and ArMutex::unlock().
Referenced by main().
bool ArClientHandlerConfig::canRequestDefaults (void)
Sees if we can request defaults (both types)
References ArClientBase::dataExists(), and myClient.
Referenced by main(), requestConfigDefaults(), requestDefaultConfigFromServer(), and requestSectionDefaults().
ArConfig * ArClientHandlerConfig::getConfig (void)
Unthreadsafe way to get the config to play with (see long docs)
This will get the config, note, it gets the config we're using, so if you change something while data comes in things will get broken.
References myConfig.
Referenced by gotConfig().
ArConfig ArClientHandlerConfig::getConfigCopy (void)
Threadsafe way to get the config to play with.
This will get a copy of the config, you can use this with the safeConfigToServer that takes an argument.
References ArMutex::lock(), myConfig, myDataMutex, and ArMutex::unlock().
ArConfig * ArClientHandlerConfig::getDefaultConfig (void)
Returns a pointer to the robot server's default configuration, if canRequestDefaults() is true.
Note that both requestConfigFromServer() and then requestDefaultConfigFromServer() must be called before a valid default configuration is available on the client. If there is no default configuration, then NULL is returned.
References myDefaultConfig.
Referenced by main().
ArPriority::Priority ArClientHandlerConfig::getLastEditablePriority ()
Returns the last editable priority of the config.
References ArMutex::lock(), myDataMutex, myLastEditablePriority, and ArMutex::unlock().
void ArClientHandlerConfig::handleGetConfig (ArNetPacket * packet)
Handles the packet from the getConfig.
References handleGetConfigData().
void ArClientHandlerConfig::handleGetConfigBySections (ArNetPacket * packet)
Handles the packet from the GetConfigBySections.
References handleGetConfigData().
void ArClientHandlerConfig::handleGetConfigBySectionsV2 (ArNetPacket * packet)
Handles the packet from the GetConfigBySectionsV2.
References handleGetConfigData().
void ArClientHandlerConfig::handleGetConfigBySectionsV3 (ArNetPacket * packet)
Handles the packet from the GetConfigBySectionsV3.
References handleGetConfigData().
void ArClientHandlerConfig::handleGetConfigBySectionsV4 (ArNetPacket * packet)
Handles the packet from the GetConfigBySectionsV4.
void ArClientHandlerConfig::handleGetConfigData (ArNetPacket * packet, bool isMultiplePackets, int version) [protected]
References ArConfig::addParamAsIs(), ArConfig::addSection(), ArBasePacket::bufToByte(), ArBasePacket::bufToStr(), ArBasePacket::bufToUByte2(), ArClientArg::createArg(), ArBasePacket::getDataLength(), ArBasePacket::getDataReadLength(), IFDEBUG, ArPriority::LAST_PRIORITY, ArMutex::lock(), ArLog::log(), ArConfig::log(), myCallbackMutex, myConfig, myDataMutex, myGotConfigCBList, myHaveGottenConfig, myLogPrefix, ArLog::Normal, ArConfig::setSectionComment(), ArLog::Terse, ArMutex::unlock(), and ArLog::Verbose.
Referenced by handleGetConfig(), handleGetConfigBySections(), handleGetConfigBySectionsV2(), and handleGetConfigBySectionsV3().
void ArClientHandlerConfig::handleGetConfigDefaults (ArNetPacket * packet)
Handles the return packet from getConfigDefaults.
References ArArgumentBuilder::add(), ArBasePacket::bufToStr(), ArConfig::clearAllValueSet(), ArBasePacket::getDataLength(), ArBasePacket::getDataReadLength(), IFDEBUG, ArMutex::lock(), ArLog::log(), ArConfig::log(), myCallbackMutex, myConfig, myDataMutex, myDefaultConfig, myGotConfigDefaultsCBList, myHaveGottenDefaults, myHaveRequestedDefaultCopy, myHaveRequestedDefaults, myIsQuiet, myLogPrefix, myRobotName, ArLog::Normal, ArConfig::parseArgument(), ArConfig::parseSection(), ArConfig::removeAllUnsetValues(), ArConfig::setConfigName(), ArArgumentBuilder::setExtraString(), ArConfig::setQuiet(), ArArgumentBuilder::setQuiet(), ArLog::Terse, and ArMutex::unlock().
void ArClientHandlerConfig::handleGetConfigSectionFlags (ArNetPacket * packet)
Handles the packet from the GetConfigSectionFlags.
References ArConfig::addSectionFlags(), ArBasePacket::bufToByte4(), ArBasePacket::bufToStr(), ArMutex::lock(), myConfig, myDataMutex, and ArMutex::unlock().
void ArClientHandlerConfig::handleGetLastEditablePriority (ArNetPacket * packet)
Handles the return packet from getLastEditablePriority.
References ArBasePacket::bufToByte(), ArPriority::getPriorityName(), ArPriority::LAST_PRIORITY, ArLog::log(), ArLog::Normal, ArPriority::PRIORITY_COUNT, and ArLog::Terse.
void ArClientHandlerConfig::handleSetConfig (ArNetPacket * packet)
Handles the return packet from the setConfig (saveConfigToServer)
References ArBasePacket::bufToStr(), ArMutex::lock(), ArLog::log(), myCallbackMutex, myLogPrefix, mySaveConfigFailedCBList, mySaveConfigSucceededCBList, ArLog::Normal, and ArMutex::unlock().
void ArClientHandlerConfig::handleSetConfigBySections (ArNetPacket * packet)
Handles the return packet from the setConfigBySections (saveConfigToServer)
Handles the return packet from the setConfig (saveConfigToServer)
References ArBasePacket::bufToStr(), ArMutex::lock(), ArLog::log(), myCallbackMutex, myLogPrefix, mySaveConfigFailedCBList, mySaveConfigSucceededCBList, ArLog::Normal, and ArMutex::unlock().
void ArClientHandlerConfig::handleSetConfigBySectionsV2 (ArNetPacket * packet)
Handles the return packet from the setConfigBySectionsV2 (saveConfigToServer)
Handles the return packet from the setConfig (saveConfigToServer)
References ArBasePacket::bufToStr(), IFDEBUG, ArMutex::lock(), ArLog::log(), myCallbackMutex, myLogPrefix, mySaveConfigFailedCBList, mySaveConfigSucceededCBList, ArLog::Normal, and ArMutex::unlock().
bool ArClientHandlerConfig::haveGottenConfig (void)
Returns true if config gotten.
References ArMutex::lock(), myDataMutex, myHaveGottenConfig, and ArMutex::unlock().
bool ArClientHandlerConfig::haveGottenDefaults (void)
Returns if we've gotten our requested defaults.
References ArMutex::lock(), myDataMutex, myHaveGottenDefaults, and ArMutex::unlock().
Referenced by main().
bool ArClientHandlerConfig::haveGottenLastEditablePriority ()
Returns whether the last editable priority has been received from the server.
References ArMutex::lock(), myDataMutex, myHaveGottenLastEditablePriority, and ArMutex::unlock().
bool ArClientHandlerConfig::haveRequestedDefaults (void)
Returns if we've requested some defaults.
References ArMutex::lock(), myDataMutex, myHaveRequestedDefaultCopy, myHaveRequestedDefaults, and ArMutex::unlock().
Referenced by requestConfigDefaults(), requestDefaultConfigFromServer(), and requestSectionDefaults().
bool ArClientHandlerConfig::isLastEditablePriorityAvailable ()
Returns whether the server supports the last editable priority request.
References ArClientBase::dataExists(), and myClient.
int ArClientHandlerConfig::lock (void)
Locks the config for if you're using the unthreadsafe getConfig.
References ArMutex::lock(), and myDataMutex.
void ArClientHandlerConfig::reloadConfigOnServer (void)
Tells the server to reload the configuration.
References myClient, and ArClientBase::requestOnce().
void ArClientHandlerConfig::remGotConfigCB (ArFunctor * functor)
Removes a gotConfig callback.
References ArMutex::lock(), myCallbackMutex, myGotConfigCBList, and ArMutex::unlock().
void ArClientHandlerConfig::remGotConfigDefaultsCB (ArFunctor * functor)
Removes a got config defaults callback.
References ArMutex::lock(), myCallbackMutex, myGotConfigDefaultsCBList, and ArMutex::unlock().
void ArClientHandlerConfig::remGotLastEditablePriorityCB (ArFunctor * functor)
Removes the specified callback from the list of last editable priority callbacks.
void ArClientHandlerConfig::remSaveConfigFailedCB (ArFunctor1< const char * > * functor)
Removes a save config to server failed callback.
References ArMutex::lock(), myCallbackMutex, mySaveConfigFailedCBList, and ArMutex::unlock().
void ArClientHandlerConfig::remSaveConfigSucceededCB (ArFunctor * functor)
Removes a save config to server succeeded callback.
References ArMutex::lock(), myCallbackMutex, mySaveConfigSucceededCBList, and ArMutex::unlock().
bool ArClientHandlerConfig::requestConfigDefaults (void)
Requests defaults for all sections from the server; modifies the config.
References canRequestDefaults(), haveRequestedDefaults(), ArMutex::lock(), ArLog::log(), myClient, myDataMutex, myHaveGottenDefaults, myHaveRequestedDefaultCopy, myHaveRequestedDefaults, myLogPrefix, ArLog::Normal, ArClientBase::requestOnce(), and ArMutex::unlock().
void ArClientHandlerConfig::requestConfigFromServer (void)
Requests the config from the server.
This requests the config from the server.
The handler's internal state is reset to indicate that the config hasn't been received.
If the server supports editable priority levels and the client wishes to receive parameters of ineditable priorities, then the method requestLastEditablePriority should be called (and completed) before requestConfigFromServer is called.
References ArClientBase::addHandler(), ArBasePacket::byteToBuf(), ArConfig::clearSections(), ArClientBase::dataExists(), ArPriority::getPriorityName(), IFDEBUG, ArPriority::LAST_PRIORITY, ArMutex::lock(), ArLog::log(), myClient, myConfig, myDataMutex, myHandleGetConfigBySectionsCB, myHandleGetConfigBySectionsV2CB, myHandleGetConfigBySectionsV3CB, myHandleGetConfigBySectionsV4CB, myHandleGetConfigCB, myHandleGetConfigDefaultsCB, myHandleGetConfigSectionFlagsCB, myHandleSetConfigBySectionsCB, myHandleSetConfigBySectionsV2CB, myHandleSetConfigCB, myHaveGottenConfig, myHaveGottenLastEditablePriority, myLastEditablePriority, myLogPrefix, ArLog::Normal, ArClientBase::remHandler(), ArClientBase::requestOnce(), ArLog::Terse, ArMutex::unlock(), and ArLog::Verbose.
Referenced by main().
bool ArClientHandlerConfig::requestDefaultConfigFromServer (void)
References canRequestDefaults(), haveRequestedDefaults(), ArMutex::lock(), ArLog::log(), myClient, myDataMutex, myHaveGottenDefaults, myHaveRequestedDefaultCopy, myHaveRequestedDefaults, myLogPrefix, ArLog::Normal, ArClientBase::requestOnce(), and ArMutex::unlock().
Referenced by main().
bool ArClientHandlerConfig::requestLastEditablePriorityFromServer ()
Requests the last editable priority from the server.
References ArClientBase::addHandler(), ArClientBase::dataExists(), ArMutex::lock(), ArLog::log(), myClient, myDataMutex, myHandleGetLastEditablePriorityCB, myHaveGottenLastEditablePriority, myHaveRequestedLastEditablePriority, myLogPrefix, ArLog::Normal, ArClientBase::remHandler(), ArClientBase::requestOnce(), and ArMutex::unlock().
bool ArClientHandlerConfig::requestSectionDefaults (const char * section)
Requests defaults for one section from the server; modifies the config.
References canRequestDefaults(), ArConfig::findSection(), haveRequestedDefaults(), ArMutex::lock(), ArLog::log(), myClient, myConfig, myDataMutex, myHaveGottenDefaults, myHaveRequestedDefaultCopy, myHaveRequestedDefaults, myLogPrefix, ArLog::Normal, ArClientBase::requestOnceWithString(), and ArMutex::unlock().
void ArClientHandlerConfig::saveConfigToServer (void)
Sends the config back to the server.
References myConfig.
Referenced by gotConfig().
void ArClientHandlerConfig::saveConfigToServer (ArConfig * config, const std::set< std::string, ArStrCaseCmpOp > * ignoreTheseSections = NULL)
Sends the config back to the server.
References ArClientArg::addArgTextToPacket(), ArClientBase::dataExists(), ArNetPacket::empty(), ArConfigSection::getName(), ArConfigSection::getParams(), ArConfig::getSections(), IFDEBUG, ArClientArg::isSendableParamType(), ArMutex::lock(), ArLog::log(), ArConfig::log(), myClient, myDataMutex, myLogPrefix, mySaveConfigFailedCBList, ArLog::Normal, ArClientBase::requestOnce(), ArBasePacket::strToBuf(), ArMutex::unlock(), and ArLog::Verbose.
void ArClientHandlerConfig::setQuiet (bool isQuiet)
Turn on this flag to reduce the number of verbose log messages.
References myConfig, myDefaultConfig, myIsQuiet, and ArConfig::setQuiet().
int ArClientHandlerConfig::tryLock (void)
Try to lock for the config for if you're using the unthreadsafe getConfig.
References myDataMutex, and ArMutex::tryLock().
int ArClientHandlerConfig::unlock (void)
Unlocks the config for if you're using the unthreadsafe getConfig.
References myDataMutex, and ArMutex::unlock().
Member Data Documentation
ArMutex ArClientHandlerConfig::myCallbackMutex [protected]
Referenced by addGotConfigCB(), addGotConfigDefaultsCB(), addSaveConfigFailedCB(), addSaveConfigSucceededCB(), ArClientHandlerConfig(), handleGetConfigData(), handleGetConfigDefaults(), handleSetConfig(), handleSetConfigBySections(), handleSetConfigBySectionsV2(), remGotConfigCB(), remGotConfigDefaultsCB(), remSaveConfigFailedCB(), and remSaveConfigSucceededCB().
ArClientBase* ArClientHandlerConfig::myClient [protected]
Referenced by canRequestDefaults(), isLastEditablePriorityAvailable(), reloadConfigOnServer(), requestConfigDefaults(), requestConfigFromServer(), requestDefaultConfigFromServer(), requestLastEditablePriorityFromServer(), requestSectionDefaults(), and saveConfigToServer().
ArConfig ArClientHandlerConfig::myConfig [protected]
Referenced by ArClientHandlerConfig(), getConfig(), getConfigCopy(), handleGetConfigData(), handleGetConfigDefaults(), handleGetConfigSectionFlags(), requestConfigFromServer(), requestSectionDefaults(), saveConfigToServer(), and setQuiet().
ArMutex ArClientHandlerConfig::myDataMutex [protected]
Referenced by ArClientHandlerConfig(), getConfigCopy(), getLastEditablePriority(), handleGetConfigData(), handleGetConfigDefaults(), handleGetConfigSectionFlags(), haveGottenConfig(), haveGottenDefaults(), haveGottenLastEditablePriority(), haveRequestedDefaults(), lock(), requestConfigDefaults(), requestConfigFromServer(), requestDefaultConfigFromServer(), requestLastEditablePriorityFromServer(), requestSectionDefaults(), saveConfigToServer(), tryLock(), and unlock().
ArConfig* ArClientHandlerConfig::myDefaultConfig [protected]
Referenced by getDefaultConfig(), handleGetConfigDefaults(), setQuiet(), and ~ArClientHandlerConfig().
std::list<ArFunctor *> ArClientHandlerConfig::myGotConfigCBList [protected]
Referenced by addGotConfigCB(), handleGetConfigData(), and remGotConfigCB().
std::list<ArFunctor *> ArClientHandlerConfig::myGotConfigDefaultsCBList [protected]
Referenced by addGotConfigDefaultsCB(), handleGetConfigDefaults(), and remGotConfigDefaultsCB().
ArCallbackList ArClientHandlerConfig::myGotLastEditablePriorityCBList [protected]
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetConfigBySectionsCB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetConfigBySectionsV2CB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetConfigBySectionsV3CB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetConfigBySectionsV4CB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetConfigCB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetConfigDefaultsCB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetConfigSectionFlagsCB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetDefaultConfigCB [protected]
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetLastEditablePriorityCB [protected]
Referenced by requestLastEditablePriorityFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleSetConfigBySectionsCB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleSetConfigBySectionsV2CB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleSetConfigCB [protected]
Referenced by requestConfigFromServer().
bool ArClientHandlerConfig::myHaveGottenConfig [protected]
Referenced by handleGetConfigData(), haveGottenConfig(), and requestConfigFromServer().
bool ArClientHandlerConfig::myHaveGottenDefaults [protected]
Referenced by handleGetConfigDefaults(), haveGottenDefaults(), requestConfigDefaults(), requestDefaultConfigFromServer(), and requestSectionDefaults().
bool ArClientHandlerConfig::myHaveGottenLastEditablePriority [protected]
Referenced by haveGottenLastEditablePriority(), requestConfigFromServer(), and requestLastEditablePriorityFromServer().
bool ArClientHandlerConfig::myHaveRequestedConfig [protected]
bool ArClientHandlerConfig::myHaveRequestedDefaultCopy [protected]
Referenced by handleGetConfigDefaults(), haveRequestedDefaults(), requestConfigDefaults(), requestDefaultConfigFromServer(), and requestSectionDefaults().
bool ArClientHandlerConfig::myHaveRequestedDefaults [protected]
Referenced by handleGetConfigDefaults(), haveRequestedDefaults(), requestConfigDefaults(), requestDefaultConfigFromServer(), and requestSectionDefaults().
bool ArClientHandlerConfig::myHaveRequestedLastEditablePriority [protected]
Referenced by requestLastEditablePriorityFromServer().
bool ArClientHandlerConfig::myIsQuiet [protected]
Referenced by handleGetConfigDefaults(), and setQuiet().
ArPriority::Priority ArClientHandlerConfig::myLastEditablePriority [protected]
Referenced by getLastEditablePriority(), and requestConfigFromServer().
std::string ArClientHandlerConfig::myLogPrefix [protected]
Referenced by ArClientHandlerConfig(), handleGetConfigData(), handleGetConfigDefaults(), handleSetConfig(), handleSetConfigBySections(), handleSetConfigBySectionsV2(), requestConfigDefaults(), requestConfigFromServer(), requestDefaultConfigFromServer(), requestLastEditablePriorityFromServer(), requestSectionDefaults(), and saveConfigToServer().
std::string ArClientHandlerConfig::myRobotName [protected]
Referenced by ArClientHandlerConfig(), and handleGetConfigDefaults().
std::list<ArFunctor1<const char *> *> ArClientHandlerConfig::mySaveConfigFailedCBList [protected]
Referenced by addSaveConfigFailedCB(), handleSetConfig(), handleSetConfigBySections(), handleSetConfigBySectionsV2(), remSaveConfigFailedCB(), and saveConfigToServer().
std::list<ArFunctor *> ArClientHandlerConfig::mySaveConfigSucceededCBList [protected]
Referenced by addSaveConfigSucceededCB(), handleSetConfig(), handleSetConfigBySections(), handleSetConfigBySectionsV2(), and remSaveConfigSucceededCB().
The documentation for this class was generated from the following files:
ArClientHandlerConfig.h
ArClientHandlerConfig.cpp