ArNetworking: Circle Class Reference
Circle Class Reference
Public Member Functions
Circle (ArServerInfoDrawings *drawingsServer, const std::string &name, ArDrawingData *drawData)
void setNumPoints (unsigned int r)
void setPos (const ArPose &p)
void setRadius (double r)
~Circle ()
Detailed Description
Examples:
drawingsExample.cpp.
Constructor & Destructor Documentation
Circle::Circle (ArServerInfoDrawings * drawingsServer, const std::string & name, ArDrawingData * drawData)
Examples:
drawingsExample.cpp.
References ArServerInfoDrawings::addDrawing().
Circle::~Circle ()
Examples:
drawingsExample.cpp.
References ArBasePacket::byte4ToBuf(), client, ArMath::cos(), ArNetPacket::empty(), ArPose::getX(), ArPose::getY(), ArMutex::lock(), ArMath::roundInt(), ArServerClient::sendPacketUdp(), ArMath::sin(), and ArMutex::unlock().
Member Function Documentation
void Circle::setNumPoints (unsigned int r) inline
Examples:
drawingsExample.cpp.
Referenced by main().
void Circle::setPos (const ArPose & p) inline
Examples:
drawingsExample.cpp.
Referenced by main().
void Circle::setRadius (double r) inline
Examples:
drawingsExample.cpp.
Referenced by main().
The documentation for this class was generated from the following file:
drawingsExample.cpp