ArNetworking: ArServerBase::SlowIdleThread Class Reference
ArServerBase::SlowIdleThread Class Reference
#include <ArServerBase.h>
Public Member Functions
void addCycleCallback (ArFunctor *functor)
Add a callback to be called at every cycle.
void remCycleCallback (ArFunctor *functor)
Remove a callback to be called at every cycle.
virtual void * runThread (void *arg)
SlowIdleThread (ArServerBase *serverBase)
Constructor.
virtual ~SlowIdleThread (void)
Destructor.
Public Member Functions inherited from ArASyncTask
ArASyncTask ()
virtual int create (bool joinable=true, bool lowerPriority=true)
virtual const char * getThreadActivity (void)
virtual void run (void)
virtual void runAsync (void)
virtual void * runInThisThread (void *arg=0)
virtual void stopRunning (void)
virtual ~ArASyncTask ()
Public Member Functions inherited from ArThread
ArThread (bool blockAllSignals=true)
ArThread (ThreadType thread, bool joinable, bool blockAllSignals=true)
ArThread (ArFunctor *func, bool joinable=true, bool blockAllSignals=true)
virtual void cancel (void)
virtual int create (ArFunctor *func, bool joinable=true, bool lowerPriority=true)
virtual int detach (void)
bool getBlockAllSignals (void)
virtual ArFunctor * getFunc (void) const
virtual bool getJoinable (void) const
virtual ThreadType getOSThread (void) const
virtual bool getRunning (void) const
virtual bool getRunningWithLock (void)
virtual const ThreadType * getThread (void) const
virtual const char * getThreadName (void)
virtual bool isThreadFinished () const
virtual bool isThreadStarted () const
virtual int join (void **ret=NULL)
int lock (void)
virtual void logThreadInfo (void)
virtual void setRunning (bool running)
virtual void setThreadName (const char *name)
virtual void threadFinished (void)
virtual void threadStarted (void)
int tryLock (void)
int unlock (void)
virtual ~ArThread ()
Protected Attributes
std::list< ArFunctor * > myCycleCallbacks
ArMutex myCycleCallbacksMutex
ArServerBase * myServerBase
Protected Attributes inherited from ArThread
bool myRunning
Additional Inherited Members
Public Types inherited from ArThread
enum Status
Static Public Member Functions inherited from ArThread
static void cancelAll (void)
static ArLog::LogLevel getLogLevel (void)
static ThreadType getThisOSThread (void)
static const ThreadType * getThisThread (void)
static const char * getThisThreadName (void)
static void init (void)
static void joinAll (void)
static ThreadType osSelf (void)
static ArThread * self (void)
static void setLogLevel (ArLog::LogLevel level)
static void shutdown ()
static void stopAll ()
static void yieldProcessor (void)
Public Attributes inherited from ArThread
STATUS_ALREADY_DETATCHED
STATUS_FAILED
STATUS_INVALID
STATUS_JOIN_SELF
STATUS_NO_SUCH_THREAD
STATUS_NORESOURCE
Constructor & Destructor Documentation
ArServerBase::SlowIdleThread::SlowIdleThread (ArServerBase * serverBase)
Constructor.
References ArServerBase::runAsync(), and ArThread::setThreadName().
ArServerBase::SlowIdleThread::~SlowIdleThread (void) virtual
Destructor.
Member Function Documentation
void ArServerBase::SlowIdleThread::addCycleCallback (ArFunctor * functor)
Add a callback to be called at every cycle.
void ArServerBase::SlowIdleThread::remCycleCallback (ArFunctor * functor)
Remove a callback to be called at every cycle.
void * ArServerBase::SlowIdleThread::runThread (void * arg) virtual
Implements ArASyncTask.
References ArThread::getRunning(), ArThread::threadFinished(), and ArThread::threadStarted().
Member Data Documentation
std::list<ArFunctor*> ArServerBase::SlowIdleThread::myCycleCallbacks protected
ArMutex ArServerBase::SlowIdleThread::myCycleCallbacksMutex protected
ArServerBase* ArServerBase::SlowIdleThread::myServerBase protected
The documentation for this class was generated from the following files:
ArServerBase.h
ArServerBase.cpp