ArNetworking: ArServerFileToClient Class Reference
ArServerFileToClient Class Reference
Gets files from the server.
#include <ArServerFileUtils.h>
Public Member Functions
ArServerFileToClient (ArServerBase *server, const char *topDir)
Constructor.
void getFile (ArServerClient *client, ArNetPacket *packet)
Gets the file.
void getFileWithTimestamp (ArServerClient *client, ArNetPacket *packet)
Gets the file, and sets its timestamp to the original server value.
virtual ~ArServerFileToClient ()
Destructor.
Protected Member Functions
void doGetFile (ArServerClient *client, ArNetPacket *packet, bool isSetTimestamp)
Protected Attributes
char myBaseDir [2048]
ArFunctor2C< ArServerFileToClient, ArServerClient *, ArNetPacket * > myGetFileCB
ArFunctor2C< ArServerFileToClient, ArServerClient *, ArNetPacket * > myGetFileWithTimestampCB
ArServerBase * myServer
Detailed Description
Gets files from the server.
Note
Available on Linux only
This class is set up so that a client can get files the robot, this class ONLY gets files. You should use this class by using ArClientFileToClient and NOT by using this classes interface directly, this is because the API is and will remain fairly volatile... if you need more functionality let us know and we'll add it if its reasonable.
Constructor & Destructor Documentation
ArServerFileToClient::ArServerFileToClient (ArServerBase * server, const char * topDir)
Constructor.
References ArServerBase::addData(), ArUtil::appendSlash(), ArUtil::fixSlashes(), myBaseDir, myGetFileCB, myGetFileWithTimestampCB, and myServer.
ArServerFileToClient::~ArServerFileToClient () virtual
Destructor.
Member Function Documentation
void ArServerFileToClient::doGetFile (ArServerClient * client, ArNetPacket * packet, bool isSetTimestamp) protected
References ArBasePacket::bufToStr(), ArBasePacket::byte4ToBuf(), ArBasePacket::dataToBuf(), ArNetPacket::empty(), file, ArUtil::fixSlashes(), ArUtil::fopen(), ArServerClient::getIPString(), ArLog::log(), ArUtil::matchCase(), myBaseDir, ArLog::Normal, ArServerClient::sendPacketTcp(), ArBasePacket::strToBuf(), ArBasePacket::uByte2ToBuf(), ArBasePacket::uByte4ToBuf(), and ArLog::Verbose.
Referenced by getFile(), and getFileWithTimestamp().
void ArServerFileToClient::getFile (ArServerClient * client, ArNetPacket * packet)
Gets the file.
References doGetFile(), and getFileWithTimestamp().
void ArServerFileToClient::getFileWithTimestamp (ArServerClient * client, ArNetPacket * packet)
Gets the file, and sets its timestamp to the original server value.
References doGetFile().
Referenced by getFile().
Member Data Documentation
char ArServerFileToClient::myBaseDir[2048] protected
Referenced by ArServerFileToClient(), and doGetFile().
ArFunctor2C<ArServerFileToClient, ArServerClient *, ArNetPacket *> ArServerFileToClient::myGetFileCB protected
Referenced by ArServerFileToClient().
ArFunctor2C<ArServerFileToClient, ArServerClient *, ArNetPacket *> ArServerFileToClient::myGetFileWithTimestampCB protected
Referenced by ArServerFileToClient().
ArServerBase* ArServerFileToClient::myServer protected
Referenced by ArServerFileToClient().
The documentation for this class was generated from the following files:
ArServerFileUtils.h
ArServerFileUtils.cpp