ArNetworking: ArServerModeRatioDrive Class Reference
ArServerModeRatioDrive Class Reference
#include <ArServerModeRatioDrive.h>
Public Member Functions
virtual void activate (void)
The function called when the mode is activated.
void addControlCommands (ArServerHandlerCommands *handlerCommands)
This adds commands that'll let you disable and enable safe driving.
void addDrivingBackwardsCallback (ArFunctor *functor, int position=50)
Adds a callback mode for when trying to back up.
void addSafeDrivingCallback (ArFunctor *functor, int position=50)
Adds a callback mode for when safe driving is activated.
void addToConfig (ArConfig *config, const char *section)
Adds to a config in a section.
void addUnsafeDrivingCallback (ArFunctor *functor, int position=50)
Adds a callback mode for when unsafe driving is activated.
ArServerModeRatioDrive (ArServerBase *server, ArRobot *robot, bool takeControlOnJoystick=true, bool useComputerJoystick=true, bool useRobotJoystick=true, bool useServerCommands=true, const char *name="ratioDrive", bool robotJoystickOverridesLocks=true)
Constructor.
virtual void deactivate (void)
The function called when the mode is deactivated.
virtual ArActionGroup * getActionGroup (void)
This function should return the action group this mode uses.
ArActionRatioInput * getActionRatioInput (void)
bool getSafeDriving (void)
Gets whether we're driving safely or not.
bool getUseLocationDependentDevices (void)
Gets whether we're using the range devices that depend on location.
void ratioDrive (double transRatio, double rotRatio, double throttleRatio, bool isActivating=false, double latRatio=0)
Sets the ratio drive action.
void remDrivingBackwardsCallback (ArFunctor *functor)
Removes a callback mode for when trying to back up.
void remSafeDrivingCallback (ArFunctor *functor)
Removes a callback mode for when safe driving is activated.
void remUnsafeDrivingCallback (ArFunctor *functor)
Removes a callback mode for when unsafe driving is activated.
void setSafeDriving (bool safe, bool internal=false)
Sets whether we're safe driving or not.
void setUseLocationDependentDevices (bool useLocationDependentDevices, bool internal=false)
Sets whether we're using the range devices that depend on location.
virtual void userTask (void)
The ArMode's user task, don't need one, subclass must provide if needed.
virtual ~ArServerModeRatioDrive ()
Destructor.
Public Member Functions inherited from ArServerMode
virtual void activationDenied (void)
The function called if the mode is not activated because another mode superceded it.
void addActivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is activated.
void addAsDefaultMode (ArListPos::Pos pos=ArListPos::LAST)
Sets this mode to default (so if a mode deactivates it activates this)
void addDeactivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is deactivated.
bool addModeData (const char *name, const char *description, ArFunctor2< ArServerClient *, ArNetPacket * > *functor, const char *argumentDescription, const char *returnDescription, const char *commandGroup=NULL, const char *dataFlags=NULL)
This basically just notes the commands associated with a mode so that clients can know what can and can't happen based on what mode is active/locked/etc.
void addSingleShotDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for when this class is deactivated.
void addSingleShotPostDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for just after the deactivate happens (when the next mode has activated)
ArServerMode (ArRobot *robot, ArServerBase *server, const char *name)
Constructor.
virtual void checkDefault (void)
Sees if this wants to become the default mode.
virtual void forceUnlock (void)
This will be called if another mode has to break the lock.
ArTime getActivityTime (void)
Gets the time of our last activity.
const char * getExtendedStatus (void) const
Gets a string representing the extended status of the mode we're in.
const char * getMode (void) const
Gets a string representing the mode we're in.
const char * getName (void) const
Gets the name of the mode we're in.
const char * getStatus (void) const
Gets a string representing the status of the mode we're in.
bool hasSetActivityTime (void)
Gets if we've set our activity time.
void internalSetActivityTime (ArTime time)
Internal call to set the activity time (this is dangerous and shouldn't be used)
bool isActive (void) const
Gets if this mode is active or not.
virtual bool isAutoResumeAfterInterrupt ()
Adds data to the list of this mode's commands.
void lockMode (bool willUnlockIfRequested=false)
Locks this mode in until its unlocked (mode must be the active mode)
void remActivateCallback (ArFunctor *functor)
Removes a callback for when this class is activated.
void remDeactivateCallback (ArFunctor *functor)
Removes a callback for when this class is deactivated.
void remSingleShotDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for when this class is deactivated.
void remSingleShotPostDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for just after the deactivate happens (when the next mode has activated)
virtual void requestUnlock (void)
This will be called if another mode wants the lock broken (can ignore)
void setActivityTimeToNow (void)
Sets that we're active right now.
void setMode (const char *str)
This should only be used by careful people and probably not then.
void setStatus (const char *str)
This should only be used by careful people and probably not then.
void unlockMode (void)
Unlocks the mode so other modes can activate.
virtual ~ArServerMode ()
Destructor.
Protected Member Functions
void joyUserTask (void)
void ratioFireCallback (void)
void serverGetSafeDrive (ArServerClient *client, ArNetPacket *packet)
void serverRatioDrive (ArServerClient *client, ArNetPacket *packet)
void serverSafeDrivingDisable (void)
void serverSafeDrivingEnable (void)
void serverSetSafeDrive (ArServerClient *client, ArNetPacket *packet)
Protected Member Functions inherited from ArServerMode
bool baseActivate (bool canSelfActivateIfLocked=false)
Activates this mode if it can (returns true if it can, false otherwise).
void baseDeactivate (void)
Deactivates this mode.
void checkBroadcastModeInfoPacket (void)
ArServerMode * getLastActiveMode ()
Protected Attributes
bool myDriveSafely
ArCallbackList myDrivingBackwardsCallbacks
bool myGotServerCommand
ArServerHandlerCommands * myHandlerCommands
ArRatioInputJoydrive * myJoydrive
ArJoyHandler * myJoyHandler
ArFunctorC< ArServerModeRatioDrive > myJoyUserTaskCB
ArTime myLastCommand
bool myLastRobotSafeDrive
bool myLastTimedOut
double myLatRatio
ArActionDeceleratingLimiter * myLimiterBackward
ArActionDeceleratingLimiter * myLimiterForward
ArActionDeceleratingLimiter * myLimiterLateralLeft
ArActionDeceleratingLimiter * myLimiterLateralRight
ArActionMovementParameters * myMovementParameters
bool myNewDriveSafely
bool myPrinting
ArActionRatioInput * myRatioAction
ArActionGroup myRatioDriveGroup
ArFunctorC< ArServerModeRatioDrive > myRatioFireCB
ArRatioInputRobotJoydrive * myRobotJoydrive
ArRobotJoyHandler * myRobotJoyHandler
bool myRobotJoystickOverridesLock
double myRotRatio
ArCallbackList mySafeDrivingCallbacks
bool mySentRecenter
ArFunctor2C< ArServerModeRatioDrive, ArServerClient *, ArNetPacket * > myServerGetSafeDriveCB
ArFunctor2C< ArServerModeRatioDrive, ArServerClient *, ArNetPacket * > myServerRatioDriveCB
ArFunctorC< ArServerModeRatioDrive > myServerSafeDrivingDisableCB
ArFunctorC< ArServerModeRatioDrive > myServerSafeDrivingEnableCB
ArFunctor2C< ArServerModeRatioDrive, ArServerClient *, ArNetPacket * > myServerSetSafeDriveCB
bool myTakeControlOnJoystick
double myThrottleRatio
double myTimeout
double myTransRatio
ArCallbackList myUnsafeDrivingCallbacks
bool myUseComputerJoystick
bool myUseLocationDependentDevices
bool myUseRobotJoystick
bool myUseServerCommands
Protected Attributes inherited from ArServerMode
ArCallbackList myActivateCallbacks
ArTime myActivityTime
ArMutex myActivityTimeMutex
ArCallbackList myDeactivateCallbacks
std::string myExtendedStatus
bool myHasSetActivityTime
bool myIsActive
std::string myMode
std::string myName
ArRobot * myRobot
ArServerBase * myServer
bool mySetActivityThisCycle
ArCallbackList mySingleShotDeactivateCallbacks
ArCallbackList mySingleShotPostDeactivateCallbacks
std::string myStatus
bool myStatusSetThisCycle
ArLog::LogLevel myVerboseLogLevel
Additional Inherited Members
Static Public Member Functions inherited from ArServerMode
static ArServerMode * getActiveMode (void)
Gets the active mode.
static int getActiveModeActivityTimeSecSince (void)
Gets the seconds since the activity of our active mode.
static const char * getActiveModeExtendedStatusString (void)
Gets the active extended status string.
static const char * getActiveModeModeString (void)
Gets the active mode string.
static bool getActiveModeSetActivityThisCycle (void)
Gets if the active mode set the activity time this cycle or not.
static const char * getActiveModeStatusString (void)
Gets the active status string.
static ArServerModeIdle * getIdleMode (void)
Call that gets our idle mode.
static void getModeBusy (ArServerClient *client, ArNetPacket *packet)
Handles the packet request for the mode busy state.
static void getModeDataList (ArServerClient *client, ArNetPacket *packet)
Gets the list of data for each mode.
static void getModeInfo (ArServerClient *client, ArNetPacket *packet)
Gets the info about which mode is active and such.
static bool isLocked (void)
Gets if the active mode is locked or not.
static bool willUnlockIfRequested (void)
Gets whether we'll unlock if requested or not.
Static Protected Member Functions inherited from ArServerMode
static void buildModeInfoPacket (ArNetPacket *packet)
static std::list< ArServerMode * > * getRequestedActivateModes (void)
static void modeUserTask (void)
Static Protected Attributes inherited from ArServerMode
static ArServerMode * ourActiveMode = NULL
static bool ourActiveModeLocked = false
static bool ourActiveModeSetActivityThisCycle = false
static bool ourActiveModeWillUnlockIfRequested = false
static ArServerMode * ourBroadcastActiveMode = NULL
static bool ourBroadcastActiveModeLocked = false
static bool ourBroadcastActiveModeWillUnlockIfRequested = false
static std::list< ArServerMode * > ourDefaultModes
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeBusyCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeDataListCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeInfoCB
static ArServerModeIdle * ourIdleMode = NULL
static bool ourIdleModeCreated = false
static ArMutex ourIdleModeMutex
static bool ourIsBusy = false
static ArServerMode * ourLastActiveMode = NULL
static std::multimap< std::string, std::string > ourModeDataMap
static ArMutex ourModeDataMapMutex
static std::list< ArServerMode * > ourModes
static ArServerMode * ourNextActiveMode = NULL
static std::list< ArServerMode * > ourRequestedActivateModes
static ArServerBase * ourServerBase = NULL
static bool ourUserTaskAdded = false
static ArGlobalFunctor ourUserTaskCB
Detailed Description
Examples:
drawingsExampleWithRobot.cpp, popupExample.cpp, and serverDemo.cpp.
Constructor & Destructor Documentation
ArServerModeRatioDrive::ArServerModeRatioDrive (ArServerBase * server, ArRobot * robot, bool takeControlOnJoystick = true, bool useComputerJoystick = true, bool useRobotJoystick = true, bool useServerCommands = true, const char * name = "ratioDrive", bool robotJoystickOverridesLocks = true)
Constructor.
References ArActionGroup::addAction(), ArServerBase::addData(), ArActionRatioInput::addFireCallback(), ArServerMode::addModeData(), ArRobot::addUserTask(), ArActionDeceleratingLimiter::BACKWARDS, ArActionDeceleratingLimiter::FORWARDS, Aria::getJoyHandler(), Aria::getRobotJoyHandler(), ArRobot::hasLatVel(), ArJoyHandler::init(), ArActionDeceleratingLimiter::LATERAL_LEFT, ArActionDeceleratingLimiter::LATERAL_RIGHT, myDriveSafely, myGotServerCommand, myHandlerCommands, myJoydrive, myJoyHandler, myJoyUserTaskCB, myLastRobotSafeDrive, myLastTimedOut, myLimiterBackward, myLimiterForward, myLimiterLateralLeft, myLimiterLateralRight, myMovementParameters, myPrinting, myRatioAction, myRatioDriveGroup, myRatioFireCB, ArServerMode::myRobot, myRobotJoydrive, myRobotJoyHandler, myRobotJoystickOverridesLock, mySentRecenter, ArServerMode::myServer, myServerGetSafeDriveCB, myServerRatioDriveCB, myServerSetSafeDriveCB, myTakeControlOnJoystick, myTimeout, myUseComputerJoystick, myUseLocationDependentDevices, myUseRobotJoystick, myUseServerCommands, Aria::setJoyHandler(), ArFunctor::setName(), and Aria::setRobotJoyHandler().
ArServerModeRatioDrive::~ArServerModeRatioDrive () virtual
Destructor.
Member Function Documentation
void ArServerModeRatioDrive::activate (void) virtual
The function called when the mode is activated.
Subclasses must implement this, but also call baseActivate().-
Implements ArServerMode.
References ratioDrive().
Referenced by joyUserTask(), and serverRatioDrive().
void ArServerModeRatioDrive::addControlCommands (ArServerHandlerCommands * handlerCommands)
This adds commands that'll let you disable and enable safe driving.
Examples:
serverDemo.cpp.
References ArServerHandlerCommands::addCommand(), ArLog::log(), myHandlerCommands, myServerSafeDrivingDisableCB, myServerSafeDrivingEnableCB, myUseServerCommands, and ArLog::Normal.
Referenced by main().
void ArServerModeRatioDrive::addDrivingBackwardsCallback (ArFunctor * functor, int position = 50) inline
Adds a callback mode for when trying to back up.
References ArGenericCallbackList< ArFunctor * >::addCallback(), and myDrivingBackwardsCallbacks.
void ArServerModeRatioDrive::addSafeDrivingCallback (ArFunctor * functor, int position = 50) inline
Adds a callback mode for when safe driving is activated.
References ArGenericCallbackList< ArFunctor * >::addCallback(), and mySafeDrivingCallbacks.
void ArServerModeRatioDrive::addToConfig (ArConfig * config, const char * section)
Adds to a config in a section.
Examples:
popupExample.cpp, and serverDemo.cpp.
References ArConfig::addParam(), ArActionRatioInput::addToConfig(), ArActionDeceleratingLimiter::addToConfig(), ArActionMovementParameters::addToConfig(), ArPriority::ADVANCED, myLimiterBackward, myLimiterForward, myLimiterLateralLeft, myLimiterLateralRight, myMovementParameters, myRatioAction, and myTimeout.
Referenced by main().
void ArServerModeRatioDrive::addUnsafeDrivingCallback (ArFunctor * functor, int position = 50) inline
Adds a callback mode for when unsafe driving is activated.
References ArGenericCallbackList< ArFunctor * >::addCallback(), and myUnsafeDrivingCallbacks.
void ArServerModeRatioDrive::deactivate (void) virtual
The function called when the mode is deactivated.
Subclasses must implement this, and also call baseDeactivate().
Implements ArServerMode.
References ArServerMode::baseDeactivate(), ArActionGroup::deactivate(), and myRatioDriveGroup.
virtual ArActionGroup* ArServerModeRatioDrive::getActionGroup (void) inline virtual
This function should return the action group this mode uses.
Reimplemented from ArServerMode.
References myRatioDriveGroup.
ArActionRatioInput* ArServerModeRatioDrive::getActionRatioInput (void) inline
References getSafeDriving(), getUseLocationDependentDevices(), myRatioAction, setSafeDriving(), and setUseLocationDependentDevices().
bool ArServerModeRatioDrive::getSafeDriving (void)
Gets whether we're driving safely or not.
References myDriveSafely.
Referenced by getActionRatioInput(), and serverGetSafeDrive().
bool ArServerModeRatioDrive::getUseLocationDependentDevices (void)
Gets whether we're using the range devices that depend on location.
References myUseLocationDependentDevices.
Referenced by getActionRatioInput().
void ArServerModeRatioDrive::joyUserTask (void) protected
References activate(), ArUtil::BIT15, ArRobot::enableMotors(), ArServerMode::forceUnlock(), ArServerMode::getActiveMode(), ArJoyHandler::getButton(), ArRobotJoyHandler::getButton1(), ArRobot::getFaultFlags(), ArServerMode::getName(), ArRobotJoyHandler::gotData(), ArJoyHandler::haveJoystick(), ArServerMode::isActive(), ArLog::log(), myJoyHandler, myLastRobotSafeDrive, ArServerMode::myName, ArServerMode::myRobot, myRobotJoyHandler, myRobotJoystickOverridesLock, myTakeControlOnJoystick, myUseComputerJoystick, myUseRobotJoystick, ArLog::Normal, ArServerMode::ourActiveMode, ArServerMode::ourActiveModeLocked, setSafeDriving(), and ArLog::Terse.
Referenced by remDrivingBackwardsCallback().
void ArServerModeRatioDrive::ratioDrive (double transRatio, double rotRatio, double throttleRatio, bool isActivating = false, double latRatio = 0)
Sets the ratio drive action.
Parameters
isActivating a bool set to true only if this method is called from the activate() method, otherwise false
transRatio Amount of forward velocity to request
rotRatio Amount of rotational velocity to request
throttleRatio Amount of speed to request
latRatio amount of lateral velocity to request (if robot supports it)
References ArAction::activate(), ArActionGroup::activateExclusive(), ArServerMode::baseActivate(), ArRobot::clearDirectMotion(), ArRobot::deactivateActions(), ArServerMode::getName(), ArCallbackList::invoke(), ArServerMode::isActive(), ArLog::log(), myDriveSafely, myDrivingBackwardsCallbacks, myLastCommand, myLatRatio, ArServerMode::myMode, ArServerMode::myName, myNewDriveSafely, myPrinting, myRatioAction, myRatioDriveGroup, ArServerMode::myRobot, myRotRatio, mySafeDrivingCallbacks, mySentRecenter, myThrottleRatio, myTransRatio, myUnsafeDrivingCallbacks, ArLog::Normal, ArServerMode::setActivityTimeToNow(), and ArTime::setToNow().
Referenced by activate(), serverRatioDrive(), setSafeDriving(), and userTask().
void ArServerModeRatioDrive::ratioFireCallback (void) protected
References ArLog::log(), myLatRatio, myPrinting, myRatioAction, myRotRatio, myThrottleRatio, myTransRatio, ArLog::Normal, and ArActionRatioInput::setRatios().
Referenced by remDrivingBackwardsCallback().
void ArServerModeRatioDrive::remDrivingBackwardsCallback (ArFunctor * functor) inline
Removes a callback mode for when trying to back up.
References client, joyUserTask(), myDrivingBackwardsCallbacks, ratioFireCallback(), ArGenericCallbackList< ArFunctor * >::remCallback(), serverGetSafeDrive(), serverRatioDrive(), serverSafeDrivingDisable(), serverSafeDrivingEnable(), and serverSetSafeDrive().
void ArServerModeRatioDrive::remSafeDrivingCallback (ArFunctor * functor) inline
Removes a callback mode for when safe driving is activated.
References mySafeDrivingCallbacks, and ArGenericCallbackList< ArFunctor * >::remCallback().
void ArServerModeRatioDrive::remUnsafeDrivingCallback (ArFunctor * functor) inline
Removes a callback mode for when unsafe driving is activated.
References myUnsafeDrivingCallbacks, and ArGenericCallbackList< ArFunctor * >::remCallback().
void ArServerModeRatioDrive::serverGetSafeDrive (ArServerClient * client, ArNetPacket * packet) protected
References getSafeDriving(), ArServerClient::sendPacketTcp(), and ArBasePacket::uByteToBuf().
Referenced by remDrivingBackwardsCallback().
void ArServerModeRatioDrive::serverRatioDrive (ArServerClient * client, ArNetPacket * packet) protected
References activate(), ArNetPacket::bufToDouble(), ArServerClient::getIPString(), ArServerMode::getName(), ArServerClient::hasGroupAccess(), ArServerMode::isActive(), ArRobot::lock(), ArLog::log(), myDriveSafely, myGotServerCommand, myPrinting, ArServerMode::myRobot, ArLog::Normal, ratioDrive(), serverSafeDrivingEnable(), and ArRobot::unlock().
Referenced by remDrivingBackwardsCallback().
void ArServerModeRatioDrive::serverSafeDrivingDisable (void) protected
References setSafeDriving().
Referenced by remDrivingBackwardsCallback().
void ArServerModeRatioDrive::serverSafeDrivingEnable (void) protected
References setSafeDriving().
Referenced by remDrivingBackwardsCallback(), and serverRatioDrive().
void ArServerModeRatioDrive::serverSetSafeDrive (ArServerClient * client, ArNetPacket * packet) protected
References ArBasePacket::bufToUByte(), and setSafeDriving().
Referenced by remDrivingBackwardsCallback().
void ArServerModeRatioDrive::setSafeDriving (bool safe, bool internal = false)
Sets whether we're safe driving or not.
References ArServerMode::isActive(), ArRobot::lock(), ArLog::log(), myDriveSafely, ArServerMode::myName, myNewDriveSafely, ArServerMode::myRobot, ArLog::Normal, ratioDrive(), and ArRobot::unlock().
Referenced by getActionRatioInput(), joyUserTask(), serverSafeDrivingDisable(), serverSafeDrivingEnable(), and serverSetSafeDrive().
void ArServerModeRatioDrive::setUseLocationDependentDevices (bool useLocationDependentDevices, bool internal = false)
Sets whether we're using the range devices that depend on location.
References ArRobot::lock(), ArLog::log(), myLimiterBackward, myLimiterForward, myLimiterLateralLeft, myLimiterLateralRight, ArServerMode::myName, ArServerMode::myRobot, myUseLocationDependentDevices, ArLog::Normal, ArActionDeceleratingLimiter::setUseLocationDependentDevices(), and ArRobot::unlock().
Referenced by getActionRatioInput().
void ArServerModeRatioDrive::userTask (void) virtual
The ArMode's user task, don't need one, subclass must provide if needed.
Reimplemented from ArServerMode.
References ArRobot::clearDirectMotion(), ArRobot::forceTryingToMove(), ArJoyHandler::getButton(), ArRobotJoyHandler::getButton1(), ArRobot::getStallValue(), ArRobotJoyHandler::gotData(), ArJoyHandler::haveJoystick(), ArRobot::isLeftMotorStalled(), ArRobot::isRightMotorStalled(), ArRobot::isStopped(), ArLog::log(), ArTime::mSecSince(), myGotServerCommand, myJoyHandler, myLastCommand, myLastTimedOut, myLatRatio, ArServerMode::myRobot, myRobotJoyHandler, myRotRatio, ArServerMode::myStatus, ArServerMode::myStatusSetThisCycle, myThrottleRatio, myTimeout, myTransRatio, myUseComputerJoystick, myUseRobotJoystick, myUseServerCommands, ArLog::Normal, ratioDrive(), ArServerMode::setActivityTimeToNow(), and ArRobot::stop().
Member Data Documentation
bool ArServerModeRatioDrive::myDriveSafely protected
Referenced by ArServerModeRatioDrive(), getSafeDriving(), ratioDrive(), serverRatioDrive(), and setSafeDriving().
ArCallbackList ArServerModeRatioDrive::myDrivingBackwardsCallbacks protected
Referenced by addDrivingBackwardsCallback(), ratioDrive(), and remDrivingBackwardsCallback().
bool ArServerModeRatioDrive::myGotServerCommand protected
Referenced by ArServerModeRatioDrive(), serverRatioDrive(), and userTask().
ArServerHandlerCommands* ArServerModeRatioDrive::myHandlerCommands protected
Referenced by addControlCommands(), and ArServerModeRatioDrive().
ArRatioInputJoydrive* ArServerModeRatioDrive::myJoydrive protected
Referenced by ArServerModeRatioDrive().
ArJoyHandler* ArServerModeRatioDrive::myJoyHandler protected
Referenced by ArServerModeRatioDrive(), joyUserTask(), and userTask().
ArFunctorC<ArServerModeRatioDrive> ArServerModeRatioDrive::myJoyUserTaskCB protected
Referenced by ArServerModeRatioDrive().
ArTime ArServerModeRatioDrive::myLastCommand protected
Referenced by ratioDrive(), and userTask().
bool ArServerModeRatioDrive::myLastRobotSafeDrive protected
Referenced by ArServerModeRatioDrive(), and joyUserTask().
bool ArServerModeRatioDrive::myLastTimedOut protected
Referenced by ArServerModeRatioDrive(), and userTask().
double ArServerModeRatioDrive::myLatRatio protected
Referenced by ratioDrive(), ratioFireCallback(), and userTask().
ArActionDeceleratingLimiter* ArServerModeRatioDrive::myLimiterBackward protected
Referenced by addToConfig(), ArServerModeRatioDrive(), and setUseLocationDependentDevices().
ArActionDeceleratingLimiter* ArServerModeRatioDrive::myLimiterForward protected
Referenced by addToConfig(), ArServerModeRatioDrive(), and setUseLocationDependentDevices().
ArActionDeceleratingLimiter* ArServerModeRatioDrive::myLimiterLateralLeft protected
Referenced by addToConfig(), ArServerModeRatioDrive(), and setUseLocationDependentDevices().
ArActionDeceleratingLimiter* ArServerModeRatioDrive::myLimiterLateralRight protected
Referenced by addToConfig(), ArServerModeRatioDrive(), and setUseLocationDependentDevices().
ArActionMovementParameters* ArServerModeRatioDrive::myMovementParameters protected
Referenced by addToConfig(), and ArServerModeRatioDrive().
bool ArServerModeRatioDrive::myNewDriveSafely protected
Referenced by ratioDrive(), and setSafeDriving().
bool ArServerModeRatioDrive::myPrinting protected
Referenced by ArServerModeRatioDrive(), ratioDrive(), ratioFireCallback(), and serverRatioDrive().
ArActionRatioInput* ArServerModeRatioDrive::myRatioAction protected
Referenced by addToConfig(), ArServerModeRatioDrive(), getActionRatioInput(), ratioDrive(), and ratioFireCallback().
ArActionGroup ArServerModeRatioDrive::myRatioDriveGroup protected
Referenced by ArServerModeRatioDrive(), deactivate(), getActionGroup(), and ratioDrive().
ArFunctorC<ArServerModeRatioDrive> ArServerModeRatioDrive::myRatioFireCB protected
Referenced by ArServerModeRatioDrive().
ArRatioInputRobotJoydrive* ArServerModeRatioDrive::myRobotJoydrive protected
Referenced by ArServerModeRatioDrive().
ArRobotJoyHandler* ArServerModeRatioDrive::myRobotJoyHandler protected
Referenced by ArServerModeRatioDrive(), joyUserTask(), and userTask().
bool ArServerModeRatioDrive::myRobotJoystickOverridesLock protected
Referenced by ArServerModeRatioDrive(), and joyUserTask().
double ArServerModeRatioDrive::myRotRatio protected
Referenced by ratioDrive(), ratioFireCallback(), and userTask().
ArCallbackList ArServerModeRatioDrive::mySafeDrivingCallbacks protected
Referenced by addSafeDrivingCallback(), ratioDrive(), and remSafeDrivingCallback().
bool ArServerModeRatioDrive::mySentRecenter protected
Referenced by ArServerModeRatioDrive(), and ratioDrive().
ArFunctor2C<ArServerModeRatioDrive, ArServerClient *, ArNetPacket *> ArServerModeRatioDrive::myServerGetSafeDriveCB protected
Referenced by ArServerModeRatioDrive().
ArFunctor2C<ArServerModeRatioDrive, ArServerClient *, ArNetPacket *> ArServerModeRatioDrive::myServerRatioDriveCB protected
Referenced by ArServerModeRatioDrive().
ArFunctorC<ArServerModeRatioDrive> ArServerModeRatioDrive::myServerSafeDrivingDisableCB protected
Referenced by addControlCommands().
ArFunctorC<ArServerModeRatioDrive> ArServerModeRatioDrive::myServerSafeDrivingEnableCB protected
Referenced by addControlCommands().
ArFunctor2C<ArServerModeRatioDrive, ArServerClient *, ArNetPacket *> ArServerModeRatioDrive::myServerSetSafeDriveCB protected
Referenced by ArServerModeRatioDrive().
bool ArServerModeRatioDrive::myTakeControlOnJoystick protected
Referenced by ArServerModeRatioDrive(), and joyUserTask().
double ArServerModeRatioDrive::myThrottleRatio protected
Referenced by ratioDrive(), ratioFireCallback(), and userTask().
double ArServerModeRatioDrive::myTimeout protected
Referenced by addToConfig(), ArServerModeRatioDrive(), and userTask().
double ArServerModeRatioDrive::myTransRatio protected
Referenced by ratioDrive(), ratioFireCallback(), and userTask().
ArCallbackList ArServerModeRatioDrive::myUnsafeDrivingCallbacks protected
Referenced by addUnsafeDrivingCallback(), ratioDrive(), and remUnsafeDrivingCallback().
bool ArServerModeRatioDrive::myUseComputerJoystick protected
Referenced by ArServerModeRatioDrive(), joyUserTask(), and userTask().
bool ArServerModeRatioDrive::myUseLocationDependentDevices protected
Referenced by ArServerModeRatioDrive(), getUseLocationDependentDevices(), and setUseLocationDependentDevices().
bool ArServerModeRatioDrive::myUseRobotJoystick protected
Referenced by ArServerModeRatioDrive(), joyUserTask(), and userTask().
bool ArServerModeRatioDrive::myUseServerCommands protected
Referenced by addControlCommands(), ArServerModeRatioDrive(), and userTask().
The documentation for this class was generated from the following files:
ArServerModeRatioDrive.h
ArServerModeRatioDrive.cpp