ArNetworking: ArMapChanger Class Reference
ArMapChanger Class Reference
Utility class used to apply incremental changes to an Aria map.
#include <ArMapChanger.h>
Classes
struct ClientChangeInfo
Accumulates the packet list that describes map changes received from a specified client.
Public Types
enum MapChangeReplyType { CHANGE_FAILED = 0, CHANGE_SUCCESS = 10 }
Reply status for a map change request.
Public Member Functions
virtual bool addChangeCB (ArFunctor2< ArServerClient *, std::list< ArNetPacket * > * > *functor)
Adds a callback to be invoked after the map has been changed on the server.
virtual void addPostWriteFileCB (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be invoked after the map file has been written.
virtual void addPreWriteFileCB (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be invoked before the map file is written.
virtual bool addRobotChangeReplyCB (ArFunctor2< ArServerClient *, ArNetPacket * > *functor)
Adds a callback to be invoked after the remote reply has been received.
virtual bool applyMapChanges (ArMapChangeDetails *changeDetails)
Applies the given map changes received from the client to the associated Aria map.
ArMapChanger (ArServerBase *server, ArMapInterface *map)
Constructs a server map changer.
ArMapChanger (ArClientSwitchManager *clientSwitch, ArServerBase *server, ArMapInterface *map)
Constructs a server map changer that can also originate changes (to the EM).
ArMapChanger (ArClientBase *client, const std::list< std::string > &infoNames)
Constructs a client map changer.
ArMapChanger (ArMapInterface *map)
Constructs a stand-alone map changer that will apply changes to the given map.
virtual bool remChangeCB (ArFunctor2< ArServerClient *, std::list< ArNetPacket * > * > *functor)
Removes a callback from the map change list.
virtual void remPostWriteFileCB (ArFunctor *functor)
Removes a callback from the post-write file list.
virtual void remPreWriteFileCB (ArFunctor *functor)
Removes a callback from the pre-write file list.
virtual bool remRobotChangeReplyCB (ArFunctor2< ArServerClient *, ArNetPacket * > *functor)
Removes a callback from the remote reply list.
virtual bool sendMapChanges (ArMapChangeDetails *changeDetails)
Sends the given map changes from the client to the server.
virtual bool sendPacketList (const std::list< ArNetPacket * > &packetList)
Transmits the given map change packet list from the client to the server.
virtual bool sendRobotMapChanges (ArMapChangeDetails *changeDetails)
Sends the given map changes from the robot to the central server.
virtual bool sendRobotPacketList (const std::list< ArNetPacket * > &packetList)
Transmit the given map change packet list from the robot to the central server.
virtual ~ArMapChanger ()
Destructor.
Static Public Attributes
static const char * CHANGES_IN_PROGRESS_PACKET_NAME
Name of a network packet that is broadcast when the map is being changed.
static const char * PROCESS_CHANGES_PACKET_NAME
Name of the network packet that contains the incremental map changes.
static const char * PROCESS_ROBOT_CHANGES_PACKET_NAME
Name of the network packet that contains incremental map changes originated by the robot.
static const char * ROBOT_CHANGES_COMPLETE_PACKET_NAME
Name of the network packet that is broadcast when map changes originated by the robot are complete.
Protected Types
enum { CHANGE_DATA_TYPE_COUNT = LAST_CHANGE_DATA_TYPE + 1, CHANGE_COMMAND_COUNT = LAST_CHANGE_COMMAND + 1, MAX_POINTS_IN_PACKET = 1000, MAX_LINES_IN_PACKET = 500 }
Miscellaneous constants.
enum MapChangeCommand {
START_CHANGES = 0, CONTINUE_CHANGES = 1, FINISH_CHANGES = 2, CANCEL_CHANGES = 3,
LAST_CHANGE_COMMAND = CANCEL_CHANGES
}
Indicates the current stage of the map change network packets.
enum MapChangeDataType {
NO_CHANGE = 0, SUMMARY_DATA = 1, INFO_DATA = 2, SUPPLEMENT_DATA = 3,
OBJECTS_DATA = 4, POINTS_DATA = 5, LINES_DATA = 6, LAST_CHANGE_DATA_TYPE = LINES_DATA
}
Type of data contained in the map change network packet.
Protected Member Functions
bool addFileLineSetPackets (MapChangeDataType dataType, ArMapChangeDetails::MapLineChangeType changeType, const char *scanType, const char *extra, ArMapFileLineSet *fileLineSet, std::list< ArNetPacket * > *packetListOut)
Creates network packets for the specified map change data and adds them to the given list.
bool addFileLineToPacketList (MapChangeDataType dataType, ArMapChangeDetails::MapLineChangeType changeType, const char *scanType, const ArMapFileLine &fileLine, std::list< ArNetPacket * > *packetListOut)
Creates network packets for the specified file line and adds them to the given list.
bool addGroupToPacketList (MapChangeDataType dataType, ArMapChangeDetails::MapLineChangeType changeType, const char *scanType, ArMapFileLineGroup &group, std::list< ArNetPacket * > *packetListOut)
Creates network packets for the specified file line group and adds them to the given list.
void addHeaderToPacket (MapChangeCommand command, MapChangeDataType dataType, ArMapChangeDetails::MapLineChangeType changeType, const char *scanType, ArNetPacket *packet)
Inserts header information into the given network packet.
bool addLinesPackets (ArMapChangeDetails::MapLineChangeType changeType, const char *scanType, std::vector< ArLineSegment > *lineSegmentList, std::list< ArNetPacket * > *packetListOut)
Creates network packets for the given map data lines and adds them to the given list.
bool addPointsPackets (ArMapChangeDetails::MapLineChangeType changeType, const char *scanType, std::vector< ArPose > *pointList, std::list< ArNetPacket * > *packetListOut)
Creates network packets for the given map data points and adds them to the given list.
void addToCallbackList (ArFunctor *functor, ArListPos::Pos position, std::list< ArFunctor * > *cbList)
Adds the given functor to the given callback list.
bool applyInfoChanges (ArMapChangeDetails *changeDetails)
Applies the given map changes to the info data in the map.
bool applyObjectChanges (ArMapChangeDetails *changeDetails)
Applies the given map changes to the object data in the map.
bool applyScanChanges (ArMapChangeDetails *changeDetails)
Applies all scan data changes that are contained in the given change details.
bool applyScanChanges (ArMapChangeDetails *changeDetails, const char *scanType, ArFileParser &parser)
Applies scan data changes for the specified scan type.
bool applySupplementChanges (ArMapChangeDetails *changeDetails)
Applies the given map changes to the supplemental data in the map.
bool convertChangeDetailsToPacketList (ArMapChangeDetails *changeDetails, std::list< ArNetPacket * > *packetListOut, bool isRelay=false)
Creates a list of network packets for the given map change details.
bool convertPacketListToChangeDetails (std::list< ArNetPacket * > &packetList, ArMapChangeDetails *changeDetailsOut)
Unpacks the given network packet list and populates the given map change details.
virtual void handleChangePacket (ArServerClient *client, ArNetPacket *packet)
Server handler for packets that contain map change details.
virtual void handleChangeReplyPacket (ArNetPacket *packet)
Client handler for the results of applying the map changes on the server.
virtual void handleChangesInProgressPacket (ArNetPacket *packet)
Client handler for the map-changes-in-progress broadcast packet.
virtual void handleClientShutdown ()
Client handler for when the robot disconnects or is shutdown.
virtual void handleIdleProcessingPacket (ArNetPacket *packet)
Client handler for the server's idle-processing-pending broadcast packet.
virtual void handleRobotChangeReplyPacket (ArServerClient *client, ArNetPacket *packet)
bool isIdleProcessingPending ()
Determines whether idle processing is pending on the server.
bool isMatchingObjects (ArMapObject *obj1, ArMapObject *obj2)
Determines whether the two given map objects are the same object.
void remFromCallbackList (ArFunctor *functor, std::list< ArFunctor * > *cbList)
Removes the given functor from the given callback list.
void resetPacketList (std::list< ArNetPacket * > *packetList)
Resets all of the network packets in the given list so that they can be read again.
bool unpackFileLineSet (ArNetPacket *packet, MapChangeDataType dataType, ArMapChangeDetails::MapLineChangeType changeType, const char *scanType, int *numGroups, int *numChildren, ArMapChangeDetails *changeDetails)
Unpacks the specified file line set from the given network packet.
bool unpackHeader (ArNetPacket *packet, MapChangeCommand *commandOut, ArMapId *origMapIdOut, ArMapId *newMapIdOut=NULL, MapChangeDataType *dataTypeOut=NULL, ArMapChangeDetails::MapLineChangeType *changeTypeOut=NULL, std::string *scanTypeOut=NULL)
Unpacks the header data from the given network packet.
bool unpackLines (ArNetPacket *packet, ArMapChangeDetails::MapLineChangeType changeType, const char *scanType, int *numLines, ArMapChangeDetails *changeDetails)
Unpacks the map data lines for the specified scan from the given network packet.
bool unpackPoints (ArNetPacket *packet, ArMapChangeDetails::MapLineChangeType changeType, const char *scanType, int *numPoints, ArMapChangeDetails *changeDetails)
Unpacks the map data points for the specified scan from the given network packet.
bool waitForCentralServerReply (ArTime &started)
bool waitForReply (ArTime &started)
Waits for a reply from the server.
Protected Attributes
std::list< ArFunctor2< ArServerClient *, std::list< ArNetPacket * > * > * > myChangeCBList
List of server client callbacks to be invoked after the map has been changed.
ArMapChangeDetails * myChangeDetails
Change details to apply to the Aria map.
ArClientBase * myClient
Associated client base; non-NULL only when changer instantiated on the client.
ClientChangeInfo * myClientInfo
Information regarding the server client that is currently sending map changes.
ArMutex myClientInfoMutex
Mutex that protects access to the myClientInfo member.
ArMutex myClientMutex
Mutex that protects access to the myClient member.
ArFunctorC< ArMapChanger > myClientShutdownCB
Handler invoked when the client shuts down.
ArClientSwitchManager * myClientSwitch
Associated client switch manager; non-NULL when changer instantiated on robot with EM.
ArFunctor2C< ArMapChanger, ArServerClient *, ArNetPacket * > myHandleChangePacketCB
Server handler for the network packets that describe map changes.
ArFunctor1C< ArMapChanger, ArNetPacket * > myHandleChangesInProgressPacketCB
Client handler for the map-changes-in-progress packet.
ArFunctor1C< ArMapChanger, ArNetPacket * > myHandleIdleProcessingPacketCB
Client handler for the idle-processing-in-progress packet.
ArFunctor1C< ArMapChanger, ArNetPacket * > myHandleReplyPacketCB
Client handler for the reply packet.
ArFunctor2C< ArMapChanger, ArServerClient *, ArNetPacket * > myHandleRobotReplyPacketCB
ArMutex myIdleProcessingMutex
Mutex that protects access to the myIsIdleProcessingPending member.
std::list< std::string > myInfoNames
Number of info types in the associated Aria map.
ArMutex myInterleaveMutex
Mutex that protects access to the interleave data.
bool myIsIdleProcessingPending
Whether the server has data to process once it becomes idle.
bool myIsServerClientInit
Whether the client switch manager's serverClient has been initialized with a handler (for EM)
bool myIsWaitingForReturn
Whether the client is waiting for a reply from the server.
ArMapInterface * myMap
Aria map currently in use.
std::list< ArFunctor * > myPostWriteCBList
List of callbacks to be invoked after the changed map file is written.
std::list< ArFunctor * > myPreWriteCBList
List of callbacks to be invoked before the changed map file is written.
bool myReadyForNextPacket
Whether the client is ready to send another packet.
std::list< ArFunctor2< ArServerClient *, ArNetPacket * > * > myRobotChangeReplyCBList
List of server client callbacks to be invoked after the map has been changed.
ArServerBase * myServer
Associated server base; non-NULL only when changer instantiated on the server.
ArMapInterface * myWorkingMap
Copy of the current Aria map, used to make sure the changes can be successfully made.
Detailed Description
Utility class used to apply incremental changes to an Aria map.
ArMapChanger is a helper class that can send and receive ArMapChangeDetails over the network and apply them to an associated Aria map. An instance of ArMapChanger must be instantiated on both the client and the server side. (Note that there are two different versions of the constructors for this.)
TODO: Possibly subclass this into ArClientMapChanger and ArServerMapChanger?
See also
ArMapChangeDetails
Member Enumeration Documentation
anonymous enum protected
Miscellaneous constants.
Enumerator
CHANGE_DATA_TYPE_COUNT
CHANGE_COMMAND_COUNT
MAX_POINTS_IN_PACKET
MAX_LINES_IN_PACKET
enum ArMapChanger::MapChangeCommand protected
Indicates the current stage of the map change network packets.
Enumerator
START_CHANGES
First packet that contains changes to be applied to the map.
CONTINUE_CHANGES
Request to continue applying changes to the map.
FINISH_CHANGES
Last packet that contains changes to be applied to the map.
CANCEL_CHANGES
Cancel the request to change the map.
LAST_CHANGE_COMMAND
Last value in the enumeration.
enum ArMapChanger::MapChangeDataType protected
Type of data contained in the map change network packet.
Enumerator
NO_CHANGE
No change data.
SUMMARY_DATA
Summary data, e.g. min/max pos, number of points.
INFO_DATA
Any of the info data, e.g. MapInfo, RouteInfo.
SUPPLEMENT_DATA
Miscellaneous supplemental data such as origin lat/long/alt.
OBJECTS_DATA
Map objects, i.e. Cairn lines.
POINTS_DATA
Map data points.
LINES_DATA
Map data lines.
LAST_CHANGE_DATA_TYPE
Last value in the enumeration.
enum ArMapChanger::MapChangeReplyType
Reply status for a map change request.
Enumerator
CHANGE_FAILED
CHANGE_SUCCESS
Constructor & Destructor Documentation
ArMapChanger::ArMapChanger (ArServerBase * server, ArMapInterface * map)
Constructs a server map changer.
The map changer will automatically apply the received map change details to the given map.
Parameters
server the ArServerBase * that receives the network packets
map the ArMapInterface * to which to apply the map changes
References ArServerBase::addData(), CHANGES_IN_PROGRESS_PACKET_NAME, ArMapInfoInterface::getInfoNames(), myHandleChangePacketCB, myInfoNames, myMap, myServer, PROCESS_CHANGES_PACKET_NAME, and PROCESS_ROBOT_CHANGES_PACKET_NAME.
ArMapChanger::ArMapChanger (ArClientSwitchManager * clientSwitch, ArServerBase * server, ArMapInterface * map)
Constructs a server map changer that can also originate changes (to the EM).
The map changer will automatically apply the received map change details to the given map.
Parameters
clientSwitch the ArClientSwitchManager * that communicates to the EM
server the ArServerBase * that receives the network packets
map the ArMapInterface * to which to apply the map changes
References ArServerBase::addData(), CHANGES_IN_PROGRESS_PACKET_NAME, ArClientSwitchManager::getCentralServerHostName(), ArMapInfoInterface::getInfoNames(), myClientSwitch, myHandleChangePacketCB, myHandleRobotReplyPacketCB, myInfoNames, myMap, myServer, PROCESS_CHANGES_PACKET_NAME, PROCESS_ROBOT_CHANGES_PACKET_NAME, and ROBOT_CHANGES_COMPLETE_PACKET_NAME.
ArMapChanger::ArMapChanger (ArClientBase * client, const std::list< std::string > & infoNames)
Constructs a client map changer.
The map changer will send map change details to the server. The application must request this by calling sendMapChanges.
Parameters
client the ArClientBase * which is used to send the map change details
infoNames the list of info names included in the map
References ArClientBase::addDisconnectOnErrorCB(), ArClientBase::addHandler(), ArClientBase::addServerShutdownCB(), CHANGES_IN_PROGRESS_PACKET_NAME, ArClientBase::dataExists(), ArMutex::lock(), ArLog::log(), myClient, myClientInfoMutex, myClientMutex, myClientShutdownCB, myHandleChangesInProgressPacketCB, myHandleIdleProcessingPacketCB, myHandleReplyPacketCB, ArLog::Normal, PROCESS_CHANGES_PACKET_NAME, ArClientBase::request(), ArClientBase::requestOnce(), ArMutex::setLogName(), and ArMutex::unlock().
ArMapChanger::ArMapChanger (ArMapInterface * map)
Constructs a stand-alone map changer that will apply changes to the given map.
This method is primarily used for debugging.
Parameters
map the ArMapInterface * to which to apply the map changes
References ArMapInfoInterface::getInfoNames(), myInfoNames, and myMap.
ArMapChanger::~ArMapChanger () virtual
Destructor.
References CHANGES_IN_PROGRESS_PACKET_NAME, myClient, myClientShutdownCB, myHandleChangesInProgressPacketCB, myHandleIdleProcessingPacketCB, myHandleReplyPacketCB, PROCESS_CHANGES_PACKET_NAME, ArClientBase::remDisconnectOnErrorCB(), ArClientBase::remHandler(), and ArClientBase::remServerShutdownCB().
Member Function Documentation
bool ArMapChanger::addChangeCB (ArFunctor2< ArServerClient *, std::list< ArNetPacket * > * > * functor) virtual
Adds a callback to be invoked after the map has been changed on the server.
This method is primarily used on the central server. After the map changes are successfully applied to its map, they are propagated to all of the connected robots.
References myChangeCBList, and remChangeCB().
bool ArMapChanger::addFileLineSetPackets (MapChangeDataType dataType, ArMapChangeDetails::MapLineChangeType changeType, const char * scanType, const char * extra, ArMapFileLineSet * fileLineSet, std::list< ArNetPacket * > * packetListOut) protected
Creates network packets for the specified map change data and adds them to the given list.
Parameters
dataType the MapChangeDataType that specifies which map data is to be added
changeType the MapLineChangeType that specifies the type of map change (lines added or deleted)
scanType the char * identifier of the scan source to add; valid only when dataType is SUMMARY_DATA
extra an optional const char * identifier that clarifies which data to add; when dataType is INFO_DATA, this is the info name; otherwise, ignored
fileLineSet the ArMapFileLineSet * component of the map change details that is to be converted to network packets
packetListOut the list of ArNetPackets to which new packets are added
References addGroupToPacketList(), addHeaderToPacket(), ArBasePacket::byte4ToBuf(), CONTINUE_CHANGES, INFO_DATA, ArUtil::isStrEmpty(), and myInfoNames.
Referenced by convertChangeDetailsToPacketList().
bool ArMapChanger::addFileLineToPacketList (MapChangeDataType dataType, ArMapChangeDetails::MapLineChangeType changeType, const char * scanType, const ArMapFileLine & fileLine, std::list< ArNetPacket * > * packetListOut) protected
Creates network packets for the specified file line and adds them to the given list.
References addHeaderToPacket(), addPointsPackets(), ArBasePacket::byte4ToBuf(), CONTINUE_CHANGES, ArBasePacket::getLength(), ArMapFileLine::getLineNum(), ArMapFileLine::getLineText(), ArBasePacket::getMaxLength(), ArLog::log(), ArLog::Normal, and ArBasePacket::strToBuf().
Referenced by addGroupToPacketList().
bool ArMapChanger::addGroupToPacketList (MapChangeDataType dataType, ArMapChangeDetails::MapLineChangeType changeType, const char * scanType, ArMapFileLineGroup & group, std::list< ArNetPacket * > * packetListOut) protected
Creates network packets for the specified file line group and adds them to the given list.
References addFileLineToPacketList(), addHeaderToPacket(), ArBasePacket::byte4ToBuf(), CONTINUE_CHANGES, ArMapFileLineGroup::getChildLines(), ArBasePacket::getLength(), ArMapFileLine::getLineNum(), ArMapFileLine::getLineText(), ArBasePacket::getMaxLength(), ArMapFileLineGroup::getParentLine(), and ArBasePacket::strToBuf().
Referenced by addFileLineSetPackets().
void ArMapChanger::addHeaderToPacket (MapChangeCommand command, MapChangeDataType dataType, ArMapChangeDetails::MapLineChangeType changeType, const char * scanType, ArNetPacket * packet) protected
Inserts header information into the given network packet.
Parameters
command the MapChangeCommand that specifies which command identifier to add to this packet
dataType the MapChangeDataType that specifies which map data is to be added
changeType the MapLineChangeType that specifies the type of map change (lines added or deleted)
scanType the char * identifier of the scan source to add; valid only when dataType is SUMMARY_DATA
packet the ArNetPacket * to be modified; must be non-NULL
References CONTINUE_CHANGES, ArMapChangeDetails::getNewMapId(), ArMapChangeDetails::getOrigMapId(), ArLog::log(), myChangeDetails, ArLog::Normal, ArBasePacket::strToBuf(), ArMapId::toPacket(), ArBasePacket::uByte2ToBuf(), and ArBasePacket::uByteToBuf().
Referenced by addFileLineSetPackets(), addFileLineToPacketList(), addGroupToPacketList(), addLinesPackets(), addPointsPackets(), and convertChangeDetailsToPacketList().
bool ArMapChanger::addLinesPackets (ArMapChangeDetails::MapLineChangeType changeType, const char * scanType, std::vector< ArLineSegment > * lineSegmentList, std::list< ArNetPacket * > * packetListOut) protected
Creates network packets for the given map data lines and adds them to the given list.
References addHeaderToPacket(), ArBasePacket::byte4ToBuf(), CONTINUE_CHANGES, convertPacketListToChangeDetails(), LINES_DATA, and MAX_LINES_IN_PACKET.
Referenced by addPointsPackets(), and convertChangeDetailsToPacketList().
bool ArMapChanger::addPointsPackets (ArMapChangeDetails::MapLineChangeType changeType, const char * scanType, std::vector< ArPose > * pointList, std::list< ArNetPacket * > * packetListOut) protected
Creates network packets for the given map data points and adds them to the given list.
References addHeaderToPacket(), addLinesPackets(), ArBasePacket::byte4ToBuf(), CONTINUE_CHANGES, MAX_POINTS_IN_PACKET, and POINTS_DATA.
Referenced by addFileLineToPacketList(), and convertChangeDetailsToPacketList().
void ArMapChanger::addPostWriteFileCB (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST) virtual
Adds a callback to be invoked after the map file has been written.
This method is primarily used to restore the server's directory write status, if necessary.
References addToCallbackList(), and myPostWriteCBList.
void ArMapChanger::addPreWriteFileCB (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST) virtual
Adds a callback to be invoked before the map file is written.
This method is primarily used to temporarily make the server's directory writeable, if necessary.
References addToCallbackList(), and myPreWriteCBList.
bool ArMapChanger::addRobotChangeReplyCB (ArFunctor2< ArServerClient *, ArNetPacket * > * functor) virtual
Adds a callback to be invoked after the remote reply has been received.
This method is primarily used on the robot. After the ARCL originated changes have been applied by the Enterprise Manager, this callback list is invoked for other interested parties.
References myRobotChangeReplyCBList, and remRobotChangeReplyCB().
Referenced by remChangeCB().
void ArMapChanger::addToCallbackList (ArFunctor * functor, ArListPos::Pos position, std::list< ArFunctor * > * cbList) protected
Adds the given functor to the given callback list.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), and ArLog::Terse.
Referenced by addPostWriteFileCB(), and addPreWriteFileCB().
bool ArMapChanger::applyInfoChanges (ArMapChangeDetails * changeDetails) protected
Applies the given map changes to the info data in the map.
Parameters
changeDetails the ArMapChangeDetails * that describes how the map should be modified; must be non-NULL
References ArMapChangeDetails::ADDITIONS, ArArgumentBuilder::addPlain(), ArArgumentBuilder::compressQuoted(), convertChangeDetailsToPacketList(), ArUtil::deleteSet(), ArMapChangeDetails::DELETIONS, ArMapFileLineSet::find(), ArMapChangeDetails::findChangedInfoNames(), ArMapChangeDetails::getChangedInfoLines(), ArMapFileLineGroup::getChildLines(), ArArgumentBuilder::getFullString(), ArMapInfoInterface::getInfo(), ArMapFileLine::getLineNum(), ArMapFileLine::getLineText(), ArMapFileLineGroup::getParentLine(), IFDEBUG, ArMapChangeDetails::isChildArg(), ArLog::log(), myWorkingMap, ArLog::Normal, ArArgumentBuilder::removeArg(), and ArMapInfoInterface::setInfo().
Referenced by applyMapChanges().
bool ArMapChanger::applyMapChanges (ArMapChangeDetails * changeDetails) virtual
Applies the given map changes received from the client to the associated Aria map.
References ArMapInterface::addPostWriteFileCB(), ArMapInterface::addPreWriteFileCB(), applyInfoChanges(), applyObjectChanges(), applyScanChanges(), applySupplementChanges(), ArMapInterface::calculateChecksum(), ArMapInterface::clone(), ArMD5Calculator::DIGEST_LENGTH, ArMD5Calculator::DISPLAY_LENGTH, ArMapId::getChecksum(), ArMapId::getDisplayChecksum(), ArMapId::getFileName(), ArMapInterface::getMapId(), ArMapChangeDetails::getNewMapId(), ArMapId::getTimestamp(), ArMapId::isNull(), ArMapInterface::lock(), ArMapId::log(), ArLog::log(), ArMapInterface::mapChanged(), myMap, myPostWriteCBList, myPreWriteCBList, myWorkingMap, ArLog::Normal, ArMapInterface::remPostWriteFileCB(), ArMapInterface::remPreWriteFileCB(), ArMapInterface::set(), ArMapChangeDetails::setNewMapId(), ArLog::Terse, ArMD5Calculator::toDisplay(), ArMapInterface::unlock(), and ArMapInterface::writeFile().
Referenced by handleChangePacket().
bool ArMapChanger::applyObjectChanges (ArMapChangeDetails * changeDetails) protected
Applies the given map changes to the object data in the map.
Parameters
changeDetails the ArMapChangeDetails * that describes how the map should be modified; must be non-NULL
References ArMapChangeDetails::ADDITIONS, ArArgumentBuilder::addPlain(), ArMapObject::createMapObject(), ArUtil::deleteSet(), ArMapChangeDetails::DELETIONS, ArMapChangeDetails::getChangedObjectLines(), ArMapFileLine::getLineText(), ArMapObjectsInterface::getMapObjects(), ArMapFileLineGroup::getParentLine(), isMatchingObjects(), ArMapObject::log(), ArLog::log(), myWorkingMap, ArLog::Normal, ArArgumentBuilder::removeArg(), and ArMapObjectsInterface::setMapObjects().
Referenced by applyMapChanges().
bool ArMapChanger::applyScanChanges (ArMapChangeDetails * changeDetails) protected
Applies all scan data changes that are contained in the given change details.
Scan data include summary data, map data points, and map data lines. If the map contains scan data for multiple sources, then this method applies all of the applicable changes.
An Aria map must have been previously associated with the map changer.
References ArMapScanInterface::addToFileParser(), ArMapChangeDetails::getScanTypes(), myWorkingMap, and ArMapScanInterface::remFromFileParser().
Referenced by applyMapChanges().
bool ArMapChanger::applyScanChanges (ArMapChangeDetails * changeDetails, const char * scanType, ArFileParser & parser) protected
Applies scan data changes for the specified scan type.
Parameters
changeDetails the ArMapChangeDetails * that describes how the map should be modified; must be non-NULL
scanType the char * identifier of the scan type to be updated
parser the ArFileParser used to parse the changeDetails
References ArMapChangeDetails::ADDITIONS, ArMapChangeDetails::DELETIONS, ArMapChangeDetails::getChangedLineSegments(), ArMapChangeDetails::getChangedPoints(), ArMapChangeDetails::getChangedSummaryLines(), ArMapScanInterface::getLines(), ArMapFileLine::getLineText(), ArMapScanInterface::getNumLines(), ArMapScanInterface::getNumPoints(), ArMapFileLineGroup::getParentLine(), ArMapScanInterface::getPoints(), ArLog::log(), ArTime::mSecSince(), myWorkingMap, ArLog::Normal, and ArFileParser::parseLine().
bool ArMapChanger::applySupplementChanges (ArMapChangeDetails * changeDetails) protected
Applies the given map changes to the supplemental data in the map.
Parameters
changeDetails the ArMapChangeDetails * that describes how the map should be modified; must be non-NULL
References ArMapChangeDetails::ADDITIONS, ArMapScanInterface::addToFileParser(), ArMapChangeDetails::getChangedSupplementLines(), ArMapFileLine::getLineText(), ArMapFileLineGroup::getParentLine(), ArLog::log(), myWorkingMap, ArLog::Normal, ArFileParser::parseLine(), and ArMapScanInterface::remFromFileParser().
Referenced by applyMapChanges().
bool ArMapChanger::convertChangeDetailsToPacketList (ArMapChangeDetails * changeDetails, std::list< ArNetPacket * > * packetListOut, bool isRelay = false) protected
Creates a list of network packets for the given map change details.
References addFileLineSetPackets(), addHeaderToPacket(), ArMapChangeDetails::ADDITIONS, addLinesPackets(), addPointsPackets(), ArMapChangeDetails::CHANGE_TYPE_COUNT, FINISH_CHANGES, ArMapChangeDetails::getChangedInfoLines(), ArMapChangeDetails::getChangedLineSegments(), ArMapChangeDetails::getChangedObjectLines(), ArMapChangeDetails::getChangedPoints(), ArMapChangeDetails::getChangedSummaryLines(), ArMapChangeDetails::getChangedSupplementLines(), ArMapChangeDetails::getNewMapId(), ArMapChangeDetails::getScanTypes(), ArMapId::getSourceName(), INFO_DATA, ArUtil::isStrEmpty(), ArLog::log(), myChangeDetails, myInfoNames, NO_CHANGE, ArLog::Normal, OBJECTS_DATA, ArMapChangeDetails::setNewMapId(), ArMapId::setTimestamp(), START_CHANGES, SUMMARY_DATA, and SUPPLEMENT_DATA.
Referenced by applyInfoChanges(), handleChangePacket(), sendMapChanges(), and sendRobotMapChanges().
bool ArMapChanger::convertPacketListToChangeDetails (std::list< ArNetPacket * > & packetList, ArMapChangeDetails * changeDetailsOut) protected
Unpacks the given network packet list and populates the given map change details.
References ArMapChangeDetails::ADDITIONS, CONTINUE_CHANGES, INFO_DATA, LINES_DATA, NO_CHANGE, OBJECTS_DATA, POINTS_DATA, ArMapChangeDetails::setNewMapId(), ArMapChangeDetails::setOrigMapId(), START_CHANGES, SUMMARY_DATA, SUPPLEMENT_DATA, unpackFileLineSet(), unpackHeader(), unpackLines(), and unpackPoints().
Referenced by addLinesPackets(), and handleChangePacket().
void ArMapChanger::handleChangePacket (ArServerClient * client, ArNetPacket * packet) protected virtual
Server handler for packets that contain map change details.
References ArMapChanger::ClientChangeInfo::addPacket(), applyMapChanges(), ArServerBase::broadcastPacketTcp(), CANCEL_CHANGES, CHANGE_FAILED, CHANGE_SUCCESS, CHANGES_IN_PROGRESS_PACKET_NAME, CONTINUE_CHANGES, convertChangeDetailsToPacketList(), convertPacketListToChangeDetails(), ArServerClient::findCommandFromName(), FINISH_CHANGES, ArMapId::getFileName(), ArMapInterface::getMapId(), ArMapChangeDetails::getNewMapId(), ArFunctor2< P1, P2 >::invoke(), ArMapId::isNull(), ArMapId::isSameFile(), ArMapId::isValidTimestamp(), ArMutex::lock(), ArLog::log(), ArMapId::log(), ArMapChangeDetails::log(), myChangeCBList, ArMapChanger::ClientChangeInfo::myClient, myClientInfo, myClientInfoMutex, ArMapChanger::ClientChangeInfo::myLastActivityTime, myMap, ArMapChanger::ClientChangeInfo::myPacketList, myServer, ArLog::Normal, resetPacketList(), ArTime::secSince(), ArServerClient::sendPacketTcp(), ArNetPacket::setCommand(), START_CHANGES, ArUtil::strcasecmp(), ArLog::Terse, ArMapId::toPacket(), ArBasePacket::uByte2ToBuf(), ArBasePacket::uByteToBuf(), ArMutex::unlock(), and unpackHeader().
void ArMapChanger::handleChangeReplyPacket (ArNetPacket * packet) protected virtual
Client handler for the results of applying the map changes on the server.
References ArBasePacket::bufToUByte2(), CHANGE_SUCCESS, IFDEBUG, ArMutex::lock(), ArLog::log(), myInterleaveMutex, myIsWaitingForReturn, myReadyForNextPacket, ArLog::Normal, and ArMutex::unlock().
void ArMapChanger::handleChangesInProgressPacket (ArNetPacket * packet) protected virtual
Client handler for the map-changes-in-progress broadcast packet.
References ArBasePacket::bufToUByte(), ArLog::log(), and ArLog::Normal.
void ArMapChanger::handleClientShutdown () protected virtual
Client handler for when the robot disconnects or is shutdown.
References ArMutex::lock(), ArLog::log(), myClient, myClientMutex, ArLog::Normal, and ArMutex::unlock().
void ArMapChanger::handleIdleProcessingPacket (ArNetPacket * packet) protected virtual
Client handler for the server's idle-processing-pending broadcast packet.
References ArBasePacket::bufToByte(), ArMutex::lock(), ArLog::log(), myIdleProcessingMutex, myIsIdleProcessingPending, ArLog::Normal, and ArMutex::unlock().
void ArMapChanger::handleRobotChangeReplyPacket (ArServerClient * client, ArNetPacket * packet) protected virtual
References ArBasePacket::bufToStr(), ArBasePacket::bufToUByte2(), CHANGE_SUCCESS, IFDEBUG, ArFunctor2< P1, P2 >::invoke(), ArMutex::lock(), ArLog::log(), myInterleaveMutex, myIsWaitingForReturn, myReadyForNextPacket, myRobotChangeReplyCBList, ArLog::Normal, ArNetPacket::resetRead(), and ArMutex::unlock().
bool ArMapChanger::isIdleProcessingPending () protected
Determines whether idle processing is pending on the server.
References ArMutex::lock(), myIdleProcessingMutex, myIsIdleProcessingPending, and ArMutex::unlock().
Referenced by waitForCentralServerReply(), and waitForReply().
bool ArMapChanger::isMatchingObjects (ArMapObject * obj1, ArMapObject * obj2) protected
Determines whether the two given map objects are the same object.
If the objects have a name, then the name must be identical. Otherwise, the type and position must be the same.
References ArMapObject::getDescription(), ArMapObject::getFromPose(), ArMapObject::getFromToSegments(), ArMapObject::getIconName(), ArMapObject::getName(), ArMapObject::getPose(), ArMapObject::getToPose(), ArMapObject::getType(), ArMapObject::hasFromTo(), ArUtil::isStrEmpty(), and ArUtil::strcasecmp().
Referenced by applyObjectChanges().
bool ArMapChanger::remChangeCB (ArFunctor2< ArServerClient *, std::list< ArNetPacket * > * > * functor) virtual
Removes a callback from the map change list.
References addRobotChangeReplyCB(), and myChangeCBList.
Referenced by addChangeCB().
void ArMapChanger::remFromCallbackList (ArFunctor * functor, std::list< ArFunctor * > * cbList) protected
Removes the given functor from the given callback list.
References ArLog::log(), and ArLog::Terse.
Referenced by remPostWriteFileCB(), and remPreWriteFileCB().
void ArMapChanger::remPostWriteFileCB (ArFunctor * functor) virtual
Removes a callback from the post-write file list.
References myPostWriteCBList, and remFromCallbackList().
void ArMapChanger::remPreWriteFileCB (ArFunctor * functor) virtual
Removes a callback from the pre-write file list.
References myPreWriteCBList, and remFromCallbackList().
bool ArMapChanger::remRobotChangeReplyCB (ArFunctor2< ArServerClient *, ArNetPacket * > * functor) virtual
Removes a callback from the remote reply list.
References myRobotChangeReplyCBList.
Referenced by addRobotChangeReplyCB().
void ArMapChanger::resetPacketList (std::list< ArNetPacket * > * packetList) protected
Resets all of the network packets in the given list so that they can be read again.
References ArNetPacket::resetRead().
Referenced by handleChangePacket().
bool ArMapChanger::sendMapChanges (ArMapChangeDetails * changeDetails) virtual
Sends the given map changes from the client to the server.
References convertChangeDetailsToPacketList(), ArUtil::deleteSet(), ArMapChangeDetails::getNewMapId(), ArMapChangeDetails::getOrigMapId(), ArClientBase::getRobotName(), ArMapId::getSourceName(), ArUtil::isStrEmpty(), ArMutex::lock(), ArLog::log(), myClient, myClientMutex, myInterleaveMutex, myIsWaitingForReturn, myReadyForNextPacket, ArLog::Normal, sendPacketList(), ArMapChangeDetails::setNewMapId(), ArMapChangeDetails::setOrigMapId(), ArMapId::setSourceName(), ArMapId::setTimestamp(), ArUtil::strcasecmp(), ArLog::Terse, and ArMutex::unlock().
bool ArMapChanger::sendPacketList (const std::list< ArNetPacket * > & packetList) virtual
Transmits the given map change packet list from the client to the server.
References ArMutex::lock(), ArLog::log(), myClient, myClientMutex, PROCESS_CHANGES_PACKET_NAME, ArClientBase::requestOnce(), ArTime::setToNow(), ArLog::Terse, ArMutex::unlock(), and waitForReply().
Referenced by sendMapChanges().
bool ArMapChanger::sendRobotMapChanges (ArMapChangeDetails * changeDetails) virtual
Sends the given map changes from the robot to the central server.
References convertChangeDetailsToPacketList(), ArUtil::deleteSet(), ArClientSwitchManager::getIdentifier(), ArMapChangeDetails::getNewMapId(), ArMapChangeDetails::getOrigMapId(), ArClientSwitchManager::getServerClient(), ArMapId::getSourceName(), ArUtil::isStrEmpty(), ArMutex::lock(), ArLog::log(), myClientMutex, myClientSwitch, myInterleaveMutex, myIsWaitingForReturn, myReadyForNextPacket, ArLog::Normal, sendRobotPacketList(), ArMapChangeDetails::setNewMapId(), ArMapChangeDetails::setOrigMapId(), ArMapId::setSourceName(), ArMapId::setTimestamp(), ArUtil::strcasecmp(), ArLog::Terse, and ArMutex::unlock().
bool ArMapChanger::sendRobotPacketList (const std::list< ArNetPacket * > & packetList) virtual
Transmit the given map change packet list from the robot to the central server.
References ArServerClient::broadcastPacketTcp(), ArClientSwitchManager::getServerClient(), ArMutex::lock(), ArLog::log(), myClientMutex, myClientSwitch, ArLog::Normal, PROCESS_ROBOT_CHANGES_PACKET_NAME, ArNetPacket::setCommand(), ArTime::setToNow(), ArLog::Terse, and ArMutex::unlock().
Referenced by sendRobotMapChanges().
bool ArMapChanger::unpackFileLineSet (ArNetPacket * packet, MapChangeDataType dataType, ArMapChangeDetails::MapLineChangeType changeType, const char * scanType, int * numGroups, int * numChildren, ArMapChangeDetails * changeDetails) protected
Unpacks the specified file line set from the given network packet.
The file line set is added to the given change details.
References ArBasePacket::bufToByte4(), ArBasePacket::bufToStr(), ArMapChangeDetails::getChangedInfoLines(), ArMapChangeDetails::getChangedObjectLines(), ArMapChangeDetails::getChangedSummaryLines(), ArMapFileLineGroup::getChildLines(), ArBasePacket::getLength(), ArMapFileLine::getLineNum(), ArMapFileLineGroup::getParentLine(), ArBasePacket::getReadLength(), IFDEBUG, INFO_DATA, ArBasePacket::isValid(), ArLog::log(), myInfoNames, ArLog::Normal, OBJECTS_DATA, and SUMMARY_DATA.
Referenced by convertPacketListToChangeDetails().
bool ArMapChanger::unpackHeader (ArNetPacket * packet, MapChangeCommand * commandOut, ArMapId * origMapIdOut, ArMapId * newMapIdOut = NULL, MapChangeDataType * dataTypeOut = NULL, ArMapChangeDetails::MapLineChangeType * changeTypeOut = NULL, std::string * scanTypeOut = NULL) protected
Unpacks the header data from the given network packet.
Parameters
packet the ArNetPacket * from which to extract the header information; must be non-NULL
commandOut the MapChangeCommand * extracted from the packet
origMapIdOut the original ArMapId * extracted from the packet
newMapIdOut the optional new ArMapId * extracted from the packet
dataTypeOut the optional MapChangeDataType * extracted from the packet
changeTypeOut the optional MapLineChangeType * extracted from the packet
scanTypeOut the optional std::string * extracted from the packet
Returns
bool true if all of the header information was succesfully extracted; false, otherwise
References ArBasePacket::bufToStr(), ArBasePacket::bufToUByte(), ArBasePacket::bufToUByte2(), CONTINUE_CHANGES, ArMapId::fromPacket(), LAST_CHANGE_COMMAND, LAST_CHANGE_DATA_TYPE, ArMapChangeDetails::LAST_CHANGE_TYPE, ArLog::log(), and ArLog::Normal.
Referenced by convertPacketListToChangeDetails(), and handleChangePacket().
bool ArMapChanger::unpackLines (ArNetPacket * packet, ArMapChangeDetails::MapLineChangeType changeType, const char * scanType, int * numLines, ArMapChangeDetails * changeDetails) protected
Unpacks the map data lines for the specified scan from the given network packet.
The data lines are added to the given change details.
References ArBasePacket::bufToByte4(), ArMapChangeDetails::getChangedLineSegments(), and MAX_LINES_IN_PACKET.
Referenced by convertPacketListToChangeDetails().
bool ArMapChanger::unpackPoints (ArNetPacket * packet, ArMapChangeDetails::MapLineChangeType changeType, const char * scanType, int * numPoints, ArMapChangeDetails * changeDetails) protected
Unpacks the map data points for the specified scan from the given network packet.
The data points are added to the given change details.
References ArBasePacket::bufToByte4(), ArMapChangeDetails::getChangedPoints(), ArLog::log(), MAX_POINTS_IN_PACKET, and ArLog::Normal.
Referenced by convertPacketListToChangeDetails().
bool ArMapChanger::waitForCentralServerReply (ArTime & started) protected
References isIdleProcessingPending(), ArMutex::lock(), ArLog::log(), myInterleaveMutex, myIsWaitingForReturn, myReadyForNextPacket, ArLog::Normal, ArTime::secSince(), ArTime::setToNow(), ArUtil::sleep(), and ArMutex::unlock().
bool ArMapChanger::waitForReply (ArTime & started) protected
Waits for a reply from the server.
If a reply is not received within 30 seconds, this method will timeout and return false.
Returns
bool true if the reply was received; false otherwise
References isIdleProcessingPending(), ArMutex::lock(), ArLog::log(), myClient, myClientMutex, myInterleaveMutex, myIsWaitingForReturn, myReadyForNextPacket, ArLog::Normal, ArTime::secSince(), ArTime::setToNow(), ArUtil::sleep(), and ArMutex::unlock().
Referenced by sendPacketList().
Member Data Documentation
const char * ArMapChanger::CHANGES_IN_PROGRESS_PACKET_NAME static
Initial value:
=
                              "mapChangesInProgress"
Name of a network packet that is broadcast when the map is being changed.
Referenced by ArMapChanger(), handleChangePacket(), and ~ArMapChanger().
std::list< ArFunctor2<ArServerClient *, std::list<ArNetPacket *> *> *> ArMapChanger::myChangeCBList protected
List of server client callbacks to be invoked after the map has been changed.
Referenced by addChangeCB(), handleChangePacket(), and remChangeCB().
ArMapChangeDetails* ArMapChanger::myChangeDetails protected
Change details to apply to the Aria map.
Referenced by addHeaderToPacket(), and convertChangeDetailsToPacketList().
ArClientBase* ArMapChanger::myClient protected
Associated client base; non-NULL only when changer instantiated on the client.
Referenced by ArMapChanger(), handleClientShutdown(), sendMapChanges(), sendPacketList(), waitForReply(), and ~ArMapChanger().
ClientChangeInfo* ArMapChanger::myClientInfo protected
Information regarding the server client that is currently sending map changes.
Referenced by handleChangePacket().
ArMutex ArMapChanger::myClientInfoMutex protected
Mutex that protects access to the myClientInfo member.
Referenced by ArMapChanger(), and handleChangePacket().
ArMutex ArMapChanger::myClientMutex protected
Mutex that protects access to the myClient member.
Referenced by ArMapChanger(), handleClientShutdown(), sendMapChanges(), sendPacketList(), sendRobotMapChanges(), sendRobotPacketList(), and waitForReply().
ArFunctorC<ArMapChanger> ArMapChanger::myClientShutdownCB protected
Handler invoked when the client shuts down.
Referenced by ArMapChanger(), and ~ArMapChanger().
ArClientSwitchManager* ArMapChanger::myClientSwitch protected
Associated client switch manager; non-NULL when changer instantiated on robot with EM.
Referenced by ArMapChanger(), sendRobotMapChanges(), and sendRobotPacketList().
ArFunctor2C<ArMapChanger, ArServerClient *, ArNetPacket *> ArMapChanger::myHandleChangePacketCB protected
Server handler for the network packets that describe map changes.
Referenced by ArMapChanger().
ArFunctor1C<ArMapChanger, ArNetPacket *> ArMapChanger::myHandleChangesInProgressPacketCB protected
Client handler for the map-changes-in-progress packet.
Referenced by ArMapChanger(), and ~ArMapChanger().
ArFunctor1C<ArMapChanger, ArNetPacket *> ArMapChanger::myHandleIdleProcessingPacketCB protected
Client handler for the idle-processing-in-progress packet.
Referenced by ArMapChanger(), and ~ArMapChanger().
ArFunctor1C<ArMapChanger, ArNetPacket *> ArMapChanger::myHandleReplyPacketCB protected
Client handler for the reply packet.
Referenced by ArMapChanger(), and ~ArMapChanger().
ArFunctor2C<ArMapChanger, ArServerClient *, ArNetPacket *> ArMapChanger::myHandleRobotReplyPacketCB protected
Referenced by ArMapChanger().
ArMutex ArMapChanger::myIdleProcessingMutex protected
Mutex that protects access to the myIsIdleProcessingPending member.
Referenced by handleIdleProcessingPacket(), and isIdleProcessingPending().
std::list<std::string> ArMapChanger::myInfoNames protected
Number of info types in the associated Aria map.
List of info types in the associated info map
Referenced by addFileLineSetPackets(), ArMapChanger(), convertChangeDetailsToPacketList(), and unpackFileLineSet().
ArMutex ArMapChanger::myInterleaveMutex protected
Mutex that protects access to the interleave data.
Referenced by handleChangeReplyPacket(), handleRobotChangeReplyPacket(), sendMapChanges(), sendRobotMapChanges(), waitForCentralServerReply(), and waitForReply().
bool ArMapChanger::myIsIdleProcessingPending protected
Whether the server has data to process once it becomes idle.
Referenced by handleIdleProcessingPacket(), and isIdleProcessingPending().
bool ArMapChanger::myIsServerClientInit protected
Whether the client switch manager's serverClient has been initialized with a handler (for EM)
bool ArMapChanger::myIsWaitingForReturn protected
Whether the client is waiting for a reply from the server.
Referenced by handleChangeReplyPacket(), handleRobotChangeReplyPacket(), sendMapChanges(), sendRobotMapChanges(), waitForCentralServerReply(), and waitForReply().
ArMapInterface* ArMapChanger::myMap protected
Aria map currently in use.
Referenced by applyMapChanges(), ArMapChanger(), and handleChangePacket().
std::list<ArFunctor*> ArMapChanger::myPostWriteCBList protected
List of callbacks to be invoked after the changed map file is written.
Referenced by addPostWriteFileCB(), applyMapChanges(), and remPostWriteFileCB().
std::list<ArFunctor*> ArMapChanger::myPreWriteCBList protected
List of callbacks to be invoked before the changed map file is written.
Referenced by addPreWriteFileCB(), applyMapChanges(), and remPreWriteFileCB().
bool ArMapChanger::myReadyForNextPacket protected
Whether the client is ready to send another packet.
Referenced by handleChangeReplyPacket(), handleRobotChangeReplyPacket(), sendMapChanges(), sendRobotMapChanges(), waitForCentralServerReply(), and waitForReply().
std::list< ArFunctor2<ArServerClient *, ArNetPacket *> *> ArMapChanger::myRobotChangeReplyCBList protected
List of server client callbacks to be invoked after the map has been changed.
Referenced by addRobotChangeReplyCB(), handleRobotChangeReplyPacket(), and remRobotChangeReplyCB().
ArServerBase* ArMapChanger::myServer protected
Associated server base; non-NULL only when changer instantiated on the server.
Referenced by ArMapChanger(), and handleChangePacket().
ArMapInterface* ArMapChanger::myWorkingMap protected
Copy of the current Aria map, used to make sure the changes can be successfully made.
Referenced by applyInfoChanges(), applyMapChanges(), applyObjectChanges(), applyScanChanges(), and applySupplementChanges().
const char * ArMapChanger::PROCESS_CHANGES_PACKET_NAME static
Initial value:
=
                              "processMapChanges"
Name of the network packet that contains the incremental map changes.
Referenced by ArMapChanger(), sendPacketList(), and ~ArMapChanger().
const char * ArMapChanger::PROCESS_ROBOT_CHANGES_PACKET_NAME static
Initial value:
=
                              "processRobotMapObjectChange"
Name of the network packet that contains incremental map changes originated by the robot.
Referenced by ArMapChanger(), and sendRobotPacketList().
const char * ArMapChanger::ROBOT_CHANGES_COMPLETE_PACKET_NAME static
Initial value:
=
                              "robotMapObjectChangeComplete"
Name of the network packet that is broadcast when map changes originated by the robot are complete.
Referenced by ArMapChanger().
The documentation for this class was generated from the following files:
ArMapChanger.h
ArMapChanger.cpp