ArNetworking: ArClientSimpleConnector Class Reference
ArClientSimpleConnector Class Reference
This will let you connect to different hosts, ports, and with different users and passwords more easily.
#include <ArClientSimpleConnector.h>
Public Member Functions
ArClientSimpleConnector (ArArgumentParser *parser)
Constructor that takes argument parser (prefered)
ArClientSimpleConnector (int *argc, char **argv)
Constructor that takes args from main (not prefered)
ArClientSimpleConnector (ArArgumentBuilder *arguments)
Constructor that takes argument builder (not prefered)
bool connectClient (ArClientBase *client, bool log=true)
Connects the client with the options given.
void logOptions (void) const
Logs the options the connector has.
bool parseArgs (void)
Parses the arguments.
bool parseArgs (ArArgumentParser *parser)
Parses the arguments.
~ArClientSimpleConnector (void)
Destructor.
Protected Member Functions
void reset (void)
Protected Attributes
const char * myHost
bool myLogDataList
ArConstFunctorC< ArClientSimpleConnector > myLogOptionsCB
bool myNoPassword
bool myOwnParser
ArRetFunctorC< bool, ArClientSimpleConnector > myParseArgsCB
ArArgumentParser * myParser
const char * myPassword
int myPort
const char * myServerKey
const char * myUser
Detailed Description
This will let you connect to different hosts, ports, and with different users and passwords more easily.
Some program command line options affect behavior:
Options for ArClientSimpleConnector (see docs for more details):
-host <hostName>
-port <portNumber>
-p <portNumber>
-user <user>
-u <user>
-password <password>
-pwd <password>
-nopassword
-np
-logDataList
-ldl
To set the host the client will connect to use '-host hostName' in the command line parameters (no abbreviation for this since -h is for help and it's only 4 letters). To set the port the client will connect to use '-port portNumber' or '-p portNumber'. To set the user to connect with use '-user userName' or '-u userName'. To set the password to connect with use '-password password' or '-pwd password'. To use no password use '-nopassword' or '-np'. Note that for using passwords you should NOT use that option on the command line since that can show everyone what the password is (especially in Linux), it's there only for testing. If you give it a username without a password it'll ask you for a password, if you don't have a password just use the -nopassword or let it ask you for a password and hit enter. To set the server key (string we need to connect to the server) use '-setServerKey serverKey' or '-ssk serverKey'.
Examples:
getVideoExample.cpp, ptzCameraClientExample.cpp, and robotUpdateExample.cpp.
Constructor & Destructor Documentation
ArClientSimpleConnector::ArClientSimpleConnector (ArArgumentParser * parser)
Constructor that takes argument parser (prefered)
References Aria::addLogOptionsCB(), Aria::addParseArgsCB(), myLogOptionsCB, myOwnParser, myParseArgsCB, myParser, reset(), and ArFunctor::setName().
ArClientSimpleConnector::ArClientSimpleConnector (int * argc, char ** argv)
Constructor that takes args from main (not prefered)
References Aria::addLogOptionsCB(), Aria::addParseArgsCB(), myLogOptionsCB, myOwnParser, myParseArgsCB, myParser, reset(), and ArFunctor::setName().
ArClientSimpleConnector::ArClientSimpleConnector (ArArgumentBuilder * arguments)
Constructor that takes argument builder (not prefered)
References Aria::addLogOptionsCB(), Aria::addParseArgsCB(), myLogOptionsCB, myOwnParser, myParseArgsCB, myParser, reset(), and ArFunctor::setName().
ArClientSimpleConnector::~ArClientSimpleConnector (void)
Destructor.
Member Function Documentation
bool ArClientSimpleConnector::connectClient (ArClientBase * client, bool log = true)
Connects the client with the options given.
Examples:
getVideoExample.cpp, ptzCameraClientExample.cpp, and robotUpdateExample.cpp.
References ArClientBase::blockingConnect(), ArClientBase::logDataList(), myHost, myLogDataList, myNoPassword, myPassword, myPort, myServerKey, myUser, and ArClientBase::setServerKey().
Referenced by main().
void ArClientSimpleConnector::logOptions (void) const
Logs the options the connector has.
References ArLog::log(), and ArLog::Terse.
Referenced by main().
bool ArClientSimpleConnector::parseArgs (void)
Parses the arguments.
References myParser.
Referenced by main().
bool ArClientSimpleConnector::parseArgs (ArArgumentParser * parser)
Parses the arguments.
References ArArgumentParser::checkArgument(), ArArgumentParser::checkParameterArgumentInteger(), ArArgumentParser::checkParameterArgumentString(), myHost, myLogDataList, myNoPassword, myPassword, myPort, myServerKey, and myUser.
void ArClientSimpleConnector::reset (void) protected
References myHost, myLogDataList, myNoPassword, myPassword, myPort, myServerKey, and myUser.
Referenced by ArClientSimpleConnector().
Member Data Documentation
const char* ArClientSimpleConnector::myHost protected
Referenced by connectClient(), parseArgs(), and reset().
bool ArClientSimpleConnector::myLogDataList protected
Referenced by connectClient(), parseArgs(), and reset().
ArConstFunctorC<ArClientSimpleConnector> ArClientSimpleConnector::myLogOptionsCB protected
Referenced by ArClientSimpleConnector().
bool ArClientSimpleConnector::myNoPassword protected
Referenced by connectClient(), parseArgs(), and reset().
bool ArClientSimpleConnector::myOwnParser protected
Referenced by ArClientSimpleConnector().
ArRetFunctorC<bool, ArClientSimpleConnector> ArClientSimpleConnector::myParseArgsCB protected
Referenced by ArClientSimpleConnector().
ArArgumentParser* ArClientSimpleConnector::myParser protected
Referenced by ArClientSimpleConnector(), and parseArgs().
const char* ArClientSimpleConnector::myPassword protected
Referenced by connectClient(), parseArgs(), and reset().
int ArClientSimpleConnector::myPort protected
Referenced by connectClient(), parseArgs(), and reset().
const char* ArClientSimpleConnector::myServerKey protected
Referenced by connectClient(), parseArgs(), and reset().
const char* ArClientSimpleConnector::myUser protected
Referenced by connectClient(), parseArgs(), and reset().
The documentation for this class was generated from the following files:
ArClientSimpleConnector.h
ArClientSimpleConnector.cpp