ArNetworking: ArClientDeleteFileOnServer Class Reference
ArClientDeleteFileOnServer Class Reference
Class for deleting a file on the server.
#include <ArClientFileUtils.h>
Public Member Functions
void addFileDeletedCallback (ArFunctor1< int > *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback for when we get the desired file (or fail)
ArClientDeleteFileOnServer (ArClientBase *client)
Constructor.
bool deleteFileFromDirectory (const char *directory, const char *fileName)
Get the file from a directory.
const char * getDirectory (void)
Gets the directory we're putting to.
const char * getFileName (void)
Gets the filename we're putting.
ArTime getLastCompletedSend (void)
Gets the last time we finished putting a file.
ArTime getLastStartedSend (void)
Gets the last time we started putting a file.
bool isAvailable (void)
Sees if the server supports what this class needs.
bool isWaitingForReturn (void)
If we're waiting for completion now.
void remFileDeletedCallback (ArFunctor1< int > *functor)
Removes a callback for when we get the desired file (or fail)
virtual ~ArClientDeleteFileOnServer ()
Destructor.
Protected Member Functions
void callFileDeletedCallbacks (int val)
void netDeleteFile (ArNetPacket *packet)
Protected Attributes
ArMutex myCallbackMutex
ArClientBase * myClient
ArMutex myDataMutex
ArFunctor1C
< ArClientDeleteFileOnServer,
ArNetPacket * > myDeleteFileCB
std::string myDirectory
FILE * myFile
std::list< ArFunctor1< int > * > myFileDeletedCallbacks
std::string myFileName
bool myIsWaitingForReturn
ArTime myLastCompletedSend
ArTime myLastStartedSend
std::string myWholeFileName
Detailed Description
Class for deleting a file on the server.
This class will interact with the ArServerFileFromClient and put a file on to the server. If you want to find out what files are on the server use ArClientFileLister.
When get a file it doesn't happen right away, but when the file is received (or failes) the fileGotten callbacks will be called, 0 as the int for the callback means everything is good, positive error messages are from the server (0 = good (got file), 1 = getting file, 2 = tried to go outside allowed area, 3 = bad directory, 4 = empty file name (or other problem with fileName), 5 = can't write temp file, 6 = error moving file from temp to perm, 7 = another client putting file, 8 = timeout (no activity for 15 seconds) and another client wanted to put the file, 9 = client adding to, finishing, or canceling a file the server doesn't have), negative would be from this class but there aren't any of those yet
Constructor & Destructor Documentation
ArClientDeleteFileOnServer::ArClientDeleteFileOnServer (ArClientBase * client)
Constructor.
References ArClientBase::addHandler(), client, myCallbackMutex, myClient, myDataMutex, myDeleteFileCB, myIsWaitingForReturn, and ArMutex::setLogName().
ArClientDeleteFileOnServer::~ArClientDeleteFileOnServer () [virtual]
Destructor.
Member Function Documentation
void ArClientDeleteFileOnServer::addFileDeletedCallback (ArFunctor1< int > * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback for when we get the desired file (or fail)
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, myFileDeletedCallbacks, ArLog::Terse, and ArMutex::unlock().
void ArClientDeleteFileOnServer::callFileDeletedCallbacks (int val) [protected]
References ArMutex::lock(), myCallbackMutex, myFileDeletedCallbacks, and ArMutex::unlock().
Referenced by netDeleteFile().
bool ArClientDeleteFileOnServer::deleteFileFromDirectory (const char * directory, const char * fileName)
Get the file from a directory.
References ArUtil::appendSlash(), ArNetPacket::empty(), ArUtil::fixSlashes(), isAvailable(), ArMutex::lock(), ArLog::log(), myClient, myDataMutex, myDirectory, myFileName, myIsWaitingForReturn, myLastStartedSend, myWholeFileName, ArLog::Normal, ArClientBase::requestOnce(), ArTime::setToNow(), ArBasePacket::strToBuf(), ArLog::Terse, and ArMutex::unlock().
const char * ArClientDeleteFileOnServer::getDirectory (void)
Gets the directory we're putting to.
References ArMutex::lock(), myDataMutex, myDirectory, and ArMutex::unlock().
const char * ArClientDeleteFileOnServer::getFileName (void)
Gets the filename we're putting.
References ArMutex::lock(), myDataMutex, myFileName, and ArMutex::unlock().
ArTime ArClientDeleteFileOnServer::getLastCompletedSend (void)
Gets the last time we finished putting a file.
References ArMutex::lock(), myDataMutex, myLastCompletedSend, and ArMutex::unlock().
ArTime ArClientDeleteFileOnServer::getLastStartedSend (void)
Gets the last time we started putting a file.
References ArMutex::lock(), myDataMutex, myLastStartedSend, and ArMutex::unlock().
bool ArClientDeleteFileOnServer::isAvailable (void)
Sees if the server supports what this class needs.
References ArClientBase::dataExists(), and myClient.
Referenced by deleteFileFromDirectory().
bool ArClientDeleteFileOnServer::isWaitingForReturn (void)
If we're waiting for completion now.
References ArMutex::lock(), myDataMutex, myIsWaitingForReturn, and ArMutex::unlock().
void ArClientDeleteFileOnServer::netDeleteFile (ArNetPacket * packet) [protected]
References ArBasePacket::bufToStr(), ArBasePacket::bufToUByte2(), callFileDeletedCallbacks(), ArMutex::lock(), myDataMutex, myIsWaitingForReturn, and ArMutex::unlock().
void ArClientDeleteFileOnServer::remFileDeletedCallback (ArFunctor1< int > * functor)
Removes a callback for when we get the desired file (or fail)
References ArMutex::lock(), myCallbackMutex, myFileDeletedCallbacks, and ArMutex::unlock().
Member Data Documentation
ArMutex ArClientDeleteFileOnServer::myCallbackMutex [protected]
Referenced by addFileDeletedCallback(), ArClientDeleteFileOnServer(), callFileDeletedCallbacks(), and remFileDeletedCallback().
ArClientBase* ArClientDeleteFileOnServer::myClient [protected]
Referenced by ArClientDeleteFileOnServer(), deleteFileFromDirectory(), and isAvailable().
ArMutex ArClientDeleteFileOnServer::myDataMutex [protected]
Referenced by ArClientDeleteFileOnServer(), deleteFileFromDirectory(), getDirectory(), getFileName(), getLastCompletedSend(), getLastStartedSend(), isWaitingForReturn(), and netDeleteFile().
ArFunctor1C<ArClientDeleteFileOnServer, ArNetPacket *> ArClientDeleteFileOnServer::myDeleteFileCB [protected]
Referenced by ArClientDeleteFileOnServer().
std::string ArClientDeleteFileOnServer::myDirectory [protected]
Referenced by deleteFileFromDirectory(), and getDirectory().
FILE* ArClientDeleteFileOnServer::myFile [protected]
std::list<ArFunctor1<int> *> ArClientDeleteFileOnServer::myFileDeletedCallbacks [protected]
Referenced by addFileDeletedCallback(), callFileDeletedCallbacks(), and remFileDeletedCallback().
std::string ArClientDeleteFileOnServer::myFileName [protected]
Referenced by deleteFileFromDirectory(), and getFileName().
bool ArClientDeleteFileOnServer::myIsWaitingForReturn [protected]
Referenced by ArClientDeleteFileOnServer(), deleteFileFromDirectory(), isWaitingForReturn(), and netDeleteFile().
ArTime ArClientDeleteFileOnServer::myLastCompletedSend [protected]
Referenced by getLastCompletedSend().
ArTime ArClientDeleteFileOnServer::myLastStartedSend [protected]
Referenced by deleteFileFromDirectory(), and getLastStartedSend().
std::string ArClientDeleteFileOnServer::myWholeFileName [protected]
Referenced by deleteFileFromDirectory().
The documentation for this class was generated from the following files:
ArClientFileUtils.h
ArClientFileUtils.cpp