ArNetworking: ArServerData Class Reference
ArServerData Class Reference
#include <ArServerData.h>
Public Member Functions
bool addDataFlags (const char *dataFlags)
ArServerData (const char *name, const char *description, unsigned int command, ArFunctor2< ArServerClient *, ArNetPacket * > *functor, const char *argumentDescription, const char *returnDescription, const char *commandGroup=NULL, const char *dataFlags=NULL, ArRetFunctor1< long, unsigned int > *getFrequencyFunctor=NULL, ArFunctor2< long, unsigned int > *requestChangedFunctor=NULL, ArRetFunctor2< bool, ArServerClient *, ArNetPacket * > *requestOnceFunctor=NULL)
Constructor.
void callRequestChangedFunctor (void)
const char * getArgumentDescription (void)
unsigned int getCommand (void)
const char * getCommandGroup (void)
const char * getDataFlagsString (void)
const char * getDescription (void)
ArFunctor2< ArServerClient *, ArNetPacket * > * getFunctor (void)
const char * getName (void)
ArRetFunctor2< bool, ArServerClient *, ArNetPacket * > * getRequestOnceFunctor (void)
const char * getReturnDescription (void)
bool hasDataFlag (const char *dataFlag)
bool isIdlePacket (void)
bool isSlowPacket (void)
bool remDataFlag (const char *dataFlag)
virtual ~ArServerData ()
Destructor.
Protected Attributes
std::string myArgumentDescription
unsigned int myCommand
std::string myCommandGroup
ArArgumentBuilder myDataFlagsBuilder
ArMutex myDataMutex
std::string myDescription
ArFunctor2< ArServerClient *, ArNetPacket * > * myFunctor
ArRetFunctor1< long, unsigned int > * myGetFrequencyFunctor
bool myIdlePacket
std::string myName
std::string myRawDataFlags
ArFunctor2< long, unsigned int > * myRequestChangedFunctor
ArRetFunctor2< bool, ArServerClient *, ArNetPacket * > * myRequestOnceFunctor
std::string myReturnDescription
bool mySlowPacket
Constructor & Destructor Documentation
ArServerData::ArServerData (const char * name, const char * description, unsigned int command, ArFunctor2< ArServerClient *, ArNetPacket * > * functor, const char * argumentDescription, const char * returnDescription, const char * commandGroup = NULL, const char * dataFlags = NULL, ArRetFunctor1< long, unsigned int > * getFrequencyFunctor = NULL, ArFunctor2< long, unsigned int > * requestChangedFunctor = NULL, ArRetFunctor2< bool, ArServerClient *, ArNetPacket * > * requestOnceFunctor = NULL)
Constructor.
References ArArgumentBuilder::add(), hasDataFlag(), myArgumentDescription, myCommand, myCommandGroup, myDataFlagsBuilder, myDataMutex, myDescription, myFunctor, myGetFrequencyFunctor, myIdlePacket, myName, myRequestChangedFunctor, myRequestOnceFunctor, myReturnDescription, mySlowPacket, and ArMutex::setLogName().
ArServerData::~ArServerData () virtual
Destructor.
Member Function Documentation
bool ArServerData::addDataFlags (const char * dataFlags)
References ArArgumentBuilder::add(), ArMutex::lock(), myDataFlagsBuilder, myDataMutex, and ArMutex::unlock().
Referenced by ArServerBase::addDataAdvanced(), and getRequestOnceFunctor().
void ArServerData::callRequestChangedFunctor (void)
References ArFunctor2< P1, P2 >::invoke(), ArRetFunctor1< Ret, P1 >::invokeR(), myCommand, myGetFrequencyFunctor, and myRequestChangedFunctor.
Referenced by getDataFlagsString(), ArServerBase::internalSetDefaultFrequency(), ArServerClient::processPacket(), and ArServerClient::~ArServerClient().
const char* ArServerData::getArgumentDescription (void) inline
References myArgumentDescription.
Referenced by ArServerClient::sendListPacket().
unsigned int ArServerData::getCommand (void) inline
References myCommand.
Referenced by ArServerClient::broadcastPacketTcp(), ArServerClient::broadcastPacketUdp(), ArServerClient::getFrequency(), ArServerClient::handleRequests(), ArServerBase::internalSetDefaultFrequency(), ArServerClient::processPacket(), and ArServerClient::sendListPacket().
const char* ArServerData::getCommandGroup (void) inline
References myCommandGroup.
Referenced by ArServerClient::processPacket(), and ArServerClient::sendListPacket().
const char* ArServerData::getDataFlagsString (void) inline
References callRequestChangedFunctor(), ArArgumentBuilder::getFullString(), and myDataFlagsBuilder.
Referenced by ArServerClient::sendListPacket().
const char* ArServerData::getDescription (void) inline
References myDescription.
Referenced by ArServerClient::sendListPacket().
ArFunctor2<ArServerClient *, ArNetPacket *>* ArServerData::getFunctor (void) inline
References myFunctor.
Referenced by ArServerClient::handleRequests(), ArServerClient::idlePacketCallback(), ArServerClient::processPacket(), and ArServerClient::slowPacketCallback().
const char* ArServerData::getName (void) inline
References myName.
Referenced by ArServerClient::idlePacketCallback(), ArServerClient::processPacket(), ArServerClient::sendListPacket(), and ArServerClient::slowPacketCallback().
ArRetFunctor2<bool, ArServerClient *, ArNetPacket *>* ArServerData::getRequestOnceFunctor (void) inline
References addDataFlags(), hasDataFlag(), myRequestOnceFunctor, and remDataFlag().
Referenced by ArServerClient::idlePacketCallback(), ArServerClient::processPacket(), and ArServerClient::slowPacketCallback().
const char* ArServerData::getReturnDescription (void) inline
References myReturnDescription.
Referenced by ArServerClient::sendListPacket().
bool ArServerData::hasDataFlag (const char * dataFlag)
References ArArgumentBuilder::getArg(), ArArgumentBuilder::getArgc(), ArMutex::lock(), myDataFlagsBuilder, myDataMutex, and ArMutex::unlock().
Referenced by ArServerData(), and getRequestOnceFunctor().
bool ArServerData::isIdlePacket (void) inline
References myIdlePacket.
Referenced by ArServerClient::processPacket().
bool ArServerData::isSlowPacket (void) inline
References mySlowPacket.
Referenced by ArServerClient::processPacket().
bool ArServerData::remDataFlag (const char * dataFlag)
References ArArgumentBuilder::getArg(), ArArgumentBuilder::getArgc(), ArMutex::lock(), myDataFlagsBuilder, myDataMutex, ArArgumentBuilder::removeArg(), and ArMutex::unlock().
Referenced by getRequestOnceFunctor().
Member Data Documentation
std::string ArServerData::myArgumentDescription protected
Referenced by ArServerData(), and getArgumentDescription().
unsigned int ArServerData::myCommand protected
Referenced by ArServerData(), callRequestChangedFunctor(), and getCommand().
std::string ArServerData::myCommandGroup protected
Referenced by ArServerData(), and getCommandGroup().
ArArgumentBuilder ArServerData::myDataFlagsBuilder protected
Referenced by addDataFlags(), ArServerData(), getDataFlagsString(), hasDataFlag(), and remDataFlag().
ArMutex ArServerData::myDataMutex protected
Referenced by addDataFlags(), ArServerData(), hasDataFlag(), and remDataFlag().
std::string ArServerData::myDescription protected
Referenced by ArServerData(), and getDescription().
ArFunctor2<ArServerClient *, ArNetPacket *>* ArServerData::myFunctor protected
Referenced by ArServerData(), and getFunctor().
ArRetFunctor1<long, unsigned int>* ArServerData::myGetFrequencyFunctor protected
Referenced by ArServerData(), and callRequestChangedFunctor().
bool ArServerData::myIdlePacket protected
Referenced by ArServerData(), and isIdlePacket().
std::string ArServerData::myName protected
Referenced by ArServerData(), and getName().
std::string ArServerData::myRawDataFlags protected
ArFunctor2<long, unsigned int>* ArServerData::myRequestChangedFunctor protected
Referenced by ArServerData(), and callRequestChangedFunctor().
ArRetFunctor2<bool, ArServerClient *, ArNetPacket *>* ArServerData::myRequestOnceFunctor protected
Referenced by ArServerData(), and getRequestOnceFunctor().
std::string ArServerData::myReturnDescription protected
Referenced by ArServerData(), and getReturnDescription().
bool ArServerData::mySlowPacket protected
Referenced by ArServerData(), and isSlowPacket().
The documentation for this class was generated from the following files:
ArServerData.h
ArServerData.cpp