ArNetworking: ArCentralForwarder Class Reference
ArCentralForwarder Class Reference
Class for forwarding...
#include <ArCentralForwarder.h>
Public Member Functions
virtual bool addHandler (const char *name, ArFunctor1< ArNetPacket * > *functor)
Adds a functor for some particular data.
ArCentralForwarder (ArServerBase *mainServer, ArSocket *socket, const char *robotName, int startingPort, std::map< int, ArTime * > *usedPorts, ArFunctor2< ArCentralForwarder *, ArServerClient * > *notifyServerClientRemovedCB, const char *enforceProtocolVersion, ArServerCommands::Type enforceType)
Normal constructor.
ArCentralForwarder ()
Constructor for those that are going to inherit.
bool callOnce (double heartbeatTimeout, double udpHeartbeatTimeout, double robotBackupTimeout, double clientBackupTimeout)
the call that actually does all the work (not virtual since this may be different per implementation)
virtual bool dataExists (const char *name)
Sees if this data exists.
virtual ArClientBase * getClient (void)
Gets the client (shouldn't need to be used by anyone)
int getPort (void)
Gets the port (shouldn't need to be used by anyone)
virtual const char * getRobotName (void)
Gets the robot name.
virtual ArServerBase * getServer (void)
Gets the server (shouldn't need to be used by anyone)
virtual bool isConnected (void)
Gets if this forwarder is connected.
virtual bool remHandler (const char *name, ArFunctor1< ArNetPacket * > *functor)
Removes a functor for some particular data by name.
virtual bool request (const char *name, long mSec)
Request some data every mSec milliseconds.
virtual bool requestOnce (const char *name, ArNetPacket *packet=NULL, bool quiet=false)
Request some data (or send a command) just once.
virtual bool requestOnceUdp (const char *name, ArNetPacket *packet=NULL, bool quiet=false)
Request some data (or send a command) just once by UDP.
virtual bool requestOnceWithString (const char *name, const char *str)
Request some data (or send a command) just once with a string as argument.
void willReplace (void)
virtual ~ArCentralForwarder ()
Destructor.
Protected Types
enum ReturnType {
RETURN_NONE, RETURN_SINGLE, RETURN_VIDEO, RETURN_UNTIL_EMPTY,
RETURN_COMPLEX, RETURN_VIDEO_OPTIM
}
enum State { STATE_STARTING, STATE_CONNECTING, STATE_GATHERING, STATE_CONNECTED }
Protected Member Functions
void checkRequestOnces (unsigned int command)
void clientServerClientRemoved (ArServerClient *client)
bool connectedCallOnce (double heartbeatTimeout, double udpHeartbeatTimeout, double robotBackupTimeout, double clientBackupTimeout)
bool connectingCallOnce (double heartbeatTimeout, double udpHeartbeatTimeout, double robotBackupTimeout, double clientBackupTimeout)
bool gatheringCallOnce (double heartbeatTimeout, double udpHeartbeatTimeout, double robotBackupTimeout, double clientBackupTimeout)
ReturnType getReturnType (int command)
void internalRequestChanged (long interval, unsigned int command)
bool internalRequestOnce (ArServerClient *client, ArNetPacket *packet, bool tcp)
void netCentralHeartbeat (ArNetPacket *packet)
void receiveData (ArNetPacket *packet)
void robotServerClientRemoved (ArServerClient *client)
void setLastBroadcast (unsigned int command)
void setLastRequest (unsigned int command)
bool startingCallOnce (double heartbeatTimeout, double udpHeartbeatTimeout, double robotBackupTimeout, double clientBackupTimeout)
Protected Attributes
ArClientBase * client
bool myBeingReplaced
ArClientBase * myClient
ArFunctor1C< ArCentralForwarder, ArServerClient * > myClientServerClientRemovedCB
std::string myEnforceProtocolVersion
ArServerCommands::Type myEnforceType
ArFunctor2< ArCentralForwarder *, ArServerClient * > * myForwarderServerClientRemovedCB
ArFunctor2C< ArCentralForwarder, long, unsigned int > myInternalRequestChangedFunctor
ArRetFunctor3C< bool, ArCentralForwarder, ArServerClient *, ArNetPacket *, bool > myInternalRequestOnceFunctor
std::map< unsigned int, ArTime * > myLastBroadcast
std::map< unsigned int, ArTime * > myLastRequest
ArTime myLastSentCentralServerHeartbeat
ArTime myLastTcpHeartbeat
ArTime myLastUdpHeartbeat
ArServerBase * myMainServer
ArFunctor1C< ArCentralForwarder, ArNetPacket * > myNetCentralHeartbeatCB
int myPort
std::string myPrefix
ArFunctor1C< ArCentralForwarder, ArNetPacket * > myReceiveDataFunctor
std::map< unsigned int, std::list< ArServerClient * > * > myRequestOnces
std::map< unsigned int, ReturnType > myReturnTypes
bool myRobotHasCentralServerHeartbeat
std::string myRobotName
ArFunctor1C< ArCentralForwarder, ArServerClient * > myRobotServerClientRemovedCB
ArServerBase * myServer
ArSocket * mySocket
int myStartingPort
State myState
std::map< int, ArTime * > * myUsedPorts
ArServerBase * server
Detailed Description
Class for forwarding...
You sould use the commands on this instead of the ones on the server and client it holds.
requestStop is missing since that'd only cause problems.
request doesn't take a packet since that'd cause problems with the proxying, other than that everything should be like the client.
Talk to MattL if there's questions.
Member Enumeration Documentation
enum ArCentralForwarder::ReturnType protected
Enumerator
RETURN_NONE
RETURN_SINGLE
RETURN_VIDEO
RETURN_UNTIL_EMPTY
RETURN_COMPLEX
RETURN_VIDEO_OPTIM
enum ArCentralForwarder::State protected
Enumerator
STATE_STARTING
STATE_CONNECTING
STATE_GATHERING
STATE_CONNECTED
Constructor & Destructor Documentation
ArCentralForwarder::ArCentralForwarder (ArServerBase * mainServer, ArSocket * socket, const char * robotName, int startingPort, std::map< int, ArTime * > * usedPorts, ArFunctor2< ArCentralForwarder *, ArServerClient * > * notifyServerClientRemovedCB, const char * enforceProtocolVersion, ArServerCommands::Type enforceType)
Normal constructor.
References myBeingReplaced, myClient, myEnforceProtocolVersion, myEnforceType, myForwarderServerClientRemovedCB, myMainServer, myPort, myPrefix, myRobotHasCentralServerHeartbeat, myRobotName, myServer, mySocket, myStartingPort, myState, myUsedPorts, and STATE_STARTING.
ArCentralForwarder::ArCentralForwarder ()
Constructor for those that are going to inherit.
References myBeingReplaced, myClient, myEnforceProtocolVersion, myEnforceType, myForwarderServerClientRemovedCB, myMainServer, myPort, myPrefix, myRobotHasCentralServerHeartbeat, myRobotName, myServer, mySocket, myStartingPort, myState, myUsedPorts, STATE_STARTING, and ArServerCommands::TYPE_UNSPECIFIED.
ArCentralForwarder::~ArCentralForwarder () virtual
Destructor.
References ArServerBase::close(), ArUtil::deleteSetPairs(), ArClientBase::disconnect(), ArClientBase::isConnected(), myClient, myLastBroadcast, myLastRequest, myRequestOnces, myServer, and mySocket.
Member Function Documentation
bool ArCentralForwarder::addHandler (const char * name, ArFunctor1< ArNetPacket * > * functor) virtual
Adds a functor for some particular data.
References ArClientBase::addHandler(), getRobotName(), ArLog::log(), myClient, and ArLog::Normal.
Referenced by getRobotName().
bool ArCentralForwarder::callOnce (double heartbeatTimeout, double udpHeartbeatTimeout, double robotBackupTimeout, double clientBackupTimeout)
the call that actually does all the work (not virtual since this may be different per implementation)
References connectedCallOnce(), connectingCallOnce(), gatheringCallOnce(), ArLog::log(), myBeingReplaced, myRobotName, myState, ArLog::Normal, startingCallOnce(), STATE_CONNECTED, STATE_CONNECTING, STATE_GATHERING, and STATE_STARTING.
Referenced by connectingCallOnce(), gatheringCallOnce(), getClient(), ArCentralManager::runThread(), and startingCallOnce().
void ArCentralForwarder::checkRequestOnces (unsigned int command) protected
References myRequestOnces.
Referenced by internalRequestOnce(), and receiveData().
void ArCentralForwarder::clientServerClientRemoved (ArServerClient * client) protected
References ArServerClient::getState(), ArFunctor2< P1, P2 >::invoke(), myForwarderServerClientRemovedCB, and ArServerClient::STATE_DISCONNECTED.
Referenced by willReplace().
bool ArCentralForwarder::connectedCallOnce (double heartbeatTimeout, double udpHeartbeatTimeout, double robotBackupTimeout, double clientBackupTimeout) protected
References ArClientBase::isConnected(), ArClientBase::isTcpOnlyFromServer(), ArClientBase::isTcpOnlyToServer(), ArLog::log(), ArServerBase::loopOnce(), ArClientBase::loopOnce(), ArTime::mSecSince(), myClient, myLastSentCentralServerHeartbeat, myLastTcpHeartbeat, myLastUdpHeartbeat, myPrefix, myRobotHasCentralServerHeartbeat, myServer, ArLog::Normal, ArClientBase::requestOnce(), ArClientBase::requestOnceUdp(), ArTime::secSince(), ArServerBase::setBackupTimeout(), ArClientBase::setBackupTimeout(), ArClientBase::setTcpOnlyFromServer(), ArClientBase::setTcpOnlyToServer(), and ArTime::setToNow().
Referenced by callOnce(), and willReplace().
bool ArCentralForwarder::connectingCallOnce (double heartbeatTimeout, double udpHeartbeatTimeout, double robotBackupTimeout, double clientBackupTimeout) protected
References callOnce(), ArSocket::getIPString(), ArClientBase::internalNonBlockingConnectContinue(), ArLog::log(), myClient, myLastTcpHeartbeat, myLastUdpHeartbeat, myPrefix, myRobotName, mySocket, myState, ArClientBase::NON_BLOCKING_CONNECTED, ArClientBase::NON_BLOCKING_CONTINUE, ArClientBase::NON_BLOCKING_FAILED, ArLog::Normal, ArTime::setToNow(), and STATE_GATHERING.
Referenced by callOnce(), and willReplace().
bool ArCentralForwarder::dataExists (const char * name) virtual
Sees if this data exists.
References ArClientBase::dataExists(), getRobotName(), ArLog::log(), myClient, and ArLog::Normal.
Referenced by getRobotName().
bool ArCentralForwarder::gatheringCallOnce (double heartbeatTimeout, double udpHeartbeatTimeout, double robotBackupTimeout, double clientBackupTimeout) protected
References ArClientBase::addHandler(), callOnce(), ArClientBase::dataExists(), ArServerBase::dataHasFlag(), ArClientData::getArgumentDescription(), ArClientData::getCommand(), ArClientData::getCommandGroup(), ArClientData::getDataFlagsString(), ArClientBase::getDataMap(), ArClientData::getDescription(), ArSocket::getIPString(), ArClientData::getName(), ArServerBase::getOpenOnIP(), ArClientBase::getReceivedArgRetList(), ArClientBase::getReceivedDataList(), ArClientBase::getReceivedGroupAndFlagsList(), ArClientData::getReturnDescription(), ArServerBase::getUserInfo(), ArClientData::hasDataFlag(), ArLog::log(), ArClientBase::loopOnce(), myClient, myClientServerClientRemovedCB, myEnforceProtocolVersion, myInternalRequestChangedFunctor, myInternalRequestOnceFunctor, myLastSentCentralServerHeartbeat, myLastTcpHeartbeat, myLastUdpHeartbeat, myMainServer, myNetCentralHeartbeatCB, myPort, myPrefix, myReceiveDataFunctor, myRequestOnces, myReturnTypes, myRobotHasCentralServerHeartbeat, myRobotName, myRobotServerClientRemovedCB, myServer, mySocket, myStartingPort, myState, myUsedPorts, ArLog::Normal, ArClientBase::request(), ArClientBase::requestOnce(), ArClientBase::requestOnceUdp(), RETURN_NONE, RETURN_SINGLE, RETURN_UNTIL_EMPTY, RETURN_VIDEO, RETURN_VIDEO_OPTIM, ArTime::secSince(), setLastBroadcast(), setLastRequest(), ArTime::setToNow(), STATE_CONNECTED, ArBasePacket::strToBuf(), and ArLog::Verbose.
Referenced by callOnce(), and willReplace().
virtual ArClientBase* ArCentralForwarder::getClient (void) inline virtual
Gets the client (shouldn't need to be used by anyone)
References callOnce(), and myClient.
Referenced by ArCentralManager::forwarderServerClientRemovedCallback(), ArCentralManager::netClientList(), and ArCentralManager::runThread().
int ArCentralForwarder::getPort (void) inline
Gets the port (shouldn't need to be used by anyone)
References myPort.
Referenced by ArCentralManager::forwarderServerClientRemovedCallback(), ArCentralManager::netClientList(), and ArCentralManager::runThread().
ArCentralForwarder::ReturnType ArCentralForwarder::getReturnType (int command) protected
References myReturnTypes, and RETURN_NONE.
Referenced by internalRequestChanged(), internalRequestOnce(), and receiveData().
virtual const char* ArCentralForwarder::getRobotName (void) inline virtual
Gets the robot name.
References addHandler(), dataExists(), myRobotName, remHandler(), request(), requestOnce(), requestOnceUdp(), and requestOnceWithString().
Referenced by addHandler(), dataExists(), ArCentralManager::forwarderAdded(), ArCentralManager::forwarderRemoved(), ArCentralManager::forwarderServerClientRemovedCallback(), ArCentralManager::logConnections(), ArCentralManager::netClientList(), ArCentralManager::netServerSwitch(), remHandler(), request(), requestOnce(), requestOnceUdp(), and ArCentralManager::runThread().
virtual ArServerBase* ArCentralForwarder::getServer (void) inline virtual
Gets the server (shouldn't need to be used by anyone)
References myServer.
Referenced by ArCentralManager::logConnections(), ArCentralManager::mainServerClientRemovedCallback(), and ArCentralManager::runThread().
void ArCentralForwarder::internalRequestChanged (long interval, unsigned int command) protected
References ArClientBase::getName(), getReturnType(), ArLog::log(), myClient, myPrefix, ArClientBase::requestByCommand(), ArClientBase::requestOnceByCommand(), ArClientBase::requestStopByCommand(), RETURN_VIDEO, RETURN_VIDEO_OPTIM, setLastRequest(), and ArLog::Verbose.
Referenced by willReplace().
bool ArCentralForwarder::internalRequestOnce (ArServerClient * client, ArNetPacket * packet, bool tcp) protected
References checkRequestOnces(), ArNetPacket::getCommand(), ArClientBase::getName(), getReturnType(), ArLog::log(), myClient, myPrefix, myRequestOnces, ArClientBase::requestOnceByCommand(), ArClientBase::requestOnceByCommandUdp(), RETURN_NONE, RETURN_SINGLE, RETURN_UNTIL_EMPTY, RETURN_VIDEO, RETURN_VIDEO_OPTIM, ArNetPacket::setAddedFooter(), setLastRequest(), and ArLog::Verbose.
Referenced by requestOnce(), requestOnceUdp(), and willReplace().
virtual bool ArCentralForwarder::isConnected (void) inline virtual
Gets if this forwarder is connected.
References myState, and STATE_CONNECTED.
Referenced by ArCentralManager::logConnections(), ArCentralManager::netClientList(), and ArCentralManager::runThread().
void ArCentralForwarder::netCentralHeartbeat (ArNetPacket * packet) protected
References ArNetPacket::getPacketSource(), ArLog::log(), myLastTcpHeartbeat, myLastUdpHeartbeat, myPrefix, ArLog::Normal, ArTime::setToNow(), ArNetPacket::TCP, and ArNetPacket::UDP.
Referenced by willReplace().
void ArCentralForwarder::receiveData (ArNetPacket * packet) protected
References ArServerBase::broadcastPacketTcpByCommand(), ArServerBase::broadcastPacketUdpByCommand(), checkRequestOnces(), client, ArNetPacket::getCommand(), ArBasePacket::getDataLength(), ArServerClient::getFrequency(), ArClientBase::getName(), ArNetPacket::getPacketSource(), getReturnType(), ArLog::log(), myClient, myLastBroadcast, myPrefix, myRequestOnces, myServer, ArLog::Normal, RETURN_SINGLE, RETURN_UNTIL_EMPTY, RETURN_VIDEO, RETURN_VIDEO_OPTIM, ArServerClient::sendPacketTcp(), ArServerClient::sendPacketUdp(), ArNetPacket::setAddedFooter(), ArNetPacket::TCP, and ArNetPacket::UDP.
Referenced by willReplace().
bool ArCentralForwarder::remHandler (const char * name, ArFunctor1< ArNetPacket * > * functor) virtual
Removes a functor for some particular data by name.
References getRobotName(), ArLog::log(), myClient, ArLog::Normal, and ArClientBase::remHandler().
Referenced by getRobotName().
bool ArCentralForwarder::request (const char * name, long mSec) virtual
Request some data every mSec milliseconds.
References getRobotName(), ArServerBase::internalSetDefaultFrequency(), ArLog::log(), myServer, and ArLog::Normal.
Referenced by getRobotName().
bool ArCentralForwarder::requestOnce (const char * name, ArNetPacket * packet = NULL, bool quiet = false) virtual
Request some data (or send a command) just once.
References ArNetPacket::finalizePacket(), ArClientBase::findCommandFromName(), getRobotName(), internalRequestOnce(), ArLog::log(), myClient, ArLog::Normal, and ArNetPacket::setCommand().
Referenced by getRobotName(), and requestOnceWithString().
bool ArCentralForwarder::requestOnceUdp (const char * name, ArNetPacket * packet = NULL, bool quiet = false) virtual
Request some data (or send a command) just once by UDP.
References ArNetPacket::finalizePacket(), ArClientBase::findCommandFromName(), getRobotName(), internalRequestOnce(), ArLog::log(), myClient, ArLog::Normal, and ArNetPacket::setCommand().
Referenced by getRobotName().
bool ArCentralForwarder::requestOnceWithString (const char * name, const char * str) virtual
Request some data (or send a command) just once with a string as argument.
References requestOnce(), and ArBasePacket::strToBuf().
Referenced by getRobotName().
void ArCentralForwarder::robotServerClientRemoved (ArServerClient * client) protected
References client, ArServerClient::getIPString(), ArLog::log(), myPrefix, myRequestOnces, and ArLog::Normal.
Referenced by willReplace().
void ArCentralForwarder::setLastBroadcast (unsigned int command) protected
References myLastBroadcast.
Referenced by gatheringCallOnce().
void ArCentralForwarder::setLastRequest (unsigned int command) protected
References myLastRequest.
Referenced by gatheringCallOnce(), internalRequestChanged(), and internalRequestOnce().
bool ArCentralForwarder::startingCallOnce (double heartbeatTimeout, double udpHeartbeatTimeout, double robotBackupTimeout, double clientBackupTimeout) protected
References callOnce(), ArClientBase::enforceProtocolVersion(), ArClientBase::enforceType(), ArSocket::getIPString(), ArClientBase::internalNonBlockingConnectStart(), ArLog::log(), myClient, myEnforceProtocolVersion, myEnforceType, myLastTcpHeartbeat, myLastUdpHeartbeat, myPrefix, myRobotName, mySocket, myState, ArClientBase::NON_BLOCKING_CONTINUE, ArLog::Normal, ArClientBase::setRobotName(), ArTime::setToNow(), and STATE_CONNECTING.
Referenced by callOnce(), and willReplace().
void ArCentralForwarder::willReplace (void) inline
References client, clientServerClientRemoved(), connectedCallOnce(), connectingCallOnce(), gatheringCallOnce(), internalRequestChanged(), internalRequestOnce(), myBeingReplaced, netCentralHeartbeat(), receiveData(), robotServerClientRemoved(), and startingCallOnce().
Referenced by ArCentralManager::netServerSwitch().
Member Data Documentation
ArClientBase* ArCentralForwarder::client protected
Referenced by receiveData(), robotServerClientRemoved(), and willReplace().
bool ArCentralForwarder::myBeingReplaced protected
Referenced by ArCentralForwarder(), callOnce(), and willReplace().
ArClientBase* ArCentralForwarder::myClient protected
Referenced by addHandler(), ArCentralForwarder(), connectedCallOnce(), connectingCallOnce(), dataExists(), gatheringCallOnce(), getClient(), internalRequestChanged(), internalRequestOnce(), receiveData(), remHandler(), requestOnce(), requestOnceUdp(), startingCallOnce(), and ~ArCentralForwarder().
ArFunctor1C<ArCentralForwarder, ArServerClient *> ArCentralForwarder::myClientServerClientRemovedCB protected
Referenced by gatheringCallOnce().
std::string ArCentralForwarder::myEnforceProtocolVersion protected
Referenced by ArCentralForwarder(), gatheringCallOnce(), and startingCallOnce().
ArServerCommands::Type ArCentralForwarder::myEnforceType protected
Referenced by ArCentralForwarder(), and startingCallOnce().
ArFunctor2<ArCentralForwarder *, ArServerClient *>* ArCentralForwarder::myForwarderServerClientRemovedCB protected
Referenced by ArCentralForwarder(), and clientServerClientRemoved().
ArFunctor2C<ArCentralForwarder, long, unsigned int> ArCentralForwarder::myInternalRequestChangedFunctor protected
Referenced by gatheringCallOnce().
ArRetFunctor3C<bool, ArCentralForwarder, ArServerClient *, ArNetPacket *, bool> ArCentralForwarder::myInternalRequestOnceFunctor protected
Referenced by gatheringCallOnce().
std::map<unsigned int, ArTime *> ArCentralForwarder::myLastBroadcast protected
Referenced by receiveData(), setLastBroadcast(), and ~ArCentralForwarder().
std::map<unsigned int, ArTime *> ArCentralForwarder::myLastRequest protected
Referenced by setLastRequest(), and ~ArCentralForwarder().
ArTime ArCentralForwarder::myLastSentCentralServerHeartbeat protected
Referenced by connectedCallOnce(), and gatheringCallOnce().
ArTime ArCentralForwarder::myLastTcpHeartbeat protected
Referenced by connectedCallOnce(), connectingCallOnce(), gatheringCallOnce(), netCentralHeartbeat(), and startingCallOnce().
ArTime ArCentralForwarder::myLastUdpHeartbeat protected
Referenced by connectedCallOnce(), connectingCallOnce(), gatheringCallOnce(), netCentralHeartbeat(), and startingCallOnce().
ArServerBase* ArCentralForwarder::myMainServer protected
Referenced by ArCentralForwarder(), and gatheringCallOnce().
ArFunctor1C<ArCentralForwarder, ArNetPacket *> ArCentralForwarder::myNetCentralHeartbeatCB protected
Referenced by gatheringCallOnce().
int ArCentralForwarder::myPort protected
Referenced by ArCentralForwarder(), gatheringCallOnce(), and getPort().
std::string ArCentralForwarder::myPrefix protected
Referenced by ArCentralForwarder(), connectedCallOnce(), connectingCallOnce(), gatheringCallOnce(), internalRequestChanged(), internalRequestOnce(), netCentralHeartbeat(), receiveData(), robotServerClientRemoved(), and startingCallOnce().
ArFunctor1C<ArCentralForwarder, ArNetPacket *> ArCentralForwarder::myReceiveDataFunctor protected
Referenced by gatheringCallOnce().
std::map<unsigned int, std::list<ArServerClient *> *> ArCentralForwarder::myRequestOnces protected
Referenced by checkRequestOnces(), gatheringCallOnce(), internalRequestOnce(), receiveData(), robotServerClientRemoved(), and ~ArCentralForwarder().
std::map<unsigned int, ReturnType> ArCentralForwarder::myReturnTypes protected
Referenced by gatheringCallOnce(), and getReturnType().
bool ArCentralForwarder::myRobotHasCentralServerHeartbeat protected
Referenced by ArCentralForwarder(), connectedCallOnce(), and gatheringCallOnce().
std::string ArCentralForwarder::myRobotName protected
Referenced by ArCentralForwarder(), callOnce(), connectingCallOnce(), gatheringCallOnce(), getRobotName(), and startingCallOnce().
ArFunctor1C<ArCentralForwarder, ArServerClient *> ArCentralForwarder::myRobotServerClientRemovedCB protected
Referenced by gatheringCallOnce().
ArServerBase* ArCentralForwarder::myServer protected
Referenced by ArCentralForwarder(), connectedCallOnce(), gatheringCallOnce(), getServer(), receiveData(), request(), and ~ArCentralForwarder().
ArSocket* ArCentralForwarder::mySocket protected
Referenced by ArCentralForwarder(), connectingCallOnce(), gatheringCallOnce(), startingCallOnce(), and ~ArCentralForwarder().
int ArCentralForwarder::myStartingPort protected
Referenced by ArCentralForwarder(), and gatheringCallOnce().
State ArCentralForwarder::myState protected
Referenced by ArCentralForwarder(), callOnce(), connectingCallOnce(), gatheringCallOnce(), isConnected(), and startingCallOnce().
std::map<int, ArTime *>* ArCentralForwarder::myUsedPorts protected
Referenced by ArCentralForwarder(), and gatheringCallOnce().
ArServerBase* ArCentralForwarder::server protected
The documentation for this class was generated from the following files:
ArCentralForwarder.h
ArCentralForwarder.cpp