ArNetworking: ArServerInfoSensor Class Reference
ArServerInfoSensor Class Reference
Service providing clients with data from range sensors.
#include <ArServerInfoSensor.h>
Public Member Functions
ArServerInfoSensor (ArServerBase *server, ArRobot *robot)
void getSensorCumulative (ArServerClient *client, ArNetPacket *packet)
void getSensorCurrent (ArServerClient *client, ArNetPacket *packet)
void getSensorList (ArServerClient *client, ArNetPacket *packet)
virtual ~ArServerInfoSensor ()
Protected Attributes
ArFunctor2C
< ArServerInfoSensor,
ArServerClient *, ArNetPacket * > myGetSensorCumulativeCB
ArFunctor2C
< ArServerInfoSensor,
ArServerClient *, ArNetPacket * > myGetSensorCurrentCB
ArFunctor2C
< ArServerInfoSensor,
ArServerClient *, ArNetPacket * > myGetSensorListCB
ArRobot * myRobot
ArServerBase * myServer
Detailed Description
Service providing clients with data from range sensors.
This service accepts the following data requests:
getSensorList to get a list of all robot sensors
getSensorCurrent to get one range sensor's set of current readings
getSensorCumulative to get one range sensor's set of cumualtive readings
The getSensorList request replies with the following data packet:
Number of sensors (2-byte integer)
For each sensor:
sensor name (Null-terminated string)
The getSensorCurrent and getSensorCumulative requests must include the following data:
Sensor name (Null-terminated string)
The getSensorCurrent and getSensorCumulative requests reply with the following data packets:
Number of readings, or -1 for invalid sensor name error (2-byte integer)
Sensor name (null-terminated string)
For each reading:
X coordinate of reading (4-byte integer)
Y coordinate of reading (4-byte integer)
This service's requests are all in the SensorInfo group.
Examples:
drawingsExampleWithRobot.cpp, and serverDemo.cpp.
Constructor & Destructor Documentation
ArServerInfoSensor::ArServerInfoSensor (ArServerBase * server, ArRobot * robot)
References ArServerBase::addData(), myGetSensorCumulativeCB, myGetSensorCurrentCB, myGetSensorListCB, myRobot, and myServer.
ArServerInfoSensor::~ArServerInfoSensor () [virtual]
Member Function Documentation
void ArServerInfoSensor::getSensorCumulative (ArServerClient * client, ArNetPacket * packet)
References ArBasePacket::bufToStr(), ArBasePacket::byte2ToBuf(), ArBasePacket::byte4ToBuf(), ArRobot::findRangeDevice(), ArRangeDevice::getCumulativeBuffer(), ArBasePacket::getDataLength(), ArBasePacket::getDataReadLength(), ArRobot::lock(), ArRangeDevice::lockDevice(), ArLog::log(), myRobot, ArMath::roundInt(), ArServerClient::sendPacketUdp(), ArBasePacket::strToBuf(), ArRobot::unlock(), ArRangeDevice::unlockDevice(), and ArLog::Verbose.
void ArServerInfoSensor::getSensorCurrent (ArServerClient * client, ArNetPacket * packet)
References ArBasePacket::bufToStr(), ArBasePacket::byte2ToBuf(), ArBasePacket::byte4ToBuf(), ArRobot::findRangeDevice(), ArRangeDevice::getCurrentBuffer(), ArBasePacket::getDataLength(), ArBasePacket::getDataReadLength(), ArRobot::lock(), ArRangeDevice::lockDevice(), ArLog::log(), myRobot, ArMath::roundInt(), ArServerClient::sendPacketUdp(), ArBasePacket::strToBuf(), ArRobot::unlock(), ArRangeDevice::unlockDevice(), and ArLog::Verbose.
void ArServerInfoSensor::getSensorList (ArServerClient * client, ArNetPacket * packet)
References ArBasePacket::byte2ToBuf(), ArRobot::getRangeDeviceList(), ArRobot::lock(), myRobot, ArServerClient::sendPacketUdp(), ArBasePacket::strToBuf(), and ArRobot::unlock().
Member Data Documentation
ArFunctor2C<ArServerInfoSensor, ArServerClient *, ArNetPacket *> ArServerInfoSensor::myGetSensorCumulativeCB [protected]
Referenced by ArServerInfoSensor().
ArFunctor2C<ArServerInfoSensor, ArServerClient *, ArNetPacket *> ArServerInfoSensor::myGetSensorCurrentCB [protected]
Referenced by ArServerInfoSensor().
ArFunctor2C<ArServerInfoSensor, ArServerClient *, ArNetPacket *> ArServerInfoSensor::myGetSensorListCB [protected]
Referenced by ArServerInfoSensor().
ArRobot* ArServerInfoSensor::myRobot [protected]
Referenced by ArServerInfoSensor(), getSensorCumulative(), getSensorCurrent(), and getSensorList().
ArServerBase* ArServerInfoSensor::myServer [protected]
Referenced by ArServerInfoSensor().
The documentation for this class was generated from the following files:
ArServerInfoSensor.h
ArServerInfoSensor.cpp