ArNetworking: ArServerHandlerPopup Class Reference
ArServerHandlerPopup Class Reference
Class for having generic popups appear in MobileEyes (created on the server)
#include <ArServerHandlerPopup.h>
Classes
class PopupData
Public Types
enum PopupType {
NOICON = 0, INFORMATION = 1, WARNING = 2, CRITICAL = 3,
QUESTION = 4
}
Public Member Functions
ArServerHandlerPopup (ArServerBase *server)
Constructor.
void closePopup (ArTypes::Byte4 id, const char *closeMessage)
Cancels a popup with the ID.
ArTypes::Byte4 createPopup (ArServerHandlerPopupInfo *popupInfo, ArFunctor2< ArTypes::Byte4, int > *callback=NULL)
Creates a new popup.
void netPopupClicked (ArServerClient *client, ArNetPacket *packet)
The call from the network that the popup was clicked.
void netPopupList (ArServerClient *client, ArNetPacket *packet)
The call from the network for getting the popup list.
void serverCycleCallback (void)
Our cycle callback.
virtual ~ArServerHandlerPopup ()
Destructor.
Protected Member Functions
void buildPacket (ArNetPacket *sendingPacket, PopupData *popupData)
Protected Attributes
ArMutex myDataMutex
ArTypes::Byte4 myLastID
ArTime myLastTimeCheck
std::map< ArTypes::Byte4,
PopupData * > myMap
ArFunctor2C
< ArServerHandlerPopup,
ArServerClient *, ArNetPacket * > myNetPopupClickedCB
ArFunctor2C
< ArServerHandlerPopup,
ArServerClient *, ArNetPacket * > myNetPopupListCB
ArServerBase * myServer
ArFunctorC< ArServerHandlerPopup > myServerCycleCB
Detailed Description
Class for having generic popups appear in MobileEyes (created on the server)
TODO make the callbacks actually happen
Examples:
popupExample.cpp.
Member Enumeration Documentation
enum ArServerHandlerPopup::PopupType
Enumerator:
NOICON
No icon at all.
INFORMATION
Just an informational message.
WARNING
A warning.
CRITICAL
A critical problem (program failure likely)
QUESTION
A question.
Constructor & Destructor Documentation
ArServerHandlerPopup::ArServerHandlerPopup (ArServerBase * server)
Constructor.
References ArServerBase::addCycleCallback(), ArServerBase::addData(), myDataMutex, myLastID, myLastTimeCheck, myNetPopupClickedCB, myNetPopupListCB, myServer, myServerCycleCB, ArMutex::setLogName(), and ArTime::setToNow().
ArServerHandlerPopup::~ArServerHandlerPopup () [virtual]
Destructor.
Member Function Documentation
void ArServerHandlerPopup::buildPacket (ArNetPacket * sendingPacket, PopupData * popupData) [protected]
References ArBasePacket::byte4ToBuf(), ArBasePacket::byteToBuf(), ArServerHandlerPopupInfo::getButton0Label(), ArServerHandlerPopupInfo::getButton1Label(), ArServerHandlerPopupInfo::getButton2Label(), ArServerHandlerPopupInfo::getDefaultButtonNumber(), ArServerHandlerPopupInfo::getEscapeButtonNumber(), ArServerHandlerPopupInfo::getIgnoreIdentifier(), ArServerHandlerPopupInfo::getMessage(), ArServerHandlerPopupInfo::getPopupType(), ArServerHandlerPopupInfo::getTitle(), ArServerHandlerPopup::PopupData::myID, ArServerHandlerPopup::PopupData::myPopupInfo, and ArBasePacket::strToBuf().
Referenced by createPopup(), and netPopupList().
void ArServerHandlerPopup::closePopup (ArTypes::Byte4 id, const char * closeMessage)
Cancels a popup with the ID.
References ArServerBase::broadcastPacketTcp(), ArBasePacket::byte4ToBuf(), ArFunctor2< P1, P2 >::invoke(), ArMutex::lock(), ArLog::log(), ArServerHandlerPopup::PopupData::myCallback, myDataMutex, ArServerHandlerPopup::PopupData::myID, myMap, myServer, ArBasePacket::strToBuf(), ArMutex::unlock(), and ArLog::Verbose.
ArTypes::Byte4 ArServerHandlerPopup::createPopup (ArServerHandlerPopupInfo * popupInfo, ArFunctor2< ArTypes::Byte4, int > * callback = NULL)
Creates a new popup.
Creates a popup, for information about whats in the popup see ArServerHandlerPopupInfo...
this just describes what happens with the popup...
So you pass in a popupInfo for the popup you want and a functor to call when buttons in the popup are pushed, this returns an id for that popup, which you can use to cancel the popup and so you know which popup this is.... the callback (if there is one) will be called when the popup has a button pushed with the id and the number of the button or -1 if the popup timed out or -2 if it was canceled. The popup has a timeout, so that if no clients are connected watching for popups or if no one is paying attention that things can move on easily.
Parameters:
popupInfo the information that describes the popup... this class makes a copy of the information so you can do whatever you want with the information after you've called this function (ie change the button and call it again or whatever)
callback The class will call this function when one of the buttons is pressed in the popup on one of the clients, the callback will be called with the long int being the ID, and the int being the button that is pushed (or -1 if the timeout happened or -2 if it was closed)
Examples:
popupExample.cpp.
References ArServerBase::broadcastPacketTcp(), buildPacket(), ArMutex::lock(), myDataMutex, myLastID, myMap, myServer, and ArMutex::unlock().
Referenced by ArServerSimpleComMovementLogging::popupMovementParams(), ArServerSimpleComLogRobotConfig::popupOrigConfig(), SensorDetectPopup::sensorTask(), and ArServerSimplePopup::simplePopup().
void ArServerHandlerPopup::netPopupClicked (ArServerClient * client, ArNetPacket * packet)
The call from the network that the popup was clicked.
References ArServerBase::broadcastPacketTcp(), ArBasePacket::bufToByte(), ArBasePacket::bufToByte4(), ArBasePacket::byte4ToBuf(), ArServerHandlerPopupInfo::getButton0Pressed(), ArServerHandlerPopupInfo::getButton1Pressed(), ArServerHandlerPopupInfo::getButton2Pressed(), ArServerClient::getIPString(), ArFunctor2< P1, P2 >::invoke(), ArMutex::lock(), ArLog::log(), ArServerHandlerPopup::PopupData::myCallback, myDataMutex, ArServerHandlerPopup::PopupData::myID, myMap, ArServerHandlerPopup::PopupData::myPopupInfo, myServer, ArBasePacket::strToBuf(), ArMutex::unlock(), and ArLog::Verbose.
void ArServerHandlerPopup::netPopupList (ArServerClient * client, ArNetPacket * packet)
The call from the network for getting the popup list.
References buildPacket(), ArNetPacket::empty(), ArServerBase::findCommandFromName(), ArMutex::lock(), ArLog::log(), myDataMutex, ArServerHandlerPopup::PopupData::myID, myMap, myServer, ArLog::Normal, ArServerClient::sendPacketTcp(), ArNetPacket::setCommand(), and ArMutex::unlock().
void ArServerHandlerPopup::serverCycleCallback (void)
Our cycle callback.
References ArServerBase::broadcastPacketTcp(), ArBasePacket::byte4ToBuf(), ArNetPacket::empty(), ArServerHandlerPopupInfo::getTimeout(), ArServerHandlerPopupInfo::getTimeoutString(), ArFunctor2< P1, P2 >::invoke(), ArMutex::lock(), ArTime::mSecSince(), ArServerHandlerPopup::PopupData::myCallback, myDataMutex, ArServerHandlerPopup::PopupData::myID, myLastTimeCheck, myMap, ArServerHandlerPopup::PopupData::myPopupInfo, myServer, ArServerHandlerPopup::PopupData::myStarted, ArTime::secSince(), ArTime::setToNow(), ArBasePacket::strToBuf(), and ArMutex::unlock().
Member Data Documentation
ArMutex ArServerHandlerPopup::myDataMutex [protected]
Referenced by ArServerHandlerPopup(), closePopup(), createPopup(), netPopupClicked(), netPopupList(), and serverCycleCallback().
ArTypes::Byte4 ArServerHandlerPopup::myLastID [protected]
Referenced by ArServerHandlerPopup(), and createPopup().
ArTime ArServerHandlerPopup::myLastTimeCheck [protected]
Referenced by ArServerHandlerPopup(), and serverCycleCallback().
std::map<ArTypes::Byte4, PopupData *> ArServerHandlerPopup::myMap [protected]
Referenced by closePopup(), createPopup(), netPopupClicked(), netPopupList(), and serverCycleCallback().
ArFunctor2C<ArServerHandlerPopup, ArServerClient*, ArNetPacket *> ArServerHandlerPopup::myNetPopupClickedCB [protected]
Referenced by ArServerHandlerPopup().
ArFunctor2C<ArServerHandlerPopup, ArServerClient*, ArNetPacket *> ArServerHandlerPopup::myNetPopupListCB [protected]
Referenced by ArServerHandlerPopup().
ArServerBase* ArServerHandlerPopup::myServer [protected]
Referenced by ArServerHandlerPopup(), closePopup(), createPopup(), netPopupClicked(), netPopupList(), and serverCycleCallback().
ArFunctorC<ArServerHandlerPopup> ArServerHandlerPopup::myServerCycleCB [protected]
Referenced by ArServerHandlerPopup().
The documentation for this class was generated from the following files:
ArServerHandlerPopup.h
ArServerHandlerPopup.cpp