ArNetworking: ArServerHandlerCommMonitor Class Reference
ArServerHandlerCommMonitor Class Reference
Handler that enables the client to monitor communication to the robot server.
#include <ArServerHandlerCommMonitor.h>
Public Types
enum { MIN_HEARTBEAT_INTERVAL = 100, DEFAULT_HEARTBEAT_INTERVAL = 500 }
Public Member Functions
ArServerHandlerCommMonitor (ArServerBase *server, int heartbeatInterval=DEFAULT_HEARTBEAT_INTERVAL)
Constructs a new handler to monitor communication between the robot server and client.
void cycleCallback ()
Callback for the server cycle; broadcasts heartbeat packets when interval has elapsed.
void handleAckCommTcp (ArServerClient *client, ArNetPacket *packet)
Handles the ackCommTcp network packet.
void handleAckCommUdp (ArServerClient *client, ArNetPacket *packet)
Handles the ackCommUdp network packet.
void handleGetHeartbeatInterval (ArServerClient *client, ArNetPacket *packet)
Handles the getHeartbeatInterval network packet.
virtual ~ArServerHandlerCommMonitor ()
Destructor.
Protected Attributes
ArFunctor2C< ArServerHandlerCommMonitor, ArServerClient *, ArNetPacket * > myAckCommTcpCB
Callback for replying to the ack request (TCP)
ArFunctor2C< ArServerHandlerCommMonitor, ArServerClient *, ArNetPacket * > myAckCommUdpCB
Callback for replying to the ack request (UDP)
ArFunctorC< ArServerHandlerCommMonitor > myCycleCB
Cycle callback executed to broadcast the heartbeat packets.
ArFunctor2C< ArServerHandlerCommMonitor, ArServerClient *, ArNetPacket * > myGetHeartbeatIntervalCB
Callback for getting the heartbeat interval.
int myHeartbeatInterval
Number of msecs between heartbeat broadcasts.
ArTime myLastHeartbeatTime
Time that the last heartbeat packets were broadcast.
ArServerBase * myServer
Server from which requests are received.
Static Protected Attributes
static const char * ACK_COMM_TCP_PACKET_NAME = "ackCommTcp"
Name of the network packet to confirm TCP communication.
static const char * ACK_COMM_UDP_PACKET_NAME = "ackCommUdp"
Name of the network packet to confirm UDP communication.
static const char * COMMAND_GROUP = "RobotInfo"
static const char * GET_HEARTBEAT_INTERVAL_PACKET_NAME = "getHeartbeatInterval"
Name of the network packet to get the heartbeat interval.
static const char * HEARTBEAT_TCP_PACKET_NAME = "heartbeatTcp"
Name of the network packet broadcast (TCP) to confirm the server is alive.
static const char * HEARTBEAT_UDP_PACKET_NAME = "heartbeatUdp"
Name of the network packet broadcast (UDP) to confirm the server is alive.
static const char * NO_ARGS = "None"
Detailed Description
Handler that enables the client to monitor communication to the robot server.
ArServerHandlerCommMonitor defines network packet handlers that simply verify the communication between the robot and server.
This class sends the following broadcast messages to clients at regular intervals:
heartbeatTcp: Packet broadcast (TCP) periodically to confirm that the server is alive.
heartbeatUdp: Packet broadcast (UDP) periodically to confirm that the server is alive.
Clients should respond with the following:
ackCommTcp: Command to acknowledge two-way communication over TCP. An empty packet is returned.
ackCommUdp: Command to acknowledge two-way communication over UDP. An empty packet is returned.
Clients may send the following requests:
getHeartbeatInterval: Command to return the expected heartbeat interval. Packet contains:
uByte4 : Interval (msecs)
Member Enumeration Documentation
anonymous enum
Enumerator
MIN_HEARTBEAT_INTERVAL
DEFAULT_HEARTBEAT_INTERVAL
Constructor & Destructor Documentation
ArServerHandlerCommMonitor::ArServerHandlerCommMonitor (ArServerBase * server, int heartbeatInterval = DEFAULT_HEARTBEAT_INTERVAL)
Constructs a new handler to monitor communication between the robot server and client.
Parameters
server the ArServerBase used to send/receive requests
heartBeatInterval How often to send a "heartbeat" packet to the client
ArServerHandlerCommMonitor::~ArServerHandlerCommMonitor () virtual
Destructor.
References handleGetHeartbeatInterval().
Member Function Documentation
void ArServerHandlerCommMonitor::cycleCallback ()
Callback for the server cycle; broadcasts heartbeat packets when interval has elapsed.
References ArServerBase::broadcastPacketTcp(), ArServerBase::broadcastPacketUdp(), HEARTBEAT_TCP_PACKET_NAME, HEARTBEAT_UDP_PACKET_NAME, ArTime::mSecSince(), myHeartbeatInterval, myLastHeartbeatTime, myServer, and ArTime::setToNow().
void ArServerHandlerCommMonitor::handleAckCommTcp (ArServerClient * client, ArNetPacket * packet)
Handles the ackCommTcp network packet.
Parameters
client the ArServerClient * that sent the request
packet the ArNetPacket * that contains the request
References ArServerClient::sendPacketTcp().
void ArServerHandlerCommMonitor::handleAckCommUdp (ArServerClient * client, ArNetPacket * packet)
Handles the ackCommUdp network packet.
Parameters
client the ArServerClient * that sent the request
packet the ArNetPacket * that contains the request
References ArServerClient::sendPacketUdp().
void ArServerHandlerCommMonitor::handleGetHeartbeatInterval (ArServerClient * client, ArNetPacket * packet)
Handles the getHeartbeatInterval network packet.
Parameters
client the ArServerClient * that sent the request
packet the ArNetPacket * that contains the request
References myHeartbeatInterval, ArServerClient::sendPacketTcp(), and ArBasePacket::uByte4ToBuf().
Referenced by ~ArServerHandlerCommMonitor().
Member Data Documentation
const char * ArServerHandlerCommMonitor::ACK_COMM_TCP_PACKET_NAME = "ackCommTcp" static protected
Name of the network packet to confirm TCP communication.
const char * ArServerHandlerCommMonitor::ACK_COMM_UDP_PACKET_NAME = "ackCommUdp" static protected
Name of the network packet to confirm UDP communication.
const char * ArServerHandlerCommMonitor::COMMAND_GROUP = "RobotInfo" static protected
const char * ArServerHandlerCommMonitor::GET_HEARTBEAT_INTERVAL_PACKET_NAME = "getHeartbeatInterval" static protected
Name of the network packet to get the heartbeat interval.
const char * ArServerHandlerCommMonitor::HEARTBEAT_TCP_PACKET_NAME = "heartbeatTcp" static protected
Name of the network packet broadcast (TCP) to confirm the server is alive.
Referenced by cycleCallback().
const char * ArServerHandlerCommMonitor::HEARTBEAT_UDP_PACKET_NAME = "heartbeatUdp" static protected
Name of the network packet broadcast (UDP) to confirm the server is alive.
Referenced by cycleCallback().
ArFunctor2C<ArServerHandlerCommMonitor, ArServerClient *, ArNetPacket *> ArServerHandlerCommMonitor::myAckCommTcpCB protected
Callback for replying to the ack request (TCP)
ArFunctor2C<ArServerHandlerCommMonitor, ArServerClient *, ArNetPacket *> ArServerHandlerCommMonitor::myAckCommUdpCB protected
Callback for replying to the ack request (UDP)
ArFunctorC<ArServerHandlerCommMonitor> ArServerHandlerCommMonitor::myCycleCB protected
Cycle callback executed to broadcast the heartbeat packets.
ArFunctor2C<ArServerHandlerCommMonitor, ArServerClient *, ArNetPacket *> ArServerHandlerCommMonitor::myGetHeartbeatIntervalCB protected
Callback for getting the heartbeat interval.
int ArServerHandlerCommMonitor::myHeartbeatInterval protected
Number of msecs between heartbeat broadcasts.
Referenced by cycleCallback(), and handleGetHeartbeatInterval().
ArTime ArServerHandlerCommMonitor::myLastHeartbeatTime protected
Time that the last heartbeat packets were broadcast.
Referenced by cycleCallback().
ArServerBase* ArServerHandlerCommMonitor::myServer protected
Server from which requests are received.
Referenced by cycleCallback().
const char * ArServerHandlerCommMonitor::NO_ARGS = "None" static protected
The documentation for this class was generated from the following files:
ArServerHandlerCommMonitor.h
ArServerHandlerCommMonitor.cpp