ArNetworking: ArServerSimpleLogRobotDebugPackets Class Reference
ArServerSimpleLogRobotDebugPackets Class Reference
Class that logs a special debug packet from the robot.
#include <ArServerSimpleCommands.h>
Public Member Functions
void addToInfoGroup (ArStringInfoGroup *infoGroup, const char *name, int whichVal, const char *format="%d")
Adds the robot debug info to the info group.
ArServerSimpleLogRobotDebugPackets (ArServerHandlerCommands *commands, ArRobot *robot, const char *baseDirectory="")
Constructor.
int getNumValues (void)
Gets the number of values there are.
int getValue (int whichVal)
Gets a particular value.
bool packetHandler (ArRobotPacket *packet)
Internal function that parses the packet.
bool startLogging (const char *fileName="robotDebugPacketsLog.txt")
Starts the logging.
bool stopLogging (void)
Ends the logging.
virtual ~ArServerSimpleLogRobotDebugPackets ()
Destructor.
Protected Attributes
std::string myBaseDir
ArServerHandlerCommands * myCommands
FILE * myFile
int myNumVals
ArRetFunctor1C< bool, ArServerSimpleLogRobotDebugPackets, ArRobotPacket * > myPacketHandlerCB
ArRobot * myRobot
ArRetFunctor1C< bool, ArServerSimpleLogRobotDebugPackets, const char * > myStartLoggingCB
ArRetFunctorC< bool, ArServerSimpleLogRobotDebugPackets > myStopLoggingCB
std::map< int, int > myVals
Detailed Description
Class that logs a special debug packet from the robot.
Examples:
serverDemo.cpp.
Constructor & Destructor Documentation
ArServerSimpleLogRobotDebugPackets::ArServerSimpleLogRobotDebugPackets (ArServerHandlerCommands * commands, ArRobot * robot, const char * baseDirectory = "")
Constructor.
References ArServerHandlerCommands::addCommand(), ArRobot::addPacketHandler(), myBaseDir, myCommands, myFile, myPacketHandlerCB, myRobot, myStartLoggingCB, myStopLoggingCB, and ArFunctor::setName().
ArServerSimpleLogRobotDebugPackets::~ArServerSimpleLogRobotDebugPackets () virtual
Destructor.
References myPacketHandlerCB, myRobot, and ArRobot::remPacketHandler().
Member Function Documentation
void ArServerSimpleLogRobotDebugPackets::addToInfoGroup (ArStringInfoGroup * infoGroup, const char * name, int whichVal, const char * format = "%d")
Adds the robot debug info to the info group.
References ArStringInfoGroup::addStringInt(), and getValue().
int ArServerSimpleLogRobotDebugPackets::getNumValues (void)
Gets the number of values there are.
References myNumVals.
int ArServerSimpleLogRobotDebugPackets::getValue (int whichVal)
Gets a particular value.
References myVals.
Referenced by addToInfoGroup().
bool ArServerSimpleLogRobotDebugPackets::packetHandler (ArRobotPacket * packet)
Internal function that parses the packet.
References ArBasePacket::bufToByte(), ArBasePacket::bufToByte2(), ArRobotPacket::getID(), ArLog::log(), myFile, myNumVals, myVals, and ArLog::Normal.
bool ArServerSimpleLogRobotDebugPackets::startLogging (const char * fileName = "robotDebugPacketsLog.txt")
Starts the logging.
References ArRobot::comInt(), ArUtil::fopen(), ArRobot::lock(), ArLog::log(), myBaseDir, myFile, myRobot, ArLog::Normal, stopLogging(), ArLog::Terse, and ArRobot::unlock().
bool ArServerSimpleLogRobotDebugPackets::stopLogging (void)
Ends the logging.
References ArRobot::comInt(), ArRobot::lock(), ArLog::log(), myFile, myRobot, ArLog::Normal, and ArRobot::unlock().
Referenced by startLogging().
Member Data Documentation
std::string ArServerSimpleLogRobotDebugPackets::myBaseDir protected
Referenced by ArServerSimpleLogRobotDebugPackets(), and startLogging().
ArServerHandlerCommands* ArServerSimpleLogRobotDebugPackets::myCommands protected
Referenced by ArServerSimpleLogRobotDebugPackets().
FILE* ArServerSimpleLogRobotDebugPackets::myFile protected
Referenced by ArServerSimpleLogRobotDebugPackets(), packetHandler(), startLogging(), and stopLogging().
int ArServerSimpleLogRobotDebugPackets::myNumVals protected
Referenced by getNumValues(), and packetHandler().
ArRetFunctor1C<bool, ArServerSimpleLogRobotDebugPackets, ArRobotPacket *> ArServerSimpleLogRobotDebugPackets::myPacketHandlerCB protected
Referenced by ArServerSimpleLogRobotDebugPackets(), and ~ArServerSimpleLogRobotDebugPackets().
ArRobot* ArServerSimpleLogRobotDebugPackets::myRobot protected
Referenced by ArServerSimpleLogRobotDebugPackets(), startLogging(), stopLogging(), and ~ArServerSimpleLogRobotDebugPackets().
ArRetFunctor1C<bool, ArServerSimpleLogRobotDebugPackets, const char *> ArServerSimpleLogRobotDebugPackets::myStartLoggingCB protected
Referenced by ArServerSimpleLogRobotDebugPackets().
ArRetFunctorC<bool, ArServerSimpleLogRobotDebugPackets> ArServerSimpleLogRobotDebugPackets::myStopLoggingCB protected
Referenced by ArServerSimpleLogRobotDebugPackets().
std::map<int, int> ArServerSimpleLogRobotDebugPackets::myVals protected
Referenced by getValue(), and packetHandler().
The documentation for this class was generated from the following files:
ArServerSimpleCommands.h
ArServerSimpleCommands.cpp