ArNetworking: ArServerHandlerMapping Class Reference
ArServerHandlerMapping Class Reference
Class that handles the starting, stopping, and status of mapping.
#include <ArServerHandlerMapping.h>
Public Member Functions
void addInfoToLog (const char *str)
Adds an info to the log (has no robot pose) (make sure the robot's locked)
bool addLocationData (const char *name, ArRetFunctor3< int, ArTime, ArPose *, ArPoseWithTime * > *functor)
Adds a new type of location data to the logger.
void addMappingBegunCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback for just after mapping has started.
void addMappingEndCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback for the end of mapping.
void addMappingEndedCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback that is invoked after mapping has been ended.
void addMappingStartCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback for the start of mapping.
void addPostMoveCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be called after moving from temp dir to base dir.
void addPreMoveCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be called before moving from temp dir to base dir.
void addSimpleCommands (ArServerHandlerCommands *handlerCommands)
Adds the simple commands to the simple command handler passed in.
void addStringForStartOfLogs (const char *str, ArListPos::Pos position=ArListPos::LAST)
Adds a string for adding to the log when we start.
void addStringsForStartOfLogToMap (ArMap *arMap)
A method to add the strings for the start of a log just straight to an ArMap.
void addTagToLog (const char *str)
Adds a tag to the logg (has robot pose and stuff) (make sure the robot's locked)
ArServerHandlerMapping (ArServerBase *server, ArRobot *robot, ArLaser *laser, const char *baseDirectory="", const char *tempDirectory="", bool useReflectorValues=false, ArLaser *laser2=NULL, const char *sickSuffix=NULL, const char *sick2Suffix=NULL, std::list< ArLaser * > *extraLasers=NULL)
Constructor.
void forceReading (void)
Forces a reading to be taken.
const char * getFileName (void)
Gets the filename we're using (make sure the robot's locked)
const std::map< std::string,
ArRetFunctor3< int, ArTime,
ArPose *, ArPoseWithTime * >
*, ArStrCaseCmpOp > * getLocationDataMap (void)
Get location data map (mostly for internal things)
const char * getMapName (void)
Gets the mapname we're using (make sure the robot's locked)
ArZippable * getSnapshotZipFile ()
Returns a pointer to a second optional zip file used to contain snapshot images.
ArZippable * getZipFile ()
Returns a pointer to the optional zip file installed on this handler.
bool isMapping (void)
Returns if we're mapping or not.
bool packetHandler (ArRobotPacket *packet)
The packet handler for starting/stopping scans from the lcd.
void remMappingBegunCallback (ArFunctor *functor)
Removes a callback for just after mapping has started.
void remMappingEndCallback (ArFunctor *functor)
Removes a callback for the end of mapping.
void remMappingEndedCallback (ArFunctor *functor)
Removes a callback from the list invoked after mapping has been ended.
void remMappingStartCallback (ArFunctor *functor)
Removes a callback for the start of mapping.
void remPostMoveCallback (ArFunctor *functor)
Removes a callback to be called after moving from temp dir to base dir.
void remPreMoveCallback (ArFunctor *functor)
Removes a callback to be called before moving from temp dir to base dir.
void remStringForStartOfLogs (const char *str)
Removes a string for adding to the log when we start.
void serverMappingEnd (ArServerClient *client, ArNetPacket *packet)
Ends a map.
void serverMappingStart (ArServerClient *client, ArNetPacket *packet)
Starts a new map unless ones already made.
void serverMappingStatus (ArServerClient *client, ArNetPacket *packet)
Gets the mapping status.
void setSnapshotZipFile (ArZippable *zipFile)
Sets the optional zip file installed on this handler.
void setZipFile (ArZippable *zipFile)
Sets the optional zip file installed on this handler.
void simpleLoopEnd (ArArgumentBuilder *arg)
Adds a loop end to the log.
void simpleLoopStart (ArArgumentBuilder *arg)
Adds a loop start to the log.
virtual ~ArServerHandlerMapping ()
Deconstructor.
Protected Member Functions
std::string makeFilePathName (const char *fileName)
Protected Attributes
std::list< ArLaser * > * myExtraLasers
std::string myFileName
std::string myFileName2
ArServerHandlerCommands * myHandlerCommands
ArLaser * myLaser
ArLaser * myLaser2
ArLaserLogger * myLaserLogger
ArLaserLogger * myLaserLogger2
std::map< std::string,
ArRetFunctor3< int, ArTime,
ArPose *, ArPoseWithTime * >
*, ArStrCaseCmpOp > myLocationDataMap
ArFunctor1C
< ArServerHandlerMapping,
ArArgumentBuilder * > myLoopEndCB
ArFunctor1C
< ArServerHandlerMapping,
ArArgumentBuilder * > myLoopStartCB
std::string myMapName
std::list< ArFunctor * > myMappingBegunCallbacks
std::list< ArFunctor * > myMappingEndCallbacks
ArFunctor2C
< ArServerHandlerMapping,
ArServerClient *, ArNetPacket * > myMappingEndCB
std::list< ArFunctor * > myMappingEndedCallbacks
std::list< ArFunctor * > myMappingStartCallbacks
ArFunctor2C
< ArServerHandlerMapping,
ArServerClient *, ArNetPacket * > myMappingStartCB
ArFunctor2C
< ArServerHandlerMapping,
ArServerClient *, ArNetPacket * > myMappingStatusCB
ArRetFunctor1C< bool,
ArServerHandlerMapping,
ArRobotPacket * > myPacketHandlerCB
std::list< ArFunctor * > myPostMoveCallbacks
std::list< ArFunctor * > myPreMoveCallbacks
ArRobot * myRobot
ArServerBase * myServer
ArZippable * mySnapshotZipFile
Second optional zip file in which snaphots may be saved.
std::list< std::string > myStringsForStartOfLog
std::string mySuffix
std::string mySuffix2
ArTempDirectoryHelper myTempDirectoryHelper
bool myUseReflectorValues
ArZippable * myZipFile
Optional zip file in which mapping results may be saved.
Detailed Description
Class that handles the starting, stopping, and status of mapping.
Constructor & Destructor Documentation
ArServerHandlerMapping::ArServerHandlerMapping (ArServerBase * server, ArRobot * robot, ArLaser * laser, const char * baseDirectory = "", const char * tempDirectory = "", bool useReflectorValues = false, ArLaser * laser2 = NULL, const char * suffix = NULL, const char * suffix2 = NULL, std::list< ArLaser * > * extraLasers = NULL)
Constructor.
Parameters:
server the server to add the handlers too
robot the robot to map from
laser the laser to map with
baseDirectory the directory to put the map file into when its done, NULL or an empty string means into the working directory
tempDirectory the directory to put the map file into while its being created, if this is NULL or empty it'll use the base directory
References ArServerBase::addData(), ArRobot::addPacketHandler(), myExtraLasers, myFileName, myHandlerCommands, myLaser, myLaser2, myLaserLogger, myLaserLogger2, myMapName, myMappingEndCB, myMappingStartCB, myMappingStatusCB, myPacketHandlerCB, myRobot, myServer, mySuffix, mySuffix2, myUseReflectorValues, and ArFunctor::setName().
ArServerHandlerMapping::~ArServerHandlerMapping () [virtual]
Deconstructor.
References myLaserLogger, and myLaserLogger2.
Member Function Documentation
void ArServerHandlerMapping::addInfoToLog (const char * str)
Adds an info to the log (has no robot pose) (make sure the robot's locked)
References ArLaserLogger::addInfoToLogPlain(), myLaserLogger, and myLaserLogger2.
bool ArServerHandlerMapping::addLocationData (const char * name, ArRetFunctor3< int, ArTime, ArPose *, ArPoseWithTime * > * functor)
Adds a new type of location data to the logger.
References ArLog::log(), myLocationDataMap, and ArLog::Normal.
void ArServerHandlerMapping::addMappingBegunCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback for just after mapping has started.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myMappingBegunCallbacks, and ArLog::Terse.
void ArServerHandlerMapping::addMappingEndCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback for the end of mapping.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myMappingEndCallbacks, and ArLog::Terse.
void ArServerHandlerMapping::addMappingEndedCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback that is invoked after mapping has been ended.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myMappingEndedCallbacks, and ArLog::Terse.
void ArServerHandlerMapping::addMappingStartCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback for the start of mapping.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myMappingStartCallbacks, and ArLog::Terse.
void ArServerHandlerMapping::addPostMoveCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback to be called after moving from temp dir to base dir.
References ArTempDirectoryHelper::addPostMoveCallback(), and myTempDirectoryHelper.
void ArServerHandlerMapping::addPreMoveCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback to be called before moving from temp dir to base dir.
References ArTempDirectoryHelper::addPreMoveCallback(), and myTempDirectoryHelper.
void ArServerHandlerMapping::addSimpleCommands (ArServerHandlerCommands * handlerCommands)
Adds the simple commands to the simple command handler passed in.
References ArServerHandlerCommands::addStringCommand(), myHandlerCommands, myLoopEndCB, and myLoopStartCB.
void ArServerHandlerMapping::addStringForStartOfLogs (const char * str, ArListPos::Pos position = ArListPos::LAST)
Adds a string for adding to the log when we start.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myStringsForStartOfLog, and ArLog::Terse.
void ArServerHandlerMapping::addStringsForStartOfLogToMap (ArMap * arMap)
A method to add the strings for the start of a log just straight to an ArMap.
References ArArgumentBuilder::add(), ArArgumentBuilder::getArg(), ArArgumentBuilder::getFullString(), ArMap::getInfo(), ArMap::getInfoNames(), myStringsForStartOfLog, and ArArgumentBuilder::removeArg().
void ArServerHandlerMapping::addTagToLog (const char * str)
Adds a tag to the logg (has robot pose and stuff) (make sure the robot's locked)
References ArLaserLogger::addTagToLogPlain(), myLaserLogger, and myLaserLogger2.
void ArServerHandlerMapping::forceReading (void)
Forces a reading to be taken.
References myLaserLogger, myLaserLogger2, and ArLaserLogger::takeReading().
const char * ArServerHandlerMapping::getFileName (void)
Gets the filename we're using (make sure the robot's locked)
References myFileName.
const std::map< std::string, ArRetFunctor3< int, ArTime, ArPose *, ArPoseWithTime * > *, ArStrCaseCmpOp > * ArServerHandlerMapping::getLocationDataMap (void)
Get location data map (mostly for internal things)
References myLocationDataMap.
const char * ArServerHandlerMapping::getMapName (void)
Gets the mapname we're using (make sure the robot's locked)
References myMapName.
ArZippable * ArServerHandlerMapping::getSnapshotZipFile ()
Returns a pointer to a second optional zip file used to contain snapshot images.
This method returns a pointer to a second optional zip file associated with the mapping session.
It contains the snapshot images, and is eventually added to the main mapping zip file. The file should be opened before the "mapping begun" callbacks are invoked, and should be closed after the "mapping end" callbacks are invoked.
It is the application's responsibility to create and manage the zip file. Not all applications will use this feature.
Parameters:
zipFile a pointer to the optional ArZippable instance in which scan results can be stored; NULL if there is no active zip file
References mySnapshotZipFile.
ArZippable * ArServerHandlerMapping::getZipFile ()
Returns a pointer to the optional zip file installed on this handler.
This method returns a pointer to the optional zip file associated with the mapping session.
The file should be opened before the "mapping begun" callbacks are invoked, and should be closed after the "mapping end" callbacks are invoked.
It is the application's responsibility to create and manage the zip file. Not all applications will use this feature.
Parameters:
zipFile a pointer to the optional ArZippable instance in which scan results can be stored; NULL if there is no active zip file
References myZipFile.
bool ArServerHandlerMapping::isMapping (void)
Returns if we're mapping or not.
References myLaserLogger.
std::string ArServerHandlerMapping::makeFilePathName (const char * fileName) [protected]
bool ArServerHandlerMapping::packetHandler (ArRobotPacket * packet)
The packet handler for starting/stopping scans from the lcd.
References ArBasePacket::bufToByte(), ArNetPacket::finalizePacket(), ArRobotPacket::getID(), ArUtil::localtime(), ArRobot::lock(), ArLog::log(), myLaserLogger, myRobot, ArLog::Normal, serverMappingEnd(), serverMappingStart(), ArBasePacket::strToBuf(), and ArRobot::unlock().
void ArServerHandlerMapping::remMappingBegunCallback (ArFunctor * functor)
Removes a callback for just after mapping has started.
References myMappingBegunCallbacks.
void ArServerHandlerMapping::remMappingEndCallback (ArFunctor * functor)
Removes a callback for the end of mapping.
References myMappingEndCallbacks.
void ArServerHandlerMapping::remMappingEndedCallback (ArFunctor * functor)
Removes a callback from the list invoked after mapping has been ended.
References myMappingEndedCallbacks.
void ArServerHandlerMapping::remMappingStartCallback (ArFunctor * functor)
Removes a callback for the start of mapping.
References myMappingStartCallbacks.
void ArServerHandlerMapping::remPostMoveCallback (ArFunctor * functor)
Removes a callback to be called after moving from temp dir to base dir.
References myTempDirectoryHelper, and ArTempDirectoryHelper::remPostMoveCallback().
void ArServerHandlerMapping::remPreMoveCallback (ArFunctor * functor)
Removes a callback to be called before moving from temp dir to base dir.
References myTempDirectoryHelper, and ArTempDirectoryHelper::remPreMoveCallback().
void ArServerHandlerMapping::remStringForStartOfLogs (const char * str)
Removes a string for adding to the log when we start.
References myStringsForStartOfLog.
void ArServerHandlerMapping::serverMappingEnd (ArServerClient * client, ArNetPacket * packet)
Ends a map.
References ArServerBase::broadcastPacketTcp(), ArBasePacket::byteToBuf(), ArRobot::lock(), ArLog::log(), ArTempDirectoryHelper::moveFilesToBaseDirectory(), myFileName, myFileName2, myLaserLogger, myLaserLogger2, myMapName, myMappingEndCallbacks, myMappingEndedCallbacks, myRobot, myServer, myTempDirectoryHelper, ArLog::Normal, ArServerClient::sendPacketTcp(), ArBasePacket::strToBuf(), ArBasePacket::uByte2ToBuf(), and ArRobot::unlock().
Referenced by packetHandler().
void ArServerHandlerMapping::serverMappingStart (ArServerClient * client, ArNetPacket * packet)
Starts a new map unless ones already made.
References ArLaserLogger::addInfoToLogPlain(), ArServerBase::broadcastPacketTcp(), ArBasePacket::bufToStr(), ArBasePacket::byteToBuf(), Aria::getJoyHandler(), Aria::getRobotJoyHandler(), ArTempDirectoryHelper::getTempDirectory(), ArFunctor::invoke(), ArRobot::lock(), ArLog::log(), ArUtil::lower(), myExtraLasers, myFileName, myFileName2, myLaser, myLaser2, myLaserLogger, myLaserLogger2, myLocationDataMap, myMapName, myMappingBegunCallbacks, myMappingStartCallbacks, myRobot, myServer, myStringsForStartOfLog, mySuffix, mySuffix2, myTempDirectoryHelper, myUseReflectorValues, ArLog::Normal, ArServerClient::sendPacketTcp(), ArBasePacket::strToBuf(), ArRobot::unlock(), and ArLaserLogger::wasFileOpenedSuccessfully().
Referenced by packetHandler().
void ArServerHandlerMapping::serverMappingStatus (ArServerClient * client, ArNetPacket * packet)
Gets the mapping status.
References myMapName, ArServerClient::sendPacketTcp(), and ArBasePacket::strToBuf().
void ArServerHandlerMapping::setSnapshotZipFile (ArZippable * zipFile)
Sets the optional zip file installed on this handler.
If snapshots are enabled when the optional zip file feature is used, this method should be called with a valid file in the context of a "mapping start" callback.
The file should have been opened in ZIP_MODE, and should remain open until after all of the "mapping end" callbacks have completed. The file should be closed and this method should be called with a NULL pointer within the context of a "mapping ended" callback. The file should then be added to the main mapping zip file.
It is the application's responsibility to create and manage the zip file. Not all applications will use this feature.
Parameters:
zipFile a pointer to the optional ArZippable instance in which snapshots can be stored
References mySnapshotZipFile.
void ArServerHandlerMapping::setZipFile (ArZippable * zipFile)
Sets the optional zip file installed on this handler.
When the optional zip file feature is used, this method should be called with a valid file in the context of a "mapping start" callback.
The file should have been opened in ZIP_MODE, and should remain open until after all of the "mapping end" callbacks have completed. The file should be closed and this method should be called with a NULL pointer within the context of a "mapping ended" callback.
It is the application's responsibility to create and manage the zip file. Not all applications will use this feature.
Parameters:
zipFile a pointer to the optional ArZippable instance in which scan results can be stored
References myZipFile.
void ArServerHandlerMapping::simpleLoopEnd (ArArgumentBuilder * arg)
Adds a loop end to the log.
References ArLaserLogger::addTagToLog(), ArArgumentBuilder::getFullString(), myLaserLogger, and myLaserLogger2.
void ArServerHandlerMapping::simpleLoopStart (ArArgumentBuilder * arg)
Adds a loop start to the log.
References ArLaserLogger::addTagToLog(), ArArgumentBuilder::getFullString(), myLaserLogger, and myLaserLogger2.
Member Data Documentation
std::list<ArLaser *>* ArServerHandlerMapping::myExtraLasers [protected]
Referenced by ArServerHandlerMapping(), and serverMappingStart().
std::string ArServerHandlerMapping::myFileName [protected]
Referenced by ArServerHandlerMapping(), getFileName(), serverMappingEnd(), and serverMappingStart().
std::string ArServerHandlerMapping::myFileName2 [protected]
Referenced by serverMappingEnd(), and serverMappingStart().
ArServerHandlerCommands* ArServerHandlerMapping::myHandlerCommands [protected]
Referenced by addSimpleCommands(), and ArServerHandlerMapping().
ArLaser* ArServerHandlerMapping::myLaser [protected]
Referenced by ArServerHandlerMapping(), and serverMappingStart().
ArLaser* ArServerHandlerMapping::myLaser2 [protected]
Referenced by ArServerHandlerMapping(), and serverMappingStart().
ArLaserLogger* ArServerHandlerMapping::myLaserLogger [protected]
Referenced by addInfoToLog(), addTagToLog(), ArServerHandlerMapping(), forceReading(), isMapping(), packetHandler(), serverMappingEnd(), serverMappingStart(), simpleLoopEnd(), simpleLoopStart(), and ~ArServerHandlerMapping().
ArLaserLogger* ArServerHandlerMapping::myLaserLogger2 [protected]
Referenced by addInfoToLog(), addTagToLog(), ArServerHandlerMapping(), forceReading(), serverMappingEnd(), serverMappingStart(), simpleLoopEnd(), simpleLoopStart(), and ~ArServerHandlerMapping().
std::map<std::string, ArRetFunctor3<int, ArTime, ArPose *, ArPoseWithTime *> *, ArStrCaseCmpOp> ArServerHandlerMapping::myLocationDataMap [protected]
Referenced by addLocationData(), getLocationDataMap(), and serverMappingStart().
ArFunctor1C<ArServerHandlerMapping, ArArgumentBuilder *> ArServerHandlerMapping::myLoopEndCB [protected]
Referenced by addSimpleCommands().
ArFunctor1C<ArServerHandlerMapping, ArArgumentBuilder *> ArServerHandlerMapping::myLoopStartCB [protected]
Referenced by addSimpleCommands().
std::string ArServerHandlerMapping::myMapName [protected]
Referenced by ArServerHandlerMapping(), getMapName(), serverMappingEnd(), serverMappingStart(), and serverMappingStatus().
std::list<ArFunctor *> ArServerHandlerMapping::myMappingBegunCallbacks [protected]
Referenced by addMappingBegunCallback(), remMappingBegunCallback(), and serverMappingStart().
std::list<ArFunctor *> ArServerHandlerMapping::myMappingEndCallbacks [protected]
Referenced by addMappingEndCallback(), remMappingEndCallback(), and serverMappingEnd().
ArFunctor2C<ArServerHandlerMapping, ArServerClient *, ArNetPacket *> ArServerHandlerMapping::myMappingEndCB [protected]
Referenced by ArServerHandlerMapping().
std::list<ArFunctor *> ArServerHandlerMapping::myMappingEndedCallbacks [protected]
Referenced by addMappingEndedCallback(), remMappingEndedCallback(), and serverMappingEnd().
std::list<ArFunctor *> ArServerHandlerMapping::myMappingStartCallbacks [protected]
Referenced by addMappingStartCallback(), remMappingStartCallback(), and serverMappingStart().
ArFunctor2C<ArServerHandlerMapping, ArServerClient *, ArNetPacket *> ArServerHandlerMapping::myMappingStartCB [protected]
Referenced by ArServerHandlerMapping().
ArFunctor2C<ArServerHandlerMapping, ArServerClient *, ArNetPacket *> ArServerHandlerMapping::myMappingStatusCB [protected]
Referenced by ArServerHandlerMapping().
ArRetFunctor1C<bool, ArServerHandlerMapping, ArRobotPacket *> ArServerHandlerMapping::myPacketHandlerCB [protected]
Referenced by ArServerHandlerMapping().
std::list<ArFunctor *> ArServerHandlerMapping::myPostMoveCallbacks [protected]
std::list<ArFunctor *> ArServerHandlerMapping::myPreMoveCallbacks [protected]
ArRobot* ArServerHandlerMapping::myRobot [protected]
Referenced by ArServerHandlerMapping(), packetHandler(), serverMappingEnd(), and serverMappingStart().
ArServerBase* ArServerHandlerMapping::myServer [protected]
Referenced by ArServerHandlerMapping(), serverMappingEnd(), and serverMappingStart().
ArZippable* ArServerHandlerMapping::mySnapshotZipFile [protected]
Second optional zip file in which snaphots may be saved.
Referenced by getSnapshotZipFile(), and setSnapshotZipFile().
std::list<std::string> ArServerHandlerMapping::myStringsForStartOfLog [protected]
Referenced by addStringForStartOfLogs(), addStringsForStartOfLogToMap(), remStringForStartOfLogs(), and serverMappingStart().
std::string ArServerHandlerMapping::mySuffix [protected]
Referenced by ArServerHandlerMapping(), and serverMappingStart().
std::string ArServerHandlerMapping::mySuffix2 [protected]
Referenced by ArServerHandlerMapping(), and serverMappingStart().
ArTempDirectoryHelper ArServerHandlerMapping::myTempDirectoryHelper [protected]
Referenced by addPostMoveCallback(), addPreMoveCallback(), remPostMoveCallback(), remPreMoveCallback(), serverMappingEnd(), and serverMappingStart().
bool ArServerHandlerMapping::myUseReflectorValues [protected]
Referenced by ArServerHandlerMapping(), and serverMappingStart().
ArZippable* ArServerHandlerMapping::myZipFile [protected]
Optional zip file in which mapping results may be saved.
Referenced by getZipFile(), and setZipFile().
The documentation for this class was generated from the following files:
ArServerHandlerMapping.h
ArServerHandlerMapping.cpp