ArNetworking: SensorDetectPopup Class Reference
SensorDetectPopup Class Reference
Public Member Functions
SensorDetectPopup (ArRobot *robot, ArServerHandlerPopup *popupServer)
Protected Member Functions
void popupClosed (ArTypes::Byte4 popupID, int button)
void sensorTask (void)
Protected Attributes
ArFunctor2C< SensorDetectPopup, ArTypes::Byte4, int > * myPopupClosedCB
bool myPopupDisplayed
ArServerHandlerPopup * myPopupServer
double myPrevObstacleAngle
bool myPrevObstacleAngleValid
ArRobot * myRobot
Detailed Description
Examples:
popupExample.cpp.
Constructor & Destructor Documentation
SensorDetectPopup::SensorDetectPopup (ArRobot * robot, ArServerHandlerPopup * popupServer)
Examples:
popupExample.cpp.
References ArRobot::addSensorInterpTask(), ArRobot::lock(), myPopupClosedCB, myRobot, popupClosed(), sensorTask(), and ArRobot::unlock().
Referenced by main().
Member Function Documentation
void SensorDetectPopup::popupClosed (ArTypes::Byte4 popupID, int button) protected
Examples:
popupExample.cpp.
References Aria::exit(), ArRobot::lock(), ArLog::log(), myPopupDisplayed, myRobot, ArLog::Normal, ArRobot::setDeltaHeading(), Aria::shutdown(), ArRobot::stopRunning(), and ArRobot::unlock().
Referenced by SensorDetectPopup().
void SensorDetectPopup::sensorTask (void) protected
Examples:
popupExample.cpp.
References ArRobot::checkRangeDevicesCurrentPolar(), ArServerHandlerPopup::createPopup(), ArServerHandlerPopup::INFORMATION, ArLog::log(), myPopupClosedCB, myPopupDisplayed, myPopupServer, myPrevObstacleAngle, myPrevObstacleAngleValid, myRobot, and ArLog::Normal.
Referenced by SensorDetectPopup().
Member Data Documentation
ArFunctor2C<SensorDetectPopup, ArTypes::Byte4, int>* SensorDetectPopup::myPopupClosedCB protected
Examples:
popupExample.cpp.
Referenced by SensorDetectPopup(), and sensorTask().
bool SensorDetectPopup::myPopupDisplayed protected
Examples:
popupExample.cpp.
Referenced by popupClosed(), and sensorTask().
ArServerHandlerPopup* SensorDetectPopup::myPopupServer protected
Examples:
popupExample.cpp.
Referenced by sensorTask().
double SensorDetectPopup::myPrevObstacleAngle protected
Examples:
popupExample.cpp.
Referenced by sensorTask().
bool SensorDetectPopup::myPrevObstacleAngleValid protected
Examples:
popupExample.cpp.
Referenced by sensorTask().
ArRobot* SensorDetectPopup::myRobot protected
Examples:
popupExample.cpp.
Referenced by popupClosed(), SensorDetectPopup(), and sensorTask().
The documentation for this class was generated from the following file:
popupExample.cpp