ArNetworking: ArNetPacket Class Reference
ArNetPacket Class Reference
our packet for the network stuff
#include <ArNetPacket.h>
Public Types
enum {
SIZE_OF_LENGTH = 2, MAX_LENGTH = 32000, HEADER_LENGTH = 6, FOOTER_LENGTH = 2,
MAX_DATA_LENGTH = MAX_LENGTH - HEADER_LENGTH - FOOTER_LENGTH - SIZE_OF_LENGTH
}
enum PacketSource { TCP, UDP }
an enum for where the packet came from
Public Member Functions
ArNetPacket (ArTypes::UByte2 bufferSize=ArNetPacket::MAX_LENGTH+5)
Constructor.
ArNetPacket (const ArNetPacket &other)
Copy constructor.
virtual double bufToDouble (void)
Gets a double from the packet buffer.
ArTypes::Byte2 calcCheckSum (void)
returns the checksum, probably used only internally
virtual void doubleToBuf (double val)
Puts a double into the packet buffer.
virtual void duplicatePacket (ArNetPacket *packet)
virtual void empty (void)
virtual void finalizePacket (void)
bool getAddedFooter (void)
Iternal function that sets if we already added the footer(for forwarding)
const char * getArbitraryString (void)
ArTypes::UByte2 getCommand (void)
Gets the command this packet is.
PacketSource getPacketSource (void)
ArNetPacket & operator= (const ArNetPacket &other)
Assignment operator.
virtual void resetRead (void)
void setAddedFooter (bool addedFooter)
Iternal function that sets if we already added the footer(for forwarding)
void setArbitraryString (const char *string)
void setCommand (ArTypes::UByte2 command)
Sets the command this packet is.
void setPacketSource (PacketSource source)
bool verifyCheckSum (void)
returns true if the checksum matches what it should be
virtual ~ArNetPacket ()
Destructor.
Public Member Functions inherited from ArBasePacket
ArBasePacket (ArTypes::UByte2 bufferSize=0, ArTypes::UByte2 headerLength=0, char *buf=NULL, ArTypes::UByte2 footerLength=0)
ArBasePacket (const ArBasePacket &other)
virtual ArTypes::Byte bufToByte (void)
virtual ArTypes::Byte2 bufToByte2 (void)
virtual ArTypes::Byte4 bufToByte4 (void)
virtual ArTypes::Byte8 bufToByte8 (void)
virtual void bufToData (unsigned char *data, int length)
virtual void bufToData (char *data, int length)
virtual void bufToStr (char *buf, int maxlen)
std::string bufToString ()
virtual ArTypes::UByte bufToUByte (void)
virtual ArTypes::UByte2 bufToUByte2 (void)
virtual ArTypes::UByte4 bufToUByte4 (void)
virtual ArTypes::UByte8 bufToUByte8 (void)
virtual void byte2ToBuf (ArTypes::Byte2 val)
virtual void byte4ToBuf (ArTypes::Byte4 val)
virtual void byte8ToBuf (ArTypes::Byte8 val)
virtual void byteToBuf (ArTypes::Byte val)
virtual void dataToBuf (const char *data, int length)
virtual void dataToBuf (const unsigned char *data, int length)
virtual void duplicatePacket (ArBasePacket *packet)
virtual const char * getBuf (void) const
virtual char * getBuf (void)
virtual ArTypes::UByte2 getDataLength (void) const
virtual ArTypes::UByte2 getDataReadLength (void) const
virtual ArTypes::UByte2 getFooterLength (void) const
virtual ArTypes::UByte2 getHeaderLength (void) const
virtual ArTypes::UByte2 getLength (void) const
virtual ArTypes::UByte2 getMaxLength (void) const
virtual ArTypes::UByte2 getReadLength (void) const
virtual bool isValid (void)
virtual void log (void)
ArBasePacket & operator= (const ArBasePacket &other)
virtual void printHex (void)
virtual void resetValid ()
virtual void setBuf (char *buf, ArTypes::UByte2 bufferSize)
virtual bool setHeaderLength (ArTypes::UByte2 length)
virtual bool setLength (ArTypes::UByte2 length)
virtual void setMaxLength (ArTypes::UByte2 bufferSize)
virtual void setReadLength (ArTypes::UByte2 readLength)
virtual void strNToBuf (const char *str, int length)
virtual void strToBuf (const char *str)
virtual void strToBufPadded (const char *str, int length)
virtual void uByte2ToBuf (ArTypes::UByte2 val)
virtual void uByte4ToBuf (ArTypes::UByte4 val)
virtual void uByte8ToBuf (ArTypes::UByte8 val)
virtual void uByteToBuf (ArTypes::UByte val)
virtual ~ArBasePacket ()
Protected Attributes
bool myAddedFooter
std::string myArbitraryString
ArTypes::UByte2 myCommand
PacketSource myPacketSource
Additional Inherited Members
Protected Member Functions inherited from ArBasePacket
bool hasWriteCapacity (int bytes)
Detailed Description
our packet for the network stuff
Examples:
drawingsExample.cpp, drawingsExampleWithRobot.cpp, getVideoExample.cpp, and ptzCameraClientExample.cpp.
Member Enumeration Documentation
anonymous enum
Enumerator
SIZE_OF_LENGTH
Number of bytes needed to store packet length value.
MAX_LENGTH
Suggested maximum total size of a packet (bytes)
HEADER_LENGTH
Bytes of packet data used for header.
FOOTER_LENGTH
Byset of packet data used for footer.
MAX_DATA_LENGTH
Suggested maximum size for data payload (this is the total suggested packet size minus headers and footers)
enum ArNetPacket::PacketSource
an enum for where the packet came from
Enumerator
TCP
Came in over tcp.
UDP
Came in over udp.
Constructor & Destructor Documentation
ArNetPacket::ArNetPacket (ArTypes::UByte2 bufferSize = ArNetPacket::MAX_LENGTH + 5)
Constructor.
ArNetPacket::ArNetPacket (const ArNetPacket & other)
Copy constructor.
ArNetPacket::~ArNetPacket () virtual
Destructor.
Member Function Documentation
double ArNetPacket::bufToDouble (void) virtual
Gets a double from the packet buffer.
References ArBasePacket::bufToStr().
Referenced by ArClientArg::bufToArgValue(), ArClientArg::createArg(), OutputHandler::handleBatteryInfo(), ArServerModeJogPosition::serverHeading(), ArServerModeJogPosition::serverMove(), ArServerModeRatioDrive::serverRatioDrive(), and ArServerModeJogPosition::serverTurn().
ArTypes::Byte2 ArNetPacket::calcCheckSum (void)
returns the checksum, probably used only internally
Referenced by finalizePacket(), and verifyCheckSum().
void ArNetPacket::doubleToBuf (double val) virtual
Puts a double into the packet buffer.
References ArBasePacket::strToBuf().
Referenced by ArClientArg::argValueToBuf(), ArServerInfoRobot::batteryInfo(), ArClientArg::createPacket(), ArClientBase::requestOnceWithDouble(), and ArClientRatioDrive::sendInput().
void ArNetPacket::duplicatePacket (ArNetPacket * packet) virtual
References ArBasePacket::getBuf(), myAddedFooter, myArbitraryString, myCommand, and ArBasePacket::setMaxLength().
Referenced by ArMapChanger::ClientChangeInfo::addPacket(), ArServerClientData::ArServerClientData(), ArServerClient::processPacket(), ArHybridForwarderVideo::receiveVideo(), ArHybridForwarderVideo::receiveVideoSize(), ArNetPacketSenderTcp::sendPacket(), ArHybridForwarderVideo::sendVideo(), and ArServerClientData::setPacket().
void ArNetPacket::empty (void) virtual
Reimplemented from ArBasePacket.
Examples:
drawingsExample.cpp, and ptzCameraClientExample.cpp.
References myAddedFooter, myCommand, ArBasePacket::resetValid(), ArBasePacket::uByte2ToBuf(), and ArBasePacket::uByteToBuf().
Referenced by ArServerClient::ArServerClient(), ArServerBase::broadcastPacketTcpByCommandWithExclusion(), ArServerBase::broadcastPacketUdpByCommandWithExclusion(), ArServerHandlerCamera::buildModePacket(), ArServerInfoStrings::buildStringsInfoPacket(), ArServerInfoStrings::buildStringsPacket(), ArClientDeleteFileOnServer::deleteFileFromDirectory(), ArServerFileToClient::doGetFile(), ArServerFileLister::getDirListingMultiplePackets(), ArServerHandlerConfig::handleGetConfig(), ArServerHandlerConfig::handleGetConfigSection(), ArClientBase::internalNonBlockingConnectContinue(), ArServerInfoDrawings::netGetDrawingList(), ArServerHandlerPopup::netPopupList(), ArServerClient::processAuthPacket(), ArServerClient::processPacket(), ArClientBase::processPacket(), ArClientFileFromClient::putFileToDirectory(), ArNetPacketReceiverTcp::readPacket(), ArNetCameraRequest::requestPanTiltAbs(), ArNetCameraRequest::requestPanTiltZoomAbs(), ArClientHandlerConfig::saveConfigToServer(), ArServerClient::sendListPacket(), ArServerHandlerMap::sendMapWithMaxCategory(), ArServerHandlerPopup::serverCycleCallback(), ArServerHandlerMap::serverGetMapBinary(), ArServerHandlerMap::writeLinesToClient(), ArServerHandlerMap::writePointsToClient(), and Circle::~Circle().
void ArNetPacket::finalizePacket (void) virtual
Reimplemented from ArBasePacket.
Examples:
ptzCameraClientExample.cpp.
References ArBasePacket::byteToBuf(), calcCheckSum(), and myAddedFooter.
Referenced by ArServerHandlerMapping::packetHandler(), ArCentralForwarder::requestOnce(), ArCentralForwarder::requestOnceUdp(), ArNetCameraRequest::requestPanTiltAbs(), ArNetCameraRequest::requestPanTiltZoomAbs(), ArServerClient::setupPacket(), and ArClientBase::setupPacket().
bool ArNetPacket::getAddedFooter (void) inline
Iternal function that sets if we already added the footer(for forwarding)
References myAddedFooter.
const char* ArNetPacket::getArbitraryString (void) inline
References myArbitraryString.
Referenced by ArNetPacketSenderTcp::sendData().
ArTypes::UByte2 ArNetPacket::getCommand (void)
Gets the command this packet is.
References myCommand.
Referenced by ArServerClient::broadcastPacketTcp(), ArServerClient::broadcastPacketUdp(), ArClientBase::buildList(), ArClientBase::getName(), ArServerClient::idlePacketCallback(), ArCentralForwarder::internalRequestOnce(), ArServerClient::processPacket(), ArServerBase::processPacket(), ArClientBase::processPacket(), ArClientBase::processPacketUdp(), ArNetPacketReceiverUdp::readData(), ArNetPacketReceiverTcp::readPacket(), ArCentralForwarder::receiveData(), ArNetPacketSenderTcp::sendData(), ArNetPacketSenderTcp::sendPacket(), ArServerClient::sendPacketTcp(), ArServerClient::sendPacketUdp(), ArHybridForwarderVideo::sendVideoSize(), ArServerClient::setupPacket(), ArClientBase::setupPacket(), ArServerClient::slowPacketCallback(), ArClientBase::trackPacketReceived(), ArServerClient::trackPacketSent(), and ArClientBase::trackPacketSent().
PacketSource ArNetPacket::getPacketSource (void) inline
References myPacketSource.
Referenced by ArCentralForwarder::netCentralHeartbeat(), ArClientSwitchManager::netCentralServerHeartbeat(), ArCentralForwarder::receiveData(), and ArServerClient::trackPacketReceived().
ArNetPacket & ArNetPacket::operator= (const ArNetPacket & other)
Assignment operator.
References myAddedFooter, myArbitraryString, myCommand, myPacketSource, and ArBasePacket::operator=().
void ArNetPacket::resetRead (void) virtual
Reimplemented from ArBasePacket.
References ArBasePacket::bufToUByte2(), myCommand, and ArBasePacket::resetValid().
Referenced by ArMapChanger::ClientChangeInfo::addPacket(), ArMapChanger::handleRobotChangeReplyPacket(), ArServerBase::processPacket(), ArClientBase::processPacket(), ArNetPacketReceiverUdp::readData(), ArNetPacketReceiverTcp::readPacket(), ArHybridForwarderVideo::receiveVideo(), ArHybridForwarderVideo::receiveVideoSize(), ArClientBase::requestByCommand(), ArMapChanger::resetPacketList(), and ArHybridForwarderVideo::sendVideo().
void ArNetPacket::setAddedFooter (bool addedFooter) inline
Iternal function that sets if we already added the footer(for forwarding)
References myAddedFooter.
Referenced by ArCentralForwarder::internalRequestOnce(), and ArCentralForwarder::receiveData().
void ArNetPacket::setArbitraryString (const char * string) inline
References myArbitraryString.
Referenced by ArNetPacketSenderTcp::sendPacket().
void ArNetPacket::setCommand (ArTypes::UByte2 command)
Sets the command this packet is.
References myCommand.
Referenced by ArServerClient::ArServerClient(), ArServerBase::broadcastPacketTcpByCommandWithExclusion(), ArServerBase::broadcastPacketUdpByCommandWithExclusion(), ArMapChanger::handleChangePacket(), ArClientBase::internalNonBlockingConnectContinue(), ArServerHandlerPopup::netPopupList(), ArServerClient::processAuthPacket(), ArServerClient::processPacket(), ArClientBase::processPacket(), ArClientBase::requestByCommand(), ArCentralForwarder::requestOnce(), ArClientBase::requestOnceByCommand(), ArClientBase::requestOnceByCommandUdp(), ArCentralForwarder::requestOnceUdp(), ArClientBase::requestStopByCommand(), ArServerClient::sendListPacket(), ArMapChanger::sendRobotPacketList(), ArHybridForwarderVideo::sendVideo(), ArHybridForwarderVideo::sendVideoSize(), ArServerHandlerConfig::setConfig(), ArServerHandlerConfig::setConfigBySections(), ArServerHandlerConfig::setConfigBySectionsV2(), ArServerHandlerConfig::setConfigParam(), ArClientBase::setTcpOnlyFromServer(), ArServerClient::setupPacket(), ArServerClient::shutdown(), ArClientBase::startNonBlockingDisconnect(), and ArServerClient::tcpCallback().
void ArNetPacket::setPacketSource (PacketSource source) inline
References myPacketSource.
Referenced by ArNetPacketReceiverUdp::readData(), and ArNetPacketReceiverTcp::readData().
bool ArNetPacket::verifyCheckSum (void)
returns true if the checksum matches what it should be
References calcCheckSum().
Referenced by ArNetPacketReceiverUdp::readData(), and ArNetPacketReceiverTcp::readPacket().
Member Data Documentation
bool ArNetPacket::myAddedFooter protected
Referenced by duplicatePacket(), empty(), finalizePacket(), getAddedFooter(), operator=(), and setAddedFooter().
std::string ArNetPacket::myArbitraryString protected
Referenced by duplicatePacket(), getArbitraryString(), operator=(), and setArbitraryString().
ArTypes::UByte2 ArNetPacket::myCommand protected
Referenced by duplicatePacket(), empty(), getCommand(), operator=(), resetRead(), and setCommand().
PacketSource ArNetPacket::myPacketSource protected
Referenced by getPacketSource(), operator=(), and setPacketSource().
The documentation for this class was generated from the following files:
ArNetPacket.h
ArNetPacket.cpp