ArNetworking: ArServerFileLister Class Reference
ArServerFileLister Class Reference
Provides a list of files to clients.
#include <ArServerFileUtils.h>
Public Member Functions
ArServerFileLister (ArServerBase *server, const char *topDir, const char *defaultUploadDownloadDir=NULL)
Constructor.
void getDefaultUploadDownloadDir (ArServerClient *client, ArNetPacket *packet)
The function that gets the default upload/download dir.
void getDirListing (ArServerClient *client, ArNetPacket *packet)
The function that gets the directory listing.
void getDirListingMultiplePackets (ArServerClient *client, ArNetPacket *packet)
The function that gets the directory listing in a better way.
virtual ~ArServerFileLister ()
Destructor.
Protected Attributes
char myBaseDir [2048]
std::string myDefaultUploadDownloadDir
ArFunctor2C
< ArServerFileLister,
ArServerClient *, ArNetPacket * > myGetDefaultUploadDownloadDirCB
ArFunctor2C
< ArServerFileLister,
ArServerClient *, ArNetPacket * > myGetDirListingCB
ArFunctor2C
< ArServerFileLister,
ArServerClient *, ArNetPacket * > myGetDirListingMultiplePacketsCB
ArServerBase * myServer
Detailed Description
Provides a list of files to clients.
Note:
Linux only
This class is set up so that a client can get file information from the robot, this class ONLY lists files, and doesn't do any manipulation of them. You should use this class by using ArClientFileLister and NOT by using this classes interface directly, this is because the API is and will remain fairly volatile, just use ArClientFileLister, if you need more functionality let us know and we'll add it if its reasonable.
Constructor & Destructor Documentation
ArServerFileLister::ArServerFileLister (ArServerBase * server, const char * topDir, const char * defaultUploadDownloadDir = NULL)
Constructor.
References ArServerBase::addData(), ArUtil::appendSlash(), ArUtil::fixSlashes(), myBaseDir, myDefaultUploadDownloadDir, myGetDefaultUploadDownloadDirCB, myGetDirListingCB, myGetDirListingMultiplePacketsCB, and myServer.
ArServerFileLister::~ArServerFileLister () [virtual]
Destructor.
Member Function Documentation
void ArServerFileLister::getDefaultUploadDownloadDir (ArServerClient * client, ArNetPacket * packet)
The function that gets the default upload/download dir.
References myDefaultUploadDownloadDir, ArServerClient::sendPacketTcp(), and ArBasePacket::strToBuf().
void ArServerFileLister::getDirListing (ArServerClient * client, ArNetPacket * packet)
The function that gets the directory listing.
References ArUtil::appendSlash(), ArBasePacket::bufToStr(), ArUtil::fixSlashes(), ArLog::log(), myBaseDir, ArLog::Normal, ArServerClient::sendPacketTcp(), ArBasePacket::strToBuf(), ArBasePacket::uByte2ToBuf(), and ArBasePacket::uByte4ToBuf().
void ArServerFileLister::getDirListingMultiplePackets (ArServerClient * client, ArNetPacket * packet)
The function that gets the directory listing in a better way.
References ArUtil::appendSlash(), ArBasePacket::bufToStr(), ArBasePacket::byteToBuf(), ArNetPacket::empty(), ArUtil::fixSlashes(), ArBasePacket::getDataLength(), ArBasePacket::getLength(), ArLog::log(), ArNetPacket::MAX_DATA_LENGTH, myBaseDir, ArLog::Normal, ArServerClient::sendPacketTcp(), ArBasePacket::setLength(), ArBasePacket::strToBuf(), ArBasePacket::uByte2ToBuf(), and ArBasePacket::uByte4ToBuf().
Member Data Documentation
char ArServerFileLister::myBaseDir[2048] [protected]
Referenced by ArServerFileLister(), getDirListing(), and getDirListingMultiplePackets().
std::string ArServerFileLister::myDefaultUploadDownloadDir [protected]
Referenced by ArServerFileLister(), and getDefaultUploadDownloadDir().
ArFunctor2C<ArServerFileLister, ArServerClient *, ArNetPacket *> ArServerFileLister::myGetDefaultUploadDownloadDirCB [protected]
Referenced by ArServerFileLister().
ArFunctor2C<ArServerFileLister, ArServerClient *, ArNetPacket *> ArServerFileLister::myGetDirListingCB [protected]
Referenced by ArServerFileLister().
ArFunctor2C<ArServerFileLister, ArServerClient *, ArNetPacket *> ArServerFileLister::myGetDirListingMultiplePacketsCB [protected]
Referenced by ArServerFileLister().
ArServerBase* ArServerFileLister::myServer [protected]
Referenced by ArServerFileLister().
The documentation for this class was generated from the following files:
ArServerFileUtils.h
ArServerFileUtils.cpp