ArNetworking: ArServerInfoStrings Class Reference
ArServerInfoStrings Class Reference
This will set up strings to send to MobileEyes so that server developers can easily add more information.
#include <ArServerInfoStrings.h>
Public Member Functions
void addString (const char *name, ArTypes::UByte2 maxLen, ArFunctor2< char *, ArTypes::UByte2 > *functor)
Adds a string to the list in the raw format.
ArServerInfoStrings (ArServerBase *server)
Constructor.
ArFunctor3< const char *, ArTypes::UByte2, ArFunctor2< char *, ArTypes::UByte2 > * > * getAddStringFunctor (void)
Gets the functor for adding a string (for ArStringInfoGroup)
ArStringInfoHolder * internalGetStringInfoHolder (const char *name)
Gets a string info holder, for internal purposes.
void netGetStrings (ArServerClient *client, ArNetPacket *packet)
Gets the strings.
void netGetStringsInfo (ArServerClient *client, ArNetPacket *packet)
Gets the information about the strings being sent.
~ArServerInfoStrings ()
Destructor.
Protected Member Functions
void buildStringsInfoPacket (void)
void buildStringsPacket (void)
Protected Attributes
ArFunctor3C< ArServerInfoStrings, const char *, ArTypes::UByte2, ArFunctor2< char *, ArTypes::UByte2 > * > myAddStringFunctor
ArTime myLastStringPacketBuild
ArTypes::UByte2 myMaxMaxLength
ArFunctor2C< ArServerInfoStrings, ArServerClient *, ArNetPacket * > myNetGetStringsCB
ArFunctor2C< ArServerInfoStrings, ArServerClient *, ArNetPacket * > myNetGetStringsInfoCB
ArServerBase * myServer
ArNetPacket myStringInfoPacket
ArNetPacket myStringPacket
std::list< ArStringInfoHolder * > myStrings
ArMutex myStringsMutex
Detailed Description
This will set up strings to send to MobileEyes so that server developers can easily add more information.
There are different ways ways you can add a string (they all are the same way internally). The raw way is addString which takes a functor with a buffer and a buffer len, the functor then has to fill in the string when called. The other ways are set up for convenience and are wrappers in this class around the addString, the other ways are addStringInt, addStringDouble, addStringBool, these all take a functor that returns the type and a format string (in addition to the name and maxLen again).
Examples:
serverDemo.cpp.
Constructor & Destructor Documentation
ArServerInfoStrings::ArServerInfoStrings (ArServerBase * server)
Constructor.
References ArServerBase::addData(), myMaxMaxLength, myNetGetStringsCB, myNetGetStringsInfoCB, myServer, myStringsMutex, and ArMutex::setLogName().
ArServerInfoStrings::~ArServerInfoStrings ()
Destructor.
Member Function Documentation
void ArServerInfoStrings::addString (const char * name, ArTypes::UByte2 maxLen, ArFunctor2< char *, ArTypes::UByte2 > * functor)
Adds a string to the list in the raw format.
References ArServerBase::broadcastPacketTcp(), buildStringsInfoPacket(), ArMutex::lock(), myMaxMaxLength, myServer, myStringInfoPacket, myStrings, myStringsMutex, and ArMutex::unlock().
void ArServerInfoStrings::buildStringsInfoPacket (void) protected
References ArNetPacket::empty(), ArStringInfoHolder::getMaxLength(), ArStringInfoHolder::getName(), ArMutex::lock(), myStringInfoPacket, myStrings, myStringsMutex, ArBasePacket::strToBuf(), ArBasePacket::uByte2ToBuf(), and ArMutex::unlock().
Referenced by addString(), and netGetStringsInfo().
void ArServerInfoStrings::buildStringsPacket (void) protected
References ArNetPacket::empty(), ArStringInfoHolder::getFunctor(), ArStringInfoHolder::getMaxLength(), ArFunctor2< char *, ArTypes::UByte2 >::invoke(), ArMutex::lock(), myMaxMaxLength, myStringPacket, myStrings, myStringsMutex, ArBasePacket::strToBuf(), and ArMutex::unlock().
Referenced by netGetStrings().
ArFunctor3<const char *, ArTypes::UByte2, ArFunctor2<char *, ArTypes::UByte2> *>* ArServerInfoStrings::getAddStringFunctor (void) inline
Gets the functor for adding a string (for ArStringInfoGroup)
Examples:
serverDemo.cpp.
References internalGetStringInfoHolder(), and myAddStringFunctor.
Referenced by main().
ArStringInfoHolder * ArServerInfoStrings::internalGetStringInfoHolder (const char * name)
Gets a string info holder, for internal purposes.
References ArStringInfoHolder::getMaxLength(), ArStringInfoHolder::getName(), ArMutex::lock(), myStringInfoPacket, myStrings, myStringsMutex, ArUtil::strcasecmp(), ArBasePacket::strToBuf(), ArBasePacket::uByte2ToBuf(), and ArMutex::unlock().
Referenced by getAddStringFunctor().
void ArServerInfoStrings::netGetStrings (ArServerClient * client, ArNetPacket * packet)
Gets the strings.
References buildStringsPacket(), myStringPacket, and ArServerClient::sendPacketTcp().
void ArServerInfoStrings::netGetStringsInfo (ArServerClient * client, ArNetPacket * packet)
Gets the information about the strings being sent.
References buildStringsInfoPacket(), myStringInfoPacket, and ArServerClient::sendPacketTcp().
Member Data Documentation
ArFunctor3C<ArServerInfoStrings, const char *, ArTypes::UByte2, ArFunctor2<char *, ArTypes::UByte2> *> ArServerInfoStrings::myAddStringFunctor protected
Referenced by getAddStringFunctor().
ArTime ArServerInfoStrings::myLastStringPacketBuild protected
ArTypes::UByte2 ArServerInfoStrings::myMaxMaxLength protected
Referenced by addString(), ArServerInfoStrings(), and buildStringsPacket().
ArFunctor2C<ArServerInfoStrings, ArServerClient *, ArNetPacket *> ArServerInfoStrings::myNetGetStringsCB protected
Referenced by ArServerInfoStrings().
ArFunctor2C<ArServerInfoStrings, ArServerClient *, ArNetPacket *> ArServerInfoStrings::myNetGetStringsInfoCB protected
Referenced by ArServerInfoStrings().
ArServerBase* ArServerInfoStrings::myServer protected
Referenced by addString(), and ArServerInfoStrings().
ArNetPacket ArServerInfoStrings::myStringInfoPacket protected
Referenced by addString(), buildStringsInfoPacket(), internalGetStringInfoHolder(), and netGetStringsInfo().
ArNetPacket ArServerInfoStrings::myStringPacket protected
Referenced by buildStringsPacket(), and netGetStrings().
std::list<ArStringInfoHolder *> ArServerInfoStrings::myStrings protected
Referenced by addString(), buildStringsInfoPacket(), buildStringsPacket(), and internalGetStringInfoHolder().
ArMutex ArServerInfoStrings::myStringsMutex protected
Referenced by addString(), ArServerInfoStrings(), buildStringsInfoPacket(), buildStringsPacket(), and internalGetStringInfoHolder().
The documentation for this class was generated from the following files:
ArServerInfoStrings.h
ArServerInfoStrings.cpp