ArNetworking: ArServerBase Class Reference
ArServerBase Class Reference
Base server for all networking services.
#include <ArServerBase.h>
Classes
class SlowIdleThread
Public Member Functions
void addClientRemovedCallback (ArFunctor1< ArServerClient * > *functor)
Add a callback to be invoked when a client has been removed (but before it is deleted)
void addCycleCallback (ArFunctor *functor)
Add a callback to be called at every cycle.
bool addData (const char *name, const char *description, ArFunctor2< ArServerClient *, ArNetPacket * > *functor, const char *argumentDescription, const char *returnDescription, const char *commandGroup=NULL, const char *dataFlags=NULL)
Adds a callback to be called when requests for some data are recieved.
bool addDataAdvanced (const char *name, const char *description, ArFunctor2< ArServerClient *, ArNetPacket * > *functor, const char *argumentDescription, const char *returnDescription, const char *commandGroup=NULL, const char *dataFlags=NULL, unsigned int commandNumber=0, ArFunctor2< long, unsigned int > *requestChangedFunctor=NULL, ArRetFunctor2< bool, ArServerClient *, ArNetPacket * > *requestOnceFunctor=NULL)
Adds a callback for requests in a more advanced manner, for internal use.
bool addIdleSingleShotCallback (ArFunctor *functor)
Adds an idle callback to be called once next time the robot is idle.
void addTooManyClientsCB (ArFunctor1< const char * > *functor, int position=50)
Adds a callback when we switch states while starting.
bool allowingIdlePackets (void)
Gets if we're allowing idle packets.
ArServerBase (bool addAriaExitCB=true, const char *serverName="", bool addBackupTimeoutToConfig=true, const char *backupTimeoutName="RobotToClientTimeoutInMins", const char *backupTimeoutDesc="The amount of time the central server can go without sending a packet to the robot successfully (when there are packets to send). A number less than 0 means this won't happen. The time is in minutes but takes doubles (ie .5) (5 seconds is used if the value is positive, but less than that amount)", bool masterServer=false, bool slaveServer=false, bool logPasswordFailureVerbosely=false, bool allowSlowPackets=true, bool allowIdlePackets=true, int maxClientsAllowed=-1, int warningTimeMSec=250)
Constructor.
bool broadcastPacketTcp (ArNetPacket *packet, const char *name)
Broadcasts packets to any client wanting this data.
bool broadcastPacketTcpByCommand (ArNetPacket *packet, unsigned int command)
Broadcasts packets to any client wanting this data.
bool broadcastPacketTcpByCommandWithExclusion (ArNetPacket *packet, unsigned int command, ArServerClient *excludeClient, bool match=false, ArServerClientIdentifier identifier=ArServerClientIdentifier(), bool matchConnectionID=false)
Broadcasts packets to any client wanting this data.
bool broadcastPacketTcpToMatching (ArNetPacket *packet, const char *name, ArServerClientIdentifier identifier, bool matchConnectionID=false)
Broadcasts packets to any client wanting this data that matches the ID.
bool broadcastPacketTcpWithExclusion (ArNetPacket *packet, const char *name, ArServerClient *excludeClient, bool match=false, ArServerClientIdentifier identifier=ArServerClientIdentifier(), bool matchConnectionID=false)
Broadcasts packets to any client wanting this data.
bool broadcastPacketUdp (ArNetPacket *packet, const char *name)
Broadcasts packets to any client wanting this data.
bool broadcastPacketUdpByCommand (ArNetPacket *packet, unsigned int command)
Broadcasts packets to any client wanting this data.
bool broadcastPacketUdpByCommandWithExclusion (ArNetPacket *packet, unsigned int command, ArServerClient *excludeClient, bool match=false, ArServerClientIdentifier identifier=ArServerClientIdentifier(), bool matchConnectionID=false)
Broadcasts packets to any client wanting this data.
bool broadcastPacketUdpToMatching (ArNetPacket *packet, const char *name, ArServerClientIdentifier identifier, bool matchConnectionID)
Broadcasts packets to any client wanting this data that matches.
bool broadcastPacketUdpWithExclusion (ArNetPacket *packet, const char *name, ArServerClient *excludeClient, bool match=false, ArServerClientIdentifier identifier=ArServerClientIdentifier(), bool matchConnectionID=false)
Broadcasts packets to any client wanting this data.
void close (void)
Closes the server.
void closeConnectionID (ArTypes::UByte4 idNum)
Closes connection with a given connection ID.
bool dataHasFlag (const char *name, const char *dataFlag)
Returns if a command has a data flag.
bool dataHasFlagByCommand (unsigned int command, const char *dataFlag)
Returns if a command has a data flag by command number.
void enforceProtocolVersion (const char *protocolVersion)
Enforces that the server is using this protocol version.
void enforceType (ArServerCommands::Type type)
Enforces that the robots that connect are this type.
unsigned int findCommandFromName (const char *command)
Gets the number of a command.
bool getDebugLogging (void)
Gets if this is using debug logging.
long getFrequency (unsigned int command, bool internalCall=false)
Gets the frequncy a command is requested (mostly internal)
int getMostClients (void)
Gets the most clients we've had connected.
int getNumClients (void)
Gets the number of clients connected.
const char * getOpenOnIP (void)
Gets the IP we're opening on (or NULL if there's none)
unsigned int getTcpPort (void)
Gets the tcp port we're using.
unsigned int getUdpPort (void)
Gets the udp port we're using.
const ArServerUserInfo * getUserInfo (void) const
Gets the user info we're using (mostly internal for switching)
bool hasIdleCallbacks (void)
Internal, Sees if we have any idle callbacks we are waiting to process.
bool hasIdlePackets (void)
Internal, Sees if we have any idle packets we are waiting to process.
bool hasSlowPackets (void)
Internal, Sees if we have any slow packets we are waiting to process.
bool idleProcessingPending (void)
Sees if we have any idle processing pending (idle packets or callbacks)
void internalLockup (void)
Internal call to lockup the server (for testing)
bool internalSetDefaultFrequency (const char *command, int frequency)
Internal call that sets the default frequency as a helper for forwarding (if it's faster than the current default)
void internalSetNumClients (int numClients)
Internal, sets the maximum number of clients.
bool loadUserInfo (const char *fileName, const char *baseDirectory="")
Loads up a set of usernames/passwords/permissions from a file.
void logCommandGroups (void)
Logs the groups and commands in those groups.
void logCommandGroupsToFile (const char *fileName)
Logs the groups and commands in those groups to a file.
void logConnections (const char *prefix="")
Logs the connections.
void logGroupDescriptions (void)
Logs the command group names and descriptions.
void logGroupDescriptionsToFile (const char *fileName)
Logs the command group names and descriptions to a file.
void logTracking (bool terse=true)
Logs the tracking on each client (how many packets and bytes were sent)
void logUserInfo (void)
Logs the users and their groups.
void loopOnce (void)
Runs the server loop once.
ArServerClient * makeNewServerClientFromSocket (ArSocket *socket, bool overrideGeneralReject)
Makes a new serverclient from this socket (for switching, needs no password since this was an outgoing connection to a trusted server)
bool open (unsigned int port, const char *openOnIP=NULL, bool tcpOnly=false)
Opens the server to accept new client connections.
void processPacket (ArNetPacket *packet, struct sockaddr_in *sin)
Processes udp packets.
void rejectSinceUsingCentralServer (const char *centralServerIPString)
Tells the server to reject connectings because we're usinga central server.
void remClientRemovedCallback (ArFunctor1< ArServerClient * > *functor)
Remove the callback invoked when a client has been removed.
void remCycleCallback (ArFunctor *functor)
Remove a callback to be called at every cycle.
void remTooManyClientsCB (ArFunctor1< const char * > *functor)
Removes a callback when we switch to running.
void resetTracking (void)
Clears the tracking on all the clients (resets counters)
virtual void run (void)
Runs the server in this thread.
virtual void runAsync (void)
Runs the server in its own thread.
virtual void * runThread (void *arg)
bool sendUdp (ArNetPacket *packet, struct sockaddr_in *sin)
Sends Udp packets.
void setAdditionalDataFlags (const char *additionalDataFlags)
Sets the data flags to add in addition to those passed in.
void setBackupTimeout (double timeoutInMins)
Sets the backup timeout.
void setDebugLogging (bool debugLogging=false)
Sets debug logging.
void setGroupDescription (const char *GrpName, const char *GrpDesc)
Logs the command group names and command group descriptions for those names.
void setServerKey (const char *serverKey)
Sets a 'key' needed to access the server through any account.
void setUserInfo (const ArServerUserInfo *userInfo)
Sets the user info we'll use (mostly internal for switching)
void sleepAfterSend (int msecDelay)
Delays the current thread by the specified msecs, for use after packet sent.
virtual ~ArServerBase ()
Destructor.
Public Member Functions inherited from ArASyncTask
ArASyncTask ()
virtual int create (bool joinable=true, bool lowerPriority=true)
virtual const char * getThreadActivity (void)
virtual void * runInThisThread (void *arg=0)
virtual void stopRunning (void)
virtual ~ArASyncTask ()
Public Member Functions inherited from ArThread
ArThread (bool blockAllSignals=true)
ArThread (ThreadType thread, bool joinable, bool blockAllSignals=true)
ArThread (ArFunctor *func, bool joinable=true, bool blockAllSignals=true)
virtual void cancel (void)
virtual int create (ArFunctor *func, bool joinable=true, bool lowerPriority=true)
virtual int detach (void)
bool getBlockAllSignals (void)
virtual ArFunctor * getFunc (void) const
virtual bool getJoinable (void) const
virtual ThreadType getOSThread (void) const
virtual bool getRunning (void) const
virtual bool getRunningWithLock (void)
virtual const ThreadType * getThread (void) const
virtual const char * getThreadName (void)
virtual bool isThreadFinished () const
virtual bool isThreadStarted () const
virtual int join (void **ret=NULL)
int lock (void)
virtual void logThreadInfo (void)
virtual void setRunning (bool running)
virtual void setThreadName (const char *name)
virtual void threadFinished (void)
virtual void threadStarted (void)
int tryLock (void)
int unlock (void)
virtual ~ArThread ()
Protected Member Functions
void acceptTcpSockets (void)
accepts new sockets and moves them into the client list
ArServerClient * finishAcceptingSocket (ArSocket *socket, bool skipPassword=false, bool overrideGeneralReject=false)
Internal function for server/client switching.
int getRequestTransactionCount ()
Returns the number of request transactions in progress for all connected clients.
void handleEndRequestTransaction (ArServerClient *client, ArNetPacket *packet)
Handles the "endRequestTransaction" packet, and updates the state of the client.
void handleStartRequestTransaction (ArServerClient *client, ArNetPacket *packet)
Handles the "startRequestTransaction" packet, and updates the state of the client.
void identGetConnectionID (ArServerClient *client, ArNetPacket *packet)
The command get the ConnectionID of this server client connection.
void identSetConnectionID (ArServerClient *client, ArNetPacket *packet)
The command set the ConnectionID of this server client connection.
void identSetHereGoal (ArServerClient *client, ArNetPacket *packet)
The command set the here goal of this server client connection.
void identSetSelfIdentifier (ArServerClient *client, ArNetPacket *packet)
The command set the self identifier of this server client connection.
void netIdleProcessingPending (ArServerClient *client, ArNetPacket *packet)
callback for our slow idle thread, which is down below...
bool processFile (void)
void slowIdleCallback (void)
Protected Attributes
ArSocket myAcceptingSocket
std::string myAdditionalDataFlags
std::list< ArServerClient * > myAddList
ArMutex myAddListMutex
bool myAllowIdlePackets
bool myAllowSlowPackets
ArFunctorC< ArServerBase > myAriaExitCB
double myBackupTimeout
ArMutex myBackupTimeoutMutex
std::list< ArFunctor1< ArServerClient * > * > myClientRemovedCallbacks
std::list< ArServerClient * > myClients
ArMutex myClientsMutex
ArTypes::UByte4 myConnectionNumber
std::list< ArFunctor * > myCycleCallbacks
ArMutex myCycleCallbacksMutex
std::map< unsigned int, ArServerData * > myDataMap
ArMutex myDataMutex
bool myDebugLogging
std::map< unsigned int, int > myDefaultFrequency
ArFunctor2C< ArServerBase, ArServerClient *, ArNetPacket * > myEndRequestTransactionCB
std::string myEnforceProtocolVersion
ArServerCommands::Type myEnforceType
ArRetFunctor2C< long, ArServerBase, unsigned int, bool > myGetFrequencyCB
std::map< std::string, std::string > myGroupDescription
our mapping of the group names
bool myHaveIdleCallbacks
bool myHaveIdlePackets
bool myHaveSlowPackets
ArFunctor2C< ArServerBase, ArServerClient *, ArNetPacket * > myIdentGetConnectionIDCB
ArFunctor2C< ArServerBase, ArServerClient *, ArNetPacket * > myIdentSetConnectionIDCB
ArFunctor2C< ArServerBase, ArServerClient *, ArNetPacket * > myIdentSetHereGoalCB
ArFunctor2C< ArServerBase, ArServerClient *, ArNetPacket * > myIdentSetSelfIdentifierCB
std::list< ArFunctor * > myIdleCallbacks
ArMutex myIdleCallbacksMutex
ArFunctor2C< ArServerBase, ArServerClient *, ArNetPacket * > myIdleProcessingPendingCB
bool myLastIdleProcessingPending
bool myLogPasswordFailureVerbosely
std::string myLogPrefix
int myLoopMSecs
int myMaxClientsAllowed
int myMostClients
bool myNewBackupTimeout
unsigned int myNextDataNumber
int myNumClients
bool myOpened
std::string myOpenOnIP
ArRetFunctorC< bool, ArServerBase > myProcessFileCB
ArMutex myProcessingSlowIdleMutex
ArFunctor2C< ArServerBase, ArNetPacket *, struct sockaddr_in * > myProcessPacketCB
int myRejecting
std::string myRejectingString
std::set< ArServerClient * > myRemoveSet
ArMutex myRemoveSetMutex
ArRetFunctor2C< bool, ArServerBase, ArNetPacket *, struct sockaddr_in * > mySendUdpCB
std::string myServerKey
std::string myServerName
SlowIdleThread * mySlowIdleThread
ArFunctor2C< ArServerBase, ArServerClient *, ArNetPacket * > myStartRequestTransactionCB
bool myTcpOnly
unsigned int myTcpPort
ArSocket myTcpSocket
ArTimeChecker myTimeChecker
ArCallbackList1< const char * > myTooManyClientsCBList
unsigned int myUdpPort
ArNetPacketReceiverUdp myUdpReceiver
ArSocket myUdpSocket
const ArServerUserInfo * myUserInfo
bool myUsingOwnNumClients
ArLog::LogLevel myVerboseLogLevel
Protected Attributes inherited from ArThread
bool myRunning
Friends
class ArServerBase::SlowIdleThread
Additional Inherited Members
Public Types inherited from ArThread
enum Status
Static Public Member Functions inherited from ArThread
static void cancelAll (void)
static ArLog::LogLevel getLogLevel (void)
static ThreadType getThisOSThread (void)
static const ThreadType * getThisThread (void)
static const char * getThisThreadName (void)
static void init (void)
static void joinAll (void)
static ThreadType osSelf (void)
static ArThread * self (void)
static void setLogLevel (ArLog::LogLevel level)
static void shutdown ()
static void stopAll ()
static void yieldProcessor (void)
Public Attributes inherited from ArThread
STATUS_ALREADY_DETATCHED
STATUS_FAILED
STATUS_INVALID
STATUS_JOIN_SELF
STATUS_NO_SUCH_THREAD
STATUS_NORESOURCE
Detailed Description
Base server for all networking services.
This class is the "base" server for network services. Start this server by calling open(), and then running the loop with run() or runAsync(), (or loopOnce() if it is absolutely neccesary to use your own loop; see the implementation of run()). You can then pass this object to the various "ArServerInfo", "ArServerHandler", and ArServerMode classes.
Data request callbacks are added to an ArServerBase object by calling addData().
This class takes care of locking in its own function calls so you don't need to worry about locking and unlocking the class before you do things.
The counterpart of this class for clients is ArClientBase.
You can require user names and passwords for making connections to the server, so each user has a set of permissions for different command groups. To do this, load configuration from a userInfo file with loadUserInfo(). You can log the user info (and what commands users have) with logUserInfo(). You can log the command groups with logCommandGroups() or logCommandGroupsToFile(). For a description of the file see ArServerUserInfo. There is also an example in ArNetworking/examples/serverDemo.userInfo.
In addition to the user and password requirement you can set a server "key" (a special string of text) required (in addition to user and password) to access the server with setServerKey(), though this is ONLY used if user and password information is requied (so that older clients can connect if there's no user and password information required).
The way that the passwords are transmitted across the network is this: Upon connection the server sends a randomly generated (for that connection) string of text to the client which we'll call the passwordKey. The client then combines the serverKey (a string which must be known to connect to the server at all), the password, and the passwordKey (that string that is generated uniquely for each connection) and comes up with an md5 of that string and sends that md5 value across the line. The server then compares the md5 from the client with the md5 generated with the correct information on the server... if they match the password is good, otherwise it rejects the connection. This is NOT perfect security but should be much better then plaintext. If you care about perfect security then use an ssh tunnel with something like PUTTY from the machine the client is on to the machine the server is on with an openssh server set up (this'll likely even work in windows with cygwin) and set up a firewall on the machine the server is on that disallows port the server port connection from outside and only allows ssh from outside (and get a book or three and read those).
This class now handles identifiers for the ArServerClients... all server bases will let a client set a self identifier string, and a here goal... those may be used by any server. Messages can be sent to just server clients that match that message (so that its easier to send messages to people who sent commands).
Master servers (the main connection server base on the central server) can also give each connection an id number (with identGetConnectionID). Things that then connect to the other server bases on a master server (slave servers) should then set their ConnectionID (with identSetConnectionID) so that things can relate the different connections together.
See also
ArServerSimpleOpener
ArClientBase
ArServerMode
Examples:
drawingsExample.cpp, drawingsExampleWithRobot.cpp, popupExample.cpp, serverDemo.cpp, and simpleServerExample.cpp.
Constructor & Destructor Documentation
ArServerBase::ArServerBase (bool addAriaExitCB = true, const char * serverName = "", bool addBackupTimeoutToConfig = true, const char * backupTimeoutName = "RobotToClientTimeoutInMins", const char * backupTimeoutDesc = "The amount of time the central server can go without sending a packet to the robot successfully (when there are packets to send). A number less than 0 means this won't happen. The time is in minutes but takes doubles (ie .5) (5 seconds is used if the value is positive, but less than that amount)", bool masterServer = false, bool slaveServer = false, bool logPasswordFailureVerbosely = false, bool allowSlowPackets = true, bool allowIdlePackets = true, int maxClientsAllowed = -1, int warningTimeMSec = 250)
Constructor.
Parameters
addAriaExitCB whether to add an exit callback to aria or not
serverName the name for logging
addBackupTimeoutToConfig whether to add the backup timeout (to clients of this server) as a config option, if this is true it sets a default value for the timeout of 2 minutes, if its false it has no timeout (but you can set one, see ArServerBase::setBackupTimeout())
backupTimeoutName the name of backup timeout
backupTimeoutName the description of backup timeout
masterServer If this is a master server (ie a central manager)
slaveServer If this is a slave server (ie a central forwarder)
logPasswordFailureVerbosely Whether we log password failure verbosely or not
allowSlowPackets Whether we allow slow packets (that go in their own thread) or not... if we don't then they're processed in the main thread like they have always been
allowIdlePackets Whether we allow idle packets (that go in their own thread and are processed only when the robot is idle) or not... if we don't then they're processed in the main thread like they have always been
numClientsAllowed This is the number of client connections allowed, negative values mean allow any number (the default is -1)
References addData(), Aria::addExitCallback(), ArConfig::addParam(), ArConfig::addProcessFileCB(), ArPriority::DETAILED, Aria::getConfig(), myAddListMutex, myAllowIdlePackets, myAllowSlowPackets, myAriaExitCB, myBackupTimeout, myBackupTimeoutMutex, myClientsMutex, myConnectionNumber, myCycleCallbacksMutex, myDataMutex, myDebugLogging, myEndRequestTransactionCB, myEnforceType, myHaveIdleCallbacks, myHaveIdlePackets, myHaveSlowPackets, myIdentGetConnectionIDCB, myIdentSetConnectionIDCB, myIdentSetHereGoalCB, myIdentSetSelfIdentifierCB, myIdleCallbacksMutex, myIdleProcessingPendingCB, myLogPasswordFailureVerbosely, myLogPrefix, myLoopMSecs, myMaxClientsAllowed, myMostClients, myNewBackupTimeout, myNextDataNumber, myNumClients, myOpened, myProcessFileCB, myProcessingSlowIdleMutex, myProcessPacketCB, myRejecting, myRemoveSetMutex, myServerName, mySlowIdleThread, myStartRequestTransactionCB, myTcpPort, myTimeChecker, myUdpPort, myUdpReceiver, myUserInfo, myUsingOwnNumClients, myVerboseLogLevel, ArTimeChecker::setDefaultMSecs(), ArMutex::setLogName(), ArTimeChecker::setName(), ArFunctor::setName(), ArNetPacketReceiverUdp::setProcessPacketCB(), ArThread::setThreadName(), ArServerCommands::TYPE_UNSPECIFIED, and ArLog::Verbose.
ArServerBase::~ArServerBase () virtual
Destructor.
References close(), and mySlowIdleThread.
Member Function Documentation
void ArServerBase::acceptTcpSockets (void) protected
accepts new sockets and moves them into the client list
References ArSocket::accept(), finishAcceptingSocket(), ArSocket::getFD(), myAcceptingSocket, and myTcpSocket.
Referenced by loopOnce(), and remTooManyClientsCB().
void ArServerBase::addClientRemovedCallback (ArFunctor1< ArServerClient * > * functor)
Add a callback to be invoked when a client has been removed (but before it is deleted)
Java Wrapper Library: Use ArFunctor_ServerClient instead of ArFunctor1<ArServerClient*> for functor.
References ArMutex::lock(), myClientRemovedCallbacks, myDataMutex, and ArMutex::unlock().
Referenced by ArCentralManager::ArCentralManager().
void ArServerBase::addCycleCallback (ArFunctor * functor)
Add a callback to be called at every cycle.
Cycle callbacks are called every cycle, in no particular order.
Parameters
functor Functor to add.
References ArMutex::lock(), myCycleCallbacks, myCycleCallbacksMutex, and ArMutex::unlock().
Referenced by ArServerHandlerPopup::ArServerHandlerPopup().
bool ArServerBase::addData (const char * name, const char * description, ArFunctor2< ArServerClient *, ArNetPacket * > * functor, const char * argumentDescription, const char * returnDescription, const char * commandGroup = NULL, const char * dataFlags = NULL)
Adds a callback to be called when requests for some data are recieved.
Note
A callback is called from the server run loop, and if this callback does not return in a timely manner data reception will be delayed (blocked).
Parameters
name the name of the data
description the more verbose description of what the data is for
functor the functor to call when this data is requested
argumentDescription a description of the arguments expected
returnDescription a description of what the data returns
commandGroup the name of the group this command is in
dataFlags Most people won't need this, its for some advanced server things... this is a list of data flags separated by | characters, the flags are listed in ArClientData docs
Python Wrapper Library: Pass the name of a function or a lambda expression for
functor.
Java Wrapper Library: Use a subclass of ArFunctor_ServerData instead of the ArFunctor2 template
functor.
References addDataAdvanced().
Referenced by ArServerHandlerCommands::addCommand(), ArServerHandlerConfig::addDefaultServerCommands(), ArServerInfoDrawings::addDrawing(), ArServerMode::addModeData(), ArServerHandlerCommands::addStringCommand(), ArHybridForwarderVideo::addToCameraCollection(), ArCentralManager::ArCentralManager(), ArClientSwitchManager::ArClientSwitchManager(), ArMapChanger::ArMapChanger(), ArServerBase(), ArServerDeleteFileOnServer::ArServerDeleteFileOnServer(), ArServerFileFromClient::ArServerFileFromClient(), ArServerFileLister::ArServerFileLister(), ArServerFileToClient::ArServerFileToClient(), ArServerHandlerCommands::ArServerHandlerCommands(), ArServerHandlerConfig::ArServerHandlerConfig(), ArServerHandlerMap::ArServerHandlerMap(), ArServerHandlerMapping::ArServerHandlerMapping(), ArServerHandlerPopup::ArServerHandlerPopup(), ArServerInfoDrawings::ArServerInfoDrawings(), ArServerInfoRobot::ArServerInfoRobot(), ArServerInfoSensor::ArServerInfoSensor(), ArServerInfoStrings::ArServerInfoStrings(), ArServerMode::ArServerMode(), ArServerModeRatioDrive::ArServerModeRatioDrive(), ArHybridForwarderVideo::finishConstructor(), and ArServerHandlerCamera::getCameraName().
bool ArServerBase::addDataAdvanced (const char * name, const char * description, ArFunctor2< ArServerClient *, ArNetPacket * > * functor, const char * argumentDescription, const char * returnDescription, const char * commandGroup = NULL, const char * dataFlags = NULL, unsigned int advancedCommandNumber = 0, ArFunctor2< long, unsigned int > * requestChangedFunctor = NULL, ArRetFunctor2< bool, ArServerClient *, ArNetPacket * > * requestOnceFunctor = NULL)
Adds a callback for requests in a more advanced manner, for internal use.
Adds a callback to be called when requests for some data are recieved.
Note
A callback is called from the server run loop, and if this callback does not return in a timely manner data reception will be delayed (blocked).
Parameters
name the name of the data
description the more verbose description of what the data is for
functor the functor to call when this data is requested
argumentDescription a description of the arguments expected
returnDescription a description of what the data returns
commandGroup the name of the group this command is in
dataFlags Most people won't need this, its for some advanced server things... this is a list of data flags separated by | characters, the flags are listed in ArClientData docs
Python Wrapper Library: Pass the name of a function or a lambda expression for
functor.
Java Wrapper Library: Use a subclass of ArFunctor_ServerData instead of the ArFunctor2 template
functor.
Parameters
advancedCommandNumber 0 for most people... it is the optional number of the command, this is a very advanced option and is made for some server forwarding things so basically no one should use it, 0 means use the auto way... anything else does it manually... the number needs to be the same or higher as the next number available
requestChangedFunctor functor called with the lowest amount of time requested for this packet, called whenever the requests for the packet change, note that 0 and higher means thats how often it was asked for, -1 means something has requested the data but just when it is called, and -2 means that nothing wants the data
requestOnceFunctor functor called if this was a request once... with the server and client just like the normal functor, but its only called if its a request once, note that both are called (as long as they aren't NULL of course)
See also
addData()
References ArServerData::addDataFlags(), ArMutex::lock(), ArLog::log(), myAdditionalDataFlags, myDataMap, myDataMutex, myGetFrequencyCB, myNextDataNumber, ArLog::Normal, ArMutex::unlock(), and ArLog::Verbose.
Referenced by addData().
bool ArServerBase::addIdleSingleShotCallback (ArFunctor * functor)
Adds an idle callback to be called once next time the robot is idle.
Note that if idle packets are not allowed then idle callbacks will not work.
Returns
true if the callback was added, false if not
References ArFunctor::getName(), ArMutex::lock(), ArLog::log(), myAllowIdlePackets, myHaveIdleCallbacks, myIdleCallbacks, myIdleCallbacksMutex, myVerboseLogLevel, and ArMutex::unlock().
void ArServerBase::addTooManyClientsCB (ArFunctor1< const char * > * functor, int position = 50) inline
Adds a callback when we switch states while starting.
References ArGenericCallbackList< GenericFunctor >::addCallback(), and myTooManyClientsCBList.
bool ArServerBase::allowingIdlePackets (void)
Gets if we're allowing idle packets.
References myAllowIdlePackets.
bool ArServerBase::broadcastPacketTcp (ArNetPacket * packet, const char * name)
Broadcasts packets to any client wanting this data.
This will broadcast this packet to any client that wants this data....
this no longer excludes things because that doesn't work well with the central server, so use broadcastPacketTcpWithExclusion for that if you really want it...
Parameters
packet the packet to send
name the type of data to send
Returns
false if there is no data for this name
References broadcastPacketTcpWithExclusion().
Referenced by ArServerInfoStrings::addString(), ArServerHandlerCamera::cameraModeLookAtGoal(), ArServerHandlerCamera::cameraModeLookAtPoint(), ArServerHandlerCamera::cameraModePosition(), ArServerMode::checkBroadcastModeInfoPacket(), ArServerHandlerPopup::closePopup(), ArServerHandlerConfig::createEmptyConfigDefaults(), ArServerHandlerPopup::createPopup(), ArServerHandlerCommMonitor::cycleCallback(), ArServerHandlerCameraCollection::handleCameraCollectionModified(), ArMapChanger::handleChangePacket(), ArServerFileFromClient::internalPutFile(), ArServerHandlerConfig::internalSetConfig(), ArServerHandlerConfig::loadDefaultsFromFile(), ArServerHandlerConfig::loadDefaultsFromPacket(), ArServerHandlerMap::loadMap(), loopOnce(), ArServerHandlerMap::mapChanged(), ArServerMode::modeUserTask(), ArServerHandlerPopup::netPopupClicked(), ArServerHandlerConfig::restartHardware(), ArServerHandlerConfig::restartSoftware(), ArCentralManager::runThread(), ArServerHandlerPopup::serverCycleCallback(), ArServerHandlerMapping::serverMappingEnd(), ArServerHandlerMapping::serverMappingStart(), ArServerHandlerCameraCollection::setParams(), ArServerHandlerMap::useMap(), and ArServerInfoRobot::userTask().
bool ArServerBase::broadcastPacketTcpByCommand (ArNetPacket * packet, unsigned int command)
Broadcasts packets to any client wanting this data.
This will broadcast this packet to any client that wants this data....
this no longer excludes things because that doesn't work well with the central server, so use broadcastPacketTcpByCommandWithExclusion for that...
Parameters
packet the packet to send
command the command number of the data to send
Returns
false if there is no data for this name
References broadcastPacketTcpByCommandWithExclusion().
Referenced by ArCentralForwarder::receiveData().
bool ArServerBase::broadcastPacketTcpByCommandWithExclusion (ArNetPacket * packet, unsigned int command, ArServerClient * excludeClient, bool match = false, ArServerClientIdentifier identifier = ArServerClientIdentifier(), bool matchConnectionID = false)
Broadcasts packets to any client wanting this data.
This will broadcast this packet to any client that wants this data.
Parameters
packet the packet to send
command the command number of the data to send
excludeClient don't send data to this client (NULL (the default) just ignores this feature)
match whether to match the identifier or not
identifier the identifier to match
matchConnectionID true to match the connection ID, false to match the other ID
Returns
false if there is no data for this name
References ArServerClient::broadcastPacketTcp(), ArNetPacket::empty(), ArServerClient::getIdentifier(), ArMutex::lock(), ArLog::log(), ArServerClientIdentifier::matches(), myClients, myClientsMutex, myOpened, ArNetPacket::setCommand(), ArMutex::unlock(), and ArLog::Verbose.
Referenced by broadcastPacketTcpByCommand(), and broadcastPacketTcpWithExclusion().
bool ArServerBase::broadcastPacketTcpToMatching (ArNetPacket * packet, const char * name, ArServerClientIdentifier identifier, bool matchConnectionID = false)
Broadcasts packets to any client wanting this data that matches the ID.
This will broadcast this packet to any client that wants this data....
Parameters
packet the packet to send
name the type of data to send
identifier the identifier to match
matchConnectionID true to match the connection ID, false to match the other ID
Returns
false if there is no data for this name
References broadcastPacketTcpWithExclusion().
Referenced by ArCentralManager::forwarderServerClientRemovedCallback().
bool ArServerBase::broadcastPacketTcpWithExclusion (ArNetPacket * packet, const char * name, ArServerClient * excludeClient, bool match = false, ArServerClientIdentifier identifier = ArServerClientIdentifier(), bool matchConnectionID = false)
Broadcasts packets to any client wanting this data.
This will broadcast this packet to any client that wants this data.
Parameters
packet the packet to send
name the type of data to send
excludeClient don't send data to this client (NULL (the default) just ignores this feature)
match whether to match the identifier or not
identifier the identifier to match
matchConnectionID true to match the connection ID, false to match the other ID
Returns
false if there is no data for this name
References broadcastPacketTcpByCommandWithExclusion(), ArMutex::lock(), ArLog::log(), myDataMap, myDataMutex, myVerboseLogLevel, and ArMutex::unlock().
Referenced by broadcastPacketTcp(), broadcastPacketTcpToMatching(), and ArServerHandlerConfig::configUpdated().
bool ArServerBase::broadcastPacketUdp (ArNetPacket * packet, const char * name)
Broadcasts packets to any client wanting this data.
This will broadcast this packet to any client that wants this data....
this no longer excludes things because that doesn't work well with the central server, so use broadcastPacketUdpWithExclusion for that if you really want to
Parameters
packet the packet to send
name the type of data to send
Returns
false if there is no data for this name
References broadcastPacketUdpWithExclusion().
Referenced by ArServerHandlerCommMonitor::cycleCallback().
bool ArServerBase::broadcastPacketUdpByCommand (ArNetPacket * packet, unsigned int command)
Broadcasts packets to any client wanting this data.
This will broadcast this packet to any client that wants this data....
(To restrict what clients the command is sent to, use the broadcastPacketUdpByCommandWithExclusion() method.)
Parameters
packet the packet to send
command the type of data to send
Returns
false if there is no data for this name
References broadcastPacketUdpByCommandWithExclusion().
Referenced by ArCentralForwarder::receiveData().
bool ArServerBase::broadcastPacketUdpByCommandWithExclusion (ArNetPacket * packet, unsigned int command, ArServerClient * excludeClient, bool match = false, ArServerClientIdentifier identifier = ArServerClientIdentifier(), bool matchConnectionID = false)
Broadcasts packets to any client wanting this data.
This will broadcast this packet to any client that wants this data.
Parameters
packet the packet to send
command the type of data to send
excludeClient don't send data to this client (NULL (the default) just ignores this feature)
match whether to match the identifier or not
identifier the identifier to match
matchConnectionID true to match the connection ID, false to match the other ID
Returns
false if there is no data for this name
References ArServerClient::broadcastPacketUdp(), ArNetPacket::empty(), ArServerClient::getIdentifier(), ArMutex::lock(), ArLog::log(), ArServerClientIdentifier::matches(), myClients, myClientsMutex, myOpened, ArNetPacket::setCommand(), ArMutex::unlock(), and ArLog::Verbose.
Referenced by broadcastPacketUdpByCommand(), and broadcastPacketUdpWithExclusion().
bool ArServerBase::broadcastPacketUdpToMatching (ArNetPacket * packet, const char * name, ArServerClientIdentifier identifier, bool matchConnectionID)
Broadcasts packets to any client wanting this data that matches.
This will broadcast this packet to any client that wants this data....
Parameters
packet the packet to send
name the type of data to send
identifier the identifier to match
matchConnectionID true to match the connection ID, false to match the other ID
Returns
false if there is no data for this name
References broadcastPacketUdpWithExclusion().
bool ArServerBase::broadcastPacketUdpWithExclusion (ArNetPacket * packet, const char * name, ArServerClient * excludeClient, bool match = false, ArServerClientIdentifier identifier = ArServerClientIdentifier(), bool matchConnectionID = false)
Broadcasts packets to any client wanting this data.
This will broadcast this packet to any client that wants this data.
Parameters
packet the packet to send
name the type of data to send
excludeClient don't send data to this client (NULL (the default) just ignores this feature)
match whether to match the identifier or not
identifier the identifier to match
matchConnectionID true to match the connection ID, false to match the other ID
Returns
false if there is no data for this name
References broadcastPacketUdpByCommandWithExclusion(), ArMutex::lock(), ArLog::log(), myDataMap, myDataMutex, myVerboseLogLevel, and ArMutex::unlock().
Referenced by broadcastPacketUdp(), and broadcastPacketUdpToMatching().
void ArServerBase::close (void)
Closes the server.
MPL adding this since it looks like its leaked
References client, ArSocket::close(), ArUtil::deleteSetPairs(), ArMutex::lock(), ArLog::log(), myClients, myClientsMutex, myDataMap, myDataMutex, myLogPrefix, myOpened, myTcpOnly, myTcpSocket, myUdpSocket, ArLog::Normal, ArServerClient::shutdown(), ArUtil::sleep(), and ArMutex::unlock().
Referenced by runThread(), ArCentralForwarder::~ArCentralForwarder(), and ~ArServerBase().
void ArServerBase::closeConnectionID (ArTypes::UByte4 idNum)
Closes connection with a given connection ID.
References client, ArServerClient::forceDisconnect(), ArServerClientIdentifier::getConnectionID(), ArServerClient::getIdentifier(), ArMutex::lock(), ArLog::log(), myClients, myClientsMutex, myLogPrefix, myRemoveSet, myRemoveSetMutex, ArMutex::unlock(), and ArLog::Verbose.
Referenced by ArCentralManager::mainServerClientRemovedCallback().
bool ArServerBase::dataHasFlag (const char * name, const char * dataFlag)
Returns if a command has a data flag.
References dataHasFlagByCommand(), findCommandFromName(), ArLog::log(), and ArLog::Verbose.
Referenced by ArCentralForwarder::gatheringCallOnce().
bool ArServerBase::dataHasFlagByCommand (unsigned int command, const char * dataFlag)
Returns if a command has a data flag by command number.
References ArMutex::lock(), myDataMap, myDataMutex, and ArMutex::unlock().
Referenced by dataHasFlag().
void ArServerBase::enforceProtocolVersion (const char * protocolVersion)
Enforces that the server is using this protocol version.
References ArMutex::lock(), ArLog::log(), myDataMutex, myEnforceProtocolVersion, myLogPrefix, ArLog::Normal, and ArMutex::unlock().
Referenced by ArServerClient::ArServerClient().
void ArServerBase::enforceType (ArServerCommands::Type type)
Enforces that the robots that connect are this type.
References ArMutex::lock(), ArLog::log(), myDataMutex, myEnforceType, myLogPrefix, ArLog::Normal, ArServerCommands::toString(), and ArMutex::unlock().
Referenced by ArServerClient::ArServerClient().
unsigned int ArServerBase::findCommandFromName (const char * name)
Gets the number of a command.
Parameters
name Name is the name of the command number to be found
Returns
the number of the command or 0 if no command has that name
References ArMutex::lock(), ArLog::log(), myDataMap, myDataMutex, myVerboseLogLevel, and ArMutex::unlock().
Referenced by dataHasFlag(), ArServerHandlerPopup::netPopupList(), ArServerHandlerConfig::setConfig(), ArServerHandlerConfig::setConfigBySections(), ArServerHandlerConfig::setConfigBySectionsV2(), and ArServerHandlerConfig::setConfigParam().
ArServerClient * ArServerBase::finishAcceptingSocket (ArSocket * socket, bool skipPassword = false, bool overrideGeneralReject = false) protected
Internal function for server/client switching.
References client, ArSocket::getIPString(), ArCallbackList1< P1 >::invoke(), ArMutex::lock(), ArLog::log(), myAddList, myAddListMutex, myAllowIdlePackets, myAllowSlowPackets, myClients, myClientsMutex, myDataMap, myDebugLogging, myEnforceProtocolVersion, myEnforceType, myLogPasswordFailureVerbosely, myLogPrefix, myMaxClientsAllowed, myNumClients, myRejecting, myRejectingString, mySendUdpCB, myServerKey, myServerName, myTooManyClientsCBList, myUdpPort, myUserInfo, myVerboseLogLevel, ArLog::Normal, ArMath::random(), and ArMutex::unlock().
Referenced by acceptTcpSockets(), makeNewServerClientFromSocket(), and remTooManyClientsCB().
bool ArServerBase::getDebugLogging (void)
Gets if this is using debug logging.
References myDebugLogging.
long ArServerBase::getFrequency (unsigned int command, bool internalCall = false)
Gets the frequncy a command is requested (mostly internal)
Parameters
command the command number, you can use findCommandFromName
internalCall whether its an internal call or not (whether to lock or not)
Returns
returns lowest amount of time requested for this packet, note that 0 and higher means thats how often it was asked for, -1 means nothing requested the data at an interval but wants it when its been pushed, and -2 means that nothing wants the data
References ArMutex::lock(), myClients, myClientsMutex, myDefaultFrequency, and ArMutex::unlock().
int ArServerBase::getMostClients (void)
Gets the most clients we've had connected.
References myMostClients.
int ArServerBase::getNumClients (void)
Gets the number of clients connected.
References myNumClients.
Referenced by ArCentralManager::logConnections(), and ArCentralManager::runThread().
const char * ArServerBase::getOpenOnIP (void)
Gets the IP we're opening on (or NULL if there's none)
Examples:
serverDemo.cpp.
References myOpenOnIP.
Referenced by ArCentralForwarder::gatheringCallOnce(), main(), and ArClientSwitchManager::runThread().
int ArServerBase::getRequestTransactionCount () protected
Returns the number of request transactions in progress for all connected clients.
See also
handleStartRequestTransaction
References client, ArServerClient::getRequestTransactionCount(), ArMutex::lock(), myClients, myClientsMutex, and ArMutex::unlock().
Referenced by remTooManyClientsCB(), and slowIdleCallback().
unsigned int ArServerBase::getTcpPort (void)
Gets the tcp port we're using.
References myTcpPort.
Referenced by ArCentralManager::runThread().
unsigned int ArServerBase::getUdpPort (void)
Gets the udp port we're using.
References myUdpPort.
const ArServerUserInfo * ArServerBase::getUserInfo (void) const
Gets the user info we're using (mostly internal for switching)
References myUserInfo.
Referenced by ArCentralForwarder::gatheringCallOnce().
void ArServerBase::handleEndRequestTransaction (ArServerClient * client, ArNetPacket * packet) protected
Handles the "endRequestTransaction" packet, and updates the state of the client.
Parameters
client the ArServerClient* that sent the request; updated to indicate that a transaction has completed
packet the ArNetPacket* that contains the request (no additional data)
See also
handleStartRequestTransaction
References ArServerClient::endRequestTransaction(), ArServerClient::getIPString(), ArLog::log(), and ArLog::Verbose.
Referenced by remTooManyClientsCB().
void ArServerBase::handleStartRequestTransaction (ArServerClient * client, ArNetPacket * packet) protected
Handles the "startRequestTransaction" packet, and updates the state of the client.
"Request transactions" are used to indicate that a sequence of request / reply packets must be completed before idle processing can proceed. Any "startRequestTransaction" MUST be followed by an "endRequestTransaction".
The packets are meant to be used sparingly. They are currently only used when the Central Server is determining whether the map file needs to be downloaded to the client robot.
Parameters
client the ArServerClient* that sent the request; updated to indicate a new transaction is in progress
packet the ArNetPacket* that contains the request (no additional data)
References ArServerClient::getIPString(), ArLog::log(), ArServerClient::startRequestTransaction(), and ArLog::Verbose.
Referenced by remTooManyClientsCB().
bool ArServerBase::hasIdleCallbacks (void)
Internal, Sees if we have any idle callbacks we are waiting to process.
References myHaveIdleCallbacks.
bool ArServerBase::hasIdlePackets (void)
Internal, Sees if we have any idle packets we are waiting to process.
References myHaveIdlePackets.
bool ArServerBase::hasSlowPackets (void)
Internal, Sees if we have any slow packets we are waiting to process.
References myHaveSlowPackets.
void ArServerBase::identGetConnectionID (ArServerClient * client, ArNetPacket * packet) protected
The command get the ConnectionID of this server client connection.
References ArServerClientIdentifier::getConnectionID(), ArServerClient::getIdentifier(), ArLog::log(), myClients, myConnectionNumber, ArServerClient::sendPacketTcp(), ArServerClientIdentifier::setConnectionID(), ArServerClient::setIdentifier(), ArLog::Terse, and ArBasePacket::uByte4ToBuf().
Referenced by remTooManyClientsCB().
void ArServerBase::identSetConnectionID (ArServerClient * client, ArNetPacket * packet) protected
The command set the ConnectionID of this server client connection.
References ArBasePacket::bufToUByte4(), ArServerClient::getIdentifier(), ArServerClientIdentifier::setConnectionID(), and ArServerClient::setIdentifier().
Referenced by remTooManyClientsCB().
void ArServerBase::identSetHereGoal (ArServerClient * client, ArNetPacket * packet) protected
The command set the here goal of this server client connection.
References ArBasePacket::bufToStr(), ArServerClient::getIdentifier(), ArServerClientIdentifier::setHereGoal(), and ArServerClient::setIdentifier().
Referenced by remTooManyClientsCB().
void ArServerBase::identSetSelfIdentifier (ArServerClient * client, ArNetPacket * packet) protected
The command set the self identifier of this server client connection.
References ArBasePacket::bufToStr(), ArServerClient::getIdentifier(), ArServerClient::setIdentifier(), and ArServerClientIdentifier::setSelfIdentifier().
Referenced by remTooManyClientsCB().
bool ArServerBase::idleProcessingPending (void)
Sees if we have any idle processing pending (idle packets or callbacks)
References myHaveIdleCallbacks, and myHaveIdlePackets.
Referenced by ArServerMode::baseActivate(), loopOnce(), netIdleProcessingPending(), and ArServerModeIdle::userTask().
void ArServerBase::internalLockup (void)
Internal call to lockup the server (for testing)
References ArMutex::lock(), ArLog::log(), myDataMutex, myServerName, and ArLog::Normal.
Referenced by remTooManyClientsCB().
bool ArServerBase::internalSetDefaultFrequency (const char * command, int frequency)
Internal call that sets the default frequency as a helper for forwarding (if it's faster than the current default)
Parameters
command the command name as a string
frequency the frequency to get the data, > 0 == milliseconds, -1 == on broadcast, -2 == never... This function won't set the value to anything slower than has already been requested
References ArServerData::callRequestChangedFunctor(), data, ArServerData::getCommand(), ArMutex::lock(), ArLog::log(), myClientsMutex, myDataMap, myDataMutex, myDefaultFrequency, myServerName, ArLog::Normal, and ArMutex::unlock().
Referenced by remTooManyClientsCB(), and ArCentralForwarder::request().
void ArServerBase::internalSetNumClients (int numClients)
Internal, sets the maximum number of clients.
References myNumClients, and myUsingOwnNumClients.
Referenced by ArCentralManager::runThread().
bool ArServerBase::loadUserInfo (const char * fileName, const char * baseDirectory = "")
Loads up a set of usernames/passwords/permissions from a file.
References ArServerUserInfo::doNotUse(), ArMutex::lock(), ArLog::log(), myDataMutex, myLogPrefix, myUserInfo, ArLog::Normal, ArServerUserInfo::readFile(), ArServerUserInfo::setBaseDirectory(), ArLog::Terse, and ArMutex::unlock().
Referenced by ArServerSimpleOpener::open().
void ArServerBase::logCommandGroups (void)
Logs the groups and commands in those groups.
Logs the different groups of commands.
It logs the command names first along with the list of commands in that group. Then it outputs a list of groups. Useful for building the user/pass file.
References logCommandGroupsToFile().
Referenced by ArServerSimpleOpener::checkAndLog().
void ArServerBase::logCommandGroupsToFile (const char * fileName)
Logs the groups and commands in those groups to a file.
For a description of what this outputs see logCommandGroups.
References file, ArUtil::fopen(), ArMutex::lock(), ArLog::log(), myDataMap, myDataMutex, myGroupDescription, ArUtil::strcasecmp(), ArLog::Terse, and ArMutex::unlock().
Referenced by logCommandGroups().
void ArServerBase::logConnections (const char * prefix = "")
Logs the connections.
References client, ArServerClient::getIPString(), ArMutex::lock(), ArLog::log(), myClients, myClientsMutex, myMostClients, myServerName, ArLog::Normal, and ArMutex::unlock().
Referenced by ArCentralManager::logConnections(), and ArServerSimpleServerCommands::logConnections().
void ArServerBase::logGroupDescriptions (void)
Logs the command group names and descriptions.
References logGroupDescriptionsToFile().
void ArServerBase::logGroupDescriptionsToFile (const char * fileName)
Logs the command group names and descriptions to a file.
References file, ArUtil::fopen(), ArMutex::lock(), ArLog::log(), myDataMutex, myGroupDescription, ArLog::Terse, and ArMutex::unlock().
Referenced by logGroupDescriptions().
void ArServerBase::logTracking (bool terse = true)
Logs the tracking on each client (how many packets and bytes were sent)
References ArSocket::getBytesRecvd(), ArSocket::getBytesSent(), ArSocket::getRecvs(), ArSocket::getSends(), ArMutex::lock(), ArLog::log(), myClients, myClientsMutex, myUdpSocket, ArLog::Terse, and ArMutex::unlock().
Referenced by ArServerSimpleServerCommands::logTerseTracking(), and ArServerSimpleServerCommands::logVerboseTracking().
void ArServerBase::logUserInfo (void)
Logs the users and their groups.
References ArMutex::lock(), ArLog::log(), ArServerUserInfo::logUsers(), myDataMutex, myLogPrefix, myUserInfo, ArLog::Terse, and ArMutex::unlock().
Referenced by ArServerSimpleOpener::checkAndLog().
void ArServerBase::loopOnce (void)
Runs the server loop once.
This runs the server loop once, normally you'll probably just use run() or runAsync(), but if you want to drive this server from within your own loop just call this repeatedly, but do note it takes up no time at all, so you'll want to put in your own millisecond sleep so it doesn't monopolize the CPU.
References acceptTcpSockets(), broadcastPacketTcp(), ArBasePacket::byteToBuf(), ArTimeChecker::check(), client, ArTimeChecker::finish(), ArServerClient::forceDisconnect(), ArServerClient::handleRequests(), ArServerClient::hasIdlePackets(), ArServerClient::hasSlowPackets(), idleProcessingPending(), ArMutex::lock(), myAddList, myAddListMutex, myBackupTimeout, myBackupTimeoutMutex, myClientRemovedCallbacks, myClients, myClientsMutex, myCycleCallbacks, myCycleCallbacksMutex, myDataMutex, myHaveIdlePackets, myHaveSlowPackets, myLastIdleProcessingPending, myMostClients, myNewBackupTimeout, myNumClients, myOpened, myProcessingSlowIdleMutex, myRemoveSet, myRemoveSetMutex, myTcpOnly, myTimeChecker, myUdpReceiver, myUsingOwnNumClients, ArNetPacketReceiverUdp::readData(), ArServerClient::setBackupTimeout(), ArTimeChecker::start(), ArServerClient::tcpCallback(), ArMutex::tryLock(), and ArMutex::unlock().
Referenced by ArCentralForwarder::connectedCallOnce(), runThread(), and sleepAfterSend().
ArServerClient * ArServerBase::makeNewServerClientFromSocket (ArSocket * socket, bool overrideGeneralReject)
Makes a new serverclient from this socket (for switching, needs no password since this was an outgoing connection to a trusted server)
References finishAcceptingSocket().
Referenced by ArClientSwitchManager::clientSwitch().
void ArServerBase::netIdleProcessingPending (ArServerClient * client, ArNetPacket * packet) protected
callback for our slow idle thread, which is down below...
The command that returns if there is idle processing to do
References ArBasePacket::byteToBuf(), idleProcessingPending(), and ArServerClient::sendPacketTcp().
Referenced by remTooManyClientsCB().
bool ArServerBase::open (unsigned int port, const char * openOnIP = NULL, bool tcpOnly = false)
Opens the server to accept new client connections.
This opens the server up on the given port, you will then need to run the server for it to actually listen and respond to client connections.
Parameters
port the port to open the server on
openOnIP If not null, only listen on the local network interface with this address
tcpOnly If true, only accept TCP connections. If false, use both TCP and UDP communications with clients.
Returns
true if the server could open the port, false otherwise
References ArSocket::close(), ArSocket::create(), ArSocket::findValidPort(), ArSocket::inPort(), ArMutex::lock(), ArLog::log(), myDataMutex, myLogPrefix, myOpened, myOpenOnIP, myTcpOnly, myTcpPort, myTcpSocket, myUdpPort, myUdpReceiver, myUdpSocket, ArSocket::netToHostOrder(), ArLog::Normal, ArSocket::open(), ArSocket::setNonBlock(), ArNetPacketReceiverUdp::setSocket(), and ArMutex::unlock().
Referenced by main(), and ArServerSimpleOpener::open().
bool ArServerBase::processFile (void) protected
References myBackupTimeout, and setBackupTimeout().
Referenced by remTooManyClientsCB().
void ArServerBase::processPacket (ArNetPacket * packet, struct sockaddr_in * sin)
Processes udp packets.
References ArBasePacket::bufToUByte4(), client, ArNetPacket::getCommand(), ArMutex::lock(), ArLog::log(), myClients, myClientsMutex, myDataMap, ArSocket::netToHostOrder(), ArLog::Normal, ArClientBase::processPacket(), ArNetPacket::resetRead(), ArClientCommands::UDP_INTRODUCTION, and ArMutex::unlock().
void ArServerBase::rejectSinceUsingCentralServer (const char * centralServerIPString)
Tells the server to reject connectings because we're usinga central server.
References ArMutex::lock(), myDataMutex, myRejecting, myRejectingString, and ArMutex::unlock().
void ArServerBase::remClientRemovedCallback (ArFunctor1< ArServerClient * > * functor)
Remove the callback invoked when a client has been removed.
Java Wrapper Library: Use ArFunctor_ServerClient instead of ArFunctor1<ArServerClient*> for functor.
References ArMutex::lock(), myClientRemovedCallbacks, myDataMutex, and ArMutex::unlock().
void ArServerBase::remCycleCallback (ArFunctor * functor)
Remove a callback to be called at every cycle.
Cycle callbacks are called every cycle, in no particular order.
Parameters
functor Functor to remove. If it's not currently in the cycle callback list, nothing is done.
References ArMutex::lock(), myCycleCallbacks, myCycleCallbacksMutex, and ArMutex::unlock().
void ArServerBase::remTooManyClientsCB (ArFunctor1< const char * > * functor) inline
Removes a callback when we switch to running.
References acceptTcpSockets(), client, finishAcceptingSocket(), getRequestTransactionCount(), handleEndRequestTransaction(), handleStartRequestTransaction(), identGetConnectionID(), identSetConnectionID(), identSetHereGoal(), identSetSelfIdentifier(), internalLockup(), internalSetDefaultFrequency(), myTooManyClientsCBList, netIdleProcessingPending(), processFile(), ArGenericCallbackList< GenericFunctor >::remCallback(), and slowIdleCallback().
void ArServerBase::resetTracking (void)
Clears the tracking on all the clients (resets counters)
References ArMutex::lock(), myClients, myClientsMutex, myDataMutex, myUdpSocket, ArSocket::resetTracking(), and ArMutex::unlock().
Referenced by ArServerSimpleServerCommands::resetTracking().
void ArServerBase::run (void) virtual
Runs the server in this thread.
Reimplemented from ArASyncTask.
References ArASyncTask::runInThisThread().
Referenced by main().
void ArServerBase::runAsync (void) virtual
Runs the server in its own thread.
Reimplemented from ArASyncTask.
Examples:
drawingsExample.cpp, drawingsExampleWithRobot.cpp, popupExample.cpp, serverDemo.cpp, and simpleServerExample.cpp.
References ArASyncTask::create().
Referenced by main(), and ArServerBase::SlowIdleThread::SlowIdleThread().
void * ArServerBase::runThread (void * arg) virtual
Implements ArASyncTask.
References close(), loopOnce(), myLoopMSecs, ArThread::myRunning, ArUtil::sleep(), ArThread::threadFinished(), and ArThread::threadStarted().
bool ArServerBase::sendUdp (ArNetPacket * packet, struct sockaddr_in * sin)
Sends Udp packets.
References ArBasePacket::getBuf(), ArBasePacket::getLength(), myUdpSocket, ArSocket::sendTo(), and sin().
void ArServerBase::setAdditionalDataFlags (const char * additionalDataFlags)
Sets the data flags to add in addition to those passed in.
Additional data flags to be added to addData calls (these are added in with what is there).
You can do multiple flags by separating them with a | character.
References ArMutex::lock(), myAdditionalDataFlags, myDataMutex, and ArMutex::unlock().
void ArServerBase::setBackupTimeout (double timeoutInMins)
Sets the backup timeout.
Sets up the backup timeout, if there are packets to send to clients and they haven't been sent for longer than this then the connection is closed.
Less than 0 means this won't happen. If this is positive but less than 5 seconds then 5 seconds is used.
References ArMutex::lock(), myBackupTimeout, myBackupTimeoutMutex, myNewBackupTimeout, and ArMutex::unlock().
Referenced by ArCentralForwarder::connectedCallOnce(), ArCentralManager::processFile(), and processFile().
void ArServerBase::setDebugLogging (bool debugLogging = false)
Sets debug logging.
References myDebugLogging, myVerboseLogLevel, ArLog::Normal, and ArLog::Verbose.
void ArServerBase::setGroupDescription (const char * cmdGrpName, const char * cmdGrpDesc)
Logs the command group names and command group descriptions for those names.
=========================================================================/// Function: setGroupDescription /// Created: 17-Nov-2005 /// Purpose: To permit the user to update the Command Group Descriptions.
/// Notes: /// /// Revision History: /// WHEN WHO WHAT and/or WHY /// 17-Nov-2005 NJ Created this function. /// /// =========================================================================///
References ArMutex::lock(), myDataMutex, myGroupDescription, and ArMutex::unlock().
void ArServerBase::setServerKey (const char * serverKey)
Sets a 'key' needed to access the server through any account.
Text string that is the key required when using user and password information...
this is NOT used if there is no user and password information.
References ArMutex::lock(), ArLog::log(), myDataMutex, myServerKey, ArLog::Normal, and ArMutex::unlock().
Referenced by ArServerSimpleOpener::open().
void ArServerBase::setUserInfo (const ArServerUserInfo * userInfo)
Sets the user info we'll use (mostly internal for switching)
References ArMutex::lock(), myDataMutex, myUserInfo, and ArMutex::unlock().
void ArServerBase::sleepAfterSend (int msecDelay)
Delays the current thread by the specified msecs, for use after packet sent.
Call this method to delay the current thread after a packet has been sent.
This allows the packet to be transmitted before any subsequent action.
If the call is made in the main server thread, then loop once will be called until the specified time has passed. If the call is made in the idle thread, then ArUtil::sleep is used. (Note that if ArUtil::sleep() were called in the main thread, then the packet would not actually be transmitted until after the sleep exits.)
References IFDEBUG, ArLog::log(), loopOnce(), ArTime::mSecSince(), mySlowIdleThread, ArLog::Normal, ArThread::self(), and ArUtil::sleep().
Referenced by ArServerHandlerConfig::restartHardware(), and ArServerHandlerConfig::restartSoftware().
void ArServerBase::slowIdleCallback (void) protected
References client, ArServerClient::forceDisconnect(), ArServerMode::getActiveModeActivityTimeSecSince(), ArFunctor::getName(), getRequestTransactionCount(), ArServerClient::idlePacketCallback(), ArFunctor::invoke(), ArMutex::lock(), ArLog::log(), myAllowIdlePackets, myAllowSlowPackets, myClients, myHaveIdleCallbacks, myIdleCallbacks, myIdleCallbacksMutex, myLoopMSecs, myOpened, myProcessingSlowIdleMutex, myRemoveSet, myRemoveSetMutex, myVerboseLogLevel, ArUtil::sleep(), ArServerClient::slowPacketCallback(), ArMutex::unlock(), and ArLog::Verbose.
Referenced by remTooManyClientsCB().
Friends And Related Function Documentation
friend class ArServerBase::SlowIdleThread friend
Member Data Documentation
ArSocket ArServerBase::myAcceptingSocket protected
Referenced by acceptTcpSockets().
std::string ArServerBase::myAdditionalDataFlags protected
Referenced by addDataAdvanced(), and setAdditionalDataFlags().
std::list<ArServerClient *> ArServerBase::myAddList protected
Referenced by finishAcceptingSocket(), and loopOnce().
ArMutex ArServerBase::myAddListMutex protected
Referenced by ArServerBase(), finishAcceptingSocket(), and loopOnce().
bool ArServerBase::myAllowIdlePackets protected
Referenced by addIdleSingleShotCallback(), allowingIdlePackets(), ArServerBase(), finishAcceptingSocket(), and slowIdleCallback().
bool ArServerBase::myAllowSlowPackets protected
Referenced by ArServerBase(), finishAcceptingSocket(), and slowIdleCallback().
ArFunctorC<ArServerBase> ArServerBase::myAriaExitCB protected
Referenced by ArServerBase().
double ArServerBase::myBackupTimeout protected
Referenced by ArServerBase(), loopOnce(), processFile(), and setBackupTimeout().
ArMutex ArServerBase::myBackupTimeoutMutex protected
Referenced by ArServerBase(), loopOnce(), and setBackupTimeout().
std::list<ArFunctor1<ArServerClient *> *> ArServerBase::myClientRemovedCallbacks protected
Referenced by addClientRemovedCallback(), loopOnce(), and remClientRemovedCallback().
std::list<ArServerClient *> ArServerBase::myClients protected
Referenced by broadcastPacketTcpByCommandWithExclusion(), broadcastPacketUdpByCommandWithExclusion(), close(), closeConnectionID(), finishAcceptingSocket(), getFrequency(), getRequestTransactionCount(), identGetConnectionID(), logConnections(), logTracking(), loopOnce(), processPacket(), resetTracking(), and slowIdleCallback().
ArMutex ArServerBase::myClientsMutex protected
Referenced by ArServerBase(), broadcastPacketTcpByCommandWithExclusion(), broadcastPacketUdpByCommandWithExclusion(), close(), closeConnectionID(), finishAcceptingSocket(), getFrequency(), getRequestTransactionCount(), internalSetDefaultFrequency(), logConnections(), logTracking(), loopOnce(), processPacket(), and resetTracking().
ArTypes::UByte4 ArServerBase::myConnectionNumber protected
Referenced by ArServerBase(), and identGetConnectionID().
std::list<ArFunctor*> ArServerBase::myCycleCallbacks protected
Referenced by addCycleCallback(), loopOnce(), and remCycleCallback().
ArMutex ArServerBase::myCycleCallbacksMutex protected
Referenced by addCycleCallback(), ArServerBase(), loopOnce(), and remCycleCallback().
std::map<unsigned int, ArServerData *> ArServerBase::myDataMap protected
Referenced by addDataAdvanced(), broadcastPacketTcpWithExclusion(), broadcastPacketUdpWithExclusion(), close(), dataHasFlagByCommand(), findCommandFromName(), finishAcceptingSocket(), internalSetDefaultFrequency(), logCommandGroupsToFile(), and processPacket().
ArMutex ArServerBase::myDataMutex protected
Referenced by addClientRemovedCallback(), addDataAdvanced(), ArServerBase(), broadcastPacketTcpWithExclusion(), broadcastPacketUdpWithExclusion(), close(), dataHasFlagByCommand(), enforceProtocolVersion(), enforceType(), findCommandFromName(), internalLockup(), internalSetDefaultFrequency(), loadUserInfo(), logCommandGroupsToFile(), logGroupDescriptionsToFile(), logUserInfo(), loopOnce(), open(), rejectSinceUsingCentralServer(), remClientRemovedCallback(), resetTracking(), setAdditionalDataFlags(), setGroupDescription(), setServerKey(), and setUserInfo().
bool ArServerBase::myDebugLogging protected
Referenced by ArServerBase(), finishAcceptingSocket(), getDebugLogging(), and setDebugLogging().
std::map<unsigned int, int> ArServerBase::myDefaultFrequency protected
Referenced by getFrequency(), and internalSetDefaultFrequency().
ArFunctor2C<ArServerBase, ArServerClient *, ArNetPacket *> ArServerBase::myEndRequestTransactionCB protected
Referenced by ArServerBase().
std::string ArServerBase::myEnforceProtocolVersion protected
Referenced by enforceProtocolVersion(), and finishAcceptingSocket().
ArServerCommands::Type ArServerBase::myEnforceType protected
Referenced by ArServerBase(), enforceType(), and finishAcceptingSocket().
ArRetFunctor2C<long, ArServerBase, unsigned int, bool> ArServerBase::myGetFrequencyCB protected
Referenced by addDataAdvanced().
std::map<std::string, std::string> ArServerBase::myGroupDescription protected
our mapping of the group names
Referenced by logCommandGroupsToFile(), logGroupDescriptionsToFile(), and setGroupDescription().
bool ArServerBase::myHaveIdleCallbacks protected
Referenced by addIdleSingleShotCallback(), ArServerBase(), hasIdleCallbacks(), idleProcessingPending(), and slowIdleCallback().
bool ArServerBase::myHaveIdlePackets protected
Referenced by ArServerBase(), hasIdlePackets(), idleProcessingPending(), and loopOnce().
bool ArServerBase::myHaveSlowPackets protected
Referenced by ArServerBase(), hasSlowPackets(), and loopOnce().
ArFunctor2C<ArServerBase, ArServerClient *, ArNetPacket *> ArServerBase::myIdentGetConnectionIDCB protected
Referenced by ArServerBase().
ArFunctor2C<ArServerBase, ArServerClient *, ArNetPacket *> ArServerBase::myIdentSetConnectionIDCB protected
Referenced by ArServerBase().
ArFunctor2C<ArServerBase, ArServerClient *, ArNetPacket *> ArServerBase::myIdentSetHereGoalCB protected
Referenced by ArServerBase().
ArFunctor2C<ArServerBase, ArServerClient *, ArNetPacket *> ArServerBase::myIdentSetSelfIdentifierCB protected
Referenced by ArServerBase().
std::list<ArFunctor *> ArServerBase::myIdleCallbacks protected
Referenced by addIdleSingleShotCallback(), and slowIdleCallback().
ArMutex ArServerBase::myIdleCallbacksMutex protected
Referenced by addIdleSingleShotCallback(), ArServerBase(), and slowIdleCallback().
ArFunctor2C<ArServerBase, ArServerClient *, ArNetPacket *> ArServerBase::myIdleProcessingPendingCB protected
Referenced by ArServerBase().
bool ArServerBase::myLastIdleProcessingPending protected
Referenced by loopOnce().
bool ArServerBase::myLogPasswordFailureVerbosely protected
Referenced by ArServerBase(), and finishAcceptingSocket().
std::string ArServerBase::myLogPrefix protected
Referenced by ArServerBase(), close(), closeConnectionID(), enforceProtocolVersion(), enforceType(), finishAcceptingSocket(), loadUserInfo(), logUserInfo(), and open().
int ArServerBase::myLoopMSecs protected
Referenced by ArServerBase(), runThread(), and slowIdleCallback().
int ArServerBase::myMaxClientsAllowed protected
Referenced by ArServerBase(), and finishAcceptingSocket().
int ArServerBase::myMostClients protected
Referenced by ArServerBase(), getMostClients(), logConnections(), and loopOnce().
bool ArServerBase::myNewBackupTimeout protected
Referenced by ArServerBase(), loopOnce(), and setBackupTimeout().
unsigned int ArServerBase::myNextDataNumber protected
Referenced by addDataAdvanced(), and ArServerBase().
int ArServerBase::myNumClients protected
Referenced by ArServerBase(), finishAcceptingSocket(), getNumClients(), internalSetNumClients(), and loopOnce().
bool ArServerBase::myOpened protected
Referenced by ArServerBase(), broadcastPacketTcpByCommandWithExclusion(), broadcastPacketUdpByCommandWithExclusion(), close(), loopOnce(), open(), and slowIdleCallback().
std::string ArServerBase::myOpenOnIP protected
Referenced by getOpenOnIP(), and open().
ArRetFunctorC<bool, ArServerBase> ArServerBase::myProcessFileCB protected
Referenced by ArServerBase().
ArMutex ArServerBase::myProcessingSlowIdleMutex protected
Referenced by ArServerBase(), loopOnce(), and slowIdleCallback().
ArFunctor2C<ArServerBase, ArNetPacket *, struct sockaddr_in *> ArServerBase::myProcessPacketCB protected
Referenced by ArServerBase().
int ArServerBase::myRejecting protected
Referenced by ArServerBase(), finishAcceptingSocket(), and rejectSinceUsingCentralServer().
std::string ArServerBase::myRejectingString protected
Referenced by finishAcceptingSocket(), and rejectSinceUsingCentralServer().
std::set<ArServerClient *> ArServerBase::myRemoveSet protected
Referenced by closeConnectionID(), loopOnce(), and slowIdleCallback().
ArMutex ArServerBase::myRemoveSetMutex protected
Referenced by ArServerBase(), closeConnectionID(), loopOnce(), and slowIdleCallback().
ArRetFunctor2C<bool, ArServerBase, ArNetPacket *, struct sockaddr_in *> ArServerBase::mySendUdpCB protected
Referenced by finishAcceptingSocket().
std::string ArServerBase::myServerKey protected
Referenced by finishAcceptingSocket(), and setServerKey().
std::string ArServerBase::myServerName protected
Referenced by ArServerBase(), finishAcceptingSocket(), internalLockup(), internalSetDefaultFrequency(), and logConnections().
SlowIdleThread* ArServerBase::mySlowIdleThread protected
Referenced by ArServerBase(), sleepAfterSend(), and ~ArServerBase().
ArFunctor2C<ArServerBase, ArServerClient *, ArNetPacket *> ArServerBase::myStartRequestTransactionCB protected
Referenced by ArServerBase().
bool ArServerBase::myTcpOnly protected
Referenced by close(), loopOnce(), and open().
unsigned int ArServerBase::myTcpPort protected
Referenced by ArServerBase(), getTcpPort(), and open().
ArSocket ArServerBase::myTcpSocket protected
Referenced by acceptTcpSockets(), close(), and open().
ArTimeChecker ArServerBase::myTimeChecker protected
Referenced by ArServerBase(), and loopOnce().
ArCallbackList1<const char *> ArServerBase::myTooManyClientsCBList protected
Referenced by addTooManyClientsCB(), finishAcceptingSocket(), and remTooManyClientsCB().
unsigned int ArServerBase::myUdpPort protected
Referenced by ArServerBase(), finishAcceptingSocket(), getUdpPort(), and open().
ArNetPacketReceiverUdp ArServerBase::myUdpReceiver protected
Referenced by ArServerBase(), loopOnce(), and open().
ArSocket ArServerBase::myUdpSocket protected
Referenced by close(), logTracking(), open(), resetTracking(), and sendUdp().
const ArServerUserInfo* ArServerBase::myUserInfo protected
Referenced by ArServerBase(), finishAcceptingSocket(), getUserInfo(), loadUserInfo(), logUserInfo(), and setUserInfo().
bool ArServerBase::myUsingOwnNumClients protected
Referenced by ArServerBase(), internalSetNumClients(), and loopOnce().
ArLog::LogLevel ArServerBase::myVerboseLogLevel protected
Referenced by addIdleSingleShotCallback(), ArServerBase(), broadcastPacketTcpWithExclusion(), broadcastPacketUdpWithExclusion(), findCommandFromName(), finishAcceptingSocket(), setDebugLogging(), and slowIdleCallback().
The documentation for this class was generated from the following files:
ArServerBase.h
ArServerBase.cpp