ArNetworking: ArServerInfoDrawings Class Reference
ArServerInfoDrawings Class Reference
Service to provide clients with information about graphical figures to be displayed with the map.
#include <ArServerInfoDrawings.h>
Public Member Functions
bool addDrawing (ArDrawingData *drawingData, const char *name, ArFunctor2< ArServerClient *, ArNetPacket * > *functor)
Adds a shape to the set of figures.
bool addRangeDevice (ArRangeDevice *rangeDevice)
Adds a specific range device to be drawn (using its default shape)
bool addRobotsRangeDevices (ArRobot *robot)
Adds all of the robot's range devices (using their default shape)
ArServerInfoDrawings (ArServerBase *server)
Constructor.
ArFunctor2< ArServerClient *, ArNetPacket * > * internalGetDrawingCallback (const char *name)
internal function that gets the functor for a drawing
ArDrawingData * internalGetDrawingData (const char *name)
internal function that gets the drawing data for a drawing
void netGetDrawingList (ArServerClient *client, ArNetPacket *packet)
void netListDrawings (ArServerClient *client, ArNetPacket *packet)
Client callback: Puts the list of shapes that can be drawn and their metadata into a reply packet (internal use mostly)
void netRangeDeviceCumulative (ArServerClient *client, ArNetPacket *packet, ArRangeDevice *device)
Client callback utilit: Puts the cumulative buffer of the given range device into a reply packet (internal use mostly)
void netRangeDeviceCurrent (ArServerClient *client, ArNetPacket *packet, ArRangeDevice *device)
Client callback utility: Puts the current data for the given range device into a reply packet (internal use mostly)
virtual ~ArServerInfoDrawings ()
Destructor.
Protected Attributes
std::map< std::string, ArFunctor2< ArServerClient *, ArNetPacket * > *, ArStrCaseCmpOp > myDrawingCallbacks
std::map< std::string, ArDrawingData *, ArStrCaseCmpOp > myDrawingDatas
ArFunctor2C< ArServerInfoDrawings, ArServerClient *, ArNetPacket * > myNetGetDrawingListCB
ArFunctor2C< ArServerInfoDrawings, ArServerClient *, ArNetPacket * > myNetListDrawingsCB
ArServerBase * myServer
Detailed Description
Service to provide clients with information about graphical figures to be displayed with the map.
Use addDrawing() to add a figure, or use addRangeDevice() or addRobotsRangeDevice() to automatically create standard drawings for range devices.
Clients may use the listDrawings data request to receive a list of figures and metadata about those figures. The reply packet to the listDrawings request is as follows:
Number of figures (4-byte integer)Then, for each figure, the following values are given
For each figure:
Figure name (null-terminated string)
Shape ID (null-terminated string)
Primary color:
Unused (byte)
Red (byte)
Green (byte)
Blue (byte)
Shape size (4-byte integer)
Layer number (4-byte integer)
Suggested refresh time (4-byte integer)
Secordary color:
Unused (byte)
Red (byte)
Green (byte)
Blue (byte)
This command is in the SensorInfo permission group for users.
Examples:
drawingsExample.cpp, drawingsExampleWithRobot.cpp, popupExample.cpp, and serverDemo.cpp.
Constructor & Destructor Documentation
ArServerInfoDrawings::ArServerInfoDrawings (ArServerBase * server)
Constructor.
References ArServerBase::addData(), myNetGetDrawingListCB, myNetListDrawingsCB, and myServer.
Referenced by addRangeDevice().
ArServerInfoDrawings::~ArServerInfoDrawings () virtual
Destructor.
Member Function Documentation
bool ArServerInfoDrawings::addDrawing (ArDrawingData * drawingData, const char * name, ArFunctor2< ArServerClient *, ArNetPacket * > * functor)
Adds a shape to the set of figures.
Note
'name' must be unique. If the name is unique, the given drawing data is stored to be returned in response to the "listDrawings" client request, and a new data request is created with the given name and functor. This functor must send a reply packet to the client containing a 4-byte integer indicating the number of coordinates or vertices in the figure, followed by a pair of 4-byte integers for each coordinate or vertex in global map space. For example, if drawingData describes a polyDots shape, then the functor must create a packet, add a 4-byte integer indicating the number of dots, then for each dot, add an integer for the X coordinate followed by an integer for the Y coordinate.
Examples:
drawingsExample.cpp.
References ArServerBase::addData(), ArLog::log(), myDrawingCallbacks, myDrawingDatas, myServer, and ArLog::Normal.
Referenced by addRangeDevice(), Circle::Circle(), and main().
bool ArServerInfoDrawings::addRangeDevice (ArRangeDevice * rangeDevice)
Adds a specific range device to be drawn (using its default shape)
References addDrawing(), ArServerInfoDrawings(), ArRangeDevice::getCumulativeDrawingData(), ArRangeDevice::getCurrentDrawingData(), ArRangeDevice::getName(), ArLog::log(), myServer, netRangeDeviceCumulative(), netRangeDeviceCurrent(), and ArLog::Normal.
Referenced by addRobotsRangeDevices().
bool ArServerInfoDrawings::addRobotsRangeDevices (ArRobot * robot)
Adds all of the robot's range devices (using their default shape)
Examples:
popupExample.cpp, and serverDemo.cpp.
References addRangeDevice(), ArRobot::getRangeDeviceList(), ArRangeDevice::lockDevice(), ArLog::log(), ArLog::Terse, and ArRangeDevice::unlockDevice().
Referenced by main().
ArFunctor2< ArServerClient *, ArNetPacket * > * ArServerInfoDrawings::internalGetDrawingCallback (const char * name)
internal function that gets the functor for a drawing
References ArLog::log(), myDrawingCallbacks, and ArLog::Normal.
ArDrawingData * ArServerInfoDrawings::internalGetDrawingData (const char * name)
internal function that gets the drawing data for a drawing
References ArLog::log(), myDrawingDatas, and ArLog::Normal.
void ArServerInfoDrawings::netGetDrawingList (ArServerClient * client, ArNetPacket * packet)
References ArBasePacket::byte4ToBuf(), ArNetPacket::empty(), myDrawingDatas, ArServerClient::sendPacketTcp(), ArBasePacket::strToBuf(), and ArBasePacket::uByte4ToBuf().
void ArServerInfoDrawings::netListDrawings (ArServerClient * client, ArNetPacket * packet)
Client callback: Puts the list of shapes that can be drawn and their metadata into a reply packet (internal use mostly)
References ArBasePacket::byte4ToBuf(), myDrawingDatas, ArServerClient::sendPacketTcp(), ArBasePacket::strToBuf(), and ArBasePacket::uByte4ToBuf().
void ArServerInfoDrawings::netRangeDeviceCumulative (ArServerClient * client, ArNetPacket * packet, ArRangeDevice * device)
Client callback utilit: Puts the cumulative buffer of the given range device into a reply packet (internal use mostly)
References ArBasePacket::byte4ToBuf(), ArRangeDevice::getCumulativeBuffer(), ArRangeDevice::getName(), ArRangeDevice::lockDevice(), ArLog::log(), ArMath::roundInt(), ArServerClient::sendPacketUdp(), ArRangeDevice::unlockDevice(), and ArLog::Verbose.
Referenced by addRangeDevice().
void ArServerInfoDrawings::netRangeDeviceCurrent (ArServerClient * client, ArNetPacket * packet, ArRangeDevice * device)
Client callback utility: Puts the current data for the given range device into a reply packet (internal use mostly)
References ArBasePacket::byte4ToBuf(), ArRangeDevice::getCurrentBuffer(), ArRangeDevice::getName(), ArRangeDevice::lockDevice(), ArLog::log(), ArMath::roundInt(), ArServerClient::sendPacketUdp(), ArRangeDevice::unlockDevice(), and ArLog::Verbose.
Referenced by addRangeDevice().
Member Data Documentation
std::map<std::string, ArFunctor2<ArServerClient *, ArNetPacket *> *, ArStrCaseCmpOp> ArServerInfoDrawings::myDrawingCallbacks protected
Referenced by addDrawing(), and internalGetDrawingCallback().
std::map<std::string, ArDrawingData *, ArStrCaseCmpOp> ArServerInfoDrawings::myDrawingDatas protected
Referenced by addDrawing(), internalGetDrawingData(), netGetDrawingList(), and netListDrawings().
ArFunctor2C<ArServerInfoDrawings, ArServerClient *, ArNetPacket *> ArServerInfoDrawings::myNetGetDrawingListCB protected
Referenced by ArServerInfoDrawings().
ArFunctor2C<ArServerInfoDrawings, ArServerClient *, ArNetPacket *> ArServerInfoDrawings::myNetListDrawingsCB protected
Referenced by ArServerInfoDrawings().
ArServerBase* ArServerInfoDrawings::myServer protected
Referenced by addDrawing(), addRangeDevice(), and ArServerInfoDrawings().
The documentation for this class was generated from the following files:
ArServerInfoDrawings.h
ArServerInfoDrawings.cpp