ArNetworking: ArClientFileFromClient Class Reference
ArClientFileFromClient Class Reference
Class for putting files to the server.
#include <ArClientFileUtils.h>
Public Types
enum SendSpeed { SPEED_AUTO, SPEED_FAST, SPEED_SLOW }
Enum that describes the speed to send at.
Public Member Functions
void addFileSentCallback (ArFunctor1< int > *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback for when we get the desired file (or fail)
ArClientFileFromClient (ArClientBase *client)
Constructor.
void cancelPut (void)
Cancels putting a file.
const char * getClientFileName (void)
Gets the filename we're taking from the client.
const char * getDirectory (void)
Gets the directory we're putting to.
const char * getFileName (void)
Gets the filename we're putting.
ArTime getLastCompletedSend (void)
Gets the last time we finished putting a file.
ArTime getLastStartedSend (void)
Gets the last time we started putting a file.
bool isAvailable (void)
Sees if the server supports what this class needs.
bool isAvailableFast (void)
Sees if the server supports what this class needs to send fast.
bool isAvailableSetTimestamp (void)
Sees if the server supports the ability to set the file timestamp.
bool isAvailableSlow (void)
Sees if the server supports what this class needs to send slowly.
bool isWaitingForReturn (void)
If we're waiting for completion now.
bool putFileToDirectory (const char *directory, const char *fileName, const char *clientFileName, SendSpeed sendSpeed=SPEED_AUTO, bool isSetTimestamp=false)
Puts the specified client file on the server in the given directory and file.
void remFileSentCallback (ArFunctor1< int > *functor)
Removes a callback for when we get the desired file (or fail)
virtual ~ArClientFileFromClient ()
Destructor.
Protected Member Functions
void callFileSentCallbacks (int val)
void netPutFile (ArNetPacket *packet)
Protected Attributes
ArMutex myCallbackMutex
ArClientBase * myClient
std::string myClientFileName
std::string myCommandName
ArMutex myDataMutex
std::string myDirectory
FILE * myFile
std::string myFileName
std::list< ArFunctor1< int > * > myFileSentCallbacks
bool myInterleaved
bool myIsWaitingForReturn
ArTime myLastCompletedSend
ArTime myLastStartedSend
ArFunctor1C< ArClientFileFromClient, ArNetPacket * > myPutFileCB
bool myReadyForNextPacket
bool myTimestamp
std::string myWholeFileName
Detailed Description
Class for putting files to the server.
This class will interact with the ArServerFileFromClient and put a file on to the server. If you want to find out what files are on the server use ArClientFileLister.
When get a file it doesn't happen right away, but when the file is received (or failes) the fileGotten callbacks will be called, 0 as the int for the callback means everything is good, positive error messages are from the server (0 = good (got file), 1 = getting file, 2 = tried to go outside allowed area, 3 = bad directory, 4 = empty file name (or other problem with fileName), 5 = can't write temp file, 6 = error moving file from temp to perm, 7 = another client putting file, 8 = timeout (no activity for 15 seconds) and another client wanted to put the file, 9 = client adding to, finishing, or canceling a file the server doesn't have), negative would be from this class but there aren't any of those yet
Member Enumeration Documentation
enum ArClientFileFromClient::SendSpeed
Enum that describes the speed to send at.
Enumerator
SPEED_AUTO
Send it fast if available, if not then send it slow.
SPEED_FAST
Send it fast.
SPEED_SLOW
Send it slow.
Constructor & Destructor Documentation
ArClientFileFromClient::ArClientFileFromClient (ArClientBase * client)
Constructor.
References ArClientBase::addHandler(), myCallbackMutex, myClient, myDataMutex, myPutFileCB, and ArMutex::setLogName().
ArClientFileFromClient::~ArClientFileFromClient () virtual
Destructor.
Member Function Documentation
void ArClientFileFromClient::addFileSentCallback (ArFunctor1< int > * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback for when we get the desired file (or fail)
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, myFileSentCallbacks, ArLog::Terse, and ArMutex::unlock().
void ArClientFileFromClient::callFileSentCallbacks (int val) protected
References ArMutex::lock(), myCallbackMutex, myFileSentCallbacks, and ArMutex::unlock().
Referenced by netPutFile().
void ArClientFileFromClient::cancelPut (void)
Cancels putting a file.
References ArMutex::lock(), myClient, myCommandName, myDataMutex, myIsWaitingForReturn, myWholeFileName, ArClientBase::requestOnce(), ArBasePacket::strToBuf(), ArBasePacket::uByte2ToBuf(), and ArMutex::unlock().
const char * ArClientFileFromClient::getClientFileName (void)
Gets the filename we're taking from the client.
References ArMutex::lock(), myClientFileName, myDataMutex, and ArMutex::unlock().
const char * ArClientFileFromClient::getDirectory (void)
Gets the directory we're putting to.
References ArMutex::lock(), myDataMutex, myDirectory, and ArMutex::unlock().
const char * ArClientFileFromClient::getFileName (void)
Gets the filename we're putting.
References ArMutex::lock(), myDataMutex, myFileName, and ArMutex::unlock().
ArTime ArClientFileFromClient::getLastCompletedSend (void)
Gets the last time we finished putting a file.
References ArMutex::lock(), myDataMutex, myLastCompletedSend, and ArMutex::unlock().
ArTime ArClientFileFromClient::getLastStartedSend (void)
Gets the last time we started putting a file.
References ArMutex::lock(), myDataMutex, myLastStartedSend, and ArMutex::unlock().
bool ArClientFileFromClient::isAvailable (void)
Sees if the server supports what this class needs.
References ArClientBase::dataExists(), and myClient.
bool ArClientFileFromClient::isAvailableFast (void)
Sees if the server supports what this class needs to send fast.
References ArClientBase::dataExists(), myClient, and putFileToDirectory().
bool ArClientFileFromClient::isAvailableSetTimestamp (void)
Sees if the server supports the ability to set the file timestamp.
References ArClientBase::dataExists(), and myClient.
bool ArClientFileFromClient::isAvailableSlow (void)
Sees if the server supports what this class needs to send slowly.
References ArClientBase::dataExists(), and myClient.
bool ArClientFileFromClient::isWaitingForReturn (void)
If we're waiting for completion now.
References ArMutex::lock(), myDataMutex, myIsWaitingForReturn, and ArMutex::unlock().
void ArClientFileFromClient::netPutFile (ArNetPacket * packet) protected
References ArBasePacket::bufToStr(), ArBasePacket::bufToUByte2(), callFileSentCallbacks(), done, ArMutex::lock(), myDataMutex, myInterleaved, myIsWaitingForReturn, myReadyForNextPacket, and ArMutex::unlock().
bool ArClientFileFromClient::putFileToDirectory (const char * directory, const char * fileName, const char * clientFileName, SendSpeed sendSpeed = SPEED_AUTO, bool isSetTimestamp = false)
Puts the specified client file on the server in the given directory and file.
References ArUtil::appendSlash(), ArBasePacket::byte4ToBuf(), ArClientBase::dataExists(), ArBasePacket::dataToBuf(), ArNetPacket::empty(), file, ArUtil::fixSlashes(), ArUtil::fopen(), ArUtil::isStrEmpty(), ArMutex::lock(), ArLog::log(), myClient, myClientFileName, myCommandName, myDataMutex, myDirectory, myFileName, myInterleaved, myIsWaitingForReturn, myLastStartedSend, myReadyForNextPacket, myTimestamp, myWholeFileName, ArLog::Normal, ArClientBase::requestOnce(), ArTime::secSince(), ArTime::setToNow(), ArUtil::sleep(), SPEED_AUTO, SPEED_FAST, SPEED_SLOW, ArBasePacket::strToBuf(), ArLog::Terse, ArBasePacket::uByte2ToBuf(), ArBasePacket::uByte4ToBuf(), and ArMutex::unlock().
Referenced by isAvailableFast().
void ArClientFileFromClient::remFileSentCallback (ArFunctor1< int > * functor)
Removes a callback for when we get the desired file (or fail)
References ArMutex::lock(), myCallbackMutex, myFileSentCallbacks, and ArMutex::unlock().
Member Data Documentation
ArMutex ArClientFileFromClient::myCallbackMutex protected
Referenced by addFileSentCallback(), ArClientFileFromClient(), callFileSentCallbacks(), and remFileSentCallback().
ArClientBase* ArClientFileFromClient::myClient protected
Referenced by ArClientFileFromClient(), cancelPut(), isAvailable(), isAvailableFast(), isAvailableSetTimestamp(), isAvailableSlow(), and putFileToDirectory().
std::string ArClientFileFromClient::myClientFileName protected
Referenced by getClientFileName(), and putFileToDirectory().
std::string ArClientFileFromClient::myCommandName protected
Referenced by cancelPut(), and putFileToDirectory().
ArMutex ArClientFileFromClient::myDataMutex protected
Referenced by ArClientFileFromClient(), cancelPut(), getClientFileName(), getDirectory(), getFileName(), getLastCompletedSend(), getLastStartedSend(), isWaitingForReturn(), netPutFile(), and putFileToDirectory().
std::string ArClientFileFromClient::myDirectory protected
Referenced by getDirectory(), and putFileToDirectory().
FILE* ArClientFileFromClient::myFile protected
std::string ArClientFileFromClient::myFileName protected
Referenced by getFileName(), and putFileToDirectory().
std::list<ArFunctor1<int> *> ArClientFileFromClient::myFileSentCallbacks protected
Referenced by addFileSentCallback(), callFileSentCallbacks(), and remFileSentCallback().
bool ArClientFileFromClient::myInterleaved protected
Referenced by netPutFile(), and putFileToDirectory().
bool ArClientFileFromClient::myIsWaitingForReturn protected
Referenced by cancelPut(), isWaitingForReturn(), netPutFile(), and putFileToDirectory().
ArTime ArClientFileFromClient::myLastCompletedSend protected
Referenced by getLastCompletedSend().
ArTime ArClientFileFromClient::myLastStartedSend protected
Referenced by getLastStartedSend(), and putFileToDirectory().
ArFunctor1C<ArClientFileFromClient, ArNetPacket *> ArClientFileFromClient::myPutFileCB protected
Referenced by ArClientFileFromClient().
bool ArClientFileFromClient::myReadyForNextPacket protected
Referenced by netPutFile(), and putFileToDirectory().
bool ArClientFileFromClient::myTimestamp protected
Referenced by putFileToDirectory().
std::string ArClientFileFromClient::myWholeFileName protected
Referenced by cancelPut(), and putFileToDirectory().
The documentation for this class was generated from the following files:
ArClientFileUtils.h
ArClientFileUtils.cpp