ArNetworking: ArClientFileLister Class Reference
ArClientFileLister Class Reference
Class for getting file list information from the server.
#include <ArClientFileUtils.h>
Public Member Functions
void addUpdatedCallback (ArFunctor1< int > *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback for when we get the desired directory info.
ArClientFileLister (ArClientBase *client)
Constructor.
void changeToAbsDir (const char *dir)
Goes to this absolute directory.
void changeToDir (const char *dir)
Goes to this directory in the current directory.
void changeToTopDir (void)
Goes to the top directory.
const char * getCurrentDir (void) const
Gets the name of the directory we're in.
std::list< ArClientFileListerItem > getDirectories (void) const
Gets the directories in the current directory.
std::list< ArClientFileListerItem > getFiles (void) const
Gets the files in the current directory.
ArTime getLastRequested (void)
Gets the last time we requested an update.
ArTime getLastUpdated (void)
Gets the last time we were updated.
const char * getWaitingForDir (void) const
Gets the name of the directory that we're currently waiting for.
bool isAvailable (void)
Sees if the server supports what this class needs.
void log (bool withTimes)
Logs the current directory.
void remUpdatedCallback (ArFunctor1< int > *functor)
Removes a callback for when we get the desired directory info.
void upOneDir (void)
Goes up one directory from current directory.
virtual ~ArClientFileLister ()
Destructor.
Protected Member Functions
void callUpdatedCallbacks (int val)
void getDirListing (const char *dir)
void logList (std::list< ArClientFileListerItem > *logThis, bool withTimes)
void netGetDirListing (ArNetPacket *packet)
void netGetDirListingMultiplePackets (ArNetPacket *packet)
Protected Attributes
ArMutex myCallbackMutex
ArClientBase * myClient
char myCurrentDir [2048]
ArMutex myDataMutex
std::list< ArClientFileListerItem > myDirectories
std::list< ArClientFileListerItem > myFiles
ArFunctor1C
< ArClientFileLister,
ArNetPacket * > myGetDirListingCB
ArFunctor1C
< ArClientFileLister,
ArNetPacket * > myGetDirListingMultiplePacketsCB
bool myLastDirMatched
ArTime myLastRequested
ArTime myLastUpdated
bool myNewDirListing
std::list< ArFunctor1< int > * > myUpdatedCallbacks
char myWaitingForDir [2048]
Detailed Description
Class for getting file list information from the server.
This class will interact with the ArServerFileLister and find out whats in directories and change directories and such. This class is all that should be used to get the information from ArServerFileLister, the API between the two is fairly volatile and will remain so. If you need more functionality let us know and we'll add it if its reasonable.
When you change directories or change to the top dir it doesn't happen right away, but when it happens the update callbacks will be called, 0 as the int for the callback means everything is good, positive error messages are from the server (1 == tried to go outside allowed area, 2 == no such directory), negative are from this class (-1 == got directory but it wasn't what we wanted (if you wait the right one might come in, like if someone selects one dir then the other)).
Constructor & Destructor Documentation
ArClientFileLister::ArClientFileLister (ArClientBase * client)
Constructor.
References ArClientBase::addHandler(), client, ArClientBase::dataExists(), log(), myCallbackMutex, myClient, myCurrentDir, myDataMutex, myGetDirListingCB, myGetDirListingMultiplePacketsCB, myLastDirMatched, myNewDirListing, myWaitingForDir, ArMutex::setLogName(), and ArLog::Verbose.
ArClientFileLister::~ArClientFileLister () [virtual]
Destructor.
Member Function Documentation
void ArClientFileLister::addUpdatedCallback (ArFunctor1< int > * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback for when we get the desired directory info.
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), log(), myCallbackMutex, myUpdatedCallbacks, ArLog::Terse, and ArMutex::unlock().
void ArClientFileLister::callUpdatedCallbacks (int val) [protected]
References ArMutex::lock(), myCallbackMutex, myUpdatedCallbacks, and ArMutex::unlock().
Referenced by netGetDirListing(), and netGetDirListingMultiplePackets().
void ArClientFileLister::changeToAbsDir (const char * dir)
Goes to this absolute directory.
References getDirListing(), ArMutex::lock(), myDataMutex, myLastRequested, myWaitingForDir, ArTime::setToNow(), and ArMutex::unlock().
void ArClientFileLister::changeToDir (const char * dir)
Goes to this directory in the current directory.
References ArUtil::appendSlash(), getDirListing(), ArMutex::lock(), myCurrentDir, myDataMutex, myLastRequested, myWaitingForDir, ArTime::setToNow(), and ArMutex::unlock().
void ArClientFileLister::changeToTopDir (void)
Goes to the top directory.
References getDirListing(), ArMutex::lock(), myCurrentDir, myDataMutex, myWaitingForDir, and ArMutex::unlock().
Referenced by upOneDir().
const char * ArClientFileLister::getCurrentDir (void) const
Gets the name of the directory we're in.
References myCurrentDir.
Referenced by log().
std::list< ArClientFileListerItem > ArClientFileLister::getDirectories (void) const
Gets the directories in the current directory.
References myDirectories.
void ArClientFileLister::getDirListing (const char * dir) [protected]
References ArClientBase::dataExists(), myClient, myLastDirMatched, myNewDirListing, and ArClientBase::requestOnceWithString().
Referenced by changeToAbsDir(), changeToDir(), changeToTopDir(), and upOneDir().
std::list< ArClientFileListerItem > ArClientFileLister::getFiles (void) const
Gets the files in the current directory.
References myFiles.
ArTime ArClientFileLister::getLastRequested (void)
Gets the last time we requested an update.
References ArMutex::lock(), myDataMutex, myLastRequested, and ArMutex::unlock().
ArTime ArClientFileLister::getLastUpdated (void)
Gets the last time we were updated.
References ArMutex::lock(), myDataMutex, myLastUpdated, and ArMutex::unlock().
const char * ArClientFileLister::getWaitingForDir (void) const
Gets the name of the directory that we're currently waiting for.
References myWaitingForDir.
bool ArClientFileLister::isAvailable (void)
Sees if the server supports what this class needs.
References ArClientBase::dataExists(), and myClient.
void ArClientFileLister::log (bool withTimes)
Logs the current directory.
References getCurrentDir(), ArMutex::lock(), logList(), myDataMutex, myDirectories, myFiles, ArLog::Normal, and ArMutex::unlock().
Referenced by addUpdatedCallback(), ArClientFileLister(), logList(), netGetDirListing(), and netGetDirListingMultiplePackets().
void ArClientFileLister::logList (std::list< ArClientFileListerItem > * logThis, bool withTimes) [protected]
References log(), and ArLog::Normal.
Referenced by log().
void ArClientFileLister::netGetDirListing (ArNetPacket * packet) [protected]
References ArBasePacket::bufToStr(), ArBasePacket::bufToUByte2(), ArBasePacket::bufToUByte4(), callUpdatedCallbacks(), ArMutex::lock(), log(), myCurrentDir, myDataMutex, myDirectories, myFiles, myWaitingForDir, ArLog::Normal, ArMutex::unlock(), and ArLog::Verbose.
void ArClientFileLister::netGetDirListingMultiplePackets (ArNetPacket * packet) [protected]
References ArBasePacket::bufToByte(), ArBasePacket::bufToStr(), ArBasePacket::bufToUByte2(), ArBasePacket::bufToUByte4(), callUpdatedCallbacks(), ArBasePacket::getDataLength(), ArMutex::lock(), log(), myCurrentDir, myDataMutex, myDirectories, myFiles, myLastDirMatched, myNewDirListing, myWaitingForDir, ArLog::Normal, ArMutex::unlock(), and ArLog::Verbose.
void ArClientFileLister::remUpdatedCallback (ArFunctor1< int > * functor)
Removes a callback for when we get the desired directory info.
References ArMutex::lock(), myCallbackMutex, myUpdatedCallbacks, and ArMutex::unlock().
void ArClientFileLister::upOneDir (void)
Goes up one directory from current directory.
References ArUtil::appendSlash(), changeToTopDir(), getDirListing(), ArMutex::lock(), myCurrentDir, myDataMutex, myLastRequested, myWaitingForDir, ArTime::setToNow(), and ArMutex::unlock().
Member Data Documentation
ArMutex ArClientFileLister::myCallbackMutex [protected]
Referenced by addUpdatedCallback(), ArClientFileLister(), callUpdatedCallbacks(), and remUpdatedCallback().
ArClientBase* ArClientFileLister::myClient [protected]
Referenced by ArClientFileLister(), getDirListing(), and isAvailable().
char ArClientFileLister::myCurrentDir[2048] [protected]
Referenced by ArClientFileLister(), changeToDir(), changeToTopDir(), getCurrentDir(), netGetDirListing(), netGetDirListingMultiplePackets(), and upOneDir().
ArMutex ArClientFileLister::myDataMutex [protected]
Referenced by ArClientFileLister(), changeToAbsDir(), changeToDir(), changeToTopDir(), getLastRequested(), getLastUpdated(), log(), netGetDirListing(), netGetDirListingMultiplePackets(), and upOneDir().
std::list<ArClientFileListerItem> ArClientFileLister::myDirectories [protected]
Referenced by getDirectories(), log(), netGetDirListing(), and netGetDirListingMultiplePackets().
std::list<ArClientFileListerItem> ArClientFileLister::myFiles [protected]
Referenced by getFiles(), log(), netGetDirListing(), and netGetDirListingMultiplePackets().
ArFunctor1C<ArClientFileLister, ArNetPacket *> ArClientFileLister::myGetDirListingCB [protected]
Referenced by ArClientFileLister().
ArFunctor1C<ArClientFileLister, ArNetPacket *> ArClientFileLister::myGetDirListingMultiplePacketsCB [protected]
Referenced by ArClientFileLister().
bool ArClientFileLister::myLastDirMatched [protected]
Referenced by ArClientFileLister(), getDirListing(), and netGetDirListingMultiplePackets().
ArTime ArClientFileLister::myLastRequested [protected]
Referenced by changeToAbsDir(), changeToDir(), getLastRequested(), and upOneDir().
ArTime ArClientFileLister::myLastUpdated [protected]
Referenced by getLastUpdated().
bool ArClientFileLister::myNewDirListing [protected]
Referenced by ArClientFileLister(), getDirListing(), and netGetDirListingMultiplePackets().
std::list<ArFunctor1<int> *> ArClientFileLister::myUpdatedCallbacks [protected]
Referenced by addUpdatedCallback(), callUpdatedCallbacks(), and remUpdatedCallback().
char ArClientFileLister::myWaitingForDir[2048] [protected]
Referenced by ArClientFileLister(), changeToAbsDir(), changeToDir(), changeToTopDir(), getWaitingForDir(), netGetDirListing(), netGetDirListingMultiplePackets(), and upOneDir().
The documentation for this class was generated from the following files:
ArClientFileUtils.h
ArClientFileUtils.cpp