ArNetworking: ArClientHandlerRobotUpdate Class Reference
ArClientHandlerRobotUpdate Class Reference
Receives robot "update" responses from server and stores them.
#include <ArClientHandlerRobotUpdate.h>
Classes
struct RobotData
Public Member Functions
void addModeChangedCB (ArFunctor1< const char * > *cb)
Add a callback function which is invoked if a new, different status string is received from the server.
void addStatusChangedCB (ArFunctor2< const char *, const char * > *cb)
Add a callback function which is invoked if a new, different status string is received from the server.
void addUpdateCB (ArFunctor1< RobotData > *cb)
Add a callback function which is called with robot data received in every update from the server.
ArClientHandlerRobotUpdate (ArClientBase *client)
const char * getMode ()
Get pointer to mode string most recently received from server.
const char * getStatus ()
Get pointer to status string most recently received from server.
void lock ()
Lock mutex used to protect robot data, status and mode while new data is stored from an update from the server, in the ArNetwork client thread.
void remModeChangedCB (ArFunctor1< const char * > *cb)
Remove status-changed callback function.
void remStatusChangedCB (ArFunctor2< const char *, const char * > *cb)
Remove status-changed callback function.
void remUpdateCB (ArFunctor1< RobotData > *cb)
Remove data update callback function.
void requestUpdates (int freq=100)
Request updates at the given rate.
void stopUpdates ()
Stop receiving updates.
void unlock ()
Unlock mutex used to protect robot data, status and mode, which was locked with lock().
bool waitForMode (const char *mode, long timeout)
bool waitForStatus (const char *status, long timeout)
~ArClientHandlerRobotUpdate ()
RobotData getData ()
Get a copy of robot position, status, etc.
double getX ()
double getY ()
double getTh ()
ArPose getPose ()
double getVel ()
double getRotVel ()
double getLatVel ()
bool haveStateOfCharge ()
Whether battery status was provided as state of charge or not.
double getStateOfCharge ()
bool haveVoltage ()
Whether battery status was provided as voltage or not.
double getVoltage ()
double getTemperature ()
Protected Member Functions
void handleUpdateNumbers (ArNetPacket *pkt)
void handleUpdateOld (ArNetPacket *pkt)
void handleUpdateStrings (ArNetPacket *pkt)
void parseData (ArNetPacket *pkt)
Protected Attributes
ArClientBase * myClient
RobotData myData
ArFunctor1C< ArClientHandlerRobotUpdate, ArNetPacket * > myHandleUpdateNumbersCB
ArFunctor1C< ArClientHandlerRobotUpdate, ArNetPacket * > myHandleUpdateOldCB
ArFunctor1C< ArClientHandlerRobotUpdate, ArNetPacket * > myHandleUpdateStringsCB
std::string myMode
ArCallbackList1< const char * > myModeChangedCBList
ArMutex myMutex
int myRequestFreq
std::string myStatus
ArCallbackList2< const char *, const char * > myStatusChangedCBList
ArCallbackList1< RobotData > myUpdateCBList
Detailed Description
Receives robot "update" responses from server and stores them.
After creating this object, call requestUpdates() to begin receiving updates from the server. You can use the accessors for robot data to get copies of the most recently received data. Use lock() and unlock() before and after using these accessors. You can also register a callback function which is called as soon as robot data is received, or whenever the server's mode or status strings change. These callbacks will be called from the ArNetworking client thread (managed by ArClientBase), so these callbacks must not lock any mutex used by that thread, and they must return quickly to avoid stalling/blocking the ArNetworking client thread. To avoid blocking the ArNetworking thread, monitor the state of ArClientHandlerRobotUpdate from your programs main thread or from another monitor thread, or if using ARNL, use RemoteArnlTask.
If the server supports separate "updateNumbers" and "updateStrings" requests, then ArClientHandlerRobotUpdate uses these requests when requestUpdates() is called. Otherwise, it uses the older combined "update" request. (In either case, status and mode callbacks are only called if status/mode strings also change value.)
Examples:
robotUpdateExample.cpp.
Constructor & Destructor Documentation
ArClientHandlerRobotUpdate::ArClientHandlerRobotUpdate (ArClientBase * client)
client Pointer to an ArClientBase object, which will be used to request and receive 'updateStrings' and 'updateNumbers'; if these requests are unavailable, then the older 'update' request is used instead.
References myHandleUpdateNumbersCB, myHandleUpdateOldCB, myHandleUpdateStringsCB, myModeChangedCBList, myStatusChangedCBList, myUpdateCBList, ArGenericCallbackList< ArFunctor2< P1, P2 > * >::setName(), ArGenericCallbackList< GenericFunctor >::setName(), and ArFunctor::setName().
Referenced by ArClientHandlerRobotUpdate::RobotData::RobotData().
ArClientHandlerRobotUpdate::~ArClientHandlerRobotUpdate ()
References myClient, and stopUpdates().
Referenced by ArClientHandlerRobotUpdate::RobotData::RobotData().
Member Function Documentation
void ArClientHandlerRobotUpdate::addModeChangedCB (ArFunctor1< const char * > * cb) inline
Add a callback function which is invoked if a new, different status string is received from the server.
References ArGenericCallbackList< GenericFunctor >::addCallback(), and myModeChangedCBList.
void ArClientHandlerRobotUpdate::addStatusChangedCB (ArFunctor2< const char *, const char * > * cb) inline
Add a callback function which is invoked if a new, different status string is received from the server.
The callback is passed the mode and the status.
References ArGenericCallbackList< ArFunctor2< P1, P2 > * >::addCallback(), and myStatusChangedCBList.
void ArClientHandlerRobotUpdate::addUpdateCB (ArFunctor1< RobotData > * cb) inline
Add a callback function which is called with robot data received in every update from the server.
See also
RobotData
References myUpdateCBList.
RobotData ArClientHandlerRobotUpdate::getData () inline
Get a copy of robot position, status, etc.
which was most recently received from the server.
References myData.
double ArClientHandlerRobotUpdate::getLatVel () inline
Examples:
robotUpdateExample.cpp.
References ArClientHandlerRobotUpdate::RobotData::latVel, and myData.
Referenced by main().
const char* ArClientHandlerRobotUpdate::getMode () inline
Get pointer to mode string most recently received from server.
Use lock() and unlock() to protect from changes by other threads; you must copy this string if you wish to store it.
Examples:
robotUpdateExample.cpp.
References handleUpdateNumbers(), handleUpdateOld(), handleUpdateStrings(), myMode, parseData(), waitForMode(), and waitForStatus().
Referenced by main().
ArPose ArClientHandlerRobotUpdate::getPose () inline
References myData, and ArClientHandlerRobotUpdate::RobotData::pose.
double ArClientHandlerRobotUpdate::getRotVel () inline
Examples:
robotUpdateExample.cpp.
References myData, and ArClientHandlerRobotUpdate::RobotData::rotVel.
Referenced by main().
double ArClientHandlerRobotUpdate::getStateOfCharge () inline
References myData, and ArClientHandlerRobotUpdate::RobotData::stateOfCharge.
const char* ArClientHandlerRobotUpdate::getStatus () inline
Get pointer to status string most recently received from server.
Use lock() and unlock() to protect from changes by other threads; you must copy this string if you wish to store it.
Examples:
robotUpdateExample.cpp.
References myStatus.
Referenced by main().
double ArClientHandlerRobotUpdate::getTemperature () inline
References myData, and ArClientHandlerRobotUpdate::RobotData::temperature.
double ArClientHandlerRobotUpdate::getTh () inline
Examples:
robotUpdateExample.cpp.
References ArPose::getTh(), myData, and ArClientHandlerRobotUpdate::RobotData::pose.
Referenced by main().
double ArClientHandlerRobotUpdate::getVel () inline
Examples:
robotUpdateExample.cpp.
References myData, and ArClientHandlerRobotUpdate::RobotData::vel.
Referenced by main().
double ArClientHandlerRobotUpdate::getVoltage () inline
Examples:
robotUpdateExample.cpp.
References myData, and ArClientHandlerRobotUpdate::RobotData::voltage.
Referenced by main().
double ArClientHandlerRobotUpdate::getX () inline
Examples:
robotUpdateExample.cpp.
References ArPose::getX(), myData, and ArClientHandlerRobotUpdate::RobotData::pose.
Referenced by main().
double ArClientHandlerRobotUpdate::getY () inline
Examples:
robotUpdateExample.cpp.
References ArPose::getY(), myData, and ArClientHandlerRobotUpdate::RobotData::pose.
Referenced by main().
void ArClientHandlerRobotUpdate::handleUpdateNumbers (ArNetPacket * pkt) protected
References data, lock(), myData, myUpdateCBList, parseData(), and unlock().
Referenced by getMode().
void ArClientHandlerRobotUpdate::handleUpdateOld (ArNetPacket * pkt) protected
References ArBasePacket::bufToStr(), data, ArCallbackList1< P1 >::invoke(), lock(), myData, myMode, myModeChangedCBList, myStatus, myStatusChangedCBList, myUpdateCBList, parseData(), and unlock().
Referenced by getMode().
void ArClientHandlerRobotUpdate::handleUpdateStrings (ArNetPacket * pkt) protected
References ArBasePacket::bufToStr(), ArCallbackList1< P1 >::invoke(), lock(), myMode, myModeChangedCBList, myStatus, myStatusChangedCBList, and unlock().
Referenced by getMode().
bool ArClientHandlerRobotUpdate::haveStateOfCharge () inline
Whether battery status was provided as state of charge or not.
If true, getStateOfCharge() provides a valid state of charge percentage value. If false, getStateOfCharge() should not be used.
References ArClientHandlerRobotUpdate::RobotData::haveStateOfCharge, and myData.
bool ArClientHandlerRobotUpdate::haveVoltage () inline
Whether battery status was provided as voltage or not.
If true, getVoltage() provides a valid voltage value. If false, getVoltage() should not be used.
References ArClientHandlerRobotUpdate::RobotData::haveVoltage, and myData.
void ArClientHandlerRobotUpdate::lock (void) inline
Lock mutex used to protect robot data, status and mode while new data is stored from an update from the server, in the ArNetwork client thread.
Call lock() before accessing data using getData() or other accessor functions below, and call unlock() when done. Hold the lock for as short a time as possible to avoid stalling the ArNetworking thread. You can copy data returned by getData() to a new RobotData object, then unlock.
Examples:
robotUpdateExample.cpp.
References ArMutex::lock(), and myMutex.
Referenced by handleUpdateNumbers(), handleUpdateOld(), handleUpdateStrings(), main(), waitForMode(), and waitForStatus().
void ArClientHandlerRobotUpdate::parseData (ArNetPacket * pkt) protected
References ArBasePacket::bufToByte(), ArBasePacket::bufToByte2(), ArBasePacket::bufToByte4(), ArClientHandlerRobotUpdate::RobotData::haveTemperature, ArClientHandlerRobotUpdate::RobotData::haveVoltage, ArClientHandlerRobotUpdate::RobotData::latVel, myData, ArClientHandlerRobotUpdate::RobotData::pose, ArClientHandlerRobotUpdate::RobotData::rotVel, ArPose::setTh(), ArPose::setX(), ArPose::setY(), ArClientHandlerRobotUpdate::RobotData::temperature, ArClientHandlerRobotUpdate::RobotData::vel, and ArClientHandlerRobotUpdate::RobotData::voltage.
Referenced by getMode(), handleUpdateNumbers(), and handleUpdateOld().
void ArClientHandlerRobotUpdate::remModeChangedCB (ArFunctor1< const char * > * cb) inline
Remove status-changed callback function.
References myModeChangedCBList, and ArGenericCallbackList< GenericFunctor >::remCallback().
void ArClientHandlerRobotUpdate::remStatusChangedCB (ArFunctor2< const char *, const char * > * cb) inline
Remove status-changed callback function.
References myStatusChangedCBList, and ArGenericCallbackList< ArFunctor2< P1, P2 > * >::remCallback().
void ArClientHandlerRobotUpdate::remUpdateCB (ArFunctor1< RobotData > * cb) inline
Remove data update callback function.
References myUpdateCBList.
void ArClientHandlerRobotUpdate::requestUpdates (int freq = 100)
Request updates at the given rate.
freq Rate (miliseconds) at which to request the server send updates. If not given, default is 100ms.
Examples:
robotUpdateExample.cpp.
References ArClientBase::addHandler(), ArClientBase::dataExists(), ArLog::log(), myClient, myHandleUpdateNumbersCB, myHandleUpdateOldCB, myHandleUpdateStringsCB, myRequestFreq, ArClientBase::request(), and ArLog::Verbose.
Referenced by main(), and ArClientHandlerRobotUpdate::RobotData::RobotData().
void ArClientHandlerRobotUpdate::stopUpdates ()
Stop receiving updates.
References myClient, myHandleUpdateNumbersCB, myHandleUpdateOldCB, myHandleUpdateStringsCB, ArClientBase::remHandler(), and ArClientBase::requestStop().
Referenced by ArClientHandlerRobotUpdate::RobotData::RobotData(), and ~ArClientHandlerRobotUpdate().
void ArClientHandlerRobotUpdate::unlock (void) inline
Unlock mutex used to protect robot data, status and mode, which was locked with lock().
Examples:
robotUpdateExample.cpp.
References myMutex, and ArMutex::unlock().
Referenced by handleUpdateNumbers(), handleUpdateOld(), handleUpdateStrings(), main(), waitForMode(), and waitForStatus().
bool ArClientHandlerRobotUpdate::waitForMode (const char * mode, long timeout)
References ArThread::getRunningWithLock(), lock(), ArTime::mSecSince(), myClient, myMode, myRequestFreq, ArUtil::sleep(), ArUtil::strcmp(), and unlock().
Referenced by getMode().
bool ArClientHandlerRobotUpdate::waitForStatus (const char * status, long timeout)
References ArThread::getRunningWithLock(), lock(), ArTime::mSecSince(), myClient, myRequestFreq, myStatus, ArUtil::sleep(), ArUtil::strcmp(), and unlock().
Referenced by getMode().
Member Data Documentation
ArClientBase* ArClientHandlerRobotUpdate::myClient protected
Referenced by requestUpdates(), stopUpdates(), waitForMode(), waitForStatus(), and ~ArClientHandlerRobotUpdate().
RobotData ArClientHandlerRobotUpdate::myData protected
Referenced by getData(), getLatVel(), getPose(), getRotVel(), getStateOfCharge(), getTemperature(), getTh(), getVel(), getVoltage(), getX(), getY(), handleUpdateNumbers(), handleUpdateOld(), haveStateOfCharge(), haveVoltage(), and parseData().
ArFunctor1C<ArClientHandlerRobotUpdate, ArNetPacket*> ArClientHandlerRobotUpdate::myHandleUpdateNumbersCB protected
Referenced by ArClientHandlerRobotUpdate(), requestUpdates(), and stopUpdates().
ArFunctor1C<ArClientHandlerRobotUpdate, ArNetPacket*> ArClientHandlerRobotUpdate::myHandleUpdateOldCB protected
Referenced by ArClientHandlerRobotUpdate(), requestUpdates(), and stopUpdates().
ArFunctor1C<ArClientHandlerRobotUpdate, ArNetPacket*> ArClientHandlerRobotUpdate::myHandleUpdateStringsCB protected
Referenced by ArClientHandlerRobotUpdate(), requestUpdates(), and stopUpdates().
std::string ArClientHandlerRobotUpdate::myMode protected
Referenced by getMode(), handleUpdateOld(), handleUpdateStrings(), and waitForMode().
ArCallbackList1<const char*> ArClientHandlerRobotUpdate::myModeChangedCBList protected
Referenced by addModeChangedCB(), ArClientHandlerRobotUpdate(), handleUpdateOld(), handleUpdateStrings(), and remModeChangedCB().
ArMutex ArClientHandlerRobotUpdate::myMutex protected
Referenced by lock(), and unlock().
int ArClientHandlerRobotUpdate::myRequestFreq protected
Referenced by requestUpdates(), waitForMode(), and waitForStatus().
std::string ArClientHandlerRobotUpdate::myStatus protected
Referenced by getStatus(), handleUpdateOld(), handleUpdateStrings(), and waitForStatus().
ArCallbackList2<const char*, const char*> ArClientHandlerRobotUpdate::myStatusChangedCBList protected
Referenced by addStatusChangedCB(), ArClientHandlerRobotUpdate(), handleUpdateOld(), handleUpdateStrings(), and remStatusChangedCB().
ArCallbackList1<RobotData> ArClientHandlerRobotUpdate::myUpdateCBList protected
Referenced by addUpdateCB(), ArClientHandlerRobotUpdate(), handleUpdateNumbers(), handleUpdateOld(), and remUpdateCB().
The documentation for this class was generated from the following files:
ArClientHandlerRobotUpdate.h
ArClientHandlerRobotUpdate.cpp