ArNetworking: ArServerSimplePopup Class Reference
ArServerSimplePopup Class Reference
Class for sending popups out the server.
#include <ArServerSimpleCommands.h>
Public Member Functions
ArServerSimplePopup (ArServerHandlerCommands *commands, ArServerHandlerPopup *popupHandler)
Constructor.
void simplePopup (ArArgumentBuilder *arg)
Handles the command.
virtual ~ArServerSimplePopup ()
Destructor.
Protected Attributes
ArServerHandlerCommands * myCommands
ArServerHandlerPopup * myPopupHandler
ArFunctor1C
< ArServerSimplePopup,
ArArgumentBuilder * > mySimplePopupCB
Detailed Description
Class for sending popups out the server.
This class will let you make a popup in MobileEyes, mostly for testing
Constructor & Destructor Documentation
ArServerSimplePopup::ArServerSimplePopup (ArServerHandlerCommands * commands, ArServerHandlerPopup * popupHandler)
Constructor.
References ArServerHandlerCommands::addStringCommand(), myCommands, myPopupHandler, and mySimplePopupCB.
ArServerSimplePopup::~ArServerSimplePopup () [virtual]
Destructor.
Member Function Documentation
void ArServerSimplePopup::simplePopup (ArArgumentBuilder * arg)
Handles the command.
References ArArgumentBuilder::compressQuoted(), ArServerHandlerPopup::createPopup(), ArArgumentBuilder::getArg(), ArArgumentBuilder::getArgc(), ArArgumentBuilder::getArgInt(), ArServerHandlerPopup::INFORMATION, ArLog::log(), myPopupHandler, and ArLog::Terse.
Member Data Documentation
ArServerHandlerCommands* ArServerSimplePopup::myCommands [protected]
Referenced by ArServerSimplePopup().
ArServerHandlerPopup* ArServerSimplePopup::myPopupHandler [protected]
Referenced by ArServerSimplePopup(), and simplePopup().
ArFunctor1C<ArServerSimplePopup, ArArgumentBuilder *> ArServerSimplePopup::mySimplePopupCB [protected]
Referenced by ArServerSimplePopup().
The documentation for this class was generated from the following files:
ArServerSimpleCommands.h
ArServerSimpleCommands.cpp