ArNetworking: ArClientArg Class Reference
ArClientArg Class Reference
Small helper class for sending/receiving an ArConfigArg in an ArNetPacket.
#include <ArClientArgUtils.h>
Public Member Functions
virtual bool addAncestorListToPacket (const std::list< ArConfigArg * > &ancestorList, ArNetPacket *packet)
virtual bool addArgTextToPacket (const ArConfigArg &arg, ArNetPacket *packet)
virtual bool addListBeginToPacket (ArConfigArg *parentArg, ArNetPacket *packet)
virtual bool addListEndToPacket (ArConfigArg *parentArg, ArNetPacket *packet)
ArClientArg (bool isDisplayHintParsed=false, ArPriority::Priority lastPriority=ArPriority::LAST_PRIORITY, int version=1, bool isSingleParam=false)
Constructor.
virtual bool argTextToBuf (const ArConfigArg &arg, ArNetPacket *packet)
Stores the arg value into the network packet as a text string.
virtual bool argValueToBuf (const ArConfigArg &arg, ArNetPacket *packet)
Stores the abbreviated arg value into the network packet.
virtual bool bufToArgValue (ArNetPacket *packet, ArConfigArg &arg)
Unpacks the abbreviated arg value and stores the data in the config arg.
virtual bool createArg (ArNetPacket *packet, ArConfigArg &argOut, std::string *parentPathNameOut=NULL)
Unpacks the given network packet and stores the data in the config arg.
virtual bool createPacket (const ArConfigArg &arg, ArNetPacket *packet, const char *parentPathName=NULL)
Stores the given config arg into the network packet.
virtual ~ArClientArg ()
Destructor.
Static Public Member Functions
static bool isSendableParamType (const ArConfigArg &arg, bool isIncludeSeparator=true)
Returns whether the given parameter can be sent in a network packet.
Protected Types
enum { BUFFER_LENGTH = 1024 }
Protected Attributes
char myBuffer [BUFFER_LENGTH]
char myDisplayBuffer [BUFFER_LENGTH]
char myExtraBuffer [BUFFER_LENGTH]
bool myIsDisplayHintParsed
bool myIsSingleParam
ArPriority::Priority myLastPriority
char myParentPathNameBuffer [BUFFER_LENGTH]
int myVersion
Detailed Description
Small helper class for sending/receiving an ArConfigArg in an ArNetPacket.
ArClientArg defines methods for packing/unpacking an ArConfigArg into/from an ArNetPacket. (The name of the class is a slight misnomer since it may be used both on the server and client sides.)
The structure of the network packet information is as follows:
   string: arg.getName()
   string: arg.getDescription()
   byte: arg.getConfigPriority()
   byte: arg type ('B' == BOOL | 'I' == INT | 'D' == DOUBLE | 'S' == STRING | 'L' == LIST)
   <arg values>
   string: arg.getDisplayHint()      -- only if isDisplayHintParsed is set to true
   string: arg.getExtraExplanation() -- only if version >= 2
   byte: arg.getRestartLevel()       -- only if version >= 2
   ubyte: arg.getIsSerializable()    -- only if version >= 4
   string: "" | arg.getParentPathName()   -- only if version >= 4 , parent included only if isSingleParam set to true
   <arg values> varies by arg type:
   if BOOL, then:
       byte: arg.getBool()
   if INT, then:
           byte4: arg.getInt()
            byte4: arg.getMinInt()
            byte4: arg.getMaxInt()
   if DOUBLE, then:
           byte4: arg.getDouble()
            byte4: arg.getMinDouble()
            byte4: arg.getMaxDouble()
       byte4: arg.getDoublePrecision()  -- only if version >= 2
   if STRING, then:
       string: arg.getString()
   if LIST, then:
       byte4: arg.getArgCount()
       <list contents>
ArClientArg also defines methods to send an "abbreviated" ArConfigArg (i.e. just value). The short packet structure is as follows:
   <arg value> varies by arg type:
   if BOOL, then:
       byte: arg.getBool()
   if INT, then:
           byte4: arg.getInt()
   if DOUBLE, then:
           byte4: arg.getDouble()
   if STRING, then:
       string: arg.getString()
   if LIST, then:
       <TODO>
       <list contents>
Lastly, it defines a method to send an "abbreviated" ArConfigArg in a text format.
Examples:
ptzCameraClientExample.cpp.
Member Enumeration Documentation
anonymous enum protected
Enumerator
BUFFER_LENGTH
Constructor & Destructor Documentation
ArClientArg::ArClientArg (bool isDisplayHintParsed = false, ArPriority::Priority lastPriority = ArPriority::LAST_PRIORITY, int version = 1, bool isSingleParam = false)
Constructor.
ArClientArg::~ArClientArg () virtual
Destructor.
Member Function Documentation
bool ArClientArg::addAncestorListToPacket (const std::list< ArConfigArg * > & ancestorList, ArNetPacket * packet) virtual
References addArgTextToPacket(), ArConfigArg::getName(), ArConfigArg::isListType(), ArConfigArg::LIST_BEGIN_TAG, ArConfigArg::LIST_END_TAG, ArLog::log(), myIsSingleParam, ArLog::Normal, and ArBasePacket::strToBuf().
Referenced by addArgTextToPacket().
bool ArClientArg::addArgTextToPacket (const ArConfigArg & arg, ArNetPacket * packet) virtual
References addAncestorListToPacket(), addListBeginToPacket(), addListEndToPacket(), ArConfigArg::BOOL, BUFFER_LENGTH, ArUtil::convertBool(), ArConfigArg::DOUBLE, ArConfigArg::getArgs(), ArConfigArg::getBool(), ArConfigArg::getDouble(), ArConfigArg::getInt(), ArConfigArg::getName(), ArConfigArg::getParentArg(), ArConfigArg::getString(), ArConfigArg::getType(), ArConfigArg::INT, isSendableParamType(), ArConfigArg::LIST, ArConfigArg::LIST_BEGIN_TAG, ArConfigArg::LIST_END_TAG, myBuffer, myIsSingleParam, ArConfigArg::SEPARATOR, ArConfigArg::STRING, and ArBasePacket::strToBuf().
Referenced by addAncestorListToPacket(), and ArClientHandlerConfig::saveConfigToServer().
bool ArClientArg::addListBeginToPacket (ArConfigArg * parentArg, ArNetPacket * packet) virtual
References ArConfigArg::getName(), ArConfigArg::getParentArg(), ArConfigArg::isListType(), ArConfigArg::LIST_BEGIN_TAG, ArLog::log(), ArLog::Normal, and ArBasePacket::strToBuf().
Referenced by addArgTextToPacket().
bool ArClientArg::addListEndToPacket (ArConfigArg * parentArg, ArNetPacket * packet) virtual
References ArConfigArg::getName(), ArConfigArg::getParentArg(), ArConfigArg::isListType(), ArConfigArg::LIST_END_TAG, ArLog::log(), ArLog::Normal, and ArBasePacket::strToBuf().
Referenced by addArgTextToPacket().
bool ArClientArg::argTextToBuf (const ArConfigArg & arg, ArNetPacket * packet) virtual
Stores the arg value into the network packet as a text string.
The stored text string is suitable for parsing by an ArArgumentBuilder.
Parameters
arg the ArConfigArg from which to retrieve the data
packet the ArNetPacket * to which data is added
Returns
bool set to true if the data was successfully stored in the packet; false if an error occurred and the packet is invalid
References ArConfigArg::BOOL, BUFFER_LENGTH, ArUtil::convertBool(), ArConfigArg::DOUBLE, ArConfigArg::getBool(), ArConfigArg::getDouble(), ArConfigArg::getInt(), ArConfigArg::getString(), ArConfigArg::getType(), ArConfigArg::INT, ArConfigArg::LIST, myBuffer, ArConfigArg::SEPARATOR, ArConfigArg::STRING, and ArBasePacket::strToBuf().
Referenced by ArServerHandlerConfig::getConfigDefaults().
bool ArClientArg::argValueToBuf (const ArConfigArg & arg, ArNetPacket * packet) virtual
Stores the abbreviated arg value into the network packet.
Parameters
arg the ArConfigArg from which to retrieve the data
packet the ArNetPacket * to which data is added
Returns
bool set to true if the data was successfully stored in the packet; false if an error occurred and the packet is invalid
References ArConfigArg::BOOL, ArBasePacket::byte4ToBuf(), ArBasePacket::byteToBuf(), ArConfigArg::DOUBLE, ArNetPacket::doubleToBuf(), ArConfigArg::getArgs(), ArConfigArg::getBool(), ArConfigArg::getDouble(), ArConfigArg::getInt(), ArConfigArg::getString(), ArConfigArg::getType(), ArConfigArg::INT, isSendableParamType(), ArConfigArg::LIST, ArLog::log(), ArConfigArg::SEPARATOR, ArConfigArg::STRING, ArBasePacket::strToBuf(), and ArLog::Terse.
Referenced by ArServerHandlerCameraCollection::setParams().
bool ArClientArg::bufToArgValue (ArNetPacket * packet, ArConfigArg & arg) virtual
Unpacks the abbreviated arg value and stores the data in the config arg.
Parameters
packet the ArNetPacket * from which data is extracted
arg the ArConfigArg in which to set the value
Returns
bool set to true if the data was successfully extracted from the packet; false if an error occurred and arg is invalid
Examples:
ptzCameraClientExample.cpp.
References ArConfigArg::BOOL, BUFFER_LENGTH, ArBasePacket::bufToByte(), ArBasePacket::bufToByte4(), ArNetPacket::bufToDouble(), ArBasePacket::bufToStr(), ArConfigArg::DOUBLE, ArConfigArg::getArg(), ArConfigArg::getArgCount(), ArConfigArg::getType(), ArConfigArg::INT, isSendableParamType(), ArConfigArg::LIST, ArLog::log(), myBuffer, ArLog::Normal, ArConfigArg::SEPARATOR, ArConfigArg::setBool(), ArConfigArg::setDouble(), ArConfigArg::setInt(), ArConfigArg::setString(), ArConfigArg::STRING, and ArLog::Terse.
Referenced by PtzCameraExample::init(), and ArServerHandlerCameraCollection::setParams().
bool ArClientArg::createArg (ArNetPacket * packet, ArConfigArg & argOut, std::string * parentPathNameOut = NULL) virtual
Unpacks the given network packet and stores the data in the config arg.
Parameters
packet the ArNetPacket * from which data is extracted
argOut the ArConfigArg in which to set the data
Returns
bool set to true if the data was successfully extracted from the packet; false if an error occurred and argOut is invalid
References ArConfigArg::addArg(), BUFFER_LENGTH, ArBasePacket::bufToByte(), ArBasePacket::bufToByte4(), ArNetPacket::bufToDouble(), ArBasePacket::bufToStr(), ArBasePacket::bufToUByte(), ArConfigArg::getName(), IFDEBUG, ArConfigArg::LIST, ArLog::log(), myBuffer, myDisplayBuffer, myExtraBuffer, myIsDisplayHintParsed, myIsSingleParam, myLastPriority, myParentPathNameBuffer, myVersion, ArConfigArg::SEPARATOR, ArConfigArg::setConfigPriority(), ArConfigArg::setDisplayHint(), ArConfigArg::setExtraExplanation(), ArConfigArg::setRestartLevel(), ArConfigArg::setSerializable(), ArLog::Terse, and ArLog::Verbose.
Referenced by ArClientHandlerConfig::requestConfigFromServer().
bool ArClientArg::createPacket (const ArConfigArg & arg, ArNetPacket * packet, const char * parentPathName = NULL) virtual
Stores the given config arg into the network packet.
Parameters
arg the ArConfigArg from which to retrieve the data
packet the ArNetPacket * to which data is added
Returns
bool set to true if the data was successfully stored in the packet; false if an error occurred and the packet is invalid
References ArConfigArg::BOOL, ArBasePacket::byte4ToBuf(), ArBasePacket::byteToBuf(), ArConfigArg::DOUBLE, ArNetPacket::doubleToBuf(), ArConfigArg::getArgs(), ArConfigArg::getBool(), ArConfigArg::getConfigPriority(), ArConfigArg::getDescription(), ArConfigArg::getDisplayHint(), ArConfigArg::getDouble(), ArConfigArg::getDoublePrecision(), ArConfigArg::getExtraExplanation(), ArConfigArg::getInt(), ArConfigArg::getMaxDouble(), ArConfigArg::getMaxInt(), ArConfigArg::getMinDouble(), ArConfigArg::getMinInt(), ArConfigArg::getName(), ArConfigArg::getRestartLevel(), ArConfigArg::getString(), ArConfigArg::getType(), ArConfigArg::INT, isSendableParamType(), ArConfigArg::isSerializable(), ArConfigArg::LIST, ArLog::log(), myIsDisplayHintParsed, myIsSingleParam, myLastPriority, myVersion, ArConfigArg::SEPARATOR, ArConfigArg::STRING, ArBasePacket::strToBuf(), ArLog::Terse, ArConfigArg::toString(), ArBasePacket::uByteToBuf(), and ArLog::Verbose.
Referenced by ArServerHandlerCameraCollection::getCameraList(), and ArServerHandlerConfig::handleGetConfigSection().
bool ArClientArg::isSendableParamType (const ArConfigArg & arg, bool isIncludeSeparator = true) static
Returns whether the given parameter can be sent in a network packet.
Currently, a parameter can only be sent if it is of type INT, DOUBLE, STRING, BOOL, LIST, or a SEPARATOR.
Parameters
arg the ArConfigArg to be checked for "sendability"
isIncludeSeparator a bool set to true if separators should be sent; (this is currently set to false for the text socket commands)
References ArConfigArg::BOOL, ArConfigArg::DOUBLE, ArConfigArg::getType(), ArConfigArg::INT, ArConfigArg::LIST, ArConfigArg::SEPARATOR, and ArConfigArg::STRING.
Referenced by addArgTextToPacket(), argValueToBuf(), bufToArgValue(), createPacket(), ArServerHandlerConfig::getConfigDefaults(), ArServerHandlerConfig::handleGetConfigSection(), and ArClientHandlerConfig::saveConfigToServer().
Member Data Documentation
char ArClientArg::myBuffer[BUFFER_LENGTH] protected
Referenced by addArgTextToPacket(), argTextToBuf(), bufToArgValue(), and createArg().
char ArClientArg::myDisplayBuffer[BUFFER_LENGTH] protected
Referenced by createArg().
char ArClientArg::myExtraBuffer[BUFFER_LENGTH] protected
Referenced by createArg().
bool ArClientArg::myIsDisplayHintParsed protected
Referenced by createArg(), and createPacket().
bool ArClientArg::myIsSingleParam protected
Referenced by addAncestorListToPacket(), addArgTextToPacket(), createArg(), and createPacket().
ArPriority::Priority ArClientArg::myLastPriority protected
Referenced by createArg(), and createPacket().
char ArClientArg::myParentPathNameBuffer[BUFFER_LENGTH] protected
Referenced by createArg().
int ArClientArg::myVersion protected
Referenced by createArg(), and createPacket().
The documentation for this class was generated from the following files:
ArClientArgUtils.h
ArClientArgUtils.cpp