ArNetworking: ArServerSimpleComLogActions Class Reference
ArServerSimpleComLogActions Class Reference
Log current ArRobot actions.
#include <ArServerSimpleCommands.h>
Public Member Functions
ArServerSimpleComLogActions (ArServerHandlerCommands *commands, ArRobot *robot)
void logActions ()
Detailed Description
Log current ArRobot actions.
Constructor & Destructor Documentation
ArServerSimpleComLogActions::ArServerSimpleComLogActions (ArServerHandlerCommands * commands, ArRobot * robot)
References ArServerHandlerCommands::addCommand().
Member Function Documentation
void ArServerSimpleComLogActions::logActions (void)
References ArLog::log(), ArRobot::logActions(), and ArLog::Normal.
The documentation for this class was generated from the following files:
ArServerSimpleCommands.h
ArServerSimpleCommands.cpp