ArNetworking: ArClientHandlerCamera Class Reference
ArClientHandlerCamera Class Reference
Includes callbacks for receiving info and data packets from a camera server and storing the values parsed from them.
Public Member Functions
ArClientHandlerCamera (ArClientBase *client, const char *cameraName)
void handleCameraDataReply (ArNetPacket *packet)
void handleCameraInfoReply (ArNetPacket *packet)
void lock ()
void requestUpdates (int dataRequestFreq)
void unlock ()
Public Attributes
std::string displayName
std::string displayType
bool haveZoom
double maxPan
double maxTilt
double maxZoom
double minPan
double minTilt
double minZoom
ArFunctor1C
< ArClientHandlerCamera,
ArNetPacket * > myCameraDataReplyFunc
ArFunctor1C
< ArClientHandlerCamera,
ArNetPacket * > myCameraInfoReplyFunc
ArClientBase * myClient
ArMutex myMutex
std::string name
double pan
ArNetCameraRequest request
double tilt
std::string type
double zoom
Detailed Description
Includes callbacks for receiving info and data packets from a camera server and storing the values parsed from them.
Examples:
ptzCameraClientExample.cpp.
Constructor & Destructor Documentation
ArClientHandlerCamera::ArClientHandlerCamera (ArClientBase * client, const char * cameraName) [inline]
Examples:
ptzCameraClientExample.cpp.
References ArClientBase::addHandler(), myCameraDataReplyFunc, myCameraInfoReplyFunc, myClient, and name.
Member Function Documentation
void ArClientHandlerCamera::handleCameraDataReply (ArNetPacket * packet)
Examples:
ptzCameraClientExample.cpp.
References ArBasePacket::bufToByte2(), lock(), ArLog::log(), name, ArLog::Normal, pan, tilt, unlock(), and zoom.
void ArClientHandlerCamera::handleCameraInfoReply (ArNetPacket * packet)
Examples:
ptzCameraClientExample.cpp.
References ArBasePacket::bufToByte(), ArBasePacket::bufToByte2(), haveZoom, lock(), ArLog::log(), maxPan, maxTilt, maxZoom, minPan, minTilt, minZoom, ArLog::Normal, and unlock().
void ArClientHandlerCamera::lock (void) [inline]
Examples:
ptzCameraClientExample.cpp.
References ArMutex::lock(), and myMutex.
Referenced by handleCameraDataReply(), handleCameraInfoReply(), and PtzCameraExample::run().
void ArClientHandlerCamera::requestUpdates (int dataRequestFreq) [inline]
Examples:
ptzCameraClientExample.cpp.
References myClient, name, and ArClientBase::request().
Referenced by PtzCameraExample::init().
void ArClientHandlerCamera::unlock (void) [inline]
Examples:
ptzCameraClientExample.cpp.
References myMutex, and ArMutex::unlock().
Referenced by handleCameraDataReply(), handleCameraInfoReply(), and PtzCameraExample::run().
Member Data Documentation
std::string ArClientHandlerCamera::displayName
Examples:
ptzCameraClientExample.cpp.
std::string ArClientHandlerCamera::displayType
Examples:
ptzCameraClientExample.cpp.
bool ArClientHandlerCamera::haveZoom
Examples:
ptzCameraClientExample.cpp.
Referenced by handleCameraInfoReply().
double ArClientHandlerCamera::maxPan
Examples:
ptzCameraClientExample.cpp.
Referenced by handleCameraInfoReply(), and PtzCameraExample::run().
double ArClientHandlerCamera::maxTilt
Examples:
ptzCameraClientExample.cpp.
Referenced by handleCameraInfoReply(), and PtzCameraExample::run().
double ArClientHandlerCamera::maxZoom
Examples:
ptzCameraClientExample.cpp.
Referenced by handleCameraInfoReply().
double ArClientHandlerCamera::minPan
Examples:
ptzCameraClientExample.cpp.
Referenced by handleCameraInfoReply(), and PtzCameraExample::run().
double ArClientHandlerCamera::minTilt
Examples:
ptzCameraClientExample.cpp.
Referenced by handleCameraInfoReply(), and PtzCameraExample::run().
double ArClientHandlerCamera::minZoom
Examples:
ptzCameraClientExample.cpp.
Referenced by handleCameraInfoReply().
ArFunctor1C<ArClientHandlerCamera, ArNetPacket*> ArClientHandlerCamera::myCameraDataReplyFunc
Examples:
ptzCameraClientExample.cpp.
Referenced by ArClientHandlerCamera().
ArFunctor1C<ArClientHandlerCamera, ArNetPacket*> ArClientHandlerCamera::myCameraInfoReplyFunc
Examples:
ptzCameraClientExample.cpp.
Referenced by ArClientHandlerCamera().
ArClientBase* ArClientHandlerCamera::myClient
Examples:
ptzCameraClientExample.cpp.
Referenced by ArClientHandlerCamera(), and requestUpdates().
ArMutex ArClientHandlerCamera::myMutex
Examples:
ptzCameraClientExample.cpp.
Referenced by lock(), and unlock().
std::string ArClientHandlerCamera::name
Examples:
ptzCameraClientExample.cpp.
Referenced by ArClientHandlerCamera(), handleCameraDataReply(), and requestUpdates().
double ArClientHandlerCamera::pan
Examples:
ptzCameraClientExample.cpp.
Referenced by handleCameraDataReply().
ArNetCameraRequest ArClientHandlerCamera::request
Examples:
ptzCameraClientExample.cpp.
Referenced by PtzCameraExample::run().
double ArClientHandlerCamera::tilt
Examples:
ptzCameraClientExample.cpp.
Referenced by handleCameraDataReply().
std::string ArClientHandlerCamera::type
Examples:
ptzCameraClientExample.cpp.
double ArClientHandlerCamera::zoom
Examples:
ptzCameraClientExample.cpp.
Referenced by handleCameraDataReply().
The documentation for this class was generated from the following file:
ptzCameraClientExample.cpp