ArNetworking: ArServerHandlerCamera Class Reference
ArServerHandlerCamera Class Reference
Accepts and processes camera pan/tilt/zoom requests from the client, and provides information about the camera (such as its current position).
#include <ArServerHandlerCamera.h>
Public Member Functions
virtual void addToCameraCollection (ArCameraCollection &collection)
Adds the camera commands to the given collection.
ArServerHandlerCamera (const char *cameraName, ArServerBase *server, ArRobot *robot, ArPTZ *camera, ArCameraCollection *collection)
Constructs a new handler for the specified camera.
ArServerHandlerCamera (ArServerBase *server, ArRobot *robot, ArPTZ *camera)
Constructor.
void camera (ArServerClient *client, ArNetPacket *packet)
Handles the camera network packet, with information stored as byte integers.
void cameraAbs (ArServerClient *client, ArNetPacket *packet)
Handles the cameraAbs network packet, with information stored as byte integers.
void cameraInfo (ArServerClient *client, ArNetPacket *packet)
Handles the cameraInfo network packet, with information returned as byte2 integers.
void cameraModeLookAtGoal (void)
Puts the camera into a mode where it will look at the goal.
void cameraModeLookAtGoalClearGoal (void)
Clears the goal for the camera mode that points at the goal.
void cameraModeLookAtGoalSetGoal (ArPose pose)
Sets the goal for the camera mode that points at the goal.
void cameraModeLookAtPoint (ArPose pose, bool controlZoom=true)
Puts the camera into a mode where it will look at a point.
void cameraModePosition (void)
Puts the camera in position mode.
void cameraPct (ArServerClient *client, ArNetPacket *packet)
Handles the cameraPct network packet, with information stored as byte integers.
void cameraUpdate (ArServerClient *client, ArNetPacket *packet)
Handles the cameraUpdate network packet, with information returned as byte2 integers.
const char * getCameraName ()
Returns the name of the camera that is controlled by this handler.
void handleCameraModeUpdated (ArServerClient *client, ArNetPacket *packet)
Handle the mode request, generally this is sent when it changes.
void handleGetCameraData (ArServerClient *client, ArNetPacket *packet)
Handles the getCameraData network packet, returning information in double format.
void handleGetCameraInfo (ArServerClient *client, ArNetPacket *packet)
Handles the getCameraInfo network packet, returning information in double format.
void handleGetCameraModeList (ArServerClient *client, ArNetPacket *packet)
Handles the mode list for the camera.
void handleResetCamera (ArServerClient *client, ArNetPacket *packet)
Handle the reset.
void handleSetCameraAbs (ArServerClient *client, ArNetPacket *packet)
Handles the setCameraAbs network packet, with information in double format.
void handleSetCameraMode (ArServerClient *client, ArNetPacket *packet)
Handle the set mode request.
void handleSetCameraPct (ArServerClient *client, ArNetPacket *packet)
Handles the setCameraPct network packet, with information in double format.
void handleSetCameraRel (ArServerClient *client, ArNetPacket *packet)
Handles the setCameraRel network packet, with information in double format.
void resetCamera (bool lockRobot=true)
Resets the camera.
void setCameraAbs (double pan, double tilt, double zoom, bool lockRobot=true)
Sends the camera absolute commands to the camera (and puts it in position mode)
void setCameraPct (double panPct, double tiltPct, bool lockRobot=true)
Sends the camera percent commands to the camera (and puts it in position mode)
void setCameraRel (double pan, double tilt, double zoom, bool lockRobot=true)
Sends the camera relative commands to the camera (and puts it in position mode)
virtual ~ArServerHandlerCamera ()
Destructor.
Public Member Functions inherited from ArCameraCollectionItem
ArCameraCollectionItem ()
virtual ~ArCameraCollectionItem ()
Protected Types
enum { DOUBLE_FACTOR = 100 }
enum CameraMode { CAMERA_MODE_POSITION, CAMERA_MODE_LOOK_AT_GOAL, CAMERA_MODE_LOOK_AT_POINT }
Protected Member Functions
void addDoubleToPacket (double val, ArNetPacket &packet)
Adds the given value as a "double" to the given network packet.
void buildModePacket (void)
double getCurrentZoomRatio ()
Gets the current camera zoom as a ratio of its zoom range.
double getDoubleFromPacket (ArNetPacket &packet)
Reads a "double" value from the given network packet.
double getZoomRange ()
Gets the range of the camera's zoom.
double getZoomRatio (double absZoom)
Converts the given absolute zoom value to a ratio of the camera's zoom range.
void userTask (void)
Protected Attributes
ArPTZ * myCamera
Camera that is controlled.
ArFunctor2C< ArServerHandlerCamera, ArServerClient *, ArNetPacket * > myCameraAbsCB
Old (integer-style) handler for the cameraAbs packet.
ArFunctor2C< ArServerHandlerCamera, ArServerClient *, ArNetPacket * > myCameraCB
Old (integer-style) handler for the camera packet.
ArCameraCollection * myCameraCollection
Pointer to the camera collection (if any)
ArFunctor2C< ArServerHandlerCamera, ArServerClient *, ArNetPacket * > myCameraInfoCB
Old (integer-style) handler for the cameraInfo packet.
CameraMode myCameraMode
std::map< CameraMode, std::string > myCameraModeNameMap
ArNetPacket myCameraModePacket
std::string myCameraName
Unique name of the associated camera.
ArFunctor2C< ArServerHandlerCamera, ArServerClient *, ArNetPacket * > myCameraUpdateCB
Old (integer-style) handler for the cameraUpdate packet.
std::map< std::string, ArFunctor2< ArServerClient *, ArNetPacket * > * > myCommandToCBMap
Map of ArCameraCommand names to the callback that handles the packet.
std::map< std::string, int > myCommandToIntervalMap
Map of ArCameraCommand names to the preferred default request interval.
std::map< std::string, std::string > myCommandToPacketNameMap
Map of ArCameraCommand names to a unique network packet name.
ArPose myGoal
bool myGoalAchieved
bool myGoalAchievedLast
bool myGoalResetZoom
ArPose myLookAtPoint
ArMutex myModeMutex
bool myPointResetZoom
ArRobot * myRobot
Associated robot (primarily used for locking)
ArServerBase * myServer
Server from which requests are received.
ArFunctorC< ArServerHandlerCamera > myUserTaskCB
Detailed Description
Accepts and processes camera pan/tilt/zoom requests from the client, and provides information about the camera (such as its current position).
The following requests are accepted. Arguments and return values are stored in the packet as signed 16-bit values. (They are converted to double-precision floating point values when received by dividing by 100; to store floating point values, multiply by 100 first: packet.byte2ToBuf((ArTypes::Byte2)(100.0 * doubleVal)); or see also getDoubleFromPacket() and addDoubleToPacket().)
Each request name is suffixed by the name (Name in the table below) of the camera to control. If more than one camera is used, each can have a different name (given in the constructor), and commands for the different cameras are differentiated by appending the camera name to the command requests listed below. For example, an ArServerHandlerCamera with camera name of "A" would receive "setCameraRelA". while the handler with camera name of "B" would receive "setCameraAbsB". If no camera name is given (typical if just one ArServerHandlerCamera object is created), Name is empty, and just the base requests are used. A list of cameras can be provided to a client via ArCameraCollection and ArServerHandlerCameraCollection.
<table>
  <tr><th>Request</th> <th>Arguments</th> <th>Description</th></tr>
  <tr><td>setCameraRel<i>Name</i></td> <td>double: pan amount; double: tilt
amount; [double: zoom amount]
Command to pan and tilt the camera from the current position by the values given in the first two arguments. If a third argument is given, zoom from the current position.
setCameraAbsName
double: pan position; double: tilt position; [double: zoom position]
Command to pan and tilt the camera to the absolute positions given by the first two arguments. If a third argument is given, set the zoom to that absolute position.
setCameraPctName
double: pan position; double tilt position
Command to pan and tilt the camera to the given positions as percentage of their overall ranges.
getCameraDataName
none
Data request to get current pan and tilt values. Also get zoom value if available.
getCameraInfoName
None
Data request to get pan and tilt ranges. Also gets the zoom range if available.
In addition, some older camera requests are accepted for partial backwards
compatability with old clients: cameraUpdate, cameraInfo, cameraAbs, camera,
and cameraPct.  These requests take values as single bytes, rather than multiplied
floats as 2-bytes as the above commands do. Note, these cannot be used in a multi-camera
configuration.
These requests are in a user permission group called CameraControl.
In addition to positioning the camera, ArServerHandlerCamera can support additional "modes" for camera control, if additional code is added to update ArServerHandlerCamera with the state of other systems such as navigation.  The additional modes are LookAtGoal and LookAtPoint.  An external system such as navigation (e.g. ARNL) must keep the camera handler object updated with its current goal by calling cameraModeLookAtGoalSetGoal() and cameraModeLookAtGoalClearGoal(), and ArServerHandlerCamera will continuously point the camera at that point or goal as the robot moves. The network requests associated with setting modes are:
getCameraModeListName none Gets the list of modes that camera with name Name supports. Replies with a message containing a list of mode names as strings, ending with an empty string (or end of packet is
setCameraModeName string: mode name change the camera mode of camera with name Name reached)
The following messages may be broadcast:
getCameraModeUpdatedName string: mode name Sent when the mode is changed of the camera with name Name
Examples:
serverDemo.cpp.
Member Enumeration Documentation
anonymous enum protected
Enumerator
DOUBLE_FACTOR
Multiplier for putting/getting "double" values to/from a packet.
enum ArServerHandlerCamera::CameraMode protected
Enumerator
CAMERA_MODE_POSITION
CAMERA_MODE_LOOK_AT_GOAL
CAMERA_MODE_LOOK_AT_POINT
Constructor & Destructor Documentation
ArServerHandlerCamera::ArServerHandlerCamera (const char * cameraName, ArServerBase * server, ArRobot * robot, ArPTZ * camera, ArCameraCollection * collection)
Constructs a new handler for the specified camera.
Parameters
cameraName the unique char * name of the associated camera
server the ArServerBase * used to send/receive requests
robot the associated ArRobot *
camera the ArPTZ * that provides access to the actual camera
collection the ArCameraCollection * to which to add the camera command information; if NULL, then addToCameraCollection() must be called manually.
References myCameraCollection.
Referenced by ArServerHandlerCamera().
ArServerHandlerCamera::ArServerHandlerCamera (ArServerBase * server, ArRobot * robot, ArPTZ * camera)
Constructor.
This constructor is maintained for backwards compatibility. It will not work in a multi-camera configuration.
Deprecated:
Parameters
server the ArServerBase * used to send/receive requests
robot the associated ArRobot *
camera the ArPTZ * that provides access to the actual camera
robot The robot we're attached to (mostly used for locking the camera before sending commands)
server The server we're putting commands into
camera The camera we're going to command and give information from... it can be NULL in which case no commands are added
References ArServerHandlerCamera().
ArServerHandlerCamera::~ArServerHandlerCamera () virtual
Destructor.
References ArRobot::addUserTask(), CAMERA_MODE_LOOK_AT_GOAL, CAMERA_MODE_LOOK_AT_POINT, CAMERA_MODE_POSITION, myCameraMode, myCameraModeNameMap, myCommandToCBMap, myGoalAchieved, myModeMutex, myRobot, myUserTaskCB, ArMutex::setLogName(), and ArFunctor::setName().
Member Function Documentation
void ArServerHandlerCamera::addDoubleToPacket (double val, ArNetPacket & packet) inline protected
Adds the given value as a "double" to the given network packet.
The "double" value is really a 2-byte integer multiplied by the DOUBLE_FACTOR.
References ArBasePacket::byte2ToBuf(), and DOUBLE_FACTOR.
Referenced by handleGetCameraData(), and handleGetCameraInfo().
void ArServerHandlerCamera::addToCameraCollection (ArCameraCollection & collection) virtual
Adds the camera commands to the given collection.
Parameters
collection the ArCameraCollection to which to add the camera commands
Implements ArCameraCollectionItem.
void ArServerHandlerCamera::buildModePacket (void) protected
References ArBasePacket::byte4ToBuf(), CAMERA_MODE_LOOK_AT_POINT, ArNetPacket::empty(), ArPose::getX(), ArPose::getY(), myCameraMode, myCameraModeNameMap, myCameraModePacket, myLookAtPoint, ArMath::roundInt(), and ArBasePacket::strToBuf().
Referenced by cameraModeLookAtGoal(), cameraModeLookAtPoint(), and cameraModePosition().
void ArServerHandlerCamera::camera (ArServerClient * client, ArNetPacket * packet)
Handles the camera network packet, with information stored as byte integers.
References ArBasePacket::bufToByte(), and setCameraRel().
Referenced by getCameraName().
void ArServerHandlerCamera::cameraAbs (ArServerClient * client, ArNetPacket * packet)
Handles the cameraAbs network packet, with information stored as byte integers.
References ArBasePacket::bufToByte(), and setCameraAbs().
Referenced by getCameraName().
void ArServerHandlerCamera::cameraInfo (ArServerClient * client, ArNetPacket * packet)
Handles the cameraInfo network packet, with information returned as byte2 integers.
References ArBasePacket::byte2ToBuf(), ArBasePacket::byteToBuf(), ArPTZ::canZoom(), ArPTZ::getMaxNegPan(), ArPTZ::getMaxNegTilt(), ArPTZ::getMaxPosPan(), ArPTZ::getMaxPosTilt(), ArRobot::lock(), myCamera, myRobot, ArMath::roundInt(), ArServerClient::sendPacketUdp(), and ArRobot::unlock().
Referenced by getCameraName().
void ArServerHandlerCamera::cameraModeLookAtGoal (void)
Puts the camera into a mode where it will look at the goal.
References ArServerBase::broadcastPacketTcp(), buildModePacket(), CAMERA_MODE_LOOK_AT_GOAL, ArCameraCommands::CAMERA_MODE_UPDATED, ArMutex::lock(), ArLog::log(), myCameraMode, myCameraModePacket, myCommandToPacketNameMap, myGoalAchieved, myGoalAchievedLast, myGoalResetZoom, myModeMutex, myServer, ArLog::Normal, and ArMutex::unlock().
Referenced by handleSetCameraMode().
void ArServerHandlerCamera::cameraModeLookAtGoalClearGoal (void)
Clears the goal for the camera mode that points at the goal.
References ArMutex::lock(), myGoalAchieved, myModeMutex, and ArMutex::unlock().
void ArServerHandlerCamera::cameraModeLookAtGoalSetGoal (ArPose pose)
Sets the goal for the camera mode that points at the goal.
References ArMutex::lock(), myGoal, myGoalAchieved, myGoalAchievedLast, myGoalResetZoom, myModeMutex, and ArMutex::unlock().
void ArServerHandlerCamera::cameraModeLookAtPoint (ArPose pose, bool controlZoom = true)
Puts the camera into a mode where it will look at a point.
References ArServerBase::broadcastPacketTcp(), buildModePacket(), CAMERA_MODE_LOOK_AT_POINT, ArCameraCommands::CAMERA_MODE_UPDATED, ArPose::findDistanceTo(), ArPose::getX(), ArPose::getY(), ArMutex::lock(), ArLog::log(), myCameraMode, myCameraModePacket, myCommandToPacketNameMap, myLookAtPoint, myModeMutex, myPointResetZoom, myServer, ArLog::Normal, and ArMutex::unlock().
Referenced by handleSetCameraMode().
void ArServerHandlerCamera::cameraModePosition (void)
Puts the camera in position mode.
References ArServerBase::broadcastPacketTcp(), buildModePacket(), CAMERA_MODE_POSITION, ArCameraCommands::CAMERA_MODE_UPDATED, ArMutex::lock(), ArLog::log(), myCameraMode, myCameraModePacket, myCommandToPacketNameMap, myModeMutex, myServer, ArLog::Normal, and ArMutex::unlock().
Referenced by handleSetCameraMode(), resetCamera(), setCameraAbs(), setCameraPct(), and setCameraRel().
void ArServerHandlerCamera::cameraPct (ArServerClient * client, ArNetPacket * packet)
Handles the cameraPct network packet, with information stored as byte integers.
References ArBasePacket::bufToByte(), ArPTZ::canGetFOV(), ArLog::log(), myCamera, ArLog::Normal, and setCameraPct().
Referenced by getCameraName().
void ArServerHandlerCamera::cameraUpdate (ArServerClient * client, ArNetPacket * packet)
Handles the cameraUpdate network packet, with information returned as byte2 integers.
References ArBasePacket::byte2ToBuf(), ArPTZ::getMaxZoom(), ArPTZ::getMinZoom(), ArPTZ::getPan(), ArPTZ::getTilt(), ArPTZ::getZoom(), ArRobot::lock(), myCamera, myRobot, ArMath::roundInt(), ArServerClient::sendPacketUdp(), and ArRobot::unlock().
Referenced by getCameraName().
const char * ArServerHandlerCamera::getCameraName () virtual
Returns the name of the camera that is controlled by this handler.
Returns
char * the unique name of the associated camera (if specified in the constructor)
Implements ArCameraCollectionItem.
References ArCameraCollection::addCameraCommand(), ArServerBase::addData(), camera(), ArCameraCommands::CAMERA_MODE_UPDATED, cameraAbs(), cameraInfo(), cameraPct(), cameraUpdate(), ArPTZ::canGetFOV(), ArCameraCollection::exists(), ArCameraCommands::GET_CAMERA_DATA, ArCameraCommands::GET_CAMERA_DATA_INT, ArCameraCommands::GET_CAMERA_INFO, ArCameraCommands::GET_CAMERA_INFO_INT, ArCameraCommands::GET_CAMERA_MODE_LIST, handleCameraModeUpdated(), handleGetCameraData(), handleGetCameraInfo(), handleGetCameraModeList(), handleResetCamera(), handleSetCameraAbs(), handleSetCameraMode(), handleSetCameraPct(), handleSetCameraRel(), ArLog::log(), myCamera, myCameraName, myCommandToCBMap, myCommandToIntervalMap, myCommandToPacketNameMap, myServer, ArLog::Normal, ArCameraCommands::RESET_CAMERA, ArCameraCommands::SET_CAMERA_ABS, ArCameraCommands::SET_CAMERA_ABS_INT, ArCameraCommands::SET_CAMERA_MODE, ArCameraCommands::SET_CAMERA_PCT, ArCameraCommands::SET_CAMERA_PCT_INT, ArCameraCommands::SET_CAMERA_REL, and ArCameraCommands::SET_CAMERA_REL_INT.
double ArServerHandlerCamera::getCurrentZoomRatio () inline protected
Gets the current camera zoom as a ratio of its zoom range.
References ArPTZ::getMaxZoom(), ArPTZ::getMinZoom(), ArPTZ::getZoom(), and myCamera.
Referenced by handleGetCameraData(), setCameraPct(), and setCameraRel().
double ArServerHandlerCamera::getDoubleFromPacket (ArNetPacket & packet) inline protected
Reads a "double" value from the given network packet.
The "double" value is really a 2-byte integer multiplied by the DOUBLE_FACTOR.
References ArBasePacket::bufToByte2(), and DOUBLE_FACTOR.
Referenced by handleSetCameraAbs(), handleSetCameraPct(), and handleSetCameraRel().
double ArServerHandlerCamera::getZoomRange () inline protected
Gets the range of the camera's zoom.
References ArPTZ::getMaxZoom(), ArPTZ::getMinZoom(), and myCamera.
Referenced by setCameraAbs(), and setCameraRel().
double ArServerHandlerCamera::getZoomRatio (double absZoom) inline protected
Converts the given absolute zoom value to a ratio of the camera's zoom range.
References ArPTZ::getMaxZoom(), ArPTZ::getMinZoom(), and myCamera.
void ArServerHandlerCamera::handleCameraModeUpdated (ArServerClient * client, ArNetPacket * packet)
Handle the mode request, generally this is sent when it changes.
Refer to handleSetCameraMode for a description of the supported modes and the various packet structures.
Parameters
client the ArServerClient * that sent the request
packet the ArNetPacket * that contains the request
References ArMutex::lock(), myCameraModePacket, myModeMutex, ArServerClient::sendPacketTcp(), and ArMutex::unlock().
Referenced by getCameraName().
void ArServerHandlerCamera::handleGetCameraData (ArServerClient * client, ArNetPacket * packet)
Handles the getCameraData network packet, returning information in double format.
Parameters
client the ArServerClient * that sent the request
packet the ArNetPacket * that contains the request
References addDoubleToPacket(), getCurrentZoomRatio(), ArPTZ::getPan(), ArPTZ::getTilt(), ArRobot::lock(), myCamera, myRobot, ArServerClient::sendPacketUdp(), and ArRobot::unlock().
Referenced by getCameraName().
void ArServerHandlerCamera::handleGetCameraInfo (ArServerClient * client, ArNetPacket * packet)
Handles the getCameraInfo network packet, returning information in double format.
Parameters
client the ArServerClient * that sent the request
packet the ArNetPacket * that contains the request
References addDoubleToPacket(), ArBasePacket::byteToBuf(), ArPTZ::canZoom(), ArPTZ::getMaxNegPan(), ArPTZ::getMaxNegTilt(), ArPTZ::getMaxPosPan(), ArPTZ::getMaxPosTilt(), ArRobot::lock(), ArLog::log(), myCamera, myCameraName, myRobot, ArServerClient::sendPacketUdp(), ArRobot::unlock(), and ArLog::Verbose.
Referenced by getCameraName().
void ArServerHandlerCamera::handleGetCameraModeList (ArServerClient * client, ArNetPacket * packet)
Handles the mode list for the camera.
Parameters
client the ArServerClient * that sent the request
packet the ArNetPacket * that contains the request
References ArMutex::lock(), myCameraModeNameMap, myModeMutex, ArServerClient::sendPacketTcp(), ArBasePacket::strToBuf(), ArBasePacket::uByte2ToBuf(), and ArMutex::unlock().
Referenced by getCameraName().
void ArServerHandlerCamera::handleResetCamera (ArServerClient * client, ArNetPacket * packet)
Handle the reset.
Parameters
client the ArServerClient * that sent the request
packet the ArNetPacket * that contains the request
References resetCamera().
Referenced by getCameraName().
void ArServerHandlerCamera::handleSetCameraAbs (ArServerClient * client, ArNetPacket * packet)
Handles the setCameraAbs network packet, with information in double format.
Parameters
client the ArServerClient * that sent the request
packet the ArNetPacket * that contains the request
References getDoubleFromPacket(), myCamera, myRobot, and setCameraAbs().
Referenced by getCameraName().
void ArServerHandlerCamera::handleSetCameraMode (ArServerClient * client, ArNetPacket * packet)
Handle the set mode request.
The following modes are currently supported:
Position: The user controls the camera position; no additional parameters in the packet
LookAtGoal: The robot automatically points the camera in the direction of its destination goal; no additional parameters in the packet
LookAtPoint: The robot "looks" at a specified point in the map; the packet contains: byte4, the x coordinate; byte4, the y coordinate
Parameters
client the ArServerClient * that sent the request
packet the ArNetPacket * that contains the request
References ArBasePacket::bufToByte4(), ArBasePacket::bufToStr(), CAMERA_MODE_LOOK_AT_GOAL, CAMERA_MODE_LOOK_AT_POINT, CAMERA_MODE_POSITION, cameraModeLookAtGoal(), cameraModeLookAtPoint(), cameraModePosition(), ArLog::log(), myCameraModeNameMap, myCameraName, ArLog::Normal, ArPose::setX(), ArPose::setY(), and ArUtil::strcasecmp().
Referenced by getCameraName().
void ArServerHandlerCamera::handleSetCameraPct (ArServerClient * client, ArNetPacket * packet)
Handles the setCameraPct network packet, with information in double format.
Parameters
client the ArServerClient * that sent the request
packet the ArNetPacket * that contains the request
References ArPTZ::canGetFOV(), getDoubleFromPacket(), ArLog::log(), myCamera, ArLog::Normal, and setCameraPct().
Referenced by getCameraName().
void ArServerHandlerCamera::handleSetCameraRel (ArServerClient * client, ArNetPacket * packet)
Handles the setCameraRel network packet, with information in double format.
Parameters
client the ArServerClient * that sent the request
packet the ArNetPacket * that contains the request
References getDoubleFromPacket(), and setCameraRel().
Referenced by getCameraName().
void ArServerHandlerCamera::resetCamera (bool lockRobot = true)
Resets the camera.
References cameraModePosition(), ArRobot::lock(), myCamera, myRobot, ArPTZ::reset(), and ArRobot::unlock().
Referenced by handleResetCamera().
void ArServerHandlerCamera::setCameraAbs (double pan, double tilt, double zoom, bool lockRobot = true)
Sends the camera absolute commands to the camera (and puts it in position mode)
Parameters
pan the degrees to pan to (absolute)
tilt the degrees to tilt to (absolute)
zoom the percent (number between 0 and 100) to pan to (absolute)
lockRobot whether to lock the robot or not
References cameraModePosition(), ArPTZ::getMinZoom(), getZoomRange(), IFDEBUG, ArRobot::lock(), ArLog::log(), myCamera, myRobot, ArLog::Normal, ArPTZ::panTilt(), ArMath::roundInt(), ArRobot::unlock(), and ArPTZ::zoom().
Referenced by cameraAbs(), and handleSetCameraAbs().
void ArServerHandlerCamera::setCameraPct (double panPct, double tiltPct, bool lockRobot = true)
Sends the camera percent commands to the camera (and puts it in position mode)
Parameters
panPct the double percent offset from the image frame center by which to pan the camera; values range -100 to 100. 0 indicates no change.
tiltPct the double percent offset from the image frame center by which to tilt the camera; values range -100 to 100. 0 indicates no change.
lockRobot whether to lock the robot or not
Figure how much the x/y/z components of the left/right vector, this part is pretty straightforward since its just multiplying the left/right vector by the cos or sin to get the component in that direction (which is based on the pan)
------------------   y
|\)lr |
| \   | sin lr
|  \  |
|   \ |
|    \|
x
That derives the sin lr for the length of the vector... for how much of that is in which direction
    dx = sin lr * sin pan
------------------------- y
|\)pan  |
| \     |
|  \slr |  dy = sin lr * cos pan
|   \   |
|    \  |
|     \ |
|      \|
x
Where slr is the sin lr derived above and pan is the pan angle (since we're doing vectors the position we calculate these components from doesn't matter so we just move it back to 0 to make life easier)...
The - on the sin is needed, I think its because the camera pans positive to the right and negative to the left instead of positive to the right.
Figure how much the x/y/z components of the up/down vector,
So for x and y first we find how much is in the x/y plane (sin(ud) * sin(oldTilt)) and then we multiply that by the same sin or cos of the pan to see how much is in which coord...
For z we just multiply the up/down vector by the cos to find what the movement in z is.
Now add the original vector, the vector from left/right and the vector from up/down together.
 Now find where we have to pan and tilt to...
       |   ,
       |  /|z
       | / |
       |/t |y
       -)--|-------
      / \)p|  /
     /  h\ | / x
    /     \|/
 Where x, y, and z are the values we found above and tilt and pan
 are the tilt (angle of the line off of the x/y plane) and pan
 values (angle of the line within the x/y plain) we need to point
 at that point, h is the hypotenuse of the line projected into the
 x/y plane.
 tan pan = x / y
! pan = atan (x / y)
 cos pan = y / hyp
 hyp = y / cos pan
 sin pan = x / hyp
 hyp = x / sin pan
 tan tilt = z / hyp
! tilt = atan (z / hyp) (substitute in one of the hyps)
Pan is easy since its just the atan of x and y.
This denom can be either y/cos(pan) or x / sin(pan) depending on which solution you use and we use them in a way that won't get us a divide by 0.
References ArMath::atan2(), cameraModePosition(), ArMath::cos(), getCurrentZoomRatio(), ArPTZ::getFOVAtMaxZoom(), ArPTZ::getFOVAtMinZoom(), ArPTZ::getPan(), ArPTZ::getTilt(), IFDEBUG, ArRobot::lock(), ArLog::log(), myCamera, myRobot, ArLog::Normal, ArPTZ::panTilt(), ArMath::sin(), ArMath::tan(), and ArRobot::unlock().
Referenced by cameraPct(), and handleSetCameraPct().
void ArServerHandlerCamera::setCameraRel (double pan, double tilt, double zoom, bool lockRobot = true)
Sends the camera relative commands to the camera (and puts it in position mode)
Parameters
pan the degrees to pan to (relative)
tilt the degrees to tilt to (relative)
zoom the percent (number between 0 and 100) to change pan by (relative)
lockRobot whether to lock the robot or not
References cameraModePosition(), getCurrentZoomRatio(), ArPTZ::getMaxZoom(), ArPTZ::getMinZoom(), getZoomRange(), IFDEBUG, ArRobot::lock(), ArLog::log(), myCamera, myRobot, ArLog::Normal, ArPTZ::panRel(), ArPTZ::panTiltRel(), ArMath::roundInt(), ArPTZ::tiltRel(), ArRobot::unlock(), and ArPTZ::zoom().
Referenced by camera(), and handleSetCameraRel().
void ArServerHandlerCamera::userTask (void) protected
References CAMERA_MODE_LOOK_AT_GOAL, CAMERA_MODE_LOOK_AT_POINT, ArRobot::findDeltaHeadingTo(), ArMutex::lock(), myCamera, myCameraMode, myGoal, myGoalAchieved, myGoalAchievedLast, myGoalResetZoom, myLookAtPoint, myModeMutex, myPointResetZoom, myRobot, ArPTZ::panTilt(), ArMutex::unlock(), and ArPTZ::zoom().
Member Data Documentation
ArPTZ* ArServerHandlerCamera::myCamera protected
Camera that is controlled.
Referenced by cameraInfo(), cameraPct(), cameraUpdate(), getCameraName(), getCurrentZoomRatio(), getZoomRange(), getZoomRatio(), handleGetCameraData(), handleGetCameraInfo(), handleSetCameraAbs(), handleSetCameraPct(), resetCamera(), setCameraAbs(), setCameraPct(), setCameraRel(), and userTask().
ArFunctor2C<ArServerHandlerCamera, ArServerClient *, ArNetPacket *> ArServerHandlerCamera::myCameraAbsCB protected
Old (integer-style) handler for the cameraAbs packet.
Deprecated:
ArFunctor2C<ArServerHandlerCamera, ArServerClient *, ArNetPacket *> ArServerHandlerCamera::myCameraCB protected
Old (integer-style) handler for the camera packet.
Deprecated:
ArCameraCollection* ArServerHandlerCamera::myCameraCollection protected
Pointer to the camera collection (if any)
Referenced by ArServerHandlerCamera().
ArFunctor2C<ArServerHandlerCamera, ArServerClient *, ArNetPacket *> ArServerHandlerCamera::myCameraInfoCB protected
Old (integer-style) handler for the cameraInfo packet.
Deprecated:
CameraMode ArServerHandlerCamera::myCameraMode protected
Referenced by buildModePacket(), cameraModeLookAtGoal(), cameraModeLookAtPoint(), cameraModePosition(), userTask(), and ~ArServerHandlerCamera().
std::map<CameraMode, std::string> ArServerHandlerCamera::myCameraModeNameMap protected
Referenced by buildModePacket(), handleGetCameraModeList(), handleSetCameraMode(), and ~ArServerHandlerCamera().
ArNetPacket ArServerHandlerCamera::myCameraModePacket protected
Referenced by buildModePacket(), cameraModeLookAtGoal(), cameraModeLookAtPoint(), cameraModePosition(), and handleCameraModeUpdated().
std::string ArServerHandlerCamera::myCameraName protected
Unique name of the associated camera.
Referenced by getCameraName(), handleGetCameraInfo(), and handleSetCameraMode().
ArFunctor2C<ArServerHandlerCamera, ArServerClient *, ArNetPacket *> ArServerHandlerCamera::myCameraUpdateCB protected
Old (integer-style) handler for the cameraUpdate packet.
Deprecated:
std::map<std::string, ArFunctor2<ArServerClient *, ArNetPacket *> *> ArServerHandlerCamera::myCommandToCBMap protected
Map of ArCameraCommand names to the callback that handles the packet.
Referenced by getCameraName(), and ~ArServerHandlerCamera().
std::map<std::string, int> ArServerHandlerCamera::myCommandToIntervalMap protected
Map of ArCameraCommand names to the preferred default request interval.
Referenced by getCameraName().
std::map<std::string, std::string> ArServerHandlerCamera::myCommandToPacketNameMap protected
Map of ArCameraCommand names to a unique network packet name.
Referenced by cameraModeLookAtGoal(), cameraModeLookAtPoint(), cameraModePosition(), and getCameraName().
ArPose ArServerHandlerCamera::myGoal protected
Referenced by cameraModeLookAtGoalSetGoal(), and userTask().
bool ArServerHandlerCamera::myGoalAchieved protected
Referenced by cameraModeLookAtGoal(), cameraModeLookAtGoalClearGoal(), cameraModeLookAtGoalSetGoal(), userTask(), and ~ArServerHandlerCamera().
bool ArServerHandlerCamera::myGoalAchievedLast protected
Referenced by cameraModeLookAtGoal(), cameraModeLookAtGoalSetGoal(), and userTask().
bool ArServerHandlerCamera::myGoalResetZoom protected
Referenced by cameraModeLookAtGoal(), cameraModeLookAtGoalSetGoal(), and userTask().
ArPose ArServerHandlerCamera::myLookAtPoint protected
Referenced by buildModePacket(), cameraModeLookAtPoint(), and userTask().
ArMutex ArServerHandlerCamera::myModeMutex protected
Referenced by cameraModeLookAtGoal(), cameraModeLookAtGoalClearGoal(), cameraModeLookAtGoalSetGoal(), cameraModeLookAtPoint(), cameraModePosition(), handleCameraModeUpdated(), handleGetCameraModeList(), userTask(), and ~ArServerHandlerCamera().
bool ArServerHandlerCamera::myPointResetZoom protected
Referenced by cameraModeLookAtPoint(), and userTask().
ArRobot* ArServerHandlerCamera::myRobot protected
Associated robot (primarily used for locking)
Referenced by cameraInfo(), cameraUpdate(), handleGetCameraData(), handleGetCameraInfo(), handleSetCameraAbs(), resetCamera(), setCameraAbs(), setCameraPct(), setCameraRel(), userTask(), and ~ArServerHandlerCamera().
ArServerBase* ArServerHandlerCamera::myServer protected
Server from which requests are received.
Referenced by cameraModeLookAtGoal(), cameraModeLookAtPoint(), cameraModePosition(), and getCameraName().
ArFunctorC<ArServerHandlerCamera> ArServerHandlerCamera::myUserTaskCB protected
Referenced by ~ArServerHandlerCamera().
The documentation for this class was generated from the following files:
ArServerHandlerCamera.h
ArServerHandlerCamera.cpp