ArNetworking: ArHybridForwarderVideo Class Reference
ArHybridForwarderVideo Class Reference
This class takes video another source and serves it back up.
#include <ArHybridForwarderVideo.h>
Public Member Functions
virtual void addToCameraCollection (ArCameraCollection &collection)
Adds this item to the given camera collection.
ArHybridForwarderVideo (ArServerBase *server, ArClientBase *client)
Constructor that takes a client.
ArHybridForwarderVideo (ArServerBase *server, const char *hostname="localhost", int port=7070)
Constructor that just takes a host and port and makes its own client.
void clientCycleCallback (void)
Our callback that requests more video.
virtual const char * getCameraName ()
Returns the name of the camera handled by this item.
bool isForwardingVideo (void) const
Returns if we're forwarding video or not.
void receiveVideo (ArNetPacket *packet)
Receives the video (and sets a timer to wait a bit and get it again)
void receiveVideoSize (ArNetPacket *packet)
Receives the video size (just gets this once)
void sendVideo (ArServerClient *client, ArNetPacket *packet)
Sends the last received video.
void sendVideoSize (ArServerClient *client, ArNetPacket *packet)
Sends the last received video size (just gets this once)
virtual void setCameraName (const char *cameraName)
Sets the name of the camera handled by this item.
void setVideoRequestTime (int ms)
Sets how often after getting video we ask for it again.
int setVideoRequestTime (void) const
Gets how often after getting video we ask for it again.
virtual ~ArHybridForwarderVideo ()
Destructor.
Public Member Functions inherited from ArCameraCollectionItem
ArCameraCollectionItem ()
virtual ~ArCameraCollectionItem ()
Protected Member Functions
void finishConstructor (void)
Protected Attributes
std::string myCameraName
ArClientBase * myClient
ArFunctorC< ArHybridForwarderVideo > * myClientCycleCB
bool myForwardingVideo
bool myIsSendVideoAvailable
ArTime myLastReceivedVideo
ArTime myLastReqSent
ArMutex myMutex
ArNetPacket myReceivedVideo
ArNetPacket myReceivedVideoSize
ArFunctor1C< ArHybridForwarderVideo, ArNetPacket * > * myReceiveVideoCB
ArFunctor1C< ArHybridForwarderVideo, ArNetPacket * > * myReceiveVideoSizeCB
bool myReqSent
ArNetPacket mySendVideoArgument
ArFunctor2C< ArHybridForwarderVideo, ArServerClient *, ArNetPacket * > * mySendVideoCB
ArFunctor2C< ArHybridForwarderVideo, ArServerClient *, ArNetPacket * > * mySendVideoSizeCB
ArServerBase * myServer
int myVideoRequestTime
Detailed Description
This class takes video another source and serves it back up.
Deprecated:
Use ArVideoRemoteForwarder from the ArVideo library instead.
Examples:
serverDemo.cpp.
Constructor & Destructor Documentation
ArHybridForwarderVideo::ArHybridForwarderVideo (ArServerBase * server, ArClientBase * client)
Constructor that takes a client.
Parameters
server this class will addData the video data to the server
client IF the client is connected to something this class will get video data from the client and send it out when requested
References client, finishConstructor(), myClient, myMutex, myServer, and ArMutex::setLogName().
Referenced by finishConstructor().
ArHybridForwarderVideo::ArHybridForwarderVideo (ArServerBase * server, const char * hostname = "localhost", int port = 7070)
Constructor that just takes a host and port and makes its own client.
This will try to connect a client to the hostname and port given, IF client connects to something this class will get video data from the client and send it out when requested.
Parameters
server a base server object
hostname the host to connect a client to
port the port to connect a client to
References ArClientBase::blockingConnect(), finishConstructor(), myClient, myServer, ArClientBase::runAsync(), and ArClientBase::setConnectTimeoutTime().
ArHybridForwarderVideo::~ArHybridForwarderVideo () virtual
Destructor.
Member Function Documentation
void ArHybridForwarderVideo::addToCameraCollection (ArCameraCollection & collection) virtual
Adds this item to the given camera collection.
Implements ArCameraCollectionItem.
References ArCameraCollection::addCameraCommand(), ArServerBase::addData(), ArCameraCollection::exists(), ArCameraCommands::GET_PICTURE, ArCameraCommands::GET_VIDEO, ArLog::log(), myCameraName, myForwardingVideo, myIsSendVideoAvailable, mySendVideoCB, myServer, myVideoRequestTime, and ArLog::Verbose.
Referenced by setCameraName().
void ArHybridForwarderVideo::clientCycleCallback (void)
Our callback that requests more video.
References ArMutex::lock(), ArTime::mSecSince(), myClient, myLastReceivedVideo, myLastReqSent, myMutex, myReqSent, mySendVideoArgument, myVideoRequestTime, ArClientBase::requestOnce(), ArTime::setToNow(), and ArMutex::unlock().
Referenced by finishConstructor().
void ArHybridForwarderVideo::finishConstructor (void) protected
References ArClientBase::addCycleCallback(), ArServerBase::addData(), ArClientBase::addHandler(), ArHybridForwarderVideo(), clientCycleCallback(), ArClientBase::dataExists(), ArClientBase::isConnected(), ArThread::lock(), ArLog::log(), myClient, myClientCycleCB, myForwardingVideo, myIsSendVideoAvailable, myLastReceivedVideo, myLastReqSent, myReceiveVideoCB, myReceiveVideoSizeCB, myReqSent, mySendVideoCB, mySendVideoSizeCB, myServer, myVideoRequestTime, ArLog::Normal, receiveVideo(), receiveVideoSize(), ArClientBase::requestOnce(), sendVideo(), sendVideoSize(), ArTime::setToNow(), ArBasePacket::uByteToBuf(), and ArThread::unlock().
Referenced by ArHybridForwarderVideo(), and setVideoRequestTime().
const char * ArHybridForwarderVideo::getCameraName () virtual
Returns the name of the camera handled by this item.
Implements ArCameraCollectionItem.
References myCameraName.
bool ArHybridForwarderVideo::isForwardingVideo (void) const
Returns if we're forwarding video or not.
Examples:
serverDemo.cpp.
References myForwardingVideo.
Referenced by main().
void ArHybridForwarderVideo::receiveVideo (ArNetPacket * packet)
Receives the video (and sets a timer to wait a bit and get it again)
References ArNetPacket::duplicatePacket(), ArMutex::lock(), myLastReceivedVideo, myMutex, myReceivedVideo, myReqSent, ArNetPacket::resetRead(), ArTime::setToNow(), and ArMutex::unlock().
Referenced by finishConstructor().
void ArHybridForwarderVideo::receiveVideoSize (ArNetPacket * packet)
Receives the video size (just gets this once)
References ArNetPacket::duplicatePacket(), ArMutex::lock(), myMutex, myReceivedVideoSize, mySendVideoArgument, ArNetPacket::resetRead(), and ArMutex::unlock().
Referenced by finishConstructor().
void ArHybridForwarderVideo::sendVideo (ArServerClient * client, ArNetPacket * packet)
Sends the last received video.
References ArNetPacket::duplicatePacket(), ArMutex::lock(), myMutex, myReceivedVideo, mySendVideoArgument, ArNetPacket::resetRead(), ArServerClient::sendPacketUdp(), ArNetPacket::setCommand(), and ArMutex::unlock().
Referenced by finishConstructor().
void ArHybridForwarderVideo::sendVideoSize (ArServerClient * client, ArNetPacket * packet)
Sends the last received video size (just gets this once)
References ArNetPacket::getCommand(), ArMutex::lock(), myMutex, myReceivedVideoSize, ArServerClient::sendPacketTcp(), ArNetPacket::setCommand(), and ArMutex::unlock().
Referenced by finishConstructor().
void ArHybridForwarderVideo::setCameraName (const char * cameraName) virtual
Sets the name of the camera handled by this item.
This method must be called before addToCameraCollection().
References addToCameraCollection(), and myCameraName.
void ArHybridForwarderVideo::setVideoRequestTime (int ms) inline
Sets how often after getting video we ask for it again.
References myVideoRequestTime.
int ArHybridForwarderVideo::setVideoRequestTime (void) const inline
Gets how often after getting video we ask for it again.
References finishConstructor(), and myVideoRequestTime.
Member Data Documentation
std::string ArHybridForwarderVideo::myCameraName protected
Referenced by addToCameraCollection(), getCameraName(), and setCameraName().
ArClientBase* ArHybridForwarderVideo::myClient protected
Referenced by ArHybridForwarderVideo(), clientCycleCallback(), and finishConstructor().
ArFunctorC<ArHybridForwarderVideo>* ArHybridForwarderVideo::myClientCycleCB protected
Referenced by finishConstructor().
bool ArHybridForwarderVideo::myForwardingVideo protected
Referenced by addToCameraCollection(), finishConstructor(), and isForwardingVideo().
bool ArHybridForwarderVideo::myIsSendVideoAvailable protected
Referenced by addToCameraCollection(), and finishConstructor().
ArTime ArHybridForwarderVideo::myLastReceivedVideo protected
Referenced by clientCycleCallback(), finishConstructor(), and receiveVideo().
ArTime ArHybridForwarderVideo::myLastReqSent protected
Referenced by clientCycleCallback(), and finishConstructor().
ArMutex ArHybridForwarderVideo::myMutex protected
Referenced by ArHybridForwarderVideo(), clientCycleCallback(), receiveVideo(), receiveVideoSize(), sendVideo(), and sendVideoSize().
ArNetPacket ArHybridForwarderVideo::myReceivedVideo protected
Referenced by receiveVideo(), and sendVideo().
ArNetPacket ArHybridForwarderVideo::myReceivedVideoSize protected
Referenced by receiveVideoSize(), and sendVideoSize().
ArFunctor1C<ArHybridForwarderVideo, ArNetPacket *>* ArHybridForwarderVideo::myReceiveVideoCB protected
Referenced by finishConstructor().
ArFunctor1C<ArHybridForwarderVideo, ArNetPacket *>* ArHybridForwarderVideo::myReceiveVideoSizeCB protected
Referenced by finishConstructor().
bool ArHybridForwarderVideo::myReqSent protected
Referenced by clientCycleCallback(), finishConstructor(), and receiveVideo().
ArNetPacket ArHybridForwarderVideo::mySendVideoArgument protected
Referenced by clientCycleCallback(), receiveVideoSize(), and sendVideo().
ArFunctor2C<ArHybridForwarderVideo, ArServerClient*, ArNetPacket *>* ArHybridForwarderVideo::mySendVideoCB protected
Referenced by addToCameraCollection(), and finishConstructor().
ArFunctor2C<ArHybridForwarderVideo, ArServerClient*, ArNetPacket *>* ArHybridForwarderVideo::mySendVideoSizeCB protected
Referenced by finishConstructor().
ArServerBase* ArHybridForwarderVideo::myServer protected
Referenced by addToCameraCollection(), ArHybridForwarderVideo(), and finishConstructor().
int ArHybridForwarderVideo::myVideoRequestTime protected
Referenced by addToCameraCollection(), clientCycleCallback(), finishConstructor(), and setVideoRequestTime().
The documentation for this class was generated from the following files:
ArHybridForwarderVideo.h
ArHybridForwarderVideo.cpp