ArNetworking: ArServerHandlerPopupInfo Class Reference
ArServerHandlerPopupInfo Class Reference
Holds the information for a popup.
#include <ArServerHandlerPopup.h>
Public Member Functions
ArServerHandlerPopupInfo (const char *ignoreIdentifier, const char *title, const char *message, ArServerHandlerPopup::PopupType popupType, ArTypes::Byte defaultButtonNumber, ArTypes::Byte escapeButtonNumber, int timeoutInSeconds, const char *timeoutString, const char *button0Label, const char *button0Pressed, const char *button1Label="", const char *button1Pressed="", const char *button2Label="", const char *button2Pressed="")
Constructor.
ArServerHandlerPopupInfo (const ArServerHandlerPopupInfo &popupInfo)
Copy constructor.
const char * getButton0Label (void)
Gets the button0Label (the label on the leftmost button, must have a label)
const char * getButton0Pressed (void)
Gets the button0Pressed (string sent as box disppears if this button is pressed)
const char * getButton1Label (void)
Gets the button1Label (the label on the middle button, empty string or NULL for no button)
const char * getButton1Pressed (void)
Gets the button1Pressed (string sent as box disppears if this button is pressed)
const char * getButton2Label (void)
Gets the button2Label (the label on the right button, empty string or NULL for no button)
const char * getButton2Pressed (void)
Gets the button2Pressed (string sent as box disppears if this button is pressed)
ArTypes::Byte getDefaultButtonNumber (void)
Gets the default button number (whats pressed when enter is hit)
ArTypes::Byte getEscapeButtonNumber (void)
Gets the escape button number (whats pressed when escape is hit)
const char * getIgnoreIdentifier (void)
Gets the popup identifer (this is used only for ignoring popups, if empty or NULL then it can't be ignored)
const char * getMessage (void)
Gets the message (the long string that is displayed that explains things)
ArServerHandlerPopup::PopupType getPopupType (void)
Gets the type (the icon thats displayed and what type of popup it is)
int getTimeout (void)
Gets the timeout in seconds (0 is never)
const char * getTimeoutString (void)
Gets the timeout string (the string that is displayed on the popup if timeout occurs)
const char * getTitle (void)
Gets the title (the title of the popup box)
ArServerHandlerPopupInfo & operator= (const ArServerHandlerPopupInfo &popupInfo)
Assignment operator.
void setButton0Label (const char *label)
Sets the button0Label (the label on the leftmost button, must have a label)
void setButton0Pressed (const char *pressed)
Sets the button0Pressed (string sent as box disppears if this button is pressed)
void setButton1Label (const char *label)
Sets the button1Label (the label on the middle button, empty string or NULL for no button)
void setButton1Pressed (const char *pressed)
Sets the button1Pressed (string sent as box disppears if this button is pressed)
void setButton2Label (const char *label)
Sets the button2Label (the label on the right button, empty string or NULL for no button)
void setButton2Pressed (const char *pressed)
Sets the button2Pressed (string sent as box disppears if this button is pressed)
void setDefaultButtonNumber (ArTypes::Byte defaultButtonNumber)
Sets the default button number (whats pressed when enter is hit)
void setEscapeButtonNumber (ArTypes::Byte escapeButtonNumber)
Sets the escape button number (whats pressed when escape is hit)
void setIgnoreIdentifier (const char *identifier)
Gets the popup identifer (this is used only for ignoring popups, if empty or NULL then it can't be ignored)
void setMessage (const char *message)
Sets the message (the long string that is displayed that explains things)
void setPopupType (ArServerHandlerPopup::PopupType popupType)
Sets the type (the icon thats displayed and what type of popup it is)
void setTimeout (int timeoutInSeconds)
Sets the timeout in seconds (0 is never)
void setTimeoutString (const char *timeoutString)
Sets the timeout string (the string that is displayed on the popup if timeout occurs)
void setTitle (const char *title)
Sets the title (the title of the popup box)
virtual ~ArServerHandlerPopupInfo ()
Destructor.
Protected Attributes
std::string myButton0Label
std::string myButton0Pressed
std::string myButton1Label
std::string myButton1Pressed
std::string myButton2Label
std::string myButton2Pressed
ArTypes::Byte myDefaultButtonNumber
ArTypes::Byte myEscapeButtonNumber
std::string myIgnoreIdentifier
std::string myMessage
ArServerHandlerPopup::PopupType myPopupType
int myTimeout
std::string myTimeoutString
std::string myTitle
Detailed Description
Holds the information for a popup.
This holds the information for the popup.... So there's a message box with the title which has in it the message, and has between 1 and 3 buttons (button0, button1, and button2) with labels of button0Label, button1Label, and button2Label (if the label is empty or NULL then there'll be no button), the default button of defaultButtonNumber (0 - 2) and the escape button number of escapeButtonNumber (0 - 2)... when a button is pushed the
Parameters
ignoreIdentifier The identifier to use for ignoring these boxes, this should be NULL or empty if you don't want this particular box to be able to be ignored (if any popup with this identifier is already being ignored this one will be too)
title The title of the box (displayed in the titlebar)
message The string that will be displayed in the message box (the point of the whole thing)
popupType The type of popup this is, which controls the icon displayed, may someday affect behavior
defaultButtonPressed The button that enter defaults to (This should be whatever is most likely)
escapeButtonPressed The button that escape defaults to (this should be doesn't change the state, ie like cancel), this also should be whats returned if the X is hit.
button0Label The label that is displayed on button 0, the leftmost button
timeoutInSeconds the number of seconds we should give people to respond to the popup before timing it out, 0 means leave it up forever (note that no clients may be watching this or no one may be at the console and use this option wisely (way too many untimed out popups could bog down the server))
timeoutString The string that will be displayed if a timeout happens
button0Pressed The string that will be put into the box if button0 is pressed (this is mainly so that with multiple clients connected the other clients will get feedback)
button1Label The label that is displayed on button 1 (the middle button if there are 3, right button if there are two)
button1Pressed The string that will be put into the box if button1 is pressed (this is mainly so that with multiple clients connected the other clients will get feedback)
button2Label The label that is displayed on button 2 (the right button)
button2Pressed The string that will be put into the box if button2 is pressed (this is mainly so that with multiple clients connected the other clients will get feedback)
Examples:
popupExample.cpp.
Constructor & Destructor Documentation
ArServerHandlerPopupInfo::ArServerHandlerPopupInfo (const char * ignoreIdentifier, const char * title, const char * message, ArServerHandlerPopup::PopupType popupType, ArTypes::Byte defaultButtonNumber, ArTypes::Byte escapeButtonNumber, int timeoutInSeconds, const char * timeoutString, const char * button0Label, const char * button0Pressed, const char * button1Label = "", const char * button1Pressed = "", const char * button2Label = "", const char * button2Pressed = "")
Constructor.
ArServerHandlerPopupInfo::~ArServerHandlerPopupInfo () virtual
Destructor.
ArServerHandlerPopupInfo::ArServerHandlerPopupInfo (const ArServerHandlerPopupInfo & popupInfo)
Copy constructor.
References myButton0Label, myButton0Pressed, myButton1Label, myButton1Pressed, myButton2Label, myButton2Pressed, myDefaultButtonNumber, myEscapeButtonNumber, myIgnoreIdentifier, myMessage, myPopupType, myTimeout, myTimeoutString, and myTitle.
Member Function Documentation
const char* ArServerHandlerPopupInfo::getButton0Label (void) inline
Gets the button0Label (the label on the leftmost button, must have a label)
Referenced by ArServerHandlerPopup::buildPacket().
const char* ArServerHandlerPopupInfo::getButton0Pressed (void) inline
Gets the button0Pressed (string sent as box disppears if this button is pressed)
Referenced by ArServerHandlerPopup::netPopupClicked().
const char* ArServerHandlerPopupInfo::getButton1Label (void) inline
Gets the button1Label (the label on the middle button, empty string or NULL for no button)
Referenced by ArServerHandlerPopup::buildPacket().
const char* ArServerHandlerPopupInfo::getButton1Pressed (void) inline
Gets the button1Pressed (string sent as box disppears if this button is pressed)
Referenced by ArServerHandlerPopup::netPopupClicked().
const char* ArServerHandlerPopupInfo::getButton2Label (void) inline
Gets the button2Label (the label on the right button, empty string or NULL for no button)
Referenced by ArServerHandlerPopup::buildPacket().
const char* ArServerHandlerPopupInfo::getButton2Pressed (void) inline
Gets the button2Pressed (string sent as box disppears if this button is pressed)
Referenced by ArServerHandlerPopup::netPopupClicked().
ArTypes::Byte ArServerHandlerPopupInfo::getDefaultButtonNumber (void) inline
Gets the default button number (whats pressed when enter is hit)
Referenced by ArServerHandlerPopup::buildPacket().
ArTypes::Byte ArServerHandlerPopupInfo::getEscapeButtonNumber (void) inline
Gets the escape button number (whats pressed when escape is hit)
Referenced by ArServerHandlerPopup::buildPacket().
const char* ArServerHandlerPopupInfo::getIgnoreIdentifier (void) inline
Gets the popup identifer (this is used only for ignoring popups, if empty or NULL then it can't be ignored)
Referenced by ArServerHandlerPopup::buildPacket().
const char* ArServerHandlerPopupInfo::getMessage (void) inline
Gets the message (the long string that is displayed that explains things)
Referenced by ArServerHandlerPopup::buildPacket().
ArServerHandlerPopup::PopupType ArServerHandlerPopupInfo::getPopupType (void) inline
Gets the type (the icon thats displayed and what type of popup it is)
Referenced by ArServerHandlerPopup::buildPacket().
int ArServerHandlerPopupInfo::getTimeout (void) inline
Gets the timeout in seconds (0 is never)
Referenced by ArServerHandlerPopup::serverCycleCallback().
const char* ArServerHandlerPopupInfo::getTimeoutString (void) inline
Gets the timeout string (the string that is displayed on the popup if timeout occurs)
Referenced by ArServerHandlerPopup::serverCycleCallback().
const char* ArServerHandlerPopupInfo::getTitle (void) inline
Gets the title (the title of the popup box)
Referenced by ArServerHandlerPopup::buildPacket().
ArServerHandlerPopupInfo & ArServerHandlerPopupInfo::operator= (const ArServerHandlerPopupInfo & popupInfo)
Assignment operator.
References myButton0Label, myButton0Pressed, myButton1Label, myButton1Pressed, myButton2Label, myButton2Pressed, myDefaultButtonNumber, myEscapeButtonNumber, myIgnoreIdentifier, myMessage, myPopupType, myTimeout, myTimeoutString, and myTitle.
void ArServerHandlerPopupInfo::setButton0Label (const char * label) inline
Sets the button0Label (the label on the leftmost button, must have a label)
void ArServerHandlerPopupInfo::setButton0Pressed (const char * pressed) inline
Sets the button0Pressed (string sent as box disppears if this button is pressed)
void ArServerHandlerPopupInfo::setButton1Label (const char * label) inline
Sets the button1Label (the label on the middle button, empty string or NULL for no button)
void ArServerHandlerPopupInfo::setButton1Pressed (const char * pressed) inline
Sets the button1Pressed (string sent as box disppears if this button is pressed)
void ArServerHandlerPopupInfo::setButton2Label (const char * label) inline
Sets the button2Label (the label on the right button, empty string or NULL for no button)
void ArServerHandlerPopupInfo::setButton2Pressed (const char * pressed) inline
Sets the button2Pressed (string sent as box disppears if this button is pressed)
void ArServerHandlerPopupInfo::setDefaultButtonNumber (ArTypes::Byte defaultButtonNumber) inline
Sets the default button number (whats pressed when enter is hit)
void ArServerHandlerPopupInfo::setEscapeButtonNumber (ArTypes::Byte escapeButtonNumber) inline
Sets the escape button number (whats pressed when escape is hit)
void ArServerHandlerPopupInfo::setIgnoreIdentifier (const char * identifier) inline
Gets the popup identifer (this is used only for ignoring popups, if empty or NULL then it can't be ignored)
void ArServerHandlerPopupInfo::setMessage (const char * message) inline
Sets the message (the long string that is displayed that explains things)
void ArServerHandlerPopupInfo::setPopupType (ArServerHandlerPopup::PopupType popupType) inline
Sets the type (the icon thats displayed and what type of popup it is)
void ArServerHandlerPopupInfo::setTimeout (int timeoutInSeconds) inline
Sets the timeout in seconds (0 is never)
void ArServerHandlerPopupInfo::setTimeoutString (const char * timeoutString) inline
Sets the timeout string (the string that is displayed on the popup if timeout occurs)
void ArServerHandlerPopupInfo::setTitle (const char * title) inline
Sets the title (the title of the popup box)
Member Data Documentation
std::string ArServerHandlerPopupInfo::myButton0Label protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
std::string ArServerHandlerPopupInfo::myButton0Pressed protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
std::string ArServerHandlerPopupInfo::myButton1Label protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
std::string ArServerHandlerPopupInfo::myButton1Pressed protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
std::string ArServerHandlerPopupInfo::myButton2Label protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
std::string ArServerHandlerPopupInfo::myButton2Pressed protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
ArTypes::Byte ArServerHandlerPopupInfo::myDefaultButtonNumber protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
ArTypes::Byte ArServerHandlerPopupInfo::myEscapeButtonNumber protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
std::string ArServerHandlerPopupInfo::myIgnoreIdentifier protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
std::string ArServerHandlerPopupInfo::myMessage protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
ArServerHandlerPopup::PopupType ArServerHandlerPopupInfo::myPopupType protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
int ArServerHandlerPopupInfo::myTimeout protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
std::string ArServerHandlerPopupInfo::myTimeoutString protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
std::string ArServerHandlerPopupInfo::myTitle protected
Referenced by ArServerHandlerPopupInfo(), and operator=().
The documentation for this class was generated from the following files:
ArServerHandlerPopup.h
ArServerHandlerPopup.cpp