ArNetworking: ArTempDirectoryHelper Class Reference
ArTempDirectoryHelper Class Reference
Helper class that manages the transition of temporary files to the base directory.
#include <ArTempDirectoryHelper.h>
Public Member Functions
void addPostMoveCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be called after moving from temp dir to base dir.
void addPreMoveCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be called before moving from temp dir to base dir.
ArTempDirectoryHelper (const char *baseDirectory="", const char *tempDirectory="")
Constructor.
const char * getBaseDirectory ()
Returns the name of the target base directory.
const char * getTempDirectory ()
Returns the name of the directory for temporary files.
std::string makeBaseFilePathName (const char *fileName)
Creates a complete file path name for the specified file in the base directory.
std::string makeTempFilePathName (const char *fileName)
Creates a complete file path name for the specified file in the temporary directory.
bool moveFilesToBaseDirectory (const std::list< std::string > &fileNameList)
Moves the specified files from the temporary directory to the base directory.
bool moveFileToBaseDirectory (const char *fileName)
Moves the specified file from the temporary directory to the base directory.
void remPostMoveCallback (ArFunctor *functor)
Removes a callback to be called after moving from temp dir to base dir.
void remPreMoveCallback (ArFunctor *functor)
Removes a callback to be called before moving from temp dir to base dir.
virtual ~ArTempDirectoryHelper ()
Destructor.
Protected Member Functions
std::string makeFilePathName (const char *fileName, const char *dirName)
Creates a complete file path name for the specified file and directory.
Protected Attributes
std::string myBaseDirectory
Path name of the base directory.
std::list< ArFunctor * > myPostMoveCallbacks
List of callbacks invoked after the files are moved.
std::list< ArFunctor * > myPreMoveCallbacks
List of callbacks invoked before the files are moved.
std::string myTempDirectory
Path name of the temporary directory.
Detailed Description
Helper class that manages the transition of temporary files to the base directory.
Constructor & Destructor Documentation
ArTempDirectoryHelper::ArTempDirectoryHelper (const char * baseDirectory = "", const char * tempDirectory = "")
Constructor.
ArTempDirectoryHelper::~ArTempDirectoryHelper () virtual
Destructor.
Member Function Documentation
void ArTempDirectoryHelper::addPostMoveCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback to be called after moving from temp dir to base dir.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myPostMoveCallbacks, and ArLog::Terse.
Referenced by ArServerHandlerMapping::addPostMoveCallback().
void ArTempDirectoryHelper::addPreMoveCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback to be called before moving from temp dir to base dir.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myPreMoveCallbacks, and ArLog::Terse.
Referenced by ArServerHandlerMapping::addPreMoveCallback().
const char * ArTempDirectoryHelper::getBaseDirectory (void)
Returns the name of the target base directory.
References moveFileToBaseDirectory(), and myBaseDirectory.
const char * ArTempDirectoryHelper::getTempDirectory (void)
Returns the name of the directory for temporary files.
References myTempDirectory.
Referenced by ArServerHandlerMapping::serverMappingStart().
std::string ArTempDirectoryHelper::makeBaseFilePathName (const char * fileName)
Creates a complete file path name for the specified file in the base directory.
References makeFilePathName(), and myBaseDirectory.
Referenced by makeTempFilePathName().
std::string ArTempDirectoryHelper::makeFilePathName (const char * fileName, const char * dirName) protected
Creates a complete file path name for the specified file and directory.
References ArUtil::isStrEmpty(), and myTempDirectory.
Referenced by makeBaseFilePathName(), and makeTempFilePathName().
std::string ArTempDirectoryHelper::makeTempFilePathName (const char * fileName)
Creates a complete file path name for the specified file in the temporary directory.
References makeBaseFilePathName(), makeFilePathName(), and myTempDirectory.
Referenced by moveFilesToBaseDirectory().
bool ArTempDirectoryHelper::moveFilesToBaseDirectory (const std::list< std::string > & fileNameList)
Moves the specified files from the temporary directory to the base directory.
References ArUtil::fixSlashes(), ArLog::log(), makeTempFilePathName(), myBaseDirectory, myPostMoveCallbacks, myPreMoveCallbacks, myTempDirectory, ArLog::Normal, ArUtil::strcasecmp(), and ArLog::Verbose.
Referenced by moveFileToBaseDirectory(), and ArServerHandlerMapping::serverMappingEnd().
bool ArTempDirectoryHelper::moveFileToBaseDirectory (const char * fileName)
Moves the specified file from the temporary directory to the base directory.
References ArUtil::isStrEmpty(), ArLog::log(), moveFilesToBaseDirectory(), and ArLog::Normal.
Referenced by getBaseDirectory().
void ArTempDirectoryHelper::remPostMoveCallback (ArFunctor * functor)
Removes a callback to be called after moving from temp dir to base dir.
References myPostMoveCallbacks.
Referenced by ArServerHandlerMapping::remPostMoveCallback().
void ArTempDirectoryHelper::remPreMoveCallback (ArFunctor * functor)
Removes a callback to be called before moving from temp dir to base dir.
References myPreMoveCallbacks.
Referenced by ArServerHandlerMapping::remPreMoveCallback().
Member Data Documentation
std::string ArTempDirectoryHelper::myBaseDirectory protected
Path name of the base directory.
Referenced by getBaseDirectory(), makeBaseFilePathName(), and moveFilesToBaseDirectory().
std::list<ArFunctor *> ArTempDirectoryHelper::myPostMoveCallbacks protected
List of callbacks invoked after the files are moved.
Referenced by addPostMoveCallback(), moveFilesToBaseDirectory(), and remPostMoveCallback().
std::list<ArFunctor *> ArTempDirectoryHelper::myPreMoveCallbacks protected
List of callbacks invoked before the files are moved.
Referenced by addPreMoveCallback(), moveFilesToBaseDirectory(), and remPreMoveCallback().
std::string ArTempDirectoryHelper::myTempDirectory protected
Path name of the temporary directory.
Referenced by getTempDirectory(), makeFilePathName(), makeTempFilePathName(), and moveFilesToBaseDirectory().
The documentation for this class was generated from the following files:
ArTempDirectoryHelper.h
ArTempDirectoryHelper.cpp