ArNetworking: ArServerHandlerCameraCollection Class Reference
ArServerHandlerCameraCollection Class Reference
Provides information to a client about different cameras and how to send requests to their different ArServerHandlerCamera and video image server objects.
#include <ArServerHandlerCameraCollection.h>
Public Member Functions
ArServerHandlerCameraCollection (ArServerBase *server, ArCameraCollection *cameraCollection)
Constructor.
void getCameraList (ArServerClient *client, ArNetPacket *packet)
Handles the request to get the camera list / collection.
void handleCameraCollectionModified ()
Callback executed when the associated camera collection is modified.
void setParams (ArServerClient *client, ArNetPacket *packet)
Handles the request to edit a camera's parameters.
virtual ~ArServerHandlerCameraCollection ()
Destructor.
Protected Attributes
ArCameraCollection * myCameraCollection
The associated camera collection.
ArFunctor * myCollectionModifiedCB
Notification callback when the camera collection has been modified.
ArFunctor2< ArServerClient *, ArNetPacket * > * myGetCameraListCB
Server callback for the get camera list request.
ArServerBase * myServer
The server used to send/receive requests.
ArFunctor2< ArServerClient *, ArNetPacket * > * mySetParamCB
Server callback for the set parameter request.
Static Protected Attributes
static const char * COLLECTION_UPDATED_PACKET_NAME
Name of the network packet broadcast when the collection is modified.
static const char * COMMAND_GROUP
Command group for these packets.
static const char * GET_COLLECTION_PACKET_NAME
Name of the network packet to get the camera list.
static const char * PARAMS_UPDATED_PACKET_NAME
Name of the network packet broadcast when a parameter value is modified.
static const char * SET_PARAMS_PACKET_NAME
Name of the network packet to set a particular camera parameter.
Detailed Description
Provides information to a client about different cameras and how to send requests to their different ArServerHandlerCamera and video image server objects.
ArServerHandlerCameraCollection defines the network packet handlers to transmit information regarding the cameras and their video streams that are installed on the robot.
This class handles the following requests:
getCameraList: Replies with a packet containing a 2-byte integer indicating the number of cameras. Then, for each camera:
camera name (string)
camera type (string)
camera name for user display (string)
camera type for user display (string)
list of requests that can be sent for this camera, beginning with the 2-byte number of commands, then, for each command:
the generic descriptive name (string)
the specific command request name (string)
an appropriate frequency for making this request (4-byte integer)
list of parameters, beginning with the 2-byte number of parameters, then, for each parameter, the parameter definition/value (see ArClientArg for format).
setCameraParams: Set some camera parameters. Begins with camera name string, then for each parameter, the parameter name and value (see ArClientArg for the format). An empty parameter name string terminates the list. In reply, this handler sends a packet confirming the changes (see cameraParamUpdated below).
When a camera is added or a parameter changes, the server broadcasts the following packets to each client:
cameraListUpdate: no arguments, use getCameraList to get the new list.
cameraParamUpdated: starts with camera name, then a list of parameter name and value (see ArClientArg for format). An empty parameter name string terminates the list.
Note that the cameraParamUpdated is currently only sent in response to a setCameraParams request. That is, it does not monitor the actual parameter values in the ArCameraCollection.
In order to manipulate a particular camera using the request names and other information provided by ArServerHandlerCameraCollection, see ArServerHandlerCamera and ArVideoServer.
Constructor & Destructor Documentation
ArServerHandlerCameraCollection::ArServerHandlerCameraCollection (ArServerBase * server, ArCameraCollection * cameraCollection)
Constructor.
Parameters
server the ArServerBase * used to send/receive requests
cameraCollection the ArCameraCollection * to be transmitted
References getCameraList(), handleCameraCollectionModified(), and setParams().
ArServerHandlerCameraCollection::~ArServerHandlerCameraCollection () virtual
Destructor.
References myCameraCollection, myCollectionModifiedCB, and ArCameraCollection::removeModifiedCB().
Member Function Documentation
void ArServerHandlerCameraCollection::getCameraList (ArServerClient * client, ArNetPacket * packet)
Handles the request to get the camera list / collection.
Parameters
client the ArServerClient * that is making the request
packet the ArNetPacket * that contains the request
References ArBasePacket::byte2ToBuf(), ArBasePacket::byte4ToBuf(), ArClientArg::createPacket(), ArCameraCollection::getCameraCommands(), ArCameraCollection::getCameraNames(), ArCameraCollection::getCameraType(), ArCameraCollection::getCommandName(), ArCameraCollection::getDisplayName(), ArCameraCollection::getDisplayType(), ArCameraCollection::getParameter(), ArCameraCollection::getParameterNames(), ArCameraCollection::getRequestInterval(), ArLog::log(), myCameraCollection, ArLog::Normal, ArServerClient::sendPacketTcp(), and ArBasePacket::strToBuf().
Referenced by ArServerHandlerCameraCollection().
void ArServerHandlerCameraCollection::handleCameraCollectionModified ()
Callback executed when the associated camera collection is modified.
References ArServerBase::broadcastPacketTcp(), COLLECTION_UPDATED_PACKET_NAME, and myServer.
Referenced by ArServerHandlerCameraCollection().
void ArServerHandlerCameraCollection::setParams (ArServerClient * client, ArNetPacket * packet)
Handles the request to edit a camera's parameters.
Parameters
client the ArServerClient * that is making the request
packet the ArNetPacket * that contains the request
TODO: Add error message? ArNetPacket retPacket; retPacket->strToBuf(""); client->sendPacketTcp(&retPacket);
References ArClientArg::argValueToBuf(), ArServerBase::broadcastPacketTcp(), ArClientArg::bufToArgValue(), ArBasePacket::bufToStr(), ArConfigArg::getName(), ArCameraCollection::getParameter(), ArLog::log(), myCameraCollection, myServer, PARAMS_UPDATED_PACKET_NAME, ArServerClient::sendPacketTcp(), ArCameraCollection::setParameter(), ArBasePacket::strToBuf(), and ArLog::Verbose.
Referenced by ArServerHandlerCameraCollection().
Member Data Documentation
const char * ArServerHandlerCameraCollection::COLLECTION_UPDATED_PACKET_NAME static protected
Initial value:
=
                        "cameraListUpdated"
Name of the network packet broadcast when the collection is modified.
Referenced by handleCameraCollectionModified().
const char * ArServerHandlerCameraCollection::COMMAND_GROUP static protected
Initial value:
=
                        "CameraInfo"
Command group for these packets.
const char * ArServerHandlerCameraCollection::GET_COLLECTION_PACKET_NAME static protected
Initial value:
=
                        "getCameraList"
Name of the network packet to get the camera list.
ArCameraCollection* ArServerHandlerCameraCollection::myCameraCollection protected
The associated camera collection.
Referenced by getCameraList(), setParams(), and ~ArServerHandlerCameraCollection().
ArFunctor* ArServerHandlerCameraCollection::myCollectionModifiedCB protected
Notification callback when the camera collection has been modified.
Referenced by ~ArServerHandlerCameraCollection().
ArFunctor2<ArServerClient *, ArNetPacket *>* ArServerHandlerCameraCollection::myGetCameraListCB protected
Server callback for the get camera list request.
ArServerBase* ArServerHandlerCameraCollection::myServer protected
The server used to send/receive requests.
Referenced by handleCameraCollectionModified(), and setParams().
ArFunctor2<ArServerClient *, ArNetPacket *>* ArServerHandlerCameraCollection::mySetParamCB protected
Server callback for the set parameter request.
const char * ArServerHandlerCameraCollection::PARAMS_UPDATED_PACKET_NAME static protected
Initial value:
=
                        "cameraParamUpdated"
Name of the network packet broadcast when a parameter value is modified.
Referenced by setParams().
const char * ArServerHandlerCameraCollection::SET_PARAMS_PACKET_NAME static protected
Initial value:
=
                        "setCameraParams"
Name of the network packet to set a particular camera parameter.
The documentation for this class was generated from the following files:
ArServerHandlerCameraCollection.h
ArServerHandlerCameraCollection.cpp