ArNetworking: ArServerFileFromClient Class Reference
ArServerFileFromClient Class Reference
Puts files onto the server.
#include <ArServerFileUtils.h>
Classes
class FileInfo
Public Member Functions
void addPostMoveCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be called after moving from temp dir to final loc.
void addPreMoveCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be called before moving from temp dir to final loc.
ArServerFileFromClient (ArServerBase *server, const char *topDir, const char *tempDir)
Constructor.
const char * getMovingFileName (void)
Internal call for getting the name of the file we're moving.
void putFile (ArServerClient *client, ArNetPacket *packet)
Puts the file.
void putFileInterleaved (ArServerClient *client, ArNetPacket *packet)
Puts the file with interleaved responses.
void putFileWithTimestamp (ArServerClient *client, ArNetPacket *packet)
Puts the file.
void putFileWithTimestampInterleaved (ArServerClient *client, ArNetPacket *packet)
Puts the file with interleaved responses.
void remPostMoveCallback (ArFunctor *functor)
Removes a callback to be called after moving from temp dir to final loc.
void remPreMoveCallback (ArFunctor *functor)
Removes a callback to be called before moving from temp dir to final loc.
virtual ~ArServerFileFromClient ()
Destructor.
Protected Member Functions
void internalPutFile (ArServerClient *client, ArNetPacket *packet, bool interleaved, bool isSetTimestamp)
Protected Attributes
char myBaseDir [2048]
int myFileNumber
std::map< std::string, FileInfo * > myMap
std::string myMovingFileName
std::list< ArFunctor * > myPostMoveCallbacks
std::list< ArFunctor * > myPreMoveCallbacks
ArFunctor2C< ArServerFileFromClient, ArServerClient *, ArNetPacket * > myPutFileCB
ArFunctor2C< ArServerFileFromClient, ArServerClient *, ArNetPacket * > myPutFileInterleavedCB
ArFunctor2C< ArServerFileFromClient, ArServerClient *, ArNetPacket * > myPutFileWithTimestampCB
ArFunctor2C< ArServerFileFromClient, ArServerClient *, ArNetPacket * > myPutFileWithTimestampInterleavedCB
ArServerBase * myServer
char myTempDir [2048]
Detailed Description
Puts files onto the server.
Note
Available on Linux only
This class is set up so that a client can put files on the robot, this class ONLY puts files. This class will take a file from a client, writing it into the tempDir given in the constructor, then after receiving the file it'll move it over to the actual location requested. You should use this class by using ArClientFileFromClient and NOT by using this classes interface directly, this is because the API is and will remain fairly volatile... if you need more functionality let us know and we'll add it if its reasonable.
Constructor & Destructor Documentation
ArServerFileFromClient::ArServerFileFromClient (ArServerBase * server, const char * topDir, const char * tempDir)
Constructor.
References ArServerBase::addData(), ArUtil::appendSlash(), ArUtil::fixSlashes(), myBaseDir, myFileNumber, myPutFileCB, myPutFileInterleavedCB, myPutFileWithTimestampCB, myServer, and myTempDir.
ArServerFileFromClient::~ArServerFileFromClient () virtual
Destructor.
Member Function Documentation
void ArServerFileFromClient::addPostMoveCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback to be called after moving from temp dir to final loc.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myPostMoveCallbacks, and ArLog::Terse.
void ArServerFileFromClient::addPreMoveCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback to be called before moving from temp dir to final loc.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myPreMoveCallbacks, and ArLog::Terse.
const char* ArServerFileFromClient::getMovingFileName (void) inline
Internal call for getting the name of the file we're moving.
void ArServerFileFromClient::internalPutFile (ArServerClient * client, ArNetPacket * packet, bool interleaved, bool isSetTimestamp) protected
References ArUtil::appendSlash(), ArServerBase::broadcastPacketTcp(), ArBasePacket::bufToByte4(), ArBasePacket::bufToData(), ArBasePacket::bufToStr(), ArBasePacket::bufToUByte2(), ArBasePacket::bufToUByte4(), ArUtil::changeFileTimestamp(), client, file, ArUtil::fopen(), ArServerClient::getCreationTime(), ArUtil::getDirectory(), ArUtil::getFileName(), ArServerClient::getIPString(), ArTime::isAt(), ArLog::log(), ArLog::logErrorFromOS(), ArUtil::matchCase(), myBaseDir, ArServerFileFromClient::FileInfo::myClient, ArServerFileFromClient::FileInfo::myClientCreationTime, ArServerFileFromClient::FileInfo::myFile, myFileNumber, ArServerFileFromClient::FileInfo::myFileTimestamp, ArServerFileFromClient::FileInfo::myLastActivity, myMap, myMovingFileName, myPostMoveCallbacks, myPreMoveCallbacks, ArServerFileFromClient::FileInfo::myRealFileName, myServer, ArServerFileFromClient::FileInfo::myStartedTransfer, myTempDir, ArServerFileFromClient::FileInfo::myTempFileName, ArLog::Normal, ArTime::secSince(), ArServerClient::sendPacketTcp(), ArTime::setToNow(), ArUtil::strcasecmp(), ArBasePacket::strToBuf(), ArBasePacket::uByte2ToBuf(), and ArLog::Verbose.
Referenced by putFile(), putFileInterleaved(), putFileWithTimestamp(), and putFileWithTimestampInterleaved().
void ArServerFileFromClient::putFile (ArServerClient * client, ArNetPacket * packet)
Puts the file.
References internalPutFile(), and putFileInterleaved().
void ArServerFileFromClient::putFileInterleaved (ArServerClient * client, ArNetPacket * packet)
Puts the file with interleaved responses.
References internalPutFile(), and putFileWithTimestamp().
Referenced by putFile().
void ArServerFileFromClient::putFileWithTimestamp (ArServerClient * client, ArNetPacket * packet)
Puts the file.
References internalPutFile(), and putFileWithTimestampInterleaved().
Referenced by putFileInterleaved().
void ArServerFileFromClient::putFileWithTimestampInterleaved (ArServerClient * client, ArNetPacket * packet)
Puts the file with interleaved responses.
References internalPutFile().
Referenced by putFileWithTimestamp().
void ArServerFileFromClient::remPostMoveCallback (ArFunctor * functor)
Removes a callback to be called after moving from temp dir to final loc.
References myPostMoveCallbacks.
void ArServerFileFromClient::remPreMoveCallback (ArFunctor * functor)
Removes a callback to be called before moving from temp dir to final loc.
References myPreMoveCallbacks.
Member Data Documentation
char ArServerFileFromClient::myBaseDir[2048] protected
Referenced by ArServerFileFromClient(), and internalPutFile().
int ArServerFileFromClient::myFileNumber protected
Referenced by ArServerFileFromClient(), and internalPutFile().
std::map<std::string, FileInfo *> ArServerFileFromClient::myMap protected
Referenced by internalPutFile().
std::string ArServerFileFromClient::myMovingFileName protected
Referenced by internalPutFile().
std::list<ArFunctor *> ArServerFileFromClient::myPostMoveCallbacks protected
Referenced by addPostMoveCallback(), internalPutFile(), and remPostMoveCallback().
std::list<ArFunctor *> ArServerFileFromClient::myPreMoveCallbacks protected
Referenced by addPreMoveCallback(), internalPutFile(), and remPreMoveCallback().
ArFunctor2C<ArServerFileFromClient, ArServerClient *, ArNetPacket *> ArServerFileFromClient::myPutFileCB protected
Referenced by ArServerFileFromClient().
ArFunctor2C<ArServerFileFromClient, ArServerClient *, ArNetPacket *> ArServerFileFromClient::myPutFileInterleavedCB protected
Referenced by ArServerFileFromClient().
ArFunctor2C<ArServerFileFromClient, ArServerClient *, ArNetPacket *> ArServerFileFromClient::myPutFileWithTimestampCB protected
Referenced by ArServerFileFromClient().
ArFunctor2C<ArServerFileFromClient, ArServerClient *, ArNetPacket *> ArServerFileFromClient::myPutFileWithTimestampInterleavedCB protected
ArServerBase* ArServerFileFromClient::myServer protected
Referenced by ArServerFileFromClient(), and internalPutFile().
char ArServerFileFromClient::myTempDir[2048] protected
Referenced by ArServerFileFromClient(), and internalPutFile().
The documentation for this class was generated from the following files:
ArServerFileUtils.h
ArServerFileUtils.cpp