ArNetworking: ArServerHandlerMap Class Reference
ArServerHandlerMap Class Reference
Service providing the contents of a map file to the client.
#include <ArServerHandlerMap.h>
Public Types
enum DataToSend { LINES = 1, POINTS = 2, BOTH = 3 }
Public Member Functions
ArServerHandlerMap (ArServerBase *server, ArMapInterface *arMap=NULL, DataToSend dataToSend=BOTH)
Constructor.
DataToSend getDataToSend (void)
Gets which kind of data we send.
ArMapInterface * getMap (void)
Gets the map object this is using.
bool loadMap (const char *mapFile)
Loads the map from a file.
void serverGetGoals (ArServerClient *client, ArNetPacket *packet)
The command that'll get the goals.
void serverGetMap (ArServerClient *client, ArNetPacket *packet)
The command that'll get the map itself.
void serverGetMapBinary (ArServerClient *client, ArNetPacket *packet)
The command that gets the map, with the data in binary format for improved performance.
void serverGetMapId (ArServerClient *client, ArNetPacket *packet)
Handles the request for the map ID.
void serverGetMapMultiScans (ArServerClient *client, ArNetPacket *packet)
Requests that the server send the map, including scan data for multiple sources if available.
void serverGetMapName (ArServerClient *client, ArNetPacket *packet)
The command that gets the map name.
void serverGetMapWithMaxCategory (ArServerClient *client, ArNetPacket *packet)
Requests that the server send the map with the specified maximum features.
void setDataToSend (DataToSend dataToSend)
Sets which kind of data we send.
void useMap (ArMapInterface *mapObj, bool takeOwnershipOfMap=false)
Uses a map already loaded.
virtual ~ArServerHandlerMap ()
Destructor.
Protected Member Functions
void handleCheckMap (ArServerClient *client, ArNetPacket *packet)
void mapChanged (void)
bool processFile (void)
void sendMapWithMaxCategory (ArServerClient *client, const char *maxCategory)
void writeLinesToClient (int lineCount, std::vector< ArLineSegment > *points, ArServerClient *client)
void writeMapToClient (const char *line, ArServerClient *client)
void writePointsToClient (int pointCount, std::vector< ArPose > *points, ArServerClient *client)
Protected Attributes
bool myAlreadyLoaded
ArFunctor2C< ArServerHandlerMap, ArServerClient *, ArNetPacket * > myCheckMapCB
DataToSend myDataToSend
ArFunctor2C< ArServerHandlerMap, ArServerClient *, ArNetPacket * > myGetGoalsCB
ArFunctor2C< ArServerHandlerMap, ArServerClient *, ArNetPacket * > myGetMapBinaryCB
ArFunctor2C< ArServerHandlerMap, ArServerClient *, ArNetPacket * > myGetMapCB
ArFunctor2C< ArServerHandlerMap, ArServerClient *, ArNetPacket * > myGetMapIdCB
ArFunctor2C< ArServerHandlerMap, ArServerClient *, ArNetPacket * > myGetMapMaxCategoryCB
ArFunctor2C< ArServerHandlerMap, ArServerClient *, ArNetPacket * > myGetMapMultiScansCB
ArFunctor2C< ArServerHandlerMap, ArServerClient *, ArNetPacket * > myGetMapNameCB
char myLastMapFile [1024]
struct stat myLastMapFileStat
ArMapInterface * myMap
ArFunctorC< ArServerHandlerMap > myMapChangedCB
char myMapFileName [512]
std::string myMapName
bool myOwnMap
ArRetFunctorC< bool, ArServerHandlerMap > myProcessFileCB
ArServerBase * myServer
ArServerHandlerMap * myServerHandlerMap
Detailed Description
Service providing the contents of a map file to the client.
A map can be provided from an ArMap object, or else the filename can be given in the global ArConfig object (see Aria::getConfig()) as "Map" in the "Files" section. This handler can also be configured to only send "point" data, "line" data, or both kinds of data from the map.
This service accepts the following data requests:
getMapId
getMapName
getMap
getGoals
getMapBinary
getMapMultiScans
The following data types will also be broadcast to all clients to indicate certain events:
mapUpdated
goalsUpdated
The getMapId request replies with: a map source identifier (NULL-terminated string); a filename for the map (NULL-terminated string); a checksum value preceded by a 4-byte unsigned integer providing the length (in bytes) of that checksum value; the total data size of the map contents (4-byte unsigned integer); and a timestamp for the map file (last modified, 4-byte signed integer, UNIX time).
The getMapName request replies with a packet containing a NULL-terminated string containing the filename of the map, or an empty string ("") if there is no map.
The getMap request replies with a series of packets each containing one line from the map file (as a null-terminated string), followed by an empty packet signifying the end of the packet. (see the documentation for ArMap for the map file format). This data may be written (with newlines added) to a map file, or may be parsed directly by an empty ArMap object using ArMap::parseLine() and ArMap::parsingComplete(). See tests/mapClient.cpp for an example of usage.
The getGoals request replies with a packet containing a series of NULL-terminated strings containing the names of the Goal objects in the map.
The getMapBinary request replies with the map headers and objects list (see ArMap for map file format) as text, but supplies point "DATA" and/or "LINES" as an undelimited sequence of 2-byte integers. (In the case of point data, each pair of integers is a point; for lines, each sequence of four integers defines a line). This binary representation of data is more compact than the ASCII text representation. This request results in a series of packets, with an empty packet signifying the end of the series.
The getMapMultiScans request is similar to getMapBinary, but it includes a list of the scan sources, along with the point and lines for each scan source in binary format.
The mapUpdated packet is sent to all connected clients whenever a new map is loaded or the map is changed. The packet contains no data; the new map can be downloaded using one of the above requests.
The goalsUpdated packet is sent to all connected clients whenever the list of Goal objects changes in the map or a new map is loaded. The packet contains no data; the new list of goals can be downloaded using getGoals, or by downloading the entire map.
Member Enumeration Documentation
enum ArServerHandlerMap::DataToSend
Enumerator
LINES
POINTS
BOTH
Constructor & Destructor Documentation
ArServerHandlerMap::ArServerHandlerMap (ArServerBase * server, ArMapInterface * arMap = NULL, DataToSend dataToSend = BOTH)
Constructor.
Parameters
server the server to add our data too
arMap If this points to a map file then this will simply serve up that map file and add in a map changed cb for that map, otherwise it'll operate via the Aria::getConfig.
dataToSend Which data to send, just the lines, the points, or both
References ArServerBase::addData(), ArMapInterface::addMapChangedCB(), ArConfig::addParam(), ArConfig::addProcessFileCB(), ArListPos::FIRST, Aria::getConfig(), ArMapInterface::getFileName(), ArPriority::IMPORTANT, myAlreadyLoaded, myCheckMapCB, myGetGoalsCB, myGetMapBinaryCB, myGetMapCB, myGetMapIdCB, myGetMapMaxCategoryCB, myGetMapMultiScansCB, myGetMapNameCB, myMap, myMapChangedCB, myMapFileName, myOwnMap, myProcessFileCB, myServer, setDataToSend(), ArFunctor::setName(), and ArConfig::setSectionComment().
ArServerHandlerMap::~ArServerHandlerMap () virtual
Destructor.
Member Function Documentation
DataToSend ArServerHandlerMap::getDataToSend (void) inline
Gets which kind of data we send.
References handleCheckMap(), mapChanged(), myDataToSend, processFile(), sendMapWithMaxCategory(), writeLinesToClient(), writeMapToClient(), and writePointsToClient().
ArMapInterface * ArServerHandlerMap::getMap (void)
Gets the map object this is using.
References myMap.
void ArServerHandlerMap::handleCheckMap (ArServerClient * client, ArNetPacket * packet) protected
References ArLog::log(), myMap, myOwnMap, ArLog::Normal, processFile(), and ArMapInterface::refresh().
Referenced by getDataToSend().
bool ArServerHandlerMap::loadMap (const char * mapFile)
Loads the map from a file.
References ArServerBase::broadcastPacketTcp(), ArLog::log(), myMap, myMapName, myOwnMap, myServer, ArLog::Normal, and ArMapInterface::readFile().
Referenced by processFile().
void ArServerHandlerMap::mapChanged (void) protected
References ArServerBase::broadcastPacketTcp(), ArMapInterface::getFileName(), ArLog::log(), myMap, myMapFileName, myServer, and ArLog::Normal.
Referenced by getDataToSend().
bool ArServerHandlerMap::processFile (void) protected
References loadMap(), ArLog::log(), myAlreadyLoaded, myLastMapFile, myLastMapFileStat, myMapFileName, ArLog::Normal, and ArLog::Terse.
Referenced by getDataToSend(), and handleCheckMap().
void ArServerHandlerMap::sendMapWithMaxCategory (ArServerClient * client, const char * maxCategory) protected
References BOTH, ArBasePacket::byte4ToBuf(), client, ArNetPacket::empty(), ArMapScanInterface::getLines(), ArMapScanInterface::getPoints(), ArMapInterface::getScanTypes(), LINES, ArMapInterface::lock(), ArLog::log(), myDataToSend, myMap, POINTS, ArServerClient::sendPacketTcp(), ArMapInterface::unlock(), ArLog::Verbose, writeLinesToClient(), ArMapScanInterface::writeLinesToFunctor(), writeMapToClient(), ArMapInterface::writeObjectsToFunctor(), writePointsToClient(), and ArMapScanInterface::writePointsToFunctor().
Referenced by getDataToSend(), serverGetMapMultiScans(), and serverGetMapWithMaxCategory().
void ArServerHandlerMap::serverGetGoals (ArServerClient * client, ArNetPacket * packet)
The command that'll get the goals.
References ArMapObjectsInterface::getMapObjects(), ArMapObject::getName(), ArMapObject::getType(), myMap, ArServerClient::sendPacketTcp(), and ArBasePacket::strToBuf().
void ArServerHandlerMap::serverGetMap (ArServerClient * client, ArNetPacket * packet)
The command that'll get the map itself.
References client, ArMapInterface::lock(), ArLog::log(), myMap, ArServerClient::sendPacketTcp(), ArMapInterface::unlock(), ArLog::Verbose, writeMapToClient(), and ArMapInterface::writeToFunctor().
void ArServerHandlerMap::serverGetMapBinary (ArServerClient * client, ArNetPacket * packet)
The command that gets the map, with the data in binary format for improved performance.
References BOTH, ArBasePacket::byte4ToBuf(), client, ArNetPacket::empty(), ArMapScanInterface::getLines(), ArMapInterface::getScanTypes(), LINES, ArMapInterface::lock(), ArLog::log(), myDataToSend, myMap, ArLog::Normal, POINTS, ArServerClient::sendPacketTcp(), ArMapInterface::unlock(), ArLog::Verbose, writeLinesToClient(), ArMapScanInterface::writeLinesToFunctor(), writeMapToClient(), ArMapInterface::writeObjectsToFunctor(), writePointsToClient(), and ArMapScanInterface::writePointsToFunctor().
Referenced by serverGetMapWithMaxCategory().
void ArServerHandlerMap::serverGetMapId (ArServerClient * client, ArNetPacket * packet)
Handles the request for the map ID.
References ArServerClient::getIPString(), ArMapInterface::getMapId(), ArLog::log(), ArMapId::log(), myMap, ArLog::Normal, ArServerClient::sendPacketTcp(), and ArMapId::toPacket().
void ArServerHandlerMap::serverGetMapMultiScans (ArServerClient * client, ArNetPacket * packet)
Requests that the server send the map, including scan data for multiple sources if available.
References sendMapWithMaxCategory().
void ArServerHandlerMap::serverGetMapName (ArServerClient * client, ArNetPacket * packet)
The command that gets the map name.
References ArMapInterface::getFileName(), myMap, ArServerClient::sendPacketTcp(), and ArBasePacket::strToBuf().
void ArServerHandlerMap::serverGetMapWithMaxCategory (ArServerClient * client, ArNetPacket * packet)
Requests that the server send the map with the specified maximum features.
References ArBasePacket::bufToStr(), ArLog::log(), ArMapInterface::MAP_CATEGORY_2D_EXTENDED, ArLog::Normal, sendMapWithMaxCategory(), serverGetMapBinary(), and ArUtil::strcasecmp().
void ArServerHandlerMap::setDataToSend (DataToSend dataToSend) inline
Sets which kind of data we send.
References myDataToSend.
Referenced by ArServerHandlerMap().
void ArServerHandlerMap::useMap (ArMapInterface * mapObj, bool takeOwnershipOfMap = false)
Uses a map already loaded.
Use the map object given, note that this will not take ownership of the map unless you tell.
References ArServerBase::broadcastPacketTcp(), ArMapInterface::getFileName(), myMap, myMapName, myOwnMap, and myServer.
void ArServerHandlerMap::writeLinesToClient (int lineCount, std::vector< ArLineSegment > * lines, ArServerClient * client) protected
References ArBasePacket::byte4ToBuf(), ArNetPacket::empty(), ArLog::log(), ArMath::roundInt(), ArServerClient::sendPacketTcp(), and ArLog::Verbose.
Referenced by getDataToSend(), sendMapWithMaxCategory(), and serverGetMapBinary().
void ArServerHandlerMap::writeMapToClient (const char * line, ArServerClient * client) protected
References ArServerClient::sendPacketTcp(), and ArBasePacket::strToBuf().
Referenced by getDataToSend(), sendMapWithMaxCategory(), serverGetMap(), and serverGetMapBinary().
void ArServerHandlerMap::writePointsToClient (int pointCount, std::vector< ArPose > * points, ArServerClient * client) protected
References ArBasePacket::byte4ToBuf(), ArNetPacket::empty(), ArLog::log(), ArMath::roundInt(), ArServerClient::sendPacketTcp(), and ArLog::Verbose.
Referenced by getDataToSend(), sendMapWithMaxCategory(), and serverGetMapBinary().
Member Data Documentation
bool ArServerHandlerMap::myAlreadyLoaded protected
Referenced by ArServerHandlerMap(), and processFile().
ArFunctor2C<ArServerHandlerMap, ArServerClient *, ArNetPacket *> ArServerHandlerMap::myCheckMapCB protected
Referenced by ArServerHandlerMap().
DataToSend ArServerHandlerMap::myDataToSend protected
Referenced by getDataToSend(), sendMapWithMaxCategory(), serverGetMapBinary(), and setDataToSend().
ArFunctor2C<ArServerHandlerMap, ArServerClient *, ArNetPacket *> ArServerHandlerMap::myGetGoalsCB protected
Referenced by ArServerHandlerMap().
ArFunctor2C<ArServerHandlerMap, ArServerClient *, ArNetPacket *> ArServerHandlerMap::myGetMapBinaryCB protected
Referenced by ArServerHandlerMap().
ArFunctor2C<ArServerHandlerMap, ArServerClient *, ArNetPacket *> ArServerHandlerMap::myGetMapCB protected
Referenced by ArServerHandlerMap().
ArFunctor2C<ArServerHandlerMap, ArServerClient *, ArNetPacket *> ArServerHandlerMap::myGetMapIdCB protected
Referenced by ArServerHandlerMap().
ArFunctor2C<ArServerHandlerMap, ArServerClient *, ArNetPacket *> ArServerHandlerMap::myGetMapMaxCategoryCB protected
Referenced by ArServerHandlerMap().
ArFunctor2C<ArServerHandlerMap, ArServerClient *, ArNetPacket *> ArServerHandlerMap::myGetMapMultiScansCB protected
Referenced by ArServerHandlerMap().
ArFunctor2C<ArServerHandlerMap, ArServerClient *, ArNetPacket *> ArServerHandlerMap::myGetMapNameCB protected
Referenced by ArServerHandlerMap().
char ArServerHandlerMap::myLastMapFile[1024] protected
Referenced by processFile().
struct stat ArServerHandlerMap::myLastMapFileStat protected
Referenced by processFile().
ArMapInterface* ArServerHandlerMap::myMap protected
Referenced by ArServerHandlerMap(), getMap(), handleCheckMap(), loadMap(), mapChanged(), sendMapWithMaxCategory(), serverGetGoals(), serverGetMap(), serverGetMapBinary(), serverGetMapId(), serverGetMapName(), and useMap().
ArFunctorC<ArServerHandlerMap> ArServerHandlerMap::myMapChangedCB protected
Referenced by ArServerHandlerMap().
char ArServerHandlerMap::myMapFileName[512] protected
Referenced by ArServerHandlerMap(), mapChanged(), and processFile().
std::string ArServerHandlerMap::myMapName protected
Referenced by loadMap(), and useMap().
bool ArServerHandlerMap::myOwnMap protected
Referenced by ArServerHandlerMap(), handleCheckMap(), loadMap(), and useMap().
ArRetFunctorC<bool, ArServerHandlerMap> ArServerHandlerMap::myProcessFileCB protected
Referenced by ArServerHandlerMap().
ArServerBase* ArServerHandlerMap::myServer protected
Referenced by ArServerHandlerMap(), loadMap(), mapChanged(), and useMap().
ArServerHandlerMap* ArServerHandlerMap::myServerHandlerMap protected
The documentation for this class was generated from the following files:
ArServerHandlerMap.h
ArServerHandlerMap.cpp