ArNetworking: ArCentralManager Class Reference
ArCentralManager Class Reference
#include <ArCentralManager.h>
Public Member Functions
virtual void addCycleCallback (ArFunctor *functor, int position=50)
Adds a cycle callback.
virtual void addForwarderAddedCallback (ArFunctor1< ArCentralForwarder * > *functor, int priority=0)
Adds a callback for when a new forwarder is added.
virtual void addForwarderRemovedCallback (ArFunctor1< ArCentralForwarder * > *functor, int priority=0)
Adds a callback for when a new forwarder is destroyed.
ArCentralManager (ArServerBase *robotServer, ArServerBase *clientServer)
Normal constructor.
ArCentralManager ()
Empty constructor for those that'll inherit and do other behavior.
virtual void enforceProtocolVersion (const char *protocolVersion)
Enforces that everything is using this protocol version.
virtual void enforceType (ArServerCommands::Type type)
Enforces that the robots that connect are this type.
void forwarderServerClientRemovedCallback (ArCentralForwarder *forwarder, ArServerClient *client)
A callback so we can tell the main connection happened when a client is removed.
void logConnections (void)
Logs all the connection information.
void mainServerClientRemovedCallback (ArServerClient *client)
A callback so we can close down other connetions when a main client loses connection.
void netClientList (ArServerClient *client, ArNetPacket *packet)
Networking command to get the list of clients.
void netServerSwitch (ArServerClient *client, ArNetPacket *packet)
Networking command to switch the direction of a connection.
virtual void remCycleCallback (ArFunctor *functor)
Removes a cycle callback.
virtual void remForwarderAddedCallback (ArFunctor1< ArCentralForwarder * > *functor)
Removes a callback for when a new forwarder is added.
virtual void remForwarderRemovedCallback (ArFunctor1< ArCentralForwarder * > *functor)
Removes a callback for when a new forwarder is destroyed.
virtual void * runThread (void *arg)
This should be its own thread here.
virtual ~ArCentralManager ()
Destructor.
Public Member Functions inherited from ArASyncTask
ArASyncTask ()
virtual int create (bool joinable=true, bool lowerPriority=true)
virtual const char * getThreadActivity (void)
virtual void run (void)
virtual void runAsync (void)
virtual void * runInThisThread (void *arg=0)
virtual void stopRunning (void)
virtual ~ArASyncTask ()
Public Member Functions inherited from ArThread
ArThread (bool blockAllSignals=true)
ArThread (ThreadType thread, bool joinable, bool blockAllSignals=true)
ArThread (ArFunctor *func, bool joinable=true, bool blockAllSignals=true)
virtual void cancel (void)
virtual int create (ArFunctor *func, bool joinable=true, bool lowerPriority=true)
virtual int detach (void)
bool getBlockAllSignals (void)
virtual ArFunctor * getFunc (void) const
virtual bool getJoinable (void) const
virtual ThreadType getOSThread (void) const
virtual bool getRunning (void) const
virtual bool getRunningWithLock (void)
virtual const ThreadType * getThread (void) const
virtual const char * getThreadName (void)
virtual bool isThreadFinished () const
virtual bool isThreadStarted () const
virtual int join (void **ret=NULL)
int lock (void)
virtual void logThreadInfo (void)
virtual void setRunning (bool running)
virtual void setThreadName (const char *name)
virtual void threadFinished (void)
virtual void threadStarted (void)
int tryLock (void)
int unlock (void)
virtual ~ArThread ()
Protected Member Functions
void close (void)
void forwarderAdded (ArCentralForwarder *forwarder)
void forwarderRemoved (ArCentralForwarder *forwarder)
bool processFile (void)
bool removePendingDuplicateConnections (const char *robotName)
removes pending duplicate connections...
Protected Attributes
ArFunctorC< ArCentralManager > myAriaExitCB
ArMutex myCallbackMutex
double myClientBackupTimeout
std::list< std::string > myClientNames
ArServerBase * myClientServer
std::list< ArSocket * > myClientSockets
ArTypes::UByte4 myClosingConnectionID
ArCallbackList myCycleCBList
ArMutex myDataMutex
std::string myEnforceProtocolVersion
ArServerCommands::Type myEnforceType
std::multimap< int, ArFunctor1< ArCentralForwarder * > * > myForwarderAddedCBList
std::multimap< int, ArFunctor1< ArCentralForwarder * > * > myForwarderRemovedCBList
std::list< ArCentralForwarder * > myForwarders
ArFunctor2C< ArCentralManager, ArCentralForwarder *, ArServerClient * > myForwarderServerClientRemovedCB
double myHeartbeatTimeout
int myLoopMSecs
ArFunctor1C< ArCentralManager, ArServerClient * > myMainServerClientRemovedCB
int myMostClients
int myMostForwarders
ArFunctor2C< ArCentralManager, ArServerClient *, ArNetPacket * > myNetClientListCB
ArFunctor2C< ArCentralManager, ArServerClient *, ArNetPacket * > myNetSwitchCB
int myOnSocket
ArRetFunctorC< bool, ArCentralManager > myProcessFileCB
double myRobotBackupTimeout
ArServerBase * myRobotServer
ArTimeChecker myTimeChecker
double myUdpHeartbeatTimeout
std::map< int, ArTime * > myUsedPorts
Protected Attributes inherited from ArThread
bool myRunning
Additional Inherited Members
Public Types inherited from ArThread
enum Status
Static Public Member Functions inherited from ArThread
static void cancelAll (void)
static ArLog::LogLevel getLogLevel (void)
static ThreadType getThisOSThread (void)
static const ThreadType * getThisThread (void)
static const char * getThisThreadName (void)
static void init (void)
static void joinAll (void)
static ThreadType osSelf (void)
static ArThread * self (void)
static void setLogLevel (ArLog::LogLevel level)
static void shutdown ()
static void stopAll ()
static void yieldProcessor (void)
Public Attributes inherited from ArThread
STATUS_ALREADY_DETATCHED
STATUS_FAILED
STATUS_INVALID
STATUS_JOIN_SELF
STATUS_NO_SUCH_THREAD
STATUS_NORESOURCE
Constructor & Destructor Documentation
ArCentralManager::ArCentralManager (ArServerBase * robotServer, ArServerBase * clientServer)
Normal constructor.
References ArServerBase::addClientRemovedCallback(), ArServerBase::addData(), Aria::addExitCallback(), ArConfig::addParam(), ArConfig::addProcessFileCB(), ArPriority::DETAILED, Aria::getConfig(), myAriaExitCB, myClientBackupTimeout, myClientServer, myClosingConnectionID, myDataMutex, myEnforceType, myForwarderServerClientRemovedCB, myHeartbeatTimeout, myLoopMSecs, myMainServerClientRemovedCB, myMostClients, myMostForwarders, myNetClientListCB, myNetSwitchCB, myProcessFileCB, myRobotBackupTimeout, myRobotServer, myTimeChecker, myUdpHeartbeatTimeout, ArASyncTask::runAsync(), ArTimeChecker::setDefaultMSecs(), ArMutex::setLogName(), ArFunctor::setName(), ArTimeChecker::setName(), ArThread::setThreadName(), and ArServerCommands::TYPE_UNSPECIFIED.
ArCentralManager::ArCentralManager ()
Empty constructor for those that'll inherit and do other behavior.
References Aria::addExitCallback(), myAriaExitCB, myClientServer, myClosingConnectionID, myDataMutex, myEnforceType, myForwarderServerClientRemovedCB, myLoopMSecs, myMainServerClientRemovedCB, myMostClients, myMostForwarders, myRobotServer, myTimeChecker, ArTimeChecker::setDefaultMSecs(), ArMutex::setLogName(), ArFunctor::setName(), ArTimeChecker::setName(), ArThread::setThreadName(), and ArServerCommands::TYPE_UNSPECIFIED.
ArCentralManager::~ArCentralManager () virtual
Destructor.
Member Function Documentation
virtual void ArCentralManager::addCycleCallback (ArFunctor * functor, int position = 50) inline virtual
Adds a cycle callback.
References ArGenericCallbackList< ArFunctor * >::addCallback(), and myCycleCBList.
void ArCentralManager::addForwarderAddedCallback (ArFunctor1< ArCentralForwarder * > * functor, int priority = 0) virtual
Adds a callback for when a new forwarder is added.
References ArMutex::lock(), myCallbackMutex, myForwarderAddedCBList, and ArMutex::unlock().
void ArCentralManager::addForwarderRemovedCallback (ArFunctor1< ArCentralForwarder * > * functor, int priority = 0) virtual
Adds a callback for when a new forwarder is destroyed.
References ArMutex::lock(), myCallbackMutex, myForwarderRemovedCBList, and ArMutex::unlock().
void ArCentralManager::close (void) protected
References ArLog::log(), myForwarderRemovedCBList, myForwarders, and ArLog::Normal.
Referenced by remCycleCallback().
void ArCentralManager::enforceProtocolVersion (const char * protocolVersion) virtual
Enforces that everything is using this protocol version.
Enforces the that the server is using this protocol version.
References ArMutex::lock(), ArLog::log(), myDataMutex, myEnforceProtocolVersion, ArLog::Normal, and ArMutex::unlock().
void ArCentralManager::enforceType (ArServerCommands::Type type) virtual
Enforces that the robots that connect are this type.
References ArMutex::lock(), ArLog::log(), myDataMutex, myEnforceType, ArLog::Normal, ArServerCommands::toString(), and ArMutex::unlock().
void ArCentralManager::forwarderAdded (ArCentralForwarder * forwarder) protected
References ArCentralForwarder::getRobotName(), ArLog::log(), myForwarderAddedCBList, and ArLog::Normal.
Referenced by remCycleCallback(), and runThread().
void ArCentralManager::forwarderRemoved (ArCentralForwarder * forwarder) protected
References ArCentralForwarder::getRobotName(), ArLog::log(), myForwarderRemovedCBList, and ArLog::Normal.
Referenced by remCycleCallback(), and runThread().
void ArCentralManager::forwarderServerClientRemovedCallback (ArCentralForwarder * forwarder, ArServerClient * client)
A callback so we can tell the main connection happened when a client is removed.
References ArServerBase::broadcastPacketTcpToMatching(), ArCentralForwarder::getClient(), ArServerClientIdentifier::getConnectionID(), ArServerClient::getIdentifier(), ArSocket::getIPString(), ArServerClient::getIPString(), ArCentralForwarder::getPort(), ArCentralForwarder::getRobotName(), ArClientBase::getTcpSocket(), ArLog::log(), myClientServer, myClosingConnectionID, ArLog::Normal, and ArBasePacket::strToBuf().
Referenced by remCycleCallback().
void ArCentralManager::logConnections (void)
Logs all the connection information.
References ArServerBase::getNumClients(), ArCentralForwarder::getRobotName(), ArCentralForwarder::getServer(), ArCentralForwarder::isConnected(), ArMutex::lock(), ArLog::log(), ArServerBase::logConnections(), myClientServer, myDataMutex, myForwarders, myMostClients, myMostForwarders, ArLog::Normal, and ArMutex::unlock().
Referenced by remCycleCallback().
void ArCentralManager::mainServerClientRemovedCallback (ArServerClient * client)
A callback so we can close down other connetions when a main client loses connection.
References ArServerBase::closeConnectionID(), ArServerClientIdentifier::getConnectionID(), ArServerClient::getIdentifier(), ArServerClient::getIPString(), ArCentralForwarder::getServer(), ArMutex::lock(), ArLog::log(), myClosingConnectionID, myDataMutex, myForwarders, ArLog::Normal, and ArMutex::unlock().
Referenced by remCycleCallback().
void ArCentralManager::netClientList (ArServerClient * client, ArNetPacket * packet)
Networking command to get the list of clients.
References ArCentralForwarder::getClient(), ArSocket::getIPString(), ArBasePacket::getLength(), ArCentralForwarder::getPort(), ArCentralForwarder::getRobotName(), ArClientBase::getTcpSocket(), ArCentralForwarder::isConnected(), ArMutex::lock(), myDataMutex, myForwarders, ArServerClient::sendPacketTcp(), ArBasePacket::setLength(), ArBasePacket::strToBuf(), ArBasePacket::uByte2ToBuf(), and ArMutex::unlock().
Referenced by remCycleCallback().
void ArCentralManager::netServerSwitch (ArServerClient * client, ArNetPacket * packet)
Networking command to switch the direction of a connection.
acknowledge the switch
References ArBasePacket::bufToStr(), ArServerClient::forceDisconnect(), ArServerClient::getIPString(), ArCentralForwarder::getRobotName(), ArServerClient::getTcpSocket(), ArMutex::lock(), ArLog::log(), myClientNames, myClientSockets, myDataMutex, myForwarders, ArLog::Normal, removePendingDuplicateConnections(), ArServerClient::sendPacketTcp(), ArServerClient::tcpCallback(), ArSocket::transfer(), ArMutex::unlock(), and ArCentralForwarder::willReplace().
Referenced by remCycleCallback().
bool ArCentralManager::processFile (void) protected
References myClientBackupTimeout, myClientServer, and ArServerBase::setBackupTimeout().
Referenced by remCycleCallback().
virtual void ArCentralManager::remCycleCallback (ArFunctor * functor) inline virtual
Removes a cycle callback.
References client, close(), forwarderAdded(), forwarderRemoved(), forwarderServerClientRemovedCallback(), logConnections(), mainServerClientRemovedCallback(), myCycleCBList, netClientList(), netServerSwitch(), processFile(), ArGenericCallbackList< ArFunctor * >::remCallback(), removePendingDuplicateConnections(), and runThread().
void ArCentralManager::remForwarderAddedCallback (ArFunctor1< ArCentralForwarder * > * functor) virtual
Removes a callback for when a new forwarder is added.
References ArMutex::lock(), myCallbackMutex, myForwarderAddedCBList, and ArMutex::unlock().
void ArCentralManager::remForwarderRemovedCallback (ArFunctor1< ArCentralForwarder * > * functor) virtual
Removes a callback for when a new forwarder is destroyed.
References ArMutex::lock(), myCallbackMutex, myForwarderRemovedCBList, and ArMutex::unlock().
bool ArCentralManager::removePendingDuplicateConnections (const char * robotName) protected
removes pending duplicate connections...
has a return since you must call it until it returns false... this is because of the list management
References ArLog::log(), myClientNames, myClientSockets, ArLog::Normal, and ArUtil::strcasecmp().
Referenced by netServerSwitch(), and remCycleCallback().
void * ArCentralManager::runThread (void * arg) virtual
This should be its own thread here.
Implements ArASyncTask.
References ArTime(), ArServerBase::broadcastPacketTcp(), ArCentralForwarder::callOnce(), ArTimeChecker::check(), ArTimeChecker::finish(), forwarderAdded(), forwarderRemoved(), ArCentralForwarder::getClient(), ArSocket::getIPString(), ArServerBase::getNumClients(), ArCentralForwarder::getPort(), ArCentralForwarder::getRobotName(), ArThread::getRunning(), ArCentralForwarder::getServer(), ArServerBase::getTcpPort(), ArClientBase::getTcpSocket(), ArServerBase::internalSetNumClients(), ArCallbackList::invoke(), ArCentralForwarder::isConnected(), ArMutex::lock(), ArLog::log(), myClientBackupTimeout, myClientNames, myClientServer, myClientSockets, myCycleCBList, myDataMutex, myEnforceProtocolVersion, myEnforceType, myForwarders, myForwarderServerClientRemovedCB, myHeartbeatTimeout, myLoopMSecs, myMostClients, myMostForwarders, myRobotBackupTimeout, myRobotServer, myTimeChecker, myUdpHeartbeatTimeout, myUsedPorts, ArLog::Normal, ArTime::setSec(), ArUtil::sleep(), ArTimeChecker::start(), ArBasePacket::strToBuf(), ArThread::threadFinished(), ArThread::threadStarted(), ArBasePacket::uByte2ToBuf(), and ArMutex::unlock().
Referenced by remCycleCallback().
Member Data Documentation
ArFunctorC<ArCentralManager> ArCentralManager::myAriaExitCB protected
Referenced by ArCentralManager().
ArMutex ArCentralManager::myCallbackMutex protected
Referenced by addForwarderAddedCallback(), addForwarderRemovedCallback(), remForwarderAddedCallback(), and remForwarderRemovedCallback().
double ArCentralManager::myClientBackupTimeout protected
Referenced by ArCentralManager(), processFile(), and runThread().
std::list<std::string> ArCentralManager::myClientNames protected
Referenced by netServerSwitch(), removePendingDuplicateConnections(), and runThread().
ArServerBase* ArCentralManager::myClientServer protected
Referenced by ArCentralManager(), forwarderServerClientRemovedCallback(), logConnections(), processFile(), and runThread().
std::list<ArSocket *> ArCentralManager::myClientSockets protected
Referenced by netServerSwitch(), removePendingDuplicateConnections(), and runThread().
ArTypes::UByte4 ArCentralManager::myClosingConnectionID protected
Referenced by ArCentralManager(), forwarderServerClientRemovedCallback(), and mainServerClientRemovedCallback().
ArCallbackList ArCentralManager::myCycleCBList protected
Referenced by addCycleCallback(), remCycleCallback(), and runThread().
ArMutex ArCentralManager::myDataMutex protected
Referenced by ArCentralManager(), enforceProtocolVersion(), enforceType(), logConnections(), mainServerClientRemovedCallback(), netClientList(), netServerSwitch(), and runThread().
std::string ArCentralManager::myEnforceProtocolVersion protected
Referenced by enforceProtocolVersion(), and runThread().
ArServerCommands::Type ArCentralManager::myEnforceType protected
Referenced by ArCentralManager(), enforceType(), and runThread().
std::multimap<int, ArFunctor1<ArCentralForwarder *> *> ArCentralManager::myForwarderAddedCBList protected
Referenced by addForwarderAddedCallback(), forwarderAdded(), and remForwarderAddedCallback().
std::multimap<int, ArFunctor1<ArCentralForwarder *> *> ArCentralManager::myForwarderRemovedCBList protected
Referenced by addForwarderRemovedCallback(), close(), forwarderRemoved(), and remForwarderRemovedCallback().
std::list<ArCentralForwarder *> ArCentralManager::myForwarders protected
Referenced by close(), logConnections(), mainServerClientRemovedCallback(), netClientList(), netServerSwitch(), and runThread().
ArFunctor2C<ArCentralManager, ArCentralForwarder *, ArServerClient *> ArCentralManager::myForwarderServerClientRemovedCB protected
Referenced by ArCentralManager(), and runThread().
double ArCentralManager::myHeartbeatTimeout protected
Referenced by ArCentralManager(), and runThread().
int ArCentralManager::myLoopMSecs protected
Referenced by ArCentralManager(), and runThread().
ArFunctor1C<ArCentralManager, ArServerClient *> ArCentralManager::myMainServerClientRemovedCB protected
Referenced by ArCentralManager().
int ArCentralManager::myMostClients protected
Referenced by ArCentralManager(), logConnections(), and runThread().
int ArCentralManager::myMostForwarders protected
Referenced by ArCentralManager(), logConnections(), and runThread().
ArFunctor2C<ArCentralManager, ArServerClient *, ArNetPacket *> ArCentralManager::myNetClientListCB protected
Referenced by ArCentralManager().
ArFunctor2C<ArCentralManager, ArServerClient *, ArNetPacket *> ArCentralManager::myNetSwitchCB protected
Referenced by ArCentralManager().
int ArCentralManager::myOnSocket protected
ArRetFunctorC<bool, ArCentralManager> ArCentralManager::myProcessFileCB protected
Referenced by ArCentralManager().
double ArCentralManager::myRobotBackupTimeout protected
Referenced by ArCentralManager(), and runThread().
ArServerBase* ArCentralManager::myRobotServer protected
Referenced by ArCentralManager(), and runThread().
ArTimeChecker ArCentralManager::myTimeChecker protected
Referenced by ArCentralManager(), and runThread().
double ArCentralManager::myUdpHeartbeatTimeout protected
Referenced by ArCentralManager(), and runThread().
std::map<int, ArTime *> ArCentralManager::myUsedPorts protected
Referenced by runThread().
The documentation for this class was generated from the following files:
ArCentralManager.h
ArCentralManager.cpp