ArNetworking: ArServerDeleteFileOnServer Class Reference
ArServerDeleteFileOnServer Class Reference
Deletes files from the server.
#include <ArServerFileUtils.h>
Public Member Functions
void addPostDeleteCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be called after moving from temp dir to final loc.
void addPreDeleteCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be called before moving from temp dir to final loc.
ArServerDeleteFileOnServer (ArServerBase *server, const char *topDir)
Constructor.
void deleteFile (ArServerClient *client, ArNetPacket *packet)
Deletes the file.
const char * getDeletingFileName (void)
Gets the filename of the file we're deleting.
void remPostDeleteCallback (ArFunctor *functor)
Removes a callback to be called after moving from temp dir to final loc.
void remPreDeleteCallback (ArFunctor *functor)
Removes a callback to be called before moving from temp dir to final loc.
virtual ~ArServerDeleteFileOnServer ()
Destructor.
Protected Attributes
char myBaseDir [2048]
ArFunctor2C
< ArServerDeleteFileOnServer,
ArServerClient *, ArNetPacket * > myDeleteFileCB
std::string myDeletingFileName
std::list< ArFunctor * > myPostDeleteCallbacks
std::list< ArFunctor * > myPreDeleteCallbacks
ArServerBase * myServer
Detailed Description
Deletes files from the server.
Note:
Linux only
This class is set up so that a client can get delete files on the robot, this class ONLY deletes files. You should use this class by using ArClientDeleteFileOnServer and NOT by using this classes interface directly, this is because the API is and will remain fairly volatile... if you need more functionality let us know and we'll add it if its reasonable.
Constructor & Destructor Documentation
ArServerDeleteFileOnServer::ArServerDeleteFileOnServer (ArServerBase * server, const char * topDir)
Constructor.
References ArServerBase::addData(), ArUtil::appendSlash(), ArUtil::fixSlashes(), myBaseDir, myDeleteFileCB, and myServer.
ArServerDeleteFileOnServer::~ArServerDeleteFileOnServer () [virtual]
Destructor.
Member Function Documentation
void ArServerDeleteFileOnServer::addPostDeleteCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback to be called after moving from temp dir to final loc.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myPostDeleteCallbacks, and ArLog::Terse.
void ArServerDeleteFileOnServer::addPreDeleteCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback to be called before moving from temp dir to final loc.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myPreDeleteCallbacks, and ArLog::Terse.
void ArServerDeleteFileOnServer::deleteFile (ArServerClient * client, ArNetPacket * packet)
Deletes the file.
References ArBasePacket::bufToStr(), ArUtil::fixSlashes(), ArServerClient::getIPString(), ArLog::log(), ArUtil::matchCase(), myBaseDir, myDeletingFileName, myPostDeleteCallbacks, myPreDeleteCallbacks, ArLog::Normal, ArServerClient::sendPacketTcp(), ArBasePacket::strToBuf(), ArBasePacket::uByte2ToBuf(), and ArLog::Verbose.
const char* ArServerDeleteFileOnServer::getDeletingFileName (void) [inline]
Gets the filename of the file we're deleting.
References myDeletingFileName.
void ArServerDeleteFileOnServer::remPostDeleteCallback (ArFunctor * functor)
Removes a callback to be called after moving from temp dir to final loc.
References myPostDeleteCallbacks.
void ArServerDeleteFileOnServer::remPreDeleteCallback (ArFunctor * functor)
Removes a callback to be called before moving from temp dir to final loc.
References myPreDeleteCallbacks.
Member Data Documentation
char ArServerDeleteFileOnServer::myBaseDir[2048] [protected]
Referenced by ArServerDeleteFileOnServer(), and deleteFile().
ArFunctor2C<ArServerDeleteFileOnServer, ArServerClient *, ArNetPacket *> ArServerDeleteFileOnServer::myDeleteFileCB [protected]
Referenced by ArServerDeleteFileOnServer().
std::string ArServerDeleteFileOnServer::myDeletingFileName [protected]
Referenced by deleteFile(), and getDeletingFileName().
std::list<ArFunctor *> ArServerDeleteFileOnServer::myPostDeleteCallbacks [protected]
Referenced by addPostDeleteCallback(), deleteFile(), and remPostDeleteCallback().
std::list<ArFunctor *> ArServerDeleteFileOnServer::myPreDeleteCallbacks [protected]
Referenced by addPreDeleteCallback(), deleteFile(), and remPreDeleteCallback().
ArServerBase* ArServerDeleteFileOnServer::myServer [protected]
Referenced by ArServerDeleteFileOnServer().
The documentation for this class was generated from the following files:
ArServerFileUtils.h
ArServerFileUtils.cpp