ArNetworking: ArServerModeWander Class Reference
ArServerModeWander Class Reference
#include <ArServerModeWander.h>
Public Member Functions
virtual void activate (void)
The function called when the mode is activated.
ArServerModeWander (ArServerBase *server, ArRobot *robot)
virtual void checkDefault (void)
Sees if this wants to become the default mode.
virtual void deactivate (void)
The function called when the mode is deactivated.
virtual ArActionGroup * getActionGroup (void)
This function should return the action group this mode uses.
void netWander (ArServerClient *client, ArNetPacket *packet)
virtual void userTask (void)
The ArMode's user task, don't need one, subclass must provide if needed.
void wander (void)
virtual ~ArServerModeWander ()
Public Member Functions inherited from ArServerMode
virtual void activationDenied (void)
The function called if the mode is not activated because another mode superceded it.
void addActivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is activated.
void addAsDefaultMode (ArListPos::Pos pos=ArListPos::LAST)
Sets this mode to default (so if a mode deactivates it activates this)
void addDeactivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is deactivated.
bool addModeData (const char *name, const char *description, ArFunctor2< ArServerClient *, ArNetPacket * > *functor, const char *argumentDescription, const char *returnDescription, const char *commandGroup=NULL, const char *dataFlags=NULL)
This basically just notes the commands associated with a mode so that clients can know what can and can't happen based on what mode is active/locked/etc.
void addSingleShotDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for when this class is deactivated.
void addSingleShotPostDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for just after the deactivate happens (when the next mode has activated)
ArServerMode (ArRobot *robot, ArServerBase *server, const char *name)
Constructor.
virtual void forceUnlock (void)
This will be called if another mode has to break the lock.
ArTime getActivityTime (void)
Gets the time of our last activity.
const char * getExtendedStatus (void) const
Gets a string representing the extended status of the mode we're in.
const char * getMode (void) const
Gets a string representing the mode we're in.
const char * getName (void) const
Gets the name of the mode we're in.
const char * getStatus (void) const
Gets a string representing the status of the mode we're in.
bool hasSetActivityTime (void)
Gets if we've set our activity time.
void internalSetActivityTime (ArTime time)
Internal call to set the activity time (this is dangerous and shouldn't be used)
bool isActive (void) const
Gets if this mode is active or not.
virtual bool isAutoResumeAfterInterrupt ()
Adds data to the list of this mode's commands.
void lockMode (bool willUnlockIfRequested=false)
Locks this mode in until its unlocked (mode must be the active mode)
void remActivateCallback (ArFunctor *functor)
Removes a callback for when this class is activated.
void remDeactivateCallback (ArFunctor *functor)
Removes a callback for when this class is deactivated.
void remSingleShotDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for when this class is deactivated.
void remSingleShotPostDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for just after the deactivate happens (when the next mode has activated)
virtual void requestUnlock (void)
This will be called if another mode wants the lock broken (can ignore)
void setActivityTimeToNow (void)
Sets that we're active right now.
void setMode (const char *str)
This should only be used by careful people and probably not then.
void setStatus (const char *str)
This should only be used by careful people and probably not then.
void unlockMode (void)
Unlocks the mode so other modes can activate.
virtual ~ArServerMode ()
Destructor.
Protected Attributes
ArFunctor2C< ArServerModeWander, ArServerClient *, ArNetPacket * > myNetWanderCB
ArActionGroupWander myWanderGroup
Protected Attributes inherited from ArServerMode
ArCallbackList myActivateCallbacks
ArTime myActivityTime
ArMutex myActivityTimeMutex
ArCallbackList myDeactivateCallbacks
std::string myExtendedStatus
bool myHasSetActivityTime
bool myIsActive
std::string myMode
std::string myName
ArRobot * myRobot
ArServerBase * myServer
bool mySetActivityThisCycle
ArCallbackList mySingleShotDeactivateCallbacks
ArCallbackList mySingleShotPostDeactivateCallbacks
std::string myStatus
bool myStatusSetThisCycle
ArLog::LogLevel myVerboseLogLevel
Additional Inherited Members
Static Public Member Functions inherited from ArServerMode
static ArServerMode * getActiveMode (void)
Gets the active mode.
static int getActiveModeActivityTimeSecSince (void)
Gets the seconds since the activity of our active mode.
static const char * getActiveModeExtendedStatusString (void)
Gets the active extended status string.
static const char * getActiveModeModeString (void)
Gets the active mode string.
static bool getActiveModeSetActivityThisCycle (void)
Gets if the active mode set the activity time this cycle or not.
static const char * getActiveModeStatusString (void)
Gets the active status string.
static ArServerModeIdle * getIdleMode (void)
Call that gets our idle mode.
static void getModeBusy (ArServerClient *client, ArNetPacket *packet)
Handles the packet request for the mode busy state.
static void getModeDataList (ArServerClient *client, ArNetPacket *packet)
Gets the list of data for each mode.
static void getModeInfo (ArServerClient *client, ArNetPacket *packet)
Gets the info about which mode is active and such.
static bool isLocked (void)
Gets if the active mode is locked or not.
static bool willUnlockIfRequested (void)
Gets whether we'll unlock if requested or not.
Protected Member Functions inherited from ArServerMode
bool baseActivate (bool canSelfActivateIfLocked=false)
Activates this mode if it can (returns true if it can, false otherwise).
void baseDeactivate (void)
Deactivates this mode.
void checkBroadcastModeInfoPacket (void)
ArServerMode * getLastActiveMode ()
Static Protected Member Functions inherited from ArServerMode
static void buildModeInfoPacket (ArNetPacket *packet)
static std::list< ArServerMode * > * getRequestedActivateModes (void)
static void modeUserTask (void)
Static Protected Attributes inherited from ArServerMode
static ArServerMode * ourActiveMode = NULL
static bool ourActiveModeLocked = false
static bool ourActiveModeSetActivityThisCycle = false
static bool ourActiveModeWillUnlockIfRequested = false
static ArServerMode * ourBroadcastActiveMode = NULL
static bool ourBroadcastActiveModeLocked = false
static bool ourBroadcastActiveModeWillUnlockIfRequested = false
static std::list< ArServerMode * > ourDefaultModes
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeBusyCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeDataListCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeInfoCB
static ArServerModeIdle * ourIdleMode = NULL
static bool ourIdleModeCreated = false
static ArMutex ourIdleModeMutex
static bool ourIsBusy = false
static ArServerMode * ourLastActiveMode = NULL
static std::multimap< std::string, std::string > ourModeDataMap
static ArMutex ourModeDataMapMutex
static std::list< ArServerMode * > ourModes
static ArServerMode * ourNextActiveMode = NULL
static std::list< ArServerMode * > ourRequestedActivateModes
static ArServerBase * ourServerBase = NULL
static bool ourUserTaskAdded = false
static ArGlobalFunctor ourUserTaskCB
Detailed Description
Examples:
drawingsExampleWithRobot.cpp, popupExample.cpp, and serverDemo.cpp.
Constructor & Destructor Documentation
ArServerModeWander::ArServerModeWander (ArServerBase * server, ArRobot * robot)
References ArServerMode::addModeData(), ArServerMode::myMode, myNetWanderCB, and ArServerMode::myServer.
ArServerModeWander::~ArServerModeWander () virtual
Member Function Documentation
void ArServerModeWander::activate (void) virtual
The function called when the mode is activated.
Subclasses must implement this, but also call baseActivate().-
Implements ArServerMode.
References ArActionGroup::activateExclusive(), ArServerMode::baseActivate(), ArRobot::clearDirectMotion(), ArServerMode::myRobot, ArServerMode::myStatus, myWanderGroup, and ArServerMode::setActivityTimeToNow().
Referenced by checkDefault(), and wander().
virtual void ArServerModeWander::checkDefault (void) inline virtual
Sees if this wants to become the default mode.
This will be called when there would be no other modes, if this mode wants to take over it should activate itself, if it doesn't want to take over it shouldn't activate
Reimplemented from ArServerMode.
References activate().
void ArServerModeWander::deactivate (void) virtual
The function called when the mode is deactivated.
Subclasses must implement this, and also call baseDeactivate().
Implements ArServerMode.
References ArServerMode::baseDeactivate(), ArActionGroup::deactivate(), and myWanderGroup.
virtual ArActionGroup* ArServerModeWander::getActionGroup (void) inline virtual
This function should return the action group this mode uses.
Reimplemented from ArServerMode.
References myWanderGroup.
void ArServerModeWander::netWander (ArServerClient * client, ArNetPacket * packet)
References ArRobot::lock(), ArLog::log(), ArServerMode::myRobot, ArServerMode::setActivityTimeToNow(), ArRobot::unlock(), ArLog::Verbose, and wander().
void ArServerModeWander::userTask (void) virtual
The ArMode's user task, don't need one, subclass must provide if needed.
Reimplemented from ArServerMode.
References ArRobot::forceTryingToMove(), ArServerMode::myRobot, and ArServerMode::setActivityTimeToNow().
void ArServerModeWander::wander (void)
References activate().
Referenced by netWander().
Member Data Documentation
ArFunctor2C<ArServerModeWander, ArServerClient *, ArNetPacket *> ArServerModeWander::myNetWanderCB protected
Referenced by ArServerModeWander().
ArActionGroupWander ArServerModeWander::myWanderGroup protected
Referenced by activate(), deactivate(), and getActionGroup().
The documentation for this class was generated from the following files:
ArServerModeWander.h
ArServerModeWander.cpp