ArNetworking: ArClientSwitchManager Class Reference
ArClientSwitchManager Class Reference
The serverInfoFile takes the form of a config file roughly, there are 3 things you can put in it now.
#include <ArClientSwitchManager.h>
Public Member Functions
void addConnectedCB (ArFunctor1< const char * > *functor, int position=50)
Adds a callback when we connect.
void addFailedConnectCB (ArFunctor1< const char * > *functor, int position=50)
Adds a callback when we fail to connect.
void addToConfig (const char *configSection, const char *connectName, const char *connectDesc, const char *addressName, const char *addressDesc)
Adds central server or identifier not passed into the config.
ArClientSwitchManager (ArServerBase *serverBase, ArArgumentParser *parser, const char *serverDescription="Central Server", const char *clientSoftwareDescription="Software")
void clientSwitch (ArNetPacket *packet)
The handler for the response to the switch command.
void enforceProtocolVersion (const char *protocolVersion)
Enforces the that the server is using this protocol version.
void enforceType (ArServerCommands::Type type)
Enforces that the robots that connect are this type.
const char * getCentralServerHostName (void)
Gets the hostname we're using for the central server (NULL means we're not trying to sue the central server)
const char * getConfigDisplayHint (void)
Gets the config display hint items dependent on the central server should use (still check getCentralServerHostName to see if it's being used)
bool getDebugLogging (void)
Gets if this is using debug logging.
const char * getIdentifier (void)
Gets the identifier we're using.
ArServerClient * getServerClient (void)
Gets the server client the forwarder is using (internal)
bool isConnected (void)
Returns if we're connected or not.
void logOptions (void) const
Log the options the simple connector has.
void netCentralHeartbeat (ArServerClient *client, ArNetPacket *packet)
The handler for the packet to let the server know we're still talking to it.
void netCentralServerHeartbeat (ArServerClient *client, ArNetPacket *packet)
The handler for the packet that comes from the server so we know we're getting these.
bool parseArgs (void)
Function to parse the arguments given in the constructor.
bool parseFile (const char *fileName)
Parses the file for holding the user, password, and server key.
void remConnectedCB (ArFunctor1< const char * > *functor)
Removes a callback when we connect.
void remFailedConnectCB (ArFunctor1< const char * > *functor)
Removes a callback when we fail to connect.
virtual void * runThread (void *arg)
void setDebugLogging (bool debugLogging=false)
Sets debug logging.
void setIdentifier (const char *identifier)
Sets the identifier we're using.
virtual ~ArClientSwitchManager ()
Public Member Functions inherited from ArASyncTask
ArASyncTask ()
virtual int create (bool joinable=true, bool lowerPriority=true)
virtual const char * getThreadActivity (void)
virtual void run (void)
virtual void runAsync (void)
virtual void * runInThisThread (void *arg=0)
virtual void stopRunning (void)
virtual ~ArASyncTask ()
Public Member Functions inherited from ArThread
ArThread (bool blockAllSignals=true)
ArThread (ThreadType thread, bool joinable, bool blockAllSignals=true)
ArThread (ArFunctor *func, bool joinable=true, bool blockAllSignals=true)
virtual void cancel (void)
virtual int create (ArFunctor *func, bool joinable=true, bool lowerPriority=true)
virtual int detach (void)
bool getBlockAllSignals (void)
virtual ArFunctor * getFunc (void) const
virtual bool getJoinable (void) const
virtual ThreadType getOSThread (void) const
virtual bool getRunning (void) const
virtual bool getRunningWithLock (void)
virtual const ThreadType * getThread (void) const
virtual const char * getThreadName (void)
virtual bool isThreadFinished () const
virtual bool isThreadStarted () const
virtual int join (void **ret=NULL)
int lock (void)
virtual void logThreadInfo (void)
virtual void setRunning (bool running)
virtual void setThreadName (const char *name)
virtual void threadFinished (void)
virtual void threadStarted (void)
int tryLock (void)
int unlock (void)
virtual ~ArThread ()
Protected Types
enum State {
IDLE, TRYING_CONNECTION, CONNECTING, CONNECTED,
LOST_CONNECTION
}
Protected Member Functions
bool filePasswordCallback (ArArgumentBuilder *arg)
bool fileServerKeyCallback (ArArgumentBuilder *arg)
bool fileUserCallback (ArArgumentBuilder *arg)
bool processFile (void)
void socketClosed (void)
void switchState (State state)
Protected Attributes
std::string myCentralServer
int myCentralServerPort
ArClientBase * myClient
std::string myClientSoftwareDesc
char myConfigCentralServer [1024]
bool myConfigConnectToCentralServer
std::string myConfigDisplayHint
bool myConfigFirstProcess
char myConfigIdentifier [1024]
ArCallbackList1< const char * > myConnectedCBList
ArMutex myDataMutex
bool myDebugLogging
std::string myEnforceProtocolVersion
ArServerCommands::Type myEnforceType
ArCallbackList1< const char * > myFailedConnectCBList
ArFileParser myFileParser
ArRetFunctor1C< bool, ArClientSwitchManager, ArArgumentBuilder * > myFilePasswordCB
ArRetFunctor1C< bool, ArClientSwitchManager, ArArgumentBuilder * > myFileServerKeyCB
ArRetFunctor1C< bool, ArClientSwitchManager, ArArgumentBuilder * > myFileUserCB
std::string myIdentifier
ArTime myLastConnectionAttempt
ArTime myLastTcpHeartbeat
ArTime myLastUdpHeartbeat
ArConstFunctorC< ArClientSwitchManager > myLogOptionsCB
ArFunctor2C< ArClientSwitchManager, ArServerClient *, ArNetPacket * > myNetCentralHeartbeatCB
ArFunctor2C< ArClientSwitchManager, ArServerClient *, ArNetPacket * > myNetCentralServerHeartbeatCB
ArRetFunctorC< bool, ArClientSwitchManager > myParseArgsCB
ArArgumentParser * myParser
std::string myPassword
ArRetFunctorC< bool, ArClientSwitchManager > myProcessFileCB
ArServerBase * myServer
double myServerBackupTimeout
ArServerClient * myServerClient
std::string myServerDesc
bool myServerHasHeartbeat
double myServerHeartbeatTimeout
std::string myServerKey
double myServerUdpHeartbeatTimeout
ArFunctorC< ArClientSwitchManager > mySocketClosedCB
ArTime myStartedState
State myState
ArFunctor1C< ArClientSwitchManager, ArNetPacket * > mySwitchCB
bool myTryConnection
std::string myUser
Protected Attributes inherited from ArThread
bool myRunning
Additional Inherited Members
Public Types inherited from ArThread
enum Status
Static Public Member Functions inherited from ArThread
static void cancelAll (void)
static ArLog::LogLevel getLogLevel (void)
static ThreadType getThisOSThread (void)
static const ThreadType * getThisThread (void)
static const char * getThisThreadName (void)
static void init (void)
static void joinAll (void)
static ThreadType osSelf (void)
static ArThread * self (void)
static void setLogLevel (ArLog::LogLevel level)
static void shutdown ()
static void stopAll ()
static void yieldProcessor (void)
Public Attributes inherited from ArThread
STATUS_ALREADY_DETATCHED
STATUS_FAILED
STATUS_INVALID
STATUS_JOIN_SELF
STATUS_NO_SUCH_THREAD
STATUS_NORESOURCE
Detailed Description
The serverInfoFile takes the form of a config file roughly, there are 3 things you can put in it now.
'user user', 'password password' and 'serverKey serverKey'. Note that it loads these files sequentially so if you pass it 5 files it'll read them in the order they were passed in. If you give it just the keyword but not the value (ie 'user') then it'll clear out that value.
Some program command line options can be used to configure this class:
ArClientSwitchManager options:
-centralServer <host>
-cs <host>
-centralServerPort <port>
-csp <port>
-identifier <identifier>
-id <identifier>
-centralServerInfoFile <fileName>
Examples:
serverDemo.cpp.
Member Enumeration Documentation
enum ArClientSwitchManager::State protected
Enumerator
IDLE
Don't want to connect.
TRYING_CONNECTION
If we're trying to connect.
CONNECTING
If we're waiting for the response from the server.
CONNECTED
If we're connected.
LOST_CONNECTION
If we lost a connection... wait a bit and try again.
Constructor & Destructor Documentation
ArClientSwitchManager::ArClientSwitchManager (ArServerBase * serverBase, ArArgumentParser * parser, const char * serverDescription = "Central Server", const char * clientSoftwareDescription = "Software")
References ArServerBase::addData(), ArFileParser::addHandler(), Aria::addLogOptionsCB(), ArConfig::addParam(), Aria::addParseArgsCB(), ArConfig::addProcessFileCB(), ArPriority::DETAILED, Aria::getConfig(), IDLE, myCentralServerPort, myClient, myClientSoftwareDesc, myConfigCentralServer, myConfigConnectToCentralServer, myConfigFirstProcess, myConfigIdentifier, myFileParser, myFilePasswordCB, myFileServerKeyCB, myFileUserCB, myLogOptionsCB, myNetCentralHeartbeatCB, myNetCentralServerHeartbeatCB, myParseArgsCB, myParser, myProcessFileCB, myServer, myServerBackupTimeout, myServerClient, myServerDesc, myServerHeartbeatTimeout, myServerUdpHeartbeatTimeout, mySwitchCB, ArFunctor::setName(), ArThread::setThreadName(), and switchState().
ArClientSwitchManager::~ArClientSwitchManager () virtual
Member Function Documentation
void ArClientSwitchManager::addConnectedCB (ArFunctor1< const char * > * functor, int position = 50) inline
Adds a callback when we connect.
References ArGenericCallbackList< GenericFunctor >::addCallback(), and myConnectedCBList.
void ArClientSwitchManager::addFailedConnectCB (ArFunctor1< const char * > * functor, int position = 50) inline
Adds a callback when we fail to connect.
References ArGenericCallbackList< GenericFunctor >::addCallback(), and myFailedConnectCBList.
void ArClientSwitchManager::addToConfig (const char * configSection, const char * connectName, const char * connectDesc, const char * addressName, const char * addressDesc)
Adds central server or identifier not passed into the config.
References ArConfig::addParam(), ArPriority::ADVANCED, ArPriority::CALIBRATION, Aria::getConfig(), getConfigDisplayHint(), myCentralServer, myConfigCentralServer, myConfigConnectToCentralServer, myConfigDisplayHint, myConfigFirstProcess, myConfigIdentifier, and myIdentifier.
Referenced by getServerClient().
void ArClientSwitchManager::clientSwitch (ArNetPacket * packet)
The handler for the response to the switch command.
References CONNECTED, ArServerClient::getTcpSocket(), ArClientBase::getTcpSocket(), ArCallbackList1< P1 >::invoke(), ArLog::log(), ArServerBase::makeNewServerClientFromSocket(), myCentralServer, myClient, myConnectedCBList, myLastTcpHeartbeat, myLastUdpHeartbeat, myServer, myServerBackupTimeout, myServerClient, myServerDesc, mySocketClosedCB, ArLog::Normal, ArServerClient::setBackupTimeout(), ArSocket::setCloseCallback(), ArTime::setToNow(), switchState(), and ArSocket::transfer().
Referenced by getConfigDisplayHint().
void ArClientSwitchManager::enforceProtocolVersion (const char * protocolVersion)
Enforces the that the server is using this protocol version.
References ArMutex::lock(), ArLog::log(), myDataMutex, myEnforceProtocolVersion, ArLog::Normal, and ArMutex::unlock().
Referenced by setIdentifier().
void ArClientSwitchManager::enforceType (ArServerCommands::Type type)
Enforces that the robots that connect are this type.
References ArMutex::lock(), ArLog::log(), myDataMutex, myEnforceType, ArLog::Normal, ArServerCommands::toString(), and ArMutex::unlock().
Referenced by setIdentifier().
bool ArClientSwitchManager::filePasswordCallback (ArArgumentBuilder * arg) protected
References ArArgumentBuilder::getArg(), ArArgumentBuilder::getArgc(), ArArgumentBuilder::getExtraString(), ArArgumentBuilder::getFullString(), ArLog::log(), myPassword, and ArLog::Normal.
bool ArClientSwitchManager::fileServerKeyCallback (ArArgumentBuilder * arg) protected
References ArArgumentBuilder::getArg(), ArArgumentBuilder::getArgc(), ArArgumentBuilder::getExtraString(), ArArgumentBuilder::getFullString(), ArLog::log(), myServerKey, and ArLog::Normal.
bool ArClientSwitchManager::fileUserCallback (ArArgumentBuilder * arg) protected
References ArArgumentBuilder::getArg(), ArArgumentBuilder::getArgc(), ArArgumentBuilder::getExtraString(), ArArgumentBuilder::getFullString(), ArLog::log(), myUser, and ArLog::Normal.
const char * ArClientSwitchManager::getCentralServerHostName (void)
Gets the hostname we're using for the central server (NULL means we're not trying to sue the central server)
References myCentralServer.
Referenced by ArMapChanger::ArMapChanger().
const char* ArClientSwitchManager::getConfigDisplayHint (void) inline
Gets the config display hint items dependent on the central server should use (still check getCentralServerHostName to see if it's being used)
References client, clientSwitch(), myConfigDisplayHint, netCentralHeartbeat(), netCentralServerHeartbeat(), parseFile(), and runThread().
Referenced by addToConfig().
bool ArClientSwitchManager::getDebugLogging (void) inline
Gets if this is using debug logging.
References myDebugLogging.
const char * ArClientSwitchManager::getIdentifier (void)
Gets the identifier we're using.
References myIdentifier.
Referenced by ArMapChanger::sendRobotMapChanges().
ArServerClient* ArClientSwitchManager::getServerClient (void) inline
Gets the server client the forwarder is using (internal)
References addToConfig(), and myServerClient.
Referenced by ArMapChanger::sendRobotMapChanges(), and ArMapChanger::sendRobotPacketList().
bool ArClientSwitchManager::isConnected (void)
Returns if we're connected or not.
References CONNECTED, and myState.
void ArClientSwitchManager::logOptions (void) const
Log the options the simple connector has.
References ArLog::log(), and ArLog::Terse.
void ArClientSwitchManager::netCentralHeartbeat (ArServerClient * client, ArNetPacket * packet)
The handler for the packet to let the server know we're still talking to it.
References ArServerClient::sendPacketTcp(), and ArServerClient::sendPacketUdp().
Referenced by getConfigDisplayHint().
void ArClientSwitchManager::netCentralServerHeartbeat (ArServerClient * client, ArNetPacket * packet)
The handler for the packet that comes from the server so we know we're getting these.
References ArServerClient::getIPString(), ArNetPacket::getPacketSource(), ArMutex::lock(), ArLog::log(), myDataMutex, myLastTcpHeartbeat, myLastUdpHeartbeat, myServerClient, ArLog::Normal, ArTime::setToNow(), ArNetPacket::TCP, ArNetPacket::UDP, and ArMutex::unlock().
Referenced by getConfigDisplayHint().
bool ArClientSwitchManager::parseArgs (void)
Function to parse the arguments given in the constructor.
References ArArgumentParser::checkParameterArgumentInteger(), ArArgumentParser::checkParameterArgumentString(), ArArgumentParser::getWasReallySetOnlyTrue(), ArMutex::lock(), myCentralServer, myCentralServerPort, myDataMutex, myIdentifier, myParser, myState, parseFile(), ArArgumentParser::setWasReallySetOnlyTrue(), TRYING_CONNECTION, and ArMutex::unlock().
bool ArClientSwitchManager::parseFile (const char * fileName)
Parses the file for holding the user, password, and server key.
References ArLog::log(), myFileParser, ArLog::Normal, and ArFileParser::parseFile().
Referenced by getConfigDisplayHint(), and parseArgs().
bool ArClientSwitchManager::processFile (void) protected
References ArMutex::lock(), myCentralServer, myConfigCentralServer, myConfigConnectToCentralServer, myConfigFirstProcess, myConfigIdentifier, myDataMutex, myIdentifier, myServerBackupTimeout, myServerClient, myState, ArServerClient::setBackupTimeout(), TRYING_CONNECTION, and ArMutex::unlock().
void ArClientSwitchManager::remConnectedCB (ArFunctor1< const char * > * functor) inline
Removes a callback when we connect.
References myConnectedCBList, ArGenericCallbackList< GenericFunctor >::remCallback(), and socketClosed().
void ArClientSwitchManager::remFailedConnectCB (ArFunctor1< const char * > * functor) inline
Removes a callback when we fail to connect.
References myFailedConnectCBList, and ArGenericCallbackList< GenericFunctor >::remCallback().
void * ArClientSwitchManager::runThread (void * arg) virtual
added this to try and eliminate the occasional duplicates
Implements ArASyncTask.
References ArSocket::close(), CONNECTED, CONNECTING, ArServerClient::forceDisconnect(), ArServerBase::getOpenOnIP(), ArThread::getRunning(), ArClientBase::getTcpSocket(), IDLE, ArCallbackList1< P1 >::invoke(), ArServerClient::isTcpOnly(), ArMutex::lock(), ArLog::log(), ArClientBase::loopOnce(), LOST_CONNECTION, myCentralServer, myCentralServerPort, myClient, myClientSoftwareDesc, myDataMutex, myDebugLogging, myEnforceProtocolVersion, myEnforceType, myFailedConnectCBList, myIdentifier, myLastConnectionAttempt, myLastTcpHeartbeat, myLastUdpHeartbeat, myPassword, myServer, myServerClient, myServerDesc, myServerHasHeartbeat, myServerHeartbeatTimeout, myServerKey, myServerUdpHeartbeatTimeout, myStartedState, myState, mySwitchCB, myUser, ArLog::Normal, ArTime::secSince(), ArClientBase::setRobotName(), ArTime::setToNow(), ArUtil::sleep(), ArBasePacket::strToBuf(), switchState(), ArThread::threadFinished(), ArThread::threadStarted(), ArServerCommands::toString(), TRYING_CONNECTION, ArMutex::unlock(), ArServerClient::useTcpOnly(), and ArLog::Verbose.
Referenced by getConfigDisplayHint().
void ArClientSwitchManager::setDebugLogging (bool debugLogging = false) inline
Sets debug logging.
References myDebugLogging.
void ArClientSwitchManager::setIdentifier (const char * identifier) inline
Sets the identifier we're using.
References enforceProtocolVersion(), enforceType(), and myIdentifier.
void ArClientSwitchManager::socketClosed (void) protected
References CONNECTED, ArCallbackList1< P1 >::invoke(), ArMutex::lock(), ArLog::log(), LOST_CONNECTION, myCentralServer, myDataMutex, myFailedConnectCBList, myServerClient, myServerDesc, myState, ArLog::Normal, switchState(), and ArMutex::unlock().
Referenced by remConnectedCB().
void ArClientSwitchManager::switchState (State state) protected
References myStartedState, myState, and ArTime::setToNow().
Referenced by ArClientSwitchManager(), clientSwitch(), runThread(), and socketClosed().
Member Data Documentation
std::string ArClientSwitchManager::myCentralServer protected
Referenced by addToConfig(), clientSwitch(), getCentralServerHostName(), parseArgs(), processFile(), runThread(), and socketClosed().
int ArClientSwitchManager::myCentralServerPort protected
Referenced by ArClientSwitchManager(), parseArgs(), and runThread().
ArClientBase* ArClientSwitchManager::myClient protected
Referenced by ArClientSwitchManager(), clientSwitch(), and runThread().
std::string ArClientSwitchManager::myClientSoftwareDesc protected
Referenced by ArClientSwitchManager(), and runThread().
char ArClientSwitchManager::myConfigCentralServer[1024] protected
Referenced by addToConfig(), ArClientSwitchManager(), and processFile().
bool ArClientSwitchManager::myConfigConnectToCentralServer protected
Referenced by addToConfig(), ArClientSwitchManager(), and processFile().
std::string ArClientSwitchManager::myConfigDisplayHint protected
Referenced by addToConfig(), and getConfigDisplayHint().
bool ArClientSwitchManager::myConfigFirstProcess protected
Referenced by addToConfig(), ArClientSwitchManager(), and processFile().
char ArClientSwitchManager::myConfigIdentifier[1024] protected
Referenced by addToConfig(), ArClientSwitchManager(), and processFile().
ArCallbackList1<const char *> ArClientSwitchManager::myConnectedCBList protected
Referenced by addConnectedCB(), clientSwitch(), and remConnectedCB().
ArMutex ArClientSwitchManager::myDataMutex protected
Referenced by enforceProtocolVersion(), enforceType(), netCentralServerHeartbeat(), parseArgs(), processFile(), runThread(), and socketClosed().
bool ArClientSwitchManager::myDebugLogging protected
Referenced by getDebugLogging(), runThread(), and setDebugLogging().
std::string ArClientSwitchManager::myEnforceProtocolVersion protected
Referenced by enforceProtocolVersion(), and runThread().
ArServerCommands::Type ArClientSwitchManager::myEnforceType protected
Referenced by enforceType(), and runThread().
ArCallbackList1<const char *> ArClientSwitchManager::myFailedConnectCBList protected
Referenced by addFailedConnectCB(), remFailedConnectCB(), runThread(), and socketClosed().
ArFileParser ArClientSwitchManager::myFileParser protected
Referenced by ArClientSwitchManager(), and parseFile().
ArRetFunctor1C<bool, ArClientSwitchManager, ArArgumentBuilder *> ArClientSwitchManager::myFilePasswordCB protected
Referenced by ArClientSwitchManager().
ArRetFunctor1C<bool, ArClientSwitchManager, ArArgumentBuilder *> ArClientSwitchManager::myFileServerKeyCB protected
Referenced by ArClientSwitchManager().
ArRetFunctor1C<bool, ArClientSwitchManager, ArArgumentBuilder *> ArClientSwitchManager::myFileUserCB protected
Referenced by ArClientSwitchManager().
std::string ArClientSwitchManager::myIdentifier protected
Referenced by addToConfig(), getIdentifier(), parseArgs(), processFile(), runThread(), and setIdentifier().
ArTime ArClientSwitchManager::myLastConnectionAttempt protected
Referenced by runThread().
ArTime ArClientSwitchManager::myLastTcpHeartbeat protected
Referenced by clientSwitch(), netCentralServerHeartbeat(), and runThread().
ArTime ArClientSwitchManager::myLastUdpHeartbeat protected
Referenced by clientSwitch(), netCentralServerHeartbeat(), and runThread().
ArConstFunctorC<ArClientSwitchManager> ArClientSwitchManager::myLogOptionsCB protected
Referenced by ArClientSwitchManager().
ArFunctor2C<ArClientSwitchManager, ArServerClient *, ArNetPacket *> ArClientSwitchManager::myNetCentralHeartbeatCB protected
Referenced by ArClientSwitchManager().
ArFunctor2C<ArClientSwitchManager, ArServerClient *, ArNetPacket *> ArClientSwitchManager::myNetCentralServerHeartbeatCB protected
Referenced by ArClientSwitchManager().
ArRetFunctorC<bool, ArClientSwitchManager> ArClientSwitchManager::myParseArgsCB protected
Referenced by ArClientSwitchManager().
ArArgumentParser* ArClientSwitchManager::myParser protected
Referenced by ArClientSwitchManager(), and parseArgs().
std::string ArClientSwitchManager::myPassword protected
Referenced by filePasswordCallback(), and runThread().
ArRetFunctorC<bool, ArClientSwitchManager> ArClientSwitchManager::myProcessFileCB protected
Referenced by ArClientSwitchManager().
ArServerBase* ArClientSwitchManager::myServer protected
Referenced by ArClientSwitchManager(), clientSwitch(), and runThread().
double ArClientSwitchManager::myServerBackupTimeout protected
Referenced by ArClientSwitchManager(), clientSwitch(), and processFile().
ArServerClient* ArClientSwitchManager::myServerClient protected
Referenced by ArClientSwitchManager(), clientSwitch(), getServerClient(), netCentralServerHeartbeat(), processFile(), runThread(), and socketClosed().
std::string ArClientSwitchManager::myServerDesc protected
Referenced by ArClientSwitchManager(), clientSwitch(), runThread(), and socketClosed().
bool ArClientSwitchManager::myServerHasHeartbeat protected
Referenced by runThread().
double ArClientSwitchManager::myServerHeartbeatTimeout protected
Referenced by ArClientSwitchManager(), and runThread().
std::string ArClientSwitchManager::myServerKey protected
Referenced by fileServerKeyCallback(), and runThread().
double ArClientSwitchManager::myServerUdpHeartbeatTimeout protected
Referenced by ArClientSwitchManager(), and runThread().
ArFunctorC<ArClientSwitchManager> ArClientSwitchManager::mySocketClosedCB protected
Referenced by clientSwitch().
ArTime ArClientSwitchManager::myStartedState protected
Referenced by runThread(), and switchState().
State ArClientSwitchManager::myState protected
Referenced by isConnected(), parseArgs(), processFile(), runThread(), socketClosed(), and switchState().
ArFunctor1C<ArClientSwitchManager, ArNetPacket *> ArClientSwitchManager::mySwitchCB protected
Referenced by ArClientSwitchManager(), and runThread().
bool ArClientSwitchManager::myTryConnection protected
std::string ArClientSwitchManager::myUser protected
Referenced by fileUserCallback(), and runThread().
The documentation for this class was generated from the following files:
ArClientSwitchManager.h
ArClientSwitchManager.cpp