ArNetworking: ArServerModeDrive Class Reference
ArServerModeDrive Class Reference
#include <ArServerModeDrive.h>
Public Member Functions
virtual void activate (void)
The function called when the mode is activated.
void addControlCommands (ArServerHandlerCommands *handlerCommands)
This adds commands that'll let you disable and enable safe driving.
ArServerModeDrive (ArServerBase *server, ArRobot *robot, bool takeControlOnJoystick=false)
virtual void deactivate (void)
The function called when the mode is deactivated.
void driveJoystick (double vel, double rotVel, bool isActivating=true)
virtual ArActionGroup * getActionGroup (void)
This function should return the action group this mode uses.
bool getSafeDriving (void)
void serverDriveJoystick (ArServerClient *client, ArNetPacket *packet)
void setExtraUnsafeAction (ArAction *action)
this action will be activated in unsafe mode
void setSafeDriving (bool safe)
void setThrottleParams (int lowSpeed, int highSpeed)
virtual void userTask (void)
The ArMode's user task, don't need one, subclass must provide if needed.
virtual ~ArServerModeDrive ()
Public Member Functions inherited from ArServerMode
virtual void activationDenied (void)
The function called if the mode is not activated because another mode superceded it.
void addActivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is activated.
void addAsDefaultMode (ArListPos::Pos pos=ArListPos::LAST)
Sets this mode to default (so if a mode deactivates it activates this)
void addDeactivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is deactivated.
bool addModeData (const char *name, const char *description, ArFunctor2< ArServerClient *, ArNetPacket * > *functor, const char *argumentDescription, const char *returnDescription, const char *commandGroup=NULL, const char *dataFlags=NULL)
This basically just notes the commands associated with a mode so that clients can know what can and can't happen based on what mode is active/locked/etc.
void addSingleShotDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for when this class is deactivated.
void addSingleShotPostDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for just after the deactivate happens (when the next mode has activated)
ArServerMode (ArRobot *robot, ArServerBase *server, const char *name)
Constructor.
virtual void checkDefault (void)
Sees if this wants to become the default mode.
virtual void forceUnlock (void)
This will be called if another mode has to break the lock.
ArTime getActivityTime (void)
Gets the time of our last activity.
const char * getExtendedStatus (void) const
Gets a string representing the extended status of the mode we're in.
const char * getMode (void) const
Gets a string representing the mode we're in.
const char * getName (void) const
Gets the name of the mode we're in.
const char * getStatus (void) const
Gets a string representing the status of the mode we're in.
bool hasSetActivityTime (void)
Gets if we've set our activity time.
void internalSetActivityTime (ArTime time)
Internal call to set the activity time (this is dangerous and shouldn't be used)
bool isActive (void) const
Gets if this mode is active or not.
virtual bool isAutoResumeAfterInterrupt ()
Adds data to the list of this mode's commands.
void lockMode (bool willUnlockIfRequested=false)
Locks this mode in until its unlocked (mode must be the active mode)
void remActivateCallback (ArFunctor *functor)
Removes a callback for when this class is activated.
void remDeactivateCallback (ArFunctor *functor)
Removes a callback for when this class is deactivated.
void remSingleShotDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for when this class is deactivated.
void remSingleShotPostDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for just after the deactivate happens (when the next mode has activated)
virtual void requestUnlock (void)
This will be called if another mode wants the lock broken (can ignore)
void setActivityTimeToNow (void)
Sets that we're active right now.
void setMode (const char *str)
This should only be used by careful people and probably not then.
void setStatus (const char *str)
This should only be used by careful people and probably not then.
void unlockMode (void)
Unlocks the mode so other modes can activate.
virtual ~ArServerMode ()
Destructor.
Protected Member Functions
void joyUserTask (void)
void serverSafeDrivingDisable (void)
void serverSafeDrivingEnable (void)
Protected Member Functions inherited from ArServerMode
bool baseActivate (bool canSelfActivateIfLocked=false)
Activates this mode if it can (returns true if it can, false otherwise).
void baseDeactivate (void)
Deactivates this mode.
void checkBroadcastModeInfoPacket (void)
ArServerMode * getLastActiveMode ()
Protected Attributes
ArActionGroupInput myDriveGroup
bool myDriveSafely
ArAction * myExtraUnsafeAction
ArServerHandlerCommands * myHandlerCommands
ArActionInput * myInputAction
ArActionJoydrive myJoydriveAction
ArJoyHandler * myJoyHandler
ArFunctorC< ArServerModeDrive > myJoyUserTaskCB
bool myNewDriveSafely
double myRotVel
ArFunctor2C< ArServerModeDrive, ArServerClient *, ArNetPacket * > myServerDriveJoystickCB
ArFunctorC< ArServerModeDrive > myServerSafeDrivingDisableCB
ArFunctorC< ArServerModeDrive > myServerSafeDrivingEnableCB
ArActionStop myStopAction
bool myTakeControlOnJoystick
double myVel
Protected Attributes inherited from ArServerMode
ArCallbackList myActivateCallbacks
ArTime myActivityTime
ArMutex myActivityTimeMutex
ArCallbackList myDeactivateCallbacks
std::string myExtendedStatus
bool myHasSetActivityTime
bool myIsActive
std::string myMode
std::string myName
ArRobot * myRobot
ArServerBase * myServer
bool mySetActivityThisCycle
ArCallbackList mySingleShotDeactivateCallbacks
ArCallbackList mySingleShotPostDeactivateCallbacks
std::string myStatus
bool myStatusSetThisCycle
ArLog::LogLevel myVerboseLogLevel
Additional Inherited Members
Static Public Member Functions inherited from ArServerMode
static ArServerMode * getActiveMode (void)
Gets the active mode.
static int getActiveModeActivityTimeSecSince (void)
Gets the seconds since the activity of our active mode.
static const char * getActiveModeExtendedStatusString (void)
Gets the active extended status string.
static const char * getActiveModeModeString (void)
Gets the active mode string.
static bool getActiveModeSetActivityThisCycle (void)
Gets if the active mode set the activity time this cycle or not.
static const char * getActiveModeStatusString (void)
Gets the active status string.
static ArServerModeIdle * getIdleMode (void)
Call that gets our idle mode.
static void getModeBusy (ArServerClient *client, ArNetPacket *packet)
Handles the packet request for the mode busy state.
static void getModeDataList (ArServerClient *client, ArNetPacket *packet)
Gets the list of data for each mode.
static void getModeInfo (ArServerClient *client, ArNetPacket *packet)
Gets the info about which mode is active and such.
static bool isLocked (void)
Gets if the active mode is locked or not.
static bool willUnlockIfRequested (void)
Gets whether we'll unlock if requested or not.
Static Protected Member Functions inherited from ArServerMode
static void buildModeInfoPacket (ArNetPacket *packet)
static std::list< ArServerMode * > * getRequestedActivateModes (void)
static void modeUserTask (void)
Static Protected Attributes inherited from ArServerMode
static ArServerMode * ourActiveMode = NULL
static bool ourActiveModeLocked = false
static bool ourActiveModeSetActivityThisCycle = false
static bool ourActiveModeWillUnlockIfRequested = false
static ArServerMode * ourBroadcastActiveMode = NULL
static bool ourBroadcastActiveModeLocked = false
static bool ourBroadcastActiveModeWillUnlockIfRequested = false
static std::list< ArServerMode * > ourDefaultModes
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeBusyCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeDataListCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeInfoCB
static ArServerModeIdle * ourIdleMode = NULL
static bool ourIdleModeCreated = false
static ArMutex ourIdleModeMutex
static bool ourIsBusy = false
static ArServerMode * ourLastActiveMode = NULL
static std::multimap< std::string, std::string > ourModeDataMap
static ArMutex ourModeDataMapMutex
static std::list< ArServerMode * > ourModes
static ArServerMode * ourNextActiveMode = NULL
static std::list< ArServerMode * > ourRequestedActivateModes
static ArServerBase * ourServerBase = NULL
static bool ourUserTaskAdded = false
static ArGlobalFunctor ourUserTaskCB
Detailed Description
Examples:
drawingsExampleWithRobot.cpp.
Constructor & Destructor Documentation
ArServerModeDrive::ArServerModeDrive (ArServerBase * server, ArRobot * robot, bool takeControlOnJoystick = false)
References ArActionGroup::addAction(), ArServerMode::addModeData(), ArRobot::addUserTask(), Aria::getJoyHandler(), ArJoyHandler::init(), myDriveGroup, myDriveSafely, myExtraUnsafeAction, myHandlerCommands, myInputAction, myJoydriveAction, myJoyHandler, myJoyUserTaskCB, ArServerMode::myRobot, ArServerMode::myServer, myServerDriveJoystickCB, myStopAction, myTakeControlOnJoystick, Aria::setJoyHandler(), ArActionJoydrive::setStopIfNoButtonPressed(), and setThrottleParams().
ArServerModeDrive::~ArServerModeDrive () virtual
Member Function Documentation
void ArServerModeDrive::activate (void) virtual
The function called when the mode is activated.
Subclasses must implement this, but also call baseActivate().-
Implements ArServerMode.
References driveJoystick().
Referenced by joyUserTask(), and serverDriveJoystick().
void ArServerModeDrive::addControlCommands (ArServerHandlerCommands * handlerCommands)
This adds commands that'll let you disable and enable safe driving.
References ArServerHandlerCommands::addCommand(), myHandlerCommands, myServerSafeDrivingDisableCB, and myServerSafeDrivingEnableCB.
void ArServerModeDrive::deactivate (void) virtual
The function called when the mode is deactivated.
Subclasses must implement this, and also call baseDeactivate().
Implements ArServerMode.
References ArServerMode::baseDeactivate(), ArActionGroup::deactivate(), and myDriveGroup.
void ArServerModeDrive::driveJoystick (double vel, double rotVel, bool isActivating = true)
Parameters
vel Forward velocity
rotVel Rotational velocity
isActivating a bool set to true only if this method is called from the activate() method, otherwise false
References ArAction::activate(), ArActionGroup::activateExclusive(), ArServerMode::baseActivate(), ArRobot::clearDirectMotion(), ArRobot::deactivateActions(), ArServerMode::isActive(), ArLog::log(), myDriveGroup, myDriveSafely, myExtraUnsafeAction, myInputAction, myJoydriveAction, ArServerMode::myMode, myNewDriveSafely, ArServerMode::myRobot, myRotVel, myVel, ArServerMode::setActivityTimeToNow(), and ArLog::Verbose.
Referenced by activate(), serverDriveJoystick(), and setSafeDriving().
virtual ArActionGroup* ArServerModeDrive::getActionGroup (void) inline virtual
This function should return the action group this mode uses.
Reimplemented from ArServerMode.
References getSafeDriving(), myDriveGroup, and setSafeDriving().
bool ArServerModeDrive::getSafeDriving (void)
References myDriveSafely.
Referenced by getActionGroup().
void ArServerModeDrive::joyUserTask (void) protected
References activate(), ArServerMode::getActiveMode(), ArJoyHandler::getButton(), ArServerMode::getName(), ArJoyHandler::haveJoystick(), ArServerMode::isActive(), ArLog::log(), myJoyHandler, myTakeControlOnJoystick, and ArLog::Normal.
Referenced by setExtraUnsafeAction().
void ArServerModeDrive::serverDriveJoystick (ArServerClient * client, ArNetPacket * packet)
References activate(), ArBasePacket::bufToByte2(), driveJoystick(), ArServerMode::isActive(), ArRobot::lock(), ArServerMode::myRobot, and ArRobot::unlock().
void ArServerModeDrive::serverSafeDrivingDisable (void) protected
References ArRobot::lock(), ArServerMode::myRobot, setSafeDriving(), and ArRobot::unlock().
Referenced by setExtraUnsafeAction().
void ArServerModeDrive::serverSafeDrivingEnable (void) protected
References ArRobot::lock(), ArServerMode::myRobot, setSafeDriving(), and ArRobot::unlock().
Referenced by setExtraUnsafeAction().
void ArServerModeDrive::setExtraUnsafeAction (ArAction * action) inline
this action will be activated in unsafe mode
References joyUserTask(), myExtraUnsafeAction, serverSafeDrivingDisable(), and serverSafeDrivingEnable().
void ArServerModeDrive::setSafeDriving (bool safe)
References driveJoystick(), ArServerMode::isActive(), ArLog::log(), myDriveSafely, myNewDriveSafely, myRotVel, myVel, and ArLog::Normal.
Referenced by getActionGroup(), serverSafeDrivingDisable(), and serverSafeDrivingEnable().
void ArServerModeDrive::setThrottleParams (int lowSpeed, int highSpeed)
References myJoydriveAction, and ArActionJoydrive::setThrottleParams().
Referenced by ArServerModeDrive().
void ArServerModeDrive::userTask (void) virtual
The ArMode's user task, don't need one, subclass must provide if needed.
MPL 2014_04_17 centralizing all the places stopped is calculated
Reimplemented from ArServerMode.
References ArRobot::forceTryingToMove(), ArJoyHandler::getButton(), ArRobot::getStallValue(), ArJoyHandler::haveJoystick(), ArRobot::isLeftMotorStalled(), ArRobot::isRightMotorStalled(), ArRobot::isStopped(), myJoyHandler, ArServerMode::myRobot, ArServerMode::myStatus, ArServerMode::myStatusSetThisCycle, and ArServerMode::setActivityTimeToNow().
Member Data Documentation
ArActionGroupInput ArServerModeDrive::myDriveGroup protected
Referenced by ArServerModeDrive(), deactivate(), driveJoystick(), and getActionGroup().
bool ArServerModeDrive::myDriveSafely protected
Referenced by ArServerModeDrive(), driveJoystick(), getSafeDriving(), and setSafeDriving().
ArAction* ArServerModeDrive::myExtraUnsafeAction protected
Referenced by ArServerModeDrive(), driveJoystick(), and setExtraUnsafeAction().
ArServerHandlerCommands* ArServerModeDrive::myHandlerCommands protected
Referenced by addControlCommands(), and ArServerModeDrive().
ArActionInput* ArServerModeDrive::myInputAction protected
Referenced by ArServerModeDrive(), and driveJoystick().
ArActionJoydrive ArServerModeDrive::myJoydriveAction protected
Referenced by ArServerModeDrive(), driveJoystick(), and setThrottleParams().
ArJoyHandler* ArServerModeDrive::myJoyHandler protected
Referenced by ArServerModeDrive(), joyUserTask(), and userTask().
ArFunctorC<ArServerModeDrive> ArServerModeDrive::myJoyUserTaskCB protected
Referenced by ArServerModeDrive().
bool ArServerModeDrive::myNewDriveSafely protected
Referenced by driveJoystick(), and setSafeDriving().
double ArServerModeDrive::myRotVel protected
Referenced by driveJoystick(), and setSafeDriving().
ArFunctor2C<ArServerModeDrive, ArServerClient *, ArNetPacket *> ArServerModeDrive::myServerDriveJoystickCB protected
Referenced by ArServerModeDrive().
ArFunctorC<ArServerModeDrive> ArServerModeDrive::myServerSafeDrivingDisableCB protected
Referenced by addControlCommands().
ArFunctorC<ArServerModeDrive> ArServerModeDrive::myServerSafeDrivingEnableCB protected
Referenced by addControlCommands().
ArActionStop ArServerModeDrive::myStopAction protected
Referenced by ArServerModeDrive().
bool ArServerModeDrive::myTakeControlOnJoystick protected
Referenced by ArServerModeDrive(), and joyUserTask().
double ArServerModeDrive::myVel protected
Referenced by driveJoystick(), and setSafeDriving().
The documentation for this class was generated from the following files:
ArServerModeDrive.h
ArServerModeDrive.cpp