ArNetworking: ArServerSimpleOpener Class Reference
ArServerSimpleOpener Class Reference
Set up and open an ArNetworking server.
#include <ArServerSimpleOpener.h>
Public Member Functions
ArServerSimpleOpener (ArArgumentParser *parser, const char *prefix="", bool addAriaCallbacks=true)
Constructor.
bool checkAndLog (void) const
Logs the things requested for logging, may check things later.
bool didOpenFail (void)
Returns true if the open failed because it couldn't open.
int getPort ()
Get the server's port number.
const char * getServerKey (void)
Gets the server key.
void logOptions (void) const
Log the options the simple connector has.
bool open (ArServerBase *server, const char *baseDirectory="", int secondsToTryFor=240)
Function to open up the server.
bool parseArgs (void)
Function to parse the arguments given in the constructor.
bool parseArgs (ArArgumentParser *parser)
Function to parse the arguments given in an arbitrary parser.
bool parseFile (const char *fileName)
Parses the file for holding the server key.
void setDefaultPort (int port)
Set default server port number (normally 7272).
void setServerTcpOnly (bool serverTcpOnly)
Sets the tcpOnly flag.
bool wasUserFileBad (void)
Returns true if the open failed because of a bad user file.
~ArServerSimpleOpener ()
Destructor.
Protected Member Functions
bool fileServerKeyCallback (ArArgumentBuilder *arg)
void logOptionsWithOutPrefix (void) const
void logOptionsWithPrefix (void) const
bool parseArgsWithOutPrefix (ArArgumentParser *parser)
bool parseArgsWithPrefix (ArArgumentParser *parser)
void reset (void)
Protected Attributes
bool myBadUserFile
ArFileParser myFileParser
ArRetFunctor1C< bool, ArServerSimpleOpener, ArArgumentBuilder * > myFileServerKeyCB
bool myLogCommandGroups
ArConstFunctorC< ArServerSimpleOpener > myLogOptionsCB
bool myLogUserInfo
bool myOpenFailed
const char * myOpenOnIP
bool myOwnParser
ArRetFunctorC< bool, ArServerSimpleOpener > myParseArgsCB
ArArgumentParser * myParser
std::string myPrefix
ArServerBase * myServer
std::string myServerKey
int myServerPort
bool myTcpOnly
const char * myUserFile
Detailed Description
Set up and open an ArNetworking server.
Some program command line options affect behavior:
Options for ArServerSimpleOpener:
-serverPort <serverPortNumber>
-sp <serverPortNumber>
-serverIP <serverIPToOpenOn>
-sip <serverIPToOpenOn>
-serverTcpOnly
-userInfo <userInfoFileName>
-ui <userInfoFileName>
-logUserInfo
-lui
-logCommandGroups
-lcg
-serverInfoFile <file>
To set the port the server uses use '-serverPort serverPortNumber' or '-sp serverPortNumber'. To set the file to look in for user information use '-userInfo fileName' or "-ui fileName'. To log out the user information use '-logUserInfo' or 'lui'. To log out the command groups use '-logCommandGroups' or '-lcg'. To set the key used for the server (that the client has to know to connect if using user and password) use '-serverInfoFile file'. With a file that has in it 'serverKey serverKey'. You should obviously make sure no one you don't want to know that server key can read your file that it is in.
For more details about all of these options see ArServerBase.
See also
ArServerBase
Examples:
drawingsExample.cpp, drawingsExampleWithRobot.cpp, popupExample.cpp, serverDemo.cpp, and simpleServerExample.cpp.
Constructor & Destructor Documentation
ArServerSimpleOpener::ArServerSimpleOpener (ArArgumentParser * parser, const char * prefix = "", bool addAriaCallbacks = true)
Constructor.
Parameters
parser the parser to use for information
References ArFileParser::addHandler(), Aria::addLogOptionsCB(), Aria::addParseArgsCB(), myFileParser, myFileServerKeyCB, myLogCommandGroups, myLogOptionsCB, myLogUserInfo, myOpenOnIP, myOwnParser, myParseArgsCB, myParser, myPrefix, myServer, myServerPort, myTcpOnly, myUserFile, and ArFunctor::setName().
ArServerSimpleOpener::~ArServerSimpleOpener (void)
Destructor.
Member Function Documentation
bool ArServerSimpleOpener::checkAndLog (void) const
Logs the things requested for logging, may check things later.
Examples:
serverDemo.cpp, and simpleServerExample.cpp.
References ArServerBase::logCommandGroups(), ArServerBase::logUserInfo(), myLogCommandGroups, myLogUserInfo, and myServer.
Referenced by main().
bool ArServerSimpleOpener::didOpenFail (void) inline
Returns true if the open failed because it couldn't open.
References myOpenFailed.
bool ArServerSimpleOpener::fileServerKeyCallback (ArArgumentBuilder * arg) protected
References ArArgumentBuilder::getArg(), ArArgumentBuilder::getArgc(), ArArgumentBuilder::getExtraString(), ArArgumentBuilder::getFullString(), ArLog::log(), myServerKey, and ArLog::Normal.
Referenced by getServerKey().
int ArServerSimpleOpener::getPort () inline
Get the server's port number.
Returns
the server's port number
Examples:
simpleServerExample.cpp.
References myServerPort.
Referenced by main().
const char* ArServerSimpleOpener::getServerKey (void) inline
Gets the server key.
References fileServerKeyCallback(), logOptionsWithOutPrefix(), logOptionsWithPrefix(), myServerKey, parseArgsWithOutPrefix(), parseArgsWithPrefix(), and reset().
void ArServerSimpleOpener::logOptions (void) const
Log the options the simple connector has.
Examples:
simpleServerExample.cpp.
References logOptionsWithOutPrefix(), logOptionsWithPrefix(), and myPrefix.
Referenced by main().
void ArServerSimpleOpener::logOptionsWithOutPrefix (void) const protected
References ArLog::log(), and ArLog::Terse.
Referenced by getServerKey(), and logOptions().
void ArServerSimpleOpener::logOptionsWithPrefix (void) const protected
References ArLog::log(), myPrefix, and ArLog::Terse.
Referenced by getServerKey(), and logOptions().
bool ArServerSimpleOpener::open (ArServerBase * server, const char * baseDirectory = "", int secondsToTryFor = 240)
Function to open up the server.
Parameters
server the server to operate on
baseDirectory the base directory (solely for loading user information)
secondsToTryFor this is the number of seconds to try opening for, 0 means only try to open once
Examples:
popupExample.cpp, serverDemo.cpp, and simpleServerExample.cpp.
References Aria::getRunning(), ArServerBase::loadUserInfo(), ArLog::log(), myBadUserFile, myOpenFailed, myOpenOnIP, myServer, myServerKey, myServerPort, myTcpOnly, myUserFile, ArLog::Normal, ArServerBase::open(), ArTime::secSince(), ArServerBase::setServerKey(), ArTime::setToNow(), and ArUtil::sleep().
Referenced by main().
bool ArServerSimpleOpener::parseArgs (void)
Function to parse the arguments given in the constructor.
Examples:
simpleServerExample.cpp.
References myParser.
Referenced by main().
bool ArServerSimpleOpener::parseArgs (ArArgumentParser * parser)
Function to parse the arguments given in an arbitrary parser.
References myPrefix, parseArgsWithOutPrefix(), and parseArgsWithPrefix().
bool ArServerSimpleOpener::parseArgsWithOutPrefix (ArArgumentParser * parser) protected
References ArArgumentParser::checkArgument(), ArArgumentParser::checkParameterArgumentInteger(), ArArgumentParser::checkParameterArgumentString(), ArArgumentParser::getWasReallySetOnlyTrue(), myLogCommandGroups, myLogUserInfo, myOpenOnIP, myParser, myServerPort, myTcpOnly, myUserFile, parseFile(), and ArArgumentParser::setWasReallySetOnlyTrue().
Referenced by getServerKey(), and parseArgs().
bool ArServerSimpleOpener::parseArgsWithPrefix (ArArgumentParser * parser) protected
References ArArgumentParser::checkArgumentVar(), ArArgumentParser::checkParameterArgumentIntegerVar(), ArArgumentParser::checkParameterArgumentStringVar(), ArArgumentParser::getWasReallySetOnlyTrue(), myLogCommandGroups, myLogUserInfo, myOpenOnIP, myParser, myPrefix, myServerPort, myTcpOnly, myUserFile, parseFile(), and ArArgumentParser::setWasReallySetOnlyTrue().
Referenced by getServerKey(), and parseArgs().
bool ArServerSimpleOpener::parseFile (const char * fileName)
Parses the file for holding the server key.
References ArLog::log(), myFileParser, ArLog::Normal, and ArFileParser::parseFile().
Referenced by parseArgsWithOutPrefix(), parseArgsWithPrefix(), and setDefaultPort().
void ArServerSimpleOpener::reset (void) protected
Referenced by getServerKey().
void ArServerSimpleOpener::setDefaultPort (int port) inline
Set default server port number (normally 7272).
This must be called before parsing command line arguments.
Since
2.7.6
References myServerPort, and parseFile().
void ArServerSimpleOpener::setServerTcpOnly (bool serverTcpOnly) inline
Sets the tcpOnly flag.
References myTcpOnly.
bool ArServerSimpleOpener::wasUserFileBad (void) inline
Returns true if the open failed because of a bad user file.
Examples:
serverDemo.cpp.
References myBadUserFile.
Referenced by main().
Member Data Documentation
bool ArServerSimpleOpener::myBadUserFile protected
Referenced by open(), and wasUserFileBad().
ArFileParser ArServerSimpleOpener::myFileParser protected
Referenced by ArServerSimpleOpener(), and parseFile().
ArRetFunctor1C<bool, ArServerSimpleOpener, ArArgumentBuilder *> ArServerSimpleOpener::myFileServerKeyCB protected
Referenced by ArServerSimpleOpener().
bool ArServerSimpleOpener::myLogCommandGroups protected
Referenced by ArServerSimpleOpener(), checkAndLog(), parseArgsWithOutPrefix(), and parseArgsWithPrefix().
ArConstFunctorC<ArServerSimpleOpener> ArServerSimpleOpener::myLogOptionsCB protected
Referenced by ArServerSimpleOpener().
bool ArServerSimpleOpener::myLogUserInfo protected
Referenced by ArServerSimpleOpener(), checkAndLog(), parseArgsWithOutPrefix(), and parseArgsWithPrefix().
bool ArServerSimpleOpener::myOpenFailed protected
Referenced by didOpenFail(), and open().
const char* ArServerSimpleOpener::myOpenOnIP protected
Referenced by ArServerSimpleOpener(), open(), parseArgsWithOutPrefix(), and parseArgsWithPrefix().
bool ArServerSimpleOpener::myOwnParser protected
Referenced by ArServerSimpleOpener().
ArRetFunctorC<bool, ArServerSimpleOpener> ArServerSimpleOpener::myParseArgsCB protected
Referenced by ArServerSimpleOpener().
ArArgumentParser* ArServerSimpleOpener::myParser protected
Referenced by ArServerSimpleOpener(), parseArgs(), parseArgsWithOutPrefix(), and parseArgsWithPrefix().
std::string ArServerSimpleOpener::myPrefix protected
Referenced by ArServerSimpleOpener(), logOptions(), logOptionsWithPrefix(), parseArgs(), and parseArgsWithPrefix().
ArServerBase* ArServerSimpleOpener::myServer protected
Referenced by ArServerSimpleOpener(), checkAndLog(), and open().
std::string ArServerSimpleOpener::myServerKey protected
Referenced by fileServerKeyCallback(), getServerKey(), and open().
int ArServerSimpleOpener::myServerPort protected
Referenced by ArServerSimpleOpener(), getPort(), open(), parseArgsWithOutPrefix(), parseArgsWithPrefix(), and setDefaultPort().
bool ArServerSimpleOpener::myTcpOnly protected
Referenced by ArServerSimpleOpener(), open(), parseArgsWithOutPrefix(), parseArgsWithPrefix(), and setServerTcpOnly().
const char* ArServerSimpleOpener::myUserFile protected
Referenced by ArServerSimpleOpener(), open(), parseArgsWithOutPrefix(), and parseArgsWithPrefix().
The documentation for this class was generated from the following files:
ArServerSimpleOpener.h
ArServerSimpleOpener.cpp