ArNetworking: ArClientFileToClient Class Reference
ArClientFileToClient Class Reference
Class for getting files from the server.
#include <ArClientFileUtils.h>
Public Member Functions
void addFileReceivedCallback (ArFunctor1< int > *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback for when we get the desired file (or fail)
ArClientFileToClient (ArClientBase *client)
Constructor.
void cancelGet (void)
Cancels getting a file.
const char * getClientFileName (void)
Gets the filename we'll save the gotten file in.
const char * getDirectory (void)
Gets the directory we're getting from.
bool getFileFromDirectory (const char *directory, const char *fileName, const char *clientFileName, bool isSetTimestamp=false)
Get the file from a directory.
const char * getFileName (void)
Gets the filename we're getting.
ArTime getLastReceived (void)
Gets the last time we finished getting a file.
ArTime getLastRequested (void)
Gets the last time we asked for a file.
bool isAvailable (void)
Sees if the server supports what this class needs.
bool isAvailableSetTimestamp (void)
bool isWaitingForFile (void)
If we're getting a file now.
void remFileReceivedCallback (ArFunctor1< int > *functor)
Removes a callback for when we get the desired file (or fail)
virtual ~ArClientFileToClient ()
Destructor.
Protected Member Functions
void callFileReceivedCallbacks (int val)
void doGetFile (ArNetPacket *packet, bool isSetTimestamp)
void netGetFile (ArNetPacket *packet)
void netGetFileWithTimestamp (ArNetPacket *packet)
Protected Attributes
ArMutex myCallbackMutex
ArClientBase * myClient
std::string myClientFileName
ArMutex myDataMutex
std::string myDirectory
FILE * myFile
std::string myFileName
std::list< ArFunctor1< int > * > myFileReceivedCallbacks
ArFunctor1C
< ArClientFileToClient,
ArNetPacket * > myGetFileCB
ArFunctor1C
< ArClientFileToClient,
ArNetPacket * > myGetFileWithTimestampCB
bool myIsWaitingForFile
ArTime myLastReceived
ArTime myLastRequested
std::string myWholeFileName
Detailed Description
Class for getting files from the server.
This class will interact with the ArServerFileToClient and get a file on the server. If you want to find out what files are on the server use ArClientFileLister.
When get a file it doesn't happen right away, but when the file is received (or failes) the fileGotten callbacks will be called, 0 as the int for the callback means everything is good, positive error messages are from the server (1 == tried to go outside allowed area, 2 == no such directory, 3 == empty file name, 4 == problem reading file), negative are from this class (-1 == got directory but it wasn't what we wanted (if you wait the right one might come in, like if someone selects one dir then the other), -2 == can't open file to put result into).
Constructor & Destructor Documentation
ArClientFileToClient::ArClientFileToClient (ArClientBase * client)
Constructor.
References ArClientBase::addHandler(), myCallbackMutex, myClient, myDataMutex, myGetFileCB, myGetFileWithTimestampCB, and ArMutex::setLogName().
ArClientFileToClient::~ArClientFileToClient () [virtual]
Destructor.
Member Function Documentation
void ArClientFileToClient::addFileReceivedCallback (ArFunctor1< int > * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback for when we get the desired file (or fail)
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, myFileReceivedCallbacks, ArLog::Terse, and ArMutex::unlock().
void ArClientFileToClient::callFileReceivedCallbacks (int val) [protected]
References ArMutex::lock(), myCallbackMutex, myFileReceivedCallbacks, and ArMutex::unlock().
Referenced by doGetFile().
void ArClientFileToClient::cancelGet (void)
Cancels getting a file.
void ArClientFileToClient::doGetFile (ArNetPacket * packet, bool isSetTimestamp) [protected]
References ArBasePacket::bufToByte4(), ArBasePacket::bufToData(), ArBasePacket::bufToStr(), ArBasePacket::bufToUByte2(), ArBasePacket::bufToUByte4(), callFileReceivedCallbacks(), ArUtil::changeFileTimestamp(), ArUtil::fixSlashes(), ArUtil::fopen(), ArBasePacket::getDataLength(), ArMutex::lock(), ArLog::log(), myClientFileName, myDataMutex, myFile, myFileName, myIsWaitingForFile, myLastReceived, myWholeFileName, ArLog::Normal, ArTime::setToNow(), ArUtil::strcasecmp(), ArMutex::unlock(), and ArLog::Verbose.
Referenced by netGetFile(), and netGetFileWithTimestamp().
const char * ArClientFileToClient::getClientFileName (void)
Gets the filename we'll save the gotten file in.
References ArMutex::lock(), myClientFileName, myDataMutex, and ArMutex::unlock().
const char * ArClientFileToClient::getDirectory (void)
Gets the directory we're getting from.
References ArMutex::lock(), myDataMutex, myDirectory, and ArMutex::unlock().
bool ArClientFileToClient::getFileFromDirectory (const char * directory, const char * fileName, const char * clientFileName, bool isSetTimestamp = false)
Get the file from a directory.
References ArUtil::appendSlash(), ArUtil::fixSlashes(), isAvailable(), isAvailableSetTimestamp(), ArMutex::lock(), ArLog::log(), myClient, myClientFileName, myDataMutex, myDirectory, myFileName, myIsWaitingForFile, myLastRequested, myWholeFileName, ArLog::Normal, ArClientBase::requestOnce(), ArTime::setToNow(), ArBasePacket::strToBuf(), ArLog::Terse, ArBasePacket::uByte2ToBuf(), and ArMutex::unlock().
const char * ArClientFileToClient::getFileName (void)
Gets the filename we're getting.
References ArMutex::lock(), myDataMutex, myFileName, and ArMutex::unlock().
ArTime ArClientFileToClient::getLastReceived (void)
Gets the last time we finished getting a file.
References ArMutex::lock(), myDataMutex, myLastReceived, and ArMutex::unlock().
ArTime ArClientFileToClient::getLastRequested (void)
Gets the last time we asked for a file.
References ArMutex::lock(), myDataMutex, myLastRequested, and ArMutex::unlock().
bool ArClientFileToClient::isAvailable (void)
Sees if the server supports what this class needs.
References ArClientBase::dataExists(), and myClient.
Referenced by getFileFromDirectory().
bool ArClientFileToClient::isAvailableSetTimestamp (void)
References ArClientBase::dataExists(), and myClient.
Referenced by getFileFromDirectory().
bool ArClientFileToClient::isWaitingForFile (void)
If we're getting a file now.
References ArMutex::lock(), myDataMutex, myIsWaitingForFile, and ArMutex::unlock().
void ArClientFileToClient::netGetFile (ArNetPacket * packet) [protected]
References doGetFile().
void ArClientFileToClient::netGetFileWithTimestamp (ArNetPacket * packet) [protected]
References doGetFile().
void ArClientFileToClient::remFileReceivedCallback (ArFunctor1< int > * functor)
Removes a callback for when we get the desired file (or fail)
References ArMutex::lock(), myCallbackMutex, myFileReceivedCallbacks, and ArMutex::unlock().
Member Data Documentation
ArMutex ArClientFileToClient::myCallbackMutex [protected]
Referenced by addFileReceivedCallback(), ArClientFileToClient(), callFileReceivedCallbacks(), and remFileReceivedCallback().
ArClientBase* ArClientFileToClient::myClient [protected]
Referenced by ArClientFileToClient(), getFileFromDirectory(), isAvailable(), and isAvailableSetTimestamp().
std::string ArClientFileToClient::myClientFileName [protected]
Referenced by doGetFile(), getClientFileName(), and getFileFromDirectory().
ArMutex ArClientFileToClient::myDataMutex [protected]
Referenced by ArClientFileToClient(), doGetFile(), getClientFileName(), getDirectory(), getFileFromDirectory(), getFileName(), getLastReceived(), getLastRequested(), and isWaitingForFile().
std::string ArClientFileToClient::myDirectory [protected]
Referenced by getDirectory(), and getFileFromDirectory().
FILE* ArClientFileToClient::myFile [protected]
Referenced by doGetFile().
std::string ArClientFileToClient::myFileName [protected]
Referenced by doGetFile(), getFileFromDirectory(), and getFileName().
std::list<ArFunctor1<int> *> ArClientFileToClient::myFileReceivedCallbacks [protected]
Referenced by addFileReceivedCallback(), callFileReceivedCallbacks(), and remFileReceivedCallback().
ArFunctor1C<ArClientFileToClient, ArNetPacket *> ArClientFileToClient::myGetFileCB [protected]
Referenced by ArClientFileToClient().
ArFunctor1C<ArClientFileToClient, ArNetPacket *> ArClientFileToClient::myGetFileWithTimestampCB [protected]
Referenced by ArClientFileToClient().
bool ArClientFileToClient::myIsWaitingForFile [protected]
Referenced by doGetFile(), getFileFromDirectory(), and isWaitingForFile().
ArTime ArClientFileToClient::myLastReceived [protected]
Referenced by doGetFile(), and getLastReceived().
ArTime ArClientFileToClient::myLastRequested [protected]
Referenced by getFileFromDirectory(), and getLastRequested().
std::string ArClientFileToClient::myWholeFileName [protected]
Referenced by doGetFile(), and getFileFromDirectory().
The documentation for this class was generated from the following files:
ArClientFileUtils.h
ArClientFileUtils.cpp