ArNetworking: ArServerHandlerCommands Class Reference
ArServerHandlerCommands Class Reference
Class for having commands that can be called easily on the client.
#include <ArServerHandlerCommands.h>
Public Member Functions
bool addCommand (const char *name, const char *description, ArFunctor *functor, const char *commandGroup=NULL)
Adds a command with no arguments.
bool addStringCommand (const char *name, const char *description, ArFunctor1< ArArgumentBuilder * > *functor, const char *commandGroup=NULL)
Adds a command that takes a string argument.
ArServerHandlerCommands (ArServerBase *server)
Constructor.
const char * getPrefix (void)
Gets the prefix.
void netListCommands (ArServerClient *client, ArNetPacket *packet)
The function that lists the commands.
void netListStringCommands (ArServerClient *client, ArNetPacket *packet)
The function that lists the string commands.
void setPrefix (const char *prefix)
Sets a prefix for commands.
void setTextServer (ArNetServer *textServer)
Sets the text server.
virtual ~ArServerHandlerCommands ()
Destructor.
Protected Member Functions
void netParseCommand (ArServerClient *client, ArNetPacket *packet, ArFunctor *functor)
void netParseStringCommand (ArServerClient *client, ArNetPacket *packet, ArFunctor1< ArArgumentBuilder * > *functor)
void textParseCommand (char **argv, int argc, ArSocket *socket, ArFunctor *functor)
void textParseStringCommand (char **argv, int argc, ArSocket *socket, ArFunctor1< ArArgumentBuilder * > *functor)
Protected Attributes
std::list< std::string > myCommandDescriptions
std::list< std::string > myCommands
std::list< ArFunctor3< ArServerClient *, ArNetPacket *, ArFunctor * > * > myFunctors
ArFunctor2C< ArServerHandlerCommands, ArServerClient *, ArNetPacket * > myNetListCommandsCB
ArFunctor2C< ArServerHandlerCommands, ArServerClient *, ArNetPacket * > myNetListStringCommandsCB
std::string myPrefix
ArServerBase * myServer
std::list< std::string > myStringCommandDescriptions
std::list< std::string > myStringCommands
std::list< ArFunctor3< ArServerClient *, ArNetPacket *, ArFunctor1< ArArgumentBuilder * > * > * > myStringFunctors
ArNetServer * myTextServer
Detailed Description
Class for having commands that can be called easily on the client.
You can add commands with addCommand and addStringCommand, you can get the list of commands by requesting the data "listCommands" and "listStringCommands".
Examples:
serverDemo.cpp.
Constructor & Destructor Documentation
ArServerHandlerCommands::ArServerHandlerCommands (ArServerBase * server)
Constructor.
References ArServerBase::addData(), myNetListCommandsCB, myNetListStringCommandsCB, myServer, and myTextServer.
Referenced by addCommand(), and addStringCommand().
ArServerHandlerCommands::~ArServerHandlerCommands () virtual
Destructor.
References ArUtil::deleteSet(), myFunctors, and myStringFunctors.
Member Function Documentation
bool ArServerHandlerCommands::addCommand (const char * name, const char * description, ArFunctor * functor, const char * commandGroup = NULL)
Adds a command with no arguments.
Parameters
name the name of the command to add
description the description used for this command
functor the functor to call
commandGroup the command group this should be in, if NULL defaults to CustomCommands
References ArNetServer::addCommand(), ArServerBase::addData(), ArServerHandlerCommands(), ArLog::log(), myCommandDescriptions, myCommands, myFunctors, myPrefix, myServer, myTextServer, netParseCommand(), ArLog::Normal, textParseCommand(), and ArLog::Verbose.
Referenced by ArServerModeDrive::addControlCommands(), ArServerModeRatioDrive::addControlCommands(), ArServerSimpleComGyro::ArServerSimpleComGyro(), ArServerSimpleComLogActions::ArServerSimpleComLogActions(), ArServerSimpleComLogRobotConfig::ArServerSimpleComLogRobotConfig(), ArServerSimpleComMovementLogging::ArServerSimpleComMovementLogging(), ArServerSimpleConnectionTester::ArServerSimpleConnectionTester(), ArServerSimpleLogRobotDebugPackets::ArServerSimpleLogRobotDebugPackets(), ArServerSimpleServerCommands::ArServerSimpleServerCommands(), and setTextServer().
bool ArServerHandlerCommands::addStringCommand (const char * name, const char * description, ArFunctor1< ArArgumentBuilder * > * functor, const char * commandGroup = NULL)
Adds a command that takes a string argument.
Parameters
name the name of the command to add
description the description used for this command
functor the functor to call (takes an argument builder)
commandGroup the command group this should be in, if NULL defaults to CustomCommands
References ArNetServer::addCommand(), ArServerBase::addData(), ArServerHandlerCommands(), ArLog::log(), myPrefix, myServer, myStringCommandDescriptions, myStringCommands, myStringFunctors, myTextServer, netParseStringCommand(), ArLog::Normal, textParseStringCommand(), and ArLog::Verbose.
Referenced by ArServerHandlerMapping::addSimpleCommands(), ArServerModeJogPosition::ArServerModeJogPosition(), ArServerSimpleComUC::ArServerSimpleComUC(), ArServerSimplePopup::ArServerSimplePopup(), and setTextServer().
const char * ArServerHandlerCommands::getPrefix (void)
Gets the prefix.
References myPrefix.
Referenced by setTextServer().
void ArServerHandlerCommands::netListCommands (ArServerClient * client, ArNetPacket * packet)
The function that lists the commands.
References ArBasePacket::byte2ToBuf(), myCommandDescriptions, myCommands, ArServerClient::sendPacketTcp(), and ArBasePacket::strToBuf().
Referenced by setTextServer().
void ArServerHandlerCommands::netListStringCommands (ArServerClient * client, ArNetPacket * packet)
The function that lists the string commands.
References ArBasePacket::byte2ToBuf(), myStringCommandDescriptions, myStringCommands, ArServerClient::sendPacketTcp(), and ArBasePacket::strToBuf().
Referenced by setTextServer().
void ArServerHandlerCommands::netParseCommand (ArServerClient * client, ArNetPacket * packet, ArFunctor * functor) protected
References ArFunctor::invoke(), ArLog::log(), and ArLog::Terse.
Referenced by addCommand().
void ArServerHandlerCommands::netParseStringCommand (ArServerClient * client, ArNetPacket * packet, ArFunctor1< ArArgumentBuilder * > * functor) protected
References ArArgumentBuilder::add(), ArBasePacket::bufToStr(), ArFunctor1< P1 >::invoke(), ArLog::log(), ArArgumentBuilder::setFullString(), and ArLog::Terse.
Referenced by addStringCommand().
void ArServerHandlerCommands::setPrefix (const char * prefix)
Sets a prefix for commands.
References myPrefix.
Referenced by setTextServer().
void ArServerHandlerCommands::setTextServer (ArNetServer * textServer) inline
Sets the text server.
References addCommand(), addStringCommand(), client, getPrefix(), myTextServer, netListCommands(), netListStringCommands(), and setPrefix().
void ArServerHandlerCommands::textParseCommand (char ** argv, int argc, ArSocket * socket, ArFunctor * functor) protected
References ArFunctor::invoke(), ArLog::log(), and ArLog::Terse.
Referenced by addCommand().
void ArServerHandlerCommands::textParseStringCommand (char ** argv, int argc, ArSocket * socket, ArFunctor1< ArArgumentBuilder * > * functor) protected
References ArArgumentBuilder::addStrings(), ArFunctor1< P1 >::invoke(), ArLog::log(), and ArLog::Terse.
Referenced by addStringCommand().
Member Data Documentation
std::list<std::string> ArServerHandlerCommands::myCommandDescriptions protected
Referenced by addCommand(), and netListCommands().
std::list<std::string> ArServerHandlerCommands::myCommands protected
Referenced by addCommand(), and netListCommands().
std::list<ArFunctor3<ArServerClient *, ArNetPacket *, ArFunctor *> *> ArServerHandlerCommands::myFunctors protected
Referenced by addCommand(), and ~ArServerHandlerCommands().
ArFunctor2C<ArServerHandlerCommands, ArServerClient *, ArNetPacket *> ArServerHandlerCommands::myNetListCommandsCB protected
Referenced by ArServerHandlerCommands().
ArFunctor2C<ArServerHandlerCommands, ArServerClient *, ArNetPacket *> ArServerHandlerCommands::myNetListStringCommandsCB protected
Referenced by ArServerHandlerCommands().
std::string ArServerHandlerCommands::myPrefix protected
Referenced by addCommand(), addStringCommand(), getPrefix(), and setPrefix().
ArServerBase* ArServerHandlerCommands::myServer protected
Referenced by addCommand(), addStringCommand(), and ArServerHandlerCommands().
std::list<std::string> ArServerHandlerCommands::myStringCommandDescriptions protected
Referenced by addStringCommand(), and netListStringCommands().
std::list<std::string> ArServerHandlerCommands::myStringCommands protected
Referenced by addStringCommand(), and netListStringCommands().
std::list<ArFunctor3<ArServerClient *, ArNetPacket *, ArFunctor1<ArArgumentBuilder *> *> *> ArServerHandlerCommands::myStringFunctors protected
Referenced by addStringCommand(), and ~ArServerHandlerCommands().
ArNetServer* ArServerHandlerCommands::myTextServer protected
Referenced by addCommand(), addStringCommand(), ArServerHandlerCommands(), and setTextServer().
The documentation for this class was generated from the following files:
ArServerHandlerCommands.h
ArServerHandlerCommands.cpp