ArNetworking: ArServerClientIdentifier Class Reference
ArServerClientIdentifier Class Reference
Class that holds an identifier for a particular serverClient.
#include <ArServerClientIdentifier.h>
Public Member Functions
ArServerClientIdentifier ()
Constructor.
ArTypes::UByte4 getConnectionID (void)
Gets the id num.
const char * getHereGoal (void)
Gets the here goal.
const char * getIDString (void)
Gets an ID string which is just the other information in this combined.
const char * getSelfIdentifier (void)
Gets the self identifier.
bool matches (ArServerClientIdentifier identifier, bool matchConnectionID)
Sees if an identifier matches.
void rebuildIDString (void)
void setConnectionID (ArTypes::UByte4 idNum)
set the id num
void setHereGoal (const char *selfIdentifier)
Sets the here goal.
void setSelfIdentifier (const char *selfIdentifier)
Sets the self identifier.
virtual ~ArServerClientIdentifier ()
Destructor.
Protected Attributes
ArTypes::UByte4 myConnectionID
std::string myHereGoal
std::string myIDString
std::string mySelfIdentifier
Detailed Description
Class that holds an identifier for a particular serverClient.
Constructor & Destructor Documentation
ArServerClientIdentifier::ArServerClientIdentifier () [inline]
Constructor.
References myConnectionID, and rebuildIDString().
virtual ArServerClientIdentifier::~ArServerClientIdentifier () [inline, virtual]
Destructor.
Member Function Documentation
ArTypes::UByte4 ArServerClientIdentifier::getConnectionID (void) [inline]
Gets the id num.
References myConnectionID.
Referenced by ArServerBase::closeConnectionID(), ArCentralManager::forwarderServerClientRemovedCallback(), ArServerBase::identGetConnectionID(), ArCentralManager::mainServerClientRemovedCallback(), and matches().
const char* ArServerClientIdentifier::getHereGoal (void) [inline]
Gets the here goal.
References myHereGoal.
Referenced by matches().
const char* ArServerClientIdentifier::getIDString (void) [inline]
Gets an ID string which is just the other information in this combined.
References myIDString.
Referenced by ArServerClient::setIdentifier().
const char* ArServerClientIdentifier::getSelfIdentifier (void) [inline]
Gets the self identifier.
References mySelfIdentifier.
Referenced by matches().
bool ArServerClientIdentifier::matches (ArServerClientIdentifier identifier, bool matchConnectionID) [inline]
Sees if an identifier matches.
It can either match id, or the other parameters (for the other parameters if the self id matches its a match, otherwise it checks the here goal, and if that matches its a match)... this is so that if someone's set a self id but changes their here goal they'll still get their messages
References getConnectionID(), getHereGoal(), and getSelfIdentifier().
Referenced by ArServerBase::broadcastPacketTcpByCommandWithExclusion(), and ArServerBase::broadcastPacketUdpByCommandWithExclusion().
void ArServerClientIdentifier::rebuildIDString (void) [inline]
References myConnectionID, myHereGoal, myIDString, and mySelfIdentifier.
Referenced by ArServerClientIdentifier(), setConnectionID(), setHereGoal(), and setSelfIdentifier().
void ArServerClientIdentifier::setConnectionID (ArTypes::UByte4 idNum) [inline]
set the id num
References myConnectionID, and rebuildIDString().
Referenced by ArServerBase::identGetConnectionID(), and ArServerBase::identSetConnectionID().
void ArServerClientIdentifier::setHereGoal (const char * selfIdentifier) [inline]
Sets the here goal.
References myHereGoal, and rebuildIDString().
Referenced by ArServerBase::identSetHereGoal().
void ArServerClientIdentifier::setSelfIdentifier (const char * selfIdentifier) [inline]
Sets the self identifier.
References mySelfIdentifier, and rebuildIDString().
Referenced by ArServerBase::identSetSelfIdentifier().
Member Data Documentation
ArTypes::UByte4 ArServerClientIdentifier::myConnectionID [protected]
Referenced by ArServerClientIdentifier(), getConnectionID(), rebuildIDString(), and setConnectionID().
std::string ArServerClientIdentifier::myHereGoal [protected]
Referenced by getHereGoal(), rebuildIDString(), and setHereGoal().
std::string ArServerClientIdentifier::myIDString [protected]
Referenced by getIDString(), and rebuildIDString().
std::string ArServerClientIdentifier::mySelfIdentifier [protected]
Referenced by getSelfIdentifier(), rebuildIDString(), and setSelfIdentifier().
The documentation for this class was generated from the following file:
ArServerClientIdentifier.h