ArNetworking: PtzCameraExample Class Reference
PtzCameraExample Class Reference
Requests a list of cameras if neccesary, maintains a list of cameras, and implements example pan/tilt movements.
Public Member Functions
bool init ()
PtzCameraExample (ArClientBase *client)
void run ()
Detailed Description
Requests a list of cameras if neccesary, maintains a list of cameras, and implements example pan/tilt movements.
Examples:
ptzCameraClientExample.cpp.
Constructor & Destructor Documentation
PtzCameraExample::PtzCameraExample (ArClientBase * client) inline
References run().
Member Function Documentation
bool PtzCameraExample::init (void)
Examples:
ptzCameraClientExample.cpp.
References ArClientArg::bufToArgValue(), ArBasePacket::bufToByte2(), ArBasePacket::bufToByte4(), ArBasePacket::bufToStr(), ArClientHandlerCamera::displayName, ArClientHandlerCamera::displayType, ArLog::log(), ArLog::Normal, ArClientHandlerCamera::requestUpdates(), ArLog::Terse, and ArClientHandlerCamera::type.
Referenced by main().
void PtzCameraExample::run (void)
Examples:
ptzCameraClientExample.cpp.
References ArClientHandlerCamera::lock(), ArClientHandlerCamera::maxPan, ArClientHandlerCamera::maxTilt, ArClientHandlerCamera::minPan, ArClientHandlerCamera::minTilt, ArClientHandlerCamera::request, ArNetCameraRequest::requestPanTiltAbs(), ArUtil::sleep(), and ArClientHandlerCamera::unlock().
Referenced by main().
The documentation for this class was generated from the following file:
ptzCameraClientExample.cpp