ArNetworking: ArClientBase Class Reference
ArClientBase Class Reference
The base client class.
#include <ArClientBase.h>
Classes
class Tracker
Public Types
enum { CLIENT_KEY_LENGTH = 16 }
enum ClientState {
STATE_NO_CONNECTION, STATE_FAILED_CONNECTION, STATE_OPENED_SOCKET, STATE_EXCHANGED_INTROS,
STATE_REJECTED, STATE_WAITING_LIST, STATE_CONNECTED, STATE_LOST_CONNECTION
}
The state of the connection.
enum NonBlockingConnectReturn { NON_BLOCKING_CONTINUE, NON_BLOCKING_CONNECTED, NON_BLOCKING_FAILED }
Public Types inherited from ArThread
enum Status
Public Member Functions
void addCycleCallback (ArFunctor *functor)
Adds a functor to call every cycle.
void addDisconnectOnErrorCB (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a call for when a disconnection has occured because of error.
bool addHandler (const char *name, ArFunctor1< ArNetPacket * > *functor)
Adds a callback functor for data packets received from the server.
void addServerShutdownCB (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a call for when the server shuts down.
ArClientBase ()
Constructor.
bool blockingConnect (const char *host, int port, bool log=true, const char *user=NULL, const char *password=NULL, const char *openOnIP=NULL)
Connect to a server.
bool dataExists (const char *name)
Sees if this data exists.
bool disconnect (void)
Disconnect from a server.
void disconnectSoon (void)
Disconnect from a server next time through the loop.
void enforceProtocolVersion (const char *protocolVersion, bool log=true)
Enforces the that the server is using this protocol version.
void enforceType (ArServerCommands::Type type, bool log=true)
Enforces that the robots that connect are this type.
unsigned int findCommandFromName (const char *name)
Returns the command number from the name.
void finishNonBlockingDisconnect ()
Finishes the process of disconnecting from the server.
void getClientKey (unsigned char key[CLIENT_KEY_LENGTH])
Gets a (probably) unique key that can be used to identify the client (after connection)
int getConnectTimeoutTime (void)
Gets the time allowed for connection.
const std::map< unsigned int, ArClientData * > * getDataMap (void)
Internal function get get the data map.
bool getDebugLogging (void)
Returns if we're doing debug logging or not.
const char * getHost (void)
Gets the name of the host we tried to connect to.
ArTime getLastPacketReceived (void)
Gets the last time a packet was received.
virtual const char * getLogPrefix () const
Returns the entire string used to prefix log entries for this client base.
const char * getName (ArNetPacket *packet, bool internalCall=false)
Gets the name of the data a packet is for.
const char * getName (unsigned int command, bool internalCall=false)
Gets the name of the data a command is.
int getPort ()
Get port we connected to (only valid if connected)
bool getReceivedArgRetList (void)
Gets if we received the list of arguments and.
bool getReceivedDataList (void)
Gets if we received the list of commands.
bool getReceivedGroupAndFlagsList (void)
Gets if we received the list of commands.
int getRejected (void)
Tells us the reason the connection was rejected (see ArServerCommands for details)
const char * getRejectedString (void)
Tells us the reason the connection was rejected (see ArServerCommands for details)
virtual const char * getRobotName () const
Returns the optional name of the connected robot for debugging purposes.
ClientState getState (void)
Gets the state of the client connection.
struct in_addr * getTcpAddr (void)
Internal function to get the socket (no one should need this)
ArSocket * getTcpSocket (void)
Internal function to get the tcp socket.
ArSocket * getUdpSocket (void)
Internal function to get the udp socket.
bool internalBlockingConnect (const char *host, int port, bool log, const char *user, const char *password, ArSocket *tcpSocket, const char *openOnIP=NULL)
Internal function that'll do the connection (mainly for switch connections)
NonBlockingConnectReturn internalNonBlockingConnectContinue (void)
Internal function that'll start the non blocking connection (mainly for switch connections)
NonBlockingConnectReturn internalNonBlockingConnectStart (const char *host, int port, bool log, const char *user, const char *password, ArSocket *tcpSocket, const char *openOnIP=NULL)
Internal function that'll start the non blocking connection (mainly for switch connections)
bool isConnected (void)
virtual bool isStopped ()
Returns whether the client has been stopped (regardless of whether its in its own thread)
bool isTcpOnlyFromServer (void)
Returns whether we only get TCP data from the server not UDP.
bool isTcpOnlyToServer (void)
Returns whether we only send TCP data to the server.
void logDataList (void)
Print out or data with descriptions.
void logTracking (bool terse)
Logs the tracking information (packet and byte counts)
void loopOnce (void)
Run the loop once.
void processPacket (ArNetPacket *packet, bool tcp)
Process the packet wherever it came from.
void processPacketUdp (ArNetPacket *packet, struct sockaddr_in *sin)
Process a packet from udp (just hands off to processPacket)
void remCycleCallback (ArFunctor *functor)
Removes a functor called every cycle.
void remDisconnectOnErrorCB (ArFunctor *functor)
Removes a call for when a disconnection has occured because of error.
bool remHandler (const char *name, ArFunctor1< ArNetPacket * > *functor)
Removes a functor for data packets received from the server.
void remServerShutdownCB (ArFunctor *functor)
Removes a call for when the server shuts down.
bool request (const char *name, long mSec, ArNetPacket *packet=NULL)
Request some data every mSec milliseconds.
bool requestByCommand (unsigned int command, long mSec, ArNetPacket *packet=NULL)
Request some data every mSec milliseconds by command not name.
bool requestOnce (const char *name, ArNetPacket *packet=NULL, bool quiet=false)
Request some data (or send a command) just once.
bool requestOnceByCommand (unsigned int command, ArNetPacket *packet=NULL)
Request some data (or send a command) just once by command not name.
bool requestOnceByCommandUdp (unsigned int command, ArNetPacket *packet=NULL)
Request some data (or send a command) just once by command not name.
bool requestOnceUdp (const char *name, ArNetPacket *packet=NULL, bool quiet=false)
Request some data (or send a command) just once by UDP.
bool requestOnceWithDouble (const char *name, double val)
Request some data or send a command once with a double value as an argument.
bool requestOnceWithInt16 (const char *name, ArTypes::Byte2 val)
Request some data or send a command once with a 16-bit (2-byte) integer value as an argument.
bool requestOnceWithInt32 (const char *name, ArTypes::Byte4 val)
Request some data or send a command once with a 32-bit (4-byte) integer value as an argument.
bool requestOnceWithString (const char *name, const char *str)
Request some data or send a command once with a string as argument.
bool requestStop (const char *name)
Don't want this data anymore.
bool requestStopByCommand (unsigned int command)
Don't want this data anymore, by command not name.
void resetTracking (void)
Clears the tracking information (resets counters)
virtual void run (void)
Runs the client in this thread.
virtual void runAsync (void)
Runs the client in its own thread.
virtual void * runThread (void *arg)
bool sendPacketTcp (ArNetPacket *packet)
Send a packet over TCP.
bool sendPacketUdp (ArNetPacket *packet)
Send a packet over UDP (unless client only wants tcp then sends over tcp)
void setBackupTimeout (double timeoutInMins)
Sets the backup timeout.
void setConnectTimeoutTime (int sec)
Sets the time to allow for connection (default 3)
virtual void setRobotName (const char *name, bool debugLogging=false, int robotId=0)
Sets the optional name of the connected robot for debugging purposes.
void setServerKey (const char *serverKey, bool log=true)
Sets the 'key' needed to connect to the server.
void setTcpOnlyFromServer (void)
Sets it so we only get TCP data from the server not UDP.
void setTcpOnlyToServer (void)
Sets it so we only send TCP data to the server.
bool startNonBlockingDisconnect ()
Starts the process of disconnecting from the server.
virtual void stopRunning (void)
Stops the thread and sets the stopped flag.
bool wasRejected (void)
virtual ~ArClientBase ()
Destructor.
Public Member Functions inherited from ArASyncTask
ArASyncTask ()
virtual int create (bool joinable=true, bool lowerPriority=true)
virtual const char * getThreadActivity (void)
virtual void * runInThisThread (void *arg=0)
virtual ~ArASyncTask ()
Public Member Functions inherited from ArThread
ArThread (bool blockAllSignals=true)
ArThread (ThreadType thread, bool joinable, bool blockAllSignals=true)
ArThread (ArFunctor *func, bool joinable=true, bool blockAllSignals=true)
virtual void cancel (void)
virtual int create (ArFunctor *func, bool joinable=true, bool lowerPriority=true)
virtual int detach (void)
bool getBlockAllSignals (void)
virtual ArFunctor * getFunc (void) const
virtual bool getJoinable (void) const
virtual ThreadType getOSThread (void) const
virtual bool getRunning (void) const
virtual bool getRunningWithLock (void)
virtual const ThreadType * getThread (void) const
virtual const char * getThreadName (void)
virtual bool isThreadFinished () const
virtual bool isThreadStarted () const
virtual int join (void **ret=NULL)
int lock (void)
virtual void logThreadInfo (void)
virtual void setRunning (bool running)
virtual void setThreadName (const char *name)
virtual void threadFinished (void)
virtual void threadStarted (void)
int tryLock (void)
int unlock (void)
virtual ~ArThread ()
Protected Types
enum NonBlockingConnectState { NON_BLOCKING_STATE_NONE, NON_BLOCKING_STATE_TCP, NON_BLOCKING_STATE_UDP }
Protected Member Functions
void buildList (ArNetPacket *packet)
void clear (void)
bool internalConnect (const char *host, int port, bool obsolete, const char *openOnIP)
void internalStartUdp (void)
void internalSwitchState (ClientState state)
bool setupPacket (ArNetPacket *packet)
void trackPacketReceived (ArNetPacket *packet, bool tcp)
void trackPacketSent (ArNetPacket *packet, bool tcp)
Protected Attributes
long myAuthKey
double myBackupTimeout
ArMutex myCallbackMutex
unsigned char myClientKey [16]
ArMutex myClientMutex
ArMutex myCycleCallbackMutex
std::list< ArFunctor * > myCycleCallbacks
ArMutex myDataMutex
bool myDebugLogging
std::list< ArFunctor * > myDisconnectOnErrorCBList
bool myDisconnectSoon
std::string myEnforceProtocolVersion
If we're enforcing the version of the protocol or not.
ArServerCommands::Type myEnforceType
if we're a particular type
std::string myHost
std::map< unsigned int, ArClientData * > myIntDataMap
long myIntroKey
bool myIsRunningAsync
bool myIsStartedDisconnect
bool myIsStopped
ArTime myLastPacketReceived
std::string myLogPrefix
Optional prefix to be inserted at the start of log messages.
ArMutex myMapsMutex
std::map< std::string, unsigned int > myNameIntMap
NonBlockingConnectState myNonBlockingConnectState
ArMutex myPacketTrackingMutex
std::string myPassword
int myPort
ArFunctor2C< ArClientBase, ArNetPacket *, bool > myProcessPacketCB
ArFunctor2C< ArClientBase, ArNetPacket *, struct sockaddr_in * > myProcessPacketUdpCB
bool myQuiet
bool myReceivedArgRetList
bool myReceivedDataList
bool myReceivedGroupAndFlagsList
int myRejected
char myRejectedString [32000]
std::string myRobotName
Optional robot name for logging.
std::string myServerKey
unsigned int myServerReportedUdpPort
unsigned int myServerSentUdpPort
std::list< ArFunctor * > myServerShutdownCBList
ArTime myStartedConnection
ArTime myStartedShutdown
ArTime myStartedUdpConnection
ClientState myState
ArMutex myStateMutex
ArTime myStateStarted
bool myTcpOnlyFrom
bool myTcpOnlyTo
ArNetPacketReceiverTcp myTcpReceiver
ArNetPacketSenderTcp myTcpSender
ArSocket myTcpSocket
int myTimeoutTime
std::map< unsigned int, Tracker * > myTrackingReceivedMap
std::map< unsigned int, Tracker * > myTrackingSentMap
ArTime myTrackingStarted
bool myUdpConfirmedFrom
bool myUdpConfirmedTo
unsigned int myUdpPort
ArNetPacketReceiverUdp myUdpReceiver
struct sockaddr_in myUdpSin
bool myUdpSinValid
ArSocket myUdpSocket
std::string myUser
ArLog::LogLevel myVerboseLogLevel
Protected Attributes inherited from ArThread
bool myRunning
Additional Inherited Members
Static Public Member Functions inherited from ArThread
static void cancelAll (void)
static ArLog::LogLevel getLogLevel (void)
static ThreadType getThisOSThread (void)
static const ThreadType * getThisThread (void)
static const char * getThisThreadName (void)
static void init (void)
static void joinAll (void)
static ThreadType osSelf (void)
static ArThread * self (void)
static void setLogLevel (ArLog::LogLevel level)
static void shutdown ()
static void stopAll ()
static void yieldProcessor (void)
Public Attributes inherited from ArThread
STATUS_ALREADY_DETATCHED
STATUS_FAILED
STATUS_INVALID
STATUS_JOIN_SELF
STATUS_NO_SUCH_THREAD
STATUS_NORESOURCE
Detailed Description
The base client class.
You need to connect a client to a server using blockingConnect() with the address for the server. Then you should add handlers to the client to receive information from the server (with addHandler(), request(), and requestOnce()). Then call run() or runAsync() to begin processing communications. You can also add a callback that will get called every cycle of the client.
User and password information may be required by the server. For details on that see ArServerBase. The most important thing is the modification to blockingConnect(), it can now take a user and password argument and upon failure you'll want to check wasRejected() to determine whether the client couldn't find the server or if the user and password were rejected. Another relevant function is setServerKey() to set the key (string of text) we need to connect to the server.
This class is threadsafe for access and does not need locking to call accessor methods. However, when run in a new thread using runAsync(), any cycle callbacks added with addCycleCallback(), and any data handlers added by addHandler(), will be called from that thread, and mutexes or other synchronization methods may be needed for those callback functions to interact with other threads. For example, if your data handler callback function stores some data received in a variable, and a different thread in the application will also be reading the data from that variable, a mutex or other synchronization technique should be used to prevent simultaneous access to that variable.
Examples:
getVideoExample.cpp, ptzCameraClientExample.cpp, and robotUpdateExample.cpp.
Member Enumeration Documentation
anonymous enum
Enumerator
CLIENT_KEY_LENGTH
enum ArClientBase::ClientState
The state of the connection.
Enumerator
STATE_NO_CONNECTION
The client has not connected.
STATE_FAILED_CONNECTION
The client tried to connect and failed.
STATE_OPENED_SOCKET
Client opened socket, waiting for intro from srvr.
STATE_EXCHANGED_INTROS
Client and server have exchanged introductions.
STATE_REJECTED
Client was rejected by server.
STATE_WAITING_LIST
Client was connected to server, waiting for list.
STATE_CONNECTED
Client is connected to server.
STATE_LOST_CONNECTION
Client lost connection to server.
enum ArClientBase::NonBlockingConnectReturn
Enumerator
NON_BLOCKING_CONTINUE
Client didn't connect or fail to connect yet.
NON_BLOCKING_CONNECTED
Client connected.
NON_BLOCKING_FAILED
Client couldn't connect.
enum ArClientBase::NonBlockingConnectState protected
Enumerator
NON_BLOCKING_STATE_NONE
NON_BLOCKING_STATE_TCP
NON_BLOCKING_STATE_UDP
Constructor & Destructor Documentation
ArClientBase::ArClientBase ()
Constructor.
References clear(), myCallbackMutex, myClientMutex, myCycleCallbackMutex, myDataMutex, myDebugLogging, myEnforceType, myMapsMutex, myNonBlockingConnectState, myPacketTrackingMutex, myProcessPacketCB, myProcessPacketUdpCB, myStateMutex, myTcpReceiver, myTcpSender, myTcpSocket, myUdpReceiver, myUdpSocket, myVerboseLogLevel, NON_BLOCKING_STATE_NONE, ArNetPacketSenderTcp::setDebugLogging(), ArMutex::setLogName(), ArNetPacketReceiverUdp::setProcessPacketCB(), ArNetPacketReceiverTcp::setProcessPacketCB(), setRobotName(), ArNetPacketSenderTcp::setSocket(), ArNetPacketReceiverUdp::setSocket(), ArNetPacketReceiverTcp::setSocket(), ArThread::setThreadName(), ArServerCommands::TYPE_UNSPECIFIED, and ArLog::Verbose.
ArClientBase::~ArClientBase () virtual
Destructor.
References clear().
Member Function Documentation
void ArClientBase::addCycleCallback (ArFunctor * functor)
Adds a functor to call every cycle.
cycleCallbacks are called every cycle, and are in no particular order, since all they should do is send packets, never any processing
You cannot add a cycle callback from within a cycle or it will deadlock
Parameters
functor callback to add
References ArMutex::lock(), myCycleCallbackMutex, myCycleCallbacks, and ArMutex::unlock().
Referenced by ArClientRatioDrive::ArClientRatioDrive(), ArHybridForwarderVideo::finishConstructor(), and getPort().
void ArClientBase::addDisconnectOnErrorCB (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a call for when a disconnection has occured because of error.
Parameters
functor functor created from ArFunctorC which refers to the function to call.
position whether to place the functor first or last
See also
remDisconnectOnErrorCB
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, myDisconnectOnErrorCBList, myLogPrefix, ArLog::Terse, and ArMutex::unlock().
Referenced by ArMapChanger::ArMapChanger(), and getPort().
bool ArClientBase::addHandler (const char * name, ArFunctor1< ArNetPacket * > * functor)
Adds a callback functor for data packets received from the server.
This adds a functor that will be called with a packet whenever a packet for that name arrives.
Note
Do not call addHandler() or remHandler() from within a handler callback, since that will possibly interfere with ArClientBase's iteration over the handler list as it invokes handhlers.
Note that if you try and add a handler for a specific piece of data from within a handler for that specific piece of data you'll deadlock.
Parameters
name the name of the data to use with this functor
functor the functor to call with the packet when data with this name arrives
Returns
false is returned if this name doesn't exist in the data
Python Wrapper Library: Pass a function taking one argument for
functor
Java Wrapper Library: Use a subclass of ArFunctor_NetPacket for the
functor object.
Examples:
getVideoExample.cpp, and ptzCameraClientExample.cpp.
References ArClientData::addFunctor(), ArClientData::getFunctorList(), ArMutex::lock(), ArClientData::lockFunctorList(), ArLog::log(), myIntDataMap, myLogPrefix, myMapsMutex, myNameIntMap, myVerboseLogLevel, ArLog::Normal, ArMutex::unlock(), and ArClientData::unlockFunctorList().
Referenced by ArCentralForwarder::addHandler(), ArClientDeleteFileOnServer::ArClientDeleteFileOnServer(), ArClientFileFromClient::ArClientFileFromClient(), ArClientFileLister::ArClientFileLister(), ArClientFileToClient::ArClientFileToClient(), ArClientHandlerCamera::ArClientHandlerCamera(), ArMapChanger::ArMapChanger(), ArHybridForwarderVideo::finishConstructor(), ArCentralForwarder::gatheringCallOnce(), getState(), main(), OutputHandler::OutputHandler(), ArClientHandlerConfig::requestConfigFromServer(), ArClientHandlerConfig::requestLastEditablePriorityFromServer(), and ArClientHandlerRobotUpdate::requestUpdates().
void ArClientBase::addServerShutdownCB (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a call for when the server shuts down.
Parameters
functor functor created from ArFunctorC which refers to the function to call.
position whether to place the functor first or last
See also
remServerShutdownCB
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, myLogPrefix, myServerShutdownCBList, ArLog::Terse, and ArMutex::unlock().
Referenced by ArMapChanger::ArMapChanger(), and getPort().
bool ArClientBase::blockingConnect (const char * host, int port, bool log = true, const char * user = NULL, const char * password = NULL, const char * openOnIP = NULL)
Connect to a server.
Parameters
host the host to connect to
port the port to connect on
log whether to log our connection information using ArLog or not. Keeping the default value of true is recommended (disabling logging is usually only for internal and unusual uses). This setting also applies to logging disconnections and some other I/O events as well.
user user name, or NULL for none.
password password (cleartext), or NULL for none.
openOnIP address of the local network interface to use for the outgoing connection, or NULL for any/all.
References internalBlockingConnect().
Referenced by ArHybridForwarderVideo::ArHybridForwarderVideo(), ArClientSimpleConnector::connectClient(), and main().
void ArClientBase::buildList (ArNetPacket * packet) protected
References ArClientData::addDataFlags(), ArBasePacket::bufToStr(), ArBasePacket::bufToUByte2(), ArNetPacket::getCommand(), getName(), ArServerCommands::LIST, ArServerCommands::LISTARGRET, ArServerCommands::LISTARGRETSINGLE, ArServerCommands::LISTGROUPANDFLAGS, ArServerCommands::LISTGROUPANDFLAGSSINGLE, ArServerCommands::LISTSINGLE, ArLog::log(), myIntDataMap, myLogPrefix, myNameIntMap, myReceivedArgRetList, myReceivedDataList, myReceivedGroupAndFlagsList, myVerboseLogLevel, ArLog::Normal, ArClientData::setArgRetDescs(), ArClientData::setCommandGroup(), and ArLog::Terse.
Referenced by processPacket().
void ArClientBase::clear (void) protected
MPL adding this since these look leaked
References ArUtil::deleteSetPairs(), internalSwitchState(), myDisconnectSoon, myIntDataMap, myIsRunningAsync, myIsStartedDisconnect, myIsStopped, myLastPacketReceived, myNameIntMap, myQuiet, myReceivedArgRetList, myReceivedDataList, myReceivedGroupAndFlagsList, myRejected, myRejectedString, myServerReportedUdpPort, myTcpOnlyFrom, myTcpOnlyTo, myTimeoutTime, myTrackingReceivedMap, myTrackingSentMap, myUdpConfirmedFrom, myUdpConfirmedTo, ArTime::setToNow(), and STATE_NO_CONNECTION.
Referenced by ArClientBase(), internalNonBlockingConnectStart(), and ~ArClientBase().
bool ArClientBase::dataExists (const char * name)
Sees if this data exists.
Parameters
name the name to stop sending
Examples:
getVideoExample.cpp.
References ArMutex::lock(), myMapsMutex, myNameIntMap, and ArMutex::unlock().
Referenced by ArClientFileLister::ArClientFileLister(), ArMapChanger::ArMapChanger(), ArClientHandlerConfig::canRequestDefaults(), ArCentralForwarder::dataExists(), ArHybridForwarderVideo::finishConstructor(), ArCentralForwarder::gatheringCallOnce(), ArClientFileLister::getDirListing(), getState(), ArClientFileLister::isAvailable(), ArClientFileToClient::isAvailable(), ArClientFileFromClient::isAvailable(), ArClientDeleteFileOnServer::isAvailable(), ArClientFileFromClient::isAvailableFast(), ArClientFileToClient::isAvailableSetTimestamp(), ArClientFileFromClient::isAvailableSetTimestamp(), ArClientFileFromClient::isAvailableSlow(), ArClientHandlerConfig::isLastEditablePriorityAvailable(), main(), OutputHandler::OutputHandler(), ArClientFileFromClient::putFileToDirectory(), ArClientHandlerConfig::requestConfigFromServer(), ArClientHandlerConfig::requestLastEditablePriorityFromServer(), ArClientHandlerRobotUpdate::requestUpdates(), and ArClientHandlerConfig::saveConfigToServer().
bool ArClientBase::disconnect (void)
Disconnect from a server.
This method blocks while the connection is being shutdown.
Examples:
robotUpdateExample.cpp.
References finishNonBlockingDisconnect(), ArUtil::sleep(), and startNonBlockingDisconnect().
Referenced by gotConfig(), main(), processPacket(), and ArCentralForwarder::~ArCentralForwarder().
void ArClientBase::disconnectSoon (void)
Disconnect from a server next time through the loop.
This method does not block while the connection is being shutdown, and the disconnect only happens the next time the client base is in its loop
References myDisconnectSoon.
void ArClientBase::enforceProtocolVersion (const char * protocolVersion, bool log = true)
Enforces the that the server is using this protocol version.
References ArMutex::lock(), ArLog::log(), myDataMutex, myEnforceProtocolVersion, myLogPrefix, ArLog::Normal, and ArMutex::unlock().
Referenced by getPort(), processPacket(), and ArCentralForwarder::startingCallOnce().
void ArClientBase::enforceType (ArServerCommands::Type type, bool log = true)
Enforces that the robots that connect are this type.
References ArMutex::lock(), ArLog::log(), myDataMutex, myEnforceType, myLogPrefix, ArLog::Normal, ArServerCommands::toString(), and ArMutex::unlock().
Referenced by getPort(), and ArCentralForwarder::startingCallOnce().
unsigned int ArClientBase::findCommandFromName (const char * name)
Returns the command number from the name.
Parameters
name the name of the data to find the command of
Returns
0 if there is no command of that name, the command number otherwise
References ArMutex::lock(), ArLog::log(), myLogPrefix, myMapsMutex, myNameIntMap, ArLog::Normal, and ArMutex::unlock().
Referenced by getDataMap(), request(), ArCentralForwarder::requestOnce(), requestOnce(), ArCentralForwarder::requestOnceUdp(), requestOnceUdp(), requestOnceWithDouble(), requestOnceWithInt16(), requestOnceWithInt32(), requestOnceWithString(), and requestStop().
void ArClientBase::finishNonBlockingDisconnect ()
Finishes the process of disconnecting from the server.
This method should be used in conjunction with startNonBlockingDisconnect in threads that should not block (such as the main GUI thread).
References ArSocket::close(), myState, myTcpSocket, myUdpSocket, and STATE_NO_CONNECTION.
Referenced by disconnect(), getPort(), and loopOnce().
void ArClientBase::getClientKey (unsigned char key[CLIENT_KEY_LENGTH])
Gets a (probably) unique key that can be used to identify the client (after connection)
NOTE that this is only valid AFTER the client is connected.
References myClientKey.
Referenced by getPort().
int ArClientBase::getConnectTimeoutTime (void)
Gets the time allowed for connection.
Returns
This value controls how long the client will give to connect, it is the argument in number of seconds... if <= 0 then no timeout will take place.
References myTimeoutTime.
Referenced by getPort().
const std::map<unsigned int, ArClientData *>* ArClientBase::getDataMap (void) inline
Internal function get get the data map.
References findCommandFromName(), myIntDataMap, requestByCommand(), requestOnceByCommand(), requestOnceByCommandUdp(), and requestStopByCommand().
Referenced by ArCentralForwarder::gatheringCallOnce().
bool ArClientBase::getDebugLogging (void)
Returns if we're doing debug logging or not.
References myDebugLogging.
const char * ArClientBase::getHost (void)
Gets the name of the host we tried to connect to.
Examples:
ptzCameraClientExample.cpp, and robotUpdateExample.cpp.
References ArMutex::lock(), myDataMutex, myHost, and ArMutex::unlock().
Referenced by getState(), and main().
ArTime ArClientBase::getLastPacketReceived (void)
Gets the last time a packet was received.
References ArMutex::lock(), myDataMutex, myLastPacketReceived, and ArMutex::unlock().
Referenced by getPort().
const char * ArClientBase::getLogPrefix () const virtual
Returns the entire string used to prefix log entries for this client base.
References myLogPrefix.
const char * ArClientBase::getName (ArNetPacket * packet, bool internalCall = false)
Gets the name of the data a packet is for.
References ArNetPacket::getCommand().
Referenced by buildList(), getPort(), ArCentralForwarder::internalRequestChanged(), ArCentralForwarder::internalRequestOnce(), logTracking(), ArCentralForwarder::receiveData(), and setupPacket().
const char * ArClientBase::getName (unsigned int command, bool internalCall = false)
Gets the name of the data a command is.
References ArMutex::lock(), myIntDataMap, myMapsMutex, and ArMutex::unlock().
int ArClientBase::getPort () inline
Get port we connected to (only valid if connected)
References addCycleCallback(), addDisconnectOnErrorCB(), addServerShutdownCB(), CLIENT_KEY_LENGTH, enforceProtocolVersion(), enforceType(), finishNonBlockingDisconnect(), getClientKey(), getConnectTimeoutTime(), getLastPacketReceived(), getName(), isStopped(), isTcpOnlyFromServer(), isTcpOnlyToServer(), ArListPos::LAST, ArMutex::lock(), log(), logDataList(), logTracking(), loopOnce(), myDataMutex, myPort, processPacket(), processPacketUdp(), remCycleCallback(), remDisconnectOnErrorCB(), remServerShutdownCB(), resetTracking(), run(), runAsync(), runThread(), sendPacketTcp(), sendPacketUdp(), setBackupTimeout(), setConnectTimeoutTime(), setServerKey(), setTcpOnlyFromServer(), setTcpOnlyToServer(), sin(), startNonBlockingDisconnect(), stopRunning(), and ArMutex::unlock().
bool ArClientBase::getReceivedArgRetList (void) inline
Gets if we received the list of arguments and.
References myReceivedArgRetList.
Referenced by ArCentralForwarder::gatheringCallOnce().
bool ArClientBase::getReceivedDataList (void) inline
Gets if we received the list of commands.
References myReceivedDataList.
Referenced by ArCentralForwarder::gatheringCallOnce().
bool ArClientBase::getReceivedGroupAndFlagsList (void) inline
Gets if we received the list of commands.
References myReceivedGroupAndFlagsList.
Referenced by ArCentralForwarder::gatheringCallOnce().
int ArClientBase::getRejected (void) inline
Tells us the reason the connection was rejected (see ArServerCommands for details)
References myRejected.
const char* ArClientBase::getRejectedString (void) inline
Tells us the reason the connection was rejected (see ArServerCommands for details)
References myRejectedString.
const char * ArClientBase::getRobotName (void) const virtual
Returns the optional name of the connected robot for debugging purposes.
References myRobotName.
Referenced by ArMapChanger::sendMapChanges().
ClientState ArClientBase::getState (void) inline
Gets the state of the client connection.
References addHandler(), dataExists(), getHost(), myState, remHandler(), request(), requestOnce(), requestOnceUdp(), requestOnceWithDouble(), requestOnceWithInt16(), requestOnceWithInt32(), requestOnceWithString(), and requestStop().
struct in_addr* ArClientBase::getTcpAddr (void) inline
Internal function to get the socket (no one should need this)
References ArSocket::inAddr(), internalBlockingConnect(), internalNonBlockingConnectContinue(), internalNonBlockingConnectStart(), log(), and myTcpSocket.
ArSocket* ArClientBase::getTcpSocket (void) inline
Internal function to get the tcp socket.
References myTcpSocket.
Referenced by ArClientSwitchManager::clientSwitch(), ArCentralManager::forwarderServerClientRemovedCallback(), ArCentralManager::netClientList(), ArCentralManager::runThread(), and ArClientSwitchManager::runThread().
ArSocket* ArClientBase::getUdpSocket (void) inline
Internal function to get the udp socket.
References myUdpSocket.
bool ArClientBase::internalBlockingConnect (const char * host, int port, bool log, const char * user, const char * password, ArSocket * tcpSocket, const char * openOnIP = NULL)
Internal function that'll do the connection (mainly for switch connections)
References internalNonBlockingConnectContinue(), internalNonBlockingConnectStart(), NON_BLOCKING_CONNECTED, NON_BLOCKING_CONTINUE, and ArUtil::sleep().
Referenced by blockingConnect(), and getTcpAddr().
bool ArClientBase::internalConnect (const char * host, int port, bool obsolete, const char * openOnIP) protected
References ArSocket::connect(), internalStartUdp(), internalSwitchState(), ArLog::log(), myDebugLogging, myLogPrefix, myQuiet, myTcpSocket, myUdpPort, myVerboseLogLevel, ArLog::Normal, ArSocket::setNonBlock(), STATE_FAILED_CONNECTION, STATE_OPENED_SOCKET, and ArLog::Terse.
Referenced by internalNonBlockingConnectStart().
ArClientBase::NonBlockingConnectReturn ArClientBase::internalNonBlockingConnectContinue (void)
Internal function that'll start the non blocking connection (mainly for switch connections)
References ArSocket::close(), ArNetPacket::empty(), internalSwitchState(), ArMutex::lock(), ArLog::log(), loopOnce(), ArTime::mSecSince(), myDataMutex, myDebugLogging, myLogPrefix, myNonBlockingConnectState, myQuiet, myStartedConnection, myStartedUdpConnection, myState, myTcpOnlyFrom, myTcpOnlyTo, myTcpSocket, myTimeoutTime, myUdpConfirmedFrom, myUdpConfirmedTo, myUdpSocket, myVerboseLogLevel, NON_BLOCKING_CONNECTED, NON_BLOCKING_CONTINUE, NON_BLOCKING_FAILED, NON_BLOCKING_STATE_NONE, NON_BLOCKING_STATE_TCP, NON_BLOCKING_STATE_UDP, ArLog::Normal, sendPacketTcp(), ArNetPacket::setCommand(), ArTime::setToNow(), STATE_CONNECTED, STATE_FAILED_CONNECTION, STATE_LOST_CONNECTION, STATE_NO_CONNECTION, STATE_REJECTED, ArClientCommands::TCP_ONLY, ArLog::Terse, and ArMutex::unlock().
Referenced by ArCentralForwarder::connectingCallOnce(), getTcpAddr(), and internalBlockingConnect().
ArClientBase::NonBlockingConnectReturn ArClientBase::internalNonBlockingConnectStart (const char * host, int port, bool log, const char * user, const char * password, ArSocket * tcpSocket, const char * openOnIP = NULL)
Internal function that'll start the non blocking connection (mainly for switch connections)
References clear(), ArSocket::close(), internalConnect(), internalStartUdp(), internalSwitchState(), ArMutex::lock(), ArLog::log(), log(), loopOnce(), myDataMutex, myDebugLogging, myHost, myLogPrefix, myNonBlockingConnectState, myPassword, myPort, myQuiet, myStartedConnection, myState, myTcpReceiver, myTcpSocket, myUdpSocket, myUser, NON_BLOCKING_CONTINUE, NON_BLOCKING_FAILED, NON_BLOCKING_STATE_TCP, ArLog::Normal, ArNetPacketReceiverTcp::setQuiet(), ArTime::setToNow(), STATE_FAILED_CONNECTION, STATE_LOST_CONNECTION, STATE_NO_CONNECTION, STATE_OPENED_SOCKET, STATE_REJECTED, ArLog::Terse, ArSocket::transfer(), and ArMutex::unlock().
Referenced by getTcpAddr(), internalBlockingConnect(), and ArCentralForwarder::startingCallOnce().
void ArClientBase::internalStartUdp (void) protected
References ArSocket::create(), ArSocket::findValidPort(), ArSocket::inAddr(), ArSocket::inPort(), ArLog::log(), myDebugLogging, myLogPrefix, myQuiet, myTcpOnlyFrom, myTcpOnlyTo, myTcpSocket, myUdpPort, myUdpSin, myUdpSinValid, myUdpSocket, ArSocket::netToHostOrder(), ArSocket::setLinger(), ArSocket::setNonBlock(), and ArLog::Terse.
Referenced by internalConnect(), and internalNonBlockingConnectStart().
void ArClientBase::internalSwitchState (ClientState state) protected
References myState, myStateStarted, and ArTime::setToNow().
Referenced by clear(), internalConnect(), internalNonBlockingConnectContinue(), internalNonBlockingConnectStart(), loopOnce(), and processPacket().
bool ArClientBase::isConnected (void) inline
Returns
true if we're connected to a server
References myState, and STATE_CONNECTED.
Referenced by ArCentralForwarder::connectedCallOnce(), ArHybridForwarderVideo::finishConstructor(), and ArCentralForwarder::~ArCentralForwarder().
bool ArClientBase::isStopped () virtual
Returns whether the client has been stopped (regardless of whether its in its own thread)
References myIsStopped.
Referenced by getPort().
bool ArClientBase::isTcpOnlyFromServer (void)
Returns whether we only get TCP data from the server not UDP.
References ArMutex::lock(), myDataMutex, myTcpOnlyFrom, and ArMutex::unlock().
Referenced by ArCentralForwarder::connectedCallOnce(), and getPort().
bool ArClientBase::isTcpOnlyToServer (void)
Returns whether we only send TCP data to the server.
References ArMutex::lock(), myDataMutex, myTcpOnlyTo, and ArMutex::unlock().
Referenced by ArCentralForwarder::connectedCallOnce(), and getPort().
void ArClientBase::logDataList (void)
Print out or data with descriptions.
References ArClientData::getArgumentDescription(), ArClientData::getCommand(), ArClientData::getCommandGroup(), ArClientData::getDataFlagsString(), ArClientData::getDescription(), ArClientData::getFunctorList(), ArClientData::getName(), ArClientData::getReturnDescription(), ArMutex::lock(), ArLog::log(), myIntDataMap, myLogPrefix, myMapsMutex, myVerboseLogLevel, ArLog::Terse, and ArMutex::unlock().
Referenced by ArClientSimpleConnector::connectClient(), getPort(), InputHandler::listData(), and main().
void ArClientBase::logTracking (bool terse)
Logs the tracking information (packet and byte counts)
References ArSocket::getBytesRecvd(), ArSocket::getBytesSent(), getName(), ArSocket::getRecvs(), ArSocket::getSends(), ArMutex::lock(), ArLog::log(), ArClientBase::Tracker::myBytesTcp, ArClientBase::Tracker::myBytesUdp, myDataMutex, myLogPrefix, ArClientBase::Tracker::myPacketsTcp, ArClientBase::Tracker::myPacketsUdp, myPacketTrackingMutex, myTcpSocket, myTrackingReceivedMap, myTrackingSentMap, myTrackingStarted, myUdpSocket, ArTime::secSince(), ArLog::Terse, and ArMutex::unlock().
Referenced by getPort(), InputHandler::logTrackingTerse(), and InputHandler::logTrackingVerbose().
void ArClientBase::loopOnce (void)
Run the loop once.
References ArSocket::close(), finishNonBlockingDisconnect(), internalSwitchState(), ArMutex::lock(), ArLog::log(), ArTime::mSecSince(), myCallbackMutex, myCycleCallbackMutex, myCycleCallbacks, myDebugLogging, myDisconnectOnErrorCBList, myDisconnectSoon, myIsRunningAsync, myIsStartedDisconnect, myLogPrefix, myQuiet, myStartedShutdown, myState, myTcpOnlyFrom, myTcpReceiver, myTcpSender, myTcpSocket, myUdpReceiver, myUdpSocket, ArLog::Normal, ArNetPacketReceiverUdp::readData(), ArNetPacketReceiverTcp::readData(), ArNetPacketSenderTcp::sendData(), ArTime::setToNow(), ArUtil::sleep(), startNonBlockingDisconnect(), STATE_FAILED_CONNECTION, STATE_LOST_CONNECTION, STATE_NO_CONNECTION, STATE_REJECTED, stopRunning(), and ArMutex::unlock().
Referenced by ArCentralForwarder::connectedCallOnce(), ArCentralForwarder::gatheringCallOnce(), getPort(), gotConfig(), internalNonBlockingConnectContinue(), internalNonBlockingConnectStart(), ArClientSwitchManager::runThread(), and runThread().
void ArClientBase::processPacket (ArNetPacket * packet, bool tcp)
Process the packet wherever it came from.
see if we've opened the socket and this is an intro
References ArBasePacket::bufToByte2(), ArBasePacket::bufToStr(), ArBasePacket::bufToUByte2(), ArBasePacket::bufToUByte4(), buildList(), ArBasePacket::byteToBuf(), ArServerCommands::CONNECTED, ArBasePacket::dataToBuf(), disconnect(), ArNetPacket::empty(), enforceProtocolVersion(), ArBasePacket::getBuf(), ArNetPacket::getCommand(), ArClientData::getFunctorList(), ArBasePacket::getLength(), ArUtil::getTime(), ArSocket::hostToNetOrder(), internalSwitchState(), ArClientCommands::INTRODUCTION, ArServerCommands::INTRODUCTION, ArFunctor1< P1 >::invoke(), ArServerCommands::LIST, ArServerCommands::LISTARGRET, ArServerCommands::LISTARGRETSINGLE, ArServerCommands::LISTGROUPANDFLAGS, ArServerCommands::LISTGROUPANDFLAGSSINGLE, ArServerCommands::LISTSINGLE, ArMutex::lock(), ArClientData::lockFunctorList(), ArBasePacket::log(), ArLog::log(), md5_append(), md5_finish(), md5_init(), myAuthKey, myCallbackMutex, myClientKey, myDataMutex, myDebugLogging, myEnforceProtocolVersion, myEnforceType, myIntDataMap, myIntroKey, myLastPacketReceived, myLogPrefix, myMapsMutex, myPassword, myQuiet, myRejected, myRejectedString, myServerKey, myServerReportedUdpPort, myServerShutdownCBList, myState, myTcpOnlyFrom, myTcpOnlyTo, myUdpConfirmedTo, myUdpPort, myUdpSin, myUser, myVerboseLogLevel, ArLog::Normal, ArMath::random(), ArServerCommands::REJECTED, ArNetPacket::resetRead(), sendPacketTcp(), sendPacketUdp(), ArNetPacket::setCommand(), ArTime::setToNow(), ArServerCommands::SHUTDOWN, STATE_CONNECTED, STATE_EXCHANGED_INTROS, STATE_LOST_CONNECTION, STATE_OPENED_SOCKET, STATE_REJECTED, STATE_WAITING_LIST, stopRunning(), ArBasePacket::strToBuf(), ArClientCommands::TCP_ONLY, ArServerCommands::TCP_ONLY, ArLog::Terse, trackPacketReceived(), ArBasePacket::uByte2ToBuf(), ArBasePacket::uByte4ToBuf(), ArServerCommands::UDP_CONFIRMATION, ArServerCommands::UDP_INTRODUCTION, ArClientCommands::UDP_INTRODUCTION, ArMutex::unlock(), and ArClientData::unlockFunctorList().
Referenced by getPort(), ArServerBase::processPacket(), and processPacketUdp().
void ArClientBase::processPacketUdp (ArNetPacket * packet, struct sockaddr_in * sin)
Process a packet from udp (just hands off to processPacket)
References ArBasePacket::bufToByte4(), ArNetPacket::getCommand(), ArMutex::lock(), ArLog::log(), myDataMutex, myDebugLogging, myIntroKey, myLastPacketReceived, myLogPrefix, myQuiet, myServerReportedUdpPort, myState, myUdpConfirmedFrom, myUdpSin, myVerboseLogLevel, ArSocket::netToHostOrder(), ArLog::Normal, processPacket(), sendPacketTcp(), ArTime::setToNow(), STATE_CONNECTED, STATE_EXCHANGED_INTROS, STATE_WAITING_LIST, ArLog::Terse, ArClientCommands::UDP_CONFIRMATION, ArServerCommands::UDP_INTRODUCTION, and ArMutex::unlock().
Referenced by getPort().
void ArClientBase::remCycleCallback (ArFunctor * functor)
Removes a functor called every cycle.
cycleCallbacks are called every cycle, and are in no particular order, since all they should do is send packets, never any processing You cannot remove a cycle callback from within a cycle or it will deadlock
Parameters
functor callback to remove
References ArMutex::lock(), myCycleCallbackMutex, myCycleCallbacks, and ArMutex::unlock().
Referenced by getPort(), and ArClientRatioDrive::~ArClientRatioDrive().
void ArClientBase::remDisconnectOnErrorCB (ArFunctor * functor)
Removes a call for when a disconnection has occured because of error.
Parameters
functor the functor to remove from the list of connect callbacks
See also
addDisconnectOnErrorCB
References ArMutex::lock(), myCallbackMutex, myDisconnectOnErrorCBList, and ArMutex::unlock().
Referenced by getPort(), and ArMapChanger::~ArMapChanger().
bool ArClientBase::remHandler (const char * name, ArFunctor1< ArNetPacket * > * functor)
Removes a functor for data packets received from the server.
This removes a functor from being called with a packet whenever a packet for that name arrives.
Note
Do not call addHandler() or remHandler() from within a handler callback, since that will possibly interfere with ArClientBase's iteration over the handler list as it invokes handhlers.
Note that if you try and remove a handler for a specific piece of data from within a handler for that specific piece of data you'll deadlock.
Parameters
name the name of the data to use with this functor
functor the functor to call with the packet when data with this name arrives
Returns
false is returned if this name doesn't exist in the data
References ArMutex::lock(), ArClientData::lockFunctorList(), ArLog::log(), myIntDataMap, myLogPrefix, myMapsMutex, myNameIntMap, ArLog::Normal, ArClientData::remFunctor(), ArMutex::unlock(), and ArClientData::unlockFunctorList().
Referenced by getState(), ArCentralForwarder::remHandler(), ArClientHandlerConfig::requestConfigFromServer(), ArClientHandlerConfig::requestLastEditablePriorityFromServer(), ArClientHandlerRobotUpdate::stopUpdates(), and ArMapChanger::~ArMapChanger().
void ArClientBase::remServerShutdownCB (ArFunctor * functor)
Removes a call for when the server shuts down.
Parameters
functor the functor to remove from the list of connect callbacks
See also
addServerShutdownCB
References ArMutex::lock(), myCallbackMutex, myServerShutdownCBList, and ArMutex::unlock().
Referenced by getPort(), and ArMapChanger::~ArMapChanger().
bool ArClientBase::request (const char * name, long mSec, ArNetPacket * packet = NULL)
Request some data every mSec milliseconds.
This requests data from the server for the given name, at a given interval, optionally passing along data with the request.
Parameters
name the name of the data to request from the server
mSec request interval: the number of milliseconds we want a refresh on this data, if this number is 0 then the server will send the information as often as it is available; if -1, then the server will send the information only when it changes (for broadcast type packets)
packet a packet to use for the request, may contain data to use as parameters or arguments along with the request.
Examples:
getVideoExample.cpp, and ptzCameraClientExample.cpp.
References findCommandFromName(), ArLog::log(), myLogPrefix, myVerboseLogLevel, ArLog::Normal, and requestByCommand().
Referenced by ArMapChanger::ArMapChanger(), ArCentralForwarder::gatheringCallOnce(), getState(), handleStringsInfo(), main(), OutputHandler::OutputHandler(), ArClientHandlerRobotUpdate::requestUpdates(), and ArClientHandlerCamera::requestUpdates().
bool ArClientBase::requestByCommand (unsigned int command, long mSec, ArNetPacket * packet = NULL)
Request some data every mSec milliseconds by command not name.
This requests data from the server for the given name, at mSec milliseconds interval, optionally passing along data for the request.
Parameters
command the command number of the data to request
mSec the number of milliseconds we want a refresh on this data, if this number is 0 then the server will send the information as often as it is available; if -1, then the server will send the information only when it changes (for broadcast type packets)
packet the packet that contains the data to use as argument
References ArBasePacket::byte4ToBuf(), ArBasePacket::dataToBuf(), ArBasePacket::getBuf(), ArBasePacket::getLength(), ArBasePacket::getReadLength(), ArClientCommands::REQUEST, ArNetPacket::resetRead(), sendPacketTcp(), ArNetPacket::setCommand(), and ArBasePacket::uByte2ToBuf().
Referenced by getDataMap(), ArCentralForwarder::internalRequestChanged(), and request().
bool ArClientBase::requestOnce (const char * name, ArNetPacket * packet = NULL, bool quiet = false)
Request some data (or send a command) just once.
This requests the data from the server, but only once...
this is useful for things like video data that you don't want to clog up the bandwidth with... its also useful for things like sending commands
Parameters
name the name of the data to request
packet the packet that contains the data to use as argument
quiet a bool set to true to override the verbose logging of this method (generally for repeating requests); default is false to log.
Examples:
getVideoExample.cpp.
References findCommandFromName(), ArLog::log(), myLogPrefix, myVerboseLogLevel, and requestOnceByCommand().
Referenced by ArMapChanger::ArMapChanger(), ArClientFileFromClient::cancelPut(), ArHybridForwarderVideo::clientCycleCallback(), ArCentralForwarder::connectedCallOnce(), ArClientDeleteFileOnServer::deleteFileFromDirectory(), ArHybridForwarderVideo::finishConstructor(), ArCentralForwarder::gatheringCallOnce(), ArClientFileToClient::getFileFromDirectory(), getState(), main(), OutputHandler::OutputHandler(), ArClientFileFromClient::putFileToDirectory(), ArClientHandlerConfig::reloadConfigOnServer(), ArClientHandlerConfig::requestConfigDefaults(), ArClientHandlerConfig::requestConfigFromServer(), ArClientHandlerConfig::requestDefaultConfigFromServer(), ArClientHandlerConfig::requestLastEditablePriorityFromServer(), ArClientRatioDrive::safeDrive(), ArClientHandlerConfig::saveConfigToServer(), ArClientRatioDrive::sendInput(), ArMapChanger::sendPacketList(), ArClientRatioDrive::stop(), and ArClientRatioDrive::unsafeDrive().
bool ArClientBase::requestOnceByCommand (unsigned int command, ArNetPacket * packet = NULL)
Request some data (or send a command) just once by command not name.
This requests the data from the server, but only once...
this is useful for things like video data that you don't want to clog up the bandwidth with... its also useful for things like sending commands
Parameters
command the command number to request
packet the packet that contains the data to use as argument
References sendPacketTcp(), and ArNetPacket::setCommand().
Referenced by getDataMap(), ArCentralForwarder::internalRequestChanged(), ArCentralForwarder::internalRequestOnce(), and requestOnce().
bool ArClientBase::requestOnceByCommandUdp (unsigned int command, ArNetPacket * packet = NULL)
Request some data (or send a command) just once by command not name.
This requests the data from the server, but only once...
this is useful for things like video data that you don't want to clog up the bandwidth with... its also useful for things like sending commands
Parameters
command the command number to request
packet the packet that contains the data to use as argument
References myTcpOnlyTo, sendPacketTcp(), sendPacketUdp(), and ArNetPacket::setCommand().
Referenced by getDataMap(), ArCentralForwarder::internalRequestOnce(), and requestOnceUdp().
bool ArClientBase::requestOnceUdp (const char * name, ArNetPacket * packet = NULL, bool quiet = false)
Request some data (or send a command) just once by UDP.
Send one request over UDP.
For example, use this method for certain kinds of data where constant streaming would be undesirable (e.g. video images that might saturate the network), or for sending a simple command. Note that since the request is sent using UDP, you cannot assume it will get there or that you will get a response.
Parameters
name the name of the data to request
packet the packet that contains the data to use as argument
quiet If true, suppress verbose-level log message
References findCommandFromName(), ArLog::log(), myLogPrefix, myVerboseLogLevel, and requestOnceByCommandUdp().
Referenced by ArCentralForwarder::connectedCallOnce(), ArCentralForwarder::gatheringCallOnce(), and getState().
bool ArClientBase::requestOnceWithDouble (const char * name, double val)
Request some data or send a command once with a double value as an argument.
References ArNetPacket::doubleToBuf(), findCommandFromName(), ArLog::log(), myLogPrefix, myVerboseLogLevel, ArLog::Normal, and sendPacketTcp().
Referenced by getState().
bool ArClientBase::requestOnceWithInt16 (const char * name, ArTypes::Byte2 val)
Request some data or send a command once with a 16-bit (2-byte) integer value as an argument.
References ArBasePacket::byte2ToBuf(), findCommandFromName(), ArLog::log(), myLogPrefix, myVerboseLogLevel, ArLog::Normal, and sendPacketTcp().
Referenced by getState().
bool ArClientBase::requestOnceWithInt32 (const char * name, ArTypes::Byte4 val)
Request some data or send a command once with a 32-bit (4-byte) integer value as an argument.
References ArBasePacket::byte4ToBuf(), findCommandFromName(), ArLog::log(), myLogPrefix, myVerboseLogLevel, ArLog::Normal, and sendPacketTcp().
Referenced by getState().
bool ArClientBase::requestOnceWithString (const char * name, const char * str)
Request some data or send a command once with a string as argument.
This requests the data from the server, but only once...
this is useful for things like video data that you don't want to clog up the bandwidth with... its also useful for things like sending commands
Parameters
name the name of the data to request
str a string to send as the packet argument
References findCommandFromName(), ArLog::log(), myLogPrefix, myVerboseLogLevel, ArLog::Normal, sendPacketTcp(), and ArBasePacket::strToBuf().
Referenced by ArClientFileLister::getDirListing(), getState(), and ArClientHandlerConfig::requestSectionDefaults().
bool ArClientBase::requestStop (const char * name)
Don't want this data anymore.
Parameters
name the name to stop sending
References findCommandFromName(), ArLog::log(), myLogPrefix, myVerboseLogLevel, and requestStopByCommand().
Referenced by getState(), ArClientHandlerRobotUpdate::stopUpdates(), and OutputHandler::~OutputHandler().
bool ArClientBase::requestStopByCommand (unsigned int command)
Don't want this data anymore, by command not name.
Parameters
command the command number to stop
References ArClientCommands::REQUESTSTOP, sendPacketTcp(), ArNetPacket::setCommand(), and ArBasePacket::uByte2ToBuf().
Referenced by getDataMap(), ArCentralForwarder::internalRequestChanged(), and requestStop().
void ArClientBase::resetTracking (void)
Clears the tracking information (resets counters)
References ArMutex::lock(), myPacketTrackingMutex, myTcpSocket, myTrackingReceivedMap, myTrackingSentMap, myTrackingStarted, myUdpSocket, ArSocket::resetTracking(), ArTime::setToNow(), and ArMutex::unlock().
Referenced by getPort(), and InputHandler::resetTracking().
void ArClientBase::run (void) virtual
Runs the client in this thread.
Reimplemented from ArASyncTask.
Examples:
getVideoExample.cpp.
References ArASyncTask::runInThisThread().
Referenced by getPort(), and main().
void ArClientBase::runAsync (void) virtual
Runs the client in its own thread.
Reimplemented from ArASyncTask.
Examples:
ptzCameraClientExample.cpp, and robotUpdateExample.cpp.
References ArASyncTask::create(), and myIsRunningAsync.
Referenced by ArHybridForwarderVideo::ArHybridForwarderVideo(), getPort(), and main().
void * ArClientBase::runThread (void * arg) virtual
Implements ArASyncTask.
References loopOnce(), ArThread::myRunning, ArUtil::sleep(), ArThread::threadFinished(), and ArThread::threadStarted().
Referenced by getPort().
bool ArClientBase::sendPacketTcp (ArNetPacket * packet)
Send a packet over TCP.
References myLogPrefix, myTcpSender, ArNetPacketSenderTcp::sendPacket(), setupPacket(), and trackPacketSent().
Referenced by getPort(), internalNonBlockingConnectContinue(), processPacket(), processPacketUdp(), requestByCommand(), requestOnceByCommand(), requestOnceByCommandUdp(), requestOnceWithDouble(), requestOnceWithInt16(), requestOnceWithInt32(), requestOnceWithString(), requestStopByCommand(), setTcpOnlyFromServer(), and startNonBlockingDisconnect().
bool ArClientBase::sendPacketUdp (ArNetPacket * packet)
Send a packet over UDP (unless client only wants tcp then sends over tcp)
References ArBasePacket::getBuf(), ArBasePacket::getLength(), myUdpSin, myUdpSocket, ArSocket::sendTo(), setupPacket(), and trackPacketSent().
Referenced by getPort(), processPacket(), and requestOnceByCommandUdp().
void ArClientBase::setBackupTimeout (double timeoutInMins)
Sets the backup timeout.
Sets up the backup timeout, if there are packets to send to the server and they haven't been sent for longer than this then the connection is closed.
Less than 0 means this won't happen. If this is positive but less than 5 seconds then 5 seconds is used.
References myBackupTimeout, myTcpSender, and ArNetPacketSenderTcp::setBackupTimeout().
Referenced by ArCentralForwarder::connectedCallOnce(), and getPort().
void ArClientBase::setConnectTimeoutTime (int sec)
Sets the time to allow for connection (default 3)
Parameters
sec This value controls how long the client will give to connect, it is the argument in number of seconds... if <= 0 then no timeout will take place.
References ArMutex::lock(), myDataMutex, myTimeoutTime, and ArMutex::unlock().
Referenced by ArHybridForwarderVideo::ArHybridForwarderVideo(), and getPort().
void ArClientBase::setRobotName (const char * name, bool debugLogging = false, int robotId = 0) virtual
Sets the optional name of the connected robot for debugging purposes.
The robot name is used solely for log messages.
Parameters
name an optional char * name of the connected robot to be used in the log messages
debugLogging a bool set to true if log messages should be written at the Normal level, if false, then they are written as Verbose
robotId an optional int which can be appended to the robot name in the log messages; if 0, then only the robot name is logged
Examples:
ptzCameraClientExample.cpp, and robotUpdateExample.cpp.
References myDebugLogging, myLogPrefix, myRobotName, myTcpReceiver, myTcpSender, myVerboseLogLevel, ArLog::Normal, ArNetPacketSenderTcp::setLoggingPrefix(), ArNetPacketReceiverTcp::setLoggingPrefix(), and ArLog::Verbose.
Referenced by ArClientBase(), main(), ArClientSwitchManager::runThread(), and ArCentralForwarder::startingCallOnce().
void ArClientBase::setServerKey (const char * serverKey, bool log = true)
Sets the 'key' needed to connect to the server.
References ArMutex::lock(), ArLog::log(), myDataMutex, myLogPrefix, myServerKey, ArLog::Normal, and ArMutex::unlock().
Referenced by ArClientSimpleConnector::connectClient(), and getPort().
void ArClientBase::setTcpOnlyFromServer (void)
Sets it so we only get TCP data from the server not UDP.
References ArMutex::lock(), myDataMutex, myTcpOnlyFrom, sendPacketTcp(), ArNetPacket::setCommand(), ArClientCommands::TCP_ONLY, and ArMutex::unlock().
Referenced by ArCentralForwarder::connectedCallOnce(), and getPort().
void ArClientBase::setTcpOnlyToServer (void)
Sets it so we only send TCP data to the server.
References ArMutex::lock(), myDataMutex, myTcpOnlyTo, and ArMutex::unlock().
Referenced by ArCentralForwarder::connectedCallOnce(), and getPort().
bool ArClientBase::setupPacket (ArNetPacket * packet) protected
References ArNetPacket::finalizePacket(), ArNetPacket::getCommand(), ArBasePacket::getLength(), getName(), ArLog::log(), ArNetPacket::MAX_LENGTH, myLogPrefix, myState, STATE_FAILED_CONNECTION, STATE_LOST_CONNECTION, STATE_NO_CONNECTION, STATE_REJECTED, and ArLog::Terse.
Referenced by sendPacketTcp(), and sendPacketUdp().
bool ArClientBase::startNonBlockingDisconnect ()
Starts the process of disconnecting from the server.
This method should be called in threads that should not block (such as the main GUI thread). The call should be followed by a delay of one second, followed by a call to finishNonBlockingDisconnect().
References ArLog::log(), myDebugLogging, myLogPrefix, myQuiet, myTcpSender, ArLog::Normal, ArNetPacketSenderTcp::sendData(), sendPacketTcp(), ArNetPacket::setCommand(), and ArClientCommands::SHUTDOWN.
Referenced by disconnect(), getPort(), and loopOnce().
void ArClientBase::stopRunning (void) virtual
Stops the thread and sets the stopped flag.
Reimplemented from ArASyncTask.
References myIsStopped, and ArASyncTask::stopRunning().
Referenced by getPort(), loopOnce(), and processPacket().
void ArClientBase::trackPacketReceived (ArNetPacket * packet, bool tcp) protected
References ArNetPacket::getCommand(), ArBasePacket::getLength(), ArMutex::lock(), myPacketTrackingMutex, myTrackingReceivedMap, and ArMutex::unlock().
Referenced by processPacket().
void ArClientBase::trackPacketSent (ArNetPacket * packet, bool tcp) protected
References ArNetPacket::getCommand(), ArBasePacket::getLength(), ArMutex::lock(), myPacketTrackingMutex, myTrackingSentMap, and ArMutex::unlock().
Referenced by sendPacketTcp(), and sendPacketUdp().
bool ArClientBase::wasRejected (void) inline
Returns
true if a server connection attempt failed because the server rejected the username or password, false if the connection failed for another reason, or the username/password were accepted.
Examples:
ptzCameraClientExample.cpp, and robotUpdateExample.cpp.
References myState, and STATE_REJECTED.
Referenced by main().
Member Data Documentation
long ArClientBase::myAuthKey protected
Referenced by processPacket().
double ArClientBase::myBackupTimeout protected
Referenced by setBackupTimeout().
ArMutex ArClientBase::myCallbackMutex protected
Referenced by addDisconnectOnErrorCB(), addServerShutdownCB(), ArClientBase(), loopOnce(), processPacket(), remDisconnectOnErrorCB(), and remServerShutdownCB().
unsigned char ArClientBase::myClientKey[16] protected
Referenced by getClientKey(), and processPacket().
ArMutex ArClientBase::myClientMutex protected
Referenced by ArClientBase().
ArMutex ArClientBase::myCycleCallbackMutex protected
Referenced by addCycleCallback(), ArClientBase(), loopOnce(), and remCycleCallback().
std::list<ArFunctor *> ArClientBase::myCycleCallbacks protected
Referenced by addCycleCallback(), loopOnce(), and remCycleCallback().
ArMutex ArClientBase::myDataMutex protected
Referenced by ArClientBase(), enforceProtocolVersion(), enforceType(), getHost(), getLastPacketReceived(), getPort(), internalNonBlockingConnectContinue(), internalNonBlockingConnectStart(), isTcpOnlyFromServer(), isTcpOnlyToServer(), logTracking(), processPacket(), processPacketUdp(), setConnectTimeoutTime(), setServerKey(), setTcpOnlyFromServer(), and setTcpOnlyToServer().
bool ArClientBase::myDebugLogging protected
Referenced by ArClientBase(), getDebugLogging(), internalConnect(), internalNonBlockingConnectContinue(), internalNonBlockingConnectStart(), internalStartUdp(), loopOnce(), processPacket(), processPacketUdp(), setRobotName(), and startNonBlockingDisconnect().
std::list<ArFunctor *> ArClientBase::myDisconnectOnErrorCBList protected
Referenced by addDisconnectOnErrorCB(), loopOnce(), and remDisconnectOnErrorCB().
bool ArClientBase::myDisconnectSoon protected
Referenced by clear(), disconnectSoon(), and loopOnce().
std::string ArClientBase::myEnforceProtocolVersion protected
If we're enforcing the version of the protocol or not.
Referenced by enforceProtocolVersion(), and processPacket().
ArServerCommands::Type ArClientBase::myEnforceType protected
if we're a particular type
Referenced by ArClientBase(), enforceType(), and processPacket().
std::string ArClientBase::myHost protected
Referenced by getHost(), and internalNonBlockingConnectStart().
std::map<unsigned int, ArClientData *> ArClientBase::myIntDataMap protected
Referenced by addHandler(), buildList(), clear(), getDataMap(), getName(), logDataList(), processPacket(), and remHandler().
long ArClientBase::myIntroKey protected
Referenced by processPacket(), and processPacketUdp().
bool ArClientBase::myIsRunningAsync protected
Referenced by clear(), loopOnce(), and runAsync().
bool ArClientBase::myIsStartedDisconnect protected
Referenced by clear(), and loopOnce().
bool ArClientBase::myIsStopped protected
Referenced by clear(), isStopped(), and stopRunning().
ArTime ArClientBase::myLastPacketReceived protected
Referenced by clear(), getLastPacketReceived(), processPacket(), and processPacketUdp().
std::string ArClientBase::myLogPrefix protected
Optional prefix to be inserted at the start of log messages.
Referenced by addDisconnectOnErrorCB(), addHandler(), addServerShutdownCB(), buildList(), enforceProtocolVersion(), enforceType(), findCommandFromName(), getLogPrefix(), internalConnect(), internalNonBlockingConnectContinue(), internalNonBlockingConnectStart(), internalStartUdp(), logDataList(), logTracking(), loopOnce(), processPacket(), processPacketUdp(), remHandler(), request(), requestOnce(), requestOnceUdp(), requestOnceWithDouble(), requestOnceWithInt16(), requestOnceWithInt32(), requestOnceWithString(), requestStop(), sendPacketTcp(), setRobotName(), setServerKey(), setupPacket(), and startNonBlockingDisconnect().
ArMutex ArClientBase::myMapsMutex protected
Referenced by addHandler(), ArClientBase(), dataExists(), findCommandFromName(), getName(), logDataList(), processPacket(), and remHandler().
std::map<std::string, unsigned int> ArClientBase::myNameIntMap protected
Referenced by addHandler(), buildList(), clear(), dataExists(), findCommandFromName(), and remHandler().
NonBlockingConnectState ArClientBase::myNonBlockingConnectState protected
Referenced by ArClientBase(), internalNonBlockingConnectContinue(), and internalNonBlockingConnectStart().
ArMutex ArClientBase::myPacketTrackingMutex protected
Referenced by ArClientBase(), logTracking(), resetTracking(), trackPacketReceived(), and trackPacketSent().
std::string ArClientBase::myPassword protected
Referenced by internalNonBlockingConnectStart(), and processPacket().
int ArClientBase::myPort protected
Referenced by getPort(), and internalNonBlockingConnectStart().
ArFunctor2C<ArClientBase, ArNetPacket *, bool> ArClientBase::myProcessPacketCB protected
Referenced by ArClientBase().
ArFunctor2C<ArClientBase, ArNetPacket *, struct sockaddr_in *> ArClientBase::myProcessPacketUdpCB protected
Referenced by ArClientBase().
bool ArClientBase::myQuiet protected
Referenced by clear(), internalConnect(), internalNonBlockingConnectContinue(), internalNonBlockingConnectStart(), internalStartUdp(), loopOnce(), processPacket(), processPacketUdp(), and startNonBlockingDisconnect().
bool ArClientBase::myReceivedArgRetList protected
Referenced by buildList(), clear(), and getReceivedArgRetList().
bool ArClientBase::myReceivedDataList protected
Referenced by buildList(), clear(), and getReceivedDataList().
bool ArClientBase::myReceivedGroupAndFlagsList protected
Referenced by buildList(), clear(), and getReceivedGroupAndFlagsList().
int ArClientBase::myRejected protected
Referenced by clear(), getRejected(), and processPacket().
char ArClientBase::myRejectedString[32000] protected
Referenced by clear(), getRejectedString(), and processPacket().
std::string ArClientBase::myRobotName protected
Optional robot name for logging.
Referenced by getRobotName(), and setRobotName().
std::string ArClientBase::myServerKey protected
Referenced by processPacket(), and setServerKey().
unsigned int ArClientBase::myServerReportedUdpPort protected
Referenced by clear(), processPacket(), and processPacketUdp().
unsigned int ArClientBase::myServerSentUdpPort protected
std::list<ArFunctor *> ArClientBase::myServerShutdownCBList protected
Referenced by addServerShutdownCB(), processPacket(), and remServerShutdownCB().
ArTime ArClientBase::myStartedConnection protected
Referenced by internalNonBlockingConnectContinue(), and internalNonBlockingConnectStart().
ArTime ArClientBase::myStartedShutdown protected
Referenced by loopOnce().
ArTime ArClientBase::myStartedUdpConnection protected
Referenced by internalNonBlockingConnectContinue().
ClientState ArClientBase::myState protected
Referenced by finishNonBlockingDisconnect(), getState(), internalNonBlockingConnectContinue(), internalNonBlockingConnectStart(), internalSwitchState(), isConnected(), loopOnce(), processPacket(), processPacketUdp(), setupPacket(), and wasRejected().
ArMutex ArClientBase::myStateMutex protected
Referenced by ArClientBase().
ArTime ArClientBase::myStateStarted protected
Referenced by internalSwitchState().
bool ArClientBase::myTcpOnlyFrom protected
Referenced by clear(), internalNonBlockingConnectContinue(), internalStartUdp(), isTcpOnlyFromServer(), loopOnce(), processPacket(), and setTcpOnlyFromServer().
bool ArClientBase::myTcpOnlyTo protected
Referenced by clear(), internalNonBlockingConnectContinue(), internalStartUdp(), isTcpOnlyToServer(), processPacket(), requestOnceByCommandUdp(), and setTcpOnlyToServer().
ArNetPacketReceiverTcp ArClientBase::myTcpReceiver protected
Referenced by ArClientBase(), internalNonBlockingConnectStart(), loopOnce(), and setRobotName().
ArNetPacketSenderTcp ArClientBase::myTcpSender protected
Referenced by ArClientBase(), loopOnce(), sendPacketTcp(), setBackupTimeout(), setRobotName(), and startNonBlockingDisconnect().
ArSocket ArClientBase::myTcpSocket protected
Referenced by ArClientBase(), finishNonBlockingDisconnect(), getTcpAddr(), getTcpSocket(), internalConnect(), internalNonBlockingConnectContinue(), internalNonBlockingConnectStart(), internalStartUdp(), logTracking(), loopOnce(), and resetTracking().
int ArClientBase::myTimeoutTime protected
Referenced by clear(), getConnectTimeoutTime(), internalNonBlockingConnectContinue(), and setConnectTimeoutTime().
std::map<unsigned int, Tracker *> ArClientBase::myTrackingReceivedMap protected
Referenced by clear(), logTracking(), resetTracking(), and trackPacketReceived().
std::map<unsigned int, Tracker *> ArClientBase::myTrackingSentMap protected
Referenced by clear(), logTracking(), resetTracking(), and trackPacketSent().
ArTime ArClientBase::myTrackingStarted protected
Referenced by logTracking(), and resetTracking().
bool ArClientBase::myUdpConfirmedFrom protected
Referenced by clear(), internalNonBlockingConnectContinue(), and processPacketUdp().
bool ArClientBase::myUdpConfirmedTo protected
Referenced by clear(), internalNonBlockingConnectContinue(), and processPacket().
unsigned int ArClientBase::myUdpPort protected
Referenced by internalConnect(), internalStartUdp(), and processPacket().
ArNetPacketReceiverUdp ArClientBase::myUdpReceiver protected
Referenced by ArClientBase(), and loopOnce().
struct sockaddr_in ArClientBase::myUdpSin protected
Referenced by internalStartUdp(), processPacket(), processPacketUdp(), and sendPacketUdp().
bool ArClientBase::myUdpSinValid protected
Referenced by internalStartUdp().
ArSocket ArClientBase::myUdpSocket protected
Referenced by ArClientBase(), finishNonBlockingDisconnect(), getUdpSocket(), internalNonBlockingConnectContinue(), internalNonBlockingConnectStart(), internalStartUdp(), logTracking(), loopOnce(), resetTracking(), and sendPacketUdp().
std::string ArClientBase::myUser protected
Referenced by internalNonBlockingConnectStart(), and processPacket().
ArLog::LogLevel ArClientBase::myVerboseLogLevel protected
Referenced by addHandler(), ArClientBase(), buildList(), internalConnect(), internalNonBlockingConnectContinue(), logDataList(), processPacket(), processPacketUdp(), request(), requestOnce(), requestOnceUdp(), requestOnceWithDouble(), requestOnceWithInt16(), requestOnceWithInt32(), requestOnceWithString(), requestStop(), and setRobotName().
The documentation for this class was generated from the following files:
ArClientBase.h
ArClientBase.cpp