ArNetworking: ArServerModeJogPosition Class Reference
ArServerModeJogPosition Class Reference
Mode that allows clients to request simple discrete motions of the robot.
#include <ArServerModeJogPosition.h>
Public Member Functions
virtual void activate (void)
The function called when the mode is activated.
void addToConfig (ArConfig *config, const char *section="Jog Robot Position")
Adds to a config in a section.
ArServerModeJogPosition (ArServerBase *server, ArRobot *robot, const char *name="jogPositionMode", ArServerHandlerCommands *customCommands=NULL)
virtual void deactivate (void)
The function called when the mode is deactivated.
virtual ArActionGroup * getActionGroup (void)
This function should return the action group this mode uses.
ArActionDriveDistance * getDriveAction ()
ArActionInput * getTurnAction ()
void heading (double angle)
Request a movement. Mode must be active.
void move (double distance)
Request a movement. Mode must be active.
void turn (double angle)
Adds a callback when trying to back up.
virtual ~ArServerModeJogPosition ()
Public Member Functions inherited from ArServerMode
virtual void activationDenied (void)
The function called if the mode is not activated because another mode superceded it.
void addActivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is activated.
void addAsDefaultMode (ArListPos::Pos pos=ArListPos::LAST)
Sets this mode to default (so if a mode deactivates it activates this)
void addDeactivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is deactivated.
bool addModeData (const char *name, const char *description, ArFunctor2< ArServerClient *, ArNetPacket * > *functor, const char *argumentDescription, const char *returnDescription, const char *commandGroup=NULL, const char *dataFlags=NULL)
This basically just notes the commands associated with a mode so that clients can know what can and can't happen based on what mode is active/locked/etc.
void addSingleShotDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for when this class is deactivated.
void addSingleShotPostDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for just after the deactivate happens (when the next mode has activated)
ArServerMode (ArRobot *robot, ArServerBase *server, const char *name)
Constructor.
virtual void checkDefault (void)
Sees if this wants to become the default mode.
virtual void forceUnlock (void)
This will be called if another mode has to break the lock.
ArTime getActivityTime (void)
Gets the time of our last activity.
const char * getExtendedStatus (void) const
Gets a string representing the extended status of the mode we're in.
const char * getMode (void) const
Gets a string representing the mode we're in.
const char * getName (void) const
Gets the name of the mode we're in.
const char * getStatus (void) const
Gets a string representing the status of the mode we're in.
bool hasSetActivityTime (void)
Gets if we've set our activity time.
void internalSetActivityTime (ArTime time)
Internal call to set the activity time (this is dangerous and shouldn't be used)
bool isActive (void) const
Gets if this mode is active or not.
virtual bool isAutoResumeAfterInterrupt ()
Adds data to the list of this mode's commands.
void lockMode (bool willUnlockIfRequested=false)
Locks this mode in until its unlocked (mode must be the active mode)
void remActivateCallback (ArFunctor *functor)
Removes a callback for when this class is activated.
void remDeactivateCallback (ArFunctor *functor)
Removes a callback for when this class is deactivated.
void remSingleShotDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for when this class is deactivated.
void remSingleShotPostDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for just after the deactivate happens (when the next mode has activated)
virtual void requestUnlock (void)
This will be called if another mode wants the lock broken (can ignore)
void setActivityTimeToNow (void)
Sets that we're active right now.
void setMode (const char *str)
This should only be used by careful people and probably not then.
void setStatus (const char *str)
This should only be used by careful people and probably not then.
void unlockMode (void)
Unlocks the mode so other modes can activate.
virtual void userTask (void)
The ArMode's user task, don't need one, subclass must provide if needed.
virtual ~ArServerMode ()
Destructor.
Protected Member Functions
void serverHeading (ArServerClient *client, ArNetPacket *packet)
void serverMove (ArServerClient *client, ArNetPacket *packet)
void serverTurn (ArServerClient *client, ArNetPacket *packet)
void stringCmdHeading (ArArgumentBuilder *args)
void stringCmdMove (ArArgumentBuilder *args)
void stringCmdTurn (ArArgumentBuilder *args)
Protected Member Functions inherited from ArServerMode
bool baseActivate (bool canSelfActivateIfLocked=false)
Activates this mode if it can (returns true if it can, false otherwise).
void baseDeactivate (void)
Deactivates this mode.
void checkBroadcastModeInfoPacket (void)
ArServerMode * getLastActiveMode ()
Protected Attributes
ArActionGroup myActionGroup
ArServerHandlerCommands * myCustomCommandServer
ArActionDriveDistance * myDriveAction
ArTime myLastCommand
ArActionDeceleratingLimiter * myLimiterBackward
ArActionDeceleratingLimiter * myLimiterForward
ArActionDeceleratingLimiter * myLimiterLateralLeft
ArActionDeceleratingLimiter * myLimiterLateralRight
ArActionLimiterRot * myLimiterRot
ArActionMovementParameters * myMovementParameters
bool myPrinting
ArFunctor2C< ArServerModeJogPosition, ArServerClient *, ArNetPacket * > myServerHeadingCB
ArFunctor2C< ArServerModeJogPosition, ArServerClient *, ArNetPacket * > myServerMoveCB
ArFunctor2C< ArServerModeJogPosition, ArServerClient *, ArNetPacket * > myServerTurnCB
ArFunctor1C< ArServerModeJogPosition, ArArgumentBuilder * > myStringCommandHeadingCB
ArFunctor1C< ArServerModeJogPosition, ArArgumentBuilder * > myStringCommandMoveCB
ArFunctor1C< ArServerModeJogPosition, ArArgumentBuilder * > myStringCommandTurnCB
ArActionInput * myTurnAction
Protected Attributes inherited from ArServerMode
ArCallbackList myActivateCallbacks
ArTime myActivityTime
ArMutex myActivityTimeMutex
ArCallbackList myDeactivateCallbacks
std::string myExtendedStatus
bool myHasSetActivityTime
bool myIsActive
std::string myMode
std::string myName
ArRobot * myRobot
ArServerBase * myServer
bool mySetActivityThisCycle
ArCallbackList mySingleShotDeactivateCallbacks
ArCallbackList mySingleShotPostDeactivateCallbacks
std::string myStatus
bool myStatusSetThisCycle
ArLog::LogLevel myVerboseLogLevel
Additional Inherited Members
Static Public Member Functions inherited from ArServerMode
static ArServerMode * getActiveMode (void)
Gets the active mode.
static int getActiveModeActivityTimeSecSince (void)
Gets the seconds since the activity of our active mode.
static const char * getActiveModeExtendedStatusString (void)
Gets the active extended status string.
static const char * getActiveModeModeString (void)
Gets the active mode string.
static bool getActiveModeSetActivityThisCycle (void)
Gets if the active mode set the activity time this cycle or not.
static const char * getActiveModeStatusString (void)
Gets the active status string.
static ArServerModeIdle * getIdleMode (void)
Call that gets our idle mode.
static void getModeBusy (ArServerClient *client, ArNetPacket *packet)
Handles the packet request for the mode busy state.
static void getModeDataList (ArServerClient *client, ArNetPacket *packet)
Gets the list of data for each mode.
static void getModeInfo (ArServerClient *client, ArNetPacket *packet)
Gets the info about which mode is active and such.
static bool isLocked (void)
Gets if the active mode is locked or not.
static bool willUnlockIfRequested (void)
Gets whether we'll unlock if requested or not.
Static Protected Member Functions inherited from ArServerMode
static void buildModeInfoPacket (ArNetPacket *packet)
static std::list< ArServerMode * > * getRequestedActivateModes (void)
static void modeUserTask (void)
Static Protected Attributes inherited from ArServerMode
static ArServerMode * ourActiveMode = NULL
static bool ourActiveModeLocked = false
static bool ourActiveModeSetActivityThisCycle = false
static bool ourActiveModeWillUnlockIfRequested = false
static ArServerMode * ourBroadcastActiveMode = NULL
static bool ourBroadcastActiveModeLocked = false
static bool ourBroadcastActiveModeWillUnlockIfRequested = false
static std::list< ArServerMode * > ourDefaultModes
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeBusyCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeDataListCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeInfoCB
static ArServerModeIdle * ourIdleMode = NULL
static bool ourIdleModeCreated = false
static ArMutex ourIdleModeMutex
static bool ourIsBusy = false
static ArServerMode * ourLastActiveMode = NULL
static std::multimap< std::string, std::string > ourModeDataMap
static ArMutex ourModeDataMapMutex
static std::list< ArServerMode * > ourModes
static ArServerMode * ourNextActiveMode = NULL
static std::list< ArServerMode * > ourRequestedActivateModes
static ArServerBase * ourServerBase = NULL
static bool ourUserTaskAdded = false
static ArGlobalFunctor ourUserTaskCB
Detailed Description
Mode that allows clients to request simple discrete motions of the robot.
Use the "moveDistance" request for forward/backward motion by the given amount (mm). Use the "turnByAngle" request to rotate by the given angle (deg). Use the "turnToHeading" request to rotate to a given absolute heading angle (deg). This mode will become active if any of the above requests are received. any active robot motion will be stopped once the mode becomes active, and also upon deactivation before switching to a new mode. Each moveDistance request interrupts any previous moveDistance request if still active. Each turnByAngle or turnToHeading interrupts any previous turnByAngle or turnToHeading if still active. For continuous velocity control, see ArServerModeRatioDrive instead. Motion will be limited based on obstacles sensed. Clearences may be configured in configuration (ArConfig) if addToConfig() is called to associate with an ArConfig object. (E.g. motionMode.addToConfig(Aria::getConfig())).
Examples:
serverDemo.cpp.
Constructor & Destructor Documentation
ArServerModeJogPosition::ArServerModeJogPosition (ArServerBase * server, ArRobot * robot, const char * name = "jogPositionMode", ArServerHandlerCommands * customCommands = NULL)
References ArActionGroup::addAction(), ArServerMode::addModeData(), ArServerHandlerCommands::addStringCommand(), ArActionDeceleratingLimiter::BACKWARDS, ArActionMovementParameters::enable(), ArActionDeceleratingLimiter::FORWARDS, ArRobot::hasLatVel(), ArActionDeceleratingLimiter::LATERAL_LEFT, ArActionDeceleratingLimiter::LATERAL_RIGHT, myActionGroup, myDriveAction, myLimiterBackward, myLimiterForward, myLimiterLateralLeft, myLimiterLateralRight, myLimiterRot, myMovementParameters, ArServerMode::myRobot, ArServerMode::myServer, myServerHeadingCB, myServerMoveCB, myServerTurnCB, myStringCommandHeadingCB, myStringCommandMoveCB, myStringCommandTurnCB, myTurnAction, and ArActionDeceleratingLimiter::setUseLocationDependentDevices().
ArServerModeJogPosition::~ArServerModeJogPosition () virtual
References ArLog::log(), and ArLog::Verbose.
Member Function Documentation
void ArServerModeJogPosition::activate (void) virtual
The function called when the mode is activated.
Subclasses must implement this, but also call baseActivate().-
Implements ArServerMode.
References ArActionGroup::activateExclusive(), ArServerMode::baseActivate(), ArRobot::clearDirectMotion(), ArServerMode::isActive(), ArLog::log(), myActionGroup, ArServerMode::myMode, ArServerMode::myName, ArServerMode::myRobot, ArLog::Normal, and ArRobot::stop().
Referenced by heading(), move(), and turn().
void ArServerModeJogPosition::addToConfig (ArConfig * config, const char * section = "Jog Robot Position")
Adds to a config in a section.
Examples:
serverDemo.cpp.
References ArActionDeceleratingLimiter::addToConfig(), ArActionMovementParameters::addToConfig(), myLimiterBackward, myLimiterForward, myLimiterLateralLeft, myLimiterLateralRight, and myMovementParameters.
Referenced by main().
void ArServerModeJogPosition::deactivate (void) virtual
The function called when the mode is deactivated.
Subclasses must implement this, and also call baseDeactivate().
Implements ArServerMode.
References ArServerMode::baseDeactivate(), ArRobot::clearDirectMotion(), ArActionGroup::deactivate(), myActionGroup, ArServerMode::myRobot, and ArRobot::stop().
virtual ArActionGroup* ArServerModeJogPosition::getActionGroup (void) inline virtual
This function should return the action group this mode uses.
Reimplemented from ArServerMode.
References myActionGroup.
ArActionDriveDistance* ArServerModeJogPosition::getDriveAction () inline
References client, heading(), move(), myDriveAction, serverHeading(), serverMove(), serverTurn(), and turn().
ArActionInput* ArServerModeJogPosition::getTurnAction () inline
References myTurnAction.
void ArServerModeJogPosition::heading (double angle)
Request a movement. Mode must be active.
References activate(), ArActionInput::clear(), ArRobot::clearDirectMotion(), ArServerMode::getName(), ArServerMode::isActive(), ArLog::log(), myLastCommand, myPrinting, ArServerMode::myRobot, ArServerMode::myStatus, myTurnAction, ArLog::Normal, ArServerMode::setActivityTimeToNow(), ArActionInput::setHeading(), and ArTime::setToNow().
Referenced by getDriveAction(), serverHeading(), stringCmdHeading(), and turn().
void ArServerModeJogPosition::move (double distance)
Request a movement. Mode must be active.
References activate(), ArActionDriveDistance::cancelDistance(), ArRobot::clearDirectMotion(), ArServerMode::getName(), ArServerMode::isActive(), ArLog::log(), myDriveAction, myLastCommand, myPrinting, ArServerMode::myRobot, ArServerMode::myStatus, ArLog::Normal, ArServerMode::setActivityTimeToNow(), ArActionDriveDistance::setDistance(), and ArTime::setToNow().
Referenced by getDriveAction(), serverMove(), and stringCmdMove().
void ArServerModeJogPosition::serverHeading (ArServerClient * client, ArNetPacket * packet) protected
References ArNetPacket::bufToDouble(), ArServerClient::getIPString(), ArServerMode::getName(), heading(), ArLog::log(), myPrinting, and ArLog::Normal.
Referenced by getDriveAction().
void ArServerModeJogPosition::serverMove (ArServerClient * client, ArNetPacket * packet) protected
References ArNetPacket::bufToDouble(), ArServerClient::getIPString(), ArServerMode::getName(), ArLog::log(), move(), myPrinting, and ArLog::Normal.
Referenced by getDriveAction().
void ArServerModeJogPosition::serverTurn (ArServerClient * client, ArNetPacket * packet) protected
References ArNetPacket::bufToDouble(), ArServerClient::getIPString(), ArServerMode::getName(), ArLog::log(), myPrinting, ArLog::Normal, and turn().
Referenced by getDriveAction().
void ArServerModeJogPosition::stringCmdHeading (ArArgumentBuilder * args) protected
References ArArgumentBuilder::getArgDouble(), ArServerMode::getName(), heading(), ArLog::log(), myPrinting, ArLog::Normal, and ArLog::Terse.
void ArServerModeJogPosition::stringCmdMove (ArArgumentBuilder * args) protected
References ArArgumentBuilder::getArgDouble(), ArServerMode::getName(), ArLog::log(), move(), myPrinting, ArLog::Normal, and ArLog::Terse.
void ArServerModeJogPosition::stringCmdTurn (ArArgumentBuilder * args) protected
References ArArgumentBuilder::getArgDouble(), ArServerMode::getName(), ArLog::log(), myPrinting, ArLog::Normal, ArLog::Terse, and turn().
void ArServerModeJogPosition::turn (double angle)
Adds a callback when trying to back up.
Removes a callback for trying to back up Request a turn. Mode must be active.
References activate(), ArActionInput::clear(), ArRobot::clearDirectMotion(), ArMath::fixAngle(), ArServerMode::getName(), ArAction::getRobot(), ArRobot::getTh(), heading(), ArServerMode::isActive(), ArRobot::lock(), ArLog::log(), myLastCommand, myPrinting, ArServerMode::myRobot, ArServerMode::myStatus, myTurnAction, ArLog::Normal, ArServerMode::setActivityTimeToNow(), ArActionInput::setHeading(), ArTime::setToNow(), and ArRobot::unlock().
Referenced by getDriveAction(), serverTurn(), and stringCmdTurn().
Member Data Documentation
ArActionGroup ArServerModeJogPosition::myActionGroup protected
Referenced by activate(), ArServerModeJogPosition(), deactivate(), and getActionGroup().
ArServerHandlerCommands* ArServerModeJogPosition::myCustomCommandServer protected
ArActionDriveDistance* ArServerModeJogPosition::myDriveAction protected
Referenced by ArServerModeJogPosition(), getDriveAction(), and move().
ArTime ArServerModeJogPosition::myLastCommand protected
Referenced by heading(), move(), and turn().
ArActionDeceleratingLimiter* ArServerModeJogPosition::myLimiterBackward protected
Referenced by addToConfig(), and ArServerModeJogPosition().
ArActionDeceleratingLimiter* ArServerModeJogPosition::myLimiterForward protected
Referenced by addToConfig(), and ArServerModeJogPosition().
ArActionDeceleratingLimiter* ArServerModeJogPosition::myLimiterLateralLeft protected
Referenced by addToConfig(), and ArServerModeJogPosition().
ArActionDeceleratingLimiter* ArServerModeJogPosition::myLimiterLateralRight protected
Referenced by addToConfig(), and ArServerModeJogPosition().
ArActionLimiterRot* ArServerModeJogPosition::myLimiterRot protected
Referenced by ArServerModeJogPosition().
ArActionMovementParameters* ArServerModeJogPosition::myMovementParameters protected
Referenced by addToConfig(), and ArServerModeJogPosition().
bool ArServerModeJogPosition::myPrinting protected
Referenced by heading(), move(), serverHeading(), serverMove(), serverTurn(), stringCmdHeading(), stringCmdMove(), stringCmdTurn(), and turn().
ArFunctor2C<ArServerModeJogPosition, ArServerClient *, ArNetPacket *> ArServerModeJogPosition::myServerHeadingCB protected
Referenced by ArServerModeJogPosition().
ArFunctor2C<ArServerModeJogPosition, ArServerClient *, ArNetPacket *> ArServerModeJogPosition::myServerMoveCB protected
Referenced by ArServerModeJogPosition().
ArFunctor2C<ArServerModeJogPosition, ArServerClient *, ArNetPacket *> ArServerModeJogPosition::myServerTurnCB protected
Referenced by ArServerModeJogPosition().
ArFunctor1C<ArServerModeJogPosition, ArArgumentBuilder*> ArServerModeJogPosition::myStringCommandHeadingCB protected
Referenced by ArServerModeJogPosition().
ArFunctor1C<ArServerModeJogPosition, ArArgumentBuilder*> ArServerModeJogPosition::myStringCommandMoveCB protected
Referenced by ArServerModeJogPosition().
ArFunctor1C<ArServerModeJogPosition, ArArgumentBuilder*> ArServerModeJogPosition::myStringCommandTurnCB protected
Referenced by ArServerModeJogPosition().
ArActionInput* ArServerModeJogPosition::myTurnAction protected
Referenced by ArServerModeJogPosition(), getTurnAction(), heading(), and turn().
The documentation for this class was generated from the following files:
ArServerModeJogPosition.h
ArServerModeJogPosition.cpp