ArNetworking: ArServerUserInfo Class Reference
ArServerUserInfo Class Reference
This class holds information about users and loads it from a file.
#include <ArServerUserInfo.h>
Public Member Functions
ArServerUserInfo (const char *baseDirectory=NULL)
Constructor.
bool doNotUse (void) const
std::set< std::string,
ArStrCaseCmpOp > getUsersGroups (const char *user) const
Gets the groups a user is in (returns empty set if no user)
void logUsers (void) const
Logs the users and groups.
bool matchUserPassword (const char *user, unsigned char password[16], const char *passwordKey, const char *serverKey, bool logFailureVerbosely=false) const
Matchs a user and password, false if user or password is wrong.
bool readFile (const char *fileName)
Loads the file, returns false if it wasn't there.
void setBaseDirectory (const char *baseDirectory)
Sets the base directory.
~ArServerUserInfo ()
Destructor.
Protected Member Functions
void logDigest (unsigned char digest[16]) const
void removeHandlers (void)
bool v1DoNotUseCallback (ArArgumentBuilder *arg)
bool v1HeaderCallback (ArArgumentBuilder *arg)
bool v1UserCallback (ArArgumentBuilder *arg)
Protected Attributes
std::string myBaseDirectory
ArMutex myDataMutex
bool myDoNotUse
bool myGotHeader
std::map< std::string,
std::set< std::string,
ArStrCaseCmpOp >
*, ArStrCaseCmpOp > myGroups
bool myLogFailureVerbosely
ArFileParser myParser
std::map< std::string,
std::string, ArStrCaseCmpOp > myPasswords
ArRetFunctor1C< bool,
ArServerUserInfo,
ArArgumentBuilder * > myV1DoNotUseCB
ArRetFunctor1C< bool,
ArServerUserInfo,
ArArgumentBuilder * > myV1HeaderCB
ArRetFunctor1C< bool,
ArServerUserInfo,
ArArgumentBuilder * > myV1UserCB
Detailed Description
This class holds information about users and loads it from a file.
For a description of the algorithm used to match passwords and keys and all look at the documentation for ArServerBase.
The file format for this class is set up to be easy to make a new version of and yet read all the old versions.
For all of the versions everything after ; or # is ignored. The version information is then the first line of non comments.
The first version is described as such: The version string is 'UserInfoVersion1'. Then there are lines that follow for each user which are 'user userName password groups'. The passwords are plain text in the file, though they aren't sent that way over the network (look at ArServerBase docs for details). To display the groups available use ArServerBase::logCommandGroups().
There is an example user info file in ArNetworking/examples/serverDemo.userInfo
Constructor & Destructor Documentation
ArServerUserInfo::ArServerUserInfo (const char * baseDirectory = NULL)
Constructor.
References myDataMutex, myDoNotUse, myGotHeader, myLogFailureVerbosely, myParser, ArFileParser::setBaseDirectory(), and ArMutex::setLogName().
ArServerUserInfo::~ArServerUserInfo ()
Destructor.
Member Function Documentation
bool ArServerUserInfo::doNotUse (void) const
References myDoNotUse.
Referenced by ArServerBase::loadUserInfo().
std::set< std::string, ArStrCaseCmpOp > ArServerUserInfo::getUsersGroups (const char * user) const
Gets the groups a user is in (returns empty set if no user)
References ArLog::log(), myGroups, and ArLog::Terse.
Referenced by logUsers(), and ArServerClient::processPacket().
void ArServerUserInfo::logDigest (unsigned char digest[16]) const [protected]
References ArLog::log(), and ArLog::Terse.
Referenced by matchUserPassword().
void ArServerUserInfo::logUsers (void) const
Logs the users and groups.
References getUsersGroups(), ArLog::log(), myDoNotUse, myPasswords, and ArLog::Terse.
Referenced by ArServerBase::logUserInfo().
bool ArServerUserInfo::matchUserPassword (const char * user, unsigned char password[16], const char * passwordKey, const char * serverKey, bool logFailureVerbosely = false) const
Matchs a user and password, false if user or password is wrong.
References ArUtil::isOnlyAlphaNumeric(), ArLog::log(), logDigest(), md5_append(), md5_finish(), md5_init(), myPasswords, ArLog::Normal, and ArLog::Terse.
Referenced by ArServerClient::processPacket().
bool ArServerUserInfo::readFile (const char * fileName)
Loads the file, returns false if it wasn't there.
References ArFileParser::addHandler(), ArUtil::deleteSetPairs(), ArMutex::lock(), ArLog::log(), myDataMutex, myGotHeader, myGroups, myParser, myPasswords, myV1HeaderCB, ArLog::Normal, ArFileParser::parseFile(), removeHandlers(), ArLog::Terse, ArMutex::unlock(), and ArLog::Verbose.
Referenced by ArServerBase::loadUserInfo().
void ArServerUserInfo::removeHandlers (void) [protected]
References myParser, myV1HeaderCB, myV1UserCB, and ArFileParser::remHandler().
Referenced by readFile(), and v1HeaderCallback().
void ArServerUserInfo::setBaseDirectory (const char * baseDirectory)
Sets the base directory.
References ArMutex::lock(), myDataMutex, myParser, ArFileParser::setBaseDirectory(), and ArMutex::unlock().
Referenced by ArServerBase::loadUserInfo().
bool ArServerUserInfo::v1DoNotUseCallback (ArArgumentBuilder * arg) [protected]
References myDoNotUse.
bool ArServerUserInfo::v1HeaderCallback (ArArgumentBuilder * arg) [protected]
References ArFileParser::addHandler(), ArLog::log(), myDoNotUse, myGotHeader, myParser, myV1DoNotUseCB, myV1UserCB, removeHandlers(), and ArLog::Terse.
bool ArServerUserInfo::v1UserCallback (ArArgumentBuilder * arg) [protected]
References ArArgumentBuilder::getArg(), ArArgumentBuilder::getArgc(), ArUtil::isOnlyAlphaNumeric(), ArLog::log(), myGroups, myPasswords, ArLog::Normal, and ArLog::Terse.
Member Data Documentation
std::string ArServerUserInfo::myBaseDirectory [protected]
ArMutex ArServerUserInfo::myDataMutex [protected]
Referenced by ArServerUserInfo(), readFile(), and setBaseDirectory().
bool ArServerUserInfo::myDoNotUse [protected]
Referenced by ArServerUserInfo(), doNotUse(), logUsers(), v1DoNotUseCallback(), and v1HeaderCallback().
bool ArServerUserInfo::myGotHeader [protected]
Referenced by ArServerUserInfo(), readFile(), and v1HeaderCallback().
std::map<std::string, std::set<std::string, ArStrCaseCmpOp> *, ArStrCaseCmpOp> ArServerUserInfo::myGroups [protected]
Referenced by getUsersGroups(), readFile(), and v1UserCallback().
bool ArServerUserInfo::myLogFailureVerbosely [protected]
Referenced by ArServerUserInfo().
ArFileParser ArServerUserInfo::myParser [protected]
Referenced by ArServerUserInfo(), readFile(), removeHandlers(), setBaseDirectory(), and v1HeaderCallback().
std::map<std::string, std::string, ArStrCaseCmpOp> ArServerUserInfo::myPasswords [protected]
Referenced by logUsers(), matchUserPassword(), readFile(), and v1UserCallback().
ArRetFunctor1C<bool, ArServerUserInfo, ArArgumentBuilder *> ArServerUserInfo::myV1DoNotUseCB [protected]
Referenced by v1HeaderCallback().
ArRetFunctor1C<bool, ArServerUserInfo, ArArgumentBuilder *> ArServerUserInfo::myV1HeaderCB [protected]
Referenced by readFile(), and removeHandlers().
ArRetFunctor1C<bool, ArServerUserInfo, ArArgumentBuilder *> ArServerUserInfo::myV1UserCB [protected]
Referenced by removeHandlers(), and v1HeaderCallback().
The documentation for this class was generated from the following files:
ArServerUserInfo.h
ArServerUserInfo.cpp