ArNetworking: ArServerSimpleComMovementLogging Class Reference
ArServerSimpleComMovementLogging Class Reference
Class for enabling or disabling logging of movement commands and data.
#include <ArServerSimpleCommands.h>
Public Member Functions
ArServerSimpleComMovementLogging (ArServerHandlerCommands *handlerCommands, ArRobot *robot, ArServerHandlerPopup *popupHandler=NULL)
Constructor.
void logActions (void)
Log the status of the actions on the robot.
void logActionsDisable (void)
Disable logging of velocities received from the robot.
void logActionsEnable (void)
Enable logging of velocities received from the robot.
void logMovementReceivedDisable (void)
Disable logging of movement received from the robot.
void logMovementReceivedEnable (void)
Enable logging of movement received from the robot.
void logMovementSentDisable (void)
Disable logging of movement commands sent to the robot.
void logMovementSentEnable (void)
Enable logging of movement commands sent to the robot.
void logVelocitiesReceivedDisable (void)
Disable logging of velocities received from the robot.
void logVelocitiesReceivedEnable (void)
Enable logging of velocities received from the robot.
void packetsReceivedTrackingDisable (void)
Disable tracking of packets from the robot.
void packetsReceivedTrackingEnable (void)
Enable tracking of packets from the robot.
void packetsSentTrackingDisable (void)
Disable tracking of packets from the robot.
void packetsSentTrackingEnable (void)
Enable tracking of packets from the robot.
void popupMovementParams (void)
Popups up the movement parameters.
void resetOdometer (void)
Resets the odometer.
virtual ~ArServerSimpleComMovementLogging ()
Destructor.
Protected Attributes
ArServerHandlerCommands * myHandlerCommands
ArFunctorC
< ArServerSimpleComMovementLogging > myLogActionsCB
ArFunctorC
< ArServerSimpleComMovementLogging > myLogActionsDisableCB
ArFunctorC
< ArServerSimpleComMovementLogging > myLogActionsEnableCB
ArFunctorC
< ArServerSimpleComMovementLogging > myLogMovementReceivedDisableCB
ArFunctorC
< ArServerSimpleComMovementLogging > myLogMovementReceivedEnableCB
ArFunctorC
< ArServerSimpleComMovementLogging > myLogMovementSentDisableCB
ArFunctorC
< ArServerSimpleComMovementLogging > myLogMovementSentEnableCB
ArFunctorC
< ArServerSimpleComMovementLogging > myLogVelocitiesReceivedDisableCB
ArFunctorC
< ArServerSimpleComMovementLogging > myLogVelocitiesReceivedEnableCB
ArFunctorC
< ArServerSimpleComMovementLogging > myPacketsReceivedTrackingDisableCB
ArFunctorC
< ArServerSimpleComMovementLogging > myPacketsReceivedTrackingEnableCB
ArFunctorC
< ArServerSimpleComMovementLogging > myPacketsSentTrackingDisableCB
ArFunctorC
< ArServerSimpleComMovementLogging > myPacketsSentTrackingEnableCB
ArServerHandlerPopup * myPopupHandler
ArFunctorC
< ArServerSimpleComMovementLogging > myPopupMovementParamsCB
ArFunctorC
< ArServerSimpleComMovementLogging > myResetOdometerCB
ArRobot * myRobot
Detailed Description
Class for enabling or disabling logging of movement commands and data.
This just calls ArRobot::setLogMovementSent and ArRobot::setLogLovementReceived. It makes these available for easy enabling or disabling on the client side.
Examples:
serverDemo.cpp, and simpleServerExample.cpp.
Constructor & Destructor Documentation
ArServerSimpleComMovementLogging::ArServerSimpleComMovementLogging (ArServerHandlerCommands * handlerCommands, ArRobot * robot, ArServerHandlerPopup * popupHandler = NULL)
Constructor.
References ArServerHandlerCommands::addCommand(), myHandlerCommands, myLogActionsCB, myLogActionsDisableCB, myLogActionsEnableCB, myLogMovementReceivedDisableCB, myLogMovementReceivedEnableCB, myLogMovementSentDisableCB, myLogMovementSentEnableCB, myLogVelocitiesReceivedDisableCB, myLogVelocitiesReceivedEnableCB, myPacketsReceivedTrackingDisableCB, myPacketsReceivedTrackingEnableCB, myPacketsSentTrackingDisableCB, myPacketsSentTrackingEnableCB, myPopupHandler, myPopupMovementParamsCB, myResetOdometerCB, and myRobot.
ArServerSimpleComMovementLogging::~ArServerSimpleComMovementLogging () [virtual]
Destructor.
Member Function Documentation
void ArServerSimpleComMovementLogging::logActions (void)
Log the status of the actions on the robot.
References ArRobot::lock(), ArRobot::logActions(), myRobot, and ArRobot::unlock().
void ArServerSimpleComMovementLogging::logActionsDisable (void)
Disable logging of velocities received from the robot.
References ArRobot::lock(), myRobot, ArRobot::setLogActions(), and ArRobot::unlock().
void ArServerSimpleComMovementLogging::logActionsEnable (void)
Enable logging of velocities received from the robot.
References ArRobot::lock(), myRobot, ArRobot::setLogActions(), and ArRobot::unlock().
void ArServerSimpleComMovementLogging::logMovementReceivedDisable (void)
Disable logging of movement received from the robot.
References ArRobot::lock(), myRobot, ArRobot::setLogMovementReceived(), and ArRobot::unlock().
void ArServerSimpleComMovementLogging::logMovementReceivedEnable (void)
Enable logging of movement received from the robot.
References ArRobot::lock(), myRobot, ArRobot::setLogMovementReceived(), and ArRobot::unlock().
void ArServerSimpleComMovementLogging::logMovementSentDisable (void)
Disable logging of movement commands sent to the robot.
References ArRobot::lock(), myRobot, ArRobot::setLogMovementSent(), and ArRobot::unlock().
void ArServerSimpleComMovementLogging::logMovementSentEnable (void)
Enable logging of movement commands sent to the robot.
References ArRobot::lock(), myRobot, ArRobot::setLogMovementSent(), and ArRobot::unlock().
void ArServerSimpleComMovementLogging::logVelocitiesReceivedDisable (void)
Disable logging of velocities received from the robot.
References ArRobot::lock(), myRobot, ArRobot::setLogVelocitiesReceived(), and ArRobot::unlock().
void ArServerSimpleComMovementLogging::logVelocitiesReceivedEnable (void)
Enable logging of velocities received from the robot.
References ArRobot::lock(), myRobot, ArRobot::setLogVelocitiesReceived(), and ArRobot::unlock().
void ArServerSimpleComMovementLogging::packetsReceivedTrackingDisable (void)
Disable tracking of packets from the robot.
References ArRobot::lock(), myRobot, ArRobot::setPacketsReceivedTracking(), and ArRobot::unlock().
void ArServerSimpleComMovementLogging::packetsReceivedTrackingEnable (void)
Enable tracking of packets from the robot.
References ArRobot::lock(), myRobot, ArRobot::setPacketsReceivedTracking(), and ArRobot::unlock().
void ArServerSimpleComMovementLogging::packetsSentTrackingDisable (void)
Disable tracking of packets from the robot.
References ArRobot::lock(), myRobot, ArRobot::setPacketsSentTracking(), and ArRobot::unlock().
void ArServerSimpleComMovementLogging::packetsSentTrackingEnable (void)
Enable tracking of packets from the robot.
References ArRobot::lock(), myRobot, ArRobot::setPacketsSentTracking(), and ArRobot::unlock().
void ArServerSimpleComMovementLogging::popupMovementParams (void)
Popups up the movement parameters.
References ArServerHandlerPopup::createPopup(), ArRobot::getAbsoluteMaxLatAccel(), ArRobot::getAbsoluteMaxLatDecel(), ArRobot::getAbsoluteMaxLatVel(), ArRobot::getAbsoluteMaxRotAccel(), ArRobot::getAbsoluteMaxRotDecel(), ArRobot::getAbsoluteMaxRotVel(), ArRobot::getAbsoluteMaxTransAccel(), ArRobot::getAbsoluteMaxTransDecel(), ArRobot::getAbsoluteMaxTransNegVel(), ArRobot::getAbsoluteMaxTransVel(), ArRobot::getLatAccel(), ArRobot::getLatDecel(), ArRobot::getLatVelMax(), ArRobot::getRotAccel(), ArRobot::getRotDecel(), ArRobot::getRotVelMax(), ArRobot::getTransAccel(), ArRobot::getTransDecel(), ArRobot::getTransNegVelMax(), ArRobot::getTransVelMax(), ArRobot::hasLatVel(), ArServerHandlerPopup::INFORMATION, ArRobot::lock(), myPopupHandler, myRobot, and ArRobot::unlock().
void ArServerSimpleComMovementLogging::resetOdometer (void)
Resets the odometer.
References ArRobot::lock(), myRobot, ArRobot::resetTripOdometer(), and ArRobot::unlock().
Member Data Documentation
ArServerHandlerCommands* ArServerSimpleComMovementLogging::myHandlerCommands [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myLogActionsCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myLogActionsDisableCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myLogActionsEnableCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myLogMovementReceivedDisableCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myLogMovementReceivedEnableCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myLogMovementSentDisableCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myLogMovementSentEnableCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myLogVelocitiesReceivedDisableCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myLogVelocitiesReceivedEnableCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myPacketsReceivedTrackingDisableCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myPacketsReceivedTrackingEnableCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myPacketsSentTrackingDisableCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myPacketsSentTrackingEnableCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArServerHandlerPopup* ArServerSimpleComMovementLogging::myPopupHandler [protected]
Referenced by ArServerSimpleComMovementLogging(), and popupMovementParams().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myPopupMovementParamsCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArFunctorC<ArServerSimpleComMovementLogging> ArServerSimpleComMovementLogging::myResetOdometerCB [protected]
Referenced by ArServerSimpleComMovementLogging().
ArRobot* ArServerSimpleComMovementLogging::myRobot [protected]
Referenced by ArServerSimpleComMovementLogging(), logActions(), logActionsDisable(), logActionsEnable(), logMovementReceivedDisable(), logMovementReceivedEnable(), logMovementSentDisable(), logMovementSentEnable(), logVelocitiesReceivedDisable(), logVelocitiesReceivedEnable(), packetsReceivedTrackingDisable(), packetsReceivedTrackingEnable(), packetsSentTrackingDisable(), packetsSentTrackingEnable(), popupMovementParams(), and resetOdometer().
The documentation for this class was generated from the following files:
ArServerSimpleCommands.h
ArServerSimpleCommands.cpp