ArNetworking: ArClientData Class Reference
ArClientData Class Reference
class to hold information about the different data the client has
#include <ArClientData.h>
Public Member Functions
void addDataFlags (const char *dataFlags)
Sets the data flags.
void addFunctor (ArFunctor1< ArNetPacket * > *functor)
Adds a new functor the end of the list.
ArClientData (const char *name, const char *description, unsigned int command, ArFunctor1< ArNetPacket * > *functor)
Constructor.
const char * getArgumentDescription (void)
Gets the argument description.
unsigned int getCommand (void)
const char * getCommandGroup (void)
Gets the command group.
const char * getDataFlagsString (void)
const char * getDescription (void)
Gets the description.
const std::list< ArFunctor1< ArNetPacket * > * > * getFunctorList (void) const
Gets the list of functors.
const char * getName (void)
Gets the name.
const char * getReturnDescription (void)
Gets the return description.
bool hasDataFlag (const char *dataFlag)
int lockFunctorList (void)
Locks the functor list so we can walk it without it changing.
void remFunctor (ArFunctor1< ArNetPacket * > *functor)
Removes a functor from the list all together.
void setArgRetDescs (const char *argDesc, const char *retDesc)
Sets the argument and return descriptions.
void setCommandGroup (const char *commandGroup)
Sets the command group.
int tryLockFunctorList (void)
Tries to lock the functor list so we can walk it without it changing.
int unlockFunctorList (void)
Unlocks the functor list so we can walk it without it changing.
virtual ~ArClientData ()
Destructor.
Protected Attributes
std::string myArgumentDescription
unsigned int myCommand
std::string myCommandGroup
ArArgumentBuilder myDataFlagsBuilder
ArMutex myDataMutex
std::string myDescription
std::list< ArFunctor1< ArNetPacket * > * > myFunctorList
ArMutex myMutex
std::string myName
std::string myReturnDescription
Detailed Description
class to hold information about the different data the client has
This class is mostly just for holding all the information about one of the client data entires in one convenient spot
Information about the data flags held here... The recognized ones right now are just for return values so some forwarding can be done intelligently, you should only have one return value, they are: RETURN_NONE (There are no return packets), RETURN_SINGLE (There is exactly one return packet), RETURN_UNTIL_EMPTY (There return goes until an empty packet), RETURN_VIDEO (this is the special case for video where basically its something thats always requested at an interval and everyone'll want it after we've transfered it), RETURN_COMPLEX (The return is more complex (so you'll need a helper class))
Constructor & Destructor Documentation
ArClientData::ArClientData (const char * name, const char * description, unsigned int command, ArFunctor1< ArNetPacket * > * functor)
Constructor.
References addFunctor(), myCommand, myDataMutex, myDescription, myMutex, myName, and ArMutex::setLogName().
ArClientData::~ArClientData () virtual
Destructor.
Member Function Documentation
void ArClientData::addDataFlags (const char * dataFlags)
Sets the data flags.
References ArArgumentBuilder::add(), ArMutex::lock(), myDataFlagsBuilder, myDataMutex, and ArMutex::unlock().
Referenced by ArClientBase::buildList(), and setCommandGroup().
void ArClientData::addFunctor (ArFunctor1< ArNetPacket * > * functor) inline
Adds a new functor the end of the list.
References myFunctorList.
Referenced by ArClientBase::addHandler(), and ArClientData().
const char* ArClientData::getArgumentDescription (void) inline
Gets the argument description.
References myArgumentDescription.
Referenced by ArCentralForwarder::gatheringCallOnce(), and ArClientBase::logDataList().
unsigned int ArClientData::getCommand (void) inline
References myCommand.
Referenced by ArCentralForwarder::gatheringCallOnce(), and ArClientBase::logDataList().
const char* ArClientData::getCommandGroup (void) inline
Gets the command group.
References hasDataFlag(), and myCommandGroup.
Referenced by ArCentralForwarder::gatheringCallOnce(), and ArClientBase::logDataList().
const char* ArClientData::getDataFlagsString (void) inline
References ArArgumentBuilder::getFullString(), and myDataFlagsBuilder.
Referenced by ArCentralForwarder::gatheringCallOnce(), and ArClientBase::logDataList().
const char* ArClientData::getDescription (void) inline
Gets the description.
References myDescription.
Referenced by ArCentralForwarder::gatheringCallOnce(), and ArClientBase::logDataList().
const std::list<ArFunctor1<ArNetPacket *> *>* ArClientData::getFunctorList (void) const inline
Gets the list of functors.
References myFunctorList.
Referenced by ArClientBase::addHandler(), ArClientBase::logDataList(), and ArClientBase::processPacket().
const char* ArClientData::getName (void) inline
Gets the name.
References myName.
Referenced by ArCentralForwarder::gatheringCallOnce(), and ArClientBase::logDataList().
const char* ArClientData::getReturnDescription (void) inline
Gets the return description.
References myReturnDescription.
Referenced by ArCentralForwarder::gatheringCallOnce(), and ArClientBase::logDataList().
bool ArClientData::hasDataFlag (const char * dataFlag)
References ArArgumentBuilder::getArg(), ArArgumentBuilder::getArgc(), ArMutex::lock(), myDataFlagsBuilder, myDataMutex, and ArMutex::unlock().
Referenced by ArCentralForwarder::gatheringCallOnce(), and getCommandGroup().
int ArClientData::lockFunctorList (void) inline
Locks the functor list so we can walk it without it changing.
References ArMutex::lock(), and myMutex.
Referenced by ArClientBase::addHandler(), ArClientBase::processPacket(), and ArClientBase::remHandler().
void ArClientData::remFunctor (ArFunctor1< ArNetPacket * > * functor) inline
Removes a functor from the list all together.
References myFunctorList.
Referenced by ArClientBase::remHandler().
void ArClientData::setArgRetDescs (const char * argDesc, const char * retDesc) inline
Sets the argument and return descriptions.
References myArgumentDescription, and myReturnDescription.
Referenced by ArClientBase::buildList().
void ArClientData::setCommandGroup (const char * commandGroup) inline
Sets the command group.
References addDataFlags(), and myCommandGroup.
Referenced by ArClientBase::buildList().
int ArClientData::tryLockFunctorList (void) inline
Tries to lock the functor list so we can walk it without it changing.
References myMutex, and ArMutex::tryLock().
int ArClientData::unlockFunctorList (void) inline
Unlocks the functor list so we can walk it without it changing.
References myMutex, and ArMutex::unlock().
Referenced by ArClientBase::addHandler(), ArClientBase::processPacket(), and ArClientBase::remHandler().
Member Data Documentation
std::string ArClientData::myArgumentDescription protected
Referenced by getArgumentDescription(), and setArgRetDescs().
unsigned int ArClientData::myCommand protected
Referenced by ArClientData(), and getCommand().
std::string ArClientData::myCommandGroup protected
Referenced by getCommandGroup(), and setCommandGroup().
ArArgumentBuilder ArClientData::myDataFlagsBuilder protected
Referenced by addDataFlags(), getDataFlagsString(), and hasDataFlag().
ArMutex ArClientData::myDataMutex protected
Referenced by addDataFlags(), ArClientData(), and hasDataFlag().
std::string ArClientData::myDescription protected
Referenced by ArClientData(), and getDescription().
std::list<ArFunctor1<ArNetPacket *> *> ArClientData::myFunctorList protected
Referenced by addFunctor(), getFunctorList(), and remFunctor().
ArMutex ArClientData::myMutex protected
Referenced by ArClientData(), lockFunctorList(), tryLockFunctorList(), and unlockFunctorList().
std::string ArClientData::myName protected
Referenced by ArClientData(), and getName().
std::string ArClientData::myReturnDescription protected
Referenced by getReturnDescription(), and setArgRetDescs().
The documentation for this class was generated from the following files:
ArClientData.h
ArClientData.cpp