ArNetworking: ArServerClient Class Reference
ArServerClient Class Reference
This class represents the server's connection to the client, and contains the socket that the server uses to talk to the client and the information for sending packets to the client.
#include <ArServerClient.h>
Classes
class Tracker
Public Types
enum ServerState { STATE_SENT_INTRO, STATE_REJECTED, STATE_CONNECTED, STATE_DISCONNECTED }
The state of the connection.
Public Member Functions
ArServerClient (ArSocket *tcpSocket, unsigned int udpPort, long authKey, long introKey, ArRetFunctor2< bool, ArNetPacket *, struct sockaddr_in * > *sendUdpCallback, std::map< unsigned int, ArServerData * > *dataMap, const char *passwordKey, const char *serverKey, const ArServerUserInfo *userInfo=NULL, int rejecting=0, const char *rejectingString="", bool debugLogging=false, const char *serverClientName="ArServerBase_unknown", bool logPasswordFailureVerbosely=false, bool allowSlowPackets=true, bool allowIdlePackets=true, const char *enforceProtocolVersion="", ArServerCommands::Type enforceType=ArServerCommands::TYPE_UNSPECIFIED)
Constructor.
void broadcastPacketTcp (ArNetPacket *packet)
Broadcasts a packet over TCP if this client wants this data – For internal use only!
void broadcastPacketUdp (ArNetPacket *packet)
Broadcasts a packet over UDP if this client wants this data (unless client only wants tcp then sends over tcp) – For internal ArNetworking use only!
bool endRequestTransaction ()
Ends the most recent request transaction, decrementing the count.
unsigned int findCommandFromName (const char *commandName) const
Returns the command ID for the specified name, or 0 if it is not found.
void forceDisconnect (bool quiet)
Forcibly disconnect a client (for client/server switching)
long getAuthKey (void)
Gets the authKey used for setting up UDP from this client to the server.
ArTime getCreationTime (void)
Get creation time.
long getFrequency (ArTypes::UByte2 command)
Gets how often a command is asked for.
ArServerClientIdentifier getIdentifier (void) const
Gets the identifier of this server client.
const char * getIPString (void) const
Gets the IP string of the client.
int getRequestTransactionCount ()
Returns the number of request transactions that are currently in progress.
ServerState getState (void)
Gets the state.
ArSocket * getTcpSocket (void)
Internal function to get the tcp socket.
struct sockaddr_in * getUdpAddress (void)
Gets the sin (network address) for the UDP socket.
void handleRequests (void)
Handles the requests for packets.
bool hasGroupAccess (const char *group)
Sees if this client has access to a given group.
bool hasIdlePackets (void)
Gets if we have any idle packets to process.
bool hasSlowPackets (void)
Gets if we have any slow packets to process.
bool idlePacketCallback (void)
The callback for taking care of idle packets (logic on idle elsewhere)
bool isTcpOnly (void)
Gets the tcp only flag.
void logTracking (bool terse)
Logs the tracking information (packet and byte counts)
void processAuthPacket (ArNetPacket *packet, struct sockaddr_in *sin)
Processes the auth packets that came from udp.
void processPacket (ArNetPacket *packet, bool tcp=true)
Process the packet whever it came from.
void resetTracking (void)
Clears the tracking information (resets counters)
virtual bool sendPacketTcp (ArNetPacket *packet)
Send a packet over TCP.
virtual bool sendPacketUdp (ArNetPacket *packet)
Send a packet over UDP (unless client only wants TCP; then sends over TCP).
void setBackupTimeout (double timeoutInMins)
Sets the backup timeout.
void setIdentifier (ArServerClientIdentifier identifier)
Sets the identifier of this server client.
void setUdpAddress (struct sockaddr_in *sin)
Sets the sin (network address) for the UDP socket.
void shutdown (void)
Sends a shutdown command to the socket.
bool slowPacketCallback (void)
The callback for taking care of slow packets.
void startRequestTransaction ()
Starts a new request transaction, incrementing the count.
bool tcpCallback (void)
The callback for taking care of the TCP connection.
void useTcpOnly (void)
Sets the TCP only flag.
virtual ~ArServerClient ()
Destructor.
Protected Member Functions
const char * findCommandName (unsigned int command) const
unsigned int getCommand ()
bool getForceTcpFlag ()
void internalSwitchState (ServerState state)
void popCommand (void)
void popForceTcpFlag (void)
void popSlowIdleCommand (void)
void popSlowIdleForceTcpFlag (void)
void pushCommand (unsigned int num)
void pushForceTcpFlag (bool forceTcp)
void pushSlowIdleCommand (unsigned int num)
void pushSlowIdleForceTcpFlag (bool forceTcp)
void sendListPacket (void)
bool setupPacket (ArNetPacket *packet)
void trackPacketReceived (ArNetPacket *packet, ArTypes::UByte2)
void trackPacketSent (ArNetPacket *packet, bool tcp)
Protected Attributes
bool myAllowIdlePackets
bool myAllowSlowPackets
long myAuthKey
double myBackupTimeout
std::list< unsigned int > myCommandStack
ArTime myCreationTime
std::map< unsigned int, ArServerData * > * myDataMap
bool myDebugLogging
std::string myEnforceProtocolVersion
ArServerCommands::Type myEnforceType
std::list< bool > myForceTcpStack
std::set< std::string, ArStrCaseCmpOp > myGroups
bool myHaveIdlePackets
bool myHaveSlowPackets
ArServerClientIdentifier myIdentifier
std::list< ArNetPacket * > myIdlePackets
ArMutex myIdlePacketsMutex
long myIntroKey
std::string myIPString
bool myLogPasswordFailureVerbosely
std::string myLogPrefix
std::string myPasswordKey
ArFunctor2C< ArServerClient, ArNetPacket *, bool > myProcessPacketCB
int myRejecting
std::string myRejectingString
std::list< ArServerClientData * > myRequested
int myRequestTransactionCount
Number of "request transactions" that are currently in progress for this client.
ArMutex myRequestTransactionMutex
Mutex for multi-threaded access to the request transaction count.
ArRetFunctor2< bool, ArNetPacket *, struct sockaddr_in * > * mySendUdpCB
bool mySentTcpOnly
std::string myServerKey
struct sockaddr_in mySin
std::list< unsigned int > mySlowIdleCommandStack
std::list< bool > mySlowIdleForceTcpStack
ArThread * mySlowIdleThread
std::list< ArNetPacket * > mySlowPackets
ArMutex mySlowPacketsMutex
ServerState myState
ArTime myStateStart
bool myTcpOnly
ArNetPacketReceiverTcp myTcpReceiver
ArNetPacketSenderTcp myTcpSender
ArSocket myTcpSocket
std::map< ArTypes::UByte2, Tracker * > myTrackingReceivedMap
std::map< ArTypes::UByte2, Tracker * > myTrackingSentMap
ArTime myTrackingStarted
bool myUdpConfirmedFrom
bool myUdpConfirmedTo
const ArServerUserInfo * myUserInfo
ArLog::LogLevel myVerboseLogLevel
Detailed Description
This class represents the server's connection to the client, and contains the socket that the server uses to talk to the client and the information for sending packets to the client.
Examples:
drawingsExample.cpp, and drawingsExampleWithRobot.cpp.
Member Enumeration Documentation
enum ArServerClient::ServerState
The state of the connection.
Enumerator
STATE_SENT_INTRO
opened socket, sent our intro to the server
STATE_REJECTED
Client was rejected by server.
STATE_CONNECTED
Client is connected to server.
STATE_DISCONNECTED
Client has disconnected from server.
Constructor & Destructor Documentation
ArServerClient::ArServerClient (ArSocket * tcpSocket, unsigned int udpPort, long authKey, long introKey, ArRetFunctor2< bool, ArNetPacket *, struct sockaddr_in * > * sendUdpCallback, std::map< unsigned int, ArServerData * > * dataMap, const char * passwordKey, const char * serverKey, const ArServerUserInfo * userInfo = NULL, int rejecting = 0, const char * rejectingString = "", bool debugLogging = false, const char * serverClientName = "ArServerBase_unknown", bool logPasswordFailureVerbosely = false, bool allowSlowPackets = true, bool allowIdlePackets = true, const char * enforceProtocolVersion = "", ArServerCommands::Type enforceType = ArServerCommands::TYPE_UNSPECIFIED)
Constructor.
In addition to the normal contructorness this contructor starts the connection between the server and the client going.
Parameters
tcpSocket the socket that has been established between the client and the server
udpPort the udp port the server is using
authKey this authKey must be presented by the client to the server on the server's UDP port for the client to be recognized by the server
introKey this key must be presented by the server to the client so that the client will recognize the server
sendUdpCallback the callback used to send Udp packets (since the udp packets need to be sent from the server's udp port and the serverclient here doesn't have one)
dataMap the map between command numbers and the command data
passwordKey the key (just plain text thats used in an md5 along with the serverKey and the password over on the client side) that was generated for the passwords on this exact connection
serverKey the key (just plain text thats used in an md5 along with the passwordKey and the password over on the client side) that should be used for any connections to this server
debugLogging If true, log some debug messages
logPasswordFailureVerbosely If true, log password errors at ArLog::Verbose level, if false, log them at ArLog::Normal level.
userInfo the pointer to the item that holds our usernames and passwords
rejecting
rejectingString string to reject with
References ArNetPacket::empty(), ArServerBase::enforceProtocolVersion(), ArServerBase::enforceType(), ArSocket::getCloseCallback(), internalSwitchState(), ArServerCommands::INTRODUCTION, myAllowIdlePackets, myAllowSlowPackets, myAuthKey, myCreationTime, myDataMap, myDebugLogging, myEnforceProtocolVersion, myEnforceType, myHaveIdlePackets, myHaveSlowPackets, myIdlePacketsMutex, myIntroKey, myLogPasswordFailureVerbosely, myLogPrefix, myPasswordKey, myProcessPacketCB, myRejecting, myRejectingString, myRequestTransactionMutex, mySendUdpCB, mySentTcpOnly, myServerKey, mySlowIdleThread, mySlowPacketsMutex, myTcpOnly, myTcpReceiver, myTcpSender, myTcpSocket, myUserInfo, myVerboseLogLevel, ArLog::Normal, pushCommand(), resetTracking(), sendPacketTcp(), ArSocket::setCloseCallback(), ArNetPacket::setCommand(), ArNetPacketSenderTcp::setDebugLogging(), setIdentifier(), ArNetPacketSenderTcp::setLoggingPrefix(), ArNetPacketReceiverTcp::setLoggingPrefix(), ArMutex::setLogName(), ArSocket::setNonBlock(), ArNetPacketReceiverTcp::setProcessPacketCB(), ArNetPacketSenderTcp::setSocket(), ArNetPacketReceiverTcp::setSocket(), ArTime::setToNow(), STATE_SENT_INTRO, ArBasePacket::strToBuf(), ArSocket::transfer(), ArBasePacket::uByte2ToBuf(), ArBasePacket::uByte4ToBuf(), and ArLog::Verbose.
ArServerClient::~ArServerClient () virtual
Destructor.
MPL fixing a memory leak
References ArServerData::callRequestChangedFunctor(), ArSocket::close(), data, ArUtil::deleteSet(), ArUtil::deleteSetPairs(), myIdlePackets, myRequested, mySlowPackets, myTcpReceiver, myTcpSocket, myTrackingReceivedMap, myTrackingSentMap, ArNetPacketReceiverTcp::setProcessPacketCB(), and ArNetPacketReceiverTcp::setSocket().
Member Function Documentation
void ArServerClient::broadcastPacketTcp (ArNetPacket * packet)
Broadcasts a packet over TCP if this client wants this data – For internal use only!
References data, ArNetPacket::getCommand(), ArServerData::getCommand(), ArServerClientData::getServerData(), myRequested, and sendPacketTcp().
Referenced by ArServerBase::broadcastPacketTcpByCommandWithExclusion(), and ArMapChanger::sendRobotPacketList().
void ArServerClient::broadcastPacketUdp (ArNetPacket * packet)
Broadcasts a packet over UDP if this client wants this data (unless client only wants tcp then sends over tcp) – For internal ArNetworking use only!
References data, ArNetPacket::getCommand(), ArServerData::getCommand(), ArServerClientData::getServerData(), myRequested, and sendPacketUdp().
Referenced by ArServerBase::broadcastPacketUdpByCommandWithExclusion().
bool ArServerClient::endRequestTransaction ()
Ends the most recent request transaction, decrementing the count.
This method is intended to be called solely by the ArServerBase.
See also
startRequestTransaction().
References ArMutex::lock(), ArLog::log(), myRequestTransactionCount, myRequestTransactionMutex, ArLog::Normal, and ArMutex::unlock().
Referenced by ArServerBase::handleEndRequestTransaction(), and hasIdlePackets().
unsigned int ArServerClient::findCommandFromName (const char * commandName) const
Returns the command ID for the specified name, or 0 if it is not found.
Note that this method is not very efficient; it performs a linear search of all commands.
References ArUtil::isStrEmpty(), and myDataMap.
Referenced by ArMapChanger::handleChangePacket(), and hasIdlePackets().
const char * ArServerClient::findCommandName (unsigned int command) const protected
References myDataMap.
Referenced by getCreationTime(), processPacket(), and setupPacket().
void ArServerClient::forceDisconnect (bool quiet)
Forcibly disconnect a client (for client/server switching)
References getIPString(), internalSwitchState(), ArLog::log(), ArLog::Normal, and STATE_DISCONNECTED.
Referenced by ArServerBase::closeConnectionID(), getTcpSocket(), ArServerBase::loopOnce(), ArCentralManager::netServerSwitch(), ArClientSwitchManager::runThread(), and ArServerBase::slowIdleCallback().
long ArServerClient::getAuthKey (void)
Gets the authKey used for setting up UDP from this client to the server.
References myAuthKey.
unsigned int ArServerClient::getCommand (void) protected
References myCommandStack, mySlowIdleCommandStack, mySlowIdleThread, and ArThread::self().
Referenced by setupPacket().
ArTime ArServerClient::getCreationTime (void) inline
Get creation time.
References findCommandName(), and myCreationTime.
Referenced by ArServerFileFromClient::internalPutFile().
bool ArServerClient::getForceTcpFlag (void) protected
References myForceTcpStack, mySlowIdleForceTcpStack, mySlowIdleThread, and ArThread::self().
Referenced by sendPacketUdp().
long ArServerClient::getFrequency (ArTypes::UByte2 command)
Gets how often a command is asked for.
Parameters
command the command number, you can use findCommandFromName
Returns
returns lowest amount of time requested for this packet, note that 0 and higher means thats how often it was asked for, -1 means nothing requested the data at an interval but wants it when its been pushed, and -2 means that nothing wants the data
References data, ArServerData::getCommand(), ArServerClientData::getMSec(), ArServerClientData::getServerData(), and myRequested.
Referenced by getTcpSocket(), and ArCentralForwarder::receiveData().
ArServerClientIdentifier ArServerClient::getIdentifier (void) const
Gets the identifier of this server client.
References myIdentifier.
Referenced by ArServerBase::broadcastPacketTcpByCommandWithExclusion(), ArServerBase::broadcastPacketUdpByCommandWithExclusion(), ArServerBase::closeConnectionID(), ArCentralManager::forwarderServerClientRemovedCallback(), ArServerBase::identGetConnectionID(), ArServerBase::identSetConnectionID(), ArServerBase::identSetHereGoal(), ArServerBase::identSetSelfIdentifier(), and ArCentralManager::mainServerClientRemovedCallback().
const char * ArServerClient::getIPString (void) const
Gets the IP string of the client.
References myIPString.
Referenced by ArServerDeleteFileOnServer::deleteFile(), ArServerFileToClient::doGetFile(), forceDisconnect(), ArCentralManager::forwarderServerClientRemovedCallback(), ArServerBase::handleEndRequestTransaction(), ArServerBase::handleStartRequestTransaction(), ArServerFileFromClient::internalPutFile(), ArServerHandlerConfig::internalSetConfig(), ArServerBase::logConnections(), logTracking(), ArCentralManager::mainServerClientRemovedCallback(), ArClientSwitchManager::netCentralServerHeartbeat(), ArServerHandlerPopup::netPopupClicked(), ArCentralManager::netServerSwitch(), processPacket(), ArServerHandlerConfig::reloadConfig(), ArCentralForwarder::robotServerClientRemoved(), ArServerHandlerMap::serverGetMapId(), ArServerModeJogPosition::serverHeading(), ArServerModeJogPosition::serverMove(), ArServerModeRatioDrive::serverRatioDrive(), ArServerModeJogPosition::serverTurn(), setIdentifier(), and tcpCallback().
int ArServerClient::getRequestTransactionCount ()
Returns the number of request transactions that are currently in progress.
This method is intended to be called solely by the ArServerBase.
See also
startRequestTransaction().
References ArMutex::lock(), myRequestTransactionCount, myRequestTransactionMutex, and ArMutex::unlock().
Referenced by ArServerBase::getRequestTransactionCount(), and hasIdlePackets().
ServerState ArServerClient::getState (void) inline
Gets the state.
References myState.
Referenced by ArCentralForwarder::clientServerClientRemoved().
ArSocket* ArServerClient::getTcpSocket (void) inline
Internal function to get the tcp socket.
References forceDisconnect(), getFrequency(), and myTcpSocket.
Referenced by ArClientSwitchManager::clientSwitch(), and ArCentralManager::netServerSwitch().
struct sockaddr_in * ArServerClient::getUdpAddress (void)
Gets the sin (network address) for the UDP socket.
References mySin.
void ArServerClient::handleRequests (void)
Handles the requests for packets.
References data, ArServerData::getCommand(), ArServerData::getFunctor(), ArServerClientData::getLastSent(), ArServerClientData::getMSec(), ArServerClientData::getPacket(), ArServerClientData::getServerData(), ArFunctor2< P1, P2 >::invoke(), ArTime::mSecSince(), myRequested, myState, popCommand(), popForceTcpFlag(), pushCommand(), pushForceTcpFlag(), ArServerClientData::setLastSentToNow(), and STATE_CONNECTED.
Referenced by ArServerBase::loopOnce().
bool ArServerClient::hasGroupAccess (const char * group)
Sees if this client has access to a given group.
References myGroups, and myUserInfo.
Referenced by ArServerModeRatioDrive::serverRatioDrive().
bool ArServerClient::hasIdlePackets (void) inline
Gets if we have any idle packets to process.
References endRequestTransaction(), findCommandFromName(), getRequestTransactionCount(), myHaveIdlePackets, and startRequestTransaction().
Referenced by ArServerBase::loopOnce().
bool ArServerClient::hasSlowPackets (void) inline
Gets if we have any slow packets to process.
References myHaveSlowPackets.
Referenced by ArServerBase::loopOnce().
bool ArServerClient::idlePacketCallback (void)
The callback for taking care of idle packets (logic on idle elsewhere)
References ArNetPacket::getCommand(), ArServerData::getFunctor(), ArServerData::getName(), ArServerData::getRequestOnceFunctor(), ArFunctor2< P1, P2 >::invoke(), ArRetFunctor2< Ret, P1, P2 >::invokeR(), ArMutex::lock(), ArLog::log(), myDataMap, myHaveIdlePackets, myIdlePackets, myIdlePacketsMutex, myLogPrefix, mySlowIdleThread, myVerboseLogLevel, popSlowIdleCommand(), popSlowIdleForceTcpFlag(), pushSlowIdleCommand(), pushSlowIdleForceTcpFlag(), ArThread::self(), ArLog::Terse, and ArMutex::unlock().
Referenced by ArServerBase::slowIdleCallback().
void ArServerClient::internalSwitchState (ServerState state) protected
References ArLog::log(), myDebugLogging, myLogPrefix, myState, myStateStart, ArLog::Normal, and ArTime::setToNow().
Referenced by ArServerClient(), forceDisconnect(), processPacket(), and tcpCallback().
bool ArServerClient::isTcpOnly (void) inline
Gets the tcp only flag.
References myTcpOnly.
Referenced by ArClientSwitchManager::runThread().
void ArServerClient::logTracking (bool terse)
Logs the tracking information (packet and byte counts)
References ArSocket::getBytesRecvd(), ArSocket::getBytesSent(), getIPString(), ArSocket::getRecvs(), ArSocket::getSends(), ArLog::log(), ArServerClient::Tracker::myBytesTcp, ArServerClient::Tracker::myBytesUdp, myDataMap, ArServerClient::Tracker::myPacketsTcp, ArServerClient::Tracker::myPacketsUdp, myTcpSocket, myTrackingReceivedMap, myTrackingSentMap, myTrackingStarted, ArTime::secSince(), and ArLog::Terse.
void ArServerClient::popCommand (void) protected
References ArLog::log(), myCommandStack, and ArLog::Terse.
Referenced by handleRequests(), and processPacket().
void ArServerClient::popForceTcpFlag (void) protected
References ArLog::log(), myForceTcpStack, and ArLog::Terse.
Referenced by handleRequests(), and processPacket().
void ArServerClient::popSlowIdleCommand (void) protected
References ArLog::log(), mySlowIdleCommandStack, and ArLog::Terse.
Referenced by idlePacketCallback(), and slowPacketCallback().
void ArServerClient::popSlowIdleForceTcpFlag (void) protected
References ArLog::log(), mySlowIdleForceTcpStack, and ArLog::Terse.
Referenced by idlePacketCallback(), and slowPacketCallback().
void ArServerClient::processAuthPacket (ArNetPacket * packet, struct sockaddr_in * sin)
Processes the auth packets that came from udp.
References ArBasePacket::bufToUByte4(), ArBasePacket::byte4ToBuf(), ArNetPacket::empty(), ArLog::log(), myAuthKey, myIntroKey, mySin, myUdpConfirmedFrom, myVerboseLogLevel, ArSocket::netToHostOrder(), sendPacketTcp(), sendPacketUdp(), ArNetPacket::setCommand(), ArLog::Terse, ArServerCommands::UDP_CONFIRMATION, and ArServerCommands::UDP_INTRODUCTION.
void ArServerClient::processPacket (ArNetPacket * packet, bool tcp = true)
Process the packet whever it came from.
References ArBasePacket::bufToByte(), ArBasePacket::bufToByte4(), ArBasePacket::bufToData(), ArBasePacket::bufToStr(), ArBasePacket::bufToUByte2(), ArBasePacket::byte2ToBuf(), ArBasePacket::byte4ToBuf(), ArServerData::callRequestChangedFunctor(), ArServerCommands::CONNECTED, data, ArNetPacket::duplicatePacket(), ArNetPacket::empty(), findCommandName(), ArNetPacket::getCommand(), ArServerData::getCommand(), ArServerData::getCommandGroup(), ArServerData::getFunctor(), getIPString(), ArBasePacket::getLength(), ArServerData::getName(), ArServerClientData::getPacket(), ArServerData::getRequestOnceFunctor(), ArServerClientData::getServerData(), ArServerUserInfo::getUsersGroups(), ArSocket::hostToNetOrder(), ArSocket::inAddr(), internalSwitchState(), ArClientCommands::INTRODUCTION, ArFunctor2< P1, P2 >::invoke(), ArRetFunctor2< Ret, P1, P2 >::invokeR(), ArServerData::isIdlePacket(), ArServerData::isSlowPacket(), ArMutex::lock(), ArLog::log(), ArServerUserInfo::matchUserPassword(), myAllowIdlePackets, myAllowSlowPackets, myDataMap, myEnforceProtocolVersion, myEnforceType, myGroups, myHaveIdlePackets, myHaveSlowPackets, myIdlePackets, myIdlePacketsMutex, myIntroKey, myLogPasswordFailureVerbosely, myLogPrefix, myPasswordKey, myRejecting, myRejectingString, myRequested, myServerKey, mySlowPackets, mySlowPacketsMutex, myState, myTcpOnly, myTcpSocket, myUdpConfirmedTo, myUserInfo, myVerboseLogLevel, ArLog::Normal, popCommand(), popForceTcpFlag(), pushCommand(), pushForceTcpFlag(), ArServerCommands::REJECTED, ArClientCommands::REQUEST, ArClientCommands::REQUESTSTOP, sendListPacket(), sendPacketTcp(), sendPacketUdp(), ArNetPacket::setCommand(), ArServerClientData::setMSec(), ArServerClientData::setPacket(), setUdpAddress(), ArClientCommands::SHUTDOWN, STATE_CONNECTED, STATE_DISCONNECTED, STATE_REJECTED, STATE_SENT_INTRO, ArBasePacket::strToBuf(), ArClientCommands::TCP_ONLY, ArLog::Terse, trackPacketReceived(), ArServerCommands::TYPE_NONE, ArServerCommands::TYPE_UNSPECIFIED, ArClientCommands::UDP_CONFIRMATION, ArServerCommands::UDP_INTRODUCTION, ArClientCommands::UDP_INTRODUCTION, ArMutex::unlock(), and ArLog::Verbose.
void ArServerClient::pushCommand (unsigned int num) protected
References myCommandStack.
Referenced by ArServerClient(), handleRequests(), and processPacket().
void ArServerClient::pushForceTcpFlag (bool forceTcp) protected
References myForceTcpStack.
Referenced by handleRequests(), and processPacket().
void ArServerClient::pushSlowIdleCommand (unsigned int num) protected
References mySlowIdleCommandStack.
Referenced by idlePacketCallback(), and slowPacketCallback().
void ArServerClient::pushSlowIdleForceTcpFlag (bool forceTcp) protected
References mySlowIdleForceTcpStack.
Referenced by idlePacketCallback(), and slowPacketCallback().
void ArServerClient::resetTracking (void)
Clears the tracking information (resets counters)
References myTcpSocket, myTrackingReceivedMap, myTrackingSentMap, myTrackingStarted, ArSocket::resetTracking(), and ArTime::setToNow().
Referenced by ArServerClient().
void ArServerClient::sendListPacket (void) protected
reset it all back down to 0
References ArNetPacket::empty(), ArNetPacket::FOOTER_LENGTH, ArServerData::getArgumentDescription(), ArServerData::getCommand(), ArServerData::getCommandGroup(), ArServerData::getDataFlagsString(), ArServerData::getDescription(), ArBasePacket::getLength(), ArServerData::getName(), ArServerData::getReturnDescription(), ArServerCommands::LIST, ArServerCommands::LISTARGRET, ArServerCommands::LISTGROUPANDFLAGS, ArNetPacket::MAX_LENGTH, myDataMap, myGroups, myUserInfo, sendPacketTcp(), ArNetPacket::setCommand(), ArBasePacket::setLength(), ArBasePacket::strToBuf(), and ArBasePacket::uByte2ToBuf().
Referenced by processPacket().
bool ArServerClient::sendPacketTcp (ArNetPacket * packet) virtual
Send a packet over TCP.
The command ID of the outgoing packet will be set to the current command ID (from the incoming packet).
References ArNetPacket::getCommand(), ArLog::log(), myDebugLogging, myLogPrefix, myTcpSender, ArLog::Normal, ArNetPacketSenderTcp::sendPacket(), setupPacket(), and trackPacketSent().
Referenced by ArServerInfoRobot::activityTimeInfo(), ArServerClient(), ArServerInfoRobot::batteryInfo(), broadcastPacketTcp(), ArServerDeleteFileOnServer::deleteFile(), ArServerFileToClient::doGetFile(), ArServerHandlerCameraCollection::getCameraList(), ArServerHandlerConfig::getConfigDefaults(), ArServerHandlerConfig::getConfigSectionFlags(), ArServerFileLister::getDefaultUploadDownloadDir(), ArServerFileLister::getDirListing(), ArServerFileLister::getDirListingMultiplePackets(), ArServerHandlerConfig::getLastEditablePriority(), ArServerMode::getModeBusy(), ArServerMode::getModeDataList(), ArServerMode::getModeInfo(), ArServerHandlerCommMonitor::handleAckCommTcp(), ArServerHandlerCamera::handleCameraModeUpdated(), ArMapChanger::handleChangePacket(), ArServerHandlerCamera::handleGetCameraModeList(), ArServerHandlerConfig::handleGetConfig(), ArServerHandlerConfig::handleGetConfigSection(), ArServerHandlerCommMonitor::handleGetHeartbeatInterval(), ArServerBase::identGetConnectionID(), ArServerFileFromClient::internalPutFile(), ArServerHandlerConfig::internalSetConfig(), ArClientSwitchManager::netCentralHeartbeat(), ArCentralManager::netClientList(), ArServerInfoDrawings::netGetDrawingList(), ArServerInfoStrings::netGetStrings(), ArServerInfoStrings::netGetStringsInfo(), ArServerBase::netIdleProcessingPending(), ArServerHandlerCommands::netListCommands(), ArServerInfoDrawings::netListDrawings(), ArServerHandlerCommands::netListStringCommands(), ArServerHandlerPopup::netPopupList(), ArCentralManager::netServerSwitch(), ArServerInfoRobot::physicalInfo(), processAuthPacket(), processPacket(), ArCentralForwarder::receiveData(), sendListPacket(), ArServerHandlerMap::sendMapWithMaxCategory(), sendPacketUdp(), ArHybridForwarderVideo::sendVideoSize(), ArServerHandlerMap::serverGetGoals(), ArServerHandlerMap::serverGetMap(), ArServerHandlerMap::serverGetMapBinary(), ArServerHandlerMap::serverGetMapId(), ArServerHandlerMap::serverGetMapName(), ArServerModeRatioDrive::serverGetSafeDrive(), ArServerHandlerMapping::serverMappingEnd(), ArServerHandlerMapping::serverMappingStart(), ArServerHandlerMapping::serverMappingStatus(), ArServerHandlerConfig::setConfig(), ArServerHandlerConfig::setConfigBySections(), ArServerHandlerConfig::setConfigBySectionsV2(), ArServerHandlerConfig::setConfigParam(), ArServerHandlerCameraCollection::setParams(), shutdown(), tcpCallback(), ArServerInfoRobot::updateStrings(), ArServerHandlerMap::writeLinesToClient(), ArServerHandlerMap::writeMapToClient(), and ArServerHandlerMap::writePointsToClient().
bool ArServerClient::sendPacketUdp (ArNetPacket * packet) virtual
Send a packet over UDP (unless client only wants TCP; then sends over TCP).
The command ID of the outgoing packet will be set to the current command ID (from the incoming packet).
Examples:
drawingsExample.cpp, and drawingsExampleWithRobot.cpp.
References ArNetPacket::getCommand(), getForceTcpFlag(), ArRetFunctor2< Ret, P1, P2 >::invokeR(), ArLog::log(), myDebugLogging, myLogPrefix, mySendUdpCB, mySin, myTcpOnly, ArLog::Normal, sendPacketTcp(), setupPacket(), and trackPacketSent().
Referenced by broadcastPacketUdp(), ArServerHandlerCamera::cameraInfo(), ArServerHandlerCamera::cameraUpdate(), exampleArrowsDrawingNetCallback(), exampleDotsDrawingNetCallback(), exampleHomeDrawingNetCallback(), exampleXDrawingNetCallback(), ArServerInfoSensor::getSensorCumulative(), ArServerInfoSensor::getSensorCurrent(), ArServerInfoSensor::getSensorList(), ArServerHandlerCommMonitor::handleAckCommUdp(), ArServerHandlerCamera::handleGetCameraData(), ArServerHandlerCamera::handleGetCameraInfo(), ArClientSwitchManager::netCentralHeartbeat(), ArServerInfoDrawings::netRangeDeviceCumulative(), ArServerInfoDrawings::netRangeDeviceCurrent(), processAuthPacket(), processPacket(), ArCentralForwarder::receiveData(), ArHybridForwarderVideo::sendVideo(), ArServerInfoRobot::update(), ArServerInfoRobot::updateNumbers(), and Circle::~Circle().
void ArServerClient::setBackupTimeout (double timeoutInMins)
Sets the backup timeout.
References myBackupTimeout, myTcpSender, and ArNetPacketSenderTcp::setBackupTimeout().
Referenced by ArClientSwitchManager::clientSwitch(), ArServerBase::loopOnce(), and ArClientSwitchManager::processFile().
void ArServerClient::setIdentifier (ArServerClientIdentifier identifier)
Sets the identifier of this server client.
References ArServerClientIdentifier::getIDString(), getIPString(), ArSocket::getRawIPString(), ArLog::log(), myIdentifier, myIPString, myLogPrefix, myTcpSocket, ArLog::Normal, and ArSocket::setIPString().
Referenced by ArServerClient(), ArServerBase::identGetConnectionID(), ArServerBase::identSetConnectionID(), ArServerBase::identSetHereGoal(), and ArServerBase::identSetSelfIdentifier().
void ArServerClient::setUdpAddress (struct sockaddr_in * sin)
Sets the sin (network address) for the UDP socket.
References mySin, and sin().
Referenced by processPacket().
bool ArServerClient::setupPacket (ArNetPacket * packet) protected
References ArNetPacket::finalizePacket(), findCommandName(), ArNetPacket::getCommand(), getCommand(), ArBasePacket::getLength(), ArLog::log(), ArNetPacket::MAX_LENGTH, myDebugLogging, myLogPrefix, myState, myVerboseLogLevel, ArNetPacket::setCommand(), STATE_DISCONNECTED, and ArLog::Terse.
Referenced by sendPacketTcp(), and sendPacketUdp().
void ArServerClient::shutdown (void)
Sends a shutdown command to the socket.
References myTcpSender, ArNetPacketSenderTcp::sendData(), sendPacketTcp(), ArNetPacket::setCommand(), and ArServerCommands::SHUTDOWN.
Referenced by ArServerBase::close().
bool ArServerClient::slowPacketCallback (void)
The callback for taking care of slow packets.
References ArNetPacket::getCommand(), ArServerData::getFunctor(), ArServerData::getName(), ArServerData::getRequestOnceFunctor(), ArFunctor2< P1, P2 >::invoke(), ArRetFunctor2< Ret, P1, P2 >::invokeR(), ArMutex::lock(), ArLog::log(), myDataMap, myHaveSlowPackets, myLogPrefix, mySlowIdleThread, mySlowPackets, mySlowPacketsMutex, myVerboseLogLevel, popSlowIdleCommand(), popSlowIdleForceTcpFlag(), pushSlowIdleCommand(), pushSlowIdleForceTcpFlag(), ArThread::self(), ArLog::Terse, and ArMutex::unlock().
Referenced by ArServerBase::slowIdleCallback().
void ArServerClient::startRequestTransaction ()
Starts a new request transaction, incrementing the count.
This method is intended to be called solely by the ArServerBase. It MUST be followed by a call to endRequestTransaction().
Request transactions are used under certain circumstances to indicate that a number of related request/reply packets must be completely processed before background idle processing can proceed. See ArServerBase for more information.
References ArMutex::lock(), myRequestTransactionCount, myRequestTransactionMutex, and ArMutex::unlock().
Referenced by ArServerBase::handleStartRequestTransaction(), and hasIdlePackets().
bool ArServerClient::tcpCallback (void)
The callback for taking care of the TCP connection.
References getIPString(), internalSwitchState(), ArLog::log(), myHaveIdlePackets, myHaveSlowPackets, myLogPrefix, mySentTcpOnly, myState, myStateStart, myTcpOnly, myTcpReceiver, myTcpSender, myVerboseLogLevel, ArNetPacketReceiverTcp::readData(), ArTime::secSince(), ArNetPacketSenderTcp::sendData(), sendPacketTcp(), ArNetPacket::setCommand(), ArUtil::sleep(), STATE_DISCONNECTED, STATE_REJECTED, STATE_SENT_INTRO, and ArServerCommands::TCP_ONLY.
Referenced by ArServerBase::loopOnce(), and ArCentralManager::netServerSwitch().
void ArServerClient::trackPacketReceived (ArNetPacket * packet, ArTypes::UByte2 command) protected
References ArBasePacket::getLength(), ArNetPacket::getPacketSource(), myTrackingReceivedMap, and ArNetPacket::TCP.
Referenced by processPacket().
void ArServerClient::trackPacketSent (ArNetPacket * packet, bool tcp) protected
References ArNetPacket::getCommand(), ArBasePacket::getLength(), and myTrackingSentMap.
Referenced by sendPacketTcp(), and sendPacketUdp().
void ArServerClient::useTcpOnly (void) inline
Sets the TCP only flag.
References myTcpOnly.
Referenced by ArClientSwitchManager::runThread().
Member Data Documentation
bool ArServerClient::myAllowIdlePackets protected
Referenced by ArServerClient(), and processPacket().
bool ArServerClient::myAllowSlowPackets protected
Referenced by ArServerClient(), and processPacket().
long ArServerClient::myAuthKey protected
Referenced by ArServerClient(), getAuthKey(), and processAuthPacket().
double ArServerClient::myBackupTimeout protected
Referenced by setBackupTimeout().
std::list<unsigned int> ArServerClient::myCommandStack protected
Referenced by getCommand(), popCommand(), and pushCommand().
ArTime ArServerClient::myCreationTime protected
Referenced by ArServerClient(), and getCreationTime().
std::map<unsigned int, ArServerData *>* ArServerClient::myDataMap protected
Referenced by ArServerClient(), findCommandFromName(), findCommandName(), idlePacketCallback(), logTracking(), processPacket(), sendListPacket(), and slowPacketCallback().
bool ArServerClient::myDebugLogging protected
Referenced by ArServerClient(), internalSwitchState(), sendPacketTcp(), sendPacketUdp(), and setupPacket().
std::string ArServerClient::myEnforceProtocolVersion protected
Referenced by ArServerClient(), and processPacket().
ArServerCommands::Type ArServerClient::myEnforceType protected
Referenced by ArServerClient(), and processPacket().
std::list<bool> ArServerClient::myForceTcpStack protected
Referenced by getForceTcpFlag(), popForceTcpFlag(), and pushForceTcpFlag().
std::set<std::string, ArStrCaseCmpOp> ArServerClient::myGroups protected
Referenced by hasGroupAccess(), processPacket(), and sendListPacket().
bool ArServerClient::myHaveIdlePackets protected
Referenced by ArServerClient(), hasIdlePackets(), idlePacketCallback(), processPacket(), and tcpCallback().
bool ArServerClient::myHaveSlowPackets protected
Referenced by ArServerClient(), hasSlowPackets(), processPacket(), slowPacketCallback(), and tcpCallback().
ArServerClientIdentifier ArServerClient::myIdentifier protected
Referenced by getIdentifier(), and setIdentifier().
std::list<ArNetPacket *> ArServerClient::myIdlePackets protected
Referenced by idlePacketCallback(), processPacket(), and ~ArServerClient().
ArMutex ArServerClient::myIdlePacketsMutex protected
Referenced by ArServerClient(), idlePacketCallback(), and processPacket().
long ArServerClient::myIntroKey protected
Referenced by ArServerClient(), processAuthPacket(), and processPacket().
std::string ArServerClient::myIPString protected
Referenced by getIPString(), and setIdentifier().
bool ArServerClient::myLogPasswordFailureVerbosely protected
Referenced by ArServerClient(), and processPacket().
std::string ArServerClient::myLogPrefix protected
Referenced by ArServerClient(), idlePacketCallback(), internalSwitchState(), processPacket(), sendPacketTcp(), sendPacketUdp(), setIdentifier(), setupPacket(), slowPacketCallback(), and tcpCallback().
std::string ArServerClient::myPasswordKey protected
Referenced by ArServerClient(), and processPacket().
ArFunctor2C<ArServerClient, ArNetPacket *, bool> ArServerClient::myProcessPacketCB protected
Referenced by ArServerClient().
int ArServerClient::myRejecting protected
Referenced by ArServerClient(), and processPacket().
std::string ArServerClient::myRejectingString protected
Referenced by ArServerClient(), and processPacket().
std::list<ArServerClientData *> ArServerClient::myRequested protected
Referenced by broadcastPacketTcp(), broadcastPacketUdp(), getFrequency(), handleRequests(), processPacket(), and ~ArServerClient().
int ArServerClient::myRequestTransactionCount protected
Number of "request transactions" that are currently in progress for this client.
Referenced by endRequestTransaction(), getRequestTransactionCount(), and startRequestTransaction().
ArMutex ArServerClient::myRequestTransactionMutex protected
Mutex for multi-threaded access to the request transaction count.
Referenced by ArServerClient(), endRequestTransaction(), getRequestTransactionCount(), and startRequestTransaction().
ArRetFunctor2<bool, ArNetPacket *, struct sockaddr_in *>* ArServerClient::mySendUdpCB protected
Referenced by ArServerClient(), and sendPacketUdp().
bool ArServerClient::mySentTcpOnly protected
Referenced by ArServerClient(), and tcpCallback().
std::string ArServerClient::myServerKey protected
Referenced by ArServerClient(), and processPacket().
struct sockaddr_in ArServerClient::mySin protected
Referenced by getUdpAddress(), processAuthPacket(), sendPacketUdp(), and setUdpAddress().
std::list<unsigned int> ArServerClient::mySlowIdleCommandStack protected
Referenced by getCommand(), popSlowIdleCommand(), and pushSlowIdleCommand().
std::list<bool> ArServerClient::mySlowIdleForceTcpStack protected
Referenced by getForceTcpFlag(), popSlowIdleForceTcpFlag(), and pushSlowIdleForceTcpFlag().
ArThread* ArServerClient::mySlowIdleThread protected
Referenced by ArServerClient(), getCommand(), getForceTcpFlag(), idlePacketCallback(), and slowPacketCallback().
std::list<ArNetPacket *> ArServerClient::mySlowPackets protected
Referenced by processPacket(), slowPacketCallback(), and ~ArServerClient().
ArMutex ArServerClient::mySlowPacketsMutex protected
Referenced by ArServerClient(), processPacket(), and slowPacketCallback().
ServerState ArServerClient::myState protected
Referenced by getState(), handleRequests(), internalSwitchState(), processPacket(), setupPacket(), and tcpCallback().
ArTime ArServerClient::myStateStart protected
Referenced by internalSwitchState(), and tcpCallback().
bool ArServerClient::myTcpOnly protected
Referenced by ArServerClient(), isTcpOnly(), processPacket(), sendPacketUdp(), tcpCallback(), and useTcpOnly().
ArNetPacketReceiverTcp ArServerClient::myTcpReceiver protected
Referenced by ArServerClient(), tcpCallback(), and ~ArServerClient().
ArNetPacketSenderTcp ArServerClient::myTcpSender protected
Referenced by ArServerClient(), sendPacketTcp(), setBackupTimeout(), shutdown(), and tcpCallback().
ArSocket ArServerClient::myTcpSocket protected
Referenced by ArServerClient(), getTcpSocket(), logTracking(), processPacket(), resetTracking(), setIdentifier(), and ~ArServerClient().
std::map<ArTypes::UByte2, Tracker *> ArServerClient::myTrackingReceivedMap protected
Referenced by logTracking(), resetTracking(), trackPacketReceived(), and ~ArServerClient().
std::map<ArTypes::UByte2, Tracker *> ArServerClient::myTrackingSentMap protected
Referenced by logTracking(), resetTracking(), trackPacketSent(), and ~ArServerClient().
ArTime ArServerClient::myTrackingStarted protected
Referenced by logTracking(), and resetTracking().
bool ArServerClient::myUdpConfirmedFrom protected
Referenced by processAuthPacket().
bool ArServerClient::myUdpConfirmedTo protected
Referenced by processPacket().
const ArServerUserInfo* ArServerClient::myUserInfo protected
Referenced by ArServerClient(), hasGroupAccess(), processPacket(), and sendListPacket().
ArLog::LogLevel ArServerClient::myVerboseLogLevel protected
Referenced by ArServerClient(), idlePacketCallback(), processAuthPacket(), processPacket(), setupPacket(), slowPacketCallback(), and tcpCallback().
The documentation for this class was generated from the following files:
ArServerClient.h
ArServerClient.cpp