ArNetworking: ArServerSimpleConnectionTester Class Reference
ArServerSimpleConnectionTester Class Reference
Class for sending commands to the microcontroller (uC)
#include <ArServerSimpleCommands.h>
Public Member Functions
ArServerSimpleConnectionTester (ArServerHandlerCommands *handlerCommands, ArRobot *robot)
Constructor.
void connectionTestStart (void)
Handles the command.
void connectionTestStop (void)
Handles the motor commands.
virtual ~ArServerSimpleConnectionTester ()
Destructor.
Protected Member Functions
void log (void)
bool packetHandler (ArRobotPacket *packet)
void userTask (void)
Protected Attributes
ArFunctorC
< ArServerSimpleConnectionTester > myConnectionTestStartCB
ArFunctorC
< ArServerSimpleConnectionTester > myConnectionTestStopCB
int myCyclesSincePacket
bool myFirst
ArServerHandlerCommands * myHandlerCommands
ArTime myLastLog
int myMissedMotorPackets
int myMissedPackets
ArRetFunctor1C< bool,
ArServerSimpleConnectionTester,
ArRobotPacket * > myPacketHandlerCB
ArTime myPacketReceived
int myPacketsThisCycle
int myReceivedPackets
ArRobot * myRobot
ArFunctorC
< ArServerSimpleConnectionTester > myUserTaskCB
Detailed Description
Class for sending commands to the microcontroller (uC)
This class will let you send commands to the microcontroller (com, comInt, and com2Bytes).
Constructor & Destructor Documentation
ArServerSimpleConnectionTester::ArServerSimpleConnectionTester (ArServerHandlerCommands * handlerCommands, ArRobot * robot)
Constructor.
References ArServerHandlerCommands::addCommand(), myConnectionTestStartCB, myConnectionTestStopCB, myHandlerCommands, myPacketHandlerCB, myRobot, myUserTaskCB, and ArFunctor::setName().
ArServerSimpleConnectionTester::~ArServerSimpleConnectionTester () [virtual]
Destructor.
Member Function Documentation
void ArServerSimpleConnectionTester::connectionTestStart (void)
Handles the command.
References ArRobot::addPacketHandler(), ArRobot::addUserTask(), ArListPos::FIRST, ArRobot::lock(), log(), myFirst, myPacketHandlerCB, myRobot, myUserTaskCB, ArLog::Normal, ArRobot::remPacketHandler(), ArRobot::remUserTask(), and ArRobot::unlock().
void ArServerSimpleConnectionTester::connectionTestStop (void)
Handles the motor commands.
References ArRobot::lock(), log(), myPacketHandlerCB, myRobot, myUserTaskCB, ArLog::Normal, ArRobot::remPacketHandler(), ArRobot::remUserTask(), and ArRobot::unlock().
void ArServerSimpleConnectionTester::log (void) [protected]
References ArRobot::getMotorPacCount(), myMissedPackets, myReceivedPackets, myRobot, and ArLog::Normal.
Referenced by connectionTestStart(), connectionTestStop(), and userTask().
bool ArServerSimpleConnectionTester::packetHandler (ArRobotPacket * packet) [protected]
References ArRobotPacket::getID(), myPacketReceived, myPacketsThisCycle, myReceivedPackets, ArCommands::SAFETY_STATE_INFO, and ArTime::setToNow().
void ArServerSimpleConnectionTester::userTask (void) [protected]
References ArRobot::comInt(), ArCommands::ENCODER, log(), ArTime::mSecSince(), myCyclesSincePacket, myFirst, myLastLog, myMissedPackets, myPacketReceived, myPacketsThisCycle, myReceivedPackets, myRobot, ArCommands::SAFETY_STATE_INFO, ArTime::secSince(), and ArTime::setToNow().
Member Data Documentation
ArFunctorC<ArServerSimpleConnectionTester> ArServerSimpleConnectionTester::myConnectionTestStartCB [protected]
Referenced by ArServerSimpleConnectionTester().
ArFunctorC<ArServerSimpleConnectionTester> ArServerSimpleConnectionTester::myConnectionTestStopCB [protected]
Referenced by ArServerSimpleConnectionTester().
int ArServerSimpleConnectionTester::myCyclesSincePacket [protected]
Referenced by userTask().
bool ArServerSimpleConnectionTester::myFirst [protected]
Referenced by connectionTestStart(), and userTask().
ArServerHandlerCommands* ArServerSimpleConnectionTester::myHandlerCommands [protected]
Referenced by ArServerSimpleConnectionTester().
ArTime ArServerSimpleConnectionTester::myLastLog [protected]
Referenced by userTask().
int ArServerSimpleConnectionTester::myMissedMotorPackets [protected]
int ArServerSimpleConnectionTester::myMissedPackets [protected]
Referenced by log(), and userTask().
ArRetFunctor1C<bool, ArServerSimpleConnectionTester, ArRobotPacket *> ArServerSimpleConnectionTester::myPacketHandlerCB [protected]
Referenced by ArServerSimpleConnectionTester(), connectionTestStart(), and connectionTestStop().
ArTime ArServerSimpleConnectionTester::myPacketReceived [protected]
Referenced by packetHandler(), and userTask().
int ArServerSimpleConnectionTester::myPacketsThisCycle [protected]
Referenced by packetHandler(), and userTask().
int ArServerSimpleConnectionTester::myReceivedPackets [protected]
Referenced by log(), packetHandler(), and userTask().
ArRobot* ArServerSimpleConnectionTester::myRobot [protected]
Referenced by ArServerSimpleConnectionTester(), connectionTestStart(), connectionTestStop(), log(), and userTask().
ArFunctorC<ArServerSimpleConnectionTester> ArServerSimpleConnectionTester::myUserTaskCB [protected]
Referenced by ArServerSimpleConnectionTester(), connectionTestStart(), and connectionTestStop().
The documentation for this class was generated from the following files:
ArServerSimpleCommands.h
ArServerSimpleCommands.cpp