ArNetworking: ArServerSimpleComLogRobotConfig Class Reference
ArServerSimpleComLogRobotConfig Class Reference
Request configuration from robot controller and log the result.
#include <ArServerSimpleCommands.h>
Public Member Functions
ArServerSimpleComLogRobotConfig (ArServerHandlerCommands *commands, ArRobot *robot, ArServerHandlerPopup *popupHandler=NULL)
void logConfig (void)
void logMovementConfig (void)
void logOrigConfig (void)
void popupConfig (void)
void popupMovementConfig (void)
void popupOrigConfig (void)
Detailed Description
Request configuration from robot controller and log the result.
Examples:
serverDemo.cpp.
Constructor & Destructor Documentation
ArServerSimpleComLogRobotConfig::ArServerSimpleComLogRobotConfig (ArServerHandlerCommands * commands, ArRobot * robot, ArServerHandlerPopup * popupHandler = NULL)
References ArServerHandlerCommands::addCommand().
Member Function Documentation
void ArServerSimpleComLogRobotConfig::logConfig (void)
References ArRobot::lock(), ArLog::log(), ArLog::Normal, ArRobotConfigPacketReader::requestPacket(), and ArRobot::unlock().
void ArServerSimpleComLogRobotConfig::logMovementConfig (void)
References ArRobot::lock(), ArLog::log(), ArLog::Normal, ArRobotConfigPacketReader::requestPacket(), and ArRobot::unlock().
void ArServerSimpleComLogRobotConfig::logOrigConfig (void)
References ArRobot::getOrigRobotConfig(), ArRobotConfigPacketReader::hasPacketArrived(), ArRobot::lock(), ArLog::log(), ArRobotConfigPacketReader::log(), ArLog::Normal, and ArRobot::unlock().
void ArServerSimpleComLogRobotConfig::popupConfig (void)
References ArRobot::lock(), ArLog::log(), ArLog::Normal, ArRobotConfigPacketReader::requestPacket(), and ArRobot::unlock().
void ArServerSimpleComLogRobotConfig::popupMovementConfig (void)
References ArRobot::lock(), ArLog::log(), ArLog::Normal, ArRobotConfigPacketReader::requestPacket(), and ArRobot::unlock().
void ArServerSimpleComLogRobotConfig::popupOrigConfig (void)
References ArRobotConfigPacketReader::buildString(), ArRobotConfigPacketReader::buildStringMovement(), ArServerHandlerPopup::createPopup(), ArRobot::getOrigRobotConfig(), ArRobotConfigPacketReader::hasPacketArrived(), ArServerHandlerPopup::INFORMATION, ArRobot::lock(), ArRobotConfigPacketReader::log(), ArLog::log(), ArRobotConfigPacketReader::logMovement(), ArLog::Normal, and ArRobot::unlock().
The documentation for this class was generated from the following files:
ArServerSimpleCommands.h
ArServerSimpleCommands.cpp