ArNetworking: ArNetCameraRequest Class Reference
ArNetCameraRequest Class Reference
A request packet that is able to send a copy of itself, with data packed in, to a server.
Public Member Functions
ArNetCameraRequest (ArClientBase *client, const char *cameraName="")
bool requestPanTiltAbs (double pan, double tilt)
bool requestPanTiltZoomAbs (double pan, double tilt, double zoom)
void setCameraName (const char *name)
Public Member Functions inherited from ArNetPacket
ArNetPacket (ArTypes::UByte2 bufferSize=ArNetPacket::MAX_LENGTH+5)
Constructor.
ArNetPacket (const ArNetPacket &other)
Copy constructor.
virtual double bufToDouble (void)
Gets a double from the packet buffer.
ArTypes::Byte2 calcCheckSum (void)
returns the checksum, probably used only internally
virtual void doubleToBuf (double val)
Puts a double into the packet buffer.
virtual void duplicatePacket (ArNetPacket *packet)
virtual void empty (void)
virtual void finalizePacket (void)
bool getAddedFooter (void)
Iternal function that sets if we already added the footer(for forwarding)
const char * getArbitraryString (void)
ArTypes::UByte2 getCommand (void)
Gets the command this packet is.
PacketSource getPacketSource (void)
ArNetPacket & operator= (const ArNetPacket &other)
Assignment operator.
virtual void resetRead (void)
void setAddedFooter (bool addedFooter)
Iternal function that sets if we already added the footer(for forwarding)
void setArbitraryString (const char *string)
void setCommand (ArTypes::UByte2 command)
Sets the command this packet is.
void setPacketSource (PacketSource source)
bool verifyCheckSum (void)
returns true if the checksum matches what it should be
virtual ~ArNetPacket ()
Destructor.
Public Member Functions inherited from ArBasePacket
ArBasePacket (ArTypes::UByte2 bufferSize=0, ArTypes::UByte2 headerLength=0, char *buf=NULL, ArTypes::UByte2 footerLength=0)
ArBasePacket (const ArBasePacket &other)
virtual ArTypes::Byte bufToByte (void)
virtual ArTypes::Byte2 bufToByte2 (void)
virtual ArTypes::Byte4 bufToByte4 (void)
virtual ArTypes::Byte8 bufToByte8 (void)
virtual void bufToData (unsigned char *data, int length)
virtual void bufToData (char *data, int length)
virtual void bufToStr (char *buf, int maxlen)
std::string bufToString ()
virtual ArTypes::UByte bufToUByte (void)
virtual ArTypes::UByte2 bufToUByte2 (void)
virtual ArTypes::UByte4 bufToUByte4 (void)
virtual ArTypes::UByte8 bufToUByte8 (void)
virtual void byte2ToBuf (ArTypes::Byte2 val)
virtual void byte4ToBuf (ArTypes::Byte4 val)
virtual void byte8ToBuf (ArTypes::Byte8 val)
virtual void byteToBuf (ArTypes::Byte val)
virtual void dataToBuf (const char *data, int length)
virtual void dataToBuf (const unsigned char *data, int length)
virtual void duplicatePacket (ArBasePacket *packet)
virtual const char * getBuf (void) const
virtual char * getBuf (void)
virtual ArTypes::UByte2 getDataLength (void) const
virtual ArTypes::UByte2 getDataReadLength (void) const
virtual ArTypes::UByte2 getFooterLength (void) const
virtual ArTypes::UByte2 getHeaderLength (void) const
virtual ArTypes::UByte2 getLength (void) const
virtual ArTypes::UByte2 getMaxLength (void) const
virtual ArTypes::UByte2 getReadLength (void) const
virtual bool isValid (void)
virtual void log (void)
ArBasePacket & operator= (const ArBasePacket &other)
virtual void printHex (void)
virtual void resetValid ()
virtual void setBuf (char *buf, ArTypes::UByte2 bufferSize)
virtual bool setHeaderLength (ArTypes::UByte2 length)
virtual bool setLength (ArTypes::UByte2 length)
virtual void setMaxLength (ArTypes::UByte2 bufferSize)
virtual void setReadLength (ArTypes::UByte2 readLength)
virtual void strNToBuf (const char *str, int length)
virtual void strToBuf (const char *str)
virtual void strToBufPadded (const char *str, int length)
virtual void uByte2ToBuf (ArTypes::UByte2 val)
virtual void uByte4ToBuf (ArTypes::UByte4 val)
virtual void uByte8ToBuf (ArTypes::UByte8 val)
virtual void uByteToBuf (ArTypes::UByte val)
virtual ~ArBasePacket ()
Additional Inherited Members
Public Types inherited from ArNetPacket
enum {
SIZE_OF_LENGTH = 2, MAX_LENGTH = 32000, HEADER_LENGTH = 6, FOOTER_LENGTH = 2,
MAX_DATA_LENGTH = MAX_LENGTH - HEADER_LENGTH - FOOTER_LENGTH - SIZE_OF_LENGTH
}
enum PacketSource { TCP, UDP }
an enum for where the packet came from
Protected Member Functions inherited from ArBasePacket
bool hasWriteCapacity (int bytes)
Protected Attributes inherited from ArNetPacket
bool myAddedFooter
std::string myArbitraryString
ArTypes::UByte2 myCommand
PacketSource myPacketSource
Detailed Description
A request packet that is able to send a copy of itself, with data packed in, to a server.
Examples:
ptzCameraClientExample.cpp.
Constructor & Destructor Documentation
ArNetCameraRequest::ArNetCameraRequest (ArClientBase * client, const char * cameraName = "") inline
Examples:
ptzCameraClientExample.cpp.
Member Function Documentation
bool ArNetCameraRequest::requestPanTiltAbs (double pan, double tilt)
Examples:
ptzCameraClientExample.cpp.
References ArBasePacket::byte2ToBuf(), ArNetPacket::empty(), and ArNetPacket::finalizePacket().
Referenced by PtzCameraExample::run(), and setCameraName().
bool ArNetCameraRequest::requestPanTiltZoomAbs (double pan, double tilt, double zoom)
Examples:
ptzCameraClientExample.cpp.
References ArBasePacket::byte2ToBuf(), ArNetPacket::empty(), and ArNetPacket::finalizePacket().
Referenced by setCameraName().
void ArNetCameraRequest::setCameraName (const char * name) inline
Examples:
ptzCameraClientExample.cpp.
References requestPanTiltAbs(), and requestPanTiltZoomAbs().
The documentation for this class was generated from the following file:
ptzCameraClientExample.cpp