ArNetworking: ArServerModeStop Class Reference
ArServerModeStop Class Reference
#include <ArServerModeStop.h>
Public Member Functions
virtual void activate (void)
The function called when the mode is activated.
void addToConfig (ArConfig *config, const char *section="Teleop settings")
Adds to the config.
ArServerModeStop (ArServerBase *server, ArRobot *robot, bool defunct=false)
virtual void checkDefault (void)
Sees if this wants to become the default mode.
virtual void deactivate (void)
The function called when the mode is deactivated.
virtual ArActionGroup * getActionGroup (void)
This function should return the action group this mode uses.
bool getUseLocationDependentDevices (void)
Gets whether we're using the range devices that depend on location.
void netStop (ArServerClient *client, ArNetPacket *packet)
void setUseLocationDependentDevices (bool useLocationDependentDevices, bool internal=false)
Sets whether we're using the range devices that depend on location.
void stop (void)
virtual void userTask (void)
The ArMode's user task, don't need one, subclass must provide if needed.
virtual ~ArServerModeStop ()
Public Member Functions inherited from ArServerMode
virtual void activationDenied (void)
The function called if the mode is not activated because another mode superceded it.
void addActivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is activated.
void addAsDefaultMode (ArListPos::Pos pos=ArListPos::LAST)
Sets this mode to default (so if a mode deactivates it activates this)
void addDeactivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is deactivated.
bool addModeData (const char *name, const char *description, ArFunctor2< ArServerClient *, ArNetPacket * > *functor, const char *argumentDescription, const char *returnDescription, const char *commandGroup=NULL, const char *dataFlags=NULL)
This basically just notes the commands associated with a mode so that clients can know what can and can't happen based on what mode is active/locked/etc.
void addSingleShotDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for when this class is deactivated.
void addSingleShotPostDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for just after the deactivate happens (when the next mode has activated)
ArServerMode (ArRobot *robot, ArServerBase *server, const char *name)
Constructor.
virtual void forceUnlock (void)
This will be called if another mode has to break the lock.
ArTime getActivityTime (void)
Gets the time of our last activity.
const char * getExtendedStatus (void) const
Gets a string representing the extended status of the mode we're in.
const char * getMode (void) const
Gets a string representing the mode we're in.
const char * getName (void) const
Gets the name of the mode we're in.
const char * getStatus (void) const
Gets a string representing the status of the mode we're in.
bool hasSetActivityTime (void)
Gets if we've set our activity time.
void internalSetActivityTime (ArTime time)
Internal call to set the activity time (this is dangerous and shouldn't be used)
bool isActive (void) const
Gets if this mode is active or not.
virtual bool isAutoResumeAfterInterrupt ()
Adds data to the list of this mode's commands.
void lockMode (bool willUnlockIfRequested=false)
Locks this mode in until its unlocked (mode must be the active mode)
void remActivateCallback (ArFunctor *functor)
Removes a callback for when this class is activated.
void remDeactivateCallback (ArFunctor *functor)
Removes a callback for when this class is deactivated.
void remSingleShotDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for when this class is deactivated.
void remSingleShotPostDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for just after the deactivate happens (when the next mode has activated)
virtual void requestUnlock (void)
This will be called if another mode wants the lock broken (can ignore)
void setActivityTimeToNow (void)
Sets that we're active right now.
void setMode (const char *str)
This should only be used by careful people and probably not then.
void setStatus (const char *str)
This should only be used by careful people and probably not then.
void unlockMode (void)
Unlocks the mode so other modes can activate.
virtual ~ArServerMode ()
Destructor.
Protected Attributes
ArActionDeceleratingLimiter * myLimiterBackward
ArActionDeceleratingLimiter * myLimiterForward
ArActionDeceleratingLimiter * myLimiterLateralLeft
ArActionDeceleratingLimiter * myLimiterLateralRight
ArFunctor2C< ArServerModeStop, ArServerClient *, ArNetPacket * > myNetStopCB
ArActionGroupStop myStopGroup
bool myUseLocationDependentDevices
Protected Attributes inherited from ArServerMode
ArCallbackList myActivateCallbacks
ArTime myActivityTime
ArMutex myActivityTimeMutex
ArCallbackList myDeactivateCallbacks
std::string myExtendedStatus
bool myHasSetActivityTime
bool myIsActive
std::string myMode
std::string myName
ArRobot * myRobot
ArServerBase * myServer
bool mySetActivityThisCycle
ArCallbackList mySingleShotDeactivateCallbacks
ArCallbackList mySingleShotPostDeactivateCallbacks
std::string myStatus
bool myStatusSetThisCycle
ArLog::LogLevel myVerboseLogLevel
Additional Inherited Members
Static Public Member Functions inherited from ArServerMode
static ArServerMode * getActiveMode (void)
Gets the active mode.
static int getActiveModeActivityTimeSecSince (void)
Gets the seconds since the activity of our active mode.
static const char * getActiveModeExtendedStatusString (void)
Gets the active extended status string.
static const char * getActiveModeModeString (void)
Gets the active mode string.
static bool getActiveModeSetActivityThisCycle (void)
Gets if the active mode set the activity time this cycle or not.
static const char * getActiveModeStatusString (void)
Gets the active status string.
static ArServerModeIdle * getIdleMode (void)
Call that gets our idle mode.
static void getModeBusy (ArServerClient *client, ArNetPacket *packet)
Handles the packet request for the mode busy state.
static void getModeDataList (ArServerClient *client, ArNetPacket *packet)
Gets the list of data for each mode.
static void getModeInfo (ArServerClient *client, ArNetPacket *packet)
Gets the info about which mode is active and such.
static bool isLocked (void)
Gets if the active mode is locked or not.
static bool willUnlockIfRequested (void)
Gets whether we'll unlock if requested or not.
Protected Member Functions inherited from ArServerMode
bool baseActivate (bool canSelfActivateIfLocked=false)
Activates this mode if it can (returns true if it can, false otherwise).
void baseDeactivate (void)
Deactivates this mode.
void checkBroadcastModeInfoPacket (void)
ArServerMode * getLastActiveMode ()
Static Protected Member Functions inherited from ArServerMode
static void buildModeInfoPacket (ArNetPacket *packet)
static std::list< ArServerMode * > * getRequestedActivateModes (void)
static void modeUserTask (void)
Static Protected Attributes inherited from ArServerMode
static ArServerMode * ourActiveMode = NULL
static bool ourActiveModeLocked = false
static bool ourActiveModeSetActivityThisCycle = false
static bool ourActiveModeWillUnlockIfRequested = false
static ArServerMode * ourBroadcastActiveMode = NULL
static bool ourBroadcastActiveModeLocked = false
static bool ourBroadcastActiveModeWillUnlockIfRequested = false
static std::list< ArServerMode * > ourDefaultModes
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeBusyCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeDataListCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeInfoCB
static ArServerModeIdle * ourIdleMode = NULL
static bool ourIdleModeCreated = false
static ArMutex ourIdleModeMutex
static bool ourIsBusy = false
static ArServerMode * ourLastActiveMode = NULL
static std::multimap< std::string, std::string > ourModeDataMap
static ArMutex ourModeDataMapMutex
static std::list< ArServerMode * > ourModes
static ArServerMode * ourNextActiveMode = NULL
static std::list< ArServerMode * > ourRequestedActivateModes
static ArServerBase * ourServerBase = NULL
static bool ourUserTaskAdded = false
static ArGlobalFunctor ourUserTaskCB
Detailed Description
Examples:
drawingsExampleWithRobot.cpp, popupExample.cpp, and serverDemo.cpp.
Constructor & Destructor Documentation
ArServerModeStop::ArServerModeStop (ArServerBase * server, ArRobot * robot, bool defunct = false)
References ArActionGroup::addAction(), ArServerMode::addModeData(), ArActionDeceleratingLimiter::BACKWARDS, ArRobot::hasLatVel(), ArActionDeceleratingLimiter::LATERAL_LEFT, ArActionDeceleratingLimiter::LATERAL_RIGHT, myLimiterBackward, myLimiterForward, myLimiterLateralLeft, myLimiterLateralRight, ArServerMode::myMode, myNetStopCB, ArServerMode::myRobot, ArServerMode::myServer, myStopGroup, and myUseLocationDependentDevices.
ArServerModeStop::~ArServerModeStop () virtual
Member Function Documentation
void ArServerModeStop::activate (void) virtual
The function called when the mode is activated.
Subclasses must implement this, but also call baseActivate().-
Implements ArServerMode.
Examples:
popupExample.cpp, and serverDemo.cpp.
References ArActionGroup::activateExclusive(), ArServerMode::baseActivate(), ArRobot::clearDirectMotion(), ArServerMode::isActive(), ArServerMode::myRobot, ArServerMode::myStatus, myStopGroup, ArServerMode::setActivityTimeToNow(), and ArRobot::stop().
Referenced by checkDefault(), main(), and stop().
void ArServerModeStop::addToConfig (ArConfig * config, const char * section = "Teleop settings")
Adds to the config.
References ArActionDeceleratingLimiter::addToConfig(), myLimiterBackward, myLimiterForward, myLimiterLateralLeft, and myLimiterLateralRight.
Referenced by getActionGroup().
virtual void ArServerModeStop::checkDefault (void) inline virtual
Sees if this wants to become the default mode.
This will be called when there would be no other modes, if this mode wants to take over it should activate itself, if it doesn't want to take over it shouldn't activate
Reimplemented from ArServerMode.
References activate().
void ArServerModeStop::deactivate (void) virtual
The function called when the mode is deactivated.
Subclasses must implement this, and also call baseDeactivate().
Implements ArServerMode.
References ArServerMode::baseDeactivate(), ArActionGroup::deactivate(), and myStopGroup.
virtual ArActionGroup* ArServerModeStop::getActionGroup (void) inline virtual
This function should return the action group this mode uses.
Reimplemented from ArServerMode.
References addToConfig(), getUseLocationDependentDevices(), myStopGroup, and setUseLocationDependentDevices().
bool ArServerModeStop::getUseLocationDependentDevices (void)
Gets whether we're using the range devices that depend on location.
References myUseLocationDependentDevices.
Referenced by getActionGroup().
void ArServerModeStop::netStop (ArServerClient * client, ArNetPacket * packet)
References ArRobot::lock(), ArLog::log(), ArServerMode::myRobot, ArServerMode::setActivityTimeToNow(), stop(), ArRobot::unlock(), and ArLog::Verbose.
void ArServerModeStop::setUseLocationDependentDevices (bool useLocationDependentDevices, bool internal = false)
Sets whether we're using the range devices that depend on location.
References ArRobot::lock(), myLimiterBackward, myLimiterForward, myLimiterLateralLeft, myLimiterLateralRight, ArServerMode::myRobot, myUseLocationDependentDevices, ArActionDeceleratingLimiter::setUseLocationDependentDevices(), and ArRobot::unlock().
Referenced by getActionGroup().
void ArServerModeStop::stop (void)
References activate().
Referenced by netStop().
void ArServerModeStop::userTask (void) virtual
The ArMode's user task, don't need one, subclass must provide if needed.
MPL 2014_04_17 centralizing all the places stopped is calculated
Reimplemented from ArServerMode.
References ArRobot::isStopped(), ArServerMode::myRobot, ArServerMode::myStatus, and ArServerMode::setActivityTimeToNow().
Member Data Documentation
ArActionDeceleratingLimiter* ArServerModeStop::myLimiterBackward protected
Referenced by addToConfig(), ArServerModeStop(), and setUseLocationDependentDevices().
ArActionDeceleratingLimiter* ArServerModeStop::myLimiterForward protected
Referenced by addToConfig(), ArServerModeStop(), and setUseLocationDependentDevices().
ArActionDeceleratingLimiter* ArServerModeStop::myLimiterLateralLeft protected
Referenced by addToConfig(), ArServerModeStop(), and setUseLocationDependentDevices().
ArActionDeceleratingLimiter* ArServerModeStop::myLimiterLateralRight protected
Referenced by addToConfig(), ArServerModeStop(), and setUseLocationDependentDevices().
ArFunctor2C<ArServerModeStop, ArServerClient *, ArNetPacket *> ArServerModeStop::myNetStopCB protected
Referenced by ArServerModeStop().
ArActionGroupStop ArServerModeStop::myStopGroup protected
Referenced by activate(), ArServerModeStop(), deactivate(), and getActionGroup().
bool ArServerModeStop::myUseLocationDependentDevices protected
Referenced by ArServerModeStop(), getUseLocationDependentDevices(), and setUseLocationDependentDevices().
The documentation for this class was generated from the following files:
ArServerModeStop.h
ArServerModeStop.cpp