ArNetworking: ArServerModeIdle Class Reference
ArServerModeIdle Class Reference
Mode that the ArServerMode infrastructure will activate if someone tries to switch from one mode to another and there's idle processing to be done...
#include <ArServerModeIdle.h>
Public Member Functions
virtual void activate (void)
The function called when the mode is activated.
void addToConfig (ArConfig *config, const char *section="Teleop settings")
Adds to the config.
ArServerModeIdle (ArServerBase *server, ArRobot *robot)
Constructor.
virtual void deactivate (void)
The function called when the mode is deactivated.
virtual ArActionGroup * getActionGroup (void)
This function should return the action group this mode uses.
ArServerMode * getModeInterrupted (void)
Gets the mode that this mode interrupted (or NULL if it didn't interrupt anything)
bool getUseLocationDependentDevices (void)
Gets whether we're using the range devices that depend on location.
void setModeInterrupted (ArServerMode *modeInterrupted)
Gets the mode that this mode interrupted (or NULL if none)
void setUseLocationDependentDevices (bool useLocationDependentDevices, bool internal=false)
Sets whether we're using the range devices that depend on location.
virtual void userTask (void)
The ArMode's user task, don't need one, subclass must provide if needed.
virtual ~ArServerModeIdle ()
Destructor.
Public Member Functions inherited from ArServerMode
virtual void activationDenied (void)
The function called if the mode is not activated because another mode superceded it.
void addActivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is activated.
void addAsDefaultMode (ArListPos::Pos pos=ArListPos::LAST)
Sets this mode to default (so if a mode deactivates it activates this)
void addDeactivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is deactivated.
bool addModeData (const char *name, const char *description, ArFunctor2< ArServerClient *, ArNetPacket * > *functor, const char *argumentDescription, const char *returnDescription, const char *commandGroup=NULL, const char *dataFlags=NULL)
This basically just notes the commands associated with a mode so that clients can know what can and can't happen based on what mode is active/locked/etc.
void addSingleShotDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for when this class is deactivated.
void addSingleShotPostDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for just after the deactivate happens (when the next mode has activated)
ArServerMode (ArRobot *robot, ArServerBase *server, const char *name)
Constructor.
virtual void checkDefault (void)
Sees if this wants to become the default mode.
virtual void forceUnlock (void)
This will be called if another mode has to break the lock.
ArTime getActivityTime (void)
Gets the time of our last activity.
const char * getExtendedStatus (void) const
Gets a string representing the extended status of the mode we're in.
const char * getMode (void) const
Gets a string representing the mode we're in.
const char * getName (void) const
Gets the name of the mode we're in.
const char * getStatus (void) const
Gets a string representing the status of the mode we're in.
bool hasSetActivityTime (void)
Gets if we've set our activity time.
void internalSetActivityTime (ArTime time)
Internal call to set the activity time (this is dangerous and shouldn't be used)
bool isActive (void) const
Gets if this mode is active or not.
virtual bool isAutoResumeAfterInterrupt ()
Adds data to the list of this mode's commands.
void lockMode (bool willUnlockIfRequested=false)
Locks this mode in until its unlocked (mode must be the active mode)
void remActivateCallback (ArFunctor *functor)
Removes a callback for when this class is activated.
void remDeactivateCallback (ArFunctor *functor)
Removes a callback for when this class is deactivated.
void remSingleShotDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for when this class is deactivated.
void remSingleShotPostDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for just after the deactivate happens (when the next mode has activated)
virtual void requestUnlock (void)
This will be called if another mode wants the lock broken (can ignore)
void setActivityTimeToNow (void)
Sets that we're active right now.
void setMode (const char *str)
This should only be used by careful people and probably not then.
void setStatus (const char *str)
This should only be used by careful people and probably not then.
void unlockMode (void)
Unlocks the mode so other modes can activate.
virtual ~ArServerMode ()
Destructor.
Protected Attributes
ArActionDeceleratingLimiter * myLimiterBackward
ArActionDeceleratingLimiter * myLimiterForward
ArActionDeceleratingLimiter * myLimiterLateralLeft
ArActionDeceleratingLimiter * myLimiterLateralRight
ArServerMode * myModeInterrupted
ArFunctor2C< ArServerModeIdle, ArServerClient *, ArNetPacket * > myNetIdleCB
ArActionGroupStop myStopGroup
bool myUseLocationDependentDevices
Protected Attributes inherited from ArServerMode
ArCallbackList myActivateCallbacks
ArTime myActivityTime
ArMutex myActivityTimeMutex
ArCallbackList myDeactivateCallbacks
std::string myExtendedStatus
bool myHasSetActivityTime
bool myIsActive
std::string myMode
std::string myName
ArRobot * myRobot
ArServerBase * myServer
bool mySetActivityThisCycle
ArCallbackList mySingleShotDeactivateCallbacks
ArCallbackList mySingleShotPostDeactivateCallbacks
std::string myStatus
bool myStatusSetThisCycle
ArLog::LogLevel myVerboseLogLevel
Additional Inherited Members
Static Public Member Functions inherited from ArServerMode
static ArServerMode * getActiveMode (void)
Gets the active mode.
static int getActiveModeActivityTimeSecSince (void)
Gets the seconds since the activity of our active mode.
static const char * getActiveModeExtendedStatusString (void)
Gets the active extended status string.
static const char * getActiveModeModeString (void)
Gets the active mode string.
static bool getActiveModeSetActivityThisCycle (void)
Gets if the active mode set the activity time this cycle or not.
static const char * getActiveModeStatusString (void)
Gets the active status string.
static ArServerModeIdle * getIdleMode (void)
Call that gets our idle mode.
static void getModeBusy (ArServerClient *client, ArNetPacket *packet)
Handles the packet request for the mode busy state.
static void getModeDataList (ArServerClient *client, ArNetPacket *packet)
Gets the list of data for each mode.
static void getModeInfo (ArServerClient *client, ArNetPacket *packet)
Gets the info about which mode is active and such.
static bool isLocked (void)
Gets if the active mode is locked or not.
static bool willUnlockIfRequested (void)
Gets whether we'll unlock if requested or not.
Protected Member Functions inherited from ArServerMode
bool baseActivate (bool canSelfActivateIfLocked=false)
Activates this mode if it can (returns true if it can, false otherwise).
void baseDeactivate (void)
Deactivates this mode.
void checkBroadcastModeInfoPacket (void)
ArServerMode * getLastActiveMode ()
Static Protected Member Functions inherited from ArServerMode
static void buildModeInfoPacket (ArNetPacket *packet)
static std::list< ArServerMode * > * getRequestedActivateModes (void)
static void modeUserTask (void)
Static Protected Attributes inherited from ArServerMode
static ArServerMode * ourActiveMode = NULL
static bool ourActiveModeLocked = false
static bool ourActiveModeSetActivityThisCycle = false
static bool ourActiveModeWillUnlockIfRequested = false
static ArServerMode * ourBroadcastActiveMode = NULL
static bool ourBroadcastActiveModeLocked = false
static bool ourBroadcastActiveModeWillUnlockIfRequested = false
static std::list< ArServerMode * > ourDefaultModes
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeBusyCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeDataListCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeInfoCB
static ArServerModeIdle * ourIdleMode = NULL
static bool ourIdleModeCreated = false
static ArMutex ourIdleModeMutex
static bool ourIsBusy = false
static ArServerMode * ourLastActiveMode = NULL
static std::multimap< std::string, std::string > ourModeDataMap
static ArMutex ourModeDataMapMutex
static std::list< ArServerMode * > ourModes
static ArServerMode * ourNextActiveMode = NULL
static std::list< ArServerMode * > ourRequestedActivateModes
static ArServerBase * ourServerBase = NULL
static bool ourUserTaskAdded = false
static ArGlobalFunctor ourUserTaskCB
Detailed Description
Mode that the ArServerMode infrastructure will activate if someone tries to switch from one mode to another and there's idle processing to be done...
Constructor & Destructor Documentation
ArServerModeIdle::ArServerModeIdle (ArServerBase * server, ArRobot * robot)
Constructor.
References ArActionGroup::addAction(), ArActionDeceleratingLimiter::BACKWARDS, ArRobot::hasLatVel(), ArActionDeceleratingLimiter::LATERAL_LEFT, ArActionDeceleratingLimiter::LATERAL_RIGHT, myLimiterBackward, myLimiterForward, myLimiterLateralLeft, myLimiterLateralRight, ArServerMode::myMode, myModeInterrupted, ArServerMode::myRobot, ArServerMode::myStatus, myStopGroup, and myUseLocationDependentDevices.
ArServerModeIdle::~ArServerModeIdle () virtual
Destructor.
Member Function Documentation
void ArServerModeIdle::activate (void) virtual
The function called when the mode is activated.
Subclasses must implement this, but also call baseActivate().-
Implements ArServerMode.
References ArActionGroup::activateExclusive(), ArServerMode::baseActivate(), ArRobot::clearDirectMotion(), ArServerMode::isActive(), ArLog::log(), myModeInterrupted, ArServerMode::myRobot, myStopGroup, ArLog::Normal, ArServerMode::setActivityTimeToNow(), and ArRobot::stop().
Referenced by ArServerMode::baseActivate().
void ArServerModeIdle::addToConfig (ArConfig * config, const char * section = "Teleop settings")
Adds to the config.
References ArActionDeceleratingLimiter::addToConfig(), myLimiterBackward, myLimiterForward, myLimiterLateralLeft, and myLimiterLateralRight.
Referenced by getActionGroup().
void ArServerModeIdle::deactivate (void) virtual
The function called when the mode is deactivated.
Subclasses must implement this, and also call baseDeactivate().
Implements ArServerMode.
References ArServerMode::baseDeactivate(), ArActionGroup::deactivate(), ArLog::log(), myStopGroup, and ArLog::Normal.
Referenced by userTask().
virtual ArActionGroup* ArServerModeIdle::getActionGroup (void) inline virtual
This function should return the action group this mode uses.
Reimplemented from ArServerMode.
References addToConfig(), getUseLocationDependentDevices(), myStopGroup, and setUseLocationDependentDevices().
ArServerMode * ArServerModeIdle::getModeInterrupted (void)
Gets the mode that this mode interrupted (or NULL if it didn't interrupt anything)
References myModeInterrupted.
bool ArServerModeIdle::getUseLocationDependentDevices (void)
Gets whether we're using the range devices that depend on location.
References myUseLocationDependentDevices.
Referenced by getActionGroup().
void ArServerModeIdle::setModeInterrupted (ArServerMode * modeInterrupted)
Gets the mode that this mode interrupted (or NULL if none)
References myModeInterrupted.
Referenced by ArServerMode::baseActivate().
void ArServerModeIdle::setUseLocationDependentDevices (bool useLocationDependentDevices, bool internal = false)
Sets whether we're using the range devices that depend on location.
References ArRobot::lock(), myLimiterBackward, myLimiterForward, myLimiterLateralLeft, myLimiterLateralRight, ArServerMode::myRobot, myUseLocationDependentDevices, ArActionDeceleratingLimiter::setUseLocationDependentDevices(), and ArRobot::unlock().
Referenced by getActionGroup().
void ArServerModeIdle::userTask (void) virtual
The ArMode's user task, don't need one, subclass must provide if needed.
MPL 2014_04_17 centralizing all the places stopped is calculated
Reimplemented from ArServerMode.
References deactivate(), ArServerBase::idleProcessingPending(), ArRobot::isStopped(), ArServerMode::myRobot, ArServerMode::myServer, ArServerMode::myStatus, and ArServerMode::setActivityTimeToNow().
Member Data Documentation
ArActionDeceleratingLimiter* ArServerModeIdle::myLimiterBackward protected
Referenced by addToConfig(), ArServerModeIdle(), and setUseLocationDependentDevices().
ArActionDeceleratingLimiter* ArServerModeIdle::myLimiterForward protected
Referenced by addToConfig(), ArServerModeIdle(), and setUseLocationDependentDevices().
ArActionDeceleratingLimiter* ArServerModeIdle::myLimiterLateralLeft protected
Referenced by addToConfig(), ArServerModeIdle(), and setUseLocationDependentDevices().
ArActionDeceleratingLimiter* ArServerModeIdle::myLimiterLateralRight protected
Referenced by addToConfig(), ArServerModeIdle(), and setUseLocationDependentDevices().
ArServerMode* ArServerModeIdle::myModeInterrupted protected
Referenced by activate(), ArServerModeIdle(), getModeInterrupted(), and setModeInterrupted().
ArFunctor2C<ArServerModeIdle, ArServerClient *, ArNetPacket *> ArServerModeIdle::myNetIdleCB protected
ArActionGroupStop ArServerModeIdle::myStopGroup protected
Referenced by activate(), ArServerModeIdle(), deactivate(), and getActionGroup().
bool ArServerModeIdle::myUseLocationDependentDevices protected
Referenced by ArServerModeIdle(), getUseLocationDependentDevices(), and setUseLocationDependentDevices().
The documentation for this class was generated from the following files:
ArServerModeIdle.h
ArServerModeIdle.cpp