ArNetworking: ArServerHandlerConfig Class Reference
ArServerHandlerConfig Class Reference
Class for sending and receiving ArConfig data via ArNetworking.
#include <ArServerHandlerConfig.h>
Public Member Functions
void addConfigUpdatedCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be called when the config is updated.
void addPostWriteCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be called after writing to disk.
void addPreWriteCallback (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a callback to be called before writing to disk.
void addRestartIOCB (ArFunctor *functor, int position=50)
Adds a callback for when the IO is changed.
ArServerHandlerConfig (ArServerBase *server, ArConfig *config, const char *defaultFile=NULL, const char *defaultFileBaseDirectory=NULL, bool allowFactory=true, const char *robotName=NULL, bool preventChanges=false, const char *preventChangesString=NULL)
Constructor.
bool configUpdated (ArServerClient *client=NULL)
Notifies the clients that the config was updated.
void createEmptyConfigDefaults (void)
Creates an empty default config...
bool getAllowFactory (void)
Changes if factory is allowed...
void getConfig (ArServerClient *client, ArNetPacket *packet)
Handles the (deprecated) "getConfig" request.
void getConfigBySections (ArServerClient *client, ArNetPacket *packet)
Handles the "getConfigBySections" request.
void getConfigBySectionsV2 (ArServerClient *client, ArNetPacket *packet)
Handles the "getConfigBySectionsV2" request.
void getConfigBySectionsV3 (ArServerClient *client, ArNetPacket *packet)
Handles the "getConfigBySectionsV3" request.
void getConfigBySectionsV4 (ArServerClient *client, ArNetPacket *packet)
Handles the "getConfigBySectionsV4" request.
void getConfigDefaults (ArServerClient *client, ArNetPacket *packet)
Handles the "getConfigDefaults" request.
void getConfigSectionFlags (ArServerClient *client, ArNetPacket *packet)
Handles the "getConfigSectionFlags" request.
void getLastEditablePriority (ArServerClient *client, ArNetPacket *packet)
Handles the "getLastEditablePriority" request.
ArFunctor * getRestartHardwareCB (void)
Gets the callback for when a RESTART_ROBOT config param is changed.
ArFunctor * getRestartSoftwareCB (void)
Gets the callback for when a RESTART_SERVER config param is changed.
bool loadDefaultsFromFile (void)
loads the whole of a default file (for internal use)
bool loadDefaultsFromPacket (ArNetPacket *packet)
Parses a line of the default config (for internal use)
int lockConfig (void)
Locks the config so we don't do anything with it.
void reloadConfig (ArServerClient *client, ArNetPacket *packet)
Handles the "reloadConfig" request.
void remConfigUpdatedCallback (ArFunctor *functor)
Removes a callback to be called when the config is updated.
void remPostWriteCallback (ArFunctor *functor)
Removes a callback to be called after writing to disk.
void remPreWriteCallback (ArFunctor *functor)
Removes a callback to be called before writing to disk.
void remRestartIOCB (ArFunctor *functor)
Adds a callback for when the IO is changed.
void restartHardware (const char *reason)
Restarts the hardware manually (mostly for because of a config change)
void restartIO (const char *reason)
Restarts the IO manually (mostly for because of a config change)
void restartSoftware (const char *reason)
Restarts the software manually (mostly for because of a config change)
void setAllowFactory (bool allowFactory)
Changes if factory is allowed...
void setConfig (ArServerClient *client, ArNetPacket *packet)
Handles the "setConfig" request.
void setConfigBySections (ArServerClient *client, ArNetPacket *packet)
void setConfigBySectionsV2 (ArServerClient *client, ArNetPacket *packet)
void setConfigParam (ArServerClient *client, ArNetPacket *packet)
Handles the "setConfigParam" request.
void setPreventChanges (bool preventChanges=false, const char *preventChangesString=NULL)
Changes the variables that prevent changes.
void setRestartHardwareCB (ArFunctor *restartRobotCB)
Sets a callback for when a RESTART_ROBOT config param is changed.
void setRestartSoftwareCB (ArFunctor *restartServerCB)
Sets a callback for when a RESTART_SERVER config param is changed.
int tryLockConfig (void)
Tries to lock the config so we don't do anything with it.
int unlockConfig (void)
Unlocks the config so we can use it again.
bool writeConfig (void)
Writes the config out.
virtual ~ArServerHandlerConfig ()
Destructor.
Protected Member Functions
void addDefaultServerCommands (void)
Adds the default config callbacks;.
ArPriority::Priority convertToPriority (int priorityVal, ArPriority::Priority defaultPriority)
void createDefaultConfig (const char *defaultFileBaseDir)
just creates the default config... (internal, don't use)
void doGetConfigBySections (ArServerClient *client, ArNetPacket *packet, int version)
ArPriority::Priority findLastEditablePriority ()
Determines the last editable priority based on the input flags.
void handleGetConfig (ArServerClient *client, ArNetPacket *packet, bool isMultiplePackets, ArPriority::Priority lastPriority, bool isSendIneditablePriorities, int version)
Helper method for the get config callbacks (e.g. getConfigBySections, getConfig, ...).
bool handleGetConfigSection (ArNetPacket &sending, ArServerClient *client, ArNetPacket *packet, bool isMultiplePackets, ArPriority::Priority lastPriority, bool isSendIneditablePriorities, int version, ArConfigSection *section, int startIndex, int paramCount, int sectionIndex, std::set< std::string > &sentParams)
Helper method for the get config callbacks (e.g. getConfigBySections, getConfig, ...).
bool internalSetConfig (ArServerClient *client, ArNetPacket *packet, int version, bool isMultiplePackets=false, bool isSingleParam=false)
Internal method that handles a setConfig packet for myConfig or myDefaults.
Protected Attributes
bool myAddedDefaultServerCommands
ArConfig * myConfig
ArMutex myConfigMutex
std::list< ArFunctor * > myConfigUpdatedCallbacks
ArConfig * myDefault
ArMutex myDefaultConfigMutex
std::string myDefaultFile
std::string myDefaultFileBaseDir
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > myGetConfigBySectionsCB
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > myGetConfigBySectionsV2CB
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > myGetConfigBySectionsV3CB
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > myGetConfigBySectionsV4CB
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > myGetConfigCB
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > myGetConfigDefaultsCB
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > myGetConfigSectionFlagsCB
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > myGetLastEditablePriorityCB
std::string myLogPrefix
bool myPermissionAllowFactory
std::list< ArFunctor * > myPostWriteCallbacks
bool myPreventChanges
std::string myPreventChangesString
std::list< ArFunctor * > myPreWriteCallbacks
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > myReloadConfigCB
ArFunctor * myRestartHardwareCB
bool myRestartHardwareCBSet
ArCallbackList myRestartIOCBList
ArFunctor * myRestartSoftwareCB
bool myRestartSoftwareCBSet
std::string myRobotName
ArServerBase * myServer
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > mySetConfigBySectionsCB
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > mySetConfigBySectionsV2CB
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > mySetConfigCB
ArFunctor2C< ArServerHandlerConfig, ArServerClient *, ArNetPacket * > mySetConfigParamCB
Detailed Description
Class for sending and receiving ArConfig data via ArNetworking.
ArServerHandlerConfig defines the network packet handlers used to transmit ArConfig objects to a client, and to modify them based on information received from the client. Since the packet structure for the ArConfig is rather complex, this class is best used in conjunction with the ArClientHandlerConfig.
This class handles the following requests:
getConfigBySections/getConfigBySectionsV2: Replies with multiple packets, one for each ArConfig section plus an empty packet that terminates the reply. Each packet contains the following header information:
Section Indicator: Always set to 'S' (byte)
Section Name: (string)
Section Comment: (string)
Section Category Name: (string) Only for getConfigBySectionsV2
For each parameter in the section, the packet then contains a a Parameter Indicator (always set to 'P' (byte)) followed by a complete description of the parameter (display hints are included). See ArClientArgUtils for more information.
getConfig: This request has been superceded by getConfigBySections. (It replies with a single packet containing all of the ArConfig sections as described above. If the ArConfig is large, then it may not be sent successfully. In addition, it contains no parameter display hints.)
setConfig: Parses the received packet and updates the robot's ArConfig (and saves it to the file). For each modified section, the received packet is expected to contain:
Section Indicator: Always set to "Section" (string)
Section Name: (string)
Followed by a brief "text" description of each modified parameter. This is the parameter name (string) followed by the parameter value formatted as text (string). See ArClientArgUtils for more information.
A reply packet containing a string is sent to the client. If the string is empty, then the config was successfully updated. Otherwise, the string contains the name of the first parameter that caused an error during the update handling.
reloadConfig: Reloads the ArConfig from the text file.
configUpdated: An empty packet is broadcast to all interested clients after setConfig or reloadConfig has been completed. The clients may then request the modified ArConfig data with getConfigBySections (or getConfig).
getConfigDefaults: If a "default" configuration file is available, then this command can be used to send the preferred default values to the client. The received packet should contain a single string, which is the name of the section to be retrieved, or an empty string to indicate all sections.
For each requested section, the reply packet contains:
Section Indicator: Always set to "Section" (string)
Section Name: (string)
Followed by a brief "text" description of each default parameter value. This is the parameter name (string) followed by the parameter value formatted as text (string). See ArClientArgUtils for more information.
If you are using this class with the default file option you'll want to make it AFTER you're done adding things to the config, ie last, so that the default code can work correctly (it needs to know about all the info).
Examples:
popupExample.cpp, and serverDemo.cpp.
Constructor & Destructor Documentation
ArServerHandlerConfig::ArServerHandlerConfig (ArServerBase * server, ArConfig * config, const char * defaultFile = NULL, const char * defaultFileBaseDirectory = NULL, bool allowFactory = true, const char * robotName = NULL, bool preventChanges = false, const char * preventChangesString = NULL)
Constructor.
Parameters
server the ArServerBase * used to send and receive network packets; must be non-NULL
config the ArConfig * that is maintained by this server handler
defaultFile the char * name of the file that contains the default values for the ArConfig; if NULL, then getConfigDefaults will not be supported
defaultFileBaseDirectory the char * name of the directory that contains the default file
server the server to add data to
config the config to serve up
defaultFile if this is given the config will try to copy the config given and then load the default file into that config and then serve data so clients can get those defaults
defaultFileBaseDirectory base directory for the default file
References ArServerBase::addData(), loadDefaultsFromFile(), myAddedDefaultServerCommands, myConfigMutex, myDefaultConfigMutex, myDefaultFile, myDefaultFileBaseDir, myGetConfigBySectionsCB, myGetConfigBySectionsV2CB, myGetConfigBySectionsV3CB, myGetConfigBySectionsV4CB, myGetConfigCB, myGetConfigSectionFlagsCB, myGetLastEditablePriorityCB, myLogPrefix, myPermissionAllowFactory, myPreventChanges, myPreventChangesString, myReloadConfigCB, myRobotName, myServer, mySetConfigBySectionsCB, mySetConfigBySectionsV2CB, mySetConfigCB, mySetConfigParamCB, and ArMutex::setLogName().
ArServerHandlerConfig::~ArServerHandlerConfig () virtual
Destructor.
References myDefault.
Member Function Documentation
void ArServerHandlerConfig::addConfigUpdatedCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback to be called when the config is updated.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myConfigUpdatedCallbacks, myLogPrefix, and ArLog::Terse.
void ArServerHandlerConfig::addDefaultServerCommands (void) protected
Adds the default config callbacks;.
References ArServerBase::addData(), handleGetConfig(), myAddedDefaultServerCommands, myGetConfigDefaultsCB, and myServer.
Referenced by createEmptyConfigDefaults(), getAllowFactory(), loadDefaultsFromFile(), and loadDefaultsFromPacket().
void ArServerHandlerConfig::addPostWriteCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback to be called after writing to disk.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myLogPrefix, myPostWriteCallbacks, and ArLog::Terse.
void ArServerHandlerConfig::addPreWriteCallback (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a callback to be called before writing to disk.
References ArListPos::FIRST, ArListPos::LAST, ArLog::log(), myLogPrefix, myPreWriteCallbacks, and ArLog::Terse.
void ArServerHandlerConfig::addRestartIOCB (ArFunctor * functor, int position = 50) inline
Adds a callback for when the IO is changed.
References ArGenericCallbackList< ArFunctor * >::addCallback(), and myRestartIOCBList.
bool ArServerHandlerConfig::configUpdated (ArServerClient * client = NULL)
Notifies the clients that the config was updated.
References ArServerBase::broadcastPacketTcpWithExclusion(), myConfigUpdatedCallbacks, and myServer.
Referenced by internalSetConfig(), reloadConfig(), and unlockConfig().
ArPriority::Priority ArServerHandlerConfig::convertToPriority (int priorityVal, ArPriority::Priority defaultPriority) protected
References ArPriority::LAST_PRIORITY.
Referenced by doGetConfigBySections(), findLastEditablePriority(), and getAllowFactory().
void ArServerHandlerConfig::createDefaultConfig (const char * defaultFileBaseDir) protected
just creates the default config... (internal, don't use)
doesn't delete the old one, do that if you're going to call this yourself and make sure you lock around all that (okay, it deletes it now, but the stuff that calls it should still take care of it)
References ArConfig::addParam(), ArConfigArg::copyAndDetach(), ArConfig::getSections(), myConfig, and myDefault.
Referenced by getAllowFactory(), loadDefaultsFromFile(), and loadDefaultsFromPacket().
void ArServerHandlerConfig::createEmptyConfigDefaults (void)
Creates an empty default config...
References addDefaultServerCommands(), ArServerBase::broadcastPacketTcp(), lockConfig(), myDefault, myServer, and unlockConfig().
Referenced by unlockConfig().
void ArServerHandlerConfig::doGetConfigBySections (ArServerClient * client, ArNetPacket * packet, int version) protected
References ArBasePacket::bufToByte(), convertToPriority(), ArPriority::DETAILED, findLastEditablePriority(), ArBasePacket::getDataLength(), ArBasePacket::getDataReadLength(), ArPriority::getPriorityName(), handleGetConfig(), ArPriority::LAST_PRIORITY, ArLog::log(), myLogPrefix, ArLog::Normal, and ArLog::Verbose.
Referenced by getAllowFactory(), getConfigBySections(), getConfigBySectionsV2(), getConfigBySectionsV3(), and getConfigBySectionsV4().
ArPriority::Priority ArServerHandlerConfig::findLastEditablePriority () protected
Determines the last editable priority based on the input flags.
References ArPriority::CALIBRATION, and convertToPriority().
Referenced by doGetConfigBySections(), getAllowFactory(), and handleGetConfigSection().
bool ArServerHandlerConfig::getAllowFactory (void) inline
Changes if factory is allowed...
this is internal, only for when that decision is deferred
References addDefaultServerCommands(), convertToPriority(), createDefaultConfig(), doGetConfigBySections(), findLastEditablePriority(), handleGetConfig(), handleGetConfigSection(), internalSetConfig(), and myPermissionAllowFactory.
void ArServerHandlerConfig::getConfig (ArServerClient * client, ArNetPacket * packet)
Handles the (deprecated) "getConfig" request.
References ArPriority::DETAILED, and handleGetConfig().
void ArServerHandlerConfig::getConfigBySections (ArServerClient * client, ArNetPacket * packet)
Handles the "getConfigBySections" request.
References doGetConfigBySections().
void ArServerHandlerConfig::getConfigBySectionsV2 (ArServerClient * client, ArNetPacket * packet)
Handles the "getConfigBySectionsV2" request.
References doGetConfigBySections().
void ArServerHandlerConfig::getConfigBySectionsV3 (ArServerClient * client, ArNetPacket * packet)
Handles the "getConfigBySectionsV3" request.
References doGetConfigBySections().
void ArServerHandlerConfig::getConfigBySectionsV4 (ArServerClient * client, ArNetPacket * packet)
Handles the "getConfigBySectionsV4" request.
References doGetConfigBySections().
void ArServerHandlerConfig::getConfigDefaults (ArServerClient * client, ArNetPacket * packet)
Handles the "getConfigDefaults" request.
References ArClientArg::argTextToBuf(), ArBasePacket::bufToStr(), ArBasePacket::getDataLength(), ArBasePacket::getDataReadLength(), ArConfigArg::getName(), ArConfigSection::getName(), ArConfig::getSections(), ArClientArg::isSendableParamType(), ArMutex::lock(), ArLog::log(), myConfigMutex, myDefault, myLogPrefix, ArLog::Normal, ArServerClient::sendPacketTcp(), ArUtil::strcasecmp(), ArBasePacket::strToBuf(), and ArMutex::unlock().
void ArServerHandlerConfig::getConfigSectionFlags (ArServerClient * client, ArNetPacket * packet)
Handles the "getConfigSectionFlags" request.
References getLastEditablePriority(), ArConfigSection::getName(), ArConfig::getSections(), ArLog::log(), myConfig, myLogPrefix, ArLog::Normal, and ArServerClient::sendPacketTcp().
void ArServerHandlerConfig::getLastEditablePriority (ArServerClient * client, ArNetPacket * packet)
Handles the "getLastEditablePriority" request.
References ArBasePacket::byteToBuf(), ArPriority::EXPERT, ArPriority::FACTORY, ArPriority::getPriorityName(), ArLog::log(), myLogPrefix, myPermissionAllowFactory, ArServerClient::sendPacketTcp(), and ArLog::Verbose.
Referenced by getConfigSectionFlags().
ArFunctor * ArServerHandlerConfig::getRestartHardwareCB (void)
Gets the callback for when a RESTART_ROBOT config param is changed.
References myRestartHardwareCB.
Referenced by remRestartIOCB().
ArFunctor * ArServerHandlerConfig::getRestartSoftwareCB (void)
Gets the callback for when a RESTART_SERVER config param is changed.
References myRestartSoftwareCB.
Referenced by remRestartIOCB().
void ArServerHandlerConfig::handleGetConfig (ArServerClient * client, ArNetPacket * packet, bool isMultiplePackets, ArPriority::Priority lastPriority, bool isSendIneditablePriorities, int version) protected
Helper method for the get config callbacks (e.g. getConfigBySections, getConfig, ...).
Parameters
client the ArServerClient * to which to send the config
packet the ArNetPacket * which accompanied the client's request
isMultiplePackets a bool set to true if the server should send a packet for each config section followed by the empty packet; false if the server should send the entire config in one packet (i.e. the old style)
lastPriority the last ArPriority::Priority that should be sent to the client (this is the greatest numerical value and the least semantic priority).
References ArNetPacket::empty(), ArConfig::getSections(), handleGetConfigSection(), ArBasePacket::isValid(), ArLog::log(), myConfig, myLogPrefix, ArLog::Normal, ArServerClient::sendPacketTcp(), and ArLog::Terse.
Referenced by addDefaultServerCommands(), doGetConfigBySections(), getAllowFactory(), and getConfig().
bool ArServerHandlerConfig::handleGetConfigSection (ArNetPacket & sending, ArServerClient * client, ArNetPacket * packet, bool isMultiplePackets, ArPriority::Priority lastPriority, bool isSendIneditablePriorities, int version, ArConfigSection * section, int startIndex, int paramCount, int sectionIndex, std::set< std::string > & sentParams) protected
Helper method for the get config callbacks (e.g. getConfigBySections, getConfig, ...).
References ArBasePacket::byteToBuf(), ArClientArg::createPacket(), ArConfigArg::DESCRIPTION_HOLDER, ArNetPacket::empty(), findLastEditablePriority(), ArConfigSection::getCategoryName(), ArConfigSection::getComment(), ArConfigArg::getConfigPriority(), ArConfigSection::getName(), ArConfigArg::getName(), ArPriority::getPriorityName(), ArConfigArg::getType(), IFDEBUG, ArClientArg::isSendableParamType(), ArBasePacket::isValid(), ArLog::log(), myLogPrefix, ArLog::Normal, ArServerClient::sendPacketTcp(), ArConfigArg::SEPARATOR, ArConfigArg::STRING_HOLDER, ArBasePacket::strToBuf(), ArLog::Terse, ArBasePacket::uByte2ToBuf(), and ArLog::Verbose.
Referenced by getAllowFactory(), and handleGetConfig().
bool ArServerHandlerConfig::internalSetConfig (ArServerClient * client, ArNetPacket * packet, int version, bool isMultiplePackets = false, bool isSingleParam = false) protected
Internal method that handles a setConfig packet for myConfig or myDefaults.
Parameters
client If client is NULL it means use the default config
packet request packet containing config options
References ArArgumentBuilder::addPlain(), ArServerBase::broadcastPacketTcp(), ArBasePacket::bufToStr(), ArBasePacket::byteToBuf(), ArConfig::callProcessFileCallBacks(), configUpdated(), ArArgumentBuilder::getArg(), ArArgumentBuilder::getArgc(), ArBasePacket::getDataLength(), ArBasePacket::getDataReadLength(), ArServerClient::getIPString(), ArConfig::getRestartLevelNeeded(), IFDEBUG, ArConfigArg::LIST_BEGIN_TAG, ArConfigArg::LIST_END_TAG, lockConfig(), ArLog::log(), myConfig, myDefault, myLogPrefix, myPermissionAllowFactory, myServer, ArLog::Normal, ArConfig::parseArgument(), ArConfig::parseSection(), reloadConfig(), ArConfig::resetRestartLevelNeeded(), restartHardware(), restartIO(), restartSoftware(), ArServerClient::sendPacketTcp(), ArArgumentBuilder::setExtraString(), ArConfig::setPermissions(), ArUtil::strcasecmp(), ArBasePacket::strToBuf(), unlockConfig(), ArLog::Verbose, and writeConfig().
Referenced by getAllowFactory(), loadDefaultsFromPacket(), setConfig(), setConfigBySections(), setConfigBySectionsV2(), and setConfigParam().
bool ArServerHandlerConfig::loadDefaultsFromFile (void)
loads the whole of a default file (for internal use)
References addDefaultServerCommands(), ArServerBase::broadcastPacketTcp(), ArConfig::clearAllValueSet(), createDefaultConfig(), lockConfig(), ArLog::log(), myDefault, myDefaultFile, myDefaultFileBaseDir, myLogPrefix, myServer, ArLog::Normal, ArConfig::parseFile(), ArConfig::removeAllUnsetValues(), ArConfig::setPermissions(), and unlockConfig().
Referenced by ArServerHandlerConfig(), and unlockConfig().
bool ArServerHandlerConfig::loadDefaultsFromPacket (ArNetPacket * packet)
Parses a line of the default config (for internal use)
References addDefaultServerCommands(), ArServerBase::broadcastPacketTcp(), ArConfig::clearAllValueSet(), createDefaultConfig(), internalSetConfig(), lockConfig(), ArLog::log(), myDefault, myLogPrefix, myServer, ArLog::Normal, ArConfig::removeAllUnsetValues(), and unlockConfig().
Referenced by unlockConfig().
int ArServerHandlerConfig::lockConfig (void) inline
Locks the config so we don't do anything with it.
References ArMutex::lock(), and myConfigMutex.
Referenced by createEmptyConfigDefaults(), internalSetConfig(), loadDefaultsFromFile(), loadDefaultsFromPacket(), and reloadConfig().
void ArServerHandlerConfig::reloadConfig (ArServerClient * client, ArNetPacket * packet)
Handles the "reloadConfig" request.
References configUpdated(), ArConfig::getFileName(), ArServerClient::getIPString(), lockConfig(), ArLog::log(), myConfig, myLogPrefix, myPermissionAllowFactory, ArLog::Normal, ArConfig::parseFile(), ArConfig::setPermissions(), and unlockConfig().
Referenced by internalSetConfig().
void ArServerHandlerConfig::remConfigUpdatedCallback (ArFunctor * functor)
Removes a callback to be called when the config is updated.
References myConfigUpdatedCallbacks.
void ArServerHandlerConfig::remPostWriteCallback (ArFunctor * functor)
Removes a callback to be called after writing to disk.
References myPostWriteCallbacks.
void ArServerHandlerConfig::remPreWriteCallback (ArFunctor * functor)
Removes a callback to be called before writing to disk.
References myPreWriteCallbacks.
void ArServerHandlerConfig::remRestartIOCB (ArFunctor * functor) inline
Adds a callback for when the IO is changed.
References getRestartHardwareCB(), getRestartSoftwareCB(), myRestartIOCBList, ArGenericCallbackList< ArFunctor * >::remCallback(), setRestartHardwareCB(), and setRestartSoftwareCB().
void ArServerHandlerConfig::restartHardware (const char * reason)
Restarts the hardware manually (mostly for because of a config change)
Clients are notified via configCausingRestart packet containing value 2, then the restart-hardware callback set by setRestartHardwareCB(), if any, is invoked 1 second after the server has finished sending pending packets.
References ArServerBase::broadcastPacketTcp(), ArBasePacket::byteToBuf(), Aria::exit(), ArFunctor::invoke(), ArLog::log(), myLogPrefix, myRestartHardwareCB, myRestartHardwareCBSet, myServer, ArLog::Normal, and ArServerBase::sleepAfterSend().
Referenced by internalSetConfig().
void ArServerHandlerConfig::restartIO (const char * reason)
Restarts the IO manually (mostly for because of a config change)
The callbackes added via addRestartIOCB(), if any, are invoked.
References ArCallbackList::invoke(), ArLog::log(), myLogPrefix, myRestartIOCBList, and ArLog::Normal.
Referenced by internalSetConfig().
void ArServerHandlerConfig::restartSoftware (const char * reason)
Restarts the software manually (mostly for because of a config change)
Clients are notified via configCausingRestart packet containing value 1, then the restart-software callback set by setRestartSoftwareCB(), if any, is invoked 1 second after the server has finished sending pending packets.
References ArServerBase::broadcastPacketTcp(), ArBasePacket::byteToBuf(), Aria::exit(), ArFunctor::invoke(), ArLog::log(), myLogPrefix, myRestartSoftwareCB, myRestartSoftwareCBSet, myServer, ArLog::Normal, and ArServerBase::sleepAfterSend().
Referenced by internalSetConfig().
void ArServerHandlerConfig::setAllowFactory (bool allowFactory) inline
Changes if factory is allowed...
this is internal, only for when that decision is deferred
References myPermissionAllowFactory.
void ArServerHandlerConfig::setConfig (ArServerClient * client, ArNetPacket * packet)
Handles the "setConfig" request.
References ArServerBase::findCommandFromName(), internalSetConfig(), ArMutex::lock(), ArLog::log(), myConfigMutex, myPreventChanges, myPreventChangesString, myServer, ArLog::Normal, ArServerClient::sendPacketTcp(), ArNetPacket::setCommand(), ArBasePacket::strToBuf(), and ArMutex::unlock().
void ArServerHandlerConfig::setConfigBySections (ArServerClient * client, ArNetPacket * packet)
References ArServerBase::findCommandFromName(), internalSetConfig(), ArMutex::lock(), ArLog::log(), myConfigMutex, myPreventChanges, myPreventChangesString, myServer, ArLog::Normal, ArServerClient::sendPacketTcp(), ArNetPacket::setCommand(), ArBasePacket::strToBuf(), and ArMutex::unlock().
void ArServerHandlerConfig::setConfigBySectionsV2 (ArServerClient * client, ArNetPacket * packet)
References ArServerBase::findCommandFromName(), internalSetConfig(), ArMutex::lock(), ArLog::log(), myConfigMutex, myPreventChanges, myPreventChangesString, myServer, ArLog::Normal, ArServerClient::sendPacketTcp(), ArNetPacket::setCommand(), ArBasePacket::strToBuf(), and ArMutex::unlock().
void ArServerHandlerConfig::setConfigParam (ArServerClient * client, ArNetPacket * packet)
Handles the "setConfigParam" request.
References ArServerBase::findCommandFromName(), internalSetConfig(), ArMutex::lock(), ArLog::log(), myConfigMutex, myPreventChanges, myPreventChangesString, myServer, ArLog::Normal, ArServerClient::sendPacketTcp(), ArNetPacket::setCommand(), ArBasePacket::strToBuf(), and ArMutex::unlock().
void ArServerHandlerConfig::setPreventChanges (bool preventChanges = false, const char * preventChangesString = NULL)
Changes the variables that prevent changes.
References ArMutex::lock(), myConfigMutex, myPreventChanges, myPreventChangesString, and ArMutex::unlock().
Referenced by unlockConfig().
void ArServerHandlerConfig::setRestartHardwareCB (ArFunctor * restartRobotCB)
Sets a callback for when a RESTART_ROBOT config param is changed.
References myRestartHardwareCB, and myRestartHardwareCBSet.
Referenced by remRestartIOCB().
void ArServerHandlerConfig::setRestartSoftwareCB (ArFunctor * restartServerCB)
Sets a callback for when a RESTART_SERVER config param is changed.
References myRestartSoftwareCB, and myRestartSoftwareCBSet.
Referenced by remRestartIOCB().
int ArServerHandlerConfig::tryLockConfig (void) inline
Tries to lock the config so we don't do anything with it.
References myConfigMutex, and ArMutex::tryLock().
int ArServerHandlerConfig::unlockConfig (void) inline
Unlocks the config so we can use it again.
References configUpdated(), createEmptyConfigDefaults(), loadDefaultsFromFile(), loadDefaultsFromPacket(), myConfigMutex, setPreventChanges(), ArMutex::unlock(), and writeConfig().
Referenced by createEmptyConfigDefaults(), internalSetConfig(), loadDefaultsFromFile(), loadDefaultsFromPacket(), and reloadConfig().
bool ArServerHandlerConfig::writeConfig (void)
Writes the config out.
References ArConfig::getFileName(), ArConfig::getSaveUnknown(), IFDEBUG, ArLog::log(), myConfig, myLogPrefix, myPostWriteCallbacks, myPreWriteCallbacks, ArLog::Normal, ArConfig::setSaveUnknown(), and ArConfig::writeFile().
Referenced by internalSetConfig(), and unlockConfig().
Member Data Documentation
bool ArServerHandlerConfig::myAddedDefaultServerCommands protected
Referenced by addDefaultServerCommands(), and ArServerHandlerConfig().
ArConfig* ArServerHandlerConfig::myConfig protected
Referenced by createDefaultConfig(), getConfigSectionFlags(), handleGetConfig(), internalSetConfig(), reloadConfig(), and writeConfig().
ArMutex ArServerHandlerConfig::myConfigMutex protected
Referenced by ArServerHandlerConfig(), getConfigDefaults(), lockConfig(), setConfig(), setConfigBySections(), setConfigBySectionsV2(), setConfigParam(), setPreventChanges(), tryLockConfig(), and unlockConfig().
std::list<ArFunctor *> ArServerHandlerConfig::myConfigUpdatedCallbacks protected
Referenced by addConfigUpdatedCallback(), configUpdated(), and remConfigUpdatedCallback().
ArConfig* ArServerHandlerConfig::myDefault protected
Referenced by createDefaultConfig(), createEmptyConfigDefaults(), getConfigDefaults(), internalSetConfig(), loadDefaultsFromFile(), loadDefaultsFromPacket(), and ~ArServerHandlerConfig().
ArMutex ArServerHandlerConfig::myDefaultConfigMutex protected
Referenced by ArServerHandlerConfig().
std::string ArServerHandlerConfig::myDefaultFile protected
Referenced by ArServerHandlerConfig(), and loadDefaultsFromFile().
std::string ArServerHandlerConfig::myDefaultFileBaseDir protected
Referenced by ArServerHandlerConfig(), and loadDefaultsFromFile().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::myGetConfigBySectionsCB protected
Referenced by ArServerHandlerConfig().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::myGetConfigBySectionsV2CB protected
Referenced by ArServerHandlerConfig().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::myGetConfigBySectionsV3CB protected
Referenced by ArServerHandlerConfig().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::myGetConfigBySectionsV4CB protected
Referenced by ArServerHandlerConfig().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::myGetConfigCB protected
Referenced by ArServerHandlerConfig().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::myGetConfigDefaultsCB protected
Referenced by addDefaultServerCommands().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::myGetConfigSectionFlagsCB protected
Referenced by ArServerHandlerConfig().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::myGetLastEditablePriorityCB protected
Referenced by ArServerHandlerConfig().
std::string ArServerHandlerConfig::myLogPrefix protected
Referenced by addConfigUpdatedCallback(), addPostWriteCallback(), addPreWriteCallback(), ArServerHandlerConfig(), doGetConfigBySections(), getConfigDefaults(), getConfigSectionFlags(), getLastEditablePriority(), handleGetConfig(), handleGetConfigSection(), internalSetConfig(), loadDefaultsFromFile(), loadDefaultsFromPacket(), reloadConfig(), restartHardware(), restartIO(), restartSoftware(), and writeConfig().
bool ArServerHandlerConfig::myPermissionAllowFactory protected
Referenced by ArServerHandlerConfig(), getAllowFactory(), getLastEditablePriority(), internalSetConfig(), reloadConfig(), and setAllowFactory().
std::list<ArFunctor *> ArServerHandlerConfig::myPostWriteCallbacks protected
Referenced by addPostWriteCallback(), remPostWriteCallback(), and writeConfig().
bool ArServerHandlerConfig::myPreventChanges protected
Referenced by ArServerHandlerConfig(), setConfig(), setConfigBySections(), setConfigBySectionsV2(), setConfigParam(), and setPreventChanges().
std::string ArServerHandlerConfig::myPreventChangesString protected
Referenced by ArServerHandlerConfig(), setConfig(), setConfigBySections(), setConfigBySectionsV2(), setConfigParam(), and setPreventChanges().
std::list<ArFunctor *> ArServerHandlerConfig::myPreWriteCallbacks protected
Referenced by addPreWriteCallback(), remPreWriteCallback(), and writeConfig().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::myReloadConfigCB protected
Referenced by ArServerHandlerConfig().
ArFunctor* ArServerHandlerConfig::myRestartHardwareCB protected
Referenced by getRestartHardwareCB(), restartHardware(), and setRestartHardwareCB().
bool ArServerHandlerConfig::myRestartHardwareCBSet protected
Referenced by restartHardware(), and setRestartHardwareCB().
ArCallbackList ArServerHandlerConfig::myRestartIOCBList protected
Referenced by addRestartIOCB(), remRestartIOCB(), and restartIO().
ArFunctor* ArServerHandlerConfig::myRestartSoftwareCB protected
Referenced by getRestartSoftwareCB(), restartSoftware(), and setRestartSoftwareCB().
bool ArServerHandlerConfig::myRestartSoftwareCBSet protected
Referenced by restartSoftware(), and setRestartSoftwareCB().
std::string ArServerHandlerConfig::myRobotName protected
Referenced by ArServerHandlerConfig().
ArServerBase* ArServerHandlerConfig::myServer protected
Referenced by addDefaultServerCommands(), ArServerHandlerConfig(), configUpdated(), createEmptyConfigDefaults(), internalSetConfig(), loadDefaultsFromFile(), loadDefaultsFromPacket(), restartHardware(), restartSoftware(), setConfig(), setConfigBySections(), setConfigBySectionsV2(), and setConfigParam().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::mySetConfigBySectionsCB protected
Referenced by ArServerHandlerConfig().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::mySetConfigBySectionsV2CB protected
Referenced by ArServerHandlerConfig().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::mySetConfigCB protected
Referenced by ArServerHandlerConfig().
ArFunctor2C<ArServerHandlerConfig, ArServerClient*, ArNetPacket *> ArServerHandlerConfig::mySetConfigParamCB protected
Referenced by ArServerHandlerConfig().
The documentation for this class was generated from the following files:
ArServerHandlerConfig.h
ArServerHandlerConfig.cpp