ArNetworking: ArClientRatioDrive Class Reference
ArClientRatioDrive Class Reference
Send continuous "ratio drive" requests to server, which spcifies robot velocities relative to user-configured maximums.
#include <ArClientRatioDrive.h>
Public Member Functions
ArClientRatioDrive (ArClientBase *client)
void safeDrive ()
Send a request to enable "safe drive" mode on the server.
void setDebugPrint (bool p=true)
void setLatVelRatio (double r)
Select a lateral velocity amount (percentage of server's maximum), and start sending continuous ratioDrive requests in the background.
void setRotVelRatio (double r)
Select a rotational velocity amount (percentage of server's maximum), and start sending continuous ratioDrive requests in the background.
void setThrottle (double t)
This is an additional modifier applied to each of the velocities when received by the server.
void setTransVelRatio (double r)
Select a translational (forward/back) velocity amount (percentage of server's maximum), and start sending continuous ratioDrive requests in the background.
void stop ()
Request stop mode on the server (sends 'stop' request), and stop sending ratioDrive requests until a new ratio value is set using setTransVelRatio(), setRotVelRatio(), or setLatVelRatio().
void unsafeDrive ()
Send a request to disable "safe drive" mode on the server (disables sensing etc.)
virtual ~ArClientRatioDrive ()
Protected Member Functions
void sendInput ()
void task ()
Protected Attributes
ArClientBase * myClient
ArFunctorC< ArClientRatioDrive > myCycleCB
ArKeyHandler * myKeyHandler
double myLatRatio
Current rotation ration value (a percentage of the maximum rotational velocity)
bool myPrinting
double myRotRatio
Current rotation ration value (a percentage of the maximum rotational velocity)
bool myStop
double myThrottle
double myTransRatio
Current translation value (a percentage of the maximum speed)
Detailed Description
Send continuous "ratio drive" requests to server, which spcifies robot velocities relative to user-configured maximums.
The user can set maximum translation and rotational velocities via server ArConfig. Remote clients can request robot speeds expressed as part (percentage) of those maximums. Remote clients can also enable or disable "safe" mode in which robot motion is limited by sensed and mapped obstacles. The ratioDrive service is provided by ArServerModeRatioDrive on the server. You can test whether a running server supports ratioDrive by calling client.dataExists("ratioDrive"); ArClientRatioDrive uses a robot task callback to periodically send the desired velocities set by calling setTransVelRatio() and setRotVelRatio().
Once any velocity ratio is set, this class will continously keep sending ratioDrive request packets to the server with the set ratios (these are sent from the ArNetworking communications cycle using a cycle callback). Calling stop() causes ArClientRatioDrive to stop sending requests, and to request "stop" mode (Provided on the server by ArServerModeStop).
To access configuration data on the server from software, use ArClientHandlerConfig. (Users can access configuration using MobileEyes.)
Constructor & Destructor Documentation
ArClientRatioDrive::ArClientRatioDrive (ArClientBase * client)
References ArClientBase::addCycleCallback(), myClient, myCycleCB, and myPrinting.
ArClientRatioDrive::~ArClientRatioDrive () virtual
References myClient, myCycleCB, myPrinting, ArClientBase::remCycleCallback(), and stop().
Member Function Documentation
void ArClientRatioDrive::safeDrive ()
Send a request to enable "safe drive" mode on the server.
References ArBasePacket::byteToBuf(), myClient, myPrinting, and ArClientBase::requestOnce().
Referenced by InputHandler::safeDrive(), and setThrottle().
void ArClientRatioDrive::sendInput (void) protected
References ArNetPacket::doubleToBuf(), myClient, myLatRatio, myRotRatio, myThrottle, myTransRatio, and ArClientBase::requestOnce().
Referenced by setDebugPrint(), and task().
void ArClientRatioDrive::setDebugPrint (bool p = true) inline
References myPrinting, sendInput(), and task().
Referenced by InputHandler::toggleDebug().
void ArClientRatioDrive::setLatVelRatio (double r)
Select a lateral velocity amount (percentage of server's maximum), and start sending continuous ratioDrive requests in the background.
Only some robots (Seekur) support lateral movement. Use 100 for full velocity, 50 for half velocity, 0 for none, etc.
References myLatRatio, myPrinting, and myStop.
Referenced by InputHandler::lateralLeft(), and InputHandler::lateralRight().
void ArClientRatioDrive::setRotVelRatio (double r)
Select a rotational velocity amount (percentage of server's maximum), and start sending continuous ratioDrive requests in the background.
Use 100 for full velocity, 50 for half velocity, 0 for none, etc.
References myPrinting, myRotRatio, and myStop.
Referenced by InputHandler::left(), and InputHandler::right().
void ArClientRatioDrive::setThrottle (double t) inline
This is an additional modifier applied to each of the velocities when received by the server.
It is 100% by default but can be reduced here to provide an overall control of all robot speed.
References myThrottle, safeDrive(), stop(), and unsafeDrive().
void ArClientRatioDrive::setTransVelRatio (double r)
Select a translational (forward/back) velocity amount (percentage of server's maximum), and start sending continuous ratioDrive requests in the background.
Use 100 for full velocity, 50 for half velocity, 0 for none, etc.
References myPrinting, myStop, and myTransRatio.
Referenced by InputHandler::down(), and InputHandler::up().
void ArClientRatioDrive::stop (void)
Request stop mode on the server (sends 'stop' request), and stop sending ratioDrive requests until a new ratio value is set using setTransVelRatio(), setRotVelRatio(), or setLatVelRatio().
Note: You may need to wait a few seconds for the robot to fully stop before driving again – stop mode will report a status of "Stopping" while slowing down, then "Stopped" when robot is fully stopped, and it may not be possible to interrupt the Stopping stage.
References myClient, myLatRatio, myPrinting, myRotRatio, myStop, myTransRatio, and ArClientBase::requestOnce().
Referenced by setThrottle(), InputHandler::space(), and ~ArClientRatioDrive().
void ArClientRatioDrive::task () protected
References myStop, and sendInput().
Referenced by setDebugPrint().
void ArClientRatioDrive::unsafeDrive ()
Send a request to disable "safe drive" mode on the server (disables sensing etc.)
References ArBasePacket::byteToBuf(), myClient, myPrinting, and ArClientBase::requestOnce().
Referenced by setThrottle(), and InputHandler::unsafeDrive().
Member Data Documentation
ArClientBase* ArClientRatioDrive::myClient protected
Referenced by ArClientRatioDrive(), safeDrive(), sendInput(), stop(), unsafeDrive(), and ~ArClientRatioDrive().
ArFunctorC<ArClientRatioDrive> ArClientRatioDrive::myCycleCB protected
Referenced by ArClientRatioDrive(), and ~ArClientRatioDrive().
ArKeyHandler* ArClientRatioDrive::myKeyHandler protected
double ArClientRatioDrive::myLatRatio protected
Current rotation ration value (a percentage of the maximum rotational velocity)
Referenced by sendInput(), setLatVelRatio(), and stop().
bool ArClientRatioDrive::myPrinting protected
Referenced by ArClientRatioDrive(), safeDrive(), setDebugPrint(), setLatVelRatio(), setRotVelRatio(), setTransVelRatio(), stop(), unsafeDrive(), and ~ArClientRatioDrive().
double ArClientRatioDrive::myRotRatio protected
Current rotation ration value (a percentage of the maximum rotational velocity)
Referenced by sendInput(), setRotVelRatio(), and stop().
bool ArClientRatioDrive::myStop protected
Referenced by setLatVelRatio(), setRotVelRatio(), setTransVelRatio(), stop(), and task().
double ArClientRatioDrive::myThrottle protected
Referenced by sendInput(), and setThrottle().
double ArClientRatioDrive::myTransRatio protected
Current translation value (a percentage of the maximum speed)
Referenced by sendInput(), setTransVelRatio(), and stop().
The documentation for this class was generated from the following files:
ArClientRatioDrive.h
ArClientRatioDrive.cpp