ArNetworking: ArServerSimpleComGyro Class Reference
ArServerSimpleComGyro Class Reference
Class for enabling or disabling the gyro.
#include <ArServerSimpleCommands.h>
Public Member Functions
ArServerSimpleComGyro (ArServerHandlerCommands *handlerCommands, ArRobot *robot, ArAnalogGyro *gyro)
Constructor.
void gyroDisable (void)
Disables the gyro.
void gyroEnable (void)
Enables the gyro.
virtual ~ArServerSimpleComGyro ()
Destructor.
Protected Attributes
ArAnalogGyro * myGyro
ArFunctorC< ArServerSimpleComGyro > myGyroDisableCB
ArFunctorC< ArServerSimpleComGyro > myGyroEnableCB
ArServerHandlerCommands * myHandlerCommands
ArRobot * myRobot
Detailed Description
Class for enabling or disabling the gyro.
This just calls ArAnalogGyro::activate and ArAnalogGyro::deactivate. If you want to see the gyro data if you use the robot's movement received (either ArRobot::setLogMovementReceived or use ArServerSimpleComMovementLogging)
Examples:
serverDemo.cpp.
Constructor & Destructor Documentation
ArServerSimpleComGyro::ArServerSimpleComGyro (ArServerHandlerCommands * handlerCommands, ArRobot * robot, ArAnalogGyro * gyro)
Constructor.
References ArServerHandlerCommands::addCommand(), myGyro, myGyroDisableCB, myGyroEnableCB, myHandlerCommands, and myRobot.
ArServerSimpleComGyro::~ArServerSimpleComGyro () virtual
Destructor.
Member Function Documentation
void ArServerSimpleComGyro::gyroDisable (void)
Disables the gyro.
References ArAnalogGyro::deactivate(), ArRobot::lock(), myGyro, myRobot, and ArRobot::unlock().
void ArServerSimpleComGyro::gyroEnable (void)
Enables the gyro.
References ArAnalogGyro::activate(), ArRobot::lock(), myGyro, myRobot, and ArRobot::unlock().
Member Data Documentation
ArAnalogGyro* ArServerSimpleComGyro::myGyro protected
Referenced by ArServerSimpleComGyro(), gyroDisable(), and gyroEnable().
ArFunctorC<ArServerSimpleComGyro> ArServerSimpleComGyro::myGyroDisableCB protected
Referenced by ArServerSimpleComGyro().
ArFunctorC<ArServerSimpleComGyro> ArServerSimpleComGyro::myGyroEnableCB protected
Referenced by ArServerSimpleComGyro().
ArServerHandlerCommands* ArServerSimpleComGyro::myHandlerCommands protected
Referenced by ArServerSimpleComGyro().
ArRobot* ArServerSimpleComGyro::myRobot protected
Referenced by ArServerSimpleComGyro(), gyroDisable(), gyroEnable(), and ArServerSimpleComMovementLogging::resetOdometer().
The documentation for this class was generated from the following files:
ArServerSimpleCommands.h
ArServerSimpleCommands.cpp