ArNetworking: ArServerInfoRobot Class Reference
ArServerInfoRobot Class Reference
Server component providing basic robot status information to clients.
#include <ArServerInfoRobot.h>
Public Member Functions
void activityTimeInfo (ArServerClient *client, ArNetPacket *packet)
The function that sends information about the time that the server mode was last active.
ArServerInfoRobot (ArServerBase *server, ArRobot *robot)
Constructor.
void batteryInfo (ArServerClient *client, ArNetPacket *packet)
The function that sends battery info about the robot off to the client.
void physicalInfo (ArServerClient *client, ArNetPacket *packet)
The function that sends information about the physical robot.
void update (ArServerClient *client, ArNetPacket *packet)
The function that sends updates about the robot off to the client.
void updateNumbers (ArServerClient *client, ArNetPacket *packet)
The function that sends updates about the robot off to the client.
void updateStrings (ArServerClient *client, ArNetPacket *packet)
The function that sends updates about the robot off to the client.
virtual ~ArServerInfoRobot ()
Destructor.
Protected Member Functions
void userTask (void)
Protected Attributes
ArFunctor2C< ArServerInfoRobot, ArServerClient *, ArNetPacket * > myActivityTimeInfoCB
ArFunctor2C< ArServerInfoRobot, ArServerClient *, ArNetPacket * > myBatteryInfoCB
std::string myExtendedStatus
std::string myMode
std::string myOldExtendedStatus
std::string myOldMode
std::string myOldStatus
ArFunctor2C< ArServerInfoRobot, ArServerClient *, ArNetPacket * > myPhysicalInfoCB
ArRobot * myRobot
ArServerBase * myServer
std::string myStatus
ArFunctor2C< ArServerInfoRobot, ArServerClient *, ArNetPacket * > myUpdateCB
ArFunctor2C< ArServerInfoRobot, ArServerClient *, ArNetPacket * > myUpdateNumbersCB
ArFunctor2C< ArServerInfoRobot, ArServerClient *, ArNetPacket * > myUpdateStringsCB
ArFunctorC< ArServerInfoRobot > myUserTaskCB
Detailed Description
Server component providing basic robot status information to clients.
This service accepts the following data requests:
updateNumbers
updateStrings
update
physicalInfo
batteryInfo
activityTimeInfo
For bandwidth savings you should use updateNumbers at a higher frequency and updateStrings at a lower frequency instead of update at high frequency request rate.
The updateNumbers request returns data regarding the current state of the robot. It replies with the following data packet:
Battery voltage (times 10) (2 Byte integer)
X position (4 byte floating point number)
Y position (4 byte floating point number)
Theta (2-byte floating point number)
Forward velocity (2-byte integer)
Rotation velocity (2-byte integer)
The updateStrings request broadcasts data regarding the current state of the robot. Request this at -1 to get the broadcasts and an initial packet with the inital data. It replies with the following data packet:
Status (Null-terminated string)
Mode (Null-terminated string)
The deprecated update request returns all data regarding the current state of the robot. It replies with the following data packet:
Status (Null-terminated string)
Mode (Null-terminated string)
Battery voltage (times 10) (2 Byte integer)
X position (4 byte floating point number)
Y position (4 byte floating point number)
Theta (2-byte floating point number)
Forward velocity (2-byte integer)
Rotation velocity (2-byte integer)
The physicalInfo request returns data regarding the physical characteristics of the robot. This information does not change during the robot execution, so only needs to be requested once or as needed. It replies with the following data packet:
Robot type (Null-terminated string)
Robot sub-type (Null-terminated string)
Robot width in mm (2 byte integer)
Robot front length - mm from center of rotation to front of robot (2 byte integer)
Robot rear length - mm from center of rotation to back of robot (2 byte integer)
The batteryInfo request replies with the following data packet:
Warning voltage (double)
Shutdown voltage (double)
The activityTimeInfo request replies with the following data packet:
Sec since - the ArServerMode::getActiveModeActivityTimeSecSince value (4-byte int)
These requests are in the RobotInfo command group.
Examples:
drawingsExampleWithRobot.cpp, popupExample.cpp, and serverDemo.cpp.
Constructor & Destructor Documentation
ArServerInfoRobot::ArServerInfoRobot (ArServerBase * server, ArRobot * robot)
Constructor.
References ArServerBase::addData(), ArRobot::addUserTask(), myActivityTimeInfoCB, myBatteryInfoCB, myPhysicalInfoCB, myRobot, myServer, myUpdateCB, myUpdateNumbersCB, myUpdateStringsCB, myUserTaskCB, and ArFunctor::setName().
ArServerInfoRobot::~ArServerInfoRobot () virtual
Destructor.
Member Function Documentation
void ArServerInfoRobot::activityTimeInfo (ArServerClient * client, ArNetPacket * packet)
The function that sends information about the time that the server mode was last active.
References ArBasePacket::byte4ToBuf(), ArServerMode::getActiveModeActivityTimeSecSince(), ArRobot::lock(), myRobot, ArServerClient::sendPacketTcp(), and ArRobot::unlock().
void ArServerInfoRobot::batteryInfo (ArServerClient * client, ArNetPacket * packet)
The function that sends battery info about the robot off to the client.
References ArNetPacket::doubleToBuf(), ArRobotConfigPacketReader::getLowBattery(), ArRobot::getOrigRobotConfig(), ArRobotConfigPacketReader::getShutdownVoltage(), ArRobot::getStateOfChargeLow(), ArRobot::getStateOfChargeShutdown(), ArRobotConfigPacketReader::hasPacketArrived(), ArRobot::haveStateOfCharge(), ArRobot::lock(), myRobot, ArServerClient::sendPacketTcp(), ArBasePacket::uByteToBuf(), and ArRobot::unlock().
void ArServerInfoRobot::physicalInfo (ArServerClient * client, ArNetPacket * packet)
The function that sends information about the physical robot.
References ArBasePacket::byte2ToBuf(), ArBasePacket::byteToBuf(), ArRobot::getRobotLengthFront(), ArRobot::getRobotLengthRear(), ArRobot::getRobotSubType(), ArRobot::getRobotType(), ArRobot::getRobotWidth(), ArRobot::hasLatVel(), ArRobot::lock(), myRobot, ArServerClient::sendPacketTcp(), ArBasePacket::strToBuf(), and ArRobot::unlock().
void ArServerInfoRobot::update (ArServerClient * client, ArNetPacket * packet)
The function that sends updates about the robot off to the client.
References ArBasePacket::byte2ToBuf(), ArBasePacket::byte4ToBuf(), ArBasePacket::byteToBuf(), ArMath::fixAngle(), ArServerMode::getActiveMode(), ArRobot::getBatteryVoltage(), ArRobot::getLatVel(), ArServerMode::getMode(), ArRobot::getRealBatteryVoltage(), ArRobot::getRotVel(), ArRobot::getStateOfCharge(), ArServerMode::getStatus(), ArRobot::getTemperature(), ArRobot::getTh(), ArRobot::getVel(), ArRobot::getX(), ArRobot::getY(), ArRobot::haveStateOfCharge(), ArRobot::lock(), myRobot, ArMath::roundInt(), ArServerClient::sendPacketUdp(), ArBasePacket::strToBuf(), and ArRobot::unlock().
void ArServerInfoRobot::updateNumbers (ArServerClient * client, ArNetPacket * packet)
The function that sends updates about the robot off to the client.
References ArBasePacket::byte2ToBuf(), ArBasePacket::byte4ToBuf(), ArBasePacket::byteToBuf(), ArMath::fixAngle(), ArRobot::getBatteryVoltage(), ArRobot::getLatVel(), ArRobot::getRealBatteryVoltage(), ArRobot::getRotVel(), ArRobot::getStateOfCharge(), ArRobot::getTemperature(), ArRobot::getTh(), ArRobot::getVel(), ArRobot::getX(), ArRobot::getY(), ArRobot::haveStateOfCharge(), ArRobot::lock(), myRobot, ArMath::roundInt(), ArServerClient::sendPacketUdp(), and ArRobot::unlock().
void ArServerInfoRobot::updateStrings (ArServerClient * client, ArNetPacket * packet)
The function that sends updates about the robot off to the client.
References ArRobot::lock(), myExtendedStatus, myMode, myRobot, myStatus, ArServerClient::sendPacketTcp(), ArBasePacket::strToBuf(), and ArRobot::unlock().
void ArServerInfoRobot::userTask (void) protected
References ArServerBase::broadcastPacketTcp(), ArServerMode::getActiveMode(), ArServerMode::getExtendedStatus(), ArServerMode::getMode(), ArServerMode::getStatus(), myExtendedStatus, myMode, myOldExtendedStatus, myOldMode, myOldStatus, myServer, myStatus, and ArBasePacket::strToBuf().
Member Data Documentation
ArFunctor2C<ArServerInfoRobot, ArServerClient *, ArNetPacket *> ArServerInfoRobot::myActivityTimeInfoCB protected
Referenced by ArServerInfoRobot().
ArFunctor2C<ArServerInfoRobot, ArServerClient *, ArNetPacket *> ArServerInfoRobot::myBatteryInfoCB protected
Referenced by ArServerInfoRobot().
std::string ArServerInfoRobot::myExtendedStatus protected
Referenced by updateStrings(), and userTask().
std::string ArServerInfoRobot::myMode protected
Referenced by updateStrings(), and userTask().
std::string ArServerInfoRobot::myOldExtendedStatus protected
Referenced by userTask().
std::string ArServerInfoRobot::myOldMode protected
Referenced by userTask().
std::string ArServerInfoRobot::myOldStatus protected
Referenced by userTask().
ArFunctor2C<ArServerInfoRobot, ArServerClient *, ArNetPacket *> ArServerInfoRobot::myPhysicalInfoCB protected
Referenced by ArServerInfoRobot().
ArRobot* ArServerInfoRobot::myRobot protected
Referenced by activityTimeInfo(), ArServerInfoRobot(), batteryInfo(), physicalInfo(), update(), updateNumbers(), and updateStrings().
ArServerBase* ArServerInfoRobot::myServer protected
Referenced by ArServerInfoRobot(), and userTask().
std::string ArServerInfoRobot::myStatus protected
Referenced by updateStrings(), and userTask().
ArFunctor2C<ArServerInfoRobot, ArServerClient *, ArNetPacket *> ArServerInfoRobot::myUpdateCB protected
Referenced by ArServerInfoRobot().
ArFunctor2C<ArServerInfoRobot, ArServerClient *, ArNetPacket *> ArServerInfoRobot::myUpdateNumbersCB protected
Referenced by ArServerInfoRobot().
ArFunctor2C<ArServerInfoRobot, ArServerClient *, ArNetPacket *> ArServerInfoRobot::myUpdateStringsCB protected
Referenced by ArServerInfoRobot().
ArFunctorC<ArServerInfoRobot> ArServerInfoRobot::myUserTaskCB protected
Referenced by ArServerInfoRobot().
The documentation for this class was generated from the following files:
ArServerInfoRobot.h
ArServerInfoRobot.cpp