ArNetworking: ArNetPacketReceiverUdp Class Reference
ArNetPacketReceiverUdp Class Reference
This is the receiver for UDP packets.
#include <ArNetPacketReceiverUdp.h>
Public Member Functions
ArNetPacketReceiverUdp ()
ArFunctor2< ArNetPacket
*, struct sockaddr_in * > * getProcessPacketCB (void)
Gets the callback used when a packet is received.
ArSocket * getSocket (void)
Gets the socket this receiver uses.
bool readData (void)
Reads in all the data available calling the processPacketCB.
void setProcessPacketCB (ArFunctor2< ArNetPacket *, struct sockaddr_in * > *functor)
Sets the callback for use when a packet is received.
void setSocket (ArSocket *socket)
Sets the socket this receiver uses.
~ArNetPacketReceiverUdp ()
Protected Attributes
char myBuff [ArNetPacket::MAX_LENGTH+20]
ArTime myLastPacket
ArNetPacket myPacket
ArFunctor2< ArNetPacket
*, struct sockaddr_in * > * myProcessPacketCB
ArSocket * mySocket
Detailed Description
This is the receiver for UDP packets.
Constructor & Destructor Documentation
ArNetPacketReceiverUdp::ArNetPacketReceiverUdp ()
References ArNetPacket::MAX_LENGTH, myBuff, myPacket, and ArBasePacket::setBuf().
ArNetPacketReceiverUdp::~ArNetPacketReceiverUdp ()
Member Function Documentation
ArFunctor2< ArNetPacket *, struct sockaddr_in * > * ArNetPacketReceiverUdp::getProcessPacketCB (void)
Gets the callback used when a packet is received.
Returns:
the callback used when a packet needs to be processed
References myProcessPacketCB.
ArSocket * ArNetPacketReceiverUdp::getSocket (void)
Gets the socket this receiver uses.
Gets the socket that the receiver is using, note that it does not have ownership of this socket and that whatever created it should.
References mySocket.
bool ArNetPacketReceiverUdp::readData (void)
Reads in all the data available calling the processPacketCB.
References ArNetPacket::getCommand(), ArFunctor2< P1, P2 >::invoke(), ArLog::log(), myBuff, myPacket, myProcessPacketCB, mySocket, ArLog::Normal, ArSocket::recvFrom(), ArNetPacket::resetRead(), ArBasePacket::setBuf(), ArBasePacket::setLength(), ArNetPacket::setPacketSource(), ArLog::Terse, ArNetPacket::UDP, ArLog::Verbose, and ArNetPacket::verifyCheckSum().
Referenced by ArServerBase::loopOnce(), and ArClientBase::loopOnce().
void ArNetPacketReceiverUdp::setProcessPacketCB (ArFunctor2< ArNetPacket *, struct sockaddr_in * > * functor)
Sets the callback for use when a packet is received.
Parameters:
functor the callback to use when a packet needs to be processed
References myProcessPacketCB.
Referenced by ArClientBase::ArClientBase(), and ArServerBase::ArServerBase().
void ArNetPacketReceiverUdp::setSocket (ArSocket * socket)
Sets the socket this receiver uses.
Sets the socket that this receiver will use, note that it does not transfer ownership of the socket.
Parameters:
socket the socket to use for receiving data
References mySocket.
Referenced by ArClientBase::ArClientBase(), and ArServerBase::open().
Member Data Documentation
char ArNetPacketReceiverUdp::myBuff[ArNetPacket::MAX_LENGTH+20] [protected]
Referenced by ArNetPacketReceiverUdp(), and readData().
ArTime ArNetPacketReceiverUdp::myLastPacket [protected]
ArNetPacket ArNetPacketReceiverUdp::myPacket [protected]
Referenced by ArNetPacketReceiverUdp(), and readData().
ArFunctor2<ArNetPacket *, struct sockaddr_in *>* ArNetPacketReceiverUdp::myProcessPacketCB [protected]
Referenced by getProcessPacketCB(), readData(), and setProcessPacketCB().
ArSocket* ArNetPacketReceiverUdp::mySocket [protected]
Referenced by getSocket(), readData(), and setSocket().
The documentation for this class was generated from the following files:
ArNetPacketReceiverUdp.h
ArNetPacketReceiverUdp.cpp