ArNetworking: ArServerMode Class Reference
ArServerMode Class Reference abstract
A mode for controlling the robot (only one active)
#include <ArServerMode.h>
Public Member Functions
virtual void activate (void)=0
The function called when the mode is activated.
virtual void activationDenied (void)
The function called if the mode is not activated because another mode superceded it.
void addActivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is activated.
void addAsDefaultMode (ArListPos::Pos pos=ArListPos::LAST)
Sets this mode to default (so if a mode deactivates it activates this)
void addDeactivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is deactivated.
bool addModeData (const char *name, const char *description, ArFunctor2< ArServerClient *, ArNetPacket * > *functor, const char *argumentDescription, const char *returnDescription, const char *commandGroup=NULL, const char *dataFlags=NULL)
This basically just notes the commands associated with a mode so that clients can know what can and can't happen based on what mode is active/locked/etc.
void addSingleShotDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for when this class is deactivated.
void addSingleShotPostDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for just after the deactivate happens (when the next mode has activated)
ArServerMode (ArRobot *robot, ArServerBase *server, const char *name)
Constructor.
virtual void checkDefault (void)
Sees if this wants to become the default mode.
virtual void deactivate (void)=0
The function called when the mode is deactivated.
virtual void forceUnlock (void)
This will be called if another mode has to break the lock.
virtual ArActionGroup * getActionGroup (void)
This function should return the action group this mode uses.
ArTime getActivityTime (void)
Gets the time of our last activity.
const char * getExtendedStatus (void) const
Gets a string representing the extended status of the mode we're in.
const char * getMode (void) const
Gets a string representing the mode we're in.
const char * getName (void) const
Gets the name of the mode we're in.
const char * getStatus (void) const
Gets a string representing the status of the mode we're in.
bool hasSetActivityTime (void)
Gets if we've set our activity time.
void internalSetActivityTime (ArTime time)
Internal call to set the activity time (this is dangerous and shouldn't be used)
bool isActive (void) const
Gets if this mode is active or not.
virtual bool isAutoResumeAfterInterrupt ()
Adds data to the list of this mode's commands.
void lockMode (bool willUnlockIfRequested=false)
Locks this mode in until its unlocked (mode must be the active mode)
void remActivateCallback (ArFunctor *functor)
Removes a callback for when this class is activated.
void remDeactivateCallback (ArFunctor *functor)
Removes a callback for when this class is deactivated.
void remSingleShotDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for when this class is deactivated.
void remSingleShotPostDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for just after the deactivate happens (when the next mode has activated)
virtual void requestUnlock (void)
This will be called if another mode wants the lock broken (can ignore)
void setActivityTimeToNow (void)
Sets that we're active right now.
void setMode (const char *str)
This should only be used by careful people and probably not then.
void setStatus (const char *str)
This should only be used by careful people and probably not then.
void unlockMode (void)
Unlocks the mode so other modes can activate.
virtual void userTask (void)
The ArMode's user task, don't need one, subclass must provide if needed.
virtual ~ArServerMode ()
Destructor.
Static Public Member Functions
static ArServerMode * getActiveMode (void)
Gets the active mode.
static int getActiveModeActivityTimeSecSince (void)
Gets the seconds since the activity of our active mode.
static const char * getActiveModeExtendedStatusString (void)
Gets the active extended status string.
static const char * getActiveModeModeString (void)
Gets the active mode string.
static bool getActiveModeSetActivityThisCycle (void)
Gets if the active mode set the activity time this cycle or not.
static const char * getActiveModeStatusString (void)
Gets the active status string.
static ArServerModeIdle * getIdleMode (void)
Call that gets our idle mode.
static void getModeBusy (ArServerClient *client, ArNetPacket *packet)
Handles the packet request for the mode busy state.
static void getModeDataList (ArServerClient *client, ArNetPacket *packet)
Gets the list of data for each mode.
static void getModeInfo (ArServerClient *client, ArNetPacket *packet)
Gets the info about which mode is active and such.
static bool isLocked (void)
Gets if the active mode is locked or not.
static bool willUnlockIfRequested (void)
Gets whether we'll unlock if requested or not.
Protected Member Functions
bool baseActivate (bool canSelfActivateIfLocked=false)
Activates this mode if it can (returns true if it can, false otherwise).
void baseDeactivate (void)
Deactivates this mode.
void checkBroadcastModeInfoPacket (void)
ArServerMode * getLastActiveMode ()
Static Protected Member Functions
static void buildModeInfoPacket (ArNetPacket *packet)
static std::list< ArServerMode * > * getRequestedActivateModes (void)
static void modeUserTask (void)
Protected Attributes
ArCallbackList myActivateCallbacks
ArTime myActivityTime
ArMutex myActivityTimeMutex
ArCallbackList myDeactivateCallbacks
std::string myExtendedStatus
bool myHasSetActivityTime
bool myIsActive
std::string myMode
std::string myName
ArRobot * myRobot
ArServerBase * myServer
bool mySetActivityThisCycle
ArCallbackList mySingleShotDeactivateCallbacks
ArCallbackList mySingleShotPostDeactivateCallbacks
std::string myStatus
bool myStatusSetThisCycle
ArLog::LogLevel myVerboseLogLevel
Static Protected Attributes
static ArServerMode * ourActiveMode = NULL
static bool ourActiveModeLocked = false
static bool ourActiveModeSetActivityThisCycle = false
static bool ourActiveModeWillUnlockIfRequested = false
static ArServerMode * ourBroadcastActiveMode = NULL
static bool ourBroadcastActiveModeLocked = false
static bool ourBroadcastActiveModeWillUnlockIfRequested = false
static std::list< ArServerMode * > ourDefaultModes
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeBusyCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeDataListCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeInfoCB
static ArServerModeIdle * ourIdleMode = NULL
static bool ourIdleModeCreated = false
static ArMutex ourIdleModeMutex
static bool ourIsBusy = false
static ArServerMode * ourLastActiveMode = NULL
static std::multimap< std::string, std::string > ourModeDataMap
static ArMutex ourModeDataMapMutex
static std::list< ArServerMode * > ourModes
static ArServerMode * ourNextActiveMode = NULL
static std::list< ArServerMode * > ourRequestedActivateModes
static ArServerBase * ourServerBase = NULL
static bool ourUserTaskAdded = false
static ArGlobalFunctor ourUserTaskCB
Detailed Description
A mode for controlling the robot (only one active)
This is a lot like ArMode but for net control instead...
Only one mode can control the robot at once, this is made to be subclassed. Each subclass needs to implement activate and deactivate, activate MUST call baseActivate and if baseActivate returns false then the mode is NOT active and shouldn't do anything. Further each class should set myMode and myStatus to the mode its in and the things its doing... You can lock your mode in with lockMode and unlock it with unlockMode but you should redefine the inherited requestUnlock and unlock yourself and deactivate gracefully.
If you want to implement a server mode as a default mode then you also need to implement checkDefault which will be called when nothing else is active
Note that there's a new mechanism in place where if you use addModeData instead of addData on the ArServerBase the command will be placed into a map of available modes with commands that can be gotten by the client. The active mode and whether its locked and will unlock and such can now be gotten too... this is all so that different commands can be disabled in client GUIs when they aren't available.
Constructor & Destructor Documentation
ArServerMode::ArServerMode (ArRobot * robot, ArServerBase * server, const char * name)
Constructor.
References ArServerBase::addData(), ArRobot::addUserTask(), ArMutex::lock(), myActivateCallbacks, myActivityTimeMutex, myDeactivateCallbacks, myHasSetActivityTime, myIsActive, myName, myRobot, myServer, mySetActivityThisCycle, mySingleShotDeactivateCallbacks, mySingleShotPostDeactivateCallbacks, myStatusSetThisCycle, myVerboseLogLevel, ourGetModeBusyCB, ourGetModeDataListCB, ourGetModeInfoCB, ourIdleMode, ourIdleModeCreated, ourIdleModeMutex, ourModeDataMapMutex, ourModes, ourServerBase, ourUserTaskAdded, ourUserTaskCB, ArMutex::setLogName(), ArGenericCallbackList< ArFunctor * >::setName(), ArGenericCallbackList< ArFunctor * >::setSingleShot(), ArMutex::unlock(), and ArLog::Verbose.
ArServerMode::~ArServerMode () virtual
Destructor.
Member Function Documentation
virtual void ArServerMode::activate (void) pure virtual
The function called when the mode is activated.
Subclasses must implement this, but also call baseActivate().-
Implemented in ArServerModeJogPosition, ArServerModeRatioDrive, ArServerModeIdle, ArServerModeDrive, ArServerModeWander, and ArServerModeStop.
Referenced by getActionGroup(), and unlockMode().
virtual void ArServerMode::activationDenied (void) inline virtual
The function called if the mode is not activated because another mode superceded it.
Referenced by baseDeactivate().
void ArServerMode::addActivateCallback (ArFunctor * functor, int position = 50) inline
Adds a callback for when this class is activated.
References ArGenericCallbackList< ArFunctor * >::addCallback(), and myActivateCallbacks.
void ArServerMode::addAsDefaultMode (ArListPos::Pos pos = ArListPos::LAST)
Sets this mode to default (so if a mode deactivates it activates this)
The default mode is activated whenever a mode is deactivated, even if a mode is deactivated only for another mode to be activated.
Examples:
popupExample.cpp, and serverDemo.cpp.
References ArListPos::FIRST, getName(), ArListPos::LAST, ArLog::log(), ArLog::Normal, ourDefaultModes, and ArLog::Terse.
Referenced by hasSetActivityTime(), and main().
void ArServerMode::addDeactivateCallback (ArFunctor * functor, int position = 50) inline
Adds a callback for when this class is deactivated.
References ArGenericCallbackList< ArFunctor * >::addCallback(), and myDeactivateCallbacks.
bool ArServerMode::addModeData (const char * name, const char * description, ArFunctor2< ArServerClient *, ArNetPacket * > * functor, const char * argumentDescription, const char * returnDescription, const char * commandGroup = NULL, const char * dataFlags = NULL)
This basically just notes the commands associated with a mode so that clients can know what can and can't happen based on what mode is active/locked/etc.
You should call it only if the addData on the ArServerBase returns true (since otherwise it means that command wasn't added).
References ArServerBase::addData(), ArMutex::lock(), ArLog::log(), myName, myServer, ArLog::Normal, ourModeDataMap, ourModeDataMapMutex, and ArMutex::unlock().
Referenced by ArServerModeDrive::ArServerModeDrive(), ArServerModeJogPosition::ArServerModeJogPosition(), ArServerModeRatioDrive::ArServerModeRatioDrive(), ArServerModeStop::ArServerModeStop(), ArServerModeWander::ArServerModeWander(), and setStatus().
void ArServerMode::addSingleShotDeactivateCallback (ArFunctor * functor, int position = 50) inline
Adds a single shot callback for when this class is deactivated.
References ArGenericCallbackList< ArFunctor * >::addCallback(), and mySingleShotDeactivateCallbacks.
void ArServerMode::addSingleShotPostDeactivateCallback (ArFunctor * functor, int position = 50) inline
Adds a single shot callback for just after the deactivate happens (when the next mode has activated)
References ArGenericCallbackList< ArFunctor * >::addCallback(), and mySingleShotPostDeactivateCallbacks.
bool ArServerMode::baseActivate (bool canSelfActivateIfLocked = false) protected
Activates this mode if it can (returns true if it can, false otherwise).
Makes this mode active if it can...
If we have an ArRobot instance (myRobot), then robot motion is stopped. Activity time is reset, and activate callbacks are called.
If this returns false then the mode's activate() method should just return... Note that before calling this a mode should have already made sure it can activate... This also calls the activate callbacks (only if the mode will be allowed to activate of course).
IMPORTANT: This method must only be called within the context of the activate() method.
Call our activate callbacks
Set the activity time to now, but do NOT set the flag, since that flag is used to determine if a particular mode has used it or not
References ArServerModeIdle::activate(), checkBroadcastModeInfoPacket(), ArRobot::clearDirectMotion(), ArUtil::convertBool(), deactivate(), getName(), ArServerBase::idleProcessingPending(), ArCallbackList::invoke(), ArMutex::lock(), ArLog::log(), myActivateCallbacks, myActivityTime, myActivityTimeMutex, myIsActive, myRobot, myServer, myVerboseLogLevel, ourActiveMode, ourActiveModeLocked, ourIdleMode, ourLastActiveMode, ourNextActiveMode, ourRequestedActivateModes, requestUnlock(), ArServerModeIdle::setModeInterrupted(), ArTime::setToNow(), ArRobot::stop(), and ArMutex::unlock().
Referenced by ArServerModeStop::activate(), ArServerModeWander::activate(), ArServerModeIdle::activate(), ArServerModeJogPosition::activate(), ArServerModeDrive::driveJoystick(), ArServerModeRatioDrive::ratioDrive(), and remSingleShotPostDeactivateCallback().
void ArServerMode::baseDeactivate (void) protected
Deactivates this mode.
Whenever a mode uses this it should already have done all of its own deactivations (this also calls the deactive callbacks)
Deactivation callbacks are called. The next mode to be activated is activated, if any. (E.g. the global default mode)
References activationDenied(), getName(), ArCallbackList::invoke(), ArLog::log(), myDeactivateCallbacks, myIsActive, mySingleShotDeactivateCallbacks, mySingleShotPostDeactivateCallbacks, myVerboseLogLevel, ArLog::Normal, ourActiveMode, ourActiveModeLocked, ourDefaultModes, ourIdleMode, ourLastActiveMode, ourNextActiveMode, ourRequestedActivateModes, and unlockMode().
Referenced by ArServerModeStop::deactivate(), ArServerModeWander::deactivate(), ArServerModeDrive::deactivate(), ArServerModeIdle::deactivate(), ArServerModeRatioDrive::deactivate(), ArServerModeJogPosition::deactivate(), and remSingleShotPostDeactivateCallback().
void ArServerMode::buildModeInfoPacket (ArNetPacket * packet) static protected
References getName(), ourActiveMode, ourActiveModeLocked, ourActiveModeWillUnlockIfRequested, ArBasePacket::strToBuf(), and ArBasePacket::uByteToBuf().
Referenced by checkBroadcastModeInfoPacket(), getModeInfo(), and remSingleShotPostDeactivateCallback().
void ArServerMode::checkBroadcastModeInfoPacket (void) protected
References ArServerBase::broadcastPacketTcp(), buildModeInfoPacket(), myServer, ourActiveMode, ourActiveModeLocked, ourActiveModeWillUnlockIfRequested, ourBroadcastActiveMode, ourBroadcastActiveModeLocked, and ourBroadcastActiveModeWillUnlockIfRequested.
Referenced by baseActivate(), lockMode(), remSingleShotPostDeactivateCallback(), and unlockMode().
virtual void ArServerMode::checkDefault (void) inline virtual
Sees if this wants to become the default mode.
This will be called when there would be no other modes, if this mode wants to take over it should activate itself, if it doesn't want to take over it shouldn't activate
Reimplemented in ArServerModeWander, and ArServerModeStop.
virtual void ArServerMode::deactivate (void) pure virtual
The function called when the mode is deactivated.
Subclasses must implement this, and also call baseDeactivate().
Implemented in ArServerModeJogPosition, ArServerModeRatioDrive, ArServerModeIdle, ArServerModeDrive, ArServerModeWander, and ArServerModeStop.
Referenced by baseActivate(), and getActionGroup().
void ArServerMode::forceUnlock (void) virtual
This will be called if another mode has to break the lock.
This should only be called from places where a forced unlock HAS to happen, ie on a robot joystick, but modes should do whatever they have to in this to turn things off or what not.
References getName(), ArLog::log(), ArLog::Terse, and unlockMode().
Referenced by ArServerModeRatioDrive::joyUserTask(), and requestUnlock().
virtual ArActionGroup* ArServerMode::getActionGroup (void) inline virtual
This function should return the action group this mode uses.
Reimplemented in ArServerModeJogPosition, ArServerModeRatioDrive, ArServerModeDrive, ArServerModeIdle, ArServerModeWander, and ArServerModeStop.
References activate(), and deactivate().
ArServerMode * ArServerMode::getActiveMode (void) static
Gets the active mode.
References ourActiveMode.
Referenced by isActive(), ArServerModeDrive::joyUserTask(), ArServerModeRatioDrive::joyUserTask(), ArServerInfoRobot::update(), and ArServerInfoRobot::userTask().
int ArServerMode::getActiveModeActivityTimeSecSince (void) static
Gets the seconds since the activity of our active mode.
References getActivityTime(), ourActiveMode, and ArTime::secSince().
Referenced by ArServerInfoRobot::activityTimeInfo(), hasSetActivityTime(), modeUserTask(), and ArServerBase::slowIdleCallback().
const char * ArServerMode::getActiveModeExtendedStatusString (void) static
Gets the active extended status string.
References getExtendedStatus(), and ourActiveMode.
Referenced by getExtendedStatus().
const char * ArServerMode::getActiveModeModeString (void) static
Gets the active mode string.
References getMode(), and ourActiveMode.
Referenced by getExtendedStatus().
bool ArServerMode::getActiveModeSetActivityThisCycle (void) static
Gets if the active mode set the activity time this cycle or not.
References ourActiveModeSetActivityThisCycle.
Referenced by hasSetActivityTime().
const char * ArServerMode::getActiveModeStatusString (void) static
Gets the active status string.
References getStatus(), and ourActiveMode.
Referenced by getExtendedStatus().
ArTime ArServerMode::getActivityTime (void)
Gets the time of our last activity.
References ArMutex::lock(), myActivityTime, myActivityTimeMutex, and ArMutex::unlock().
Referenced by getActiveModeActivityTimeSecSince(), and hasSetActivityTime().
const char* ArServerMode::getExtendedStatus (void) const inline
Gets a string representing the extended status of the mode we're in.
References getActiveModeExtendedStatusString(), getActiveModeModeString(), getActiveModeStatusString(), and myExtendedStatus.
Referenced by getActiveModeExtendedStatusString(), and ArServerInfoRobot::userTask().
ArServerModeIdle * ArServerMode::getIdleMode (void) static
Call that gets our idle mode.
References ourIdleMode.
Referenced by remSingleShotPostDeactivateCallback().
ArServerMode * ArServerMode::getLastActiveMode () protected
References ourLastActiveMode.
const char* ArServerMode::getMode (void) const inline
Gets a string representing the mode we're in.
References myMode.
Referenced by getActiveModeModeString(), ArServerInfoRobot::update(), and ArServerInfoRobot::userTask().
void ArServerMode::getModeBusy (ArServerClient * client, ArNetPacket * packet) static
Handles the packet request for the mode busy state.
References ArBasePacket::byteToBuf(), ourIsBusy, and ArServerClient::sendPacketTcp().
Referenced by setStatus().
void ArServerMode::getModeDataList (ArServerClient * client, ArNetPacket * packet) static
Gets the list of data for each mode.
This returns the list of which data is in which mode.
References ArMutex::lock(), ourModeDataMap, ourModeDataMapMutex, ArServerClient::sendPacketTcp(), ArBasePacket::strToBuf(), ArBasePacket::uByte4ToBuf(), and ArMutex::unlock().
Referenced by setStatus().
void ArServerMode::getModeInfo (ArServerClient * client, ArNetPacket * packet) static
Gets the info about which mode is active and such.
This will get the info about the current active mode.
References buildModeInfoPacket(), and ArServerClient::sendPacketTcp().
Referenced by setStatus().
const char* ArServerMode::getName (void) const inline
Gets the name of the mode we're in.
References myName.
Referenced by addAsDefaultMode(), baseActivate(), baseDeactivate(), buildModeInfoPacket(), forceUnlock(), ArServerModeJogPosition::heading(), ArServerModeDrive::joyUserTask(), ArServerModeRatioDrive::joyUserTask(), lockMode(), ArServerModeJogPosition::move(), ArServerModeRatioDrive::ratioDrive(), ArServerModeJogPosition::serverHeading(), ArServerModeJogPosition::serverMove(), ArServerModeRatioDrive::serverRatioDrive(), ArServerModeJogPosition::serverTurn(), ArServerModeJogPosition::stringCmdHeading(), ArServerModeJogPosition::stringCmdMove(), ArServerModeJogPosition::stringCmdTurn(), ArServerModeJogPosition::turn(), and unlockMode().
std::list< ArServerMode * > * ArServerMode::getRequestedActivateModes (void) static protected
References ourRequestedActivateModes.
Referenced by remSingleShotPostDeactivateCallback().
const char* ArServerMode::getStatus (void) const inline
Gets a string representing the status of the mode we're in.
References myStatus.
Referenced by getActiveModeStatusString(), ArServerInfoRobot::update(), and ArServerInfoRobot::userTask().
bool ArServerMode::hasSetActivityTime (void) inline
Gets if we've set our activity time.
References addAsDefaultMode(), getActiveModeActivityTimeSecSince(), getActiveModeSetActivityThisCycle(), getActivityTime(), ArListPos::LAST, myHasSetActivityTime, and setActivityTimeToNow().
void ArServerMode::internalSetActivityTime (ArTime time)
Internal call to set the activity time (this is dangerous and shouldn't be used)
References ArMutex::lock(), myActivityTime, myActivityTimeMutex, myHasSetActivityTime, mySetActivityThisCycle, and ArMutex::unlock().
Referenced by remSingleShotPostDeactivateCallback().
bool ArServerMode::isActive (void) const inline
Gets if this mode is active or not.
References getActiveMode(), isLocked(), myIsActive, and willUnlockIfRequested().
Referenced by ArServerModeStop::activate(), ArServerModeIdle::activate(), ArServerModeJogPosition::activate(), ArServerModeDrive::driveJoystick(), ArServerModeJogPosition::heading(), ArServerModeDrive::joyUserTask(), ArServerModeRatioDrive::joyUserTask(), ArServerModeJogPosition::move(), ArServerModeRatioDrive::ratioDrive(), ArServerModeDrive::serverDriveJoystick(), ArServerModeRatioDrive::serverRatioDrive(), ArServerModeDrive::setSafeDriving(), ArServerModeRatioDrive::setSafeDriving(), and ArServerModeJogPosition::turn().
bool ArServerMode::isAutoResumeAfterInterrupt () virtual
Adds data to the list of this mode's commands.
Returns whether the mode should be automatically resumed after it was interrupted This method primarily applies when the mode has been interrupted by a forced docking situation. In that case, when the docking mode is complete, it will resume the interrupted mode – if this method returns true. This would primarily be applicable to very long, complex modes.
The default return value is false.
Referenced by setStatus().
bool ArServerMode::isLocked (void) static
Gets if the active mode is locked or not.
References ourActiveMode, and ourActiveModeLocked.
Referenced by isActive().
void ArServerMode::lockMode (bool willUnlockIfRequested = false)
Locks this mode in until its unlocked (mode must be the active mode)
References checkBroadcastModeInfoPacket(), ArUtil::convertBool(), getName(), ArLog::log(), myIsActive, myVerboseLogLevel, ourActiveMode, ourActiveModeLocked, ourActiveModeWillUnlockIfRequested, and willUnlockIfRequested().
Referenced by requestUnlock().
void ArServerMode::modeUserTask (void) static protected
References ArServerBase::broadcastPacketTcp(), ArBasePacket::byteToBuf(), getActiveModeActivityTimeSecSince(), ArLog::log(), mySetActivityThisCycle, ArLog::Normal, ourActiveMode, ourActiveModeSetActivityThisCycle, ourDefaultModes, ourIsBusy, ourServerBase, ArLog::Terse, and userTask().
Referenced by remSingleShotPostDeactivateCallback().
void ArServerMode::remActivateCallback (ArFunctor * functor) inline
Removes a callback for when this class is activated.
References myActivateCallbacks, and ArGenericCallbackList< ArFunctor * >::remCallback().
void ArServerMode::remDeactivateCallback (ArFunctor * functor) inline
Removes a callback for when this class is deactivated.
References myDeactivateCallbacks, and ArGenericCallbackList< ArFunctor * >::remCallback().
void ArServerMode::remSingleShotDeactivateCallback (ArFunctor * functor) inline
Removes a single shot callback for when this class is deactivated.
References mySingleShotDeactivateCallbacks, and ArGenericCallbackList< ArFunctor * >::remCallback().
void ArServerMode::remSingleShotPostDeactivateCallback (ArFunctor * functor) inline
Removes a single shot callback for just after the deactivate happens (when the next mode has activated)
References baseActivate(), baseDeactivate(), buildModeInfoPacket(), checkBroadcastModeInfoPacket(), getIdleMode(), getRequestedActivateModes(), internalSetActivityTime(), modeUserTask(), mySingleShotPostDeactivateCallbacks, and ArGenericCallbackList< ArFunctor * >::remCallback().
virtual void ArServerMode::requestUnlock (void) inline virtual
This will be called if another mode wants the lock broken (can ignore)
References forceUnlock(), lockMode(), unlockMode(), and willUnlockIfRequested().
Referenced by baseActivate().
void ArServerMode::setActivityTimeToNow (void)
Sets that we're active right now.
References ArMutex::lock(), myActivityTime, myActivityTimeMutex, myHasSetActivityTime, mySetActivityThisCycle, ArTime::setToNow(), and ArMutex::unlock().
Referenced by ArServerModeStop::activate(), ArServerModeWander::activate(), ArServerModeIdle::activate(), ArServerModeDrive::driveJoystick(), hasSetActivityTime(), ArServerModeJogPosition::heading(), ArServerModeJogPosition::move(), ArServerModeStop::netStop(), ArServerModeWander::netWander(), ArServerModeRatioDrive::ratioDrive(), ArServerModeJogPosition::turn(), ArServerModeStop::userTask(), ArServerModeWander::userTask(), ArServerModeIdle::userTask(), ArServerModeDrive::userTask(), and ArServerModeRatioDrive::userTask().
void ArServerMode::setMode (const char * str) inline
This should only be used by careful people and probably not then.
References myMode.
void ArServerMode::setStatus (const char * str) inline
This should only be used by careful people and probably not then.
This changes the status of the mode and sets the myStatusSetThisCycle to true. If the mode inheriting is setting the status in cycles then it should use this status instead and then clear the myStatusSetThisFlag to false.
References addModeData(), client, getModeBusy(), getModeDataList(), getModeInfo(), isAutoResumeAfterInterrupt(), myStatus, and myStatusSetThisCycle.
void ArServerMode::unlockMode (void)
Unlocks the mode so other modes can activate.
References activate(), checkBroadcastModeInfoPacket(), getName(), ArLog::log(), myIsActive, myVerboseLogLevel, ArLog::Normal, ourActiveMode, ourActiveModeLocked, ourActiveModeWillUnlockIfRequested, ourIdleMode, ourNextActiveMode, and ourRequestedActivateModes.
Referenced by baseDeactivate(), forceUnlock(), and requestUnlock().
virtual void ArServerMode::userTask (void) inline virtual
The ArMode's user task, don't need one, subclass must provide if needed.
Reimplemented in ArServerModeRatioDrive, ArServerModeDrive, ArServerModeIdle, ArServerModeWander, and ArServerModeStop.
Referenced by modeUserTask().
bool ArServerMode::willUnlockIfRequested (void) static
Gets whether we'll unlock if requested or not.
References ourActiveMode, ourActiveModeLocked, and ourActiveModeWillUnlockIfRequested.
Referenced by isActive(), lockMode(), and requestUnlock().
Member Data Documentation
ArCallbackList ArServerMode::myActivateCallbacks protected
Referenced by addActivateCallback(), ArServerMode(), baseActivate(), and remActivateCallback().
ArTime ArServerMode::myActivityTime protected
Referenced by baseActivate(), getActivityTime(), internalSetActivityTime(), and setActivityTimeToNow().
ArMutex ArServerMode::myActivityTimeMutex protected
Referenced by ArServerMode(), baseActivate(), getActivityTime(), internalSetActivityTime(), and setActivityTimeToNow().
ArCallbackList ArServerMode::myDeactivateCallbacks protected
Referenced by addDeactivateCallback(), ArServerMode(), baseDeactivate(), and remDeactivateCallback().
std::string ArServerMode::myExtendedStatus protected
Referenced by getExtendedStatus().
bool ArServerMode::myHasSetActivityTime protected
Referenced by ArServerMode(), hasSetActivityTime(), internalSetActivityTime(), and setActivityTimeToNow().
bool ArServerMode::myIsActive protected
Referenced by ArServerMode(), baseActivate(), baseDeactivate(), isActive(), lockMode(), and unlockMode().
std::string ArServerMode::myMode protected
Referenced by ArServerModeJogPosition::activate(), ArServerModeIdle::ArServerModeIdle(), ArServerModeStop::ArServerModeStop(), ArServerModeWander::ArServerModeWander(), ArServerModeDrive::driveJoystick(), getMode(), ArServerModeRatioDrive::ratioDrive(), and setMode().
std::string ArServerMode::myName protected
Referenced by ArServerModeJogPosition::activate(), addModeData(), ArServerMode(), getName(), ArServerModeRatioDrive::joyUserTask(), ArServerModeRatioDrive::ratioDrive(), ArServerModeRatioDrive::setSafeDriving(), and ArServerModeRatioDrive::setUseLocationDependentDevices().
ArRobot* ArServerMode::myRobot protected
Referenced by ArServerModeStop::activate(), ArServerModeWander::activate(), ArServerModeIdle::activate(), ArServerModeJogPosition::activate(), ArServerMode(), ArServerModeDrive::ArServerModeDrive(), ArServerModeIdle::ArServerModeIdle(), ArServerModeJogPosition::ArServerModeJogPosition(), ArServerModeRatioDrive::ArServerModeRatioDrive(), ArServerModeStop::ArServerModeStop(), baseActivate(), ArServerModeJogPosition::deactivate(), ArServerModeDrive::driveJoystick(), ArServerModeJogPosition::heading(), ArServerModeRatioDrive::joyUserTask(), ArServerModeJogPosition::move(), ArServerModeStop::netStop(), ArServerModeWander::netWander(), ArServerModeRatioDrive::ratioDrive(), ArServerModeDrive::serverDriveJoystick(), ArServerModeRatioDrive::serverRatioDrive(), ArServerModeDrive::serverSafeDrivingDisable(), ArServerModeDrive::serverSafeDrivingEnable(), ArServerModeRatioDrive::setSafeDriving(), ArServerModeStop::setUseLocationDependentDevices(), ArServerModeIdle::setUseLocationDependentDevices(), ArServerModeRatioDrive::setUseLocationDependentDevices(), ArServerModeJogPosition::turn(), ArServerModeStop::userTask(), ArServerModeWander::userTask(), ArServerModeIdle::userTask(), ArServerModeDrive::userTask(), and ArServerModeRatioDrive::userTask().
ArServerBase* ArServerMode::myServer protected
Referenced by addModeData(), ArServerMode(), ArServerModeDrive::ArServerModeDrive(), ArServerModeJogPosition::ArServerModeJogPosition(), ArServerModeRatioDrive::ArServerModeRatioDrive(), ArServerModeStop::ArServerModeStop(), ArServerModeWander::ArServerModeWander(), baseActivate(), checkBroadcastModeInfoPacket(), and ArServerModeIdle::userTask().
bool ArServerMode::mySetActivityThisCycle protected
Referenced by ArServerMode(), internalSetActivityTime(), modeUserTask(), and setActivityTimeToNow().
ArCallbackList ArServerMode::mySingleShotDeactivateCallbacks protected
Referenced by addSingleShotDeactivateCallback(), ArServerMode(), baseDeactivate(), and remSingleShotDeactivateCallback().
ArCallbackList ArServerMode::mySingleShotPostDeactivateCallbacks protected
Referenced by addSingleShotPostDeactivateCallback(), ArServerMode(), baseDeactivate(), and remSingleShotPostDeactivateCallback().
std::string ArServerMode::myStatus protected
Referenced by ArServerModeStop::activate(), ArServerModeWander::activate(), ArServerModeIdle::ArServerModeIdle(), getStatus(), ArServerModeJogPosition::heading(), ArServerModeJogPosition::move(), setStatus(), ArServerModeJogPosition::turn(), ArServerModeStop::userTask(), ArServerModeIdle::userTask(), ArServerModeDrive::userTask(), and ArServerModeRatioDrive::userTask().
bool ArServerMode::myStatusSetThisCycle protected
Referenced by ArServerMode(), setStatus(), ArServerModeDrive::userTask(), and ArServerModeRatioDrive::userTask().
ArLog::LogLevel ArServerMode::myVerboseLogLevel protected
Referenced by ArServerMode(), baseActivate(), baseDeactivate(), lockMode(), and unlockMode().
ArServerMode * ArServerMode::ourActiveMode = NULL static protected
Referenced by baseActivate(), baseDeactivate(), buildModeInfoPacket(), checkBroadcastModeInfoPacket(), getActiveMode(), getActiveModeActivityTimeSecSince(), getActiveModeExtendedStatusString(), getActiveModeModeString(), getActiveModeStatusString(), isLocked(), ArServerModeRatioDrive::joyUserTask(), lockMode(), modeUserTask(), unlockMode(), and willUnlockIfRequested().
bool ArServerMode::ourActiveModeLocked = false static protected
Referenced by baseActivate(), baseDeactivate(), buildModeInfoPacket(), checkBroadcastModeInfoPacket(), isLocked(), ArServerModeRatioDrive::joyUserTask(), lockMode(), unlockMode(), and willUnlockIfRequested().
bool ArServerMode::ourActiveModeSetActivityThisCycle = false static protected
Referenced by getActiveModeSetActivityThisCycle(), and modeUserTask().
bool ArServerMode::ourActiveModeWillUnlockIfRequested = false static protected
Referenced by buildModeInfoPacket(), checkBroadcastModeInfoPacket(), lockMode(), unlockMode(), and willUnlockIfRequested().
ArServerMode * ArServerMode::ourBroadcastActiveMode = NULL static protected
Referenced by checkBroadcastModeInfoPacket().
bool ArServerMode::ourBroadcastActiveModeLocked = false static protected
Referenced by checkBroadcastModeInfoPacket().
bool ArServerMode::ourBroadcastActiveModeWillUnlockIfRequested = false static protected
Referenced by checkBroadcastModeInfoPacket().
std::list< ArServerMode * > ArServerMode::ourDefaultModes static protected
Referenced by addAsDefaultMode(), baseDeactivate(), and modeUserTask().
ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ArServerMode::ourGetModeBusyCB static protected
Referenced by ArServerMode().
ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ArServerMode::ourGetModeDataListCB static protected
Referenced by ArServerMode().
ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ArServerMode::ourGetModeInfoCB static protected
Referenced by ArServerMode().
ArServerModeIdle * ArServerMode::ourIdleMode = NULL static protected
Referenced by ArServerMode(), baseActivate(), baseDeactivate(), getIdleMode(), and unlockMode().
bool ArServerMode::ourIdleModeCreated = false static protected
Referenced by ArServerMode().
ArMutex ArServerMode::ourIdleModeMutex static protected
Referenced by ArServerMode().
bool ArServerMode::ourIsBusy = false static protected
Referenced by getModeBusy(), and modeUserTask().
ArServerMode * ArServerMode::ourLastActiveMode = NULL static protected
Referenced by baseActivate(), baseDeactivate(), and getLastActiveMode().
std::multimap< std::string, std::string > ArServerMode::ourModeDataMap static protected
Referenced by addModeData(), and getModeDataList().
ArMutex ArServerMode::ourModeDataMapMutex static protected
Referenced by addModeData(), ArServerMode(), and getModeDataList().
std::list< ArServerMode * > ArServerMode::ourModes static protected
Referenced by ArServerMode().
ArServerMode * ArServerMode::ourNextActiveMode = NULL static protected
Referenced by baseActivate(), baseDeactivate(), and unlockMode().
std::list< ArServerMode * > ArServerMode::ourRequestedActivateModes static protected
Referenced by baseActivate(), baseDeactivate(), getRequestedActivateModes(), and unlockMode().
ArServerBase * ArServerMode::ourServerBase = NULL static protected
Referenced by ArServerMode(), and modeUserTask().
bool ArServerMode::ourUserTaskAdded = false static protected
Referenced by ArServerMode().
ArGlobalFunctor ArServerMode::ourUserTaskCB static protected
Referenced by ArServerMode().
The documentation for this class was generated from the following files:
ArServerMode.h
ArServerMode.cpp