ArNetworking: ArServerSimpleComUC Class Reference
ArServerSimpleComUC Class Reference
Class for sending commands to the microcontroller (uC)
#include <ArServerSimpleCommands.h>
Public Member Functions
ArServerSimpleComUC (ArServerHandlerCommands *handlerCommands, ArRobot *robot)
Constructor.
void command (ArArgumentBuilder *arg)
Handles the command.
void motionCommand (ArArgumentBuilder *arg)
Handles the motor commands.
virtual ~ArServerSimpleComUC ()
Destructor.
Protected Member Functions
void processCommand (ArArgumentBuilder *arg, bool motionCommand)
Protected Attributes
ArFunctor1C
< ArServerSimpleComUC,
ArArgumentBuilder * > myCommandCB
ArServerHandlerCommands * myHandlerCommands
ArFunctor1C
< ArServerSimpleComUC,
ArArgumentBuilder * > myMotionCommandCB
ArRobot * myRobot
Detailed Description
Class for sending commands to the microcontroller (uC)
This class will let you send commands to the microcontroller (com, comInt, and com2Bytes).
Examples:
serverDemo.cpp, and simpleServerExample.cpp.
Constructor & Destructor Documentation
ArServerSimpleComUC::ArServerSimpleComUC (ArServerHandlerCommands * handlerCommands, ArRobot * robot)
Constructor.
References ArServerHandlerCommands::addStringCommand(), myCommandCB, myHandlerCommands, myMotionCommandCB, and myRobot.
ArServerSimpleComUC::~ArServerSimpleComUC () [virtual]
Destructor.
Member Function Documentation
void ArServerSimpleComUC::command (ArArgumentBuilder * arg)
Handles the command.
References processCommand().
Referenced by processCommand().
void ArServerSimpleComUC::motionCommand (ArArgumentBuilder * arg)
Handles the motor commands.
References processCommand().
void ArServerSimpleComUC::processCommand (ArArgumentBuilder * arg, bool motionCommand) [protected]
References ArRobot::clearDirectMotion(), ArRobot::com(), ArRobot::com2Bytes(), ArRobot::comInt(), command(), ArArgumentBuilder::getArgc(), ArArgumentBuilder::getArgInt(), ArArgumentBuilder::getFullString(), ArArgumentBuilder::isArgInt(), ArRobot::lock(), ArLog::log(), myRobot, ArRobot::stop(), ArRobot::stopStateReflection(), ArLog::Terse, and ArRobot::unlock().
Referenced by command(), and motionCommand().
Member Data Documentation
ArFunctor1C<ArServerSimpleComUC, ArArgumentBuilder *> ArServerSimpleComUC::myCommandCB [protected]
Referenced by ArServerSimpleComUC().
ArServerHandlerCommands* ArServerSimpleComUC::myHandlerCommands [protected]
Referenced by ArServerSimpleComUC().
ArFunctor1C<ArServerSimpleComUC, ArArgumentBuilder *> ArServerSimpleComUC::myMotionCommandCB [protected]
Referenced by ArServerSimpleComUC().
ArRobot* ArServerSimpleComUC::myRobot [protected]
Referenced by ArServerSimpleComUC(), and processCommand().
The documentation for this class was generated from the following files:
ArServerSimpleCommands.h
ArServerSimpleCommands.cpp