ArNetworking: ArNetPacketReceiverTcp Class Reference
ArNetPacketReceiverTcp Class Reference
This class receives TCP packets from a socket, you need to have an open socket and give it to the socket with setSocket, then you need to set up a callback to process packets with setProcessPacketCB, finally call readData which will read in all the data and call the processPacketCB.
#include <ArNetPacketReceiverTcp.h>
Public Member Functions
ArNetPacketReceiverTcp ()
Constructor.
ArFunctor1< ArNetPacket * > * getProcessPacketCB (void)
Gets the callback used when a packet is received.
bool getQuiet (void)
Gets whether we're quiet about errors or not.
ArSocket * getSocket (void)
Gets the socket this receiver uses.
bool readData (void)
Reads in all the data available calling the processPacketCB.
void setLoggingPrefix (const char *loggingPrefix)
Sets the logging prefix.
void setProcessPacketCB (ArFunctor1< ArNetPacket * > *functor)
Sets the callback for use when a packet is received.
void setQuiet (bool quiet)
Sets whether we're quiet about errors or not.
void setSocket (ArSocket *socket)
Sets the socket this receiver uses.
~ArNetPacketReceiverTcp ()
Destructor.
Protected Types
enum { TOTAL_PACKET_LENGTH = ArNetPacket::MAX_LENGTH+ArNetPacket::HEADER_LENGTH+ArNetPacket::FOOTER_LENGTH }
enum Ret {
RET_CONN_CLOSED, RET_CONN_ERROR, RET_GOT_PACKET, RET_BAD_PACKET,
RET_FAILED_READ, RET_TIMED_OUT
}
enum State {
STATE_SYNC1, STATE_SYNC2, STATE_LENGTH1, STATE_LENGTH2,
STATE_ACQUIRE_DATA
}
Protected Member Functions
Ret readPacket (int msWait)
Reads in a single packet, returns NULL if not one.
Protected Attributes
ArTime myLastPacket
std::string myLoggingPrefix
ArNetPacket myPacket
ArFunctor1< ArNetPacket * > * myProcessPacketCB
bool myQuiet
char myReadBuff [TOTAL_PACKET_LENGTH]
int myReadCommand
int myReadCount
int myReadLength
ArSocket * mySocket
State myState
unsigned char mySync1
unsigned char mySync2
Detailed Description
This class receives TCP packets from a socket, you need to have an open socket and give it to the socket with setSocket, then you need to set up a callback to process packets with setProcessPacketCB, finally call readData which will read in all the data and call the processPacketCB.
Member Enumeration Documentation
anonymous enum [protected]
Enumerator:
TOTAL_PACKET_LENGTH
enum ArNetPacketReceiverTcp::Ret [protected]
Enumerator:
RET_CONN_CLOSED
RET_CONN_ERROR
RET_GOT_PACKET
RET_BAD_PACKET
RET_FAILED_READ
RET_TIMED_OUT
enum ArNetPacketReceiverTcp::State [protected]
Enumerator:
STATE_SYNC1
STATE_SYNC2
STATE_LENGTH1
STATE_LENGTH2
STATE_ACQUIRE_DATA
Constructor & Destructor Documentation
ArNetPacketReceiverTcp::ArNetPacketReceiverTcp ()
Constructor.
References myReadBuff, and TOTAL_PACKET_LENGTH.
ArNetPacketReceiverTcp::~ArNetPacketReceiverTcp ()
Destructor.
Member Function Documentation
ArFunctor1< ArNetPacket * > * ArNetPacketReceiverTcp::getProcessPacketCB (void)
Gets the callback used when a packet is received.
Returns:
the callback used when a packet needs to be processed
References myProcessPacketCB.
bool ArNetPacketReceiverTcp::getQuiet (void) [inline]
Gets whether we're quiet about errors or not.
References myQuiet.
ArSocket * ArNetPacketReceiverTcp::getSocket (void)
Gets the socket this receiver uses.
Gets the socket that the receiver is using, note that it does not have ownership of this socket and that whatever created it should.
References mySocket.
bool ArNetPacketReceiverTcp::readData (void)
Reads in all the data available calling the processPacketCB.
This reads in the available data in the TCP port so that packets can be fetched with getPacket.
If an error occurs that is unrecoverable false will be returned which means that the socket owner who is calling this should close the socket and clean up.
Returns:
false on an error that should cause the socket to be closed, true with no errors
References ArSocket::getIPString(), ArFunctor1< P1 >::invoke(), ArLog::log(), myLoggingPrefix, myPacket, myProcessPacketCB, myQuiet, mySocket, readPacket(), RET_BAD_PACKET, RET_CONN_CLOSED, RET_CONN_ERROR, RET_FAILED_READ, RET_GOT_PACKET, RET_TIMED_OUT, ArNetPacket::setPacketSource(), ArNetPacket::TCP, and ArLog::Terse.
Referenced by ArClientBase::loopOnce(), and ArServerClient::tcpCallback().
ArNetPacketReceiverTcp::Ret ArNetPacketReceiverTcp::readPacket (int msWait) [protected]
Reads in a single packet, returns NULL if not one.
References ArTime::addMSec(), ArBasePacket::dataToBuf(), ArNetPacket::empty(), ArSocket::getBadRead(), ArNetPacket::getCommand(), ArBasePacket::getFooterLength(), ArBasePacket::getHeaderLength(), ArLog::log(), ArNetPacket::MAX_LENGTH, ArTime::mSecTo(), myLoggingPrefix, myPacket, myQuiet, myReadBuff, myReadCount, myReadLength, mySocket, myState, mySync1, mySync2, ArLog::Normal, ArSocket::read(), ArNetPacket::resetRead(), RET_BAD_PACKET, RET_CONN_CLOSED, RET_CONN_ERROR, RET_FAILED_READ, RET_GOT_PACKET, RET_TIMED_OUT, ArBasePacket::setLength(), ArTime::setToNow(), STATE_ACQUIRE_DATA, STATE_LENGTH1, STATE_LENGTH2, STATE_SYNC1, STATE_SYNC2, ArLog::Terse, ArBasePacket::uByteToBuf(), ArLog::Verbose, and ArNetPacket::verifyCheckSum().
Referenced by readData().
void ArNetPacketReceiverTcp::setLoggingPrefix (const char * loggingPrefix)
Sets the logging prefix.
References myLoggingPrefix.
Referenced by ArServerClient::ArServerClient(), and ArClientBase::setRobotName().
void ArNetPacketReceiverTcp::setProcessPacketCB (ArFunctor1< ArNetPacket * > * functor)
Sets the callback for use when a packet is received.
Parameters:
functor the callback to use when a packet needs to be processed
References myProcessPacketCB.
Referenced by ArClientBase::ArClientBase(), ArServerClient::ArServerClient(), and ArServerClient::~ArServerClient().
void ArNetPacketReceiverTcp::setQuiet (bool quiet) [inline]
Sets whether we're quiet about errors or not.
References myQuiet.
Referenced by ArClientBase::internalNonBlockingConnectStart().
void ArNetPacketReceiverTcp::setSocket (ArSocket * socket)
Sets the socket this receiver uses.
Sets the socket that this receiver will use, note that it does not transfer ownership of the socket.
Parameters:
socket the socket to use for receiving data
References mySocket.
Referenced by ArClientBase::ArClientBase(), ArServerClient::ArServerClient(), and ArServerClient::~ArServerClient().
Member Data Documentation
ArTime ArNetPacketReceiverTcp::myLastPacket [protected]
std::string ArNetPacketReceiverTcp::myLoggingPrefix [protected]
Referenced by readData(), readPacket(), and setLoggingPrefix().
ArNetPacket ArNetPacketReceiverTcp::myPacket [protected]
Referenced by readData(), and readPacket().
ArFunctor1<ArNetPacket *>* ArNetPacketReceiverTcp::myProcessPacketCB [protected]
Referenced by getProcessPacketCB(), readData(), and setProcessPacketCB().
bool ArNetPacketReceiverTcp::myQuiet [protected]
Referenced by getQuiet(), readData(), readPacket(), and setQuiet().
char ArNetPacketReceiverTcp::myReadBuff[TOTAL_PACKET_LENGTH] [protected]
Referenced by ArNetPacketReceiverTcp(), and readPacket().
int ArNetPacketReceiverTcp::myReadCommand [protected]
int ArNetPacketReceiverTcp::myReadCount [protected]
Referenced by readPacket().
int ArNetPacketReceiverTcp::myReadLength [protected]
Referenced by readPacket().
ArSocket* ArNetPacketReceiverTcp::mySocket [protected]
Referenced by getSocket(), readData(), readPacket(), and setSocket().
State ArNetPacketReceiverTcp::myState [protected]
Referenced by readPacket().
unsigned char ArNetPacketReceiverTcp::mySync1 [protected]
Referenced by readPacket().
unsigned char ArNetPacketReceiverTcp::mySync2 [protected]
Referenced by readPacket().
The documentation for this class was generated from the following files:
ArNetPacketReceiverTcp.h
ArNetPacketReceiverTcp.cpp