ArNetworking: clientStringInfoExample.cpp File Reference
clientStringInfoExample.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
#include "ArClientHandlerRobotUpdate.h"
#include <string>
#include <vector>
#include <assert.h>
Classes
struct Item
Functions
void handleStringsData (ArNetPacket *)
void handleStringsInfo (ArNetPacket *)
int main (int argc, char **argv)
Variables
ArClientBase client
std::vector< struct Item > data
ArMutex dataMutex
bool go = false
Function Documentation
void handleStringsData (ArNetPacket * pkt)
References ArBasePacket::bufToString(), data, ArMutex::lock(), and ArMutex::unlock().
Referenced by main().
void handleStringsInfo (ArNetPacket * pkt)
References ArBasePacket::bufToString(), ArBasePacket::bufToUByte2(), data, go, ArMutex::lock(), Item::name, ArClientBase::request(), and ArMutex::unlock().
Referenced by main().
int main (int argc, char ** argv)
References ArClientBase::addHandler(), ArArgumentParser::checkHelpAndWarnUnparsed(), ArClientSimpleConnector::connectClient(), data, ArClientBase::disconnect(), Aria::exit(), ArClientBase::getHost(), ArClientHandlerRobotUpdate::getLatVel(), ArClientHandlerRobotUpdate::getMode(), ArClientHandlerRobotUpdate::getRotVel(), ArThread::getRunningWithLock(), ArClientHandlerRobotUpdate::getStatus(), ArClientHandlerRobotUpdate::getTh(), ArClientHandlerRobotUpdate::getVel(), ArClientHandlerRobotUpdate::getVoltage(), ArClientHandlerRobotUpdate::getX(), ArClientHandlerRobotUpdate::getY(), go, handleStringsData(), handleStringsInfo(), Aria::init(), ArArgumentParser::loadDefaultArguments(), ArMutex::lock(), ArClientHandlerRobotUpdate::lock(), Aria::logOptions(), Aria::parseArgs(), ArClientBase::requestOnce(), ArClientHandlerRobotUpdate::requestUpdates(), ArClientBase::runAsync(), ArClientBase::setRobotName(), ArUtil::sleep(), ArMutex::unlock(), ArClientHandlerRobotUpdate::unlock(), and ArClientBase::wasRejected().
Variable Documentation
ArClientBase client
std::vector<struct Item> data
Referenced by ArServerClient::broadcastPacketTcp(), ArServerClient::broadcastPacketUdp(), ArServerClient::getFrequency(), ArServerClient::handleRequests(), handleStringsData(), handleStringsInfo(), ArClientHandlerRobotUpdate::handleUpdateNumbers(), ArClientHandlerRobotUpdate::handleUpdateOld(), ArServerBase::internalSetDefaultFrequency(), main(), md5_append(), md5_finish(), md5_process(), ArServerClient::processPacket(), and ArServerClient::~ArServerClient().
ArMutex dataMutex
bool go = false
Referenced by handleStringsInfo(), and main().