ArNetworking: clientDemo.cpp File Reference
clientDemo.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
#include "ArClientRatioDrive.h"
Classes
class InputHandler
class OutputHandler
This class requests continual data updates from the server and prints them out.
Macros
#define VEL_AMOUNT 50
Functions
void escape (void)
int main (int argc, char **argv)
Macro Definition Documentation
#define VEL_AMOUNT 50
Referenced by InputHandler::down(), InputHandler::lateralLeft(), InputHandler::lateralRight(), InputHandler::left(), InputHandler::right(), and InputHandler::up().
Function Documentation
void escape (void)
References Aria::shutdown().
Referenced by main().
int main (int argc, char ** argv)
References ArKeyHandler::addKeyHandler(), ArArgumentParser::checkHelpAndWarnUnparsed(), ArKeyHandler::checkKeys(), client, ArClientSimpleConnector::connectClient(), ArClientBase::dataExists(), ArClientBase::disconnect(), ArKeyHandler::ESCAPE, escape(), Aria::exit(), ArClientBase::getHost(), ArThread::getRunningWithLock(), Aria::init(), ArArgumentParser::loadDefaultArguments(), Aria::logOptions(), Aria::parseArgs(), ArClientBase::runAsync(), InputHandler::safeDrive(), Aria::setKeyHandler(), ArClientBase::setRobotName(), ArUtil::sleep(), and ArClientBase::wasRejected().