ArNetworking: configServerRobot.cpp File Reference
configServerRobot.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References configHandler, Aria::getConfig(), Aria::init(), ArServerBase::open(), ArServerBase::run(), and Aria::shutdown().