ArNetworking: configClientToServer.cpp File Reference
configClientToServer.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
Functions
void gotConfig (void)
int main (int argc, char **argv)
void saveConfigFailed (const char *str)
void saveConfigSucceeded (void)
Variables
ArClientBase * client
ArClientHandlerConfig * configHandler
char * file
Function Documentation
void gotConfig (void)
References ArClientBase::disconnect(), file, ArClientHandlerConfig::getConfig(), ArClientBase::loopOnce(), ArConfig::parseFile(), ArClientHandlerConfig::saveConfigToServer(), Aria::shutdown(), and ArUtil::sleep().
Referenced by main().
int main (int argc, char ** argv)
References ArClientHandlerConfig::addGotConfigCB(), ArClientHandlerConfig::addSaveConfigFailedCB(), ArClientHandlerConfig::addSaveConfigSucceededCB(), ArClientBase::blockingConnect(), file, gotConfig(), Aria::init(), ArClientHandlerConfig::requestConfigFromServer(), ArClientBase::run(), saveConfigFailed(), and saveConfigSucceeded().
void saveConfigFailed (const char * str)
Referenced by main().
void saveConfigSucceeded (void)
Referenced by main().
Variable Documentation
ArClientBase* client
ArClientHandlerConfig* configHandler
char* file
Examples:
getVideoExample.cpp.
Referenced by ArServerFileToClient::doGetFile(), gotConfig(), ArServerFileFromClient::internalPutFile(), jpegHandler(), ArServerBase::logCommandGroupsToFile(), ArServerBase::logGroupDescriptionsToFile(), main(), and ArClientFileFromClient::putFileToDirectory().