ArNetworking: drawingsExampleWithRobot.cpp File Reference
drawingsExampleWithRobot.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
#include <math.h>
Functions
void exampleArrowsDrawingNetCallback (ArServerClient *client, ArNetPacket *requestPkt)
void exampleDotsDrawingNetCallback (ArServerClient *client, ArNetPacket *requestPkt)
void exampleHomeDrawingNetCallback (ArServerClient *client, ArNetPacket *requestPkt)
void exampleXDrawingNetCallback (ArServerClient *client, ArNetPacket *requestPkt)
int main (int argc, char **argv)
Function Documentation
void exampleArrowsDrawingNetCallback (ArServerClient * client, ArNetPacket * requestPkt)
Examples:
drawingsExampleWithRobot.cpp.
References ArBasePacket::byte4ToBuf(), and ArServerClient::sendPacketUdp().
Referenced by main().
void exampleDotsDrawingNetCallback (ArServerClient * client, ArNetPacket * requestPkt)
Examples:
drawingsExampleWithRobot.cpp.
References ArBasePacket::byte4ToBuf(), ArUtil::getTime(), ArServerClient::sendPacketUdp(), and sin().
Referenced by main().
void exampleHomeDrawingNetCallback (ArServerClient * client, ArNetPacket * requestPkt)
Examples:
drawingsExampleWithRobot.cpp.
References ArBasePacket::byte4ToBuf(), and ArServerClient::sendPacketUdp().
Referenced by main().
void exampleXDrawingNetCallback (ArServerClient * client, ArNetPacket * requestPkt)
Examples:
drawingsExampleWithRobot.cpp.
References ArBasePacket::byte4ToBuf(), and ArServerClient::sendPacketUdp().
Referenced by main().
int main (int argc, char ** argv)
Examples:
drawingsExampleWithRobot.cpp.
References ArServerModeStop::activate(), ArServerMode::addAsDefaultMode(), ArUtil::addDirectories(), ArServerInfoDrawings::addDrawing(), ArRobot::addRangeDevice(), ArServerInfoDrawings::addRobotsRangeDevices(), ArRobot::attachKeyHandler(), ArServerSimpleOpener::checkAndLog(), ArArgumentParser::checkHelpAndWarnUnparsed(), ArSimpleConnector::connectLaser(), ArSimpleConnector::connectRobot(), ArRobot::enableMotors(), exampleArrowsDrawingNetCallback(), exampleDotsDrawingNetCallback(), exampleHomeDrawingNetCallback(), exampleXDrawingNetCallback(), Aria::getDirectory(), Aria::getKeyHandler(), Aria::init(), ArArgumentParser::loadDefaultArguments(), ArRobot::lock(), ArSimpleConnector::logOptions(), ArServerSimpleOpener::logOptions(), ArServerSimpleOpener::open(), ArSimpleConnector::parseArgs(), ArServerSimpleOpener::parseArgs(), ArRangeDeviceThreaded::runAsync(), ArRobot::runAsync(), ArServerBase::runAsync(), Aria::setKeyHandler(), ArSimpleConnector::setupLaser(), Aria::shutdown(), ArRobot::unlock(), ArRobot::waitForRunExit(), and ArServerSimpleOpener::wasUserFileBad().