ArNetworking: getVideoExample.cpp File Reference
getVideoExample.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
Functions
void jpegHandler (ArNetPacket *packet)
int main (int argc, char **argv)
Variables
unsigned long counter = 1
double rate = 0
int rateAsTime = 0
bool useCounter = false
Function Documentation
void jpegHandler (ArNetPacket * packet)
Examples:
getVideoExample.cpp.
References ArBasePacket::bufToData(), ArBasePacket::bufToUByte2(), counter, Aria::exit(), file, ArUtil::fopen(), ArBasePacket::getDataLength(), ArBasePacket::getDataReadLength(), ArLog::log(), ArLog::Normal, rate, rateAsTime, and useCounter.
Referenced by main().
int main (int argc, char ** argv)
Examples:
getVideoExample.cpp.
References ArClientBase::addHandler(), ArArgumentParser::checkArgument(), ArArgumentParser::checkHelpAndWarnUnparsed(), ArArgumentParser::checkParameterArgumentDouble(), client, ArClientSimpleConnector::connectClient(), ArDaemonizer::daemonize(), ArClientBase::dataExists(), Aria::exit(), ArLog::File, Aria::init(), ArLog::init(), ArDaemonizer::isDaemonized(), jpegHandler(), ArArgumentParser::loadDefaultArguments(), ArLog::log(), Aria::logOptions(), ArLog::Normal, Aria::parseArgs(), rate, rateAsTime, ArClientBase::request(), ArClientBase::requestOnce(), ArMath::roundInt(), ArClientBase::run(), Aria::shutdown(), ArLog::Terse, and useCounter.
Variable Documentation
unsigned long counter = 1
Examples:
getVideoExample.cpp.
Referenced by jpegHandler().
double rate = 0
Examples:
getVideoExample.cpp.
Referenced by jpegHandler(), and main().
int rateAsTime = 0
Examples:
getVideoExample.cpp.
Referenced by jpegHandler(), and main().
bool useCounter = false
Examples:
getVideoExample.cpp.
Referenced by jpegHandler(), and main().