ArNetworking: ptzCameraClientExample.cpp File Reference
ptzCameraClientExample.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
#include <math.h>
Classes
class ArClientHandlerCamera
Includes callbacks for receiving info and data packets from a camera server and storing the values parsed from them.
class ArNetCameraRequest
A request packet that is able to send a copy of itself, with data packed in, to a server.
class PtzCameraExample
Requests a list of cameras if neccesary, maintains a list of cameras, and implements example pan/tilt movements.
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Examples:
ptzCameraClientExample.cpp.
References ArArgumentParser::checkHelpAndWarnUnparsed(), client, ArClientSimpleConnector::connectClient(), ArClientBase::getHost(), Aria::init(), PtzCameraExample::init(), ArArgumentParser::loadDefaultArguments(), ArLog::log(), Aria::logOptions(), Aria::parseArgs(), PtzCameraExample::run(), ArClientBase::runAsync(), ArClientBase::setRobotName(), Aria::shutdown(), ArLog::Terse, and ArClientBase::wasRejected().