ArNetworking: robotUpdateExample.cpp File Reference
robotUpdateExample.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
#include "ArClientHandlerRobotUpdate.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Examples:
robotUpdateExample.cpp.
References ArArgumentParser::checkHelpAndWarnUnparsed(), client, ArClientSimpleConnector::connectClient(), ArClientBase::disconnect(), Aria::exit(), ArClientBase::getHost(), ArClientHandlerRobotUpdate::getLatVel(), ArClientHandlerRobotUpdate::getMode(), ArClientHandlerRobotUpdate::getRotVel(), ArThread::getRunningWithLock(), ArClientHandlerRobotUpdate::getStatus(), ArClientHandlerRobotUpdate::getTh(), ArClientHandlerRobotUpdate::getVel(), ArClientHandlerRobotUpdate::getVoltage(), ArClientHandlerRobotUpdate::getX(), ArClientHandlerRobotUpdate::getY(), Aria::init(), ArArgumentParser::loadDefaultArguments(), ArClientHandlerRobotUpdate::lock(), Aria::logOptions(), Aria::parseArgs(), ArClientHandlerRobotUpdate::requestUpdates(), ArClientBase::runAsync(), ArClientBase::setRobotName(), ArUtil::sleep(), ArClientHandlerRobotUpdate::unlock(), and ArClientBase::wasRejected().