ArNetworking: ArMapChanger::ClientChangeInfo Struct Reference
ArMapChanger::ClientChangeInfo Struct Reference
Accumulates the packet list that describes map changes received from a specified client.
#include <ArMapChanger.h>
Public Member Functions
void addPacket (ArNetPacket *packet)
Adds the given packet to the list.
ClientChangeInfo (ArServerClient *client)
Constructor for changes received from a client.
ClientChangeInfo (ArCentralForwarder *forwarder)
Constructor for changes received from a robot on the CS.
~ClientChangeInfo ()
Destructor.
Public Attributes
ArServerClient * myClient
Server client which sent the map changes...
ArCentralForwarder * myForwarder
Or the forwarder that sent the map changes.
ArTime myLastActivityTime
Time at which the most recent packet in this list was received.
std::list< ArNetPacket * > myPacketList
List of network packets received from the client for these map changes.
ArTime myStartTime
Time at which the first packet in this list was received.
Detailed Description
Accumulates the packet list that describes map changes received from a specified client.
Constructor & Destructor Documentation
ArMapChanger::ClientChangeInfo::ClientChangeInfo (ArServerClient * client)
Constructor for changes received from a client.
ArMapChanger::ClientChangeInfo::ClientChangeInfo (ArCentralForwarder * forwarder)
Constructor for changes received from a robot on the CS.
ArMapChanger::ClientChangeInfo::~ClientChangeInfo ()
Destructor.
References ArUtil::deleteSet(), and myPacketList.
Member Function Documentation
void ArMapChanger::ClientChangeInfo::addPacket (ArNetPacket * packet)
Adds the given packet to the list.
References ArNetPacket::duplicatePacket(), myPacketList, and ArNetPacket::resetRead().
Referenced by ArMapChanger::handleChangePacket().
Member Data Documentation
ArServerClient* ArMapChanger::ClientChangeInfo::myClient
Server client which sent the map changes...
Referenced by ArMapChanger::handleChangePacket().
ArCentralForwarder* ArMapChanger::ClientChangeInfo::myForwarder
Or the forwarder that sent the map changes.
ArTime ArMapChanger::ClientChangeInfo::myLastActivityTime
Time at which the most recent packet in this list was received.
Referenced by ArMapChanger::handleChangePacket().
std::list<ArNetPacket *> ArMapChanger::ClientChangeInfo::myPacketList
List of network packets received from the client for these map changes.
Referenced by addPacket(), ArMapChanger::handleChangePacket(), and ~ClientChangeInfo().
ArTime ArMapChanger::ClientChangeInfo::myStartTime
Time at which the first packet in this list was received.
The documentation for this struct was generated from the following files:
ArMapChanger.h
ArMapChanger.cpp