/*
Adept MobileRobots Robotics Interface for Applications (ARIA)
Copyright (C) 2004-2005 ActivMedia Robotics LLC
Copyright (C) 2006-2010 MobileRobots Inc.
Copyright (C) 2011-2014 Adept Technology

     This program is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

If you wish to redistribute ARIA under different terms, contact 
Adept MobileRobots for information about a commercial version of ARIA at 
robots@mobilerobots.com or 
Adept MobileRobots, 10 Columbia Drive, Amherst, NH 03031; +1-603-881-7960
*/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArNetPacketSenderTcp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArNetPacketSenderTcp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArNetPacketSenderTcp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArNetPacketSenderTcp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArNetPacketSenderTcp() {
    this(ArNetworkingJavaJNI.new_ArNetPacketSenderTcp(), true);
  }

  public void setSocket(ArSocket socket) {
    ArNetworkingJavaJNI.ArNetPacketSenderTcp_setSocket(swigCPtr, this, ArSocket.getCPtr(socket), socket);
  }

  public ArSocket getSocket() {
    long cPtr = ArNetworkingJavaJNI.ArNetPacketSenderTcp_getSocket(swigCPtr, this);
    return (cPtr == 0) ? null : new ArSocket(cPtr, false);
  }

  public void setBackupTimeout(double connectionTimeoutInMins) {
    ArNetworkingJavaJNI.ArNetPacketSenderTcp_setBackupTimeout(swigCPtr, this, connectionTimeoutInMins);
  }

  public void setDebugLogging(boolean debugLogging) {
    ArNetworkingJavaJNI.ArNetPacketSenderTcp_setDebugLogging(swigCPtr, this, debugLogging);
  }

  public void setLoggingPrefix(String prefix) {
    ArNetworkingJavaJNI.ArNetPacketSenderTcp_setLoggingPrefix(swigCPtr, this, prefix);
  }

  public void sendPacket(ArNetPacket packet, String loggingString) {
    ArNetworkingJavaJNI.ArNetPacketSenderTcp_sendPacket__SWIG_0(swigCPtr, this, ArNetPacket.getCPtr(packet), packet, loggingString);
  }

  public void sendPacket(ArNetPacket packet) {
    ArNetworkingJavaJNI.ArNetPacketSenderTcp_sendPacket__SWIG_1(swigCPtr, this, ArNetPacket.getCPtr(packet), packet);
  }

  public boolean sendData() {
    return ArNetworkingJavaJNI.ArNetPacketSenderTcp_sendData(swigCPtr, this);
  }

}
