/*
Adept MobileRobots Robotics Interface for Applications (ARIA)
Copyright (C) 2004-2005 ActivMedia Robotics LLC
Copyright (C) 2006-2010 MobileRobots Inc.
Copyright (C) 2011-2014 Adept Technology

     This program is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

If you wish to redistribute ARIA under different terms, contact 
Adept MobileRobots for information about a commercial version of ARIA at 
robots@mobilerobots.com or 
Adept MobileRobots, 10 Columbia Drive, Amherst, NH 03031; +1-603-881-7960
*/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArAction {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArAction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArAction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AriaJavaJNI.ArAction_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AriaJavaJNI.ArAction_change_ownership(this, swigCPtr, true);
  }

  public ArAction(String name, String description) {
    this(AriaJavaJNI.new_ArAction__SWIG_0(name, description), true);
    AriaJavaJNI.ArAction_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ArAction(String name) {
    this(AriaJavaJNI.new_ArAction__SWIG_1(name), true);
    AriaJavaJNI.ArAction_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean isActive() {
    return (getClass() == ArAction.class) ? AriaJavaJNI.ArAction_isActive(swigCPtr, this) : AriaJavaJNI.ArAction_isActiveSwigExplicitArAction(swigCPtr, this);
  }

  public void activate() {
    if (getClass() == ArAction.class) AriaJavaJNI.ArAction_activate(swigCPtr, this); else AriaJavaJNI.ArAction_activateSwigExplicitArAction(swigCPtr, this);
  }

  public void deactivate() {
    if (getClass() == ArAction.class) AriaJavaJNI.ArAction_deactivate(swigCPtr, this); else AriaJavaJNI.ArAction_deactivateSwigExplicitArAction(swigCPtr, this);
  }

  public ArActionDesired fire(ArActionDesired currentDesired) {
    long cPtr = AriaJavaJNI.ArAction_fire(swigCPtr, this, ArActionDesired.getCPtr(currentDesired), currentDesired);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public void setRobot(ArRobot robot) {
    if (getClass() == ArAction.class) AriaJavaJNI.ArAction_setRobot(swigCPtr, this, ArRobot.getCPtr(robot), robot); else AriaJavaJNI.ArAction_setRobotSwigExplicitArAction(swigCPtr, this, ArRobot.getCPtr(robot), robot);
  }

  public int getNumArgs() {
    return (getClass() == ArAction.class) ? AriaJavaJNI.ArAction_getNumArgs(swigCPtr, this) : AriaJavaJNI.ArAction_getNumArgsSwigExplicitArAction(swigCPtr, this);
  }

  public ArArg getArg(int number) {
    long cPtr = (getClass() == ArAction.class) ? AriaJavaJNI.ArAction_getArg(swigCPtr, this, number) : AriaJavaJNI.ArAction_getArgSwigExplicitArAction(swigCPtr, this, number);
    return (cPtr == 0) ? null : new ArArg(cPtr, false);
  }

  public String getName() {
    return (getClass() == ArAction.class) ? AriaJavaJNI.ArAction_getName(swigCPtr, this) : AriaJavaJNI.ArAction_getNameSwigExplicitArAction(swigCPtr, this);
  }

  public String getDescription() {
    return (getClass() == ArAction.class) ? AriaJavaJNI.ArAction_getDescription(swigCPtr, this) : AriaJavaJNI.ArAction_getDescriptionSwigExplicitArAction(swigCPtr, this);
  }

  public ArActionDesired getDesired() {
    long cPtr = (getClass() == ArAction.class) ? AriaJavaJNI.ArAction_getDesired__SWIG_0(swigCPtr, this) : AriaJavaJNI.ArAction_getDesiredSwigExplicitArAction__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public void log(boolean verbose) {
    if (getClass() == ArAction.class) AriaJavaJNI.ArAction_log__SWIG_0(swigCPtr, this, verbose); else AriaJavaJNI.ArAction_logSwigExplicitArAction__SWIG_0(swigCPtr, this, verbose);
  }

  public void log() {
    if (getClass() == ArAction.class) AriaJavaJNI.ArAction_log__SWIG_1(swigCPtr, this); else AriaJavaJNI.ArAction_logSwigExplicitArAction__SWIG_1(swigCPtr, this);
  }

  public ArRobot getRobot() {
    long cPtr = AriaJavaJNI.ArAction_getRobot(swigCPtr, this);
    return (cPtr == 0) ? null : new ArRobot(cPtr, false);
  }

  public static void setDefaultActivationState(boolean defaultActivationState) {
    AriaJavaJNI.ArAction_setDefaultActivationState(defaultActivationState);
  }

  public static boolean getDefaultActivationState() {
    return AriaJavaJNI.ArAction_getDefaultActivationState();
  }

  public void setActionRobot(ArRobot robot) {
    AriaJavaJNI.ArAction_setActionRobot(swigCPtr, this, ArRobot.getCPtr(robot), robot);
  }

}
