/*
Adept MobileRobots Robotics Interface for Applications (ARIA)
Copyright (C) 2004-2005 ActivMedia Robotics LLC
Copyright (C) 2006-2010 MobileRobots Inc.
Copyright (C) 2011-2014 Adept Technology

     This program is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

If you wish to redistribute ARIA under different terms, contact 
Adept MobileRobots for information about a commercial version of ARIA at 
robots@mobilerobots.com or 
Adept MobileRobots, 10 Columbia Drive, Amherst, NH 03031; +1-603-881-7960
*/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArLineSegment {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArLineSegment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArLineSegment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArLineSegment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArLineSegment(ArPose pose1, ArPose pose2) {
    this(AriaJavaJNI.new_ArLineSegment(ArPose.getCPtr(pose1), pose1, ArPose.getCPtr(pose2), pose2), true);
  }

  public void newEndPoints(double x1, double y1, double x2, double y2) {
    AriaJavaJNI.ArLineSegment_newEndPoints__SWIG_0(swigCPtr, this, x1, y1, x2, y2);
  }

  public void newEndPoints(ArPose pt1, ArPose pt2) {
    AriaJavaJNI.ArLineSegment_newEndPoints__SWIG_1(swigCPtr, this, ArPose.getCPtr(pt1), pt1, ArPose.getCPtr(pt2), pt2);
  }

  public ArPose getEndPoint1() {
    return new ArPose(AriaJavaJNI.ArLineSegment_getEndPoint1(swigCPtr, this), true);
  }

  public ArPose getEndPoint2() {
    return new ArPose(AriaJavaJNI.ArLineSegment_getEndPoint2(swigCPtr, this), true);
  }

  public boolean intersects(ArLine line, ArPose pose) {
    return AriaJavaJNI.ArLineSegment_intersects__SWIG_0(swigCPtr, this, ArLine.getCPtr(line), line, ArPose.getCPtr(pose), pose);
  }

  public boolean intersects(ArLineSegment line, ArPose pose) {
    return AriaJavaJNI.ArLineSegment_intersects__SWIG_1(swigCPtr, this, ArLineSegment.getCPtr(line), line, ArPose.getCPtr(pose), pose);
  }

  public boolean getPerpPoint(ArPose pose, ArPose perpPoint) {
    return AriaJavaJNI.ArLineSegment_getPerpPoint(swigCPtr, this, ArPose.getCPtr(pose), pose, ArPose.getCPtr(perpPoint), perpPoint);
  }

  public double getPerpDist(ArPose pose) {
    return AriaJavaJNI.ArLineSegment_getPerpDist(swigCPtr, this, ArPose.getCPtr(pose), pose);
  }

  public double getPerpSquaredDist(ArPose pose) {
    return AriaJavaJNI.ArLineSegment_getPerpSquaredDist(swigCPtr, this, ArPose.getCPtr(pose), pose);
  }

  public double getDistToLine(ArPose pose) {
    return AriaJavaJNI.ArLineSegment_getDistToLine(swigCPtr, this, ArPose.getCPtr(pose), pose);
  }

  public double getLengthOf() {
    return AriaJavaJNI.ArLineSegment_getLengthOf(swigCPtr, this);
  }

  public ArPose getMidPoint() {
    return new ArPose(AriaJavaJNI.ArLineSegment_getMidPoint(swigCPtr, this), true);
  }

  public double getX1() {
    return AriaJavaJNI.ArLineSegment_getX1(swigCPtr, this);
  }

  public double getY1() {
    return AriaJavaJNI.ArLineSegment_getY1(swigCPtr, this);
  }

  public double getX2() {
    return AriaJavaJNI.ArLineSegment_getX2(swigCPtr, this);
  }

  public double getY2() {
    return AriaJavaJNI.ArLineSegment_getY2(swigCPtr, this);
  }

  public double getA() {
    return AriaJavaJNI.ArLineSegment_getA(swigCPtr, this);
  }

  public double getB() {
    return AriaJavaJNI.ArLineSegment_getB(swigCPtr, this);
  }

  public double getC() {
    return AriaJavaJNI.ArLineSegment_getC(swigCPtr, this);
  }

  public boolean linePointIsInSegment(ArPose pose) {
    return AriaJavaJNI.ArLineSegment_linePointIsInSegment(swigCPtr, this, ArPose.getCPtr(pose), pose);
  }

  public ArLine getLine() {
    long cPtr = AriaJavaJNI.ArLineSegment_getLine(swigCPtr, this);
    return (cPtr == 0) ? null : new ArLine(cPtr, false);
  }

}
